### ISSUE TITLE
Add <num_banned_ips> tag for actionban/actionunban

### ISSUE THREAD

**Issue by selivan** [fail2ban/fail2ban#10]
I'v succesfuly integrated fail2ban with [Zabbix](http://zabbix.com) monitoring system. Each time actionban/actionunban happens, external script is called to pass parameters to Zabbix server. Different jails have different triggers in Zabbix, because I want to know not only from which ip attack happend, but also what service was attacked. actionban/actionunban doesn't know, for which jail it was called, so I need to write separate action scripts for each service. If &lt;jail&gt; tag will be added, single script for all actions may be used. If &lt;num_banned_ips&gt; tag will be added(I mean number of banned ips in current jail), external script with call to fail2ban-client will not necessary.

If this changes will be made, integrating with different monitoring services will be as easy as configuring mail warnings and may become out-of-the-box fail2ban ability. I can provide actions configuration, Zabbix template and how-to insruction for wiki.

**Comment by leeclemens** [comment]
Following the reference from #540, this issue is still sadly present. iptables-ipset needs bantime , but it is not defined as a parameter for action_ (and still isn't effective when passed in as `bantime="%(bantime)s"`).

**Comment by nuno-silva** [comment]
+1 for `<num_banned_ips>` :)

**Comment by sebres** [comment]
Revisited this... 
Looks pretty simple now, just calling map [ActionInfo.AI_DICT](https://github.com/fail2ban/fail2ban/blob/ca4da9d1d3f792562500182711abc149b2c741a1/fail2ban/server/actions.py#L376-L398) should be extended like here (can provide even more info):
```diff
			# raw ticket info:
			"raw-ticket":		lambda self: repr(self.__ticket)
+			# jail info:
+			"jail.banned":		lambda self: self.__jail.actions.__banManager.size(),
+			"jail.banned_tot":	lambda self: self.__jail.actions.__banManager.getBanTotal(),
+			"jail.found":		lambda self: self.__jail.filter.failManager.size(),
+			"jail.found_tot":	lambda self: self.__jail.filter.failManager.getFailTotal()
}
```
So the requested tag `<num_banned_ips>` would be either `<jail.banned>` (number of currently banned tickets) or `<jail.banned_tot>` (totally banned since fail2ban start), don't known which of both exactly is needed.

That's it... ought to write still some tests in favor of coverage.
