### ISSUE TITLE
Option to limit initial file scanning

### ISSUE THREAD

**Issue by morphles** [fail2ban/fail2ban#1016]
Parsing/scaning large log files is a bit problematic, say files >500MB take some time and CPU power to be parsed. Also modyfing log format to drop info and thus make file smaller just to run fail2ban does not sound optimal/desiarable. It would seem that very often, most of log file is not that relevant. Well at least in my use case, probably days worth of logging, at most, is what is relevant. Though I could even live with no "pre-scanning" of log file. So it would be nice if jail could define something like:
log_tail = <num>
If that is specified it should only look at <num> log lines on startup. Additionall alternative (though considerably more complicated to implement):
log_scan_only_last_min = <num>
If that is specified only, scan lines that have timestamps that are less than num minutes before now. Obviously scanning would need to happen backwards in such case.

Or at least option to disable "pre-scaning" miget even be enough. Though obviously this (well all mentioned options) should be on per jail basis.

**Comment by sebres** [comment]
Option `log_tail` is imho not required, because since v.0.9 the last offset of log file will be saved in database and after restart, f2b will parse file after this position only (if not new file).
Suggested option `log_scan_only_last_min` is indirect already included - it's `findtime`.

But current implementation of filter makes a full scan (to find a time `now` - `findtime`), if we have a new log file / initial state (new jail enabled). In addition it have a little bug (see https://github.com/fail2ban/fail2ban/issues/795#issuecomment-57732657).

I have developed a new algorithm (half-interval search) for very fast seek to `now-findtime` within my major branch #716 - see https://github.com/sebres/fail2ban/commit/53a30a2d42fa9cc114335cc7328651637f12162c and https://github.com/sebres/fail2ban/commit/c1637e97b2e210a6351e356aa351f9efe6109c3c
It can be cheery-picked into master branch together with bug fix above. 
@fail2ban/contributors should I do it?

**Comment by szepeviktor** [comment]
Called [binary search](http://en.wikipedia.org/wiki/Binary_search_algorithm).

**Comment by sebres** [comment]
@szepeviktor know-it-all :)
No, I know this under "half-interval search algorithm" - but see the first para inside your link...

**Comment by sebres** [comment]
Conclusion:
- use logrotate
- since database introduced, the last position of the log file (saved in database) will be used after restart of service (recognize logrotate etc. with checking of md5 of the first line in the log file)
- specify option "tail" after name of logfile in `jail.local` (for seek to end of file)
- specify not so large `findtime`, since 0.10 the log-line corresponding `findtime` will be found using fast search algorithm (from last saved position)
