### ISSUE TITLE
Config for lighttpd-fastcgi is missing in filter.d

### ISSUE THREAD

**Issue by langner** [fail2ban/fail2ban#1062]
Althought the jain for lighttpd-fastcgi is defined in `jail.conf`, there is no corresponding config file in `filter.d`.

This file seems to work fine:
http://www.buanzo.com.ar/files/lighttpd-fastcgi.conf
(from this blog post: http://blogs.buanzo.com.ar/2009/01/fail2ban-rules-for-lighttpd-fastcgi-alerts.html)

Any reason why it isn't included?

**Comment by langner** [comment]
Also reported in Ubuntu here: https://bugs.launchpad.net/ubuntu/+source/fail2ban/+bug/1374878

**Comment by buanzo** [comment]
Probably an error on my behalf.

**Comment by langner** [comment]
> Probably an error on my behalf.

I see. Will you fix it?

**Comment by leeclemens** [comment]
I do not see `lighttpd-fastcgi` defined as a jail in [jail.conf] (https://github.com/fail2ban/fail2ban/blob/8c4d4aa7fbcb6efb1853dc11720222c0a3aab4c9/config/jail.conf). Can you provide a link to the source code/line, version information?

The blog you referenced is over 6 years old and the `lighttpd-fastcgi` jail was renamed to `suhosin` in 2013.
 ```
ver. 0.8.11 (2013/11/13):
  Filter name changes:
   * 'lighttpd-fastcgi' filter has been renamed to 'suhosin'
```

Please let me know if I'm simply missing something, otherwise this seems invalid.

**Comment by buanzo** [comment]
Oh, excellent. Yes. I failed to remember that detail. Thank you Lee. I am
sure Karol will agree, as long as she is using >= 0.8.11

Good night.

**Comment by langner** [comment]
You guys are right. I had a very old version installed from an old Debian distro. Sorry for wasting your time.

P. S. I now installed 0.9 and it's great!
