### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by techpulse** [fail2ban/fail2ban#1079]
is it only me or does it use a lot of memory?

does it store the results in memory or something? i ban for 7200 seconds, and use it as nginx r/s limit banner.. it stores a couple thousand ip's

**Comment by leeclemens** [comment]
Please read http://www.fail2ban.org/wiki/index.php/HOWTO_Seek_Help so that people will be able to help assist you better.

If it does store IPs in memory and you need a "couple thousand" IPs stored in memory, that would be a couple KBs. Since "a lot of memory" is extremely subjective, it isn't really possible to assist you. Please use the above link.
