### ISSUE TITLE
RFC: Drop support of Python 2.6

### ISSUE THREAD

**Issue by leeclemens** [fail2ban/fail2ban#1106]
[PEP 361] (https://www.python.org/dev/peps/pep-0361/) states:
> With its release on October 29, 2013, all official support for Python 2.6 has ended.  Python 2.6 is no longer being maintained for any purpose.

From [Porting Python 2 Code to Python 3] (https://docs.python.org/3/howto/pyporting.html):
> But you should aim for only supporting Python 2.7. Python 2.6 is no longer supported and thus is not receiving bugfixes.

**Comment by leeclemens** [comment]
Regarding performance, efficiency with a common code base, [PEP 469 - migrating-from-python-3-to-the-common-subset-with-python-2-7] (http://legacy.python.org/dev/peps/pep-0469/#migrating-from-python-3-to-the-common-subset-with-python-2-7):
> Python 2.7 compatibility is often sufficient

**Comment by sebres** [comment]
I want to save support of 2.6 so long as possible (think about all weak hardware like routers etc., that will not get python 2.7). They are not so different with 2.7 (2.x and 3.x - absolutely yes, but not 2.6 and 2.7).
Doesn't matter to me, that 2.6 is no longer supported from maintainers and what any PEPs will say about that.
@fail2ban/developers The next developer, that agree with me, simply closes this ticket. :)

**Comment by leeclemens** [comment]
@sebres How many users run fail2ban on routers? Where Python 2.7 is not an option?

The difference between 2.6 and 2.7 boils down to being able to ultimately support Python 3 out of the same code base (at least without a lot of branching/performance impact - you like performance :) ). We claim to support Python 3 and we know that's where everything is heading...why not embrace it? Plus, if any low-level issue pops up in Python 2.6, we'll get no support from Python, it's simply not supported by anyone.

I created this Issue to open a discussion (RFC), so hopefully it's not just a '-2 vote and close' as suggested (Especially given some of the Issues I've seen lately that have been open for 2-3 years.)

**Comment by yarikoptic** [comment]
I am using fail2ban on few obscure pieces of hardware but they all have recentish debian so python is 2.7.  But I do see the point of maintaining compatibility with 2.6 unless we really run into a big problem causing us to drop its support... I haven't tried yet to support much of code natively between 2. and 3. so not sure what would be such a showstopper.  In one project which we drafted recently (http://github.com/duecredit/duecredit) we did run into some awkward issue I have now happily forgot which caused us to drop 2.6, although originally we did stay compatible with both 2.6, 2.7 and 3.2, 3.3 .

**Comment by yarikoptic** [comment]
I would recommend starting work on conversion, having 2.7 as the primary target in mind while keeping testing running against 2.6... so whenever we run into a specific issue of 2.6 incompatibility, then we would review again.  How does that sound for a plan? ;)

**Comment by sebres** [comment]
<blockquote>Where Python 2.7 is not an option?</blockquote> Nope, unfortunately not everywhere, because of core of python 2.7 self, cpu model, ram etc. as constraint. But I should think a little bit about pypy as replacement...

<blockquote>you like performance</blockquote>we can make it's with good performance with another things, without loss of support for 2.6 :) And when we talk about performance, we should definitely change to pypy. Let us go away from c-python. Viva pypy at all! :)

<blockquote>2-3 years</blockquote> I like it :)

**Comment by sebres** [comment]
I'm with @yarikoptic and as already said, so long we will support 2.7 - 2.6 is not a problem (PEP or not PEP).

By the way, I don't like and can't stand by such thing as PEP (to be compliant only). For example, I have a very great pleasure to merge all this PEP compliant changes, you made last time. And that in all my branches and pull request, that are not small (such as ban-time-incr - conflicts without end).

**Comment by leeclemens** [comment]
I've been working on the conversion, which is what brought up the question :) Dismissing that Python 2.6 was EOL'd (almost 2 years ago) seems illogical to me, and frankly is pretty frustrating. Holding back any other progress until we discover an issue we can't solve isn't a really good reason to retain supporting something EOL'd either, IMHO.

I have asked for specific information, but only got obscure responses. What routers are running fail2ban that cannot use python 2.7? How many? When it comes to continuing to support 2.6, what users are we looking at? How many? Percentage? Can you provide specifics around the CPU and RAM incompatibilities between 2.6 and 2.7 (honestly pretty interested in that, I hadn't heard of it being an issue) you referenced?

The performance reference I made was directly pertaining to the dict usage/conversion I linked. Can you speak to that?

You may like issues being open for 2-3 years...personally and professionally, I'd rather resolve issues before they stay open that long.

I'm not sure if it's a language (English, not Python) issue; I have made a number of PEP8 changes recently, do you believe they were not valuable (simply because they change the code to conform to PEP8)? You said you "don't like and can't stand" PEP changes, but also that you took "great pleasure to merge ... PEP compliant changes" - which seem like contradictory statements...I'm just trying to make sure I understand.

**Comment by yarikoptic** [comment]
1. for me personal showstopper would be the fact that Debian squeeze (LTS) comes with 2.6.6-3+squeeze7 and I still do have few servers running it.  Others already stated that CentOS 6.6 also comes with 2.6
2. even if 99.9% of users use >=2.7, 0.1% of others might constitute thousands (fail2ban installed on ~10% of Debian installations, there is 15946 squeeze installations according to http://popcon.debian.org/ , so probably there is around 1,500 fail2ban installations on squeeze with 2.6) -- not sure that would be an insignificant number to piss of for now good reason.  There is no reliable statistic otherwise to give you a better idea of how many people use fail2ban with 2.6 ... not all of them need to migrate/up to a new version, but that would be a separate discussion, ok?
3. I do not see yet any specific "progress" aspect which requires dropping 2.6.  May be there could be low-pain workarounds with 'six' module or custom constructs when we run into a specific case -- but, again, lets get there first, ok?  Performance wise, again, we have (unfortunately) no analysis of tight points in the code, so "optimization" of pieces of code which do not really contribute to run time load is of minor benefit imho.
4. Thanks for cleaning up the pull of issues, it helps, but unrelated here
5. PEP/merges -- code "purification" is always a neat thing to do, but often costs hours to those whose pull requests linger (for one reason or another) without merge for a while.  They complicate also retrospection and adoption of "perspective" feature branches (e.g. all those with IPv6 support ideas).  So such changes should indeed be carried out with a due appreciation and caution (e.g. like those suggestions to move entire code base to indentation with spaces -- too late now, unless we resolve all pull requests "positively" first).   Otherwise, let's stop that line of discussion since it is unrelated to this specific question.

My executive (khe khe) summary would be -- let's maintain 2.6 compatibility as long as we can without major blood, e.g. until there is a clear demonstration that we would acquire SIGNIFICANT benefit from dropping it ;)

**Comment by leeclemens** [comment]
Thank you for the robust response (Ironically, I didn't disagree with anything you said previously.). You actually referred to my plan, which is how I came upon creating this Issue (to start the 'discussion' vs a specific limitation...although I believe I did link a specific performance related concern (copy vs iterator)).

1. I'm not sure who the "others" are, no other occurrence of "centos" exists in this Issue. But yes, CentOS comes with 2.6. It's also not hard to install Python 2.7 or Python 3 (on Debian or CentOS). I'm actually pleasantly surprised you're giving CentOS some love :)  I admit I develop for systems I manage, so handling the more vague issue of supporting some user I know nothing about is more complicated and foreign to me. That's perhaps part of the reason you should offer the executive summary I was hoping for :)
2. I'm not sure where ~10% comes from, but fair enough. Just for fun, Windows XP market share is [~12%] (http://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0) but was EOL'd in [4/2014] (https://www.microsoft.com/en-us/WindowsForBusiness/end-of-xp-support). Great for virus/malware, but who wants to support EOL'd software, let alone an EOL'd language or even OS? Point taken, but I didn't EOL Python 2.6.
3. I believe my links are specific, as starters. No one has commented directly about them yet (except that we shouldn't care that Python 2.6 is EOL'd or about any PEPs related to it). I believe a copy of a list is more expensive to create than an iterator, and 2to3 converts them inefficiently in some circumstances. As you mention, I have not (nor claimed to have) run an extensive profile to determine the impact of those copy vs iterator changes - but it seems there could be a performance impact (I know, I know...[premature optimization] (http://c2.com/cgi/wiki?PrematureOptimization)).
4. My pleasure...I only mentioned it here as a direct response to a previous comment. (Responding directly to comments other people make tends to lead to productive discussions, imho. Especially when compared to making random or unrelated statements and ignoring what another person says.)
5. If implementing a few simple [PEP8] (https://github.com/fail2ban/fail2ban/issues/876) fixes cost hours of work to merge (actually I intentionally started with simple changes that should have been automatically merge-able), think of all the time that could be saved if all of the code was PEP8 compliant *and* new pulls were PEP8 compliant :)  I think design not coming before development is the real hold-back for the various IPv6 branches. However, unrelated indeed; ftr I didn't bring it up :/

I'll reopen if I feel SIGNIFICANT benefit exists; until then I'll keep on keepin' on.


P.S. Hadn't seen the popcorn graph in a while...any idea what that ~2,000 drop off is between 6/21-6/28? That's more than your estimated Python 2.6-reliant user base :) (I'm not trying to be a jerk...is there an emoji for that?)

**Comment by yarikoptic** [comment]
just for completeness ;-)
2. ~10% comes from the same debian popcon:  https://qa.debian.org/popcon-graph.php?packages=fail2ban&show_installed=on&show_vote=on&show_old=on&show_recent=on&show_nofiles=on&want_percent=on&want_ticks=on&from_date=&to_date=&hlght_date=&date_fmt=%25Y-%25m&beenhere=1
3. EOLed upstream product might still be maintained (with exhaustive security patching) by downstream distributions.  So as long as those distribution releases are not EOLed, that version might still be kicking around .  And btw -- we can use generators already ;-) 
5. Fail2Ban has quite a bit (or actually A LOT) of legacy.  I believe I have started contributing to it when we were learning new features of python 2.3, and pep8 wasn't yet treated as a bible ;-)  With legacy and such age lots of crafty code/constructs sneak in and ruin its beauty... but with legacy comes responsibility, and I could take some blame for not adhering to PEP8 earlier, when it would have been easier (no git, no contributors).  But also I would advise to listen to PEP8's father at recent pycon15: https://www.youtube.com/watch?v=wf-BqAjZb8M

P.S. popcon drop -- indeed, looks a bit abnormal.    Note that % of fail2ban installations kept growing regardless ;) and usually popcon drops slightly every summer (damn people turn off their laptops when going to vacations).  Also I see increasing at least for NeuroDebian: http://neuro.debian.net/popularity.html#popularity-contest (there was also a dive recently -- may be related).  Anyways -- I wouldn't get alarmed.  Most of the time it is the % which matters ;)

**Comment by sebres** [comment]
@leeclemens "great pleasure to merge" was sarcasm.

**Comment by leeclemens** [comment]
@sebres sarcasm doesn't read very well on the Internet...I'd suggest using /s or some other notation.
