### ISSUE TITLE
I'd like to see a rule blocking ssh attempts that fail to negotiate a key exchange

### ISSUE THREAD

**Issue by bjmgeek** [fail2ban/fail2ban#1117]
I followed the recommendations at https://stribika.github.io/2015/01/04/secure-secure-shell.html and now I see lots of inbound connection attempts that never even make it to login attempts, because the client is using ssh connection parameters that are not compatible.  Therefore, my logs are full of such connection attempts.

Here's some example lines:

```
Jul 16 01:19:55 bminton sshd[22440]: Connection from 43.229.53.67 port 39678 on 192.168.1.9 port 22
Jul 16 01:20:00 bminton sshd[22440]: fatal: Unable to negotiate a key exchange method [preauth]
```

I'd like to request the sshd filter have that line added.

thanks

**Comment by emkael** [comment]
If it's any help, OpenSSH since v7.0 generates this error as:
```
fatal: Unable to negotiate with <HOST>: no matching key exchange method found. Their offer: (...) [preauth]
```

So the matching failregex would be something in lines of:
`^%(__prefix_line)sfatal\: Unable to negotiate with <HOST>.*\[preauth\]$`
Note that it's a broader match than just your KEX error, but your hardened configuration will also fail with similar error messages for negotiation of MACs or host key types, for example.

**Comment by mo0nsniper** [comment]
Yes, I'm also having this problem after hardening SSH configuration. 
Maybe this can be included to fail2ban.

**Comment by sebres** [comment]
IMHO "no matching key exchange method found" is not really an authentication failure (that does not take place), but would be good candidate for sshd-aggressive jail... (link #1209)
