### ISSUE TITLE
don't re-email after reboot

### ISSUE THREAD

**Issue by jepio** [fail2ban/fail2ban#1141]
I'm using fail2ban on my ssh server, with the iptables, complain and mail-whois actions. After a reboot all the previous bans get reapplied (definitely good, because they're permanent bans), but fail2ban insists on re-emailing me and the abuse emails. 

I get why it's doing this, but is there a way to prevent this? When googling for "fail2ban persistent bans across reboot" I saw mention of some form of database, but in my case it's just rescanning the log and reapplying all the rules, I don't see any form of memory

**Comment by yarikoptic** [comment]
On Wed, 29 Jul 2015, jepio wrote:

>    I'm using fail2ban on my ssh server, with the iptables, complain and
>    mail-whois actions. After a reboot all the previous bans get reapplied
>    (definitely good, because they're permanent bans), but fail2ban insists on
>    re-emailing me and the abuse emails.

>    I get why it's doing, this but is there a way to prevent this? When
>    googling for "fail2ban persistent bans across reboot" I saw mention of
>    some form of database, but in my case it's just rescanning the log and
>    reapplying all the rules, I don't see any form of memory

which version of fail2ban are you using???

**Comment by jepio** [comment]
0.9.2

**Comment by sebres** [comment]
I think, the last version will do it also, because all of "active" (not expired) bans go banned "again" after restoring from db, and all of actions, including emails also, will be executed again.

**Comment by jepio** [comment]
On Wed, 29 Jul 2015, Serg G. Brester wrote:

> 
> I think, the last version will do it also, because all of "active" (not 
> expired) bans go banned "again" after restoring from db, and all of 
> actions, including emails also, will be executed again.
> 

Is there a way to check from within an action if it's being triggered from 
the db or from the log? That way I could return early and not execute the 
action. Sort of like a "run-once" mode.

**Comment by sebres** [comment]
The problem is currently a banning is action also, and fail2ban makes no difference between all of actions - so each action will be executed by banning of IP (ex.: ban - iptables, mail, anythingelse, etc.)

The solution would be:
* an optional parameter in action (like `exec_for_restored_ban=off`), that will prevent executing it for restored ban (comming from db).
* or just extending notifying (mail, etc.) into separate processing, for example that will send exact one mail with summary and list of all bans after some latency (have partially already realized it in one of my branches, similar issue resp. solution discussed in https://github.com/fail2ban/fail2ban/issues/832#issuecomment-60483697).

**Comment by yarikoptic** [comment]
On Wed, 29 Jul 2015, Serg G. Brester wrote:
>    The problem is currently a banning is action also, and fail2ban makes no
>    difference between all of actions - so each action will be executed by
>    banning of IP (ex.: ban - iptables, mail, anythingelse, etc.)

>    The solution would be:

>      * an optional parameter in action (like exec_for_restored_ban=off), that
>        will prevent executing it for restored ban (comming from db).

may be more of "exec_once" and some DB support for that, i.e. marking
per each ticket/ban every action ever executed, expiring those
entries together with tickets?

**Comment by sebres** [comment]
I have already a functionality for recognition of restored ticket, see https://github.com/fail2ban/fail2ban/pull/716/files#diff-56e72e6e68a9901de2da13ebe5b2545cR308 for example.

**Comment by szepeviktor** [comment]
Duplicate: https://github.com/fail2ban/fail2ban/issues/921

**Comment by kekh** [comment]
Hi,

Same problem here, like many people I guess :-/

So to work around this annoying situation I use some silly "grace period" strategy this way:

1. Define a time period in minutes, in which you decide that no emails will be sent. That should be at least the time Fail2Ban is taking to start and restore all bans.
2. Find [a script](https://github.com/kekh/Fail2Ban-Tweaks/blob/master/gracetime) or whatever command which tell you since how much time the system and/or Fail2Ban is started.
3. Modify your [MTA action.d](https://gist.github.com/kekh/bc26e919fcd338cc4918) file to take in account this new strategy, and only executing the Whois&Mail stuff if the system and/or Fail2Ban started for long enough (your time period defined in 1.)

Still looking for a real solution...

**Comment by szepeviktor** [comment]
@yarikoptic Would it be possible to implement this?

**Comment by hansdg1** [comment]
I am also having this issue on 0.9.4

**Comment by szepeviktor** [comment]
I think you have to wait for 0.10

**Comment by sebres** [comment]
As already said I've already back-ported the functionality with "restored" flag from my favorite branch.

Today I had a free minute to "fix" this issue. 
And just to make clear: I don't feel like for implementing of it in 0.9 (I'll shelve the development of 0.9 in the future). 

When the maintainers are so slow, that's not my fault.
