### ISSUE TITLE
Recommendation for log errors

### ISSUE THREAD

**Issue by AlexanderSk** [fail2ban/fail2ban#1160]
Hello,

I recently setup a new server and noticed many things for a brand new fail2ban setup. One of these is that in the case a rule does not find the correct log or it doesn't exists an error like the following is created:
ERROR  create fail2ban-xxx timeout 600

Do i believe it would be more proper to check if the logs exists and if not not to forward the rule into the firewall and display a relative error about the log file not found.

**Comment by sebres** [comment]
Well, I don't like a solution you have suggested, just because if someone makes a typo, that will be never recognized and the jail goes idle without any error.
Default all of jails are disabled and you should enable (in jails.local) only jails for services you are really used.

**Comment by AlexanderSk** [comment]
Hello, i think you did not exactly understand my point.

Please allow me to explain better.

Current fail2ban case: 
If a log typo is made the rule is executed and the error appears in the log but the fail2ban rule appears running in the fail2ban-client status so everything is ok right? Well yes according to your logic though this rule will Never catch an intruder and some admin might think the rule is ok only to find our much latter that is not perhaps after the server is hacked.

What i  proposed:
When the rule is executed a log file check will be made and if the log file is not found then: 
A) a rule like" Log file not found for rule xxx"
B) Do not forward the rule to the iptalbes (or any other) firewall since there is no point doing that...

What do you think?
Alexander.

**Comment by sebres** [comment]
The "firewall rules" you mean are `actionstart` and `actionend` and will be executed if jail will be started resp. stopped.
At the moment after recognition the log file does not exists will set a jail to idle.
The currently logic of idle jail does not remove firewall rules, because some IP adresses may be already banned (jail goes idle after unfortunate log-rotate or someone will set it manually to idle).

The easy solution for '(B)' would be to execute `actionstart` implicit before a first ban. 
But we can have more as one action and `actionstart` will be use not for firewall only.
I will think about.

Secondly, I don't understand why some jail should be enabled for a service (for log file) that does not exists.

**Comment by AlexanderSk** [comment]
Hello thank you for the explanation.
Regarding "Secondly, I don't understand why some jail should be enabled for a service (for log file) that does not exists." I am only referring to the case an admin makes a typo for example in centos  the httpd is /var/log/httpd/access_log on some other OSes are access.log. It is not too difficult to get confused.

Regarding the idle rule if i remember correctly it can be sees with the command fail2ban-client rulename right? 
Could we somehow print the idles in fail2ban-client status like rule fb2-httpd,f2b-rulename-IDLE,etc... ? Just asking :)
