### ISSUE TITLE
Fail2Ban & BadIPs Configuration?

### ISSUE THREAD

**Issue by MichaelCropper** [fail2ban/fail2ban#1192]
Implemented Fail2Ban successfully (I think..) and want to see data using BadIPs as outlined here, https://www.netmess.org/examine-your-attackers/, recommended from, http://www.fail2ban.org/wiki/index.php/HOWTOs which states that you simply need to add the following code;

wget -q -O /dev/null www.badips.com/add/<name>/<ip>

to the "/etc/fail2ban/action.d/iptables-multiport.conf" file as outlined here, https://www.badips.com/snippets

Problem being that when doing this on Fail2Ban V. 0.9.3, an error message appears when using the command "fail2ban-client reload" of "Error in action definition iptables-multiport[name=sshd...... etc"

Is there something not configured correctly which would cause this problem? Or is this a genuine error on the latest version when wanting to graph data with BadIPs?

**Comment by sebres** [comment]
`Error in action definition iptables-multiport[name=sshd......` etc?
Just that "etc" is interesting...

Since fail2ban supported multiple actions, it is not necessary to modify any action configuration.
Additionally, a default action to work with badips.com already exists, so you should be able to configure it without customizing of any action configuration. See https://github.com/fail2ban/fail2ban/blob/master/config/jail.conf#L191

Just add badips action to your `jail.local` for needed jails or even for `DEFAULT` and it should work out of the box.

**Comment by MichaelCropper** [comment]
Looks like the guide I was working towards is a bit out of date then. I can see the default action within the jail.local file which contains the uncommented line;

action_badips = badips.py[category="%(name)s", banaction="%(banaction)s"]

This being the case. Why would it be that when running the following command in SSH;

wget -q -O - http://www.badips.com/get/key

that a key isn't generated which can then be used to view data on BadIPs.com as outlined here, https://www.netmess.org/examine-your-attackers/?

**Comment by jamesarmitage** [comment]
Try submitting an IP manually.  I had the same issue, until I ran:

`wget https://www.badips.com/get/key`

and got this repsonse:
`{"err":"we could not find you in reporter DB, maybe you never reported an IP?","suc":""}`

After I manually submitted one attempt:
`wget https://www.badips.com/add/ssh/12.34.56.78`

I was able to rerun the `wget -q -O - http://www.badips.com/get/key` and it worked.
