### ISSUE TITLE
init/service script should install, too

### ISSUE THREAD

**Issue by yoosefi** [fail2ban/fail2ban#1193]
I replaced my dist version of fail2ban with the current tarball version, but running setup.py didn't copy the init script over. Scratched my head for a bit but figured out that the init script was in the `files` directory.

I copied that to my `init.d` directory and now I have fail2ban as a service again.

Could this be included for the install process?

**Comment by yarikoptic** [comment]
unlikely since it is platform/release dependent and there is no overreaching python library providing support for e.g. installing init scripts "properly" across them (thus for now will mark as wontfix and close, but if anyone chimes in with "I will do it", I would not mind ;)).   I guess we could for few based on platform.dist() output but not sure if we would want to mess with it.
Generally myself I am just using packaged (Debian) version

**Comment by yoosefi** [comment]
Ok. Would still be helpful to mention in the README, though.

**Comment by yarikoptic** [comment]
Sure, PR? :-)

**Comment by yoosefi** [comment]
Sent
