### ISSUE TITLE
recidive not correct/accurate when fail2ban restarts multiple times during findtime period

### ISSUE THREAD

**Issue by RhysMcW** [fail2ban/fail2ban#1210]
If you enable the recidive jail and your fail2ban is restarted enough times during the findtime duration then the recidive chain gets quite large due to the filter matching IPs maxretry occurrences in the fail2ban.log, purely because fail2ban restarted and banned the IPs in the persistent database again, as it should, but thus creating multiple ban entries that the recidive filter relies on.

Would it be possible to add a string, like "persistent banning", to the log entry when fail2ban starts and processes it persistent database to re-ban IPs, and then add that same string to the ignoreregex field in the recidive filter?
That way the filter should ignore any ban log entries that are due to the persistent banning and therefore be more correct/accurate even if fail2ban is restarted multiple times during the findtime period...

**Comment by sebres** [comment]
BTW: in #716 I have realized a flag `restored` for banned ticket, that was restored after restart of fail2ban. 
Changing of log message for such bans to something like "Ban restored <HOST> ...", that the recidive jail regexp will not match, will solve this issue.

**Comment by RhysMcW** [comment]
Hi Serg,
I've read through 716 and not sure if I follow correctly.
I gather this has been implemented in a release but it's not in 0.9.2 ? I'm running 0.9.2 installed from from the EPEL repos using yum...
If it is implemented in 0.9.3 then I'll probably download the tar-ball is it would be nice to use...
Am i correct or do I just need to add/change some config somewhere?

**Comment by sebres** [comment]
It was planned, but was not released with 0.9.3.
There are complications with regard to the unity of developers about this PR (716). 
As long as it is my own main branch.
In comment above I meant, how this kind of error can be simply fixed (and was already fixed in 716).

But of course, if you will use #716, you can certainly do it. Just save your old configs (and fail2ban-sqlite database) uninstall org-f2b and install 716 from archive. Hereafter enable increment in config jail.local.
You can any time switch back to original fail2ban, but before you install it, you should remove fail2ban-sqlite database operated with 716 (or restore from your backup), because it is incomatible with mainstream and does not downgrade.

**Comment by sebres** [comment]
I'll close it, because was fixed a long time ago within 0.10 branch. 
The ban will be restored with log entry `[<jail>] Restore Ban <ip>`, so this way not affects recidive jail (because does not match).
