### ISSUE TITLE
Specific banaction in jail.conf overides default in jail.local

### ISSUE THREAD

**Issue by stewardle** [fail2ban/fail2ban#1216]
Where banaction for specific jails (eg pam-generic) is defined in jail.conf it must be redefined for those jails in jail.local.
I expected the default banaction in jail.local to take precedence.

**Comment by sebres** [comment]
It's not a bug - is a feature :) 
So works config reader mechanism, that the *.local completely overwrites all of *.conf, but read of defaults occurs in each file separately, before it will be merged together, so the defaults are not interested after each file was read.

If this logic will be changed, other things can be broken.
I need some info to think about - can you provide your situation as example?

**Comment by stewardle** [comment]
On Fri, 09 Oct 2015 03:50:00 -0700
"Serg G. Brester" <notifications@github.com> wrote:

> It's not a bug - is a feature :) 
> So works config reader mechanism, that the *.local completely overwrites all of *.conf, but read of defaults occurs in each file separately, before it will be merged together, so the defaults are not interested after each file was read.
> 
> If this logic will be changed, other things can be broken.
> I need some info to think about - can you provide your situation as example?
> 

I'd updated fail2ban from 8.10 to 9.3 on Mac OS X.

In action.d have a modified version of pf.conf to use Murus firewall anchors.

In jail.local banaction was only specified for default and jail recidive:
	[DEFAULT]
	...
	banaction = pf-murus
	...
	[pam-generic]
	enabled  = true
	action = %(action_mw)s
	logpath  = /var/log/system.log

	[postfix-sasl]
	...
	[recidive]
	enabled  = true
	banaction = pf-murus[pftable=recidive]
	...

On starting fail2ban it tries to use banaction = iptables-multiport for jail pam-generic.

Easily fixed in jail.local
	[pam-generic]
	enabled  = true
	banaction = pf-murus

But I did not expect to have to redefine banaction for pam-generic after setting default.

Steve

**Comment by sebres** [comment]
Can you additionaly provide a dump output of
```bash
fail2ban-client -vvd
```

**Comment by stewardle** [comment]
Attached fail2ban-client dumps and jail.local for current (working) and original configurations and jail.conf (which is as installed).

**Comment by sebres** [comment]
Attached where?

**Comment by stewardle** [comment]
Attached to email I sent but not showing here. Tried via web but kept getting 
"Unfortunately, we don’t support that file type" or "Something went really wrong and we can't process that file" with or without .txt suffix.
Trying dropbox:
https://dl.dropboxusercontent.com/u/70478183/fail2ban-client-vvd-current
https://dl.dropboxusercontent.com/u/70478183/fail2ban-client-vvd-original
https://dl.dropboxusercontent.com/u/70478183/jail.local-current
https://dl.dropboxusercontent.com/u/70478183/jail.local-original
https://dl.dropboxusercontent.com/u/70478183/jail.conf

**Comment by sebres** [comment]
> On starting fail2ban it tries to use banaction = iptables-multiport for jail pam-generic.

You're probably wrong?
I mean the banaction for pam-generic is possibly `iptables-allports`?
Because of default value for jail `pam-generic` in jail.conf:
https://github.com/fail2ban/fail2ban/blob/master/config/jail.conf#L719

Then it works as expected and not a bug, but unfavourable for some platforms such as yours.

@fail2ban/contributors should we really define `banaction` for some jails in jail.conf? Or should we make it platform independent?

**Comment by smwardle** [comment]
Sorry - yes - iptables-allports

**Comment by sebres** [comment]
Yes, the problem is that in `jail.conf` for some jails (inclusively `pam-generic`) the `banaction` is predefined directly in jail (not in default), so no matter which `banaction` you will specify in `[DEFAULT]` (irrespective of jail.conf, jail.local or in some includes), because that directly set in jail will win always.

The solely way to go away this, would be to move a such `banaction` into `[DEFAULT]` as subst variable and use that in jail, something like:
```
[DEFAULT]
banaction = iptables-multiport
banaction_allports = iptables-allports
...
[pam-generic]
# pam-generic filter can be customized to monitor specific subset of 'tty's
banaction = %(banaction_allports)s
logpath  = %(syslog_authpriv)s
```
And to redefine both (banaction and banaction_allports) in your `jail.local`

**Comment by smwardle** [comment]
That looks like a good solution.
Also for recidive should also be changed to
banaction = %(banaction_allports)s

**Comment by stewardle** [comment]
Thanks.
