### ISSUE TITLE
Re-ban aggressive attackers

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1224]
Would it be possible to examine iptables counters at unban-time and re-ban if counter is non-zero?
Then reset the counter for the next week (recidive)

**Comment by sebres** [comment]
We have already two solution to ban aggressive attackers:
- recidive jail/filter (not very good, because parses f2b own log, misfired sometimes after rotate of it, does not taken failures into account, etc).
- #716 (imho, much better as recidive, for example beside bans also considers failures count, but still not accepted);

Therefore I don't know why this third solution may be better.
Reopen it if I'm wrong.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
@sebres Do you see any chance that ban-time-increase will land in Fail2ban?

**Comment by szepeviktor** [comment]
BTW iptables counters give information in a protected status, for recidive to trigger a new attack attempt should be made.

**Comment by sebres** [comment]
I know what is iptables counters, but I don't believe this way should be used to recognize recidives. Maybe, but too hazardous: attempts during ban time are not directly failures, so in case of the mistake (banning of good IP-address) that has few chances to correct the situation, because each attempt during ban time (also with changed correct login data) makes it more and more recidive - so will prolong its ban time, etc.
