### ISSUE TITLE
Whitelist outside jail.conf

### ISSUE THREAD

**Issue by binarykitchen** [fail2ban/fail2ban#123]
Hi there

Would be great if I can maintain a whitelist outside of jail.conf. For two reasons: a) I have a very long list of IP addresses, the `ignoreip` entry would become too long. b) I want to share the same whitelist for other programs like spamassassin (less redundancy).

Thanks,
Michael

**Comment by spacecwoboy** [comment]
I'm interested in seeing a simple, working example of how to incorporate an external file to the ignoreip whitelist.  I've read the howto/READ.me, but didnt quite get the best grip of it.

Let's say I start with this:
- [x] The whitelist of IP Addresses /etc/fail2ban/jail.d/list_of_ipaddresses_to_Whitelist.txt
* 127.0.0.1/32
* some.domainname.us
* 192.168.0.0/16

I need to understand:
- [ ] Other configs required to reference "/etc/fail2ban/jail.d/list_of_ipaddresses_to_Whitelist.txt"

**Comment by jult** [comment]
Yes, me too. How does this work? I have a global list, already in use for other machines and services, it's on the server where fail2ban resides, so it can be referenced using something like
allow-file=/path/dir/ip_ignoredallowed_list
As you seem to have closed this, it should be in config somewhere, but it totally is not.

Perhaps you can copy the code for this from CSF/LFD, who do this exact thing very well. You can even have it autoreload a global remote file for it from a URL.

**Comment by sebres** [comment]
It is currently not possible via "list_of_ipaddresses_to_whitelist.txt" in plain text form. 
But via separated python-config in form of `ignoreip = comma-, or space-separated list of IPs resp. DNS`.
#### file jail.local
```
[INCLUDES]

before = %(known/before)s
              list_of_ipaddresses_to_whitelist.conf
```
#### file list_of_ipaddresses_to_whitelist.conf
```
[DEFAULT]
ignoreip = 127.0.0.1/32 some.domainname.us 192.168.0.0/16

[sshd]
ignoreip = %(known/ignoreip)s another.domainname.us
```

Corresponding of the source code (function `splitwords` used for this), you can use newline+space as separator (Note **at least one space is expected after new-line**, because of the standard syntax of python config-file):
#### file list_of_ipaddresses_to_whitelist.conf (using newline+space)
```
[DEFAULT]
ignoreip = 127.0.0.1/32
 some.domainname.us
 192.168.0.0/16
 ...
```

Also note: extending of this "list" does not affect until fail2ban will be reloaded (resp. restarted in v.0.9).

**Comment by jult** [comment]
How is this (a python config syntax for a whitelist) progress in any way or form? This puts the user back ~20 years, reminiscent of sendmail files and similar.
I think I'll move to [CSF/LFD](https://configserver.com/cp/csf.html) completely, as far as I can tell LFD can do all fail2ban can, and more. Plus it handles plaintext IP-lists, as mentioned above, with a wide range of accepted syntaxes.

**Comment by sebres** [comment]
> I think I'll move to CSF/LFD completely...

You can use the software you want... 

Back to the issue, I don't see it currently as task with heighest prio in the priority-list, sorry.

**Comment by mikeg-de** [comment]
Searching for a solution which was requested here. The scenario is simple:

1. CDN makes a lot of legit requests which are banned
2. CDN IP's do frequently change
3. Using i.e. the AWS CloudFront an [SNS topic](https://aws.amazon.com/blogs/aws/subscribe-to-aws-public-ip-address-changes-via-amazon-sns/) could be subscribed to to generate a file

Integrating fail2ban with AWS WAF or EC2 Security Groups may be others options. Though, the first can come with a heavy price tag due to too many rules and the later is quite sophisticated to been implemented.

Having a file which could be referenced is much more straight forward and efficient.

**Comment by sebres** [comment]
> Using i.e. the AWS CloudFront an SNS topic could be subscribed to to generate a file

And which profit it could theoretically make? 
Shortly: the IP produces a failure, you would verify the IP against SNS-list, and find 3 related IPs that are known by fail2ban as bad (e. g. were already banned previously).
Then what should happen? The current IP will be banned longer? But as you said "IP's do frequently change"...

One option would be to begin a ban earlier (e. g. by first failed attempt), so the IP does not reach `maxretry` (normally 3) and banned quasi immediately.
Another would be to ban preventive (for example periodical pull this SNS-list and reban all the IPs from the list, like "switch" `old IP` to `new IP`).
Just it depends (and is a bit ugly in my opinion).

First option would be more conceivable and can be relatively simple implemented within 0.11th observer as a kind of "plugin" affected on failure found event to check and increase attempts for such "bad" IPs (to do the ban earlier up to immediately).
For example in my own fail2ban build (not yet public 0.11th continuation) I have similar "plugin" doing that based on GeoIP data.

> Integrating fail2ban with AWS WAF or EC2 Security Groups may be others options. 

Well one could already now implement many scenarios (e. g. using own actions) to do such integration.
Especially if something like #2304 gets implemented (or if I'll provide my "plugin-API" enhancements for 0.11).

**Comment by sebres** [comment]
Oh... may be I was confused as regards the searching solution (at least I could read the subject :smile:).
So the comment above describes more the blacklisting of some "bad" intruders often changing IPs.

For the whitelisting of own IPs (in order to ignore them) it could be implemented pretty simply: write your own script validating this SBS-list (or whatever AWS could provide). And add this into `jail.local` for default or jails sections you need:
```ini
[DEFAULT]
ignorecommand = /path/to/command <ip>
```
The IP is whitelisted if command exits with code 0.
Also note #2176 (since 0.10.4) which allows you to implement caching of `ignorecommand` for some time (reduces the load and improves performance of fail2ban).

**Comment by srulikuk** [comment]
Hi @sebres I tried the following but get an error on reload

> ```
> [INCLUDES]
> 
> before = %(known/before)s
>               list_of_ipaddresses_to_whitelist.conf
> ```
> 

fail2ban-client reload
2020-03-27 08:40:36,907 fail2ban                [12337]: ERROR   Failed during configuration: Bad value substitution:
	section: [INCLUDES]
	option : before
	key    : known/before
	rawval : 
whitelist.local

Fail2Ban v0.10.5
any ideas?

**Comment by srulikuk** [comment]
Resolved. in jail.local i put 
```
[INCLUDES]
before = whitelist.local
[DEFAULT]
ignoreip = %(ignoreip)s
```
and the whitelist.local is as described above
[DEFAULT]
ignoreip = 127.0.0.1/32
 192.168.1.1/32
 10.8.0.0/32
