### ISSUE TITLE
Nginx path log

### ISSUE THREAD

**Issue by gagomap** [fail2ban/fail2ban#1237]
In paths-common.conf, i just see:
```bash
27	nginx_error_log = /var/log/nginx/error.log
28	
29	nginx_access_log = /var/log/nginx/access.log
```
But i am using EasyEngine (Rtcamp), path to nginx log will include:
```bash
/var/log/nginx/access.log
/var/log/nginx/error.log
```
And:
```bash
/var/log/nginx/mysite.com.access.log
/var/log/nginx/mysite.com.error.log
```
for every sites host on my VPS.

I think you should change nginx log path to:
```bash
/var/log/nginx/*access.log
/var/log/nginx/*error.log
```

// I'm sorry for my English :D

**Comment by sebres** [comment]
Thanks for this proposal.

There are the default values for the nginx log files. 
Of course the change to the wildcard as you suggested is an easy fix and would be possibly better. But I'm not sure, that would be sufficient enough. I've seen other systems, where the logs was distributed in sub-directories inside `/var/log/nginx`.

@fail2ban/contributors easyfix?

Fail2ban is simply a tool you should correctly use, therefore it is powerful configurable :)
Some people want to install only (and enable = true), and everything works out of the box...

**Comment by yarikoptic** [comment]
> [1]@fail2ban/contributors easyfix?

I think we should do that since we are doing similar globbing for apache
already:

$> grep apache paths-*
paths-debian.conf:apache_error_log = /var/log/apache2/*error.log
paths-debian.conf:apache_access_log = /var/log/apache2/*access.log
paths-fedora.conf:apache_error_log = /var/log/httpd/*error_log
paths-fedora.conf:apache_access_log = /var/log/httpd/*access_log
paths-freebsd.conf:apache_error_log = /usr/local/www/logs/*error[_.]log
paths-freebsd.conf:apache_access_log = /usr/local/www/logs/*access[_.]log
paths-opensuse.conf:apache_error_log = /var/log/apache2/*error_log
paths-opensuse.conf:apache_access_log = /var/log/apache2/*access_log

**Comment by sebres** [comment]
:+1 :ok_hand:

**Comment by gagomap** [comment]
If someone host more than 1 website on a VPS, some bots or hacker will access via VPS's IP and nginx will record them in access.log and error.log

+1 for change log path :D

**Comment by sebres** [comment]
Done within e825e97

**Comment by leeclemens** [comment]
Any known platforms that don't use /var/log/nginx by default? Or I suppose we can cross that bridge when we get there?

**Comment by yarikoptic** [comment]
On Fri, 30 Oct 2015, Lee Clemens wrote:

> Any known platforms that don't use /var/log/nginx by default? Or I suppose we
> can cross that bridge when we get there?

I am just aware of

config/paths-freebsd.conf:# http://svnweb.freebsd.org/ports/head/www/nginx/Makefile?view=markup
config/paths-freebsd.conf:nginx_error_log = /var/log/nginx-error.log
config/paths-freebsd.conf:nginx_access_log = /var/log/nginx-access.log
