### ISSUE TITLE
Question Debian distribution

### ISSUE THREAD

**Issue by ADDISON74** [fail2ban/fail2ban#1255]
I am using Debian Wheezy 7.9. Fail2Ban version from repository is 0.8.6.3. I have a few issues related to same jails and I would like to use the latest version which is far more completely (Debian maintenance team is not updating the package in wheezy branch). 

1) Is there any risk latest version not worked? Is it fully compatible or needs some changes?

2) If I installed it from terminal (python setup.py instal), can I uninstall in the same way? By the way what is the command to completely remove from terminal the whole package not installed from repository?

Sorry for my basic questions, I am new to Fail2Ban but after a few days I need this software on my servers. I would like to thank you for your dedicated work.

**Comment by yarikoptic** [comment]
"wheezy branch" can't be updated since no updates to wheezy (which is in LTS support mode) beyond security and critical fixes possible.  Want it stable -- use it stable ;)

Want to use fresh 0.9.x version on wheezy -- you are welcome to try the one I provide from NeuroDebian "non-publicized" -devel repository... actually I have only 0.9.2 available there and I marked 0.9.3 as the one to not upload for wheezy, although forgot why.  You can try jessie's version (nd80) which would be identical and report back what doesn't work: http://neuro.debian.net/debian-devel/pool/main/f/fail2ban/

Thus

1) there is always a higher risk of using recent developments on elderly stable releases of OS

2) nope. I guess smth like  rm -rf /*/fail2ban /*/*fail2ban* /*/*/fail2ban or close to that ;) (you can first use ls -ld instead of rm -rf to see what you find ;) )

**Comment by ADDISON74** [comment]
I appreciate for your reply. In this case I will use stable version from Debian repository. I will try using jails, actions and filters from latest Fail2Ban, I did a few tests and it seems working.
