### ISSUE TITLE
fail2ban-client status  ERROR  unsupported pickle protocol: 4

### ISSUE THREAD

**Issue by Rhandyx** [fail2ban/fail2ban#1259]
I,m running ubuntu 15.1 server

Fail2ban version 0.9.3

#service fail2ban start    - works without issues

Fail2ban work and ban

but when i use fail2ban-client

I have:  ERROR  unsupported pickle protocol: 4

# python -V
Python 2.7.10

# python3 -V
Python 3.4.3+

**Comment by sebres** [comment]
I believe your fail2ban-server and fail2ban-client run within different python versions!
This is strange and something is wrong, using inside virtualenv, etc?

Because python2 supports pickle up to version 2, but default pickle protocol version in python3 is 3.

BTW, you can start fail2ban-client (and server) using dedicated python version, also:
```
python2 <f2b-path>/fail2ban-client ?parameters?
python3 <f2b-path>/fail2ban-client ?parameters?
```

**Comment by Rhandyx** [comment]
Results:

# python3 /usr/local/bin/fail2ban-client status
Traceback (most recent call last):
  File "/usr/local/bin/fail2ban-client", line 4, in <module>
    __import__('pkg_resources').run_script('fail2ban==0.9.3', 'fail2ban-client')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1644, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'fail2ban-client'


 python2 /usr/local/bin/fail2ban-client status
ERROR  unsupported pickle protocol: 4

**Comment by sebres** [comment]
:eyes: 
It is installed for python2 only, but uses unsupported proto?!

Whats about root (I mean you are root or `sudo fail2ban-client status`)? 
Which linux distribution?
How you start the fail2ban self? Because it will be normally started with `fail2ban-client` also.

Can you look in running processes f2b really runs and which python really used with fail2ban server? Something like:
```
sudo ps aux | grep fail2ban
```

**Comment by Rhandyx** [comment]
I´m using  Ubuntu 15.10 (GNU/Linux 3.16.0-53-generic x86_64)

I start fail2ban using as root  {service fail2ban start}

**Comment by sebres** [comment]
Yes, but the client communicates with the server, and server runs it in python3! (and you can't start your client in python3 where it seems to be not/not properly installed)!
Something is wrong in your system as regards python2-3 mix.
Either reinstall fail2ban, or if you use the stock version, it could be an issue of maintainer from ubuntu.

**Comment by Rhandyx** [comment]
Solved

First I backup /etc/fail2ban folder

After 
`# apt-get remove fail2ban
#apt-get autoremove
#apt-get install fail2ban´

Replace /etc/fail2ban

**Comment by sebres** [comment]
I told you :)

**Comment by acsfer** [comment]
I'm having this error too after installed fail2ban from sources https://www.fail2ban.org/wiki/index.php/Fail2Ban#Installation
```

systemctl status fail2ban
● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-05-18 11:09:23 CEST; 6s ago
     Docs: man:fail2ban(1)
  Process: 15464 ExecStop=/usr/bin/fail2ban-client stop (code=exited, status=0/SUCCESS)
  Process: 15465 ExecStartPre=/bin/mkdir -p /var/run/fail2ban (code=exited, status=0/SUCCESS)
 Main PID: 15471 (fail2ban-server)
    Tasks: 13 (limit: 4582)
   CGroup: /system.slice/fail2ban.service
           └─15471 /usr/bin/python3 /usr/bin/fail2ban-server -xf start
```

```
#fail2ban-client status
[20220]: ERROR   unsupported pickle protocol: 4

# which fail2ban-server
/usr/local/bin/fail2ban-server

# which fail2ban-client
/usr/local/bin/fail2ban-client

# head -1 /usr/bin/fail2ban-*
==> /usr/bin/fail2ban-client <==
#!/usr/bin/python3

==> /usr/bin/fail2ban-python <==
ELF>▒$[@▒

==> /usr/bin/fail2ban-regex <==
#!/usr/bin/python3

==> /usr/bin/fail2ban-server <==
#!/usr/bin/python3

==> /usr/bin/fail2ban-testcases <==
#!/usr/bin/python3
```

**Comment by sebres** [comment]
> I'm having this error too after installed fail2ban from sources

So your previous fail2ban-installation probably used python 2. And it was still running during upgrade, despite it must be stopped before.
So the new client (using python 3) cannot connect to the server (still running with python 2).

The only possibility to fix that (excepting reboot) is to stop it using old protocol.
Either with original (unmodified by 2to3) client from source:
```bash
cd /path/to/f2b-installation/
PYTHONPATH=. bin/fail2ban-client stop
```
Or with small python script using raw socket:
```
python -c 'import socket; s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); 
s.connect("/run/fail2ban/fail2ban.sock");
s.send(pickle.dumps(["stop"], 0) + b"<F2B_END_COMMAND>"); s.close()'
```
Killing of fail2ban server process is basically bad idea (remain many entries in net-filter e. g. iptables, so it may produce several issues after start).

**Comment by acsfer** [comment]
Yes, i've upgraded from apt to sources, but it was done using `systemctl stop`, `systemctl disable`, `apt purge` and `reboot` BEFORE installing from sources...

But it is solved now, thanks 👍

**Comment by diegaless** [comment]
help, install the default version and then try to update to the latest version which caused this error.

Prove to # apt-get remove fail2ban # apt-get autoremove # apt-get install fail2ban but I keep getting the error even after rebooting:

python -V
Python 2.7.17

python3 -V
Python 3.6.9

/ etc $ sudo python3 / usr / local / bin / fail2ban-client status
Status
| - Number of jail: 1
`- Jail list: sshd

sudo python2 / usr / local / bin / fail2ban-client status
2020-08-19 03: 52: 32,224 fail2ban [14192]: ERROR unsupported pickle protocol: 4

sudo fail2ban-client status
2020-08-19 03: 53: 12,887 fail2ban [14210]: ERROR unsupported pickle protocol: 4

sudo ps aux | grep fail2ban
root 14057 0.0 2.5 297792 22972? Ssl 03:46 0:00 / usr / bin / python3 / usr / bin / fail2ban-server -xf start
diego 14224 0.0 0.1 14848 1056 ttyS0 S + 03:53 0:00 grep --color = auto fail2ban



systemctl status fail2ban
● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset:
   Active: active (running) since Wed 2020-08-19 03:46:06 UTC; 9min ago
     Docs: man: fail2ban (1)
  Process: 14048 ExecStop = / usr / bin / fail2ban-client stop (code = exited, status = 0 / S
  Process: 14049 ExecStartPre = / bin / mkdir -p / var / run / fail2ban (code = exited, stat
 Main PID: 14057 (fail2ban-server)
    Tasks: 3 (limit: 1024)
   CGroup: /system.slice/fail2ban.service
           └─14057 / usr / bin / python3 / usr / bin / fail2ban-server -xf start

Aug 19 03:46:06 diegales systemd [1]: Stopped Fail2Ban Service.
Aug 19 03:46:06 diegales systemd [1]: Starting Fail2Ban Service ...
Aug 19 03:46:06 diegales systemd [1]: Started Fail2Ban Service.
Aug 19 03:46:07 diegales fail2ban-server [14057]: Server ready

head -1 / usr / bin / fail2ban- *
==> / usr / bin / fail2ban-client <==
#! / usr / bin / python3

==> / usr / bin / fail2ban-python <==
ELF ??????????> ????? & [????? @ ????????

==> / usr / bin / fail2ban-regex <==
#! / usr / bin / python3

==> / usr / bin / fail2ban-server <==
#! / usr / bin / python3

==> / usr / bin / fail2ban-testcases <==
#! / usr / bin / python3

The funny thing is that if I run
fail2ban-client --version
Fail2Ban v0.11.1

It keeps telling me that I'm at 0.11 instead of 0.10

I tried to install, uninstall, reboot so that the demons would reload many times and I comment here because I no longer know how to solve it

**Comment by sebres** [comment]
> install the default version and then try to update to the latest version which caused this error.

Well, I don't know how you get 0.11.1 resp. 0.10.2 installed. What is default and what is latest version? Has been some of that installed manually (via setup)?
Anyway, an upgrade of python version is not possible in ongoing operation (fail2ban should be stopped before upgrade).
(@fail2ban/maintainers) Maybe some upgrade script is missing that.

Additionally it looks like the server/client bindings are installed in different locations (`/usr/bin` and `/usr/local/bin`).

> It keeps telling me that I'm at 0.11 instead of 0.10

Firstly you have to stop fail2ban process. If you would kill it, you have to remove all net-filter (iptables) rules of fail2ban manually.
Then make a backup of your local config files from `/etc/fail2ban`.
Then you have to remove all the files: 
- `/usr/bin/fail2ban-*`
- `/usr/local/bin/fail2ban-*`
- `/usr/lib/python*/*/fail2ban`
- `/usr/local/lib/python*/*/fail2ban` (e. g. `/usr/local/lib/python2.7/dist-packages/fail2ban/`)
- `/etc/fail2ban`

Because 0.11th database version has other schema as 0.10th (and I don't know whether an upgrade of sqlite database is occurred or not), if you would rather switch to 0.10 (and not to 0.11), you must probably remove it also:
 - `/var/lib/fail2ban/fail2ban.sqlite3`

Now you should be able to install fail2ban version which you need.

**Comment by diegaless** [comment]
> Well, I don't know how you get 0.11.1 resp. 0.10.2 installed. What is default and what is latest version? Has been some of that installed manually (via setup)?

Initially install 10.2 from the repositories and everything is working properly. The problem came when updating to the latest version from dpkg and without stopping the fail2ban daemon.

That was the reason why I tried the steps described above. My distro is ubuntu 18.04. I will apply the steps that you tell me, but that you advise me, that once applied, install the version of the repositories or go to the last one using dpkg (I do not know if this can lead to more errors, so before acting I ask you)

Thanks for the help, I really appreciate it

**Comment by diegaless** [comment]
With your steps I managed to solve it being able to install the stable version in repositories, the latest version available through dpkg was impossible for me to install, always the same error, I do not know why and I doubt that it is a dependency problem.

Thanks for the help

**Comment by sebres** [comment]
> So you need to completely uninstall the source package first 

Yep... As our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually) says:
*if your fail2ban version departs significantly or you decided install from source, **stop and uninstall** obsolete version of fail2ban*

What I meant as "not quite correct" above was - you could either remove wrong client this way (or remove it too early, because then would be unable to stop previous fail2ban version).

**Comment by mehdi-song** [comment]
Hi
I have the same problem.
2022-11-27 04:59:32,359 fail2ban                [9931]: ERROR   unsupported pickle protocol: 4

**Comment by francwalter** [comment]
I got from cron this morning that error mail:

Subject: Cron <root@ew6> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )

Body:

```
/etc/cron.daily/logrotate:
2023-02-27 06:28:28,138 fail2ban                [28912]: ERROR   unsupported pickle protocol: 4
error: error running non-shared postrotate script for /var/log/fail2ban.log of '/var/log/fail2ban.log '
run-parts: /etc/cron.daily/logrotate exited with return code 1
```

Is that related?
I did not reinstall or install recently fail2ban. I have fail2ban 1.0.1.dev1* and when I ask status I get the same pickle error:

```
#fail2ban-client status
2023-02-27 14:18:52,151 fail2ban                [18610]: ERROR   unsupported pickle protocol: 4
```

but fail2ban works.
Thanks for hints.
frank

PS:  * I installed (2021-03-10) fail2ban from git:
 
```
git clone https://github.com/fail2ban/fail2ban.git
cd fail2ban
python setup.py install
```

**Comment by sebres** [comment]
> I did not reinstall or install recently fail2ban.

Maybe it is python that got updated and uses pickle v.4 now by default, but your fail2ban still running with older protocol version.
No idea how it is possible without to switch python-version (and necessity to reinstall fail2ban-modules for that python, so a stop of fail2ban before would be required either way).

Anyway, you'd need to restart fail2ban (but will be unable do that via fail2ban-client normally because of different pickle version now).
So either try to stop fail2ban using that:
```python
?sudo? fail2ban-python -c "
import pickle, socket
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM);
s.connect('/run/fail2ban/fail2ban.sock'); s.send(pickle.dumps(['stop'], protocol=3) + b'<F2B_END_COMMAND>'); s.close()
"
```
(and try to decrease `protocol` if it is still lower version than 3)

Alternatively, try to simulate simplest pickle sequence:
```bash
printf "(lp0\nS'stop'\np1\na.<F2B_END_COMMAND><F2B_CLOSE_COMMAND>" | nc -q 0 -U '/run/fail2ban/fail2ban.sock'
# or:
printf "(lp0\nVstop\np1\na.<F2B_END_COMMAND><F2B_CLOSE_COMMAND>" | nc -q 0 -U '/run/fail2ban/fail2ban.sock'
```
And then if fail2ban got stopped, try to start it normally.

Or simply reboot the machine.

**Comment by francwalter** [comment]
No, simple reboot didnt change it, still I see:

```
#fail2ban-client status
2023-02-27 20:54:13,417 fail2ban                [6012]: ERROR   unsupported pickle protocol: 4
```

and the command from above shows (as root):

```
#fail2ban-python -c "
> import pickle, socket
> s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM);
> s.connect('/run/fail2ban/fail2ban.sock'); s.send(pickle.dumps(['stop'], protocol=3) + b'<F2B_END_COMMAND>'); s.close()
> "
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/lib/python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 202, in __init__
    raise ValueError("pickle protocol must be <= %d" % HIGHEST_PROTOCOL)
ValueError: pickle protocol must be <= 2
```

Obviously Python 2.7 and not 3.x
But I had Python 3 installed already since a while, I think. But now I see weird things:

```
# less /var/log/apt/history.log
...
Start-Date: 2023-02-22  14:25:07
Upgrade: libopenjp2-7:amd64 (2.3.0-2build0.18.04.1, 2.3.0-2ubuntu0.1~esm1), mc:amd64 (3:4.8.19-1, 3:4.8.19-1ubuntu0.1~esm1), lynx-common:amd64 (2.8.9dev16-3, 2.8.9dev16-3ubuntu0.1~esm1), libopenmpt0:amd64 (0.3.6-1, 0.3.6-1ubuntu0.1~esm1), python3-pip:amd64 (9.0.1-2.3~ubuntu1.18.04.6, 9.0.1-2.3~ubuntu1.18.04.6+esm1), fail2ban:amd64 (0.10.2-2, 0.10.2-2ubuntu0.1~esm1), mc-data:amd64 (3:4.8.19-1, 3:4.8.19-1ubuntu0.1~esm1), libmediainfo0v5:amd64 (17.12-1ubuntu0.1, 17.12-1ubuntu0.1+esm1), lynx:amd64 (2.8.9dev16-3, 2.8.9dev16-3ubuntu0.1~esm1), ntpdate:amd64 (1:4.2.8p10+dfsg-5ubuntu7.3, 1:4.2.8p10+dfsg-5ubuntu7.3+esm1), libsdl2-2.0-0:amd64 (2.0.8+dfsg1-1ubuntu1.18.04.4, 2.0.8+dfsg1-1ubuntu1.18.04.4+esm1), libmysofa0:amd64 (0.6~dfsg0-3+deb10u1build1, 0.6~dfsg0-3+deb10u1ubuntu0.1~esm1), libonig4:amd64 (6.7.0-1, 6.7.0-1ubuntu0.1~esm2), python-pip-whl:amd64 (9.0.1-2.3~ubuntu1.18.04.6, 9.0.1-2.3~ubuntu1.18.04.6+esm1)
Remove: libegl1:amd64 (1.0.0-2ubuntu2.3), libegl-mesa0:amd64 (20.0.8-0ubuntu1~18.04.1), libgbm1:amd64 (20.0.8-0ubuntu1~18.04.1), libwayland-egl1-mesa:amd64 (20.0.8-0ubuntu1~18.04.1), libwayland-server0:amd64 (1.16.0-1ubuntu1.1~18.04.4)
End-Date: 2023-02-22  14:29:50
...
```

I see fail2ban 0.10.2-2 installed!???
I thought I had the old apt fail2ban uninstalled.
So this is maybe the reason. I wonder then why now only I get this mail with error?

**Comment by sebres** [comment]
> ValueError: pickle protocol must be <= 2

As already said: *try to decrease `protocol` if it is still lower version than 3*.

It looks like you have at least two fail2ban versions installed.
Basically it's not a problem, as long as you'd stop old fail2ban version and remove it's bindings from bin and init or systemd unit starter.
One possibility for a conflict may be a PATH env-variable and several files `fail2ban-client` or `fail2ban-server` in different bin folders (sbin, usr/bin, etc).
What do you see with `whereis fail2ban-client`? If there are 2 variants you'd be able to stop with one of them and even remove it later.

> I see fail2ban 0.10.2-2 installed!???
I thought I had the old apt fail2ban uninstalled.

You must uninstall it before you install newer version.
See https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually for more details.

> Will the git-fail2ban v1 will uninstall too?

Conditionally, It can remove init or systemd unit files, so you have to create them later.

**Comment by francwalter** [comment]
```
~#whereis fail2ban-client
fail2ban-client: /usr/bin/fail2ban-client /usr/local/bin/fail2ban-client /usr/share/man/man1/fail2ban-client.1.gz
```

**Comment by sebres** [comment]
> How is that done? Dont find this.

It means the 3 in `protocol=3` by `s.send(pickle.dumps(['stop'], protocol=3) + b'<F2B_END_COMMAND>');`
But you can also stop it with correct version of `fail2ban-client`.

> apt remove fail2ban

`apt purge` would be probably better one in that case, because it removes everything (inclusive configuration)... now I'm unsure the later install has upgraded the config in /etc/fail2ban.

> then I installed the deb package... changed the start script's pathes (from /usr/bin/ to /usr/local/bin/)

How so? did that really install systemd unit with a wrong path? Maybe it was still a result of not uninstalled previous version.

> and reboot

So does it run correctly now, or do you still have issues with protocol version?

**Comment by francwalter** [comment]
Sorry, updated my post and in the meantime you postet 😊 
So yes, it works now!
I indeed might have not uninstalled the old apt fail2ban before, I guess.
Anyway, now its the real one running:

```
#ps aux | grep -i fail2ban
root       923  0.7  0.1 1181588 20900 ?       Ssl  14:20   0:19 /usr/bin/python /usr/local/bin/fail2ban-server -xf start
```
