### ISSUE TITLE
Fail2ban issue after an update

### ISSUE THREAD

**Issue by KeizerMc** [fail2ban/fail2ban#1261]
Hi fail2ban, 

I apologize I am new to this thread and I hope im not posting in the wrong thread.
I currently have:
- Python 2.6.6
- Fail2ban v0.9.3  

I seem to have a lot of Log Warnings after an update.  I tried placing logencoding =utf-8 on my jails but it seems that it is not working. I still see the warnings in my logs. 

```
2015-11-27 13:16:34,151 fail2ban.filter         [18014]: WARNING Error decoding line from '/XXXXXXXXX/maillog.txt' with 'utf-8'. Consider setting logencoding=utf-8 (or another appropriate encoding) for this jail. Continuing to process line ignoring invalid characters: "XXXXXX"
2015-11-27 13:16:34,153 fail2ban.filter         [18014]: WARNING Error decoding line from '/XXXXXXXXX/maillog.txt' with 'utf-8'. Consider setting logencoding=utf-8 (or another appropriate encoding) for this jail. Continuing to process line ignoring invalid characters: "XXXXXX"
```
It is really spamming my logs. I was wondering if there is a way to also disable it. 

In other things, here are the things that i'ved tried but still no go. 
- I tried UTF8, UTF-8. 
- I also placed it in the jail where I needed it to work (assp jail). 
- In the defaults i did set to utf-8.
- Tried others formats like en_US, MIME, RFC's but it was not being recognised when fail2ban starts.
- Did read past articles about this issue after i made my post and it seems i can only found out that i need to set it to utf-8 but it still didnt work on my side. 

Please let me know if there are other things I needed to post to resolve this. 

Thank you for all your time. 

Best regards,
Keizer Mc

**Comment by sebres** [comment]
The problem is - you have no proper characters in log (in sense of current encoding).
You can not avoid that, because for example the url will be pass from outside, and the one can use as url what he want.
Example: character `ü` in utf-8 would be `xC3BC`, in cp1252 in would be `xFC`. If you log is in utf-8 and you get `xFC`, it is invalid. But if you log would be in cp1252 and you get some multibyte characters from utf-8 - it invalid also.

But fail2ban works further and even bans such failures if matched (prerequisite the invalid characters are not in filter rules, resp. regular expressions, and normally it is never the case).

I find this warning message totally unnecessary also. But the colleagues unfortunately not (greetings to @yarikoptic).

So leave your log in utf-8 and just ignore this warning, as long as we don't make it configurable, and it can be switched off.

**Comment by KeizerMc** [comment]
Thank you!. 

About the last part, My understanding is that it can be switched off?(i mean those specific warning logs) is there a way to turn off those specific logs? 

Sorry, English is not my main language. 

There were cases of it on the warning logs that it will be about 80 lines to 100 lines in an instance. and also it provides the whole line of information of what it was trying to check(its good in a sense but it kinda worries me that it may cause a security issue as it is providing all the information in the logs specially the long ones as well.)

Best regards,
Brian D.
