### ISSUE TITLE
fail2ban bans legitimate SSH users with multiple public keys

### ISSUE THREAD

**Issue by CyberShadow** [fail2ban/fail2ban#1263]
In some circumstances, fail2ban can ban users for logging in successfully. This can happen if the user has multiple public keys, and they are tried one after another.

Example log excerpt:

```
Nov 28 09:16:02 k3 sshd[32307]: Connection from 178.168.x.x port 57904 on 178.33.224.37 port 22
Nov 28 09:16:02 k3 sshd[32307]: reverse mapping checking getaddrinfo for 178-168-x-x.starnet.md [178.168.x.x] failed - POSSIBLE BREAK-IN ATTEMPT!
Nov 28 09:16:03 k3 sshd[32307]: Failed publickey for git from 178.168.x.x port 57904 ssh2: ECDSA 0e:ff:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
Nov 28 09:16:03 k3 sshd[32307]: Failed publickey for git from 178.168.x.x port 57904 ssh2: RSA 04:bc:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
Nov 28 09:16:03 k3 sshd[32307]: Postponed publickey for git from 178.168.x.x port 57904 ssh2 [preauth]
Nov 28 09:16:03 k3 sshd[32307]: Accepted publickey for git from 178.168.x.x port 57904 ssh2: DSA 36:48:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
Nov 28 09:16:03 k3 sshd[32307]: pam_unix(sshd:session): session opened for user git by (uid=0)
```

Simply logging in a few times in quick succession (in this case, issuing a few git push/pull commands) is enough to get you banned.

**Comment by sebres** [comment]
Just increase a value of `maxretry` (and possible decrease `findtime` at the same time) for this jail.
But if your git does not remember a right key that was accepted for login to server, the only way is to disable this regexp in sshd filter.

We would have possibly a solution for this issue (#1243), that may take into account a successful logins. But is just a PR, still rough and has still no success regexp for sshd-filter.

**Comment by yarikoptic** [comment]
On Sat, 28 Nov 2015, Vladimir Panteleev wrote:
> In some circumstances, fail2ban can ban users for logging in successfully. This
> can happen if the user has multiple public keys, and they are tried one after
> another.

> Example log excerpt:

> Nov 28 09:16:02 k3 sshd[32307]: Connection from 178.168.x.x port 57904 on 178.33.224.37 port 22
> Nov 28 09:16:02 k3 sshd[32307]: reverse mapping checking getaddrinfo for 178-168-x-x.starnet.md [178.168.x.x] failed - POSSIBLE BREAK-IN ATTEMPT!
> Nov 28 09:16:03 k3 sshd[32307]: Failed publickey for git from 178.168.x.x port 57904 ssh2: ECDSA 0e:ff:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
> Nov 28 09:16:03 k3 sshd[32307]: Failed publickey for git from 178.168.x.x port 57904 ssh2: RSA 04:bc:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
> Nov 28 09:16:03 k3 sshd[32307]: Postponed publickey for git from 178.168.x.x port 57904 ssh2 [preauth]
> Nov 28 09:16:03 k3 sshd[32307]: Accepted publickey for git from 178.168.x.x port 57904 ssh2: DSA 36:48:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
> Nov 28 09:16:03 k3 sshd[32307]: pam_unix(sshd:session): session opened for user git by (uid=0)

> Simply logging in a few times in quick succession (in this case, issuing a few
> git push/pull commands) is enough to get you banned.

As a quick proper workaround please specify the specific key you want to
use for that host(s) using IdentityFile within your ~/.ssh/config, e.g.
I have

Host *.xxx.org
 IdentityFile %d/.ssh/id_rsa_xxx

Otherwise, not sure how we should react to this one yet since such a
problematic use-case seems to be not that frequent.

**Comment by heini** [comment]
I've got that problem, too.

**Comment by yarikoptic** [comment]
Doesn't 'Host/IdentityFile' solution works for you @heini and @CyberShadow ?

**Comment by CyberShadow** [comment]
Sure, but it's a workaround, not a solution, and you have to perform it on the client side. If it is out of your control then it is a burden on your users (who are already vexed from being unjustly banned).

**Comment by yarikoptic** [comment]
Well @CyberShadow , I could argue that allowing your authentications to fail X times first you are pretty much consciously imposing this upon yourself...  But overall, #1243 would probably be the best approach for a 'fix', so chime in there, help etc. But again, this solution might be not out of the box since it would  depend on number of keys you have and you might need to at least beef up your maxretry (thus server side adjustment needed), which leads to weakening protection by fail2ban (more failed attempts to sneak in etc).  So you would need to adjust somewhere -- server of client -- no free lunch sort of ;)

**Comment by CyberShadow** [comment]
> allowing your authentications to fail X times first

Trying a public key is not an authentication failure. The excerpt I provided in the original post is from auth.log. the user is not even aware that their SSH client is trying multiple keys.

**Comment by CyberShadow** [comment]
OpenSSH already limits how many public keys a client is attempting to try within a session. In that case it will issue an error such as `Too many authentication failures for <username>`. Wouldn't it make more sense to change fail2ban to look for that error message instead, since that one is actually an authentication failure?

**Comment by sebres** [comment]
> OpenSSH already limits how many public keys ... 
> Wouldn't it make more sense to change fail2ban to look for that error message instead ...

No, because the problem is sshd does that inside current session only (session-related not IP-related, how the file2ban works). So indirect it is fewer "secure" as IP-related.
Just imagine a situation, where the attacker will always try it exactly one time and closes the session immediatelly if (until) it not success. Fail2ban will never ban such IP, if we will remove this filter rule, as you suggested. 

So once again, we will not disable this rule in the standard sshd-filter. I'm definitively against.

If you have only key-authetication allowed, and you mean the key is very secure and you don't want that ssh will be checked with fail2ban - just disable this jail completelly. Otherwise as long as #1243 not released, you can remove this rule in your own copy of sshd-filter (.local).

**Comment by CyberShadow** [comment]
> where the attacker will always try it exactly one time and closes the session immediatelly

Ah, right. Makes sense. Then I agree that #1243 is a very sensible direction.

**Comment by mc0e** [comment]
Unfortunately, I think that #1243 is conceptually flawed.  The problem is that it allows an attacker with access to one account to use that to reset the counter for their IP, allowing them to brute-force another account with impunity.

The approach is possible, but it's more complex than has been described.  You'd need to keep counters for (IP,user) tuples.

**Comment by braindevices** [comment]
I still get this problem. Neither the `-i` option nor 'Host/IdentityFile' solution works. The auth.log always show multiple attempt DSA->RSA->ed25519

**Comment by olberger** [comment]
I have experienced the same issue, and am trying the following workaround : 

1. create a duplicate filter of sshd.conf, for instance named my-ssh.conf
2. add there a:
```
ignoreregex = ^%(__prefix_line)sFailed publickey for \S* from <HOST>(?: port \d*)?(?: ssh\d*)?$
```
3. change the [ssh] section in jail.local to use it:
[ssh]
filter  = my-ssh

Not so sure this is right, but this may help

**Comment by sebres** [comment]
BTW. To use this workaround without duplicating or changing anything else in other config files...

The value of `ignoreregex` can be specified in `filter.d/sshd.local`:
```INI
# filter.d/sshd.local - local version of sshd.conf
[Definition]
ignoreregex = ^%(__prefix_line)sFailed publickey\s
```

The value of `ignoreregex` can be also specified direct in `jail.local` (without touch of filter), however the substitution `%(__prefix_line)s` is not available there, thus it will be enough:
```INI
[sshd]
# disable recognition of publickey failures:
ignoreregex =^\s*(?:\S+ )?sshd\[\d+\]: Failed publickey\s
enabled = true
```

**Comment by sebres** [comment]
I found a "simple" solution for this, see #2014 (for >= v.0.10)... 
If someone would want test it - welcome with feedback.

I'll merge it tomorrow for both major branches.

People still having v.0.9, could "fix" it with adding of `ignoreregex` as described above, resp. can try to make a back-port of the obsolete multi-line filter `zzz-sshd-obsolete-multiline.conf` from PR #2014.
