### ISSUE TITLE
Numeric hostname breaks sshd filter

### ISSUE THREAD

**Issue by varnav** [fail2ban/fail2ban#1294]
Hello!

I have hostname that is '16950.local'
/var/log/secure will have strings that look like this:

```
Jan 8 16:18:54 16950 sshd[4528]: pam_unix(sshd:session): session opened for user root by (uid=0)
```

timestamp parser throws an error, because it takes hostname as a year. I'm getting errors:

```
2016–01–08 15:50:34,269 fail2ban.filter [1531]: WARNING Found a match for u'Jan 8 15:39:05 16950 sshd[3774]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=27.154.37.285 ' but no valid date/time found for u'Jan 8 15:50:34 1695'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.
```

Workaround is to edit filter.d/sshd.conf and put into [Init] section:

`datepattern = ^%%b %%d %%H:%%M:%%S`

**Comment by yarikoptic** [comment]
On Fri, 08 Jan 2016, varnav wrote:
>    I have hostname that is '16950.local'
>    /var/log/secure will have strings that look like this:

>    Jan 8 16:18:54 16950 sshd[4528]: pam_unix(sshd:session): session opened
>    for user root by (uid=0)

>    timestamp parser throws an error, because it takes hostname as a year. I'm
>    getting errors:

>    2016a**01a**08 15:50:34,269 fail2ban.filter [1531]: WARNING Found a match
>    for u'Jan 8 15:39:05 16950 sshd[3774]: pam_unix(sshd:auth): authentication
>    failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=27.154.37.285 ' but no
>    valid date/time found for u'Jan 8 15:50:34 1695'. Please try setting a
>    custom date pattern (see man page jail.conf(5)). If format is complex,
>    please file a detailed issue on
>    https://github.com/fail2ban/fail2ban/issues in order to get support for
>    this format.

I guess ATM you would indeed need to follow the advice and set a custom
date pattern without year listed.  In a longer run, may be we could
adjust date detection only to match years as "current year+-1".

or we could skip those matches where year is not in close proximity to
current one (probably the best possible workaround).  But that
would not solve it for you if you have a host numbered matching the
year, so not a generic solution really. And providing fixed date/time
pattern would be the way to go 

Proper resolution could be to make all our regexes specify where the
date/time pattern should be expected and make it non-greedy for matching
there, but that would be also major overhaul I am not quite sure we
should pursue.

am I missing some other simple "fix"?
-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by sebres** [comment]
The best possible workaround would be imho also to set Y-regexp in the date-templates to something like `(\d{2}|\d{4})\b`, but incidentally aggre with you ... because it will match hosts like 1999 or 2008 (and because too old date, and will not ban).

Idea to match with current year only is also not so bad (at least faster matching), but the test cases may failed, because of old date used within...
And doesn't change the fact - the same issue on hosts with names equal current year.

> make it non-greedy for matching there

Very, very bad idea.

**Comment by sebres** [comment]
BTW. About a numeric hostnames... However, it was provided in RFC 1124, 1178 etc. guidelines to choose a hostname beginning with a character, because of implementations issues. 
You would be surprised how many implementations do not honor these RFC and don't recognize numeric hostnames at all. I've seen already too many issues in this respect, in several directions...

So the best way would be really to change the hostnames to something like v16950 etc.
If you can do that... :)
