### ISSUE TITLE
fail2ban on OSX : ERROR   Unable to get stat on /var/log/system.log because of: [Errno 2] No such file or directory: '/var/log/system.log'

### ISSUE THREAD

**Issue by brunobhr** [fail2ban/fail2ban#1329]
Hello,
fail2ban v0.8.14 is crashing on Mavericks 10.9.5, every few days but every time at 00:00.
It seems it has to do with the system.log rotation.
I get this from the log: ERROR   Unable to get stat on /var/log/system.log because of: [Errno 2] No such file or directory: '/var/log/system.log'
and then: WARNING Too many errors. Setting the jail idle
Is there anyway this is gonna be fixed in a further release?
Or should I find a way to grep fail2ban.log at 00:00 and relaunch it if it crashed?
Thank you very much for your help.

**Comment by sebres** [comment]
0.8 is too old version, so no fix for that. 
But I think (or rather hope), you may easy fix it, through a workaround by adding a rule `create <mode> <owner> <group>` to your logrotate config for the syslog. See man of logrotate for more info.

**Comment by brunobhr** [comment]
Sebres,
Thank you for your answer.
I wanted to try your fix but I run OSX, so there is no command logrotate.
Any idea of how I can prevent fail2ban to crash, or should I find a way to grep fail2ban.log at 00:00 and relaunch it if it crashed?
I runs perfectly on 10.6.8 but crashes on all my 10.9.5 machines..
Thank you

**Comment by sebres** [comment]
Unfortunately for you (or fortunately for me) I speak no apple'ian :)

It crashes without any log entries (except for the you already mentioned)?

Can you try to run fail2ban with `loglevel = DEBUG` (see fail2ban.conf) on a single machine, and provide here the last excerpt from fail2ban.log after it crashes?

Fail2ban is a pure python application, so because I've not so often seen the crash of python self in normal usage, I will suspect it may be anyone module, that let the the python crashes. For example, you can try to switch the backend to polling (`backend = polling`) to prevent occurring of critical exception in pyinotify or gamin backends.

Possibly the updating to the newer version (0.9) can help?
Elsewise I've no ideas and you should possibly seek help with this issue by the maintainers of f2b for OSX...

**Comment by jameslbrown** [comment]
I'm getting the same thing. El Capitan Mac OS X 10.11.6

Fail2ban 0.9.3
