### ISSUE TITLE
Seeking help for rule creation

### ISSUE THREAD

**Issue by Zorrototo** [fail2ban/fail2ban#1334]
### Environment:

- Fail2Ban last version for Ubuntu 12.04LTS
- Ubuntu 12.04LTS: 
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Sorry for posting here but it seems to be the only active place to seek for help (I tried IRC, but no one answer or say a thing, I tried the mailing list, never got a reply). I would like some help to create a fail2ban rule to block someone from downloading continuously the same file over and over (maybe thinks I will pay more bandwidth or whatever). I am manually banning the offending IP but I need to regulary scaning the logs and finding these IP. Here is an example:

```
111.222.333.444 - - [25/Feb/2016:12:34:56 +0100] "GET /MyDownloadsFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
```

I have loads of lines like this from the same IP, in my apache2 access logs (like 20000 for one IP, 15000 for another, and so on).

What I would like to do is permanently banning someone who downloads the same file from the  folder  /MyDownloadsFolder/ repeatedly in a short period of time.

Is it possible with fail2ban? If so I'm here to seek some help in creating such rule.

Thank you to anyone reading and replying to my message.

**Comment by sebres** [comment]
Well, I don't think that the given log line would be a bot resp. something "evil", because http code 304 (not modified) may be retrieved regular, too many such lines from the same IP can point to the proxy server, etc.
For other really "evil" behavior under apache we have already some filters, like `apache-botsearch`, `apache-badbots`, where you need just to enable corresponding jail.

But I would be careful by such unenlightened "failures", see my https://github.com/fail2ban/fail2ban/pull/1070#issuecomment-113232258

If you want nevertheless to ban too many 304 (or 404), you can just add a new jail direct to your `jail.local` with the following content:
```
[apache-my-jail]
# specify _badurl_ to ban accurate as posible:
#_badurl_ = /(download|evil-url1|evil-url2)/
_badurl_ =
# _badhttpcode_ for "not modified" and "not found":
_badhttpcode_ = (?:304|404)
failregex = ^<HOST> -.*"(?:GET|POST|HEAD)\s%(_badurl_)s[^"]*?"\s+%(_badhttpcode_)s\s+
#
# ban only after 100 failures in 1 minute:
maxretry = 100
findtime = 60
#
filter =
enabled = true
port     = http,https
#logpath  = %(apache_error_log)s
logpath = %(apache_access_log)s
```

You can always test your own expression with `fail2ban-regex`, like here:
```
fail2ban-regex '1.2.3.4 - - [25/Feb/2016:12:34:56 +0100] "GET /MyDownloadsFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"' '^<HOST> -.*"(?:GET|POST|HEAD)\s[^"]*?"\s+(?:304)\s+'
```

But as already said, **I hold it not for a good idea**... There are definitely better methods to achieve that, for example to shrink per IP the throughput rate, max request resp. connect count, etc.
Please don't ask me how you can do that in apache, because I speak nginx only :), and there it would be for example using `limit_rate`. We've already a filter for that, see #1236.

**Comment by sebres** [comment]
Oh yeah, the example above applies of course to version \>= 0.9 only.
If you have in your (old) ubuntu a lower version, you should replace some variables, that version 0.8 may not offer, for example `%(apache_access_log)s` with `/var/log/apache2/*access.log`, etc.

**Comment by Zorrototo** [comment]
Yeah it is definitely a script someone run to spam my server with request by downloading repeatedly from my webserver the same file again and again, reason I am sure of that is the numbers (too much in too little time to be logical), the IP origins (china, everytime, when my website is french, and when you have to dig deep to know such url, and of course when even the total downlad from my regular members are really low (like 100 download from people from France, TOTAL, since website creation; when I have for now more than 50000 download from various IPs in China, which is ridiculously impossible to be real, no one from china consults my website, it is really not a known website, I am clearly under some kind of attack, numbers don't lie :P )

If I understand, with this rule/jail, I can specify to only apply the jail for urls starting with /MyDownloadFolder/ ? is that for my case what I should specify? in you exemple if I have 100 download from same IP in one minute, it will apply the ban?

> #_badurl_ = /(download|evil-url1|evil-url2)/
_badurl_ = /MyDownloadFolder/

@sebres Thanks you very much for your quick reply, too sad I could not reply before you closed this.. If this is not the place to 'discuss' (it is closed but I can reply, I don't know if others can too), where am I supposed to go? this is the only place I got a reply from since I'm seeking for help.

**Comment by sebres** [comment]
> with request by downloading repeatedly from my webserver the same file again and again

Well, according to the log entry in your example above, it was 304 status code, what does mean "Not modified". This is definitely not a download, incidentally the apache has transfered 202 bytes only (http answer with status code 304 + small header to this end). But whatever...

> If I understand, with this rule/jail, I can specify to only apply the jail for urls starting with /MyDownloadFolder/ ? 
badurl = /MyDownloadFolder/

Yes you can do it exact so... (and that means really a url prefix).

> in you exemple if I have 100 download from same IP in one minute, it will apply the ban?

Yes, but as already said, not downloads (then you should also add status code 200 or just to rewrite `_badhttpcode_ = \d+` for any status code). In the example I made, it does only for 304 and 404, so "not modified" and "not found"...

<sub>About an issue self: closed because 1) I thought it was answered; 2) it was not really an issue, in sense of problem; 3) just to not be open in our listing "open issues"
And of course you (and all other) can write here further (at least as long I or any other f2b member don't lay down the law and will not lock this conversation :))
</sub>

**Comment by Zorrototo** [comment]
OK thanks for the clarifications, my mistake to not search what this code was meant for. I am also new to GitHub and still don't know how all of this is working ;)

So yes it is not a download, but actually, there is a download I did not give enough log:

> 111.222.333.444 - - [21/Feb/2016:07:47:03 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:47:16 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:47:19 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:47:33 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:47:35 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:47:40 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 200 18980 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:47:49 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:47:57 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:48:06 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:48:13 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:48:22 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:48:28 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:48:29 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 200 16060 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:48:34 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:48:38 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:48:51 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:48:55 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:49:07 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"
111.222.333.444 - - [21/Feb/2016:07:49:11 +0100] "GET /MyDownloadFolder/MyFile.zip HTTP/1.1" 304 202 "-" "Mozilla/5.0 Gecko/20100115 Firefox/3.6"

 what is crazy is the number of these lines in my server log from multiple chinese IPs. In the last four day only, I have around 30000 occurrence and 2500 certified downloads. Anyway, download or not I want to stop it so thank you very much for your time :)
