### ISSUE TITLE
FAIL: testReadStockJailConfForceEnabled (fail2ban.tests.clientreadertestcase.JailsReaderTest)

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#1353]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.9.4
- OS, including release name/version: Fedora Rawhide (F25)

### The issue:

~~~~~
FAIL: testReadStockJailConfForceEnabled (fail2ban.tests.clientreadertestcase.JailsReaderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/clientreadertestcase.py", line 636, in testReadStockJailConfForceEnabled
    self.assertTrue(['add', j, 'auto'] in comm_commands)
AssertionError: False is not true
~~~~~
#### Steps to reproduce
~~~~~
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.LC5buM
+ umask 022
+ cd /builddir/build/BUILD
+ cd fail2ban-0.9.4
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ ./fail2ban-testcases-all-python3 --no-network
Testing using /usr/bin/python3.5
Fail2ban 0.9.4 test suite. Python 3.5.1 (default, Mar  4 2016, 13:43:50) [GCC 6.0.0 20160302 (Red Hat 6.0.0-0.14)]. Please wait...
~~~~~

**Comment by sebres** [comment]
Can you try my branch <a href="https://github.com/sebres/fail2ban/tree/f2b-perfom-prepare-716-cs">f2b-perfom-prepare-716-cs</a>? I suspect, already fixed there

**Comment by opoplawski** [comment]
Still fails for me with that branch.

**Comment by sebres** [comment]
Can you replace this line in my branch (or in 0.9.4) with following to see the error more accurate:
```
# self.assertTrue(['add', j, 'auto'] in comm_commands)
self.assertIn(['add', j, 'auto'], comm_commands)
```

**Comment by opoplawski** [comment]
Ah, I see now - this is because for Fedora, the sshd jail is configured to be systemd, not auto, via fail2ban-0.9.4/config/paths-fedora.conf.

**Comment by sebres** [comment]
Bad thing: now we should write the test cases all distributions compatible... Grrr.

**Comment by AlexNPavel** [comment]
Any updates on fixing this test? I am building fail2ban 0.10a1 for CentOS7, so for now I have to disable this test to get the build working. It would be nice to be able to run all the tests for the build. I understand if there is a lot of work now during the alphas for 0.10, but it would be nice to see this fixed in the coming months, or maybe during the beta versions.

**Comment by yarikoptic** [comment]
@sebres suggested a PR... But I wonder if we should"fix" it actually... This year verifies default assumption of configuration. If distribution provides alternative configuration, it might benefit from simply patching/adjusting this test to match desired behavior on their systems

**Comment by yarikoptic** [comment]
Sorry for the typos... Phone at thousands of feet above the ground ;-)

**Comment by sebres** [comment]
I think, we should, because e.g. <a href="https://github.com/fail2ban/fail2ban/blob/0.10/config/paths-fedora.conf#L44">paths-fedora.conf</a>, that overrides a default backend, is under our control...
Otherwise agree, if `paths-*.conf` will be maintained from distribution maintainers, then yes, they can write a small patch for the test cases...

**Comment by yarikoptic** [comment]
On Wed, 27 Jul 2016, Serg G. Brester wrote:

>    I think, we should, because e.g. paths-fedora.conf, that overrides a
>    default backend, is under our control...
>    Otherwise agree, if paths-*.conf will be maintained from distribution
>    maintainers, then yes, they can write a small patch for the test cases...

ok, let's make it easier for everyone for now
