### ISSUE TITLE
hi, i found this issue please help with time format , centos 6 and fail2ban 0.9

### ISSUE THREAD

**Issue by adilabd** [fail2ban/fail2ban#1383]
Apr  6 20:13:52 virtu1 fail2ban.filter[553]: WARNING Found a match for u'[01:03:33.390] cache: Alert! unknown peer (176.31.xxx.xxx:7500)' but no valid date/time found for u'[01:03:33.390] cache: Alert! unknown peer (176.31.xxx.xxx:7500)'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.
Apr  6 20:13:52 virtu1 fail2ban.filter[553]: WARNING Found a match for u'[01:04:33.512] cache: Alert! unknown peer (176.31.xxx.xxx:7500)' but no valid date/time found for u'[01:04:33.512] cache: Alert! unknown peer (176.31.xxx.xxx:7500)'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.
Apr  6 20:13:52 virtu1 fail2ban.filter[553]: WARNING Found a match for u'[01:05:33.637] cache: Alert! unknown peer (176.31.xxx.xxx:7500)' but no valid date/time found for u'[01:05:33.637] cache: Alert! unknown peer (176.31.xxx.xxx:7500)'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.

**Comment by sebres** [comment]
The correct date template for `01:03:33.390` would be `%H:%M:%S.%f`, but without date, Hmm...
You can add this to the jail, but I don't know whether it would be right, because you've  provided here no information like the log-line, jail, filter, some customization rules etc...
```
datepattern = %H:%M:%S.%f
```
I hope it helps.

The next time, please provide a corresponding log entry (from log file that fail2ban observes), the jail/filter or custom failregex you used for this jail.
Whithout that it's too hard to help you.

I'll close it, as long as you don't add the examples here.
