### ISSUE TITLE
Provide PID validation facility

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#14]
Just ran into sshguard which has such a nice feature 
http://www.sshguard.net/docs/log-validation/
which could be easily implemented in fail2ban for the syslog's which carry pid information which we already match but do not use.

So it would require specification of pidfile for the process (usually under /var/run/**.pid) + logic to monitor for their possible updates upon those services restarts (to avoid re-reading it every time) and that is pretty much it I guess.

**Comment by leeclemens** [comment]
Considering fail2ban largely deals with failed login attempts (SSH), the SSH pid is essentially ephemeral and not linked to a parent for very long - I'm not sure how such an association could be reliably be made between the parent pid (SSH) and the failed log in SSH pid's. And if other applications behave differently (thread vs process) fail2ban would also need to understand all of those relationships.

**Comment by sebres** [comment]
I've tried some time ago with a small change on my fail2ban, where #1698 was already implemented, so I could get the PID from the several filters, by adding `<F-PID>\S+</F-PID>` (and using a simple solution by checking of PID with pid_exists in failmanager).
It works as expected... But not for the services like sshd, because of session- resp. connection-related pid, so fail2ban misses the failure sporadic, if the connection was closed too fast after failure (pid_exists says False).
I can try to cherry-pick it, if someone needed.

**Comment by sebres** [comment]
Playing a bit with this I can judge that this approach is hardly suitable (as for PID validation), at least turns out to be not really practicable, but also too error-prone.
Thus I tend to close it at the moment.
Please reopen if the interest is still existing.
