### ISSUE TITLE
recidive - unable to make it work

### ISSUE THREAD

**Issue by Nihim** [fail2ban/fail2ban#1457]
OS: Ubuntu 16.04

relevant lines from configs

jail.local
```
[sshd]

port    = ssh
logpath = %(sshd_log)s
bantime = 18000
findtime = 300
maxretry = 2

[recidive]
logpath  = /var/log/fail2ban.log
banaction = iptables-allports
bantime  = 604800  ; 1 week
findtime = 86400   ; 1 day
maxretry = 2
```
fail2ban.local 
```
loglevel = INFO
logtarget = /var/log/fail2ban.log
dbpurgeage = 648000
```

From what I read in the configs the above should be enough to for recidive to work. I am banning for 5hours on 2 attemps. fail2ban.log is full of entries where every 5-6h same ip is rebanned for 5h then unbanned - rebanned in 10-30min etc.

Since recidive has a findtime of a day with a limit of 2, those ips should have been banned for a week right?

Kindly help me to figure out what I am doing wrong.

ps: did read several of existing tickets for recidive - didn't feel I figured out my problem.

**Comment by mitchellkrogza** [comment]
Hi, this is how I have my recidive jail setup and it works perfectly. 

I see you have no **enabled = true** in your recidive jail so you are either using enable = true in the main part of jail.local which is not recommended or somewhere else. I prefer having an enabled command in each jails config so you know 100% it's enabled or not. I also wildcard my log file locations so Fail2Ban can read any older files that get gzipped during log rotation.

I also suggest you change your log location for your ssh jail to be hardcoded to /var/log/auth.* I find hardcoding my log file locations and wild-carding them works 100% and nothing is ever skipped.

This is my recidive jail

[recidive]
enabled = true
logpath  = /var/log/fail2ban.*
banaction = iptables-allports
bantime  = 2629746   ; 1 month
findtime = 31536000   ; 1 year
maxretry = 10

My findtime is set to 1 year because if an attacker has tried more than 10 times anytime within a year, he truly is naughty and is blacklisted for 1 month (actually have mine set to 1 year in real life).

I have also customized my iptables-allports.conf file to deal with permanent banning through an ip.blacklist file, if you want that config too just shout.

**Comment by sebres** [comment]
Close now (I think also, the jails are just not enabled), please reopen if I'm wrong
