### ISSUE TITLE
filter for exim

### ISSUE THREAD

**Issue by ben29** [fail2ban/fail2ban#1466]
Hi.
i add exim filter with directadmin.
```
[exim]
enabled = true
port    = smtp,ssmtp
filter  = exim
logpath = /var/log/exim/mainlog
logencoding = utf-8
```
all my emails on hebrew.
so i get this error:

> WARNING Error decoding line from '/var/log/exim/mainlog' with 'utf-8'. Consider setting logencoding=utf-8 (or another appropriate encoding) for this jail. Continuing to process line ignoring invalid characters: '2016-06-06 17:07:06 1b9vBK-0002oZ-50 

i'm using the last version
and i also try with auto encoding,
thanks

**Comment by sebres** [comment]
This warnings say you, that the lines read from this logfile contains not utf-8 characters.
We don't known which encoding uses your system resp. your exim-daemon. 

Because the single-byte codecs can be rare recognized automatically, you should always specify logencoding, that will be really used for logging via corresponding service.

For the list of encoding see https://docs.python.org/2/library/codecs.html#standard-encodings

**Comment by ben29** [comment]
i try by change to windows-1255,, and still

> WARNING Error decoding line from '/var/log/exim/mainlog' with 'windows-1255'. Consider setting logencoding=utf-8 (or another appropriate encoding) for this jail. Continuing to process line ignoring invalid characters

**Comment by sebres** [comment]
It is just a warning. And you can really have some lines in logfile, that are not in your current encoding (for example the attacker uses some characters from another charset), then you can ignore it (as long as you'll not get this warning for each line).
Otherwise as already said, please specify the encoding will be used by logging in exim.

Still again, we don't known which encoding uses your system resp. your exim-daemon.
