### ISSUE TITLE
(Possibly a standalone) installation into a directory

### ISSUE THREAD

**Issue by hdatma** [fail2ban/fail2ban#1487]
1. A general security best-practice demands the removal of compilers and interpreters from production servers. Fail2Ban (a security tool) demands the installation of Python, a 100MB+ interpreter. Python is a big knife without safe handle: it makes it really easy to cut yourself. A single line of Python at the terminal is sufficient to turn any folder into a home page. Please show awareness of the elephant in the room. Aim at a self contained installation, with a minimal python, all under the same prefix folder. I am doing this, and it is a nightmare. 

2. Fail2Ban's installation is a nightmare by modern standards. --- Hardcoded paths, suitable for pre-cooked/half-baked linux servers-wannabe, demand reading 4 MB of scripts to change them all to fit local requirements. What happened to "./configure --prefix"?

**Comment by sebres** [comment]
Thx for the info, but ...

> Python is a big knife without safe handle

Well, fail2ban is written in python. So you have a choice: rewrite it using your favorite language..., or just don't use... 
> A single line of Python at the terminal is sufficient to turn any folder into a home page.

Exact the same you can say about sh, bash, etc, and?
>  Aim at a self contained installation, with a minimal python, all under the same prefix folder. I am doing this, and it is a nightmare. 

Perhaps yet knowledge is missing :) Because I've made it also some time ago for one of my routers, and it was easy-going (ca. half hour).

> Fail2Ban's installation is a nightmare by modern standards.

It is called as not constructive criticism, please open a PR, then we can "fix" that.
Otherwise you can install a ready packet from your distribution, where all this is already made from the maintainers.

I close this "issue" now, because imho it is neither an issue, nor it has any general use.

**Comment by yarikoptic** [comment]
If interested to help, try compiling fail2ban eg with nuitka. Then we might avoid shipping any python per se. PR with instructions and making testing of compiled fail2ban might indeed be nice. 
-- 
Sent from a phone which beats iPhone.

**Comment by hdatma** [comment]
Re: yarikoptic

I've got my head into this now
https://github.com/bendmorris/static-python

Thank you for the head up on nuitka
https://github.com/kayhayen/Nuitka 

Re: sebres
>  I close this "issue" now, because imho it is neither an issue, nor it has any general use.

I re-open this issue now, because the problem is still open.

**Comment by hdatma** [comment]
This is the result of installing fail2ban after rewriting paths. 
I explicitly instructed the installed to put the executables under /opt/fail2ban/bin. 

/opt/fail2ban/etc/
action.d		fail2ban.d		jail.conf		paths-common.conf
fail2ban.conf		filter.d		jail.d		paths-osx.conf
paths-debian.conf paths-fedora.conf paths-freebsd.conf paths-opensuse.conf

/opt/fail2ban/var/lib (empty)
/opt/fail2ban/var/run (empty)

No executables. The installer *ignored* my specs, and dumped the all that is missing from the above into an "egg", in python's own installation folder. 

No relevant configurations either. The installer *ignored* the OS and littered /etc with linux junk.

**Comment by yarikoptic** [comment]
my barrier for adoption was inability to 'apt-get install fail2ban'.  That problem was solved.  If you want to keep some issue open about standalone installation of fail2ban into a custom directory -- here you go.  I will reopen and retitle

**Comment by sebres** [comment]
I did not understood what for problem we have here...

My knowledge about "(standalone) installation into a directory":
- copy (or install) your favored minimalist python into `/test/fail2ban/bin`
- copy (or git) fail2ban into `/test/fail2ban/`
- create `/test/fail2ban/config/fail2ban.local` or `/test/fail2ban/config/jail.local` and set there all the path you will use;
- it is direct startable via `cd /test/fail2ban/ ; PYTHONPATH=. ./bin/python ./bin/fail2ban-client -c /test/fail2ban/config start`
- first time it started, it will be compiled from python (if not pure jit-python used);
- for example to stop it, use `cd /test/fail2ban/ ; PYTHONPATH=. ./bin/python ./bin/fail2ban-client -c /test/fail2ban/config stop`

It worked always so, and I and 10.000 people in this world have this way already successfully "installed" fail2ban since version 0.8 for several mini-linux distributions on mashines like routers etc.

**I really don't understand which kind of problems we should have here?**

So, our lastest 0.10th branch is even better in this direction, because: 
- it can start server directly (without fork it from client);
- it has more starting parameters (e.g. several paths) to specify it direct from command line;

Here is my output of `fail2ban-server --help`
```
Usage: fail2ban-server [OPTIONS]

Fail2Ban v0.10.0a1 reads log file that contains password failure report
and bans the corresponding IP addresses using firewall rules.

Options:
    -c <DIR>                configuration directory
    -s <FILE>               socket path
    -p <FILE>               pidfile path
    --loglevel <LEVEL>      logging level
    --logtarget <FILE>|STDOUT|STDERR|SYSLOG
    --syslogsocket auto|<FILE>
    -d                      dump configuration. For debugging
    -i                      interactive mode
    -v                      increase verbosity
    -q                      decrease verbosity
    -x                      force execution of the server (remove socket file)
    -b                      start server in background (default)
    -f                      start server in foreground
    --async                 start server in async mode (for internal usage only, don't read configuration)
    --timeout               timeout to wait for the server (for internal usage only, don't read configuration)
    -h, --help              display this help message
    -V, --version           print the version
```

**Comment by yarikoptic** [comment]
so all the underlying "technology" might well be available already and we might just need a good doc or a helper script to facilitate it, since classical `python setup.py install` ATM can't handle it.  We might want to enhance it so we could do e.g. `python setup.py install --prefix=/test/fail2ban` (may be some other than `--prefix`) which would carry out installation so that all cmdline tools are aware of where to look for configuration, and may be allow for `--standalone` switch which would "install" all needed python pieces so /test/fail2ban becomes completely sufficient to run without any system installed python?

**Comment by hdatma** [comment]
fail2ban is driving me out of focus instead of helping me on my own problem. I will look into fail2ban again, if and when it will be capable of generating a minimal (less than 5 MB), self-contained, and possibly chrootable installation of itself. In the meantime, I wrote a three-lines shell script that solves essentially the same problem using "tail", "grep" and "pfctl"... :)

**Comment by yarikoptic** [comment]
Yeap, let's all stay focused.  If someone else decides that standalone installation requires some helpers etc, please open a new issue, so we don't de-focus hdatma ;-)

**Comment by sebres** [comment]
I've created a wiki page with a simple how-to for the subject. 
See https://github.com/sebres/fail2ban/wiki/How-to-test-newer-fail2ban-version-resp.-use-fail2ban-standalone-instance
