### ISSUE TITLE
Bad honeypot failregex in exim-spam.conf

### ISSUE THREAD

**Issue by SineSwiper** [fail2ban/fail2ban#1514]
exim-spam.conf has the following fragment:

    From \S+ \(host=\S+ \[<HOST>\]\) for <honeypot>$

However, just the raw text of "honeypot" isn't going to match anything.  This should really be something like `<%(honeypot)s>`.

**Comment by sebres** [comment]
You should overwrite `honeypot` parameter (default specified in init section of filter) with your one...

jail.local:
```
[exim-spam]
filter = exim-spam[honeypot=honeypot@yourdomain.com]
#filter = exim-spam[honeypot=[^@]+@\S+]
```

BTW @fail2ban/contributors should we possibly replace example default honeypot with this one `[^@]+@\S+` in https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/exim-spam.conf#L44 ?
I think no matter which e-mail address specified there...

**Comment by szepeviktor** [comment]
Maybe `[^@]+@[^@]+`

**Comment by sebres** [comment]
> Maybe [^@]+@[^@]+

No, we will also not check the validity of the email address :) because it is not so easy with one regular expression according to RFC.

More about you can read here - https://davidcel.is/posts/stop-validating-email-addresses-with-regex/

My question was: take the honeypot value into account or may be any other...
