### ISSUE TITLE
fail2ban.system with wrong path to fail2ban-client

### ISSUE THREAD

**Issue by staehler** [fail2ban/fail2ban#1524]
Hi,
I freshly installed fail2ban-0.10 via _python setup.py install_ on my debian 8.5.
After copying the fail2ban.system to /lib/systemd/system a start of f2b failed.
I needed to adapt the path from /usr/bin/fail2ban-client to /usr/local/bin/fail2ban-client.

Maybe this should be changed.

Regards,
Michael

**Comment by sebres** [comment]
Thx a lot

**Comment by joaonl** [comment]
@staehler 

Can you please let me know how you did this? I am having the same issue.

Thanks.

**Comment by staehler** [comment]
Not sure what problem you have.
I needed to adapt the path in fail2ban.service from /usr/bin/fail2ban-client to /usr/local/bin/fail2ban-client. But this may be depended on the fail2ban package you use.
I downloaded fail2ban-0.10 tar file.

**Comment by viisauksena** [comment]
just installed it and had the same issue
(i purged the plesk maintained and fairly crippled fail2ban which without asking override my old debian fail2ban :( )
i simply linked all fail2ban* in /usr/local/bin to /usr/bin

**Comment by sebres** [comment]
I'll close this as 3rd party issue, because:
- our common (cross distribution version) fail2ban installation does not install systemd service file resp. init.d script at all (note our README file). Looks like seemingly still have an original distributed system unit file.
- the path where fail2ban-scripts will be installed (as well as the init scripts and units) are distribution-related, and thus is the subject of maintainer of your distribution.
- if you want to install fail2ban-scripts in another directory (resp. in same directory as in your original system unit file from distribution) you can use setup like here:
```bash
python setup.py install --install-scripts=/usr/bin
```
- #1874 fixes it partially (but `fail2ban.service` should be nevertheless installed manually at the moment).
