### ISSUE TITLE
Fail2Ban scan secure log and ban IPs backwards in time

### ISSUE THREAD

**Issue by bertalanimre** [fail2ban/fail2ban#1526]
I just have a simple question.
I've installed Fail2Ban on my server but forgot to start it (silly me...).
The server was running for months now with no issue, but I just noticed there were no banned IPs, there I got my atention on Fail2Ban. Started it. 

Now everything works fine, but I have a question. Can I somehow make Fail2Ban scan my /var/log/secure log and ban any IP addresses that would have been banned if Fail2Ban was running?

**Comment by sebres** [comment]
Shortly - no, because they are all too old and should be unbanned again (if your configured `bantime` is not too large, typically it is 15 minutes).

Additionally some of your logs may be already retated (so not available for fail2ban)

If you just want to see which addresses made failures, you can use 
```bash
fail2ban-regex ?--print-all-matched? /var/log/path/to/jail-log /etc/fail2ban/filter.d/jail-filter.conf
```

Another (not recommended way) if you want yet ban it all, just to increase the `findtime`, remove (backup it first) your fail2ban sqlite database, typically located `/var/lib/fail2ban/fail2ban.sqlite3`, and restart fail2ban hereafter. 
But be ready to get a lot of system load. You'll see many warnings in fail2ban "IP already banned", because it will ban IP after `maxretry` failures but find such IP again and again.
Secondly if the `findtime` is too large, you can get the situation where some "legal" IPs going banned (users that tried to authenticate), because it is enough to do `maxretry` attempts within `findtime` to be banned. So if you'll set `findtime=604800` , by `maxretry=3` all IPs doing 3 failures within 1 week will be banned.
