### ISSUE TITLE
Fail2Ban bans some iPhone and iPad users

### ISSUE THREAD

**Issue by Winniepooh1** [fail2ban/fail2ban#1550]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): v0.8.11
- OS, including release name/version: Ubuntu 14.04
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:
Some users with an iPhone or iPad gets banned by my fail2ban nginx-noproxy rule. But the log looks almost fine:
`XX.XXX.XXX.XX - - [17/Sep/2016:23:24:34 +0200] "GET http://WWW.MYWEBSITE.ORG**:80**/ANY_ARTICLE HTTP/1.1" 200 9390 "http://m.facebook.com" "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69 [FBAN/FBIOS;FBAV/62.0.0.43.141;FBBV/36454510;FBRV/37589473;FBDV/iPhone5,2;FBMD/iPhone;FBSN/iPhone OS;FBSV/9.3.2;FBSS/2;FBCR/E-Plus;FBID/phone;FBLC/de_DE;FBOP/5]"`
 
As you can see they try to access the domain with the port appended. 

Is there any malicious purpose behind this access? Why they get banned?

(I'm sorry for posting it here. Unfortunately I couldn't find any other place to ask for.)

#### Expected behavior
The users should be directed to the URL without the port at the end.

#### Any customizations done to /etc/fail2ban/ configuration
Here is the content of my nginx-noproxy.conf file:
```
[Definition]

failregex = ^<HOST> -.*GET http.*

ignoreregex =
```

**Comment by sebres** [comment]
Well, your filter does exact that, what it should do corresponding failregex...
Normally, the get-request does not send http before uri (it is relative, and nginx writes it as is)...
So, you should precise your regexp (e. g. forbidding other as your site).
 BTW it is currently very bad (catch-alls, no end-anchor, etc)

**Comment by Winniepooh1** [comment]
I've found this expression on every site about setting up fail2ban. 

So I just need to add a new expression to the ignoreregex like: /example.org/
Or should it be better integrated into the failregex?

**Comment by sebres** [comment]
> I've found this expression on every site about setting up fail2ban. 

Well, there are lots of people who even do not understand what they are doing...

- Firstly rename your .conf file in .local (because it is yours, so you can also easy differentiate between your and our files)
- Secondly, I would have made the expression as following:
```
_badurl_ = https?://(?!(?i)(?:(?:www\.)?mywebsite\.org|(?:www\.)?my-other-site\.org)\b)
_badhttpcode_ = (?:304|404)
failregex = ^<HOST> -[^"]*"(?:GET|POST|HEAD)\s%(_badurl_)s[^"]*?"\s+%(_badhttpcode_)s\s+
```
- `_badurl_` specifies expression to match begin of bad-urls, here is specified as anything begins with http but not mywebsite.org and not my-other-site.org (`(?i)` case-insensitive). `\b` means here end of word.
- `_badhttpcode_` defines expression more precisely, because nginx normally should not allow to execute and will return 404 (or 304) for such urls. If you not want this, just use `_badhttpcode_ = \d+`
- you should check you have correct specified `server_name` in each server context of nginx-conf, see http://nginx.org/en/docs/http/server_names.html
- if you will ban any type of request, just replace `(?:GET|POST|HEAD)` with `\w+`
- additionally I'll recommend you, to increase `maxretry` for this jail...

Thus I'll close this issue as answered (please give the word if not).
