### ISSUE TITLE
Add one regex in apache-auth.conf

### ISSUE THREAD

**Issue by AlexisWilke** [fail2ban/fail2ban#1589]
### The issue:

I am getting hits on an Apache 2.4 server where I have (among other things) a:

```
require ip <myip>
```

The resulting Apache error is an `AH01630`. I see that you handle the `AH01631` in the `apache-auth.conf`, but you missed the `AH01630` which I think would also be useful.

> [Sun Oct 23 12:14:00.710099 2016] [authz_core:error] [pid 12900:tid 140710963500800] [client 64.120.44.186:56051] AH01630: client denied by server configuration: /var/www/snapmanager/public_html/

I propose to add the following regex to the existing list in the `failregex` variable:

```
^%(_apache_error_client)s (AH01630: )?client denied by server configuration: \S+\s*$
```
### Environment:
- Fail2Ban version (including any possible distribution suffixes): 0.9.3-1
- OS, including release name/version: Ubuntu 16.04.1 LTS
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

**Comment by sebres** [comment]
Fail2ban is a tool, that provides banning functionality with default configs for default configurations of corresponding services. 
It is extreme customizeable and can resp. must be configured for your own requires (in this case configuration `require ip`). 

I think, we've no interested in providing of all possible configuration possibilities, e. g. to react for lot of all possible failures, that apache may throw conditionally any possible config option.

In your case you can easy extend it in your `apache-auth.local` or even directly in your `jail.local`:
```
[Definition]
failregex = %(known/failregex)s
            ^...your custom regex 1...$
            ^...your custom regex 2...$
```

Additionally your log-excerpt, as well as your expression example do not contain a host-IP, which should be banned (our failregex expected `<HOST>` or another failure-ID). 
Otherwise you can build multi-line log expression...
