### ISSUE TITLE
Cannot change chain to different from INPUT.

### ISSUE THREAD

**Issue by soloma** [fail2ban/fail2ban#1590]
Hello.
I'm running fail2ban under Centos 6.7. F2B installed from epel repo. fail2ban version is 0.9.4
I'm trying to change chain to different from INPUT. But unfortunately always get it in IPTABLES.
I've tried to make fresh install with clearing configs and db but no results.

Thank you,
Kirill.

**Comment by soloma** [comment]
fail2ban version is 0.9.4

**Comment by AlexisWilke** [comment]
You'll need to show us what changes you made. Without that, how do you expect us to help?!

Also you may want to explain why you wouldn't want the chain to appear in INPUT. It probably won't be useful if not there?

**Comment by soloma** [comment]
Hello Alexis.
Too large listing, http://dpaste.com/2GY530E.
I want to fell myself free to set in what order packet should be processed throughout the table. I understand that in most cases it will be right to place fail2ban chains to the first place and there are no problems to add additional ignoreip to it. But I want to try to put first my trusted network and devices.

Thank you for understanding,
Kirill.

**Comment by AlexisWilke** [comment]
Ah, now I understand your question.

There is an `actionstart = ...` which attaches the rule to the `INPUT` table using the `-I` (insert) command line option. Insert means that it will added just before the position you indicate. If no position is indicated, then it is inserted at the very beginning.

You could change the `-I` with a `-A` if you do not have a `DROP` rule to "close" your `INPUT` chain.

Otherwise, if you know the number of rules you have in your own set of rules, use that number:

    iptables [-t table] -I chain [rulenum] rule-specification

The `[rulenum]` is the position where it will be inserted. Obviously, as you make changes to your own rules, it could end up moving before/after. In any event, assuming your rules are already added when `fail2ban` starts, you can do:

    actionstart = <iptables> -N f2b-<name>
              <iptables> -A f2b-<name> -j <returntype>
              <iptables> -I <chain> 15 -p <protocol> -m multiport --dports <port> -j f2b-<name>

where the 15 is what I added to insert that new change at position 15.

**Comment by soloma** [comment]
Hello Alexis.
Thank you. As I understand property <chain> cannot be changed. The only way to modify it change all actions in iptables-* configuration file. 
All live as it is.
Thank you

**Comment by sebres** [comment]
All parameters from init block of corresponding action (include chain) can be redefined using three ways:
- directly in jail configuration (jail.local), per jail or for all jails, with redefining chain variable:
```
# jail.local

# for all jails, that use `action_` interpolation:
[DEFAULT]
chain=OTHER

# for single jail (as long as it uses `action_` interpolation):
[your-jail1]
chain=OTHER
# action_ = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
# action = %(action_)s

# for single jail (uses custom action):
[your-jail2]
action = %(banaction)s[chain=OTHER]
```

- Or per action (for all jails using this action) in respective action.local file (iptables-common.local applies to all iptables actions using iptables-common as include):
```
# config/action.d/iptables-common.local
[Init]
chain = OTHER
```
**But only if chain was not overridden in jail self, so this way does not work if jail uses action defined like below, because it will be redefined via `jail.conf` configuration:**
```
chain = INPUT
action_ = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
action = %(action_)s
```

Which parameters supplied to fail2ban action you can see with following command:
```bash
?sudo? fail2ban-client -d | grep "sshd.*action"
```
