### ISSUE TITLE
Enabling jails in jail.d?

### ISSUE THREAD

**Issue by charleslcso** [fail2ban/fail2ban#1596]
### Environment:
OS X 10.7, fail2ban v0.9.5

### The issue:
From jail.conf there is a note that:

> # "enabled" enables the jails.
> #  By default all jails are disabled, and it should stay this way.
> #  Enable only relevant to your setup jails in your .local or jail.d/*.conf
> #
> # true:  jail will be enabled and log files will get monitored for changes
> # false: jail is not enabled
> enabled = false

Currently I get:

> sh-3.2# fail2ban-client status                                                                                                   
> Status
> |- Number of jail:	0
> `- Jail list:	

I can't find anywhere in github that says what should be in folder jail.d... 

Can anyone help?

**Comment by sebres** [comment]
In directory jail.d you can create a file per jail, with name equal to jail and `.conf` as extension.
But this way to configure is rather for maintainer an co...
`jail.local` would be better for you (you can write there your customisations only, don't copy jail.conf as local)

**Comment by charleslcso** [comment]
Thanks for your reply

I've been using 0.8.4, so the change of requirements is rather new to me. 

I'm still confused about what needs to be written in jail.local...

In 0.8.4 there's the filters.d folder. So I should migrate what's in it, consolidate the filters into 1 file named jail.local?

Thanks!

**Comment by sebres** [comment]
All the settings in local files overrides that in corresponding conf files, the `jail.local` is thereby a counterpart of `jail.conf`. It is not good solution to change direct in conf file. So you will prevent a los of your changes after update, resp. merge with stock configs if they are changed.
filter.d folder contains a filter configurations only (e. g. failregex, irgnoreregex, etc.) for corresponding jail (or multiple jails) - if you have own filter, better to hold it as .local instead of .conf, because of above mentioned reason (you can rename it). All the changes you made in stock .cond files will be overwritten by update to newer version.

**Comment by charleslcso** [comment]
I created a jail.local file and it contains:

bantime = 3600
before = paths-osx.conf
[DEFAULT]
ignoreip = 127.0.0.1/8
ignorecommand =
bantime  = 600
findtime  = 600
maxretry = 3
backend = auto
usedns = warn
enabled = true
...
[postfix]

port     = smtp,465,submission
logpath  = %(postfix_log)s
backend  = %(postfix_backend)s

But fail2ban-client status still shows 0 jails.



Can you kindly provide an example jail.local?

**Comment by sebres** [comment]
- 2 first entries are sectionsless
- enabling of all jails (in default section) is not good idea
- only changes belongs there (not unchanged entries from stock conf
- the local-file takes place in the same folder as con ft file
- you've not a mix from config files 0.8 and 0.9, or?
- example of jail.local:
```
[DEFAULT] 
backend = pyinotify 
default_backend = pyinotify 
[sshd] 
enabled = true
[pam-generic] 
enabled = true
```
- you can see dump of your current config with:
`fail2ban-client -vv -d`
