### ISSUE TITLE
fail2ban fails to ban IPs even though filter matches

### ISSUE THREAD

**Issue by johannburkard** [fail2ban/fail2ban#1601]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.8.11-1
- OS, including release name/version: Ubuntu 14.04.5 LTS
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

I'm trying to ban garbage postfix traffic:

Nov  6 13:06:28 johannburkard postfix/smtpd[58353]: connect from unknown[87.236.215.57]
Nov  6 13:06:33 johannburkard postfix/smtpd[58353]: lost connection after AUTH from unknown[87.236.215.57]
Nov  6 13:06:33 johannburkard postfix/smtpd[58353]: disconnect from unknown[87.236.215.57]

I've created two rules in postfix.conf that ``fail2ban-regex`` says match:

```
^%(__prefix_line)slost connection after AUTH from.+\[<HOST>\].*$
lost connection after (AUTH|UNKNOWN|EHLO) from (.*)\[<HOST>\].*$
```

But fail2ban never bans the IPs.

#### Expected behavior

Fail2ban bans the offending IPs.

#### Observed behavior

Fail2ban doesn't ban the offending IPs.

#### Configuration, dump and another helpful excerpts

```
# cat /etc/fail2ban/filter.d/postfix.conf
# Fail2Ban filter for selected Postfix SMTP rejections
#
#

[INCLUDES]

# Read common prefixes. If any customizations available -- read them from
# common.local
before = common.conf

[Definition]

_daemon = postfix/smtpd

failregex = ^%(__prefix_line)slost connection after AUTH from.+\[<HOST>\].*$
            ^%(__prefix_line)sNOQUEUE: reject: RCPT from \S+\[<HOST>\]: 554 5\.7\.1 .*$
            ^%(__prefix_line)sNOQUEUE: reject: RCPT from \S+\[<HOST>\]: 450 4\.7\.1 : Helo command rejec$
            ^%(__prefix_line)sNOQUEUE: reject: VRFY from \S+\[<HOST>\]: 550 5\.1\.1 .*$
            lost connection after (AUTH|UNKNOWN|EHLO) from (.*)\[<HOST>\].*$

ignoreregex = 

# Author: Cyril Jaquier
```

#### Any customizations done to /etc/fail2ban/ configuration
```
loglevel = 4
```

#### Relevant parts of /var/log/fail2ban.log file:

```
2016-11-06 13:04:28,479 fail2ban.filter : DEBUG  Default Callback for Event: <Event dir=False mask=0x2 maskname=IN_MODIFY name='' path=/var/log/mail.log pathname=/var/log/mail.log wd=2 >
2016-11-06 13:04:28,480 fail2ban.filter.datedetector: DEBUG  Matched time template MONTH Day Hour:Minute:Second
2016-11-06 13:04:28,480 fail2ban.filter.datedetector: DEBUG  Got time using template MONTH Day Hour:Minute:Second
2016-11-06 13:04:28,480 fail2ban.filter.datedetector: DEBUG  Sorting the template list
2016-11-06 13:04:28,480 fail2ban.filter.datedetector: DEBUG  Winning template: MONTH Day Hour:Minute:Second with 5002 hits
```

#### Relevant lines from monitored log files in question:

```
Nov  6 13:07:21 johannburkard postfix/smtpd[59355]: connect from unknown[87.236.215.57]
Nov  6 13:07:24 johannburkard postfix/smtpd[59355]: lost connection after AUTH from unknown[87.236.215.57]
Nov  6 13:07:24 johannburkard postfix/smtpd[59355]: disconnect from unknown[87.236.215.57]
Nov  6 13:07:26 johannburkard postfix/smtpd[59355]: connect from unknown[87.236.215.57]
Nov  6 13:07:40 johannburkard postfix/smtpd[59355]: lost connection after EHLO from unknown[87.236.215.57]
Nov  6 13:07:40 johannburkard postfix/smtpd[59355]: disconnect from unknown[87.236.215.57]
```

**Comment by sebres** [comment]
I don't think, that banning by lost connection is a good idea, just to answer your question...

If `fail2ban-regex` finds expected entries, but `fail2ban` does not - it just means one: fail2ban works with another configuration as specified, so either you've not restarted fail2ban after changing of the config files, or you've not specified your filter in expected jail (in jail.conf/jail.local normally via parameter `filter` or if not specified equal with name of jail).

To test, the regex will be used by fail2ban, dump your current configuration, e. g. like:
```
fail2ban-client -d | grep "lost connection"
```
If all are correct (you find your expression) - just restart fail2ban.

BTW anchored expression `.*$` makes no sense at all, so replace it with something reasonable (like in my example below - `\s*$` - spaces possible) or just remove completely. You can also combine first and last regex:
```
failregex = ^%(__prefix_line)slost connection after (AUTH|UNKNOWN|EHLO) from [^\[]*\[<HOST>\]\s*$
```

Secondly, saving of your own files (resp. customizing of stock files directly in) is not so good (can be overridden with update to newer version, or be incompatible hereafter if the stock config will be changed).

So nstead of editing of `/etc/fail2ban/filter.d/postfix.conf`, just create `/etc/fail2ban/filter.d/postfix.local` like this (for example since fail2ban version 0.9.2 you can use `%(known/failregex)s`, not possible in 0.8):
```
# >= 0.9.2
[Definition]
failregex = %(known/failregex)s
            ^%(__prefix_line)slost connection after (AUTH|UNKNOWN|EHLO) from [^\[]*\[<HOST>\]\s*$

# <= 0.9.1
[Definition]
failregex = ...stock regex 1...
            ...
            ...stock regex N...
            ^%(__prefix_line)slost connection after (AUTH|UNKNOWN|EHLO) from [^\[]*\[<HOST>\]\s*$
```

This will extend the list of expressions, provided with stock configuration `postfix.conf` (add a new custom rule).

**Comment by sebres** [comment]
BTW 0.8.11 is too old, no support for it anymore (better seek support 
from the distribution you obtained Fail2Ban from)

**Comment by johannburkard** [comment]
Thank you for the answer. Indeed the wrong filter was set up.
