### ISSUE TITLE
QQ: trying to monitor a log for messages and run command but...

### ISSUE THREAD

**Issue by mgaulton** [fail2ban/fail2ban#1604]
These are logs that have no IP or host or port information associated to them. it's a simple phase that I need to match and run a command if found. Since I already use fail2ban , i don't want to add another app/script to the mix but I'm unclear how to accomplish what i'm looking for.

monitor stuff.log, if "Server did not respond!", then run "/user/bin/script.sh"

Any suggestions (examples) would be appreciated.

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):Fail2Ban v0.9.5
- OpenSuse Leap 42
- [ x] Fail2Ban installed via OS/distribution mechanisms
- [x ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

**Comment by sebres** [comment]
Is theoretically possible with fail2ban, since no-host banning was implemented from me (v. 0.9.5 or 0.10). See #1454.

But you've no failure-id at all, so additionally you should:
- set empty or something other as match for failure-id (still host in 0.9th-branch) in `failregex`, in your case something like `^Server did not respond!(?P<host>)$` (empty, I don't know it is good enough) or something like `^(?P<host>Server) did not respond!$` (imho may be better, because fail2ban was never tested with pure empty failure ID);
- set `maxretry = 1` and `findtime = 1` (ban after first occurrence in 1 seconds);
- set small `bantime` (e. g. 1 second) to this "jail" (otherwise no "ban" action will be executed in this time, because "already banned" occurs), e. g. `bantime = 1`
- you need to specify only `actionban` parameter in your custom action file (`actionban = /user/bin/script.sh`); 
- actionban script will be executed as root (or with user, fail2ban running), so use `su` if other/restricted user needed;
- set usedns, ignoreip, ignorecommand as suggested in #1454, otherwise you can get error by comparison with empty/illegal host (that will be found by "failure");

Hope, this helps

**Comment by mgaulton** [comment]
That definitely gives me something to work with, i'll give it a hack. Thank you very much.

**Comment by sebres** [comment]
close since it should be answered, give feedback here if I'm wrong

**Comment by 7starsone** [comment]
Hello, sorry to up this...
just a question:
so, as I understand, is it possible to run a command instead of a ban?

That is, in a particular case, I just need to run a command, I don't need a ban or bantime.

Is it possible?
what are the correct steps?
1) create a .conf file in action.d folder?
2) on jail.local the bantime will be ignored?
3) on jail.local do I just need to use action = "my new action" ?

Can you write a working example, please?

Thanks

**Comment by sebres** [comment]
The easiest action with single command as `actionban` will be enough, see for example:
https://github.com/fail2ban/fail2ban/blob/c0994b0c6c2d4760f137ee3fdc1bf06c37a190dd/config/action.d/badips.conf#L11-L13

So if you've new action `action.d/my-cmd.conf`, then it is enough to add following into jail.local:
```INI
[my-jail]
logpath =/path/to/log/
filter =
failregex = ^failure from <HOST> - unknown user$
bantime = 0
action = my-cmd[param1="...", param2=...]
```

That's it.

**Comment by 7starsone** [comment]
ok, thanks but I guess it could be an issue in this case, eg.:

- a specific string appears 30 times in a minute (findtime 60, maxretry 30)
- I run a command
- since I don't ban an IP, how fail2ban understands that it doesn't repeat that command if it doesn't happen again later?

hope my example's clear

**Comment by sebres** [comment]
Value `bantime = 0` means that the ticket will get unbanned immediately after ban.
So it finds `maxretry` failures during `findtime`, bans the ticket (execute your command), unbans after 0 seconds.... so it is ready to accept further failures from same address.

If you want the converse (don't execute this command during some time) you can vice versa set the bantime, thus  `bantime = 60` means that 60 seconds after last ban any other failures will be ignored.
But note, because it is not really banned, in this case you can get many log messages in fail2ban.log - `NOTICE  [my-jail] 1.2.3.4 already banned`.

Possibly a new option like `ignore_already_banned` could be implemented to "fix" it (for silently ignoring).

**Comment by 7starsone** [comment]
I write the complete example to let you understand. 
php-fpm randomly becomes unresponsive even on low server load. So, not a problem about CPU/RAM resources. Since at the moment is impossible to know what's the culprit, this happens on error log:

[Thu Mar 08 10:53:50.824497 2018] [proxy_fcgi:error] [pid 5963:tid 140604000233216] (104)Connection reset by peer: [client xx.xx.xxx.xx:5939] AH01075: Error dispatching request to :

where xx.xx.xxx.xx is an IP address
when it happens many times in a minute, it means that php-fpm is unresponsive regardless of the system resource. The server load average could be even at 0,x but it happens the same, even if after a long time.

So, the only way to fix, at the moment, is to do a `service php-fpm restart` (or reload)

How should I do so that it runs the command if that happened at 10:53 (as in this example) but it has **not** to repeat if that doesn't happen again later, after 10:53 (the last time it happened)?

At the moment, is it possible with fail2ban?

**Comment by sebres** [comment]
> php-fpm randomly becomes unresponsive
> the only way to fix, at the moment, is to do a service php-fpm restart (or reload)

I doubt it is good solution, possibly something is wrong there...

> At the moment, is it possible with fail2ban?

The short answer is yes.

How you can do it for not IP-related messages see in our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-to-ban-something-other-as-host-(IP-address),-like-user-or-mail,-etc.)
