### ISSUE TITLE
Enabling of multiple of same action in single jail fails with "Action already exists"

### ISSUE THREAD

**Issue by tgoodlet** [fail2ban/fail2ban#1611]
I ripped this verbatim out of @chris001's comment on #798 since it's exactly what I'm seeing.

I have tested this on `0.9.4`

>Am getting this same error on fail2ban 0.9.3 on CentOS 7.
These lines are from the relevant section of /etc/fail2ban/jail.conf
```
[asterisk]

enabled  = true
filter   = asterisk
action   = iptables-multiport[name=asterisk-tcp, port="5060,5061", protocol=tcp]
           iptables-multiport[name=asterisk-udp, port="5060,5061", protocol=udp]
           iptables-allports[name=ASTERISK, protocol=all]
           sendmail-whois[name=ASTERISK, dest=root, sender=asterisk@fail2ban.local]
logpath  = /var/log/asterisk/full
maxretry = 5
bantime  = 1800
```

>Fail2ban is complaining, Action iptables-multiport already exists.
```
Sep 03 01:25:01 mydomain.com fail2ban-client[16206]: 2016-09-03 01:25:01,768 fail2ban.server         [16224]: INFO    Starting Fail2ban v0.9.3
Sep 03 01:25:01 mydomain.com fail2ban-client[16206]: 2016-09-03 01:25:01,768 fail2ban.server         [16224]: INFO    Starting in daemon mode
Sep 03 01:25:02 mydomain.com fail2ban-client[16206]: ERROR  NOK: ('Action iptables-multiport already exists',)
Sep 03 01:25:02 mydomain.com systemd[1]: Started Fail2Ban Service.
```
>And so fail2ban 0.9.3 only adds the asterisk rule for udp, and not the rule for tcp.

```
~$ iptables -nL | grep f2b-
f2b-ASTERISK  all  --  0.0.0.0/0            0.0.0.0/0
f2b-asterisk-udp  udp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 5060,5061
f2b-BadBots  tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 80,443
f2b-SSH    tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:22
Chain f2b-ASTERISK (1 references)
Chain f2b-BadBots (1 references)
Chain f2b-SSH (1 references)
Chain f2b-asterisk-udp (1 references)
```

**Comment by sebres** [comment]
Nope, it is not the chain name, but the same action name in single jail.

Your definition for "multiple of same action in a single jail" is wrong: **you should give different `actname` for that**. 
Proper example:
```
action = iptables-multiport[actname=asterisk-tcp, name=asterisk-tcp, port="5060,5061", protocol=tcp]
         iptables-multiport[actname=asterisk-udp, name=asterisk-udp, port="5060,5061", protocol=udp]
```
The parameter `name` (that you correctly set also) is action oriented (pure action runtime parameter, in case of iptables it is a part of chain like `f2b-<name>`), and can mean quite another matter in other actions or quite without meaning.

This possibility was introduced a long time ago by @kwirk (on 25 Apr 2013) in 45c9c45b41e6b1c6de3a2ae9764666ed515e7694. Thus it is available since version 0.9.0.

Closed as invalid

**Comment by sebres** [comment]
Reference to #189

**Comment by tgoodlet** [comment]
@sebres oh wow thanks for the explanation; your suggestion worked!

Now my question is where is this documented?

**Comment by sebres** [comment]
> where is this documented?

see https://github.com/fail2ban/fail2ban/pull/189/files#diff-f6e691903ae372ab1383d4085868d948R63
or 
`man jail.conf | grep actname`

BTW looking on https://github.com/fail2ban/fail2ban/blob/master/config/jail.conf#L699
In our default `jail.conf` it was already set correctly for asterisk jail (still one example for you, so I'll say RTFM and default configs ;)

**Comment by gnat** [comment]
Is there some reason `actname` should not simply be an alias for `name` ? Would save a lot of confusion for others. How many names do we really need...

**Comment by sebres** [comment]
> Is there some reason actname should not simply be an alias for name ?

Yes it is, because `name` is basically name of jail and `actname` is name of action.
The originated roots coming from the fact that some jails can have two actions of the same type, e. g. 2 banning actions one for tcp protocol, another for udp protocol (not every action can ban both within single action), what could cause a naming conflict otherwise (if also name of jail is required in action for some reason).

In some version (I guess 0.10.x) `actname` is not mandatory anymore - now it is automatically interpolated from jail name (and action name if it were not unique), but this was not always the case (so I try to provide it in examples still with `actname`, because some people can copy-paste it to configs of 0.9 or even 0.8 versions).

For example here it does not matter (and as you can see actname is not provided here anymore):
https://github.com/fail2ban/fail2ban/blob/725354c79315d8eac6cdc7ffa550a8acb9a01d73/config/jail.conf#L737-L738

> Would save a lot of confusion for others.

What do you talking about? What exactly and where gets confused?
