### ISSUE TITLE
Make adding a jail straight-forward

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1650]
It is possible to add a jail during runtime:
```bash
$ fail2ban-client add apache-cf1-instant auto
$ fail2ban-client get apache-cf1-instant actions
No actions for jail apache-cf1-instant

$ fail2ban-client reload apache-cf1-instant
$ fail2ban-client get apache-cf1-instant actions
The jail apache-cf1-instant has the following actions:
cloudflare, sendmail-geoip-lines
```

Could we make it easier thus in one command?

**Comment by szepeviktor** [comment]
I have 100+ banned IP-s, it is very painful to do full `fail2ban-client reload`

**Comment by sebres** [comment]
0.10th reload (in oposite to restart) does not unbans resp. rebans the IPs, it just read config and updates running instance - regarding new jails, actions, filter rules etc.

**Comment by szepeviktor** [comment]
https://github.com/fail2ban/fail2ban/pull/1557

**Comment by alasdairdc** [comment]
For anyone visiting this and stuck on a version pre 0.10 you could add the jail by hand:

taken from [fail2ban-manually-create-jail.md ](https://gist.github.com/alasdairdc/e7f1986b57e974555349a9c38058c1c3)

- Modify `jail.local` and add any required files to `filter.d` / `action.d`
- Interrogate `jail.local` / `filter.d` / `action.d` for settings to use
- Interrogate existing running jail for useful items (if neccessary)
- Use `fail2ban-client` to create and start new jail.

To elaborate

- commands for interrogation of running jail

```
# fail2ban-client get ssh ignoreip
These IP addresses/networks are ignored:
|- 127.0.0.1/8
|- another ip
`- last ip

# fail2ban-client get ssh actionstart iptables-multiport
iptables -N fail2ban-<name>
iptables -A fail2ban-<name> -j RETURN
iptables -I <chain> -p <protocol> -m multiport --dports <port> -j fail2ban-<name>
```

- Commands used to create and start jail
- here I've used `new-jail` as the name of the jail you want to create (you may wish to keep it the same as you've defined in `jail.local` for consistency)
- `{my-logpath}` is what you would define `logpath` as in your `jail.local`
- `{my-regex}` is a quoted string (due to bash expansions) of what you would define `failregex` as in your `jail.local`
- repeat the line with `addignoreip` for all addresses to use for `ignoreip`
- the values used for `actionstart`, `actioncheck`, `actionstop`, `actionban`, `actionunban` are the same as those that were already in use for `iptables-allports` within another jail
- Unsure if it the version I was using or not but most `fail2ban` variables found had to be expanded when using this way i.e. note `<name>`, `<port>`, `<protocol>`, `<chain>`, `<blocktype>` have all be replaced in the below statements.  The only variables I left in the statements were `<ip>` for the `iptables-allports` statements and `<HOST>` in the `addfailregex` statement
```
# fail2ban-client add new-jail auto
# fail2ban-client set new-jail maxretry 1
# fail2ban-client set new-jail findtime 2592000
# fail2ban-client set new-jail bantime 604800
# fail2ban-client set new-jail addlogpath {my-logpath}
# fail2ban-client set new-jail addfailregex '{my-regex}'
# fail2ban-client set new-jail addignoreip 127.0.0.1/8
# fail2ban-client set new-jail addaction iptables-allports
# fail2ban-client set new-jail actionstart iptables-allports 'iptables -N fail2ban-new-jail
iptables -A fail2ban-new-jail -j RETURN
iptables -I INPUT -p tcp -j fail2ban-new-jail'
# fail2ban-client set new-jail actioncheck iptables-allports "iptables -n -L INPUT | grep -q 'fail2ban-new-jail[ \t]'"
# fail2ban-client set new-jail actionstop iptables-allports "iptables -D INPUT -p tcp -j fail2ban-new-jail
iptables -F fail2ban-new-jail
iptables -X fail2ban-new-jail"
# fail2ban-client set new-jail actionban iptables-allports "iptables -I fail2ban-new-jail 1 -s <ip> -j REJECT --reject-with icmp-port-unreachable"
# fail2ban-client set new-jail actionunban iptables-allports "iptables -D fail2ban-new-jail -s <ip> -j REJECT --reject-with icmp-port-unreachable"
# fail2ban-client start new-jail
```
