### ISSUE TITLE
Many fail2ban entries into iptables (DDOS attack) causes extremely slow system response

### ISSUE THREAD

**Issue by gravyboat** [fail2ban/fail2ban#1654]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.9.3-1
- OS, including release name/version: Ubuntu 15.10 (wily)
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below if so):
  general additional jail entries.

### The issue:

We noticed recently during a DDOS attack that fail2ban was managing/adding so many entries to iptables that it caused extremely slow system responses. (over 246 recidive jail (config below) entries alone per instance).

#### Steps to reproduce

You can set up jails similar to the ones I have below that reviews Nginx logs and then attempt to DDOS the server so many entries are added and managed, or have to be swapped between jails.

#### Expected behavior

Server responses occur within an acceptable time frame.

#### Observed behavior

Server responses become extremely slow (slow command execution, slow responses, etc. while fail2ban is running).

#### Any additional information

I believe this is either related to how lookups are happening when an address is moved between the main jails and the recidive jail, or that fail2ban is having issues with reading a large amount of log data (something I have never had an issue with before). There are no errors or warnings in the log, fail2ban is working correctly, the server just becomes extremely slow. I am happy to admit this is most likely a problem with the iptables interaction if that is the case, however this issue does not occur when fail2ban is not running (many of the IPs remain in iptables and the server performs without issue). 

If I've somehow set up my configuration in a way that could potentially lead to this scenario please let me know, or if I should look at other applications for this sort of high traffic attack. I should also note this is running on multiple systems which are load balanced over in AWS so resource utilization from reading the logs shouldn't be problematic.

### Configuration, dump and another helpful excerpts

Unfortunately there isn't any error output, as fail2ban is still working, it's just causing slowness as noted above. This problem does not manifest as a RAM/CPU/disk I/O issue (which leads me to believe there is some other system wait going on).

#### Any customizations done to /etc/fail2ban/ configuration

jail.local:
```
[nginx-wpcomments]
action = iptables-multiport[name=wpcomments, port="http,https"]
enabled = true
filter = nginx-wpcomments
logpath = /var/log/nginx*/*access*.log
maxretry = 6
port = http,https

[nginx-wplogin]
action = iptables-multiport[name=wplogin, port="http,https"]
enabled = true
filter = nginx-wplogin
logpath = /var/log/nginx*/*access*.log
maxretry = 6
port = http,https

[nginx-xmlrpc]
action = iptables-multiport[name=xmlrpc, port="http,https"]
enabled = true
filter = nginx-xmlrpc
logpath = /var/log/nginx*/*access*.log
maxretry = 6
port = http,https

[recidive]
action = iptables-allports[name=f2b-recidive]
bantime = 604800
enabled = true
filter = recidive
logpath = /var/log/fail2ban.log
maxretry = 6
```
nginx-wpcomments.local filter:
```
[Definition]
failregex = ^<HOST> .*POST .*wp-comments-post\.php.*
```
nginx-wplogin.local:
```
[Definition]
failregex = ^<HOST> .*POST .*wp-login\.php.*
```
nginx-xmlrpc:
```
[Definition]
failregex = ^<HOST> .*POST .*xmlrpc\.php.*
```

The recidive jail is the standard one that ships with fail2ban.

#### Relevant parts of /var/log/fail2ban.log file:

As noted above I don't have these on hand as the issue happened a while back and logs rotated out, I did review the logs however (though not log level 4) and there were no errors, fail2ban was just extremely busy dealing with problematic addresses.

#### Relevant lines from monitored log files in question:

N/A

**Comment by sebres** [comment]
Firstly, many failregex (or filter) that can be found in internet (forums, etc) have bad performance at all (e. g. because of poor regex's within).
So for example all the `nginx-*` filter you've provided in your config excerpt are not the stock filter (we cannot resp. do not want to estimate the quality of it). Provided regex's look very-very strange (greedy catch-all, etc) and vulnerable.

Secondly, observing of pure nginx access.log may be also at all very bad idea, if too many entries will be written in the access-log. You can for example use different logs target for locations handling 401, 403, etc or such as your cases like wp-login, etc (pre-filtering on the side of nginx).

And last but not least:
- try to use 0.10th fail2ban version (from 10 to 50 times faster as 0.9th);
- use pyinotify or systemd backends of fail2ban (more faster as polling or gamin);
- don't use recidive if you don't know what you do exactly (e. g. better something like ban-time-incr resp. own actions that additionally write bad IPs only in own recidive.log, that will be observed instead of fail2ban.log;

Fail2ban is neither a IDS, IPS nor the DDOS prevention system. You can do many things thus, but it is not panacea out-of-the-box. Use it as tool that should be properly configured, combine it with another tools, then it can help.

I'll close this issue, because we cannot help you at that.

**Comment by gravyboat** [comment]
Hey @sebres thanks for the response. I'll look into these suggestions and see what I can do to improve things, thanks for your time and working on this project. As a note it was never meant to be a DDOS protector, it just happened that we were attacked in such a way that traffic was making it through to the Nginx systems so fail2ban was taking much of the workload. Thanks again!

**Comment by mitchellkrogza** [comment]
Hi Forrest

I have several hundred IP’s blocked by Fail2Ban in IPTables using Recidive
without any lag at all, also running Nginx.
Had a look at your Regex’s and they differ slightly from what I use, not
sure if this may have anything to do with it at all but worth mentioning.

*Your Regex for wp-login:*
failregex = ^<HOST> .*POST .*wp-login\.php.*

*My Regex for wp-login:*
failregex = ^<HOST> - .*] "POST /wp-login.php HTTP/1.1” 500

Also not sure of your formatting for the jails either

*Your jail for wp-login: (the bolded line is unnecessary and possibly
causing problems)*

[nginx-wplogin]
*action = iptables-multiport[name=wplogin, port="http,https"]*
enabled = true
filter = nginx-wplogin
logpath = /var/log/nginx*/*access*.log
maxretry = 6
port = http,https

*My jail for wp-login:*

[wp-login]
enabled  = true
port     = http,https
filter   = wp-login
logpath = %(nginx_access_log)s
maxretry = 3

I specify my action once only much higher up in the jail.local file, not
with each jail.

action = %(action_mwl)s

Also try using the new formatting for logpath as %(nginx_access_log)s
and then edit paths-common.conf and paths-debian.conf and change the line

nginx_access_log = /var/log/nginx/*access*.log

Have you also tried resetting Fail2Ban so it can start off clean and
rebuild it’s log file and database?

sudo service fail2ban stop
sudo truncate -s 0 /var/log/fail2ban.log
sudo rm /var/lib/fail2ban/fail2ban.sqlite3
sudo service fail2ban restart

Have a look at my jail.local setup below (comments stripped),
iptables-multiport is enabled much higher up before your jails with the
banaction = not with every jail unless you specifically want to use
different banactions on each jail but then use banaction and not action

[INCLUDES]
before = paths-debian.conf
[DEFAULT]
ignoreip = 127.0.0.1/8 2.2.2.2 3.3.3.3;
ignorecommand =
bantime  = 600
findtime  = 600
maxretry = 6
backend = auto
usedns = warn
logencoding = auto
enabled = false
filter = %(__name__)s
destemail = security@mydomain.com
sender = security@mydomain.com
sendername = Fail2Ban
mta = mail
protocol = tcp
chain = INPUT
port = 0:65535
*banaction = iptables-multiport*
action_ = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s",
port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
action_mw = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s",
port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
action_mwl = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s",
port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
             %(mta)s-whois-lines[name=%(__name__)s, dest="%(destemail)s",
sender="%(sender)s", logpath=%(logpath)s, chain="%(chain)s"]
action_xarf = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s",
port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
             xarf-login-attack[service=%(__name__)s, sender="%(sender)s",
logpath=%(logpath)s, port="%(port)s"]
action_cf_mwl = cloudflare[cfuser="%(cfemail)s", cftoken="%(cfapikey)s"]
                %(mta)s-whois-lines[name=%(__name__)s,
dest="%(destemail)s", logpath=%(logpath)s, chain="%(chain)s"]
action_blocklist_de  = blocklist_de[email="%(sender)s", service=%(filter)s,
apikey="%(blocklist_de_apikey)s"]
action_badips = badips.py[category="%(name)s", banaction="%(banaction)s"]
*action = %(action_mwl)s*
# NOW SETUP JAILS BELOW


Have you also checked permissions on the log files, perhaps there is some
log files there that Fail2Ban is having difficulty reading or accessing?
Could perhaps be some kind of permissions issue that is not being logged
anywhere that is causing you this slowdown.

Have you checked if there is anything logged in:
/var/log/syslog

KR
Mitchell



From: Forrest <notifications@github.com> <notifications@github.com>
Reply: fail2ban/fail2ban
<reply@reply.github.com>
<reply@reply.github.com>
Date: 05 January 2017 at 2:40:54 AM
To: fail2ban/fail2ban <fail2ban@noreply.github.com>
<fail2ban@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  [fail2ban/fail2ban] Many fail2ban entries into iptables (DDOS
attack) cause extremely slow system response (#1654)

Environment:

   - Fail2Ban version (including any possible distribution suffixes):
   0.9.3-1
   - OS, including release name/version: Ubuntu 15.10 (wily)
   - Fail2Ban installed via OS/distribution mechanisms
   - You have not applied any additional foreign patches to the codebase
   - Some customizations were done to the configuration (provide details
   below if so):
   general additional jail entries.

The issue:

We noticed recently during a DDOS attack that fail2ban was managing/adding
so many entries to iptables that it caused extremely slow system responses.
(over 246 recidive jail (config below) entries alone per instance).
Steps to reproduce

You can set up a jail similar to the ones I have below that reviews Nginx
logs and then attempt to DDOS the server so many entries are added and
managed, or have to be swapped between jails.
Expected behavior

Server responses occur within an acceptable time frame.
Observed behavior

Server responses become extremely slow (slow command execution, slow
responses, etc. while fail2ban is running).
Any additional information

I believe this is either related to how lookups are happening when an
address is moved between the main jails and the recidive jail, or that
fail2ban is having issues with reading a large amount of log data
(something I have never had an issue with before). There are no errors or
warnings in the log, fail2ban is working correctly, the server just becomes
extremely slow. I am happy to admit this is most likely a problem with the
iptables interaction if that is the case, however this issue does not occur
when fail2ban is not running (many of the IPs remain in iptables and the
server performs without issue). If I'm somehow set up my configuration in a
way that could potentially lead to this scenario please let me know. I
should also note this is running on multiple systems which are load
balanced over in AWS so resource utilization from reading the logs
shouldn't be problematic.
Configuration, dump and another helpful excerpts

Unfortunately there isn't any error output, as fail2ban is still working,
it's just causing slowness as noted above. This problem does not manifest
as a RAM/CPU/disk I/O issue (which leads me to believe there is some other
system wait going on).
Any customizations done to /etc/fail2ban/ configuration

jail.local:

[nginx-wpcomments]
action = iptables-multiport[name=wpcomments, port="http,https"]
enabled = true
filter = nginx-wpcomments
logpath = /var/log/nginx*/*access*.log
maxretry = 6
port = http,https

[nginx-wplogin]
action = iptables-multiport[name=wplogin, port="http,https"]
enabled = true
filter = nginx-wplogin
logpath = /var/log/nginx*/*access*.log
maxretry = 6
port = http,https

[nginx-xmlrpc]
action = iptables-multiport[name=xmlrpc, port="http,https"]
enabled = true
filter = nginx-xmlrpc
logpath = /var/log/nginx*/*access*.log
maxretry = 6
port = http,https

[recidive]
action = iptables-allports[name=f2b-recidive]
bantime = 604800
enabled = true
filter = recidive
logpath = /var/log/fail2ban.log
maxretry = 6

nginx-wpcomments.local filter:

[Definition]
failregex = ^<HOST> .*POST .*wp-comments-post\.php.*

nginx-wplogin.local:

[Definition]
failregex = ^<HOST> .*POST .*wp-login\.php.*

nginx-xmlrpc:

[Definition]
failregex = ^<HOST> .*POST .*xmlrpc\.php.*

The recidive jail is the standard one that ships with fail2ban.
Relevant parts of /var/log/fail2ban.log file:

As noted above I don't have these on hand as the issue happened a while
back and logs rotated out, I did review the logs however (though not log
level 4) and there were no errors, fail2ban was just extremely busy dealing
with problematic addresses.
Relevant lines from monitored log files in question:

N/A

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fail2ban/fail2ban/issues/1654>, or mute the thread

**Comment by gravyboat** [comment]
Thanks for your detailed response @mitchellkrogza, I've done most of your suggested troubleshooting steps already in terms of cleaning things up (and there wasn't anything in syslog, it was one of the first things I checked), it's more a concern if we encounter this issue when someone isn't around it could potentially negatively impact the systems. 

I'll go through and clean up the jails and implement some of your suggestions to see if we can speed things up, I'll also look at getting onto a newer release, as I think that 0.9 release is the last one available for wily so I'll see what I can do on that end as I wasn't aware the more recent releases were such a drastic improvement performance wise. Thanks again for your detailed response and suggestions, in the event that these suggestions improve things I'll report back so others who might stumble into this issue have a direction to go in and some information on the results!

**Comment by mitchellkrogza** [comment]
No problem, hope you pin down the problem. I am still using 0.9.3 with those config's above. I am about to start testing 0.10 on a testbench before I put it into production but so far 0.9.3 is stable and fast for me. Please do report back on your findings.

For the benefit of future readers of this comment my email response did not support markdown so I am pasting below what I wrote with better formatting.

**Your Regex for wp-login:** 
`failregex = ^<HOST> .*POST .*wp-login\.php.* `

**My Regex for wp-login:** 
`failregex = ^<HOST> - .*] "POST /wp-login.php HTTP/1.1” 500` 

Also not sure of your formatting for the jails either 

**Your jail for wp-login:**  
```
[nginx-wplogin] 
action = iptables-multiport[name=wplogin, port="http,https"] 
enabled = true 
filter = nginx-wplogin 
logpath = /var/log/nginx*/*access*.log 
maxretry = 6 
port = http,https 
```

**My jail for wp-login:** 
```
[wp-login] enabled = true 
port = http,https 
filter = wp-login 
logpath = %(nginx_access_log)s 
maxretry = 3 
```

I specify my action once only much higher up in the jail.local file, not with each jail. action = %(action_mwl)s Also try using the new formatting for logpath as %(nginx_access_log)s and then edit paths-common.conf and paths-debian.conf and change the line nginx_access_log = /var/log/nginx/*access*.log 

Have you also tried resetting Fail2Ban so it can start off clean and rebuild it’s log file and database? 

```
sudo service fail2ban stop 
sudo truncate -s 0 /var/log/fail2ban.log 
sudo rm /var/lib/fail2ban/fail2ban.sqlite3 
sudo service fail2ban restart 
```

Have a look at my jail.local setup below (comments stripped), iptables-multiport is enabled much higher up before your jails with the banaction = not with every jail unless you specifically want to use different banactions on each jail but then use banaction and not action 

```
[INCLUDES] 
before = paths-debian.conf 
[DEFAULT] 
ignoreip = 127.0.0.1/8 2.2.2.2 3.3.3.3; 
ignorecommand = 
bantime = 600 
findtime = 600 
maxretry = 6 
backend = auto 
usedns = warn 
logencoding = auto 
enabled = false 
filter = %(__name__)s 
destemail = security@mydomain.com 
sender = security@mydomain.com 
sendername = Fail2Ban 
mta = mail 
protocol = tcp 
chain = INPUT 
port = 0:65535 
banaction = iptables-multiport 
action_ = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"] 
action_mw = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"] 
action_mwl = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"] %(mta)s-whois-lines[name=%(__name__)s, dest="%(destemail)s", sender="%(sender)s", logpath=%(logpath)s, chain="%(chain)s"] 
action_xarf = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"] xarf-login-attack[service=%(__name__)s, sender="%(sender)s", logpath=%(logpath)s, port="%(port)s"] 
action_cf_mwl = cloudflare[cfuser="%(cfemail)s", cftoken="%(cfapikey)s"] %(mta)s-whois-lines[name=%(__name__)s, dest="%(destemail)s", logpath=%(logpath)s, chain="%(chain)s"] 
action_blocklist_de = blocklist_de[email="%(sender)s", service=%(filter)s, apikey="%(blocklist_de_apikey)s"] 
action_badips = badips.py[category="%(name)s", banaction="%(banaction)s"] 
action = %(action_mwl)s 
# NOW SETUP JAILS BELOW 
```

**Comment by gravyboat** [comment]
@mitchellkrogza I haven't seen the bad bot blocker before, I'll take a look at it tomorrow!
