### ISSUE TITLE
Redirect donations

### ISSUE THREAD

**Issue by lostcontrol** [fail2ban/fail2ban#1679]
Hi Fail2ban devs,

Since the beginning, I receive donations for this project. Even if I'm still in the top 3 contributors in terms of commits, I'm not active on this project since many years and don't deserve these donations. I pay for the domain name (fail2ban.org) and host the (outdated installation, sorry) wiki on my private server but that's something I'm willing to sponsor for free.

I would like the donations to go to people who really deserve them. That's not me anymore (since a long time actually). @yarikoptic contacted me about it some years ago I think but there was no real outcome. I just feel bad receiving that money on my Paypal account and just doing nothing to the project anymore, not even responding to e-mails or even thanking the donators :disappointed:

Not sure an issue on Github is the right place to discuss. Feel free to propose another mean if needed.

Cheers,
Cyril

**Comment by yarikoptic** [comment]
Hi Cyril,

Thank you for bringing back discussion on this issue.  Indeed it might be nice to start accumulating some funds we could potentially use for project and its developers/contributors needs, e.g. servers, services and possibly finally organizing some meetups and hackathons to finally meet face to face.

I had an idea to place Fail2Ban under the wing of the [Software Freedom Conservancy](http://sfconservancy.org), which provides [services](https://sfconservancy.org/projects/services/) which could come useful...  Last interaction was me asking permission to share their application questions publicly but I never got a reply. Oh well, hopefully it would be not of so much crime so here it is now: https://github.com/fail2ban/fail2ban-publications/blob/master/sfc-application/how-to-apply-to-conservancy.txt  . @sebres -- should we start filling it up, or you have better ideas on how to establish a centralized official umbrella for the project?

**Comment by yarikoptic** [comment]
BTW @lostcontrol  -- for sensitive discussions we have fail2ban-vulnerabilities@lists.sourceforge.net ;-)

**Comment by lostcontrol** [comment]
@yarikoptic I found again that last e-mail (June 2015) you sent them. I almost thought I forgot again to answer my e-mails :stuck_out_tongue: We can communicate via the top-secret mailing-list if you think it is more appropriate :wink:

**Comment by sebres** [comment]
Hi Cyril,

Thanks for the making a query... Indeed the further development (and support) of fail2ban costed many time. And donations can theoretically sweeten the pill (about which amount are we talking?).

Whats about communication via top-secret mailing list - it does not matter IMHO. But if Yaroslav like it so better...

> should we start filling it up, or you have better ideas on how to establish a centralized official umbrella for the project?

@yarikoptic No ideas (and not really time for it, same here than you :)
Except that possibly "we could make a simple paypal-account (and share its login-data between 2-3 people) and provide a paypal donate button in markdown format on the our README-page".

Additionally I've heard about https://www.gitcheese.com/. Please take a look whether it could be good enough for this...

**Comment by mitchellkrogza** [comment]
Hi Cyril,

Nice to see you are still around. I fully support that @yarikoptic and
@sebres and a few others are able to benefit from those donations they have
done amazing work taking Fail2Ban forward to version 0.10 and beyond I see
even greater things in the pipeline. @yarikoptic and @sebres especially
work tirelessly on the project and are always willing to help users out,
even with what may seem like silly questions, they help.

Thank you for the original Fail2Ban, the most vital tool for me and many
thousands of people.

It would be nice if the original wiki could be turned into a Github repo so
that we can contribute to updating it, helping with translations and more.

Kind Regards
Mitchell Krog



From: Serg G. Brester <notifications@github.com> <notifications@github.com>
Reply: fail2ban/fail2ban
<reply@reply.github.com>
<reply@reply.github.com>
Date: 30 January 2017 at 6:26:49 PM
To: fail2ban/fail2ban <fail2ban@noreply.github.com>
<fail2ban@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  Re: [fail2ban/fail2ban] Redirect donations (#1679)

Hi Cyril,

Thanks for the making a query... Indeed the further development (and
support) of fail2ban costed many time. And donations can theoretically
sweeten the pill (about which amount are we talking?).

Whats about communication via top-secret mailing list - it does not matter
IMHO. But if Yaroslav like it so better...

should we start filling it up, or you have better ideas on how to establish
a centralized official umbrella for the project?

@yarikoptic <https://github.com/yarikoptic> No ideas (and not really time
for it, same here than you :)
Except that possibly "we could make a simple paypal-account (and share its
login-data between 2-3 people) and provide a paypal donate button in
markdown format on the our README-page".

Additionally I've heard about https://www.gitcheese.com/. Please take a
look whether it could be good enough for this...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fail2ban/fail2ban/issues/1679#issuecomment-276110067>,
or mute the thread

**Comment by yarikoptic** [comment]
I am ok to go with gitcheese.com for now (trying to set it up now and will send a PR with a badge in README), but we should really look into applying to SFC.  I will try to carve some time soon to fill out that document

**Comment by lostcontrol** [comment]
Thanks for the feedback. Sorry for the late answer, I miss the two last comments.

The main question I think is who should receive the donations, how should they be shared, etc. Up to now it was easy, I received them on my Paypal account and used them for financing my hobbies (well, I pay for the domain name and host the wiki but that is nothing). Likely having a foundation or some quite of third-party service would ensure that nobody steals the money 😉 I don't really care about the option, I would just like that the money goes to people who deserves it.

> about which amount are we talking?

I received an important donation some days ago and that triggered me to open this ticket. I'm willing to pay back the donations starting from 2012 or maybe a bit earlier. Unfortunately, the data are not on Paypal anymore but I still have all the e-mails. I haven't done the maths so far but it is way enough to get all the devs drunk 🍺🍺🍺🍺🍺

> provide a paypal donate button in markdown format on the our README-page

Actually I wonder where people do find the donate button currently!? Maybe from sourceforge.net!?

**Comment by yarikoptic** [comment]
Actually -- may be we should consider some other donation portal -- gitcheese seems to support only "credit card" donations (and a fee seems to be a hefty 9%, whenever iirc credit cards fees are around 3% generally), which might be a touchy topic for some -- e.g. even myself I would prefer to not give my credit card number and prefer to pay via e.g. donate via paypal or google wallet.  Also could not find much of feedback about this service :-/  we might want to do some research first

**Comment by yarikoptic** [comment]
What about 
1. leaving @lostcontrol for now in charge for collecting donations and distributing some for-beer gratitudes to current (and some past) developers?
2. making an effort to apply for SFC so at least there would be some coherent central umbrella above the project (with possible legal protection) and accepting donations?

**Comment by sebres** [comment]
1. I'm prejudiced ('cause dev =), but agree .
2. positive, but who makes an effort :)

Interim we can simply add paypal to github (via https://github.com/blog/57-getting-paid-the-open-source-way). Just provide yours or my paypal-mail (I can do it, if you say I should add my one).
I think we (as admins) will see all the donations. Then we can distribute it between devs, contributers and authors (I don't think that @lostcontrol should be excluded just because he makes a long pause).

**Comment by yarikoptic** [comment]
2. I will (just might take some time as you know ;) )

note that that page states "Update: We’ve discontinued this feature" ;)  as for which paypal to use -- might as well stay with @lostcontrol , or we could transfer this "chief financial officer" duty to you -- I don't mind either way.

My concern with directly dealing with paypal though is a known history of pain due to it blocking paypal accounts and iirc even linked bank accounts if any issue arises. IIRC that is why Debian [1] never used paypal to accept donations. And we are all spread across countries -- so legalities becomes really tricky AFAIK, and that is why I thought to make it all legit by going through SFC.

[1] now I see that you can donate via PayPal to Debian (https://www.debian.org/donations#spi-paypal) but it goes through SPI -- the non-profit umbrella organization alike SFC.

**Comment by yakatz** [comment]
I just ran into this while checking on the wiki infrastructure. I think mediawiki is much better than the github wiki and we should probably keep using it. I can update it to a new version and provide a server it can run on if Cyril doesn't want to.

**Comment by sebres** [comment]
>  I think mediawiki is much better than the github wiki

"I think..." is controversial. 
Arguments?

**Comment by yakatz** [comment]
GitHub's Wiki isn't designed for creating a whole website and doesn't give you subpages or categories.

Mediawiki is much more flexible and average people are more familiar with it. It also supports extensions to allow changing its behavior.

The other alternative I can think of would be GitHub Pages or a real documentation builder/service.

**Comment by sebres** [comment]
> GitHub's Wiki isn't designed for creating a whole website 

For this purposes there are [github-pages](https://pages.github.com/) (as you already self said).
> doesn't give you subpages or categories.

subpages = futter

categories -> see our current wiki, what you see on the right of [the page](https://github.com/fail2ban/fail2ban/wiki)?

> average people are more familiar with it

What can be complex on the markdown-syntax?

--

Now my pros (why I would prefer this all on github):
- the same login (and permissions-system);
- several contents can be easy linked (some github-subjects like issues, releases, files, etc.);
- all this (github-pages as well as wiki) are git-repos (so versionable, each change comprehensible, can be easy reviewed, reverted, merged, etc).
- everyone who has a github account can contribute to the wiki also (even direct edit it);
- there's hope, that before someone will open new issue, he take a look in wiki (that is on the same page, a click away, right beside issues)

Additionally, I don't think that we should mix a web-site with wiki (that is in my opinion something like FAQ, HowTos, etc.).

BTW. That of course does not prevent you also to create your own mediawiki as suggested.
2 wiki's are better as no one.

**Comment by yakatz** [comment]
I didn't understand your last line - I would think 2 wikis is worse because people wouldn't know where to look.
I will admit that I never did like the main website being the wiki. The Vyos project used to do that and they finally got a real website and they keep the wiki separate. (Tangentially, we have fail2ban put blocks in Vyos. I have been meaning to write it up for the wiki.)

**Comment by lostcontrol** [comment]
> I just ran into this while checking on the wiki infrastructure. I think mediawiki is much better than the github wiki and we should probably keep using it. I can update it to a new version and provide a server it can run on if Cyril doesn't want to.

I was just too lazy to keep the installation up to date 😞 I can't upgrade to the latest Mediawiki because it requires PHP 5.5. My server is still running Ubuntu 12.04 LTS (with PHP 5.3) which is going to be end-of-life soon so I will have to upgrade anyway. I could upgrade to Mediawiki 1.26 which supports PHP 5.3 still. I can give it a try this week.

Also if someone wants to create a modern main website, I'll happily change the DNS to point to it. We can move the wiki to wiki.fail2ban.org or docs.fail2ban.org or anything else. The only example that comes to my mind right now is [openhab.org](www.openhab.org). They have many things on github, including wiki, a separate documentation website, a separate forum, etc. The main page mainly provides links to these others locations.

**Comment by lostcontrol** [comment]
Quick note (actually off-topic but since this was mentioned here): Mediawiki upgraded to 1.26.4 and HTTPS now available.

**Comment by keithchristian** [comment]
GitHub is not bad for documentation, but MediaWiki has more text formatting capabilities, MediaWiki is easier to understand, more laypeople use Wikipedia (and thus MediaWiki) than GitHub for reading documentation.  MediaWiki has a user-friendly diff option, and so forth.  To each his own.

**Comment by buanzo** [comment]
Hello Team, Cyril:

I like MarkDown for documentation, it is just enough for the kind of
requirements we have, and to provide good, readable doc for users. A wiki
is, IMHO, just too much nowadays.

I would propose the main website to be an html-only export of a nice
wordpress site, and keep backend access tightly controlled and protected.

If there is anything I can do, other than code which I no longer have much
time to, because my main job is development, my experience in linux and
security systems is readily available for Team.

And... happy new year!!! :D

**Comment by lostcontrol** [comment]
Hi all,

First of all, happy new Year to everyone.

I realized that I opened this ticket almost 1 year ago and I still haven't dispatched any donations. I'm really sorry about that. As I explained before, I would like to redistribute the donations I received (and used to finance my new hobby, FPV with drones) to the devs that deserve them. In order to start 2018 with a good resolution, I just went through my e-mails and did the list of the donations I received starting from 2012.

@yarikoptic and @sebres (or others) could you please tell me how to dispatch the donations?

Off-topic: If you want to see what FPV is, visit (like, comment and subscribe) my YouTube channel: https://www.youtube.com/channel/UCyzECm9LkrCz9eTWZ385rQg :smile:

**Comment by yarikoptic** [comment]
@lostcontrol paypal (to paypal@onerussian.com) or google wallet (to yarikoptic@gmail.com) would all be ok, or I could share my amazon wishlist ;)  Thanks in advance **BUT** keep in mind, that my primary role in 2017 was just to keep slowing down @sebres ;-) 

Re FPV -- crazy sh.t -- is that real time??? what kind of drone flies that fast and resilient to being smashed that you aren't afraid to speed it that much?

**Comment by lostcontrol** [comment]
@yarikoptic could you (and @sebres) come with a proposition to share the donations? Remember that this is from 2012 to now so maybe some devs active back then also deserve a bit of it. And don't forget me :wink: Like e.g. dev A 20%, dev B 40%, dev C 40%

Paypal is probably the easiest way to do it, even though they charge fees for transfer to friends.

FPV is the craziest and most addictive hobby I got to do so far!!! Completely addicted to it since ~2 years. Yes, it is real time but most video on YouTube are from a GoPro whereas I get an analog video feed in the goggles from another camera while flying. And yes, those racer (as they are called) are made of carbon and built to endure crashes.

**Comment by yarikoptic** [comment]
Although suboptimal, you could use git shortlog -sn from dinner point in 2012, and make cut off at eg 5 or 10% of commits

Which model of drone and analog feed camera do you use?

**Comment by lostcontrol** [comment]
Looking at https://github.com/fail2ban/fail2ban/graphs/contributors, I see 4 main contributors since 2012. I can do 25% to each of you or maybe a bit more to @sebres since I think he is clearly the main contributors now. I won't count me in but I will reduce the total amount I transfer to cover the different Paypal fees (e.g. a 19$ donation results in 17,96$ on my Paypal account, also transferring money will cost me some fees).

Have a look [here](https://bestdroneforthejob.com/drones-for-fun/racing-drone-buyers-guide-2/#What8217s_In_a_FPV_Racing_Quad) for example. I mainly use 250mm (motor to motor) quadcopter (so called FPV racer). The camera is e.g. a HS1177 (google for it) with a 5.8GHz video transmitter. I receive the signal on my Fatshark Dominator V3 in real-time (just a few milliseconds of delay). Analog is still the best here because it is cheap, zero delay and the signal degrades instead of cutting out like digital. But the picture quality is crap (that's why people fly with an additional GoPro on the quad for nice video).

**Comment by yakatz** [comment]
If the main website is static, how about using [Github Pages](https://pages.github.com/)? It means no infrastructure is needed and it can be maintained in Git.
I am happy to make an example site (hopefully in the next few days).

**Comment by buanzo** [comment]
That is SO awesome, FPV makes me totally crazy. I have a small bebop 1 with
the big controller + ipad support. I want to use my samsung gear vr with a
smartphone for 3d, but i would need to modify the drone or something. One
day I shall have time :P

**Comment by yarikoptic** [comment]
@lostcontrol count @sebres for two ;)  yeah -- I hate those companies milking a notable portion of the transactions, like they really have to move the trucks with money and more money means more trucks.. heh

good link about intro for racing drones, thanks!  may be some time when I get time and spare $s ;)

**Comment by sebres** [comment]
Hi all,
happy new Year!

> Paypal is probably the easiest way to do it

@lostcontrol My paypal is [paypal.me/sebres](https://paypal.me/sebres/).

>> 2. making an effort to apply for SFC ...
> 2. I will (just might take some time as you know ;) )

@yarikoptic Some news here?

**Comment by lostcontrol** [comment]
Hi @sebres,

Thanks for the reply. What about @grooverdan and @kwirk who also contributed quite a bit in 2013-2014? Do you have some suggestions for the split (who get which percentage)?

**Comment by yarikoptic** [comment]
@sebres :
> Some news here?

unfortunately not... may be the productive one of us could take a first stab at that https://github.com/fail2ban/fail2ban-publications/blob/master/sfc-application/how-to-apply-to-conservancy.txt ? ;)

re @grooverdan and @kwirk -- although I could come up with some kind of uneven split, I would just split 50/50 at this point - it was great to have multiple people collaborating productively at the same time

**Comment by sebres** [comment]
> @lostcontrol, What about @grooverdan and @kwirk ...

Of course! But I don't have any suggestion how you can split it... The commits count resp. added or removed lines are not really good reference for it - someone had commited exactly one line, but invested several hours with reading documentation, thinking, trying, etc, another changed 1000 lines with adding one `if` scope (reindent) in 5 minutes...
But please, don't forget also @koeppea in your calculation, for his great contribution part as regards IPv6-copability etc.

> @yarikoptic, may be the productive one of us could take a first stab ...

Somehow, I knew it :)

**Comment by lostcontrol** [comment]
Thanks all for the comments.

I'll try to contact @grooverdan, @kwirk and @koeppea. I'll split the pot evenly between @yarikoptic, @grooverdan, @kwirk and @koeppea and give @sebres a bit more since he is clearly the most active I think. I leave myself out but will reduce the amount to cover the Paypal transaction fees.

**Comment by sebres** [comment]
> I leave myself out

Why?!

BTW I make the development of fail2ban for completely other reasons as possible "profit" (and never awaited it), thus I'll say let us consider myself equal to other contributors...

**Comment by lostcontrol** [comment]
> Why?!

Because I contributed nothing for many years, I'm happy to "sponsor" the project by paying for the fail2ban.org and I'm even more glad to see people like you keeping it alive. I would have never thought the project would be still alive 14 years after I started it in 2004. I don't deserve any of those later donations.

So ok, I'll cut the pot into five equal parts. I'll try to do it this week-end.

@grooverdan @kwirk @koeppea please contact me.

**Comment by kwirk** [comment]
Thanks all for including me 😃 It's great to see the project continuing to develop, especially the long awaited IPv6

@lostcontrol: I couldn't see your email address on your profile, so could I ask for you drop me an email (address should be on my profile) and I'll pass you my paypal account details.

**Comment by sebres** [comment]
So done (Thanks again, Cyril), thus I'll close this.
