### ISSUE TITLE
How can I force a rescan of a log?

### ISSUE THREAD

**Issue by basildane** [fail2ban/fail2ban#1682]
I have a very large log, but it looks like it wasn't processed correctly.  Now after adjusting settings, I would like to re-parse it.

**Comment by sebres** [comment]
> I would like to re-parse it.

Why it should be necessary? After new failures all this IP will going anyway banned...

But if you want nevertheless...
You should reset last log position in sqlite-database of fail2ban:
- simple method would be to delete whole database (but affects all logs, jail, etc). Where you can find it you could look in fail2ban.log or fail2ban.conf (or dump it via `fail2ban-client  -d | grep dbfile`).
So stop fail2ban. Delete fail2ban sqlite-database (maybe backup it firstly). Start fail2ban again.
- another method would be to delete logpath via fail2ban-client and add it hereafter again.
See `fail2ban-client --help` for more information. It can be, that you should reenable this jail hereafter, if it going idle after deleting of the last logpath.

Note that fail2ban will find and ban entries only beginning from time corresponding now minus `findtime`, that you've specified for this jail (default 15 minutes). So old entries will be ignored anyway.
Of course you can increase `findtime`, but it affects the jail in the future also: if some IP makes `maxretry` failures within `findtime` it will be banned (so be sure that by some possible mistakes decent people don't be banned, by too large `findtime` / small `maxrety` pair).

BTW. You can also grep and parse all this IP from the output of fail2ban-regex and ban it manually or per some shell-script, using:
```bash
fail2ban-client  set "your-jail" banip "bad-ip"
```
Then they will be automatically unbanned after `bantime` was reached.

**Comment by basildane** [comment]
Let me clarify.  We have been undergoing a sustained attack for 2.5 years.  It's one attacker, the same spam, coming from over 100 separate subnets, from every country in the world.  I was spending an hour a day aggregating logs and building blocklists, and that's why I want to use fail2ban.

I want to ban these IP's (around 2 million so far) permanently.
And there are other victims on the firewall groups waiting to hear my success story and then they are going to join in.

**Comment by sebres** [comment]
> I want to ban these IP's (around 2 million so far) permanently.

Well, I don't think, that permanent holding 2mio IPs in the iptables (or even ipsec) would be a good idea at all. Possibly you'll try my incremental fail2ban solution (see https://github.com/sebres/fail2ban/tree/ban-time-incr, PR #1460).
So the bad-ips will be relatively fast banned for the long time. But it means exactly long (not persistent) - i. e. not or no more active IPs would be removed from the banned list (hereby will relieve iptables/ipsec, database, memory etc.)
Additionally it is more interesting with regard to the botnet recognition. Because smart botnets will experimental find your current fail2ban settings and adjust attempts time resp. the failure retry will adapted to it. So later it will be almost impossible to recognize it (goes never banned). 
The mentioned incremental solution "decreases" `maxretry`  for known bad-IPs. So it will be banned faster by repeated attempts.

Below you'll find an example how it looks (note the reversed order):
```
2014-09-18 04:37:29,155 fail2ban.observer [named-refused] Found XXX.XXX.XX.XXX, bad - 2014-09-18 04:37:28, 3 # -> 5, Ban
2014-09-18 04:37:29,148 fail2ban.filter   [named-refused] Found XXX.XXX.XX.XXX - 2014-09-18 04:37:28
......
2014-09-18 02:55:04,790 fail2ban.observer [named-refused] Found XXX.XXX.XX.XXX, bad - 2014-09-18 02:55:04, 2 # -> 3, Ban
2014-09-18 02:55:04,763 fail2ban.filter   [named-refused] Found XXX.XXX.XX.XXX - 2014-09-18 02:55:04
2014-09-18 02:22:37,683 fail2ban.observer [named-refused] Found XXX.XXX.XX.XXX, bad - 2014-09-18 02:22:37, 2 # -> 3
2014-09-18 02:22:37,648 fail2ban.filter   [named-refused] Found XXX.XXX.XX.XXX - 2014-09-18 02:22:37
......
2014-09-18 00:40:08,908 fail2ban.observer [named-refused] Found XXX.XXX.XX.XXX, bad - 2014-09-18 00:40:08, 1 # -> 2, Ban
2014-09-18 00:40:08,625 fail2ban.filter   [named-refused] Found XXX.XXX.XX.XXX - 2014-09-18 00:40:08
2014-09-17 23:48:54,404 fail2ban.observer [named-refused] Found XXX.XXX.XX.XXX, bad - 2014-09-17 23:48:53, 1 # -> 2
2014-09-17 23:48:54,397 fail2ban.filter   [named-refused] Found XXX.XXX.XX.XXX - 2014-09-17 23:48:53
2014-09-17 22:49:04,647 fail2ban.observer [named-refused] Found XXX.XXX.XX.XXX, bad - 2014-09-17 22:49:03, 1 # -> 2
2014-09-17 22:49:04,620 fail2ban.filter   [named-refused] Found XXX.XXX.XX.XXX - 2014-09-17 22:49:03
......
2014-09-17 22:32:05,593 fail2ban.filter   [named-refused] Found XXX.XXX.XX.XXX - 2014-09-17 22:32:05
2014-09-17 22:06:29,952 fail2ban.filter   [named-refused] Found XXX.XXX.XX.XXX - 2014-09-17 22:06:29
2014-09-17 21:47:43,439 fail2ban.filter   [named-refused] Found XXX.XXX.XX.XXX - 2014-09-17 21:47:42
2014-09-17 20:43:41,490 fail2ban.filter   [named-refused] Found XXX.XXX.XX.XXX - 2014-09-17 20:43:40
2014-09-17 16:44:35,130 fail2ban.filter   [named-refused] Found XXX.XXX.XX.XXX - 2014-09-17 16:44:34
```
You see, while IP was not yet recognized as a bad, it was banned after 5 failures (configure `maxretry`).
Second time (already as bad) — after 3th failure (each attempt was counted for 2).
The third — after 2 (each attempt was counted as 3) 
And fourth time it was banned immediately after the first attempt (which was counted for the 5 failures).

**Comment by LunarWatcher** [comment]
As pointed out [here](https://superuser.com/a/1337247), one hack is to feed the log back into itself. `cd /var/log && sudo mv auth.log authold.log && cat authold.log | sudo tee auth.log` makes fail2ban think there's a whole bunch of new entries, when it's really just re-parsing the old ones. Worked for me anyway, and added nearly 600 IPs from the past 6 days that weren't caught because jail.conf doesn't seem to work with `mode = aggressive` anymore

Add `> /dev/null` in appropriate places if necessary; the IO will slow down the operation if there's a huge amount of logs being dumped into the terminal. I don't do much piping and redirection though, and don't have enough logs for it to be a problem worth fixing :p As long as it's re-added to the file, though, it should be re-parsed. Note that this may result in premature bans for some IPs while reparsing, at least for IPs that have partial failures. Not a problem for me (I ban after one failed attempt), but this depends on individual use.

Admittedly, this is with a sample size of 1; no guarantees this is fully general.

**Comment by sebres** [comment]
> As pointed out [here](https://superuser.com/a/1337247), one hack is to feed the log back into itself.

This can work only conditionally - the timestamp of old log-entries may be too old, so expired in sense of `findtime` window fail2ban holds the failures back.

There is a (still open) RFE for rescan ability - #2909
And also two ways what you can use as a workaround now - https://github.com/fail2ban/fail2ban/issues/2909#issuecomment-758073892 and https://github.com/fail2ban/fail2ban/issues/2909#issuecomment-1039267423
