### ISSUE TITLE
install without config?

### ISSUE THREAD

**Issue by ben29** [fail2ban/fail2ban#1683]
Hi.
i rewrite all the config for this project.
so every update. i need to copy again the config files.

can you add python serup.py install --without-config

or something that will not install the config?

**Comment by sebres** [comment]
> i rewrite all the config for this project.

Bad idea, because you should never change the stock configs directly. Use .local instead of .conf.
See https://github.com/fail2ban/fail2ban/wiki/Properly-fail2ban-configuration

> can you add python serup.py install --without-config

Well, we can, but it could be incompatible from one version to another, because config files would be very often extended.

**Comment by ben29** [comment]
yea.
but it's not match to directadmin setting, and i don't need all.

**Comment by sebres** [comment]
> but it's not match to directadmin setting

I don't know what you mean here. If it is an own filter:
- it will be anyway not overwritten.
- also this filter could get extension .local (to be sure).

> and i don't need all.

Only enabled jails would be started. So you can create jail.local like
```
[sshd]
logpath = my-log-path
backend = my-backend
enabled = true
```
Then jail sshd only will be started.

BTW. You can rewrite your start-scripts of fail2ban service (or init.d) to use parameter `-c /etc/fail2ban-my-own-config`.
