### ISSUE TITLE
bdist_rpm fails 

### ISSUE THREAD

**Issue by maxxer** [fail2ban/fail2ban#1701]
On the current 0.10 branch (but also on 0.10.0a1) `./setup.py bdist_rpm` fails with the following errors (error are translated by me so they could be imprecise in english locale):

```
RPM build errors:
    Double declaration: /usr/lib/python2.7/site-packages/fail2ban-0.10.0a1-py2.7.egg-info/PKG-INFO
    Double declaration: /usr/lib/python2.7/site-packages/fail2ban-0.10.0a1-py2.7.egg-info/SOURCES.txt
    Double declaration: /usr/lib/python2.7/site-packages/fail2ban-0.10.0a1-py2.7.egg-info/dependency_links.txt
    Double declaration: /usr/lib/python2.7/site-packages/fail2ban-0.10.0a1-py2.7.egg-info/top_level.txt
    Found installed files (but in included into package):
   /etc/fail2ban/action.d/badips.pyc
   /etc/fail2ban/action.d/badips.pyo
   /etc/fail2ban/action.d/smtp.pyc
   /etc/fail2ban/action.d/smtp.pyo
```

**Comment by sebres** [comment]
I assume that you want to create RPM package?

This occurred, because setup may run the test-cases, possible something there (I assume some action using fail2ban modules) creates a .pyc file in "current" directory (for the action).

You've several possibilities:
- first test (via fail2ban-testcases), and then make RPM from the clean copy (without starting of the test-cases).
- add clean-ups in setup script after test-cases call;
- use something like PYTHONDONTWRITEBYTECODE to prevent creating of pyc-files during setup proceses;
