### ISSUE TITLE
migration from fail2ban 8 to fail2ban 10 on  debian jessie

### ISSUE THREAD

**Issue by i300220** [fail2ban/fail2ban#1712]
Jessie version encompass fail2ban 8 which is getting pretty old

It does not support either IPV6, although a patch and disponible - and ipset is totally broken, i.e. it ignores the ban time.

We do need both.

Is there is a simple way to migrate to v 10.  All my attempts have failed.  Including adapting filter.py and  failregex.py according to the readily available patch from an external user intended for v 8 (2012) to make it ipv6 friendly.

We use debian 8 Jessie and right now fail2ban is completely broken after the update - and tentative of conversion - to v 10

**Comment by sebres** [comment]
> Is there is a simple way to migrate to v 10. All my attempts have failed.

Details?
Normally uninstalling of stock version and manually installing from github word perfect.
Because the configs are incompatible you should have "clean" /etc/fail2ban. I mean without modified old .conf files. You can leave your simple .local files (with modified entries only, if not the whole copies of the old .conf files).
You can also test your configs on a test instance. See our wiki for details:
https://github.com/fail2ban/fail2ban/wiki/How-to-test-newer-fail2ban-version-resp.-use-fail2ban-standalone-instance

I'll close it as long more info not provided, what exactly fails etc.
