### ISSUE TITLE
How to upgrade from 0.8.13 to 0.10.x?

### ISSUE THREAD

**Issue by PepeLopez** [fail2ban/fail2ban#1753]
Hi,

is it possible to update fail2ban in a way, that the already deployed rules are overtaken and working as usual? I just need that <ip> will also recognize ipv6 addresses.

**Comment by sebres** [comment]
The configuration of v,0.10 is 99% compatible to v.0.8, however some setting are different. Overview will give you the changelog (but it is too big since v.0.8).
To test your configuration with 0.10 see [our wiki](https://github.com/fail2ban/fail2ban/wiki/How-to-test-newer-fail2ban-version-resp.-use-fail2ban-standalone-instance)

The upgrade will be relative easy if all of your custom configuration located in `.local` files (and they contain customization only, thus not the whole copy of the original `.conf` files). Otherwise you should find all your changes and set it in the `.local` files after upgrade.

As regards ipv6 addresses, all the filter rules should match IPv6 with tag `<HOST>`.
But ATM we've still not all ban-actions ported as IPv6 capable.
