### ISSUE TITLE
Fail2ban Haproxy config

### ISSUE THREAD

**Issue by frodood** [fail2ban/fail2ban#1775]
i'm trying to config fail2ban for haproxy, i cant get correct regex 

here's my expression 
```
failregex = haproxy\[\d+\]: <HOST> .* "(GET|POST) .*http?://
```
this doesn't work

log :- 
```
May 11 08:37:46 httplb2 haproxy[5353]: 10.212.134.200:58788 [11/May/2017:08:37:46.273] localnodes nodes/<NOSRV> 0/-1/-1/-1/0 503 213 - - SC-- 1/1/0/0/0 0/0 "GET / HTTP/1.1"
```

**Comment by sebres** [comment]
It would be very vulnerable if you would have used your regex, because e. g. not anchored :)

You can use our default filter `haproxy-http-auth` (that uses common-include and has `%(__prefix_line)s` substitution)...
For example extend it within your `haproxy-http-auth.local`:
```
[Definition]
failregex = %(known/failregex)s
            ^%(__prefix_line)s<HOST>(?::\d+)?\s+.*<NOSRV> 0/-1/-1/-1/0 503
```
which results in this:
```
failregex = ^%(__prefix_line)s<HOST>(?::\d+)?\s+.*<NOSRV> -1/-1/-1/-1/\+*\d* 401
            ^%(__prefix_line)s<HOST>(?::\d+)?\s+.*<NOSRV> 0/-1/-1/-1/0 503
```
