### ISSUE TITLE
Can you explain this FAIL regex, please?

### ISSUE THREAD

**Issue by 7starsone** [fail2ban/fail2ban#1776]
Hello,
obviously on all the online regex this works:

`^<HOST> .*GET .*PhantomJS.*`
for eg.

`hostxxx-xx-xx-xx.domain.name.com - - [11/May/2017:15:01:23 +0200] "GET /blog/wp-includes/js/comment-reply.min.js?ver=4.7.4 HTTP/1.1" 200 589 "http://mydomain.com/blog/2017/05/11/post-title/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"`

for Fail2ban, instead, this is **missed** (!?)

this
`^<HOST> .*GET .*linkfluence\.com.*`
**works** for

`ec2-xx-xx-xx-xx.xx-name-1.domain.name.com - - [11/May/2017:14:07:22 +0200] "GET /blog/2017/05/11/post-title/ HTTP/1.1" 200 20843 "-" "Mozilla/5.0 (compatible; YaK/1.0; http://linkfluence.com/; bot@linkfluence.com)"`

so, I thought was about the **?** ... tried everything, to match...to escape the ?

nothing...

can you explain why, please?
thanks

**Comment by 7starsone** [comment]
and also, can't be too specific... it needs to match even when **?** is not there...but I have doubt, because **.*** is **everything**...I really don't understand here, sorry

**Comment by sebres** [comment]
> obviously on all the online regex this works ... for Fail2ban, instead, this is missed

I don't know, what you mean with the statement, because it pretty works:
```
$ fail2ban-regex <...line...> <...re...>

Running tests
=============
Use   failregex line : ^<HOST> .*GET .*PhantomJS.*
Use      single line : hostxxx-xx-xx-xx.domain.name.com - - [11/May/2017:...
...
Results
=======
Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^<HOST> .*GET .*PhantomJS.*
`-
...
Date template hits:
|- [# of hits] date format
|  [1] Day(?P<_sep>[-/])MON(?P=_sep)ExYear[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```
But as already said, I don't understand your concern at all (what you exactly need)

Although the regex is indeed not so good:
- ahead-anchored only, but to many catch-alls in-between (it is very unprecise therefore vulnerable)
- the only thing that makes it good is the HOST at begin, implicit after anchor.
- the last `.*` does not needed (because causes nothing)

>  I thought was about the `?` ...  tried everything, to match...to escape

Which `?` did you meant, I don't see any `?` in your expressions (that you could escape).

Well, you can read how the regex's work in the [python documentation](https://docs.python.org/2/library/re.html). 
The deviations in fail2ban are only:
- several substitutions (variables interpolations) will be made before compiling of regex, I mean things like `<tag>` (e.g. `<HOST>`) and `%(var)s`.
- be careful with `%` character (because of the python-config, it should be dual-escaped `%%`)
- fail2ban will try to match not the original string - the datetime (matched datepattern) will be cut out from it before.

Here is actually not the right place to seek help for such issues, but ...
Better you will just provide several log-entries, that should be matched (with explanation, e. g. words or phrases that imply a failure for you, resp. why you interpret it as failure). And possibly pair another that should be not matched (not failures).
Then we can theoretically help, otherwise I don't know how, because I really not understand what you want.

**Comment by 7starsone** [comment]
also tried:

`-.*GET .*\?.*\=.* HTTP\/.* PhantomJ.*`

nothing, on the online tester works, on `fail2ban-regex` doesn't...
please help

**Comment by 7starsone** [comment]
no, it doesn't work here

CentOS 7 `fail2ban-0.9.6-3.el7.noarch` that fail2ban-regex doesn't work
what's the problem, please?

**Comment by sebres** [comment]
> no, it doesn't work here
tested on v.9.6, v.9x and v.10.x:
```bash
$ fail2ban-regex 'hostxxx-xx-xx-xx.domain.name.com - - [11/May/2017:15:01:23 +0200] "GET /blog/wp-includes/js/comment-reply.min.js?ver=4.7.4 HTTP/1.1" 200 589 "http://mydomain.com/blog/2017/05/11/post-title/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"' '^<HOST> .*GET .*PhantomJS.*'
```
with the same result:
```
....
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```

**Comment by 7starsone** [comment]
found, this works and if I replace the real string, with numbers and letters doesn't work...

there's some bug...may be the whole string lenght or the host lenght or something like this?
there are no special chars, really

now try this
`fail2ban-regex 'host141-23-37-46.serverdedicati.aruba.it - - [11/May/2017:15:01:23 +0200] "GET /blog/wp-includes/js/comment-reply.min.js?ver=4.7.4 HTTP/1.1" 200 589 "http://mydomain.com/blog/2017/05/11/post-title/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"' '^<HOST> .*GET .*PhantomJS.*'`

**1 missed** just inserted the real HOST...

**Comment by 7starsone** [comment]
really REALLY weird lol

`fail2ban-regex 'host141-23-37-46.xxx.com - - [11/May/2017:15:01:23 +0200] "GET /blog/wp-includes/js/comment-reply.min.js?ver=4.7.4 HTTP/1.1" 200 589 "http://mydomain.com/blog/2017/05/11/post-title/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"' '^<HOST> .*GET .*PhantomJS.*'`
**MATCHED**

`fail2ban-regex 'host141-23-37-46.abc.com - - [11/May/2017:15:01:23 +0200] "GET /blog/wp-includes/js/comment-reply.min.js?ver=4.7.4 HTTP/1.1" 200 589 "http://mydomain.com/blog/2017/05/11/post-title/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"' '^<HOST> .*GET .*PhantomJS.*'`
**MISSED**
(just **abc** in place of **xxx**)
there's something really weird here...

**Comment by sebres** [comment]
> there's something really weird here...

No. It works as expected:
You've no IP in the log-file, only the hostname, but...
Just **the host is not resolvable** (fail2ban needs an IP, don't forget).

If you start it with higher log level, you'll see:
```
Unable to find a corresponding IP address for host141-23-37-46.serverdedicati.aruba.it: [Errno -2] Name or service not known
```

So to test it without IP resolving, add `--raw` argument (but just for the testing, it will still not be banned in fail2ban).
```bash
$ fail2ban-regex -v --raw '<...line...>' '<...re...>'
```
If you've not parameter `--raw` in your fail2ban version, you can try `--usedns=raw`, but I'm not sure it'll work).

**Comment by 7starsone** [comment]
and this **hostxxx-xx-xx-xx.domain.name.com** which matches would be **resolvable**? where's the IP here?

**Comment by 7starsone** [comment]
the difference is that the 1st one is **No match for...** on **whois** and the 2nd is **UNASSIGNABLE**...

**Comment by sebres** [comment]
Oh brother! should I do everything instead of you?
```bash
$ dig +short 'hostxxx-xx-xx-xx.domain.name.com'
69.64.159.30
```

**Comment by 7starsone** [comment]
but, how is possible that there's no IP for that specific host if the host line is the exact one on my log? what does mean in this case, please? thank you

**Comment by sebres** [comment]
This meant that you DNS-resolving is a little bit "crazy" (just kidding).
Seriously, it was resolved (reverse way) from your system (to this time-point). 
But it has no forward entry, or just it is not resolvable now anymore (dns entries have expiration date, please note it may be cached somewhere).

Better would be to log directly the IP, instead of the reversed host-entry.

**Comment by 7starsone** [comment]
thank you.
Pardon, in my opinion misunderstanding is about the not well documented "fail2ban-regex", at least in this case...nowhere is explained that it does a check on the HOST. So, I thought the test was just about a regex and not to even check the IP. Then, I also think that **ignoreregex** is not explained as well.
In one case, If I do `ignoreregex = ^<HOST> .*GET .*something.*` it doesn't work, I need to do ` .*GET .*something.*` to let it work as it should, but this nowhere explained.

**Comment by sebres** [comment]
> not well documented fail2ban-regex, at least in this case...nowhere is explained that it does a check on the HOST. 

As regards the parsing `fail2ban-regex` behaves exactly as `fail2ban-server`, so this is IMHO transparent enough. But we can indeed extend our docu a little bit more.

> I also think that ignoreregex is not explained as well.

Excerpt from `man jail.conf.5`:
```
       failregex
              is the regex (regular expression) that will match failed attempts. 
              The tag <HOST> is used as part of the regex and is itself a regex for IPv4 addresses (and hostnames if usedns). 
....

       ignoreregex
              is the regex to identify log entries that should be ignored by Fail2Ban, even if they match failregex.
```
I don't see there any reference where `ignoreregex` should behave similar to `failregex` as regards as tag `<HOST>`. I think also it is understandable enough as it is.

BTW `ignoreregex = .*GET .*something.*` is very-very vulnerable as `ignoreregex`, because it is enough to add `something` at end of the request (of course if the botnets can guess this), to completely ignoring the possible bruteforce from fail2ban hereafter.
