### ISSUE TITLE
private key brute-force not blocked

### ISSUE THREAD

**Issue by sergey-safarov** [fail2ban/fail2ban#1809]
Could you please add fail regex to catch systemd messages like
```
[root@node1.docker filter.d]# journalctl -flu sshd
-- Logs begin at Пт 2017-06-16 06:25:06 EDT. --
июн 19 05:17:09 node1.docker.rcsnet.ru sshd[8865]: Received disconnect from 223.68.192.243: 11: Bye Bye [preauth]
июн 19 05:17:14 node1.docker.rcsnet.ru sshd[8874]: Received disconnect from 223.68.192.243: 11: Bye Bye [preauth]
июн 19 05:17:19 node1.docker.rcsnet.ru sshd[8876]: Received disconnect from 223.68.192.243: 11: Bye Bye [preauth]
июн 19 05:17:24 node1.docker.rcsnet.ru sshd[8880]: Received disconnect from 223.68.192.243: 11: Bye Bye [preauth]
июн 19 05:17:29 node1.docker.rcsnet.ru sshd[8883]: Received disconnect from 223.68.192.243: 11: Bye Bye [preauth]
июн 19 05:17:34 node1.docker.rcsnet.ru sshd[8888]: Received disconnect from 223.68.192.243: 11: Bye Bye [preauth]
июн 19 05:17:39 node1.docker.rcsnet.ru sshd[8890]: Received disconnect from 223.68.192.243: 11: Bye Bye [preauth]
июн 19 05:17:44 node1.docker.rcsnet.ru sshd[8899]: Received disconnect from 223.68.192.243: 11: Bye Bye [preauth]
июн 19 05:17:49 node1.docker.rcsnet.ru sshd[8902]: Received disconnect from 223.68.192.243: 11: Bye Bye [preauth]
июн 19 05:17:55 node1.docker.rcsnet.ru sshd[8906]: Received disconnect from 223.68.192.243: 11: Bye Bye [preauth]
```
This attacker tried to brute force private key.
Example of network traffic in attached file.
[ssh.zip](https://github.com/fail2ban/fail2ban/files/1084449/ssh.zip)

**Comment by sergey-safarov** [comment]
I added folowing string to "/etc/fail2ban/filter.d/sshd.conf" but think this not optimal.
^.*Received disconnect from <HOST>: 11: Bye Bye \[preauth\]$

**Comment by sebres** [comment]
> This attacker tried to brute force private key.

How you come to this conclusion? If this take place in log without any other message, then it has don't tried to authenticate at all after connect (and still closes connection on preauth-phase).
You will see `Failed publickey for user from <IP> port 37955 ssh2: ...` if it would be really so.
In this case it's not an authentication failure, so I'll not add it to the default fail2ban sshd-filter.

If you nevertheless need it, you can add it in your `filter.d/sshd.local` like:
```
[Definition]
failregex = %(known/failregex)s
            ^%(__prefix_line_sl)sReceived disconnect from <HOST>: 11: Bye Bye \[preauth\]$
```
Note that will not work in fail2ban 0.10, because of other syntax of the sshd-filter, and because this one regex is explicit marked there as not failure (`<F-NOFAIL>`), and used just as helper to identify host for failure-messages without IP.
In this case you should use another order (your regexp first):
```
[Definition]
failregex = ^Received disconnect from <HOST>: 11:
            %(known/failregex)s
```
For v.0.10 you can add it directly in your `jail.local` like this:
```
[sshd]
failregex = ^Received disconnect from <HOST>: 11:
            %(known/failregex)s
```

**Comment by sergey-safarov** [comment]
@sebres you are right
Nice description of this message located [here](https://security.stackexchange.com/questions/44238/whats-the-purpose-strange-login-attemps-sshd-received-disconnect-from)
`attacker is using some custom code to brute-force the server which is ending up in malformed authentication requests being sent, resulting in the server killing the connection`
