### ISSUE TITLE
Apache Log with multiple VHosts

### ISSUE THREAD

**Issue by rokka** [fail2ban/fail2ban#1817]
Hi,

I have an apache log which contains access log lines of multiple VHosts domains.

I want to block the IP of an attacker who accesses a specific website more then 10 times per minute. 

In general this is not a big problem with fail2ban. 

But how can I achive that the fail counter works per VHost domain?

For example this should force the block:
10x http://foo.de/index.html

But this should not block:
5x http://foo.de/index.html
5x http://bar.de/index.html

Is this possible?

Greatings
Andre

**Comment by sebres** [comment]
> But how can I achieve that the fail counter works per VHost domain?

This is a wrong question, the "fail counter" works per IP-address (or failure-ID in v.0.10).
Rather the correct question would be: how you can achieve that apache write a failure after 10 attempts to one domain...
No idea about this for apache, but e. g. with nginx you could use <a href = "http://nginx.org/en/docs/http/ngx_http_limit_req_module.html">ngx_http_limit_req_module</a>.

It's currently not possible using pure fail2ban only. The only way would be 1 jail per 1 domain, as something like here:
```INI
[jail-vhost1]
filter = my-appache-access[vdomain=vhost1]

[jail-vhost2]
filter = my-appache-access[vdomain=vhost2]
```
You can use interpolation `%(vdomain)s` for replacement in your `failregex`.

**Comment by rokka** [comment]
Hi. 

Thanks for the quick answer. 

One last question. Instead of making one jail per domain, could I also write and process one logfile per domain?

In case of 400 domains which solution do you prefer? 400 jails or 400 logfiles?


Greatings
Andre

**Comment by sebres** [comment]
>  Instead of making one jail per domain, could I also write and process one logfile per domain?

No, unfortunately not possible now (as regards the "fail counter", for fail2ban in the same jail it has no importance which log-file contains the failure - all failures of IP are equivalent and be counted).

> In case of 400 domains which solution do you prefer? 400 jails or 400 logfiles?

As already said, in case of 400 domains, I would try to find some opportunity to write (to one log-file) exactly 1 failure only after 10 attempts to one domain...
I don't use apache, so I don't know how it can be made with him. With nginx it would be very easy using special locations with ngx_http_limit_req_module (and our filter [nginx-limit-req](https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/nginx-limit-req.conf)).

Another way is to build a pre-processor that do it for you (between apache and fail2ban).

Possibly we'll make an enhancement for a similar issue #1784:
- in fail2ban v.0,10 you can currently use a failure-id instead of IP;
- (todo) but fail2ban cannot ban IP in this case, because it will then execute `actionban` using this FID instead of IP;
- (todo) we've currently no opportunities to group the failures by some fields resp. to generate different failures depending on some fields.
