### ISSUE TITLE
feature request : send mail only once per banned ip adress.

### ISSUE THREAD

**Issue by mrpg99** [fail2ban/fail2ban#1852]
Would love if fail2ban only sent an e-mail notification once per banned ip address, i live in an area with frequent power cuts, and each time my server reboots due to a power cut, i get 5000 e-mails, some nights with 2-3 power cuts, i get 15k emails.

i.e , i ban all failed logon attempts permanently.

Please let me know if any further info/details are needed.

Best Regards
Patric

**Comment by StephenAtty** [comment]
I'd love this too - although I don't restart fail2ban that often when I do it basically swamps my email server.

So a "don't email bans made from the DB at startup" option would be a great little feature to add.

**Comment by sebres** [comment]
Implemented in #1669 (our fail2ban v.0.10 version).

**Comment by StephenAtty** [comment]
Is this a new config item in the fail2ban.local file?

**Comment by sebres** [comment]
Shortly, no.

From this version, the parameter `norestored = 1` can be used in action config files to prevent the repeat of actionban for restored tickets. For all affected actions from the list (see https://github.com/fail2ban/fail2ban/pull/1669#issue-200693370) it is already `1`.

But you can (re)write it for any action in your `action.d/some-action.local` file (or in your own actions `action.d/my-action.conf`).

**Comment by StephenAtty** [comment]
OK thanks

I tried to install 0.10 but it just fails to run :

fail2ban-client -h
Traceback (most recent call last):
  File "/usr/local/bin/fail2ban-client", line 34, in <module>
    from fail2ban.client.fail2banclient import exec_command_line, sys
ImportError: No module named fail2banclient


I suspect its something to do with the fact that on this linux system fail2ban used to run from /usr/bin

**Comment by sebres** [comment]
> I tried to install 0.10 but it just fails to run

Firstly uninstall previous (stock) version...
Secondly if you install our common version, you can provide the bin-path with:
```bash
?sudo? python setup.py install --install-scripts=/usr/bin
```
Note that fail2ban.service (resp. init.d-script) should be installed manually.

If you not familiar, just install fail2ban from your distribution...

**Comment by StephenAtty** [comment]
Its odd because the previous version from here just installed with no problems..

Totally removed what was there before - still falls over with the same error.

But now I can't get the old .9.7 version to start up 

ERROR  Failed during configuration: Bad value substitution:
	section: [postfix]
	option : backend
	key    : default/backend
	rawval : 

from files I've not touched

**Comment by StephenAtty** [comment]
OK - it looks like something in the 0.10 install replaced something that the 0.97 didn't roll back.
removed the contents of the /etc/fail2ban directory
re-ran the 0.97 install and then copied my local files and extra filters in and its now starting back up.

**Comment by StephenAtty** [comment]
Right - I've got 0.10 running.

I removed everything to do with 0.9.7 : 
removed the binaries from /usr/local/bin
removed all the old 0.9.7 files in the python directory

Re-ran the 0.10 install .. but it looks like when you run the install script option it doesn't put the binary in there just the symbolic link to python so you have to manually copy the executables from /usr/bin to /usr/local/bin

Is now starting up fine

**Comment by kasumiru** [comment]
to hotfix it change python2 to python3 in fail2ban-client. 
can usage:
`sed  's|\#\!\/usr\/bin\/python|\#\!\/usr\/bin\/env python3|g' -i `which fail2ban-client``

**Comment by sebres** [comment]
This issue is a RFE about send mail action, please remain by the subject.

As for python version, since 0.10 the shebang in `fail2ban-*` bindings or some scripts (like actions) can also be switched to `fail2ban-python` (a link to correct python version fail2ban uses); 
Just it is a matter of installer or even distribution, that maintainers are creating for you.
Normally you'd already have correct shebang to right python version... It looks like a version conflict, as you could have two fail2ban-client files (in different bin folders, both in PATH, so wrong previously installed version wins for some reason).
But if you just switch python2 to python3, in the old fail2ban-client (like 0.9) it would then use old protocol and you could experience some issues later (let alone modules of fail2ban can be installed also in different python). So it is better to resolve this correctly (and probably to find the reason why old file was used).
