### ISSUE TITLE
netfilter-persistent save command will save Fail2ban rules

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1883]
Do we have at least a small documentation on preserving non-Fail2ban iptables rules on reboot?

Issuing `netfilter-persistent save` would **also** save Fail2ban chains.
https://packages.debian.org/stretch/netfilter-persistent

The best hack I come up is `iptables-save | grep -E -v '(:|\s)f2b-' | sed -e 's| \[[0-9]*:[0-9]*\]$| [0:0]|' > /etc/iptables/rules.v4`

Any thoughts?

**Comment by sebres** [comment]
> Any thoughts?

What could we do? Dependencies to each possible service working on iptables, ipset and others?

Just to link -  #1680 (as similar task).

**Comment by mitchellkrogza** [comment]
@szepeviktor your [rules.v4 and rules.v6 files should be constructed manually](https://ubuntu101.co.za/security/iptables-firewall/iptables-persistent-ubuntu-16-xenial/) and set to load at startup with netfilter-persistent. 

Those 2 basic firewall rules files should not include any fail2ban rules as Fail2ban takes care of adding them itself. 

Any time you want to make changes to your rules.v4 and rules.v6 files make your changes in those files and using (iptables-restore and iptables-save) they will be loaded next time you reload iptables or reboot the system. If you ever manually reload iptables with your new rules you must restart the fail2ban service yourself so it can then start adding it's bans and rules to your new iptable set.

**Comment by szepeviktor** [comment]
> Any time you want to make changes to your rules.v4 and rules.v6 files make your changes in those files and using (iptables-restore and iptables-save)

As I described the `service netfilter-persistent save` command will save Fail2ban chains also.
It basically does `iptables-save > /etc/iptables/rules.v4` which should be filtered to exclude Fail2ban rules.

So my question is really

### How to save iptables rules manually?

**Comment by szepeviktor** [comment]
I hope no one will come up with shutting down Fail2ban temporarily 😄

**Comment by sebres** [comment]
> I hope no one will come up with temporarily shutting down Fail2ban

This not :) but my question is - Why it should be an "issue" of fail2ban?
Because this does not really different to "something else modifying my iptables dynamically, how `netfilter-persistent` can properly ignore/filter this...".
IMHO, this belongs to common firewall issues, no matter which used, no matter who dynamically change the rule-set of the firewall.

If filtering (or some post processing) is not possible within `netfilter-persistent`, then perhaps the creating of the dependent service may help, filtering unneeded  entries after `save`, `stop`, etc?

Thus again, I think it is rather an issue of `netfilter-persistent`...

**Comment by szepeviktor** [comment]
Ok.
https://bugs.debian.org/cgi-bin/pkgreport.cgi?src=iptables-persistent

**Comment by sebres** [comment]
By the way, action [nftables](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/nftables.conf) uses single table (by default `f2b-table`) where all fail2ban lists and rules get created:
https://github.com/fail2ban/fail2ban/blob/725354c79315d8eac6cdc7ffa550a8acb9a01d73/config/action.d/nftables.conf#L126

So it should be a lot simpler to exclude this table by storing in netfilter-persistent (I don't use it so still have no idea how it can be configured).

**Comment by kalleswe** [comment]
No, it's a fail2ban problem. And it still needs to be fixed.

**Comment by TheAndrey** [comment]
I solved this problem by changing the fail2ban configuration files. Before creating a new rule in iptables, I added a command that tries to delete an existing rule.

**Comment by sebres** [comment]
> No, it's a fail2ban problem. And it still needs to be fixed.

Your opinion is very important to us, but... we can independently decide whether it is a fail2ban's issue or not.

However if seriously:
- external application/script/whatever (e. g. `netfilter-persistent`) saves current state of net-filter that can be basically used from whatever software (without to filter some entries of dynamic nature);
- then later it'd restore them and obviously some of those saved entries would conflict with entries created by fail2ban (or another software using net-filter to create dynamic entries);
- someone is really thinking this would be the issue of fail2ban and not of the software that stores **all rules unfiltered**?

Moreover normally this is not really solvable at side of fail2ban, simply because it would be not correct (the values stored by `netfilter-persistent` can be outdated and would bother normal work).
The "solutions" like "delete before create" or "ignore if already exists" are rather workaround, because may be error-prune (for instance ignoring errors caused by misconfiguration, e. g. if some chains of different jails called equally) and ugly.

The simplest solution is to "fix" it (basically filter all chains which name matches `f2b-*`) at side of storing application (or after it stored the to file).

**Comment by AubsUK** [comment]
Old thread, but came across it when looking for something else.

netfilter-persistent is there to do a specific task, and that is to save a copy of the current net-filter, and restore it when you reboot.  The fact that Fail2Ban creates and removes its own rules when it starts/stops, doesn't take away from netfilter-persistent's task when you run it while Fail2Ban is running.

In my opinion (and that's all it is), Fail2Ban should probably manage its own entries by their name, and move/re-use them if they already exist.  That's what I've done in the latest version of my own blockist importer script example below ...

https://github.com/AubsUK/aubs-blocklist-importer/
(the current main is v0.3.0, the below will be contained in v0.4.0 when I finish it - I'm also building in Override "internal" blocklists which will seamlessly take IPs from Fail2Ban for a permanent block, instead of filling F2B's lists up)

```
## Function to check the Parent Chain config and create where required
CheckConfigParentChain()
{
    # Check if the parent chain exists in the table
    if ! $IPTABLES_PATH -t "$IPTABLES_TABLE" -L "$PARENT_CHAIN_NAME" -n >/dev/null 2>&1; then
        $IPTABLES_PATH -t "$IPTABLES_TABLE" -N "$PARENT_CHAIN_NAME" 2>&1
        LogThis "    New parent $PARENT_CHAIN_NAME chain created in $IPTABLES_TABLE table"
    else
        LogThis "    Parent chain already exists"
    fi

    # Enforce the parent chain is linked at position 1 in the requested routing chain, excluding loopback traffic
    CURRENT_ROUTING_RULE_POSITION=$($IPTABLES_PATH -t "$IPTABLES_TABLE" -S "$IPTABLES_ROUTING_CHAIN" 2>/dev/null | $GREP_PATH -E '^-[AI]' | sed -n '1p')
    if [[ "$CURRENT_ROUTING_RULE_POSITION" != *"! -i lo -j $PARENT_CHAIN_NAME"* ]]; then
        # Remove any existing misaligned links first
        while $IPTABLES_PATH -t "$IPTABLES_TABLE" -C "$IPTABLES_ROUTING_CHAIN" ! -i lo -j "$PARENT_CHAIN_NAME" >/dev/null 2>&1; do
            $IPTABLES_PATH -t "$IPTABLES_TABLE" -D "$IPTABLES_ROUTING_CHAIN" ! -i lo -j "$PARENT_CHAIN_NAME" 2>/dev/null
        done
        # Re-insert at position 1, ensuring the loopback interface is bypassed
        $IPTABLES_PATH -t "$IPTABLES_TABLE" -I "$IPTABLES_ROUTING_CHAIN" 1 ! -i lo -j "$PARENT_CHAIN_NAME" 2>&1
        LogThis "    Parent chain forced to position 1 in $IPTABLES_ROUTING_CHAIN (Excluding loopback)"
    else
        LogThis "    Parent chain already at position 1 in $IPTABLES_ROUTING_CHAIN (Excluding loopback)"
    fi
}
```


To manage F2B rules when I import a new blocklist and save the net-filter, knowing I have F2B installed, I use (partial extract from my script):


```
#...
NETFILTER_PERSISTENT_PATH="$(command -v netfilter-persistent)"
#...
if [ ! -x "$NETFILTER_PERSISTENT_PATH" ]; then LogThis "Cannot find [ netfilter-persistent ] via command -v. Is it installed? Exiting"; exit 1; fi;
#...
# Save the new firewall state, ignore Fail2Ban rules, and make it persistent
if [ -x "$NETFILTER_PERSISTENT_PATH" ]; then
    LogThis -s "Saving persistent firewall rules (excluding Fail2Ban)..."
    "$NETFILTER_PERSISTENT_PATH" save >/dev/null 2>&1

    # Post-process the saved IPv4 rules to strip out active Fail2Ban chains
    if [ -f /etc/iptables/rules.v4 ]; then
        sed -i '/f2b-/d' /etc/iptables/rules.v4
    fi

    # Post-process the saved IPv6 rules to strip out active Fail2Ban chains
    if [ -f /etc/iptables/rules.v6 ]; then
        sed -i '/f2b-/d' /etc/iptables/rules.v6
    fi

    LogThis -e " Done"
else
    LogThis -e " WARNING: 'netfilter-persistent' not found. New rules will not be retained after a reboot."
fi
```

Or if you know what you're doing and in control, simply:

```
sudo netfilter-persistent save >/dev/null 2>&1
sudo sed -i '/f2b-/d' /etc/iptables/rules.v4
sudo sed -i '/f2b-/d' /etc/iptables/rules.v6
```

Someone might correct me and tell me I'm doing something completely wrong, and I will gladly take their advice.
