### ISSUE TITLE
One explanation about the syntax

### ISSUE THREAD

**Issue by WagnerGMD** [fail2ban/fail2ban#1890]
Hello,

I had create one new file (or jail) inside the folder `/etc/fail2ban/filter.d`.
But it's seem to be complicated to write (or to get my aim)... In fact, I have met these errors (and no it isn't very clear) :
```
Init of command line failed [...]
Unable to compile regular expression [...]
## What's wrong with my var (or variable) ? To give you one little example :
ListNameToBlock = phpmyadmin|PMA|
		mysql|
		webdav|
		## etc Because my list is long.
## The trouble is cause by each new line ?
```
In fact, for me it will be easier to read my file. I want to write my var on several lines (to precise, it want one word by line and as you can guess combine the regex). So could you tell me the right syntax ? How should I proceed to prevent these errors ?

At the contrary, it's seem to work only in one line (such as) :
`ArrayNameToBlock = phpmyadmin | PMA | mysql | webdav`

Kind regards.

PS : Right now, I have Fail2Ban_v0.11 under Debian 9 (aka Debian Stretch). It was installed with Python_v3.6.2 and I'm little familiar with Python but it isn't the same with Fail2ban (very light).

**Comment by sebres** [comment]
This is not a bug, is a feature :)
The parameter `failregex` which contains as part the ListNameToBlock, can hold multiple regexp's, separated by newline.
This occurs because after interpolation of whole `failregex` this will be splitted by newline, thus your regexp will be wrong.
With other words, it is impossible to use newline inside such parameters.

**Comment by WagnerGMD** [comment]
Thank you for the reply but Fail2Ban is based on Python, that's right ? Then could I define a var with a particular syntax ("\n", """, "[]", etc)? I can't use the same syntax (list, array, dico, etc) ?
Unless I could use an operator (like in the aim to concatenate strings) ? For me, it's sound a little strange.

**Comment by sebres** [comment]
1. We speek about INI-file. No matter which language used for programming.
2. The NL is historiy

**Comment by sebres** [comment]
FWIW: Just to extracting the groups and put it after the split will not work, because in this case python will compile the regex using a new line as character (that should match). At least if flag VERBOSE not specified (but then it is incompatible, because e. g. the spaces should be escaped resp. written explicit as `\s`)...

The only way I see here would be an intelligent split like below:
Remove `\n` characters in all the groups in parentheses `(...)` before split, thereby taking into account the open/closed parentheses-pairs (what is not so easy).
If I get a bit time I can try to implement such thing.

**Comment by WagnerGMD** [comment]
I imagine it would be nice if you can.
```
start = admin|dbadmin
phpmyadmin = pma|phpadmin|phpmyadmin|phpmy|php-my-admin
sgbdr = database|db|mysql
end = wallet|wp
block = (<start>|<phpmyadmin>|<sgbdr>|<end>)
failregex = ^(?i)<HOST> .* "(GET|POST|HEAD) .*(%(block)s).* HTTP.*" (400|403|404|444) .*$
ignoreregex =
```
About two weeks ago, I had discover [this article](https://www.binsp.net/?post/fail2ban-proteger-serveur-des-bots). Then I was inspired and I believe I had found one solution. At least until now it seeem's to work as expected.
It could improve by one regex, right ? How check the number (after a word or letter) ?
A few examples :
- xEA\x00\xDEc\x1E\xED{\xC2e\x9B\xB1\x9E\xA6\xFF
- 4phpmyadmin
- \x03\xA9\xF8\x1Cv\xA8
- phpmyadmin2
- \x16\x03\x01\x01\x22\x01\x00\x01

**PS :**
- After a reboot I had met one trouble with Fail2Ban... The solution was to recreate it : `mkdir /var/run/fail2ban`.
- It woudn't be better to store them ? Because in the aim to restart Fail2Ban, I need to run the both commands :
```
fail2ban-client stop;
fail2ban-client start;
## I avoid to use "fail2ban-client reload;" because no it doesn't work and it's sound complicated...
```
That's why the list of IP was clean (entirely) and despite the fact I had installed the package **iptables-persistent**.
