### ISSUE TITLE
Mikrotik Integration

### ISSUE THREAD

**Issue by a16bitsysop** [fail2ban/fail2ban#1906]
I am integrating fail2ban on a raspbian pi (stretch) to a mikrotik router (6.40.4), with instructions from here:
https://wiki.mikrotik.com/wiki/Use_Mikrotik_as_Fail2ban_firewall

The instructions are a bit outdated and you need to use rsa keys not dsa keys for it to work without further configuration.

I have got it working adding and removing ip addresses to a filter with an action.d/mikrotik file with:
```
actionban = mikrotik ":ip firewall filter add action=drop chain=forward dst-address=<ip> comment=AutoFail2ban-<ip>"

actionunban =  mikrotik ":ip firewall filter remove [:ip firewall filter find comment=AutoFail2ban-<ip>]"
```
This adds and removes address to the forward chain, however it is the bottom of the forward chain and after accept established so it only drops new connections.  

I found the easiest solution would be to have an address list for fail2ban which I then create rules for where I want.

I can do this with:
actionban = mikrotik ":ip firewall address-list add list=fail2ban address=<ip> timeout=36000 comment=AutoFail2ban-<ip>"

Which includes a timeout field which automatically deletes the entry when the timeout is reached, this is the easiest way to do it as you have to delete by rule number not matching the ip and list on mikrotik.

To work fully this needs a <bantime> variable available to the action.d configuration, is this going to be implemented?

**Comment by sebres** [comment]
> To work fully this needs a variable available to the action.d configuration...

If I correct understand, you want the current value of the ban-time.
Thus the answer is not so easy. 
The ban-time is variable since fail2ban version 0.11 (can variate through incremental ban). So for this version it is enough to use the interpolation `<bantime>`...
Note, that besides `actionban` you may need to implement `actionprolong` for this version...
```INI
actionban = my-ban-cmd <ip> --timeout=<bantime>
# the same for prolongation:
actionprolong = %(actionban)s --comment="prolongation"
```

Versions before 0.11 have static parameter `bantime`, however you should supply it to the action via your own parameter:
```INI
# jail.local:
banaction = my-action[timeout=%(bantime)s, another-param="...", ...]
```
```INI
# action.d/my-action.conf:
actionban = my-ban-cmd <ip> --timeout=<timeout>
```

**Comment by a16bitsysop** [comment]
Hi,
Thanks for your reply, yes you are correct I wanted the current value of ban time.
I have checked and raspbian stretch currently has 0.9.6-2 of fail2ban.

So I can add the variable in fail2ban configs, but a better bash script for ‘mikrotik’ that can find the correct rule number on the address list is the best answer you are saying and let fail2ban deal with ban times as they can increase?


Regards,
Duncan

**Comment by sebres** [comment]
> and let fail2ban deal with ban times as they can increase?

Anyway it will expect a configuration change...
As already said v.0.11 have action-parameter `bantime`. But v.0.9 and v.0.10 both don't have (only in the jail).
Thus if you'll supply it to the action (v.0.9) you should remove / rewrite it as in example above after upgrate to v.0.11...

**Comment by a16bitsysop** [comment]
Thanks, I will add the variable and work on the ‘miktotik' script then see if the mikrotik wiki will update it with an address-list action.

Regards,
Duncan

**Comment by sebres** [comment]
Also, if you want to contribute here - welcome with PR for mikrotik action...

**Comment by a16bitsysop** [comment]
I have done it now with just rules in action.d/mikrotik.conf 

`#add to ban address-list "fail2ban"
actionban = mikrotik ":ip firewall address-list add list=fail2ban address=<ip> comment=AutoFail2ban-<ip>"

#remove from ban address-list "fail2ban
actionunban =  mikrotik ":ip firewall address-list remove [:ip firewall address-list find comment=AutoFail2ban-<ip>]"
`

**Comment by sebres** [comment]
Well, if I can follow this is a bit worse, because the comment may be non unique:
if you've more as one jail using this action, this should contain the jail name (otherwise will delete the rules of second jail if the same IP will be unbanned by first jail).

Rather you need to add the jail to the list:
```diff
- actionban = mikrotik ":ip firewall address-list add list=fail2ban address=<ip> comment=AutoFail2ban-<ip>"
+ actionban = mikrotik ":ip firewall address-list add list=f2b-<name> address=<ip> comment=AutoFail2ban-<ip>"
```
Or to the comment:
```diff
+ ip_id = AutoF2B-<name>-<ip>
- actionban = mikrotik ":ip firewall address-list add list=fail2ban address=<ip> comment=AutoFail2ban-<ip>"
+ actionban = mikrotik ":ip firewall address-list add list=fail2ban address=<ip> comment=%(ip_id)s"
- actionunban =  mikrotik ":ip firewall address-list remove [:ip firewall address-list find comment=AutoFail2ban-<ip>]"
+ actionunban =  mikrotik ":ip firewall address-list remove [:ip firewall address-list find comment=%(ip_id)s]"
```
Currently don't have the box with mikrotik at hand, thus you can self look wich of both is better for common case, but I think you can use the first variant (additionally write actionstart/actionstop for automatically add/remove the list `f2b-<name>` with corresponding rules for chain, dst-port and protocol)...
