### ISSUE TITLE
Ban the MAC!  Feature Request

### ISSUE THREAD

**Issue by apb1963** [fail2ban/fail2ban#1920]
Please note - at least on ubuntu 16.04 - the MAC address associated with an IP is available.  If we could ban based on MAC, then we need not ban those people allocated a dynamic IP address previously belonging to a cracker, and instead ban only the cracker - permanently (or at least until they change their MAC).  While spoofing is easy enough, the cracker has to realize his MAC has been banned.  PLUS if one comes under a MAC ATTACK (sorry, couldn't resist), it helps uniquely identify the cracker so that the appropriate authorities can be alerted should one desire to do so.  

(A second unrelated feature request - I would like to see the right authority automatically alerted when someone gets banned - i.e. the cracker's ISP abuse address perhaps.)

Sample command:
iptables -A INPUT -p tcp --dport 1723 -m mac --mac-source 00:11:22:33:44:55 -j ACCEPT

The below was obtained through iptables logging.  There are probably other ways to get the src MAC.

Oct 15 00:20:19 yellow kernel: [25713.800316] [netfilter] Dropped: IN=enp5s0
+OUT= MAC=70:85:c2:3b:13:24:64:66:b3:a0:07:22:08:00 SRC=64.187.217.234
+DST=192.168.1.101 LEN=48 TOS=0x00 PREC=0x00 TTL=118 ID=43070 PROTO=TCP
+SPT=14400 DPT=22 WINDOW=65535 RES=0x00 SYN URGP=0

**Comment by sebres** [comment]
The issue with MAC is: too easy to change it (compared to IP-address), and to have **ANY** MAC-address, thus can overlap with some non-attacker MAC but still worse to intentionally change of MAC to cause a banning someone other. 
Just imagine: there are 2 competed sites in google top for "buy candies", the site B has configured MAC banning and the site A (evil competitor) has found it out. 
To "ban" each potential visitors of site B, it would be enough to make X requests from the site A with net-adapter with changed MAC of (for) each visitor. This will completely avoid the visiting of this people to the site B after visiting of site A.
And I can imagine much more similar scenarios...

As regards the permanent banning - it is anyway too fragile - just growing a chain (and burdens it several years, also if the IP/MAC become clean/are changed/not exists anymore).
For this purposes better to use incremental banning (introduced in v.0.11).

BTW. Banning of the MAC is already possible with custom filter and action, see <a href = "https://github.com/fail2ban/fail2ban/wiki/How-to-ban-something-other-as-host-(IP-address),-like-user-or-mail,-etc.">[wiki] How to ban something other as host (IP address), like user or mail, etc. · fail2ban/fail2ban Wiki</a>.

**Currently I don't see any advantages for this and I tend to close this as unlikely to be implemented.**

> A second unrelated feature request - I would like to see the right authority automatically alerted when someone gets banned

What is the problem? Just create your own action e. g. `notify-right-authority` like here:
```INI
# action.d/notify-right-authority.local
[Definition]
actionban = notify-right-authority-command '<auth>' 'failure for <F-USER> from <ip>:<F-PORT>' '<matches>' ...
```
To use it, extend action in default section or corresponding jail:
```INI
# jail.local
[sshd]
action = %(action_)s
         notify-right-authority[auth='admin']
```
Instead of your own action `notify-right-authority` you can use many another available actions (like [mail-whois-lines](https://github.com/fail2ban/fail2ban/blob/b5dd5adb08f9fd3496f8c63b1d53b0e3c6aabbf1/config/action.d/mail-whois-lines.conf), sending a mail)...

**Comment by miken32** [comment]
Also, MAC addresses do not leave the local network. They are layer 2.

**Comment by sebres** [comment]
Oh, right, exactly... Thus it will ban some router (The MAC addresses are removed once it crosses out of the broadcast domain (moves across a router), resp. replaced with the appropriate addresses in the next broadcast domain.

Thus I don't see the benefit of this RFE.
