### ISSUE TITLE
action.d/pf.conf misleading nested anchor description

### ISSUE THREAD

**Issue by mkeilwaldbrunn** [fail2ban/fail2ban#1923]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.1
- OS, including release name/version: FreeBSD 11.1
- [x] Fail2Ban installed via OS/distribution mechanisms

### The issue:

./action.d/pf.conf describes the anchor mechanism in /etc/pf.conf

` 
we don't enable PF automatically; to enable run pfctl -e
or add `pf_enable="YES"` to /etc/rc.conf (tested on FreeBSD)
also, these rulesets are loaded into (nested) anchors
to enable them, add
anchor f2b {
name1
name2
  ...
 }
`
This syntax doesn't comply whith pf-syntax

#### Expected behavior
A valid nested anchor looks like:

`anchor f2b {
   {anchor name1}
   {anchor name1} }`

Since anchors are inserted dynamically by f2b it's even more appropriate to define one single  wildcard anchor:

`anchor "f2b/*"`

**Comment by chtheis** [comment]
I think this is fixed upstream, in the fail2ban sources. The fix was 
made soon after I submitted the FreeBSD port. I didn't update the port 
yet because there were and are other and more serious issues with pf 
than this one.

Once the pf issues are solved (or a new version of fail2ban is released) 
I will update the port.


Best regards

Christoph

Am 17.10.2017 um 07:45 schrieb mkeilwaldbrunn:

**Comment by sebres** [comment]
closed as duplicate, further in #1915
