### ISSUE TITLE
Does fail2ban support send email use third-party SMTP server, like Gmail and so on, not use sendmail.

### ISSUE THREAD

**Issue by charleslxh** [fail2ban/fail2ban#1930]
Does fail2ban support send email use third-party SMTP server, like Gmail and so on, not use sendmail.

I have a gmail account, I want to send email by google email server directly, not setup a local smtp server.

**Comment by sebres** [comment]
Following is possible:
1. Either you can configure sendmail to send mails via external smtp, for example see [here](https://linuxconfig.org/configuring-gmail-as-sendmail-email-relay)
2. We've an pythonic [smpt-action](https://github.com/fail2ban/fail2ban/blob/0.10/config/action.d/smtp.py) (currently used for test purposes only), but possibly you can get it running.
Try something like:
```INI
# jail.local:
[sshd]
action = %(action_)s
         smtp.py[host="host:25", user="my-account", password="my-pwd", sender="sender@example.com", dest="example@example.com", name="%(__name__)s"]
```
3. Or you can create new action, or rewrite any already available mail-action, e. g. like here:
```INI
# action.d/my-mail.local extended "mail-whois-lines.conf":

[INCLUDES]
before = mail-whois-lines.conf

[Init]
# original:
## mailcmd = mail -s
# new:
mailcmd = my-mail-command ... --subject
```
4. If you use fail2ban v. >= 0.10, you can easy redefine each action-parameter of some default action, directly in you `jail.local`:
```INI
[sshd]
action = %(action_)s
         mail-whois-lines[mailcmd="my-mail-command ... --subject", dest="example@example.com", name="%(__name__)s", ...]
```
Note: not all our actions currently have a parameter `mailcmd`, take a look in corresponding action conf-file to check which parameters could be overriden.

**Comment by shunkica** [comment]
I am trying to use method #2 with f2b v0.9.7 but I get this warning:
`fail2ban.transmitter: WARNING Command ['set', 'sshd', 'addaction', 'smtp', '/etc/fail2ban/action.d/smtp.py', '{"dest": "myemail", "host": "myhost", "password": "mypassword", "user": "myuser", "name": "sshd"}'] has failed. Received TypeError("__init__() got multiple values for keyword argument 'name'",)`

**Comment by sebres** [comment]
Well the smpt-action used currently for test-purposes only.
I don't know why the name received twice for you, but you can try it without `, name="%(__name__)s"` inside supplied parameters. Use `fail2ban-client -d | grep smtp` to see which parameters the action will get.

Otherwise, sendmail can be configured to use extern smtp-server... So you can use other mail-actions.

1. [Configuring Gmail as Sendmail email relay - LinuxConfig.org](https://linuxconfig.org/configuring-gmail-as-sendmail-email-relay)
2. [How To Send Email through an External SMTP Service with Sendmail on FreeBSD 10.1 | DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-send-email-through-an-external-smtp-service-with-sendmail-on-freebsd-10-1)

**Comment by rohitchormale** [comment]
Just for reference, first link mentioned above is not working on Ubuntu 18.04 because of [this bug](https://github.com/systemd/systemd/issues/9833)
