### ISSUE TITLE
Stop keeping track of bans in local database

### ISSUE THREAD

**Issue by scifibob** [fail2ban/fail2ban#1941]
I'm adding banned ip's to a blacklist on my firewall (not running on the fail2ban pc) with parameters to say how long they should stay on the list, using address lists on a RouterOS firewall.
The firewall takes care of removing them after the specified interval.

Therefore, I do not need fail2ban to keep track of the bans, my firewall does that.

My problem is that every time I restart my mail server (running fail2ban) it spends several minutes to unban all ip's, and when it starts up again it spends a lot of time adding every ip again.

I've tried modifying bantime and findtime without any luck. 

All I want is for fail2ban to just ban ip's when they connect, and restart without any unban and ban again, since they already are banned on my firewall.

### Environment:
Ubuntu Server 16.04
fail2ban version 0.9.3-1 (standard 16.04 package installed with Aptitude).

**Comment by sebres** [comment]
> I've tried modifying bantime and findtime without any luck.

This doesn't matter for already banned IPs.

> it spends several minutes to unban all ip's, and when it starts up again it spends a lot of time adding every ip again.
See https://github.com/fail2ban/fail2ban/issues/1588#issuecomment-256640688 and #1743.

If you don't need still active bans, you can:
- delete database before fail2ban-start or configure your fail2ban without database (just set `dbfile = ` empty value in your `fail2ban.local` in order to overwrite corresponding entry in [fail2ban.conf](https://github.com/fail2ban/fail2ban/blob/0.9/config/fail2ban.conf#L64);
- unban each not needed IPs manually (this will delete all tickets from database also);
- unban all IPs at all (v0.10 only) using `fail2ban-client unban --all` implicit before stop in order to restart;

**Comment by brianjmurrell** [comment]
I have the same model.  I ban IPs in the firewall, which is different than the machines running fail2ban.  So ultimately, when fail2ban stops, even in the case of the machine running fail2ban rebooting, the bans are still working and active on the firewall.

Therefore, I would like fail2ban to be able to understand that the "ban" state is preserved across stop/start/reboot/etc. and not try tear-down and recreate this state on stop/start.

That doesn't mean however that I don't want it to still keep a database of what it's banned.  That is useful otherwise.

`actionflush` seems to be half of this problem solved.  The other half however is the opposite.  Being able to tell fail2ban to start without trying to create 1000s of bans that actually already exist.

**Comment by sebres** [comment]
> Being able to tell fail2ban to start without trying to create 1000s of bans that actually already exist.

Well, somewhat should restore the active banned IPs after restart. 
Either it is a net-filter (some persistent rules), or it is fail2ban.
Due to a lot of different banning actions it would not so easy to implement a construct completely replacing fail2ban's ban-manager (or considering the tickets from firewall subsystem after restart), which must also know all the banned tickets with its end-of-ban (to be able to trigger unban for every ticket after expiration).

Furthermore, there is concept for a bulk ban/unban functionality (allowing to ban couple of IPs in single step)... Work in progress, please be patient.

If you wanted to handle ban expiration in your custom action (e. g. your net-filter can handle unban by itself due to internal timeout), just create an action which would use `actionban` with a timeout you need use as a ban time, no `actionunban` at all (empty), and set some short bantime for the jail (e. g. `1m`), so your fail2ban would "forget" the ticket in 1 minute, where your net-filter can get larger timeout from action, so the ban is active much longer.
I know it looks like a workaround either, but I don't have better solution at the moment.

**Comment by brianjmurrell** [comment]
> Well, somewhat should restore the active banned IPs after restart.

No.  Restore bans is not needed.  The bans are being enforced on a remote machine so they persist fail2ban (running on different machine) stopping/starting/machine-rebooting/etc. (assuming fail2ban doesn't unban on stop/shutdown of course).

> Either it is a net-filter (some persistent rules), or it is fail2ban.

I'm not really sure what that means.  It is fail2ban running, analysing logs, etc. and telling a remote machine to add the rule blocking the IP address.  This is why the banning state survives fail2ban stopping and/or the machine fail2ban is running on restarting.

> Due to a lot of different banning actions it would not so easy to implement a construct completely replacing fail2ban's ban-manager

That's not what is being asked for.  I think you are reading much too much into this.

All that is being asked for is the simple manner of being to tell fail2ban not to create bans on startup because they are still present from when it stopped.  All else remains the same in fail2ban processing.

> Furthermore, there is concept for a bulk ban/unban functionality (allowing to ban couple of IPs in single step)... Work in progress, please be patient.

This might be quite useful also.  I have often thought that such a facility would be useful.

> If you wanted to handle ban expiration in your custom action (e. g. your net-filter can handle unban by itself due to internal timeout),

I think OP does that, but I do not.  I still let fail2ban handle unban in addition to ban.

> just create an action which would use `actionban` with a timeout you need use as a ban time, no `actionunban` at all (empty), and set some short bantime for the jail (e. g. `1m`), so your fail2ban would "forget" the ticket in 1 minute, where your net-filter can get larger timeout from action, so the ban is active much longer.

Again, all much more complicated than necessary.

I'm just looking for a "switch" in an action that tells fail2ban on startup not to try to re-create bans as it can assume they are already there.

**Comment by sebres** [comment]
> I'm just looking for a "switch" in an action that tells fail2ban on startup not to try to re-create bans as it can assume they are already there.

And such "switch" is already implemented years ago, see #1669.
The tickets loaded by restart marked as "restored" - the tag `<restored>` as value in action signaling that a ticket is restored after restart as well as action option `norestored = true`, to complete avoid of execution ban/unban for such tickets. 
Note in this case (using norestored) it would not be called for unban also, so probably something like this in actionban is your choice either:
```bash
if [ '<restored>' = '1' ]; then exit 0; fi;
```

**Comment by sebres** [comment]
Hmm... Checked source code and it looks like norestored is currently affecting ban (and prolong) only. Unban is completely unaffected.
So thinking a bit about that, I guess this could be probably enough for your needs:
```ini
[Definition]
# avoid (re)ban after restart:
norestored = true
# ban ticket:
actionban = some-command ban -persistent "<name>/<ip>"
# unban ticket:
actionunban = some-command unban -persistent "<name>/<ip>"
# flush (dummy, do nothing):
actionflush = echo ok
```
Just in this case there is no possibility to stop fail2ban together with flush functionality (stop doesn't cause a flush/unban all IPs) at all. 
In this case you've to use your firewall additionally to force a complete stop (with unbanning):
```bash
fail2ban-client stop "$jail" && some-command flush "$jail"
```
I must admit I have no better idea at the moment (at least unless bulk functionality gets implemented).

**Comment by brianjmurrell** [comment]
I was thinking of much the same.

Now that I have added `actionflush = true` (a NOOP) and `norestored = true` to my action, and given that all of my jails use my action, what is the most effective method of applying those changes to the existing/running fail2ban that doesn't involve that running fail2ban trying to apply one last landslide of unban actions for all of the existing bans?

Surely simply stopping that fail2ban at this point won't achieve that as it doesn't yet know about the `actionflush = true` that I added to my action configuration file.

**Comment by sebres** [comment]
> what is the most effective method of applying those changes to the existing/running fail2ban

If your action name is unchanged (as well as other parameters like chain name or something else expecting refreshing of net-filter), the simplest way would be to use `fail2ban-client reload` (it does not cause a reban).
