### ISSUE TITLE
Understanding 0.10 changes

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1946]
I am trying to get familiar with 0.10 as I have to update my local configuration.

There are things like

> `<F-...>` - interpolates to the corresponding filter group capture `...`

which needs to be explained to me.

Are there plans to **explain 0.10 changes in depth** or *We know the changes, and sorry for people not being able to understand our changelog + source code* ?

**Comment by szepeviktor** [comment]
I've found a note: https://github.com/fail2ban/fail2ban/blob/0.10.1/ChangeLog#L48

> documentation should be extended (new options, etc)

**Comment by sebres** [comment]
> Are there plans to explain 0.10 changes in depth or We know the changes, and sorry for people not being able to understand our changelog + source code ?

I don't understand your objection... Many features of v.10 were made as RFE with corresponding issues (e. g. #1110) resp. PR (e. g. #1698). Because of the lack of time is not always documented good enough, but possibly the PR resp. discussions in the issues can give you more information.
The last question about this handling was answered in https://github.com/fail2ban/fail2ban/issues/1935#issuecomment-339113985. IMHO there it is described pretty clear.

**Comment by szepeviktor** [comment]
@sebres Thank you.

This issue is not about the particular feature but the whole 0.9 -> 0.10 migration.
I don't dare to say "expect" but I would definitely welcome a migration guide.

Do you think we have the resources to produce one?

**Comment by sebres** [comment]
I would say: if you get any issue by migration, so welcome with the list here;
If you've any idea about or want write such a migration guide - I think our wiki is more interesting place for it as the issue.
But you can collate here as draft list - I could put it together as an article for the wiki later.

**Comment by szepeviktor** [comment]
Thank you.
