### ISSUE TITLE
failregex for apache filter

### ISSUE THREAD

**Issue by hardlick** [fail2ban/fail2ban#1972]
Hi, please can you help me?
my access.log on apache has this format:
```
174.227.129.60 websales.hgjgf.com - [27/Nov/2017:19:19:11 -0600] "PROPFIND /media/images/redcoach/mail-icon-3.jpg HTTP/1.1" 403 336 "-" "-"
52.169.5.162 websales.gjhghj.com - [27/Nov/2017:19:17:36 -0600] "POST /public/ApiFriendly/getTravels HTTP/1.1" 403 328 "-" "-"
```
and the filter on:
/etc/fail2ban/filter.d/apache-badbots.conf
```INI
failregex = ^<HOST> -.*"(GET|POST|HEAD).* HTTP\/.*$
```
But not match :(
please help!
what is the correct failregex

**Comment by sebres** [comment]
BTW I don't like apache-badbots (and other similar filter), because too many greedy catch-alls for me.
The filter search known user-agents, see the [badbots resp. badbotscustom](https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/apache-badbots.conf#L11). And therefore does not match, because both from your excerpt don't have user-agent at all.
Perhaps you should try another filter or you would write your own filter to cover this (fail2ban-regex is your friend by building of the regex).

Additionally in the regex you mentioned is a `-` character after IP, that you don't have.
```diff
-^<HOST> -.*"(GET|POST|HEAD).* HTTP\/.*$
+^<HOST> .*"(GET|POST|HEAD).* HTTP\/.*$
```
But as already said it's too bad IMHO, below you'll find better regex (at least not so vulnerable as above-mentioned):
```diff
-^<HOST> -.*"(GET|POST|HEAD).* HTTP\/.*$
+^<HOST>[^"]+"[A-Z]+[^"]* HTTP\/[\d\.]+" 40[34]
```

Here is not a common forum for such queries, thus next time please seek somewhere else for such questions.
