### ISSUE TITLE
ip6tables not initialized

### ISSUE THREAD

**Issue by koeppea** [fail2ban/fail2ban#1984]
in the 0.11 branch, in the file *config/action.d/iptables-common.conf* an section exists to address the IPv6 variant of iptables:
```
[Init?family=inet6]

# Option:  blocktype (ipv6)
# Note:    This is what the action does with rules. This can be any jump target
#          as per the iptables man page (section 8). Common values are DROP
#          REJECT, REJECT --reject-with icmp6-port-unreachable
# Values:  STRING
blocktype = REJECT --reject-with icmp6-port-unreachable

# Option:  iptables (ipv6)
# Notes.:  Actual command to be executed, including common to all calls options
# Values:  STRING
iptables = ip6tables <lockingopt>
```
But I don't know how to make use of it. When starting fail2ban, I just see that **actionstart** is executed for iptables. ip6tables remain uninitialized.
Could you pls give me a hint how to make use of the inet6 family?

Thanks.

**Comment by sebres** [comment]
> ip6tables remain uninitialized.

I think this occurs because of the new feature "starting actions on demand", see #1742.
For example this avoid fails by start of ipv6-related actions on systems without IPv6 support.
If you want to start it directly by jail-start, just use `actionstart_on_demand = true` in locals of action, resp. `action = iptables[actionstart_on_demand=true]` in jail.local.

**Comment by sebres** [comment]
Of course `actionstart_on_demand = false`, true is default... Sorry for typo.
