### ISSUE TITLE
malformed database schema

### ISSUE THREAD

**Issue by dansperfect** [fail2ban/fail2ban#1993]
Alright so now that I have fail2ban working and it's banning people I have one last question. I get these errors

```
No file(s) found for glob /var/log/mariadb/mariadb.log
 NOK: ('malformed database schema (bans_ip) - no such table: main.bans',)

```
Do I need to worry about these? I do not have mariadb and nothing i can find in fail2ban refers to mariadb.  Is this something that should be ignored. I have googled and looked on here but cannot find anything about these.

**Comment by sebres** [comment]
> No file(s) found for glob /var/log/mariadb/mariadb.log

You've enabled mysql jail, but either you don't have it or it log into other log-file (on some systems default is mariadb instead of mysql).
Set proper `logpath` for this jail or disable it (if not active).

> NOK: ('malformed database schema (bans_ip) - no such table: main.bans',)

Something is wrong with your fail2ban database (possibly you've mixed some versions of fail2ban or switched there and here). 
So just stop fail2ban and remove file `/var/lib/fail2ban/fail2ban.sqlite3` (make a backup firstly) and start fail2ban again.
Be sure it affects the same file you've specified in your fail2ban.local (.conf) with option `dbfile`.
If issue still persist, please let me know...
