### ISSUE TITLE
Failed to execute ban jail (Debian 9 Stretch / v0.9.6)

### ISSUE THREAD

**Issue by shellshocker** [fail2ban/fail2ban#1997]
### Environment:
- Fail2Ban version: v0.9.6
- OS, including release name/version: Debian Jessie 9 (Stretch)
- [x] Fail2Ban installed via OS/distribution mechanisms: apt-get instal fail2ban

### The issue:
After a couple of hours fail2ban will stop working and all iptables rules from fail2ban gets flushed. 

#### Any customizations done to /etc/fail2ban/jail.local (relevant part) configuration
```
[wp-auth]
enabled  = true 
port     = http,https 
filter   = wp-auth 
logpath  = /var/log/nginx/error.log 
maxretry = 0
findtime = 86400
# 28 Tage Ban
bantime  = 2419200
```
#### Filter /etc/fail2ban/filter.d/wp-auth.conf:
```
# wp-auth filter /etc/fail2ban/filter.d/wp-auth.conf: 
# 
# Detection of not allowed IPs based on nginx IP restriction in WordPress.
# 
# Server: Nginx 
# Author: XY
#

[Definition]

# Option: failregex 
# Notes : Blocks IPs with nginx 'access forbidden by rule' response.
# Values: TEXT 
#

failregex = access forbidden by rule.*client: <HOST>.*".*/(wp-login.php|wp-admin).*"

# Option: ignoreregex 
# Notes : Regex to ignore. If this regex matches, the line is ignored. 
# Values: TEXT 
#

ignoreregex =
```

#### Relevant parts of /var/log/fail2ban.log file:
```
20955:2017-12-11 12:33:02,542 fail2ban.action         [1665]: ERROR   iptables -w -n -L INPUT | grep -q 'f2b-wp-auth[ \t]' -- stdout: b''
20956:2017-12-11 12:33:02,542 fail2ban.action         [1665]: ERROR   iptables -w -n -L INPUT | grep -q 'f2b-wp-auth[ \t]' -- stderr: b''
20957:2017-12-11 12:33:02,542 fail2ban.action         [1665]: ERROR   iptables -w -n -L INPUT | grep -q 'f2b-wp-auth[ \t]' -- returned 1
20958:2017-12-11 12:33:02,542 fail2ban.CommandAction  [1665]: ERROR   Invariant check failed. Trying to restore a sane environment
20959:2017-12-11 12:33:02,651 fail2ban.action         [1665]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports http,https -j f2b-wp-auth
20962:2017-12-11 12:33:02,652 fail2ban.action         [1665]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports http,https -j f2b-wp-auth
20965:2017-12-11 12:33:02,652 fail2ban.action         [1665]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports http,https -j f2b-wp-auth
20968:2017-12-11 12:33:02,652 fail2ban.actions        [1665]: ERROR   Failed to execute ban jail 'wp-auth' action 'iptables-multiport' info 'CallingMap({'ipfailures': <function Actions.__checkBan.<locals>.<lambda> at 0x7f56a46e5b70>, 'time': 1512991982.4321287, 'ipmatches': <function Actions.__checkBan.<locals>.<lambda> at 0x7f56a46e50d0>, 'failures': 1, 'matches': '2017/12/11 12:33:01 [error] 14564#14564: *68350 access forbidden by rule, client: 171.4.92.208, server: www.xy.de, request: "GET /wp-login.php?action=register HTTP/1.1", host: "www.xy.de", referrer: "https://www.xy.de/"', 'ipjailmatches': <function Actions.__checkBan.<locals>.<lambda> at 0x7f56a46e5158>, 'ipjailfailures': <function Actions.__checkBan.<locals>.<lambda> at 0x7f56a46e51e0>, 'ip': '171.4.92.208'})': Error stopping action
```

I can provide more details / log files. Configuration was working rock solid on Debian Jessie 8.

**Comment by sebres** [comment]
> fail2ban will stop working and all iptables rules from fail2ban gets flushed.

Possibly you miss some dependencies (to some service flushing iptables)? I mean something (firewall, etc) has flushed iptables... 
It looks like fail2ban was not able to find chain `f2b-wp-auth`, and started restore sane environment process (meant stop/start of "broken" action in "broken" jail, that was also not successful for some reasons).

I don't see how we could help you here... More details resp. logs will get nothing here.
But you can try to test the commands from iptables-multiport. All affected command-lines you'll see if you do a dump `?sudo? fail2ban-client -d | grep wp-auth`...
There are:
- actionstart - starts the jail-action (executed once by start and after failed check);
- actioncheck - checks the jail-action is still active;
- actionban - ban IP
- actionstop - stops the jail-action (executed once by stop and after failed check, before start again);

> Configuration was working rock solid on Debian Jessie 8.

The configuration of the filter is redundant here, because only the action acts on iptables level.
The action iptables-multiport works fine with Stretch, but v.0.9.6 is actually too old (I can not say what can be broken there, because I use v.0.11 already several years)

**Comment by shellshocker** [comment]
Well the jail, rule and iptables is working fine. But after some time fail2ban crashes. I don't know how or why.

**Comment by shellshocker** [comment]
I disabled the jail and will look into the problem. It might be helpful, to keep the issue open.

**Comment by sebres** [comment]
We can keep it open, but the development of 0.9th version is anyway discontinued...

**Comment by shellshocker** [comment]
> We can keep it open, but the development of 0.9th version is anyway discontinued...

Well that may be true, but not for linux distros based on Debian GNU/Linux. ;-)

**Comment by sebres** [comment]
Well, you seek for help here and not by maintainers of this "distros"...
Really, why it should be our problem, if the maintainers are too slow?

**Comment by shellshocker** [comment]
> Well, you seek for help here and not by maintainers of this "distros"...
Really, why it should be our problem, if the maintainers are too slow?

Well you are developing fail2ban. I would say it's a start to get an idea of the problem. Furthermore I wouldn't say that the maintainers are slow. It's a different sytle and thinking. 

Maybe I should search for an fail2ban alternative, since this is not "your problem". ;-)

**Comment by Vagrantin** [comment]
I'm experiencing the same issue, just seen that a 0.9.7-2 is available on sid, I'll give a try.
Also seems that all rules are stored under f2b-default not under the specific corresponding chain name.
Currently gathering data, we'll update here if I find something useful.

Matth

**Comment by sebres** [comment]
> Also seems that all rules are stored under f2b-default not under the specific corresponding chain name.

This may cause indeed this issue in some cases. Which banaction do you use?

**Comment by dedetok** [comment]
I have no problem running Fail2ban from Debian Stretch Distribution package.

# uname -an
Linux example.com 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
# service fail2ban status
* fail2ban.service - Fail2Ban Service
   Loaded: loaded (/etc/systemd/system/fail2ban.service; enabled; vendor preset:
 enabled)
   Active: active (running) since Mon 2018-01-01 11:26:18 WIB; 31min
ago
     Docs: man:fail2ban(1)
  Process: 15494 ExecStop=/usr/bin/fail2ban-client stop (code=exited, status=0/S
UCCESS)
  Process: 15567 ExecStart=/usr/bin/fail2ban-client -x start (code=exited, statu
s=0/SUCCESS)
 Main PID: 15572 (fail2ban-server)
    Tasks: 13 (limit: 4915)
   CGroup: /system.slice/fail2ban.service
           `-15572 /usr/bin/python3 /usr/bin/fail2ban-server -s /var/run/fail2ba
n/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid -x -b

Jan 01 11:26:16 example.com systemd[1]: Starting Fail2Ban Service...
Jan 01 11:26:17 example.com fail2ban-client[15567]: 2018-01-01 11:26:17,415 fail2ban.se
rver         [15568]: INFO    Starting Fail2ban v0.9.6
Jan 01 11:26:17 example.com fail2ban-client[15567]: 2018-01-01 11:26:17,416 fail2ban.se
rver         [15568]: INFO    Starting in daemon mode
Jan 01 11:26:18 example.com systemd[1]: Started Fail2Ban Service.

Backup your configuration, and try to remove completely Fail2ban and reinstall fresh Fail2ban with its new configurations. After that run properly, insert your custom rules / configuration.

**Comment by Vagrantin** [comment]
@sebres 
I'm using the ``iptables-allports`` ban action, my understanding it's using the value **default** from ``iptables-common.conf`` for the variable ``<name>`` instead of the the action name itself.

Probably a wrong configuration somewhere but i don't get where it could be...

ps: Setup has been done through Webmin.
Matth

**Comment by sebres** [comment]
> `action = iptables-allports[name=apache-badbots]`

This is wrong a bit, better you should use internal interpolations, see in jail.conf for examples.
In your case use `banaction` instead `action`, and following would be enough in your jail.local:
```INI
# jail.local:
[apache-badbots]
banaction = iptables-allports
enabled = true
```

**Comment by Vagrantin** [comment]
Thanks didn't know that way to do it.
Basically I have everything in my jail.conf but i guess it's going to be an issue at the upgrade stage.

**Comment by sebres** [comment]
@shellshocker I've analysed this again, so I'm sure something (like iptables restart) has removed fail2ban chains/tables on your machine. 
Because `iptables -w -n -L INPUT | grep -q 'f2b-wp-auth[ \t]'` will return 1 only in this case (`f2b-wp-auth` is missing).

But it can be indeed a small bug by trying to restore of sane environment (via stop+start)...
So I fixed it in major branches (>= v.0.10) now, where fail2ban will bypass possible errors in stop, if start and check succeeded hereafter,  see 7516cd025d22dd82a700a2690455973bc33ca2aa.

Thus closed.
