### ISSUE TITLE
pull  #1925 completely screws up existing configs

### ISSUE THREAD

**Issue by VVelox** [fail2ban/fail2ban#2003]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

_Summary here_

#### Steps to reproduce

Attempt to get it working with PF from a previous version.

#### Expected behavior

It works.

#### Observed behavior

It no longer bothers to insert anything into PF. The pf action appears to have been broken between upgrades and there are no documentations any where about expected pf configuration or the like for the new config in this version.

A quick check shows the post update it now expects the table to be named f2b instead of fail2ban...

Renamed so those those bits in the config are now as below.

table <f2b>
block in quick inet from <f2b>

And pfctl -T show -t f2b shows nothing still.

Looking at bit more and it looks like wants stuff in the form of $basetablename-$jailname.

So to test it out, I added the table f2b-sshd and f2b-apache-auth, which gets this...

service pf reload                                                                                         [0]
Reloading pf rules.
pfctl: warning: namespace collision with <f2b-sshd> global table.

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:

echo "block quick proto tcp from <f2b-recidive> to any port {<port>}" | pfctl -a f2b/recidive -f-
2017-12-20 05:33:36,732 fail2ban.utils          [84614]: ERROR   80200c920 -- stderr: 'stdin:1: syntax error'
2017-12-20 05:33:36,732 fail2ban.utils          [84614]: ERROR   80200c920 -- stderr: 'pfctl: Syntax error in config file: pf rules not loaded'
2017-12-20 05:33:36,733 fail2ban.utils          [84614]: ERROR   80200c920 -- returned 1
2017-12-20 05:33:36,735 fail2ban.actions        [84614]: ERROR   Failed to start jail 'recidive' action 'pf': Error starting action Jail('recidive')/pf

**Comment by VVelox** [comment]
Just reference 1925 as that is in the pkg-message for the port about pf and what ever has changed with PF this version seems be more than a bit problematic.

**Comment by sebres** [comment]
I assume you've wrong configuration for some jails:
- rather you should specify `banaction = pf[actiontype=<allports>]` (for all-ports banning, as documented [here](https://github.com/sebres/fail2ban/blob/3c4910a3e219a7d77d8bb99b1987bc78e12898e3/config/action.d/pf.conf#L107))
- or you should specify value of port (for multiport banning)

Or just specify correct defaults for pf-action in your jail.local...
```INI
# jail.local:
[DEFAULT]
banaction = pf[actiontype=<multiport>]
banaction_allports = pf[actiontype=<allports>]
```

**Comment by VVelox** [comment]
action = pf

That is it for everything. Like I said, I am not using it.

**Comment by koeppea** [comment]
I've just tried if I experience the same issues on FreeBSD. Not really.
This is my stupid test config:
```
# cat config/jail.local 

[DEFAULT]
banaction = pf

[sshd]
enabled = true
port = 22,2222
# 
```

And this is what I did to see if it also screws up for me:
```
# kldload pf.ko
# pfctl -e
pf enabled
# 
# 
# ./bin/fail2ban-client -s /tmp/f2b.sock -c config/ -i start
Server ready
Fail2Ban v0.11.0.dev0 reads log file that contains password failure report
and bans the corresponding IP addresses using firewall rules.

fail2ban> status 
Status
|- Number of jail:	1
`- Jail list:	sshd
fail2ban> 
fail2ban> set sshd banip 1.2.3.4
1.2.3.4
fail2ban> set sshd banip 2001:db8::1
2001:db8::1
fail2ban> exit
# 
# 
# pfctl -a f2b/sshd -sr
block drop quick proto tcp from <f2b-sshd> to any port = ssh
block drop quick proto tcp from <f2b-sshd> to any port = 2222
# 
# pfctl -a f2b/sshd -t f2b-sshd -T show
   1.2.3.4
   2001:db8::1
# 
# 
```

So I have nothing special. I have no anchor pre-defined in the */etc/pf.conf*. I also use the standard *config/action.d/pf.conf*. 
However, one anchor for fail2ban would be sufficient rather than one anchor for each jail, so that one have the whole fail2ban ruleset on a glance.

**Comment by sebres** [comment]
You are right, but... both jails you've used having port, thus passed as multi port action.
I assume if you'll try this for all ports jails like pam-generic, it will faill with `action=pf`, because of default multi port config, that will substitute into `... {}`.
Early because of missing braces the usage of pf, without any parameter was all ports compatible, but vice versa not for jails with multiple ports specified, even because of missing braces.

**Comment by VVelox** [comment]
Howdy!

The issue is basically nothing about this update is backwards compatible.

I was wrong about pull #1925 breaking it, my apologies.

Basically it boils down the the braces v. no braces issues being irrelevant and the move from using a table to using anchors, except to be thrown through a loop when you first start messing with them as they are a bit esoteric.

But simply but you need to put this in your pf.conf...

```
anchor f2b {
    anchor sshd
    anchor dovecot
}
```

Adjust the anchors inside to match what ever jails you have configured... adding more or less etc as needed.

Then just up date your pf[actiontype=<allports>] or the like.

You can go ahead and remove table stuff from pf.conf.

Sorry I've not had a chance to sit down and kick out more documentation or anything yet. Been distracted working on some LibreNMS.

**Comment by jrronimo** [comment]
Gonna sound like a giant noob here, so sorry in advance. I'd like to relate my experience with this update, though.

I noticed recently that my fail2ban install, which has been running for several months, has broken. I didn't really understand why it had broken, so I ended up wiped my config files and re-installing fail2ban from ports. Even trying to reconfigure fail2ban has been a challenge. I previously had fail2ban set to use the aggressive filter (which now seems to be part of the regular sshd filter, rather than a separate sshd-aggressive filter), and I had the recidive filter set up. The idea was "if you've been banned from SSH connections to my server X times before, now you are permabanned."

Most articles online discussing configuration of fail2ban with pf and FreeBSD mention that it's "fail2ban", so I had "table <fail2ban persist>" in my pf.conf, and later "block in quick on em0 from <fail2ban> to any" in my pf.conf.

Normally I just have in my jail.local
`[DEFAULT]
banaction = pf

[sshd]
enabled = true`

Did I miss some notification about massive changes to fail2ban and the config files? It's really confusing how to set it up correctly now. I'm not sure how to check what addresses are being banned anymore (previously "pfctl -t fail2ban -T show" was sufficient. Now I need... something like "pfctl -t f2b-sshd -T show"? But that's not working..."Table does not exist.")


It seems like there were big changes to the way fail2ban works with pf in ways that might really break existing installs. The comments in the /usr/local/etc/fail2ban/action.d/pf.conf help some, but it's still not entirely clear to me what's going on.

Thanks for your time.

**Comment by sebres** [comment]
@jrronimo fail2ban version (now and before)?
Looks like #1924.

**Comment by jrronimo** [comment]
@sebres Version now is v0.10.1. I don't know what version it was before, I'm sorry. The system is FreeBSD 11.1 with pf. I'm guessing fail2ban broke back in October when 0.10 was released.

If I run `pfctl -sr -a f2b/sshd -t f2b-sshd -T show`, I'm told `block drop quick proto tcp from <f2b-sshd> to any`, with some IPs listed. Those IPs don't appear in /var/log/auth.log, so I guess it's working...?

This update really required me to re-work my config files, both my /etc/pf.conf as well as my .local files for fail2ban. Quite a bit changed from the version I had running before. I'm sure other people are much more attentive to their logs than I am, though. :)

Sorry to bother, but thanks for checking.
