### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by WagnerGMD** [fail2ban/fail2ban#2021]
```
fail2ban-client stop;
fail2ban-client start;
```
Hello,

in fact something strange will happen right after these commands.
The list of IP banned was erased (in totally) and I will assume that's probably true for each jails.
Then could you explain me why Fail2Ban_v0.11 (I'm under Debian 9 aka Stretch x64) doesn't keep (neither restore) the list ?

Did you forgot to include another dependency on [this page](https://github.com/fail2ban/fail2ban/blob/0.11/README.md) ? This list of dependency is really complete ? What about the SQLite ?
Can we trust this part in the aim to install Fail2Ban ? Nothing is missing ? I'm wonder perhaps my installation of Fail2Ban isn't complete ?

`fail2ban-client reload;`
What's the aim of this command ? Because no I didn't find the information. And the latest time I had check, it didn't work (not as excepted).

Kind regards.

**Comment by sebres** [comment]
> Did you forgot to include another dependency on this page ?  This list of dependency is really complete ? 

This "dependencies" are minimum requirements for fail2ban.
Fail2ban runs also without sqlite-configured (even with restrictions like persistent storage).
But you don't need to install sqlite3 python-module. According to my info, it is included in the standard library since python v.2.5.

Possibly you overlooked another point there:
> It is possible that Fail2ban is already packaged for your distribution. In this case, you should use it instead.

This meant that if you are not familiar, possibly the best would be to use distributed package (also if it a bit obsolete, but stable and prepared for you from your maintainers).
Also note that 0.11 was still never released (this is development nightly edition).
Of course we're interested to fix all bugs you could find there, but you've provided no info about it.

Although you've disregarded the issue template (e. g. log-excerpt, etc.), but... back to the issue:
The `man fail2ban-client` is your friend:
 - `start`
    starts the server and the jails
- `stop`
    stops all jails and terminate the server
-  `reload [--restart] [--unban] [--all]`
    reloads  the  configuration without restarting of the server, the option '--restart' activates completely restarting of affected jails, thereby can unban IP addresses (if option '--unban' specified)

And yes, if you've proper configured your fail2ban-installation, the bans for IP's should be restored after `stop/start` (BTW, we've also `restart` command that does the same), but:
- only if sqlite-database proper configured for fail2ban (e. g. the directory path exists, and fail2ban can write there);
- only active bans (`now < timeOfBan + banTime`) ;

> `reload`... And the latest time I had check, it didn't work (not as excepted).

Can you please be a bit precise - what exactly does not work or expected.
It is a matter of development edition, thus be sure you use the latest version before you post an issue,

Thus closed as answered as long as no further info provided.

**Comment by sebres** [comment]
Found one case where similar situation (with no bans restored) can occur: by the first start of fail2ban 0.11 directly after upgrade of DB from version <= 0.10, the restoring of current ban can sometimes find no tickets (with some versions of 0.11).

Fixed in #2022 now.

**Comment by WagnerGMD** [comment]
```
 ## A little resume with just the last lines :
changing mode of /usr/local/bin/fail2ban-regex to 755
changing mode of /usr/local/bin/fail2ban-server to 755

Please do not forget to update your configuration files.
They are in "/etc/fail2ban/".

You can also install systemd service-unit file from "build/fail2ban.service"
resp. corresponding init script from "files/*-initd".
```
In fact, my plan at the origin was to provide more informations later. Because these last days, I was a little busy to reinstall Fail2Ban_v0.11. I wanted to be sure too and I'm sorry but you didn't correct this trouble :
```
fail2ban-client status
## Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running?
fail2ban-client start
## There is no directory /var/run/fail2ban to contain the socket file /var/run/fail2ban/fail2ban.sock.
fail2ban-client restart
##  Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running?
##  There is no directory /var/run/fail2ban to contain the socket file /var/run/fail2ban/fail2ban.sock.
```
[Which was reported there](https://github.com/fail2ban/fail2ban/issues/1890) by me a few months ago. And today, yes it has happened again (right after one server reboot).
After this command :
`python3.6 setup.py install;`
Do we have to create a service ? You didn't mentioned it on the page [readme.](https://github.com/fail2ban/fail2ban/blob/0.11/README.md)
Unless the solution is again : `mkdir /var/run/fail2ban` ?

And now I can give another example (related to **fail2ban-client reload** or **fail2ban-client reload --all**) :
```
NOK: ('Cannot change database when there are jails present',)
Cannot change database when there are jails present
```
From my point of view, the **reload** could be compare to **restart**. That's why I didn't except this result.
Could you explain me why I got this message ? But you had already answer (just need to be complete such as **fail2ban-client reload --restart**)

I wasn't aware about the command : **fail2ban-client restart;** When did you add it ?
In fact, the first time Fail2Ban_v0.11 was installed a few months ago. Unless I miss it ?

Sorry but I don't remember. But no you're wrong because I'm aware about the both (**man** and **help**). But that's true sometimes you won't find there any explications.

And no you're wrong too because I'm little familiar with Debian (several years). Despite my big respect to Debian, sometimes I just want to try a new program (instead to wait several years for the next Debian).

**Comment by sebres** [comment]
> Do we have to create a service ?

If you installed common version of fail2ban, then - Yes, see the [README](https://github.com/fail2ban/fail2ban/blob/0.11/README.md)-file:
```
Please note that the system init/service script is not automatically installed. ...
```
Any other errors looks like just because the fail2ban does not running (wrong configured).
So in your case it expected `/var/run/fail2ban/fail2ban.sock`, but it is inaccessible for some reasons (missing sudo?, etc).

> From my point of view, the reload could be compare to restart.

Not as I already said, `reload` does reload of configuration only. But `restart` is an alias for `stop/start`. So fail2ban process will be restarted.
Unless you call it with the jail name, in which case only jail configuration (failregex, etc) will be reloaded (`reload $jail`) or jail will be completely restarted (`restart $jail`).

**Comment by WagnerGMD** [comment]
Usually the service is supposed to be create by the installer. Sometimes, you just need to start the program and the service will be create at the same moment.
It's very strange, no ? Because from my point of view, no it doesn't explain why this folder doesn't exist anymore (just after one reboot) ? For that reason it was remove ? Because no I don't have a clue (no it can't be me).

Now I understand but for me the help could be improve (just clarify)
**PS :** To be clear, no I can't be sudo.
