### ISSUE TITLE
Higher cpu-usage from 0.9 to 0.10

### ISSUE THREAD

**Issue by Glandos** [fail2ban/fail2ban#2032]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.2-1
- OS, including release name/version: Debian GNU/Linux testing (buster)
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Fail2ban 0.10 hits Debian/testing yesterday, so I migrated.
However, I have the following monitoring report:
![](https://screenshotscdn.firefoxusercontent.com/images/32ff3545-1cb2-416b-ac2e-d80efdd51dfd.png)

As you can see, the upgrade happened right after 21:00.
The user CPU usage doubled. The system CPU usage was multiplied by 3 to 10. What happened exactly?
I'm not angry about it, but this is really different from the performance improvements advertised in the changelog…

#### Any customizations done to /etc/fail2ban/ configuration
```
> cat dovecot.local nsd.local postfix.local sshd.local

[dovecot]
enabled = true
backend = systemd
[nsd]
#enabled = true
#backend = systemd
[postfix]
enabled = true
backend = systemd

[postfix-sasl]
enabled = true
#backend = systemd
[sshd]
maxretry = 5
bantime = 86400

[sshd-ddos]
enable = true

```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
1. some sleep intervals (in "polling" mechanisms) are shorter now (dynamic range from 0.02 up to 2 seconds, compared with previously exactly 1 second). This means fail2ban reacts with lower latency, but may cause higher CPU usage. But normally it should be not so "large".
2. in order to facilitate the fix resp. analyze, please provide more info, e. g. how many active jails do you have and which backend (polling, pyinotify, systemd) do you use for this jails.

**Comment by Glandos** [comment]
Thanks for this fast answer.
I've updated the initial report with my local files. All other files are unchanged from Debian package.

**Comment by Glandos** [comment]
The default backend is pyinotify. That was a missing information

**Comment by sebres** [comment]
Just to be sure it is affected by the sleep-intervals (as I said), can you please test it with following temporary changes in fail2ban/server/utils.py:
```diff
--- a/fail2ban/server/utils.py
+++ b/fail2ban/server/utils.py
@@ -58,7 +58,7 @@ class Utils():
 	"""
 
 	DEFAULT_SLEEP_TIME = 2
-	DEFAULT_SLEEP_INTERVAL = 0.2
+	DEFAULT_SLEEP_INTERVAL = 1
 	DEFAULT_SHORT_INTERVAL = 0.001
 	DEFAULT_SHORTEST_INTERVAL = DEFAULT_SHORT_INTERVAL / 100
 ```
Unfortunately this can't be currently changed via configuration (so if you can, please try to change the code)...

Or/and temporary disable pyinotify jails (I think both sshd) and take a look the cpu-usage.

**Comment by Glandos** [comment]
I confirm. Switching from 0.2 to 1 gives me the old figures for CPU usage.
Is there any way to configure it, except from modifying the source?

**Comment by Glandos** [comment]
By the way, a long time ago, I started some work to remove those regular sleeps that are CPU-killers: https://github.com/Glandos/fail2ban/commits/idle-action-thread-0.9

This code is completely obsolete, but the question remains: why use regular wake up when you can sleep longer and avoid going from kernel to userspace? Maybe the answer should be for another thread, though.

**Comment by sebres** [comment]
> Is there any way to configure it, except from modifying the source?

Currently not, but:
- I'll definitive provide the way to configure latency/responsiveness of fail2ban (still before next release).
- this should be fixed regardless the option, because normally this value is a minimum boundary and it grows up to DEFAULT_SLEEP_TIME (2 seconds) in conditional wait operations, and wait using longest sleep until the condition is fulfilled.
So I assume somewhat uses shorter timeout in the cycle.
