### ISSUE TITLE
Setting up fail2ban on macOS High Sierra

### ISSUE THREAD

**Issue by COOLIRON2311** [fail2ban/fail2ban#2049]
So, I installed fail2ban on may Mac with Homebrew and could not find how to properly set it up to protect ssh. All the articles were either outdated (ipfw was removed from macOS)  or made for other operating systems.

macOS High Sierra 10.13.3
Homebrew 1.5.4
fail2ban 0.10.2

**Comment by sebres** [comment]
Note that this is a developer repository, so issues like how-to's, etc are not really welcome.
We don't know which firewall-system do you use, resp. which is installed on your system that would be supported from fail2ban (especially with MacOS because for example I myself don't have apple hardware to test it with this OS, and the great company policy does not allow to install it as VM on non-apple hardware).

But I assume [PF](https://github.com/fail2ban/fail2ban/blob/0.10/config/action.d/pf.conf) could be your friend.

1. Do you obtained fail2ban from your MacOS distribution? If yes, fail2ban may be already correct pre-configured for you.
In this case just try to enable jail and test it:
```INI
# jail.local
[sshd]
enabled = true
```
2. Which default values do you see there?
```
fail2ban-client -d | grep action
```
3. If it does not work (resp. you've installed fail2ban from github), try to change default action to PF:
```INI
# jail.local
[DEFAULT]
banaction = pf[actiontype=<multiport>]
banaction_allports = pf[actiontype=<allports>]
```

@fail2ban/maintainers, @fail2ban/contributors Does anyone know the proper configuration for macOS High Sierra 10.13.3?

**Comment by sereose** [comment]
Hi having issues on OSX . 10.13  to run the service 
orch:fail2ban root# fail2ban-client -d | grep action
2018-04-25 15:58:19,860 fail2ban                [58965]: ERROR   Failed during configuration: Bad value substitution:
	section: [sshd]
	option : logpath
	key    : sshd_log
	rawval : 

2018-04-25 15:58:19,860 fail2ban                [58965]: ERROR   Init of command line failed
