### ISSUE TITLE
Q: retrieve failregex value of another jail ?

### ISSUE THREAD

**Issue by benrubson** [fail2ban/fail2ban#2052]
Hi,

Can we retrieve `failregex` value from a specific jail ?

Let's imagine I want to configure an `apache` jail, with existing/stock `failregex` from both `apache-auth` and `apache-overflows`. How could I do ?

Workaround I've found is to only activate `apache-auth`, and do the following in its jail configuration :
```
failregex = %(known/failregex)s
            ...manually copy/paste rules from apache-overflows...
```
which is not really convenient.

Goal is to have only one jail per service / port / series of ports.

Thank you 👍 

Ben

**Comment by sebres** [comment]
Admittedly since 0.10 you could use section-related interpolations like `%(section/failregex)s`, BUT if this second jail does not allowed in jail.local:
- you'll not be able to obtain its failregex (because disabled jail does not load filter, so no failregex at all);
- another issue is - this failregex belong to the filter so not directly in the jail after load jail-config, so JailReader should be rewritten to do it properly (what would be not really easy).

Another way would be to allow specify several filters per jail, but this is also not so easy to implement (since filter contains not the failregex's, but also date-patterns, journal-units, etc).

I see currently no way to do it as you expect.
Now you should just enable both jails.

I've a branch (still in development), where the jails are containers only (not the threads), and the workers are backend-, jail-, filter-independent. So if this new feature get published once, then it will not matter how many jails you will configure for single service, it will be anyway done within exact one thread (the thread-pool is separately configured and whole configuration independent).

**Comment by benrubson** [comment]
Thank you very much Sergey for your detailed explanation 👍 
For the moment I'll then enable all required jails, or use the workaround in my first post for jails with a low number of rules (as `sshd-ddos` (10.1), `apache-overflows`... which have only one rule).
And I'll keep an eye on future improvements.
Thx 👍

**Comment by sebres** [comment]
You could rewrite all apache filters to single one, with parameters like `mode` (similar how it was implemented in sshd-, postfix- or other filters).

Feel free to open a PR if you have such filter ready.

**Comment by benrubson** [comment]
That would be a nice improvement yes.
No such work ready on my side for the moment.
