### ISSUE TITLE
'sshd' jail logpath and backend 

### ISSUE THREAD

**Issue by cnrat** [fail2ban/fail2ban#2068]
Finally, finds out what happened to #2065 

I have 6 hosts with fail2ban 0.10.2 using exactly the same configuration. But one of them has an issue mentioned above.

I was really confused unit I noticed the other 5 host's 'sshd' jail never ban any IP.

I checked one of the 5 with `fail2ban-client get sshd logpath` shows

```
Current monitored log file(s):
`- /var/log/auth.log
```

That is obviously a mistake in CentOS, the correct path is `/var/log/secure`.

There is a commit(eba68a8f377795ca151d7ebd9199107a538cbb7a) 4 month ago that modified `fail2ban/config/paths-common.conf`
```
syslog_authpriv = /var/log/auth.log
```

Why #2065 ?
Because the only one has an issue is completely new installed, without an empty file `/var/log/auth.log`, and fail2ban use an backend 'systemd' as default.

So the only question now is why '/var/log/auth.log' in CentOS?

**Comment by sebres** [comment]
> There is a commit(eba68a8) 4 month ago that modified

This commit changes nothing. It is just normalization of config files.
In previous variant substutition of `sshd_log = %(syslog_authpriv)s` will fail, because previously it was not specified in config/paths-common.conf.

The issue may be missing file `paths-centos.conf`...
What do you see as "Loading files" by verbose dump:
```bash
?sudo? fail2ban-client -vvd 2>&1 | grep '/paths'
```

> Because the only one has an issue is completely new installed, without an empty file /var/log/auth.log, and fail2ban use an backend 'systemd' as default.

If fail2ban uses systemd backend, there is no matter which logpath specified.

> So the only question now is why '/var/log/auth.log' in CentOS?

From where you've obtained your fail2ban package?

**Comment by cnrat** [comment]
> What do you see as "Loading files" by verbose dump...

```
 2018-03-07 07:48:34,042 7FBADD4E2740 INFO    Loading files: ['/etc/fail2ban/paths-debian.conf']
 2018-03-07 07:48:34,043 7FBADD4E2740 INFO    Loading files: ['/etc/fail2ban/paths-common.conf']
 2018-03-07 07:48:34,044 7FBADD4E2740 INFO    Loading files: ['/etc/fail2ban/paths-overrides.local']
 2018-03-07 07:48:34,046 7FBADD4E2740 INFO    Loading files: ['/etc/fail2ban/paths-common.conf', '/etc/fail2ban/paths-overrides.local', '/etc/fail2ban/paths-debian.conf', '/etc/fail2ban/paths-overrides.local', '/etc/fail2ban/jail.conf', '/etc/fail2ban/jail.local', '/etc/fail2ban/jail.d/honeypot.local', '/etc/fail2ban/jail.d/nginx-stream-proxy.local', '/etc/fail2ban/jail.d/sshd.local']
```

The commit (eba68a8f377795ca151d7ebd9199107a538cbb7a) seems moved `syslog_authpriv = /var/log/auth.log` from `paths-debian.conf` to `paths-common.conf`.

Is this correct? In my opinion that should be `paths-fedora.conf` in CentOS which are both from Radhat.

**Comment by sebres** [comment]
> The commit (eba68a8) seems moved syslog_authpriv ...

Yes but it should be overwritten within paths-distro.conf,  without this it fails on interpolate `%(syslog_authpriv)s`.

> In my opinion that should be paths-fedora.conf in CentOS which are both from Radhat.

Maybe... I'm not maintainer of this distributions.
The value of `before` should be changed in jail.conf...
https://github.com/fail2ban/fail2ban/blob/ffd6b9f6de3b94a255d145017ed6efb3a5c9e79c/config/jail.conf#L36

@fail2ban/maintainers How it currently implemented in the fail2ban packet for centos / RHEL, etc?

As long as it is not fixed there, you can easy fix it within your `jail.local`, for example:
```INI
[INCLUDES]
before = paths-fedora.conf
...
```

> The one with log path issue uses 'https://github.com/fail2ban/fail2ban/archive/0.10.2.tar.gz'.

The problem is - this is just a common installation (as is debian's-derivate compatible only), thus in case of install on other systems, you should re-configure it, using merge from the config-files of your origin packet.
We have nothing to do with packet for other system/distributions.
