### ISSUE TITLE
The sendername is deprecated?

### ISSUE THREAD

**Issue by Moskvichov** [fail2ban/fail2ban#2071]
In my jail.local, i tryed change the sendername:

[DEFAULT]
bantime = 3600
destemail = admin@mydomain.ru
sender = root@smb.mydomain.ru
action = %(action_mw)s
sendername = Fail2Ban.mydomain

[sshd]
enabled = true

In any case i received e-mail, where From field have Fail2Ban.

If i change the sendername  in sendmail-common.conf, all work very well.

**Comment by sebres** [comment]
> [DEFAULT]
> sendername = Fail2Ban.mydomain

I don't know paremeter `sendername` was ever translated from jail to the action... (Don't see also any reference in our jail.conf at all).

Here you see all parameter fail2ban will provide to the action (>= 0.9):
https://github.com/fail2ban/fail2ban/blob/7013729a1f86de4f38da5297cfb5eae2c4b4abf3/config/jail.conf#L167-L168

In order to provide it from jail.local you should extend the `action` like other parameters.
Since version 0.10 it can be easy done with:
```INI
action_mw = %(known/action_mw)s[sendername="Fail2Ban.mydomain"]
# or:
action = %(action_mw)s[sendername="Fail2Ban.mydomain"]
# or:
sendername = Fail2Ban.mydomain
action_mw = %(known/action_mw)s[sendername="%(sendername)s"]
```
Unfortunately it is impossible in older version 0.9.x (syntax with dual bracket `action[...][...]` is not allowed).
Thus for this older versions, you should overwrite `action_mw` in your jail.local completely.

**Comment by Moskvichov** [comment]
I tryed the

action = %(action_mw)s[sendername="Fail2Ban.mydomain"]
in jail.local

Same result. Field From is Fail2Ban 

My version is 9.7

**Comment by sebres** [comment]
Read this again:
> Unfortunately it is impossible in older version 0.9.x (syntax with dual bracket action[...][...] is not allowed).

The problem is substitution of `%(action_mw)s[sendername="Fail2Ban.mydomain"]` will result into:
`... sendmail-whois[parameters...][sendername="Fail2Ban.mydomain"]`
And this is not valid syntax for 0.9.

This:
> Thus for this older versions, you should overwrite action_mw in your jail.local completely.

means you should append sendername into you local copy of action_mw:
```INI
action_mw = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"] 
            %(mta)s-whois[name=%(__name__)s, sender="%(sender)s", sendername="%(sendername)s", dest="%(destemail)s", protocol="%(protocol)s", chain="%(chain)s"]
```

**Comment by vmpr** [comment]
Hi, 

I have the same problem, if I  set `sendername = Fail2ban-Servername` in `jail.local` it is not used in the action.
I don't want to change the `/etc/fail2ban/action.d/sendmail-common.conf`. my version is: `Fail2Ban v1.0.2`

Can you implement a way to overwrite it with the `jail.local` file?

cheers Ringo

**Comment by sebres** [comment]
> Can you implement a way to overwrite it with the jail.local file?

Here - https://github.com/fail2ban/fail2ban/issues/2071#issuecomment-371776997 is an example how you can set it to the action in jail.local for jail or default.
