### ISSUE TITLE
Strange banning without reason

### ISSUE THREAD

**Issue by takenek** [fail2ban/fail2ban#2077]
Hello
I write my own filter he look like this:
`root@POCZTA:~# cat apache-rc-login.conf`
```INI
[Definition]
failregex = ^<HOST>.*GET.*(?i)admin.*
            ^<HOST>.*GET.*(?i)manager.*
            ^<HOST>.*GET.*(?i)setup.*
            ^<HOST>.*GET.*(?i)mysql.*
            ^<HOST>.*GET.*(?i)sqlweb.*
            ^<HOST>.*GET.*(?i)webdb.*
            ^<HOST>.*GET.*(?i)pma.*
            ^<HOST>.*GET.*(?i)vtigercrm.*
            ^<HOST>.*GET.*(?i)phpmyadmin*
            ^<HOST>.*GET.*(?i)phpMyAdmin*
            ^<HOST>.*GET.*(?i)PMA*
            ^<HOST>.*GET.*(?i)pma*
            ^<HOST>.*GET.*(?i)admin*
            ^<HOST>.*GET.*(?i)dbadmin*
            ^<HOST>.*GET.*(?i)sql*
            ^<HOST>.*GET.*(?i)mysql*
            ^<HOST>.*GET.*(?i)myadmin*
            ^<HOST>.*GET.*(?i)MyAdmin*
            ^<HOST>.*GET.*(?i)phpmyadmin2*
            ^<HOST>.*GET.*(?i)phpMyAdmin2*
            ^<HOST>.*GET.*(?i)phpMyAdmin-2*
            ^<HOST>.*GET.*(?i)php-my-admin*
            ^<HOST>.*GET.*(?i)sqlmanager*
            ^<HOST>.*GET.*(?i)mysqlmanager*
            ^<HOST>.*GET.*(?i)PMA2005*
            ^<HOST>.*GET.*(?i)pma2005*
            ^<HOST>.*GET.*(?i)phpmanager*
            ^<HOST>.*GET.*(?i)php-myadmin*
            ^<HOST>.*GET.*(?i)phpmy-admin*
            ^<HOST>.*GET.*(?i)webadmin*
            ^<HOST>.*GET.*(?i)sqlweb*
            ^<HOST>.*GET.*(?i)websql*
            ^<HOST>.*GET.*(?i)webdb*
            ^<HOST>.*GET.*(?i)mysqladmin*
            ^<HOST>.*GET.*(?i)mysql-admin*
            ^<HOST>.*GET.*(?i)w00tw00t*

ignoreregex =
```

I don`t know why he ban all the time because of:
```
root@POCZTA:~# fail2ban-regex /root/misio /root/apache-rc-login.conf

Running tests
=============

Use   failregex file : /root/apache-rc-login.conf
Use         log file : /root/misio


Results
=======

Failregex: 3 total
|-  #) [# of hits] regular expression
|  15) [3] ^<HOST>.*GET.*(?i)sql*
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [262] Day/MONTH/Year:Hour:Minute:Second
`-

Lines: 262 lines, 0 ignored, 3 matched, 259 missed
Missed line(s): too many to print.  Use --print-all-missed to print all 259 lines
```
The most funny there is no "sql" string in log file:
```
root@POCZTA:~# grep -i sql /root/misio
root@POCZTA:~#
```
I check this on few version of fail2ban and exacly same problem...
What is wrong? why he find something but it`s not in file?

/root/misio log file from Apache is here: http://www.wklej.org/hash/0ebc5a876e7/

Best Regards
TaKeN

**Comment by sebres** [comment]
1. You can use `--print-all-matched` to see which lines was found as failures.
2. Your guess is wrong, if you think `sql*` must match `sql` only, because it matches `sq`, `sql`, `sqll`, ... `sqlllll`, etc. The `*` quantifier applied to the last token (which is last character `l` in this expression).
3. BTW. All your regex's are very vulnerable at all (greedy catch-all, not end-anchored, etc.).

**Comment by sebres** [comment]
*Answered here, because I cannot answer you per mail (supposedly `554 5.7.1 Service unavailable; Client host [MY-IP] blocked using rbl.rbldns.ru`, but I don't know and no interested to clarify why it is blocked by such stupid RBL-lists like `rbldns.ru`. Checked via http://www.anti-abuse.org/ or https://rblwatcher.com/ - no one said I'm listed):*

Well,

as I already wrote `*` is a quantifier, so applied to the last token (which is `l` in this case).

Regex is even not glob, so if you said anything - it should be `.*` and not `*`.
How regex works exactly you can read in https://docs.python.org/2/library/re.html#regular-expression-syntax.

   `*`
    *Causes the resulting RE to match 0 or more repetitions of the preceding RE, as many repetitions as are possible. `ab*` will match `a`, `ab`, or `a` followed by any number of `b`s.*

BTW. But usage of `.*` (called greedy catch-all), as well as non-greedy variant like `.*?` in fail2ban regex
in the wild may be very vulnerable (give an intruder more chances to skirt around the failure, resp. even to cause a ban for some other IP-address, if he can do an inject on username, referrer, user-agent, etc).

So instead of `.*` normally more precise RE-parts are expected. And anchors (`^`,`$`) help also.

For example to bypass all before word `failed` in text like
  `test "something in quotes" 123 failed`
instead of catch-all:
  `.* failed`
better would be to use something more precise like:
  `[^"]* "[^"]*" \d+ failed`.

Just I can not teach you how to write good RE's in few hours (or even days), because it is simply impossible.
One needs several years to have RE's writing down to fine art :)

>
> Hey Sergey,
>
> Can You tell me what is wrong with this because looks like i don`t understand logic of this regexp.
>
> Why „sql*" match „sq" ?
>
> I understand why match sqll or sqlllllllll or sqlsomething because * is anything but why „sql*" match „sq"?
>
>  
>
> Best Regards
>
> Marek

**Comment by takenek** [comment]
Thanks for explanation.

Best Regards!
