### ISSUE TITLE
Jail reload without log rescan

### ISSUE THREAD

**Issue by gzzz** [fail2ban/fail2ban#2091]
### Environment:
- Fail2Ban v0.9.3
- Ubuntu 16.04.4 LTS
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:
I've made some modifications in jail config and execute `fail2ban-client reload my-jail`.
Each time i do jail reload i've got 100% CPU utilization for a few minutes, and received duplicates of all ban report emails.

How I can just reload jail configuration to apply it's for new requests?

#### Steps to reproduce

`fail2ban-client reload my-jail`

#### Expected behavior
Configuration reload without log rescan.

#### Observed behavior
Log rescan, resending notifications.

**Comment by sebres** [comment]
> how I can just reload jail configuration

Shortly: for 0.9.3 - no way (only restart of the jail implement).
But normally (if database configured) it should not do full rescan of the log (starts from the last saved position).

In newer version of fail2ban (since 0.10) you could reload configuration only (fail2ban differentiates between `reload` and `restart`).

> received duplicates of all ban report emails.

Also this is "reimplemented" in newer version (>= 0.10) - since parameter `norestored` introduced (and all mail-actions got `norestored = 1`), see RFE #1852.

Back to 0.9 - the active bans are known (tickets saved in the database), so it will be restored after restart - and all actions (mail-actions inclusive) will be repeated after restart.

So only one option currently - update to newer version.

**Comment by gzzz** [comment]
I got it.
Thank you.
