### ISSUE TITLE
Not banning OUTPUT

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#2107]
After a special incident (banned our CDN's connecting IP) I was tcpdump-ing: 
when Fail2ban catches an attacker our server is still able to **send** packets to the attacker. Am I wrong?

**Comment by sebres** [comment]
It's depending on the selected ban-action (and/or parameters).

For example if you'll drop or reject only on **new** inbound connections, then yes - after ban your existing connection still remain and server can send the packets to the intruder IP.
Additionally note that the packets, the server sends, can be rejected in the firewall.

Which action and parameters do you use there?

**Comment by szepeviktor** [comment]
AFAIK the default iptables-multiport action does not touch the OUTPUT chain thus the server can send pockets to the already banned intruder (this question is not related to stat NEW!)

**Comment by sebres** [comment]
I think I wrote "For example" :)

**Comment by szepeviktor** [comment]
Okay

**Comment by szepeviktor** [comment]
Do Fail2ban have a setting that also bans by destination in the OUTPUT chain, not only by source in the INPUT chain?

**Comment by sebres** [comment]
Well, it is not so easy to use single rule for both chains because the intruder-IP in chain INPUT is source and in OUTPUT is distance. 
But you can write a custom action creating two rules (for both chain).

Although I don't really understand the need to block the send immediatelly...
But I think it would be not the proper way via iptables OUTPUT chain, because you'll unnecessary slowing down your firewall output queues (anyway the future connections from intruder are not accepted anymore).
So I'll suggest just to drop the existing connections of the intruder after ban, for example using `tcpkill` or [cutter](http://www.digitage.co.uk/digitage/software/linux-security/cutter), e. g. something like:
```INI
actionban = %(known/actionban)s
            cutter <ip> <port> || echo not connected
```
But if I'm correct, for cutter you should have a module 'conntrack' loaded in the kernel.
So you could just create two FORWARD rules (in both directions to send FIN+RST) with `-j REJECT -reject-with tcp-reset` and delete it hereafter.
But there are also a couple of issues with this approach, please read [How to kill a TCP/IP connection using "IPTables REJECT with RESET"](http://www.digitage.co.uk/digitage/software/linux-security/cutter) for more info.

**Comment by szepeviktor** [comment]
> anyway the future connections from intruder are not accepted anymore

My main point is not about the intruder's traffic but a - let's say - accidental outbound traffic **towards** the intruder.

So I should invent a solution myself to clone the current INPUT chain + `f2b-*` chains to OUTPUT?

**Comment by sebres** [comment]
> So I should invent a solution myself to clone the current INPUT chain + f2b-* chains to OUTPUT?

As already said, it's at all not recommended to do, besides it's not too easy to drop the existing connection (or rather to ban the outgoing packets). Note also the service may send the data before you be able to block it via firewall.
Normally, your service should close the connect after failed authorization, insufficient rights (and similar).
So again, can you please explain what exactly you want to ban regarding the outgoing traffic? Which service it is?

**Comment by szepeviktor** [comment]
> So again, can you please explain what exactly you want to ban regarding the outgoing traffic?

Maybe I forgot to say "later":

1. intruder attacks
1. Fail2ban bans
1. all related TCP connection close
1. ~~~ a lot of time passes ~~~
1. then accidentally my server tries to connect to the intruder's host **<-- this is the topic of this issue**

**Comment by szepeviktor** [comment]
Thanks for cutter! I was looking for a tool like this.

**Comment by sebres** [comment]
> then accidentally my server tries to connect to the intruder's host

Hmm... what it is exactly?

**Comment by szepeviktor** [comment]
I do not know, it is a theoretical question to be on the safe side.

**Comment by sebres** [comment]
I think, at the moment only non-secure FTP can be a candidate for such things. 
But I doubt the passive-FTPs as well as some other services will do this after an unauthorized connect.

And yes, in the case you've no control about the outbound connection from your server, you should write a custom action for such purposes (which will ban the packets for OUTPUT chain also). 
If you've it ready, you could provide a PR (for the case if someone will need it)...

So I'll close this, as long as it remains a "theoretical question". 
Please reopen if found.

**Comment by szepeviktor** [comment]
I've found `conntrack -D -s 1.2.3.4`
https://manpages.debian.org/stretch/conntrack/conntrack.8.en.html

**Comment by sebres** [comment]
You should be very careful with connection tracking (resp. enabling of the kernel conntrack module).
It could sometimes cause a slowing down of your network throughput.
I mean - better don't do it just for the case of "theoretical question" (only if really needed).

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
The modern solution is

```ini
[Definition]

actionban = <iptables> -I f2b-<name> 1 -s <ip> -j <blocktype>
            ss --no-header --numeric --kill dst <ip> >/dev/null
```
