### ISSUE TITLE
Is Python 3 better than 2 for F2B?

### ISSUE THREAD

**Issue by PepeLopez** [fail2ban/fail2ban#2111]
I'm curious if an update to Python 3 would improve the performance of fail2ban!?

When having a large ddos attack on my server, fail2ban 0.10.0 is still struggling to keep running in sync, sometimes it's running 15-30s behind - and that with 16 cores and 192gb ram -_-

Any further performance improvement hints are desired! :)

**Comment by sebres** [comment]
Shortly - would not.

For example if you look the performance of the test-cases (with `--fast` option), you'll see some things are faster in python2.x and another in python3.x. Even python3.x versions need more time for all the test cases.
Let alone the performance of python self is secondary, because the execution of action (e. g. iptables) plays also primary role.

So what you can do to improve performance:
- optimize regex's (prefregex, failregex and ignoreregex);
- specify precise datepattern (corresponding the log-date on your system);
- split the log-files if possible (failures into separate log-file/journal) to avoid burden with parasitic log-lines;
- try to find more efficient ban-action (working on your system);

So what we can do too:
- optimize regex's (and we do it every so often);
- rewrite communication between worker threads, e. g. event-driven instead of polling/select/etc (WiP);
- rewrite ban-action to use native libraries instead of call of shell-scripts;
