### ISSUE TITLE
Wish: Make setting of the match option in iptables possible (iptables -m <string>)

### ISSUE THREAD

**Issue by ulicodex** [fail2ban/fail2ban#2160]
### The wish:

I'd like to drop packets that access a specific URL for the nth time. As far as I can see this is possible with with the match option (-m <string>) in iptables. I'd like to set this in the jail.local. Wouldn't it be a nobrainer oneline for you?

**Comment by sebres** [comment]
Our include `iptables-common` have already an option that you could use to extend iptables-call....
https://github.com/fail2ban/fail2ban/blob/d03872fbbf1b78d6047f4bc1876e2acc3293873d/config/action.d/iptables-common.conf#L70-L71

So just specify your action as `iptables-multiport[lockingopt="-w -m ..."]` or if it should affect only one call of iptables (e. g. by create chain) simply create a new derivation action (with include of expected iptables-action), where you can overwrite some lines (e. g. define a new `actionstart`), so that will do what you need.

To show the end result, what the action doing, you can create and enable one jail for it, and dump arguments using:
```
# pretty dump for fail2ban >= v.0.10.x
fail2ban-client --dp
# fail2ban >= 0.9.x
fail2ban-client -d
```
