### ISSUE TITLE
Hardening systemd service

### ISSUE THREAD

**Issue by francoism90** [fail2ban/fail2ban#2162]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): fail2ban 0.10.3.1-1
- OS, including release name/version: Arch Linux (rolling)
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

If I understand correctly fail2ban needs to run as `root`.
To 'protect' the system and it's files, I would like to ask if hardening the systemd service would be a good option by default (although some distro's may follow different paths/setup).

#### Steps to reproduce

As you can [read here](https://wiki.archlinux.org/index.php/Fail2ban#Service_hardening) I have added  systemd options to protect the (file)system and so far it doesn't seem to cause issues with fail2ban.

#### Expected behavior

Secure service by default (if possible).

#### Observed behavior

fail2ban runs as root unprotected

#### Any additional information

N/A

#### Any customizations done to /etc/fail2ban/ configuration

```
$ cat /etc/systemd/system/fail2ban.service.d/override.conf
[Service]
PrivateDevices=yes
PrivateTmp=yes
ProtectHome=read-only
ProtectSystem=strict
NoNewPrivileges=yes
ReadWritePaths=-/var/run/fail2ban
ReadWritePaths=-/var/lib/fail2ban
ReadWritePaths=-/var/log/fail2ban
ReadWritePaths=-/var/spool/postfix/maildrop
CapabilityBoundingSet=CAP_AUDIT_READ CAP_DAC_READ_SEARCH CAP_NET_ADMIN CAP_NET_RAW
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
> if hardening the systemd service would be a good option by default

Well, theoretically it's wrong to protect fail2ban service per default the way like this. 
Just because you don't really know which actions the user has configured (or will do later) and where fail2ban (via this actions) could write.

Correct is:
- fail2ban runs as root (per default) to have access to all the log-files (or systemd-journals) observing and to execute root-related actions (firewall subsystem like iptables, etc);
- if you'll give some technical user the corresponding privileges, you could run fail2ban as this technical user (without root to be);
- but some new action added by user (doing something other. e. g. write nginx-config include and reload nginx configuration hereafter) may expect to extend this rights for this technical fail2ban user (in case of nginx - write right for this nginx-config include and/or corresponding rights to produce nginx reload-signal).

So as we cannot preliminary know how the user will configure its own fail2ban instance, we cannot use the hardening the systemd-service per default.

This could be a nice enhancements (e. g. for our [wiki](https://github.com/fail2ban/fail2ban/wiki) or some install/configuration script, something like user-interactive `fail2ban-client configure-service`).

If you could do it for one or other, welcome ... it's appreciated.

**Comment by CameronNemo** [comment]
I use an AppArmor profile on my system to achieve similar goals as `ProtectSystem`. I put it in complain-only mode, however.
