### ISSUE TITLE
Available RPM packages

### ISSUE THREAD

**Issue by marciofoz** [fail2ban/fail2ban#2196]
Hello ! 
I have a small question: will be the version 0.10 or 0.11 available in rpm packages for use with CentOS 7 ? Today only 0.9.7 is available.
Thank you.

**Comment by sebres** [comment]
@fail2ban/maintainers ...ping...

**Comment by marciofoz** [comment]
Nothing yet ...?

**Comment by plaimbock** [comment]
@marciofoz EPEL has fail2ban 0.9.7 for CentOS7. If you want a fail2ban 0.10.3.1 RPM for CentOS 7 then you could download the latest fail2ban SRPM for Fedora from https://koji.fedoraproject.org then edit fail2ban.spec to use python (aka python 2.x.x) instead of python3 and rebuild on CentOS 7.
https://kojipkgs.fedoraproject.org//packages/fail2ban/0.10.3.1/3.fc29/src/fail2ban-0.10.3.1-3.fc29.src.rpm

**Comment by marciofoz** [comment]
@plaimbock.  Thank you by the explanations.

The main idea is use the .10 or .11 directly from packages because:

   -receive future package updates;
   -we use IPv6;
   -f2b setup/configuration will be delivered for a lot of servers by puppet/foreman, then we can adjust the classes according to the operating system.

So a manual deploy of packages will not meet these points above (at least easily);

Thank you again.
