### ISSUE TITLE
Fail to match systemd log, but matches text file

### ISSUE THREAD

**Issue by neilromig** [fail2ban/fail2ban#2203]
I am running fail2ban v0.10.3.fix1 on an Arch Linux server, installed with pacman using the standard package.
I am having trouble with my "courier-smtp" jail not always matching against the systemd logs. My "courier-imap" jail is configured in the same way and is working OK. You can see my startup logs in issue #2202 .

If I do the following:

`journalctl -S "2018-08-01 00:00:00" > jc.out`
`fail2ban-regex jc.out '^.*: error,relay=<HOST>,msg="502 ESMTP command error",cmd:.*'`

I will get the expected number of matches, but meantime my running fail2ban server has not found any matches for this regex, but has matched against another regex in the same jail. I'm puzzled.

Portion of systemd log that failed to match:
```
Aug 16 03:42:59 pinnacle courieresmtpd[18089]: error,relay=::ffff:104.148.126.197,msg="502 ESMTP command error",cmd: DATA
Aug 16 03:42:59 pinnacle courieresmtpd[18089]: error,relay=::ffff:104.148.126.197,from=<bounce-2900-13580120-3104-248@tajqne.com>,to=<xxx@xxx.co.uk>: 550 User <xxx@xxx.co.uk> unknown
Aug 16 03:42:51 pinnacle courieresmtpd[18089]: started,ip=[::ffff:104.148.126.197]
```

Portion of systemd log that matched successfully:
```
Aug 16 07:38:26 pinnacle courieresmtpd[20897]: error,relay=::ffff:5.188.231.232,from=<info@educationplusnews.com>,to=<a6c7c1o5u6n8t5s7@xxx.co.uk>: 550 User <a6c7c1o5u6n8t5s7@xxx.co.uk> unknown
Aug 16 07:38:18 pinnacle courieresmtpd[20897]: started,ip=[::ffff:5.188.231.232]
Aug 16 07:38:18 pinnacle courieresmtpd[20892]: started,ip=[::ffff:5.188.231.232]
```

**Comment by sebres** [comment]
Our default `courier-smtp` finds matches of `error,relay=...,from=` in both cases.
I don't know why you want to catch `ESMTP command error` additionally (because then you could catch 2 failures for 1 attempt).

Why it does not find/ban in fail2ban you can see the first QA in [wiki :: Fail2ban does not detect some authentication failures resp. banning does not occurred](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works).

My assumption - either it is too old (exceeds `now - findtime` interval) or not enough failures (to be banned IP should take `maxretry` failures in the mentioned interval).

> journalctl ... > jc.out
> fail2ban-regex jc.out ....

BTW. fail2ban-regex is able to read systemd-journal (use --help to see options).

**Comment by neilromig** [comment]
I need to catch the 502 error because it occurs often and it is unusual to have both a 550 & 502 together. I still don't understand why IP 104.148.126.197 did not get banned (I have a very strict maxretry=1).

**Comment by sebres** [comment]
No idea why it does not match (inside the fail2ban service)... excepting possible the TZ issue (courieresmtpd works/logs using other TZ as the fail2ban process), but I never saw this by usage of systemd backend (the time you see in the log-excerpt is just the output, fail2ban gets proper date-time in this case directly from the systemd-journal monitor), so one can exclude almost ever this from possible reasons.

What do you see in fail2ban.log round about 03:42:59?
If nothing is findable, I think it will be impossible to solve the issue, without increase the log-level to DEBUG (at least for this jail).

**Comment by neilromig** [comment]
The fail2ban log shows nothing at around 03:42:59

```
2018-08-16 00:19:18,167 fail2ban.filter         [11304]: INFO    [courier-imap] Found 58.18.137.83 - 2018-08-16 00:19:17
2018-08-16 00:19:18,308 fail2ban.actions        [11304]: NOTICE  [courier-imap] Ban 58.18.137.83
2018-08-16 00:34:21,917 fail2ban.filter         [11304]: INFO    [courier-imap] Found 61.164.81.210 - 2018-08-16 00:34:21
2018-08-16 00:34:21,947 fail2ban.actions        [11304]: NOTICE  [courier-imap] Ban 61.164.81.210
2018-08-16 06:20:13,186 fail2ban.server         [11304]: INFO    Shutdown in progress...
```

I shut the server down to try a few tweaks to the regex. I'll just keep an eye on things and see how it goes.

**Comment by sebres** [comment]
Hmm... I see strange "pause" between 00:34:21 and 06:20:13... Looks like fail2ban stopped to monitor everything (or systemd journal monitor resp. python systemd module has swallowed up).

You meant:
> fail2ban server has not found any matches for this regex, but has matched against another regex in the same jail.

I don't see this, corresponding this fail2ban log-excerpt, simply nothing happens in this time (no matter which regex and jail).

Gotcha!
Take a look in your output by start of fail2ban from #2202 for courier-smtp:
```
2018-08-15 08:25:26,003 fail2ban.jail           [1300]: INFO    Jail 'courier-smtp' uses systemd {}
...
2018-08-15 08:25:26,005 fail2ban.server         [1300]: DEBUG     prefregex: '^(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?courieresmtpd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?courieresmtpd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?error,relay=<HOST>,<F-CONTENT>.+</F-CONTENT>$'
2018-08-15 08:25:26,008 fail2ban.server         [1300]: DEBUG     failregex: '^.*: error,relay=<HOST>,.*: 550 User.*unknown$'
2018-08-15 08:25:26,009 fail2ban.server         [1300]: DEBUG     failregex: '^.*: error,relay=<HOST>,msg="502 ESMTP command error",cmd:.*$'
2018-08-15 08:25:26,010 fail2ban.server         [1300]: DEBUG     failregex: '^.*: error,relay=<HOST>,msg="535 Authentication failed.",cmd:.*$'
2018-08-15 08:25:26,010 fail2ban.server         [1300]: DEBUG     failregex: '^.*: error,relay=<HOST>,msg="535 Authentication required.",cmd:.*$'
2018-08-15 08:25:26,011 fail2ban.server         [1300]: DEBUG     failregex: '^.*: error,relay=<HOST>,msg="540 TLS not available.*$'
2018-08-15 08:25:26,012 fail2ban.server         [1300]: DEBUG     failregex: '^.*: error,relay=<HOST>,.*: 513 Relaying denied.$'
```
one sees a `prefregex` - which used for prefiltering of the log-message, additionally it cuts out the part of message (included in `<F-CONTENT>.+</F-CONTENT>`) for finally parsing/processing via `failregex`.
This part of message does not have `... error,relay=<HOST>` anymore.
So **all** of your `failregex` are invalid (because expects more data), take a look in our filter:
https://github.com/fail2ban/fail2ban/blob/22afdbd536a193fe8ee7ff8dcc0ed7dd6cd23342/config/filter.d/courier-smtp.conf#L15-L18

So either you should remove `prefregex` (slowly), or you must change your (BTW very unprecise/vulnerable) fairegexp's like it was made in this commit
https://github.com/fail2ban/fail2ban/commit/22afdbd536a193fe8ee7ff8dcc0ed7dd6cd23342#diff-6d63112a973b1dd5a36f09474fdf95c7L15

fail2ban-regex can use `prefregex` also, but only if you specify name of the filter instead of regex, so:
```diff
-fail2ban-regex jc.out '^.*: error,relay=<HOST>,msg="502 ESMTP command error",cmd:.*'
+fail2ban-regex jc.out courier-smtp
```
This way you can check your filter work.

**Comment by neilromig** [comment]
OK, thanks for your help. Basically I didn't understand what <F-CONTENT> was - it is what is passed to the failregex, yes?
As I am not a regex guru, can you hint as to what is vulnerable in my failregex?
Also, there were no events for fail2ban to respond to after 00:34:21 - a quiet night on our small server...

**Comment by sebres** [comment]
> what F-CONTENT was - it is what is passed to the failregex, yes?

Yes, the part included between tags.

> what is vulnerable in my failregex?

- `^.*something...` does not make sense (it is the same as `something...`), so the expression is not-anchored;
- the same about end-(non-)anchored `something.*$` (like `something`);
- it is slow (or can be very slow on large messages if some present in the log)
- if regex is not-anchored from both sides (like yours), and an intruder be able to produce a message containing somewhere (in data, etc) the part, you are looking for (e. g. if courier allows to log this resp. there is some leak making this possible), your filter could catch a failure where it is not really there, so he can "ddos" you with such injected messages (with replaced another IP as the intruder really has).
