### ISSUE TITLE
Passive waiting to solve defunct proc and to dramatically improve performances

### ISSUE THREAD

**Issue by benrubson** [fail2ban/fail2ban#2213]
Hi,

From time to time I have alerts on my servers regarding _defunct_ processes.
I investigated and found that these are fail2ban processes, launched to execute system commands.
As fail2ban does not use the `wait()` call to wait for its children, there is a short moment where the children are seen as _defunct_.

I then tried the following, in `fail2ban/fail2ban/server/utils.py`, in `executeCmd()` function.

I replaced the first :
`retcode = popen.poll()`
With :
`retcode = popen.wait()`

In addition to solve the defunct issue, this passive waiting dra-ma-ti-ca-lly improves performances.

On Linux, using iptables, 3350 rules are added in 33 seconds instead of 11.5 minutes !

I know that the `wait()` call is a blocking call, but perhaps there's a workaround.
I tried to put it in a `try` bock using `signal.alarm(timeout)`, but this can't be used in threads.

Thank you very much,

Ben

**Comment by benrubson** [comment]
See #2215 for a proposal to solve this !

**Comment by benrubson** [comment]
See #2215 for some tryouts & solutions.

**Comment by sebres** [comment]
Hmm... `popen.wait()` is noting else as try `popen.poll()` (or rather internal call of `os.waitpid` used in both) while the child process running. Just the normal call of poll will use a very short inbetween sleep's additionally (but this does not explain why this should take 11 min instead of 33 seconds).
So I don't know how you tested this (by the way which python version is used?) to reach values like this (or something is just wrong on your system).

Because if I test 5 second simple ban+unban the original version vs. your version, I get:
```diff
- # original 0.10:
- 6.078ms/# 823 # (5.002s total)
+ # PR gh-2215:
+ 7.662ms/# 653 # (5.004s total)
```

So your variant seems to be 1.6ms slower per iteration (ban/unban).

This means that if I test both on my machine 33 seconds long, I get:
- 5430 ban/unban invocations, so ca. 11000 rules processed **with original version**;
- 4310 ban/unban invocations, so ca. 8600 rules processed **with your version**;

And I don't really understand how such "dra-ma-ti-ca-lly" performance increase can be reached, neither by usage of wait, nor by usage of additional command (`timeout`).

Can you please describe a scenario how you tested this? 
Additionally please provide:
1. which fail2ban and python version exactly?
2. which banaction is used in your case?

**Comment by sebres** [comment]
Futher investigations (resp. switch to simple wait without timeout) show in my case a very marginal "performance increase" by `5.914ms/# 846 # (5.003s total)`

This means a mere 0.16ms per iteration (ban+unban), so ca. 0.06ms faster on the single invocation.

I tried also a continuously add of the rules (without unban, just flush at end of the test), the result shows certain slowing down by growing of the chain, but the same "latency" for both variants (poll/wait):
```diff
- # poll (with interim sleep's):
+ # wait (without timeout):
- 6.264ms/# 799 # (5.005s total)
+ 6.196ms/# 808 # (5.007s total)
- 8.519ms/# 1175 # (10.009s total)
+ 8.455ms/# 1184 # (10.011s total)
- 15.904ms/# 2075 # (33.002s total)
+ 15.814ms/# 2089 # (33.035s total)
```
But it will be still slower as original if prefix `timeout -k ...` used in the ban-command.
Rather you seem to have a "dra-ma-ti-ca-l" performance degradation in case of poll, which I cannot explain at all.
Still waiting for more info from your side.

**Comment by benrubson** [comment]
_Sorry for my delay @sebres, I plan to give you further info !_

**Comment by benrubson** [comment]
Thank you @sebres for your feedback.
And sorry for my delayed answer.

Here are then some more details.

I'm running Fail2Ban 0.9.6-2, the official Debian 9 (current stable) version.
Python version is 3.5.3.
_banaction_ is `iptables-allports`.

I then performed the following modification in `executeCmd()` :

```
 try:
     retcode = None  # to guarantee being defined upon early except
     stdout = tempfile.TemporaryFile(suffix=".stdout", prefix="fai2ban_")
     stderr = tempfile.TemporaryFile(suffix=".stderr", prefix="fai2ban_")
+    realCmd = "timeout " + str(timeout) + " " + realCmd
     popen = subprocess.Popen(
         realCmd, stdout=stdout, stderr=stderr, shell=True,
         preexec_fn=os.setsid  # so that killpg does not kill our process
     )
     stime = time.time()
-    retcode = popen.poll()
+    retcode = popen.wait()
     while time.time() - stime <= timeout and retcode is None:
         time.sleep(0.1)
         retcode = popen.poll()
     if retcode is None:
         logSys.error("%s -- timed out after %i seconds." %
             (realCmd, timeout))
         pgid = os.getpgid(popen.pid)
         os.killpg(pgid, signal.SIGTERM)  # Terminate the process
         time.sleep(0.1)
         retcode = popen.poll()
         if retcode is None:  # Still going...
             os.killpg(pgid, signal.SIGKILL)  # Kill the process
             time.sleep(0.1)
             retcode = popen.poll()
 except OSError as e:
     logSys.error("%s -- failed with %s" % (realCmd, e))
```
This part of the code is almost the same in Fail2Ban 0.10.

Difference between `poll()` and `wait()` is that `poll()` returns immediately while `wait()` will block waiting for the child to complete.
With `poll()`, active waiting is then used to wait for the child to finish thanks to the loop.
While `wait()` uses passive waiting, which takes less resources.
This can however be a drawback as it is a blocking call.
This is why I prefixed `realCmd` with `timeout`, so that we are sure command will exit (but I'm not sure that all commands, such as _iptables_, really require this).

We could use a _timeout_ option to `wait()` as per this :
https://docs.python.org/3.5/library/subprocess.html#subprocess.Popen.wait
But then, `wait()` will use a busy-loop (non-blocking call and short sleeps), which is active waiting
(verified in the sources).

To test performance, I use `badips2.py` (with _bancategory=any_, _score=5_ and _age=24h_) to add a lot of rules when Fail2Ban starts.

Method | Result
--------|--------
`poll()` - Fail2Ban active waiting | 9094 banned IPs in 1912 seconds
`wait(timeout)` - Python active waiting (1ms sleep) | 9045 banned IPs in 0192 seconds
`wait()` - passive waiting | 9045 banned IPs in 0146 seconds
`wait()` + `timeout` `realCmd` prefix - passive waiting | 9052 banned IPs in 0165 seconds
`poll()` + `sleep(0.001/100)` - as in 0.10, instead of 0.1s | 9057 banned IPs in 0192 seconds

OK, so the last test shows that 0.9 performance issue is mainly due to the 0.1s sleep duration.
It also reveals that 0.10 reproduces the `wait(timeout)` behavior with `poll()` + `sleep(0.001/100)`.

These tests show that we could improve performance again thanks to passive waiting.
Don't know if it's worth it though.
But it was interesting to test 👍

**Comment by sebres** [comment]
Good to know. 
I thought you made your comparision with 0.10, because #2215 was 0.10-based.
And 0.9 is famously **significantly** slower as 0.10 (so it makes no sence at all)... 

Anyway:

1. I noticed other results as your (in my case `wait() + timeout` was a bit slower as current `0.10` branch).
2. There is another branch of me (WiP) with a multi-threaded pool of workers (totally asynchronous execution), so no waiting at all anymore in the ban-manager.
3. There is another branch (WiP) with new `bulkban` functionality (at the moment iptables/ipset actions only), so the ban of 9000 IPs occurs here as one single command.

Thus closed because of 2. and 3... Just be patient.

**Comment by benrubson** [comment]
Thank you again for your feedback @sebres 👍
