### ISSUE TITLE
Code structure for filter/action with script

### ISSUE THREAD

**Issue by fartbagxp** [fail2ban/fail2ban#2252]
Thank you for fail2ban.

I'm currently on using a RedHat variant with Fail2Ban v0.10.4 installed, and I wrote filters + actions in order to geofence a device.
The filter is similar to what's in the *sshd* filter. It works and is able to funnel messages over to the action.

The action looks like the following:
```sh
# Option:  actionban
# Notes.:  command executed when banning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionban = IP=<ip> &&
            COUNTRY=$(geoiplookup $IP | egrep "<country_list>") && [ "$COUNTRY" ] ||
            (iptables -I f2b-<name> 1 -s <ip> -j <blocktype>)

# Option:  actionunban
# Notes.:  command executed when unbanning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionunban = IP=<ip> &&
              COUNTRY=$(geoiplookup $IP | egrep "<country_list>") && [ "$COUNTRY" ] ||
              (iptables -D f2b-<name> -s <ip> -j <blocktype>)
```

Currently, everything works, but the log file in */var/log/fail2ban.log* contains entries that I do not want. From a code structure perspective, all IPs that has gone through the filter is considered banned, but since I'm letting my action set up the condition, logs are still being written for IP addresses being banned.

For example, I would view the logs and see the following:
```sh
2018-10-06 22:15:10,252 fail2ban.filter         [13044]: INFO    [geoip-fence] Found 192.40.95.27 - 2018-10-06 22:15:09
2018-10-06 22:15:10,273 fail2ban.actions        [13044]: NOTICE  [geoip-fence] Ban 192.40.95.27
```

It is listed as banned in the logs, but no action was actually applied to it, which is correct.

My expectation is that this IP shouldn't show up in the logs at all, but since filter only gives me a failregex to work with, I don't currently have a solution to filter them out of the logs, since rules aren't applied to some of these IP addresses.

Is there a way to run scripts within filter? Is there a pre-condition I can set in action, before action determines it should be banned?

**Comment by sebres** [comment]
So you're looking for the way to ignore IP in case of certain countries (whitelist)...
In this case appending it to the banaction is a bit wrong way, because simply too late - the "banning" of the ticket already happens, for example it is already added into the list of banned tickets (and if you get this IP again - you'll see still another log messages, like "Already banned", etc).

The proper way is to use `ignorecommand` (with small cache to avoid too many calls):
```ini
# cache max 100 ips for max 5 minutes:
ignorecache = key="<ip>", max-count=100, max-time=5m

# ignore IPs from country_list (returns 0 if ignore, 1 otherwise):
ignorecommand =  COUNTRY=$(geoiplookup "<ip>" | egrep "<country_list>"); if [ "$COUNTRY" == "" ]; then exit 0; fi; exit 1
```

I don't think that completely ignore like you're doing this is a good at all... for example an intruder could use affected computers of some bot-net (or VPN) from countries that you have whitelisted.
BTW, I have an extension (not yet published) for our 0.11th branch where the ban-factor may be changed corresponding geo-data... One can control `maxretry` as well as `bantime` values, for example one could configure the factors to ban after 100 attempts from "DE", after 10 attempts from "EU" and after 3 attempts from "CN". 
I'll try to publish this enhancement this or next week (I inform you here if it is available).

**Comment by johnramsden** [comment]
@sebres I'd love to have something that bans based on geodata, do you have any updates on this feature?

**Comment by edsontadeuas** [comment]
Hello fartbagxp!

Were you able to block IP addresses by country using fail2ban and geoip?
I need help to make it work.
It's not working as i need.

**Comment by Goret05** [comment]
@sebres It has been a very long time here. Sorry to dig this up, but controling `maxretry` and `bantime` values according to countries is exactly what I'm looking for and what I'm struggling with at the moment. Is this extension published?

**Comment by sebres** [comment]
> Is this extension published?

Not yet, but I'm working on backport to stock fail2ban now... this feature (with geo-based factor for attempt count and bantime-increment) will be definitely released with next version.
