### ISSUE TITLE
Ban not working in environments with load balancer

### ISSUE THREAD

**Issue by NisariAIT** [fail2ban/fail2ban#2258]
Hello,
I am using fail2ban(v 0.9.3) on Ubuntu 16.04 server with nginx 1.15.0. I have written a custom filter that will ban the IP address that tries to access forbidden pages of the site n number of times. When I try testing this using an IP address, my IP is listed as banned in the IPTables list. However, when I try to access the site using the sub-domain name from the same IP address(banned one), I am able to login to the site and access all the pages in spite of the ban.

**NOTE: This site is hosted using AWS ELB under which there are 2 nginx servers.**

**Filter:**
```ini
[Definition]
failregex = ^ \[error\] \d+#\d+: . forbidden ., client: <HOST>, .*$
ignoreregex =
```
Any ideas on how to appropriately configure fail2ban for servers behind a load balancer would be appreciated.

**Comment by sebres** [comment]
> Any ideas on how to appropriately configure fail2ban for servers behind a load balancer would be appreciated.

You have several options for such banning:
1. either you should do the ban directly on the load balancer server;
2. or you have to use some custom action to notify the load balancer to ban/unban the IP/session/user/etc (no idea AWS ELB offers such kind of functionality).
3. or you can use some action to ban the IP/session/user/etc inside nginx or/and backends locally.
  For example in case of nginx it may be something like our [action.d/nginx-block-map.conf](https://github.com/fail2ban/fail2ban/blob/0.10/config/action.d/nginx-block-map.conf), see #1974 for details.

Please note that the option 3, if used not IP-related (so token_id is something like session-id not the IP) is only available for fail2ban version >= 0.10 (previously no `<fid>` tag, so only tag `<ip>` is available in action).
You can also try to rewrite this action (and your nginx-config) simply using real IP (if that is provided from AWS), for example using http-headers `X-Real-IP` or `X-Forwarded-For`:
```diff
# in nginx http-section:
-     #map $arg_token_id      $blck_lst_tok { include blacklisted-tokens.map; }
-     map  $cookie_session_id $blck_lst_ses { include blacklisted-sessions.map; }
+     map $http_x_real_ip     $blck_lst_ses { include blacklisted-sessions.map; }
```
in this case the filter should capture the IP instead of the session-id:
https://github.com/fail2ban/fail2ban/blob/76f28658835aac152d4f850a7f43930b871e3b4c/config/action.d/nginx-block-map.conf#L67-L75
```ini
# The same log-file can be used for IP-related jail (additionally to session-related, to ban very bad IPs):
#
[nginx-blck-ip]
maxretry = 100
filter =
datepattern = ^Epoch
failregex = ^ failure "[^"]+" - <HOST>
usedns = no
```
and you can use tag `<ip>` instead of `<fid>` in the action:
```diff
-actionban = echo "\\\\<fid> 1;" >> '%(blck_lst_file)s'; %(blck_lst_reload)s
+actionban = echo "\\\\<ip> 1;" >> '%(blck_lst_file)s'; %(blck_lst_reload)s
-actionunban = id=$(echo "<ip>" | sed -e 's/[]\/$*.^|[]/\\&/g'); sed -i "/$id 1;/d" %(blck_lst_file)s; %(blck_lst_reload)s
+actionunban = id=$(echo "<ip>" | sed -e 's/[]\/$*.^|[]/\\&/g'); sed -i "/$id 1;/d" %(blck_lst_file)s; %(blck_lst_reload)s
```
If you will use the tag `<HOST>` (instead of `<ADDR>` without `<F-ID>...</F-ID>`) in filter and the tag `<ip>` (instead of `<fid>`) in the action, this could theoretically work for fail2ban v.0.9.x (but I've never tested it with this old version).
