### ISSUE TITLE
Using %(__on_port_opt)s suffix makes F2B to miss log entries

### ISSUE THREAD

**Issue by denrasulev** [fail2ban/fail2ban#2262]
/etc/fail2ban/filter.d/sshd.conf contains 14 regex rules with this suffix and they work fine.
New rule with this suffix misses log entries unless replaced with straight 'port \d+'.

### Environment:

- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.10.2
- OS, including release name/version: Linux 4.15.0-38-generic x86_64 / Ubuntu LTS 18.04
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

This rule
`^Disconnecting (?:authenticating|invalid) user .* <HOST>%(__on_port_opt)s:.*$`
misses these kind of log entries in auth.log:
```
Oct 25 10:14:41 localhost sshd[17951]: Disconnecting authenticating user root 185.246.128.25 port 38771: Change of username or service not allowed: (root,ssh-connection) -> (administrator,ssh-connection) [preauth]
Oct 25 10:15:00 localhost sshd[17953]: Disconnecting invalid user administrator 185.246.128.25 port 3943: Change of username or service not allowed: (administrator,ssh-connection) -> (nagios,ssh-connection) [preauth]
```

But if I change the rule to this:
`^Disconnecting (?:authenticating|invalid) user .* <HOST> port \d+:.*$`
it works fine and catches all the entries.

LogLevel in /etc/ssh/sshd_conf is set to VERBOSE.

Providing this suffix works fine in all other rules, how to solve this puzzle?

**Comment by sebres** [comment]
> New rule with this suffix misses log entries unless replaced with straight 'port \d+'.

Where you have entered this new rule? 
The "local" filter interpolation variables are available in `filter.d/sshd.conf`, its local-version `filter.d/sshd.local` (and includes) only.
So extending the failregex in `jail.local` resp. in other config-files doesn't interpolate it (because the variable `__on_port_opt` is unknown there).

I'm not sure, but possibly our new filter could catch this kind of "failures" without this new rule (and without VERBOSE mode), at least in aggressive mode...
But if you really want this new own rule, implementing of `filter.d/sshd.local` like below should work:
```ini
[Definition]
failregex = %(known/failregex)s
            ^Disconnecting (?:authenticating|invalid) user \S+ <HOST>%(__on_port_opt)s:
```

> `^Disconnecting (?:authenticating|invalid) user .* <HOST>%(__on_port_opt)s:.*$`

Please note, that usage of greedy catch-all (part `.*`) before the host is a bit vulnerable, especially in not anchored regex (and it is really unanchored, because `.*$` makes no sense at all and the regex is open from the right).
