### ISSUE TITLE
Need userID for SSH Login Failures

### ISSUE THREAD

**Issue by kdhallbgm** [fail2ban/fail2ban#2263]
Environment:

- Version: 0.9.6-2 (Debian 9 standard package)
- OS, including release name/version: Debian 9 with BPO
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

Summary:

We have an extremely high SSH attack rate on a couple Debian 9 servers, so we have a fairly tight detection threshold and a rather long ban time.  However, once in a while a legitimate user has a bad day and gets blocked.  We would like to write an action that checks if the username is known and sends the IP that got blocked to a legitimate user's registered email.  The idea is to have the user use a service such as http://findmyip.org to check their IP address.  If it matches the email will have instructions on how to contact the SysAdmin to get their IP unblocked.  

In order to do this we have tried to do something similar to how other fields are extracted by the regexs in filter.d/sshd.conf and subsequently applied, but we have not been successful.

If there is already a mechanism in place for this please let us know.  Otherwise we would gladly accept some hints and direction and report back on how our setup works.

Thanks.

-Dave

```
```

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
The capturing of user-id from the log is already availaible in fail2ban since version 0.10 (see #1698)
So if `failregex` specified like this:
```ini
failregex = ^Failed password for user <F-USER>\S+</F-USER>...$
```
You can use it in the action with tag `<F-USER>`, for example:
```ini
actionban = do-ban.sh "<ip>" && notify-user-banned.sh "<F-USER>"
```

Please note, that our standard sshd-filter was fully rewritten in 0.10, so it is more stable and robust now as regards the possible mistake banning of legitimate users (see for example #2188 for more info).
So a successful connect will automatically reset a possible previous failures for the IP (if always the same user name is used by authentication).
Therefore if you will update your version, possibly it will work as expected out-of-the-box and you won't need any action-customization anymore.
