### ISSUE TITLE
fail2ban-client: ERROR  No file(s) found for glob 

### ISSUE THREAD

**Issue by jingxize** [fail2ban/fail2ban#2275]
### Environment:
Centos 7

- Fail2Ban version (including any possible distribution suffixes):
Fail2Ban v0.9.7 

### The issue:
I used fail2ban for Challenge Collapsar to nginx , and I create a file nginx-cc.conf in /etc/fail2ban/filter.d ,the add the nginx-cc to the jail.local .
when I start the fail2ban,I got the error message which recorded in /var/log/messages
Nov 15 11:33:04 localhost fail2ban-client: ERROR  No file(s) found for glob /usr/local/nginx/log/nginx.access.log .But the nginx.access.log is exists.If I pass backend = systemd in the jail.local for the nginx-cc,the fail2ban can start successfully.

**Comment by sebres** [comment]
> ERROR No file(s) found for glob /usr/local/nginx/log/nginx.access.log. But the nginx.access.log is exists.

Possibly it exists now, but it was still not available at fail2ban start point.
Additionally note if you run your fail2ban not as root or fail2ban service hardening (like #2162) you may need to set correct permission for this file.
> If I pass backend = systemd in the jail.local for the nginx-cc,the fail2ban can start successfully.

This is wrong if your nginx writes to the log-file. The backend `systemd` is provided to search failures inside the systemd-journal (this way your jail nginx-cc will simply never catch any failure).

**Comment by taolianggit** [comment]
**I have the same issue**, fail2ban-client: ERROR No file(s) found for glob...
I did some tests, when the nginx "access.log" & "error.log"  located in /var/log/nginx/, the fail2ban can start successfully, if the log files located in other folder... I got the error message...
I have not resolved it.

**Comment by sebres** [comment]
> I have not resolved it.

You cannot "resolve" it without configuring the correct `logpath`.
Because at least in file-related backend's, fail2ban still expects the log-file is available by start.

> if the log files located in other folder

Here is the simple entries in jail.local as example for nginx-jails, either set the interpolations variables `nginx_error_log` and `nginx_access_log` in your default section, or set `logpath` directly in jail (you must do this for all jails expecting this log-files):
```ini
[DEFAULT]
nginx_error_log = /var/log/nginx/error.log
                  /var/log/nginx-other-folder/error.log
nginx_access_log = /var/log/nginx/access.log
                   /var/log/nginx-other-folder/access.log
...
[my-nginx-jail-that-need-access-log]
logpath = /var/log/nginx-other-folder/access.log
```

**Comment by taolianggit** [comment]
### The nginx error log file exists, list the file

[root@localhost fail2ban]# ll  /data/nginx/logs/*error.log
-rw-rw-rw-. 1 root root 0 11月 29 20:45 /data/nginx/logs/error.log


### logpath configured in jail.local

[root@localhost fail2ban]# cat jail.local
[DEFAULT]
ignoreip = 127.0.0.1/8
bantime  = 86400
findtime = 300
maxretry = 5
banaction = firewallcmd-ipset
action = %(action_mwl)s

[sshd]
enabled = true
filter  = sshd
port    = 22
action = %(action_mwl)s
logpath = /var/log/secure


[sshd-ddos]
enabled = true
filter = sshd-ddos
port    = ssh
action = %(action_mwl)s
logpath = %(sshd_log)s
backend = %(sshd_backend)s


[nginx-http-auth]
enabled = true
filter = nginx-http-auth
port    = http,https
action = %(action_mwl)s
maxretry = 20
findtime = 600
bantime = 3600
logpath = /data/nginx/logs/*error.log


### Start fail2ban unsuccessful 

[root@localhost fail2ban]# systemctl start fail2ban.service
Job for fail2ban.service failed because the control process exited with error code. See "systemctl status fail2ban.service" and "journalctl -xe" for details.


[root@localhost fail2ban]# systemctl status fail2ban.service
fail2ban.service - Fail2Ban Service
   Loaded: loaded (/usr/lib/systemd/system/fail2ban.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since 五 2018-11-30 12:20:44 CST; 52s ago
     Docs: man:fail2ban(1)
  Process: 35628 ExecStop=/usr/bin/fail2ban-client stop (code=exited, status=0/SUCCESS)
  Process: 38493 ExecStart=/usr/bin/fail2ban-client -x start (code=exited, status=255)
 Main PID: 35343 (code=exited, status=0/SUCCESS)

11月 30 12:20:44 localhost.localdomain systemd[1]: Failed to start Fail2Ban Service.
11月 30 12:20:44 localhost.localdomain systemd[1]: Unit fail2ban.service entered failed state.
11月 30 12:20:44 localhost.localdomain systemd[1]: fail2ban.service failed.
11月 30 12:20:44 localhost.localdomain systemd[1]: fail2ban.service holdoff time over, scheduling restart.
11月 30 12:20:44 localhost.localdomain systemd[1]: start request repeated too quickly for fail2ban.service
11月 30 12:20:44 localhost.localdomain systemd[1]: Failed to start Fail2Ban Service.
11月 30 12:20:44 localhost.localdomain systemd[1]: Unit fail2ban.service entered failed state.
11月 30 12:20:44 localhost.localdomain systemd[1]: fail2ban.service failed.


### Error message in /var/log/message, 
**it said ‘No file(s) found for glob /data/nginx/logs/*error.log’**

Nov 30 12:20:43 localhost systemd: Starting Fail2Ban Service...
Nov 30 12:20:44 localhost fail2ban-client: ERROR  No file(s) found for glob /data/nginx/logs/*error.log
Nov 30 12:20:44 localhost fail2ban-client: ERROR  Failed during configuration: Have not found any log file for nginx-http-auth jail
Nov 30 12:20:44 localhost systemd: fail2ban.service: control process exited, code=exited status=255
Nov 30 12:20:44 localhost systemd: Failed to start Fail2Ban Service.
Nov 30 12:20:44 localhost systemd: Unit fail2ban.service entered failed state.
Nov 30 12:20:44 localhost systemd: fail2ban.service failed.
Nov 30 12:20:44 localhost systemd: fail2ban.service holdoff time over, scheduling restart.
Nov 30 12:20:44 localhost systemd: Starting Fail2Ban Service...
Nov 30 12:20:44 localhost fail2ban-client: ERROR  No file(s) found for glob /data/nginx/logs/*error.log
Nov 30 12:20:44 localhost fail2ban-client: ERROR  Failed during configuration: Have not found any log file for nginx-http-auth jail
Nov 30 12:20:44 localhost systemd: fail2ban.service: control process exited, code=exited status=255
Nov 30 12:20:44 localhost systemd: Failed to start Fail2Ban Service.
Nov 30 12:20:44 localhost systemd: Unit fail2ban.service entered failed state.
Nov 30 12:20:44 localhost systemd: fail2ban.service failed.
Nov 30 12:20:44 localhost systemd: fail2ban.service holdoff time over, scheduling restart.
Nov 30 12:20:44 localhost systemd: start request repeated too quickly for fail2ban.service
Nov 30 12:20:44 localhost systemd: Failed to start Fail2Ban Service.
Nov 30 12:20:44 localhost systemd: Unit fail2ban.service entered failed state.
Nov 30 12:20:44 localhost systemd: fail2ban.service failed.
