### ISSUE TITLE
jail.conf - ASSP - action : Issue on centos7

### ISSUE THREAD

**Issue by bellocarico** [fail2ban/fail2ban#2280]
I just want to report that to make the default installation of fail2ban on centos7 I could see the IP appearing in the ipset but not apparent banning happening . From the fail2ban log:
```
2018-11-20 20:41:27,609 fail2ban.actions [107003]: NOTICE [assp] 45.125.66.105 already banned
```
A quick investigation of the iptables reported no reference to fail2ban. So I had to modify the jail.conf

from this
```ini
action = iptables-ipset-proto4[name=assp, port="25,465,"]
```
to this:
```ini
action = iptables-ipset-proto4[name=assp, port="25,465"]
```
and now it works.

**Comment by sebres** [comment]
> So I had to modify the `jail.conf`

We have nothing like this in our (default) `jail.conf` for jail `assp`.
Solely the port entry (see https://github.com/fail2ban/fail2ban/blob/e2a255d104f947f149cc34b17e778c05175e9f78/config/jail.conf#L524-L528)

Either your `jail.conf` has been modified by you or by your maintainers in the distribution packet (then it is 3rd party issue).
Or (if you meant this default `port` entry), it looks like port `submission` is not defined on your system.

Anyway strange is that you don't have an error by inserting the iptables chain with "invalid" dports parameter via:
```
iptables -I <chain> -p <protocol> -m multiport --dports <port> -m set --match-set f2b-<name> src -j <blocktype>
```
Anyway it should produce an error (or silently ignore the comma), thus somehow or other it looks like a 3rd party issue (iptables/ipset bug or wrong maintainer fail2ban config).

By the way: direct changing of the config in `jail.conf` is not good idea at all, see [wiki :: Proper fail2ban configuration :: FAQ](https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration) for more info. Shortly - use `jail.local` instead of.
