### ISSUE TITLE
Error recidive jail

### ISSUE THREAD

**Issue by spawnzao** [fail2ban/fail2ban#2283]
I have activated the recidive jail in my environment

> Fail2Ban v0.9.7

But, the jail is not recognizing any entries in the log file...

fail2ban-client status recidive

> Status for the jail: recidive
> |- Filter
> |  |- Currently failed: 0
> |  |- Total failed:     0
> |  `- Journal matches:  _SYSTEMD_UNIT=fail2ban.service PRIORITY=5
> `- Actions
>    |- Currently banned: 0
>    |- Total banned:     0
>    `- Banned IP list:

fail2ban-regex /var/log/fail2ban.log /etc/fail2ban/filter.d/recidive.conf

> Running tests
> =============
> 
> Use   failregex filter file : recidive, basedir: /etc/fail2ban
> Use         log file : /var/log/fail2ban.log
> Use         encoding : UTF-8
> 
> 
> Results
> =======
> 
> Failregex: 4786 total
> |-  #) [# of hits] regular expression
> |   1) [4786] ^((?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel: \[ *\d+\.\d+\]\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?fail2ban\.actions\s*(?:\(\S+\))?[\]\)]?:?|[\[\(]?fail2ban\.actions\s*(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?| fail2ban\.actions\s*(?:\[\d+\])?:\s+)NOTICE\s+\[(?!recidive\])(?:.*)\]\s+Ban\s+<HOST>\s*$
> `-
> 
> Ignoreregex: 0 total
> 
> Date template hits:
> |- [# of hits] date format
> |  [45009] Year(?P<_sep>[-/.])Month(?P=_sep)Day 24hour:Minute:Second(?:,Microseconds)?
> `-
> 
> Lines: 45963 lines, 0 ignored, 4786 matched, 41177 missed
> [processed in 3.52 sec]
> 
> Missed line(s): too many to print.  Use --print-all-missed to print all 41177 lines
> 

There are many BAN entries in the file, but the recidive rule is not working

jail.conf:
```
[recidive]
enabled = true
logpath  = /var/log/fail2ban.log
banaction = %(banaction_allports)s
bantime  = 604800  ; 1 week
findtime = 86400   ; 1 day
maxretry = 3
```

Odd that the sshd rule is working perfectly, but recivide jail not.

**Comment by sebres** [comment]
Which backend used for recidive jail? I assume systemd.

Because corresponding your `fail2ban-regex` excerpt, your fail2ban seems to log into log file (`/var/log/fail2ban.log`), not into systemd-journal...
In case of systemd-backend the filter of jail observes systemd-journal (and would not find any entry).
In this case you must set backend to any file-relate backends (or `auto`):
```ini
[recidive]
backend = auto
...
findtime = 86400   ; 1 day
maxretry = 3
```
Also note that you have configured `maxretry` as 3, this means you should get at least 3 entries within `maxretry` (1 day) for an IP to ban it.

You can take a look in our [wiki / FAQ](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) for several reasons why Fail2ban does not detect some authentication failures resp. banning does not occur.

**Comment by spawnzao** [comment]
Which backend used for recidive jail?

```
[DEFAULT]
ignorecommand =
bantime  = 600
findtime = 600
maxretry = 5
**backend = auto**
usedns = warn
logencoding = auto
enabled = false
filter = %(__name__)s
sendername = Fail2Ban
sender = fail2ban@localhost
banaction = iptables-multiport
banaction_allports = iptables-allports
mta = sendmail
protocol = tcp
chain = INPUT
port = 0:65535
action_ = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
action_mb = %(banaction)s[name=%(__name__)s, port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
            %(mta)s-buffered[name=%(__name__)s, dest="%(destemail)s", protocol="%(protocol)s", chain="%(chain)s", sendername="%(sendername)s"]
action_mw = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
            %(mta)s-whois[name=%(__name__)s, dest="%(destemail)s", protocol="%(protocol)s", chain="%(chain)s"]
action_mwl = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
             %(mta)s-whois-lines[name=%(__name__)s, dest="%(destemail)s", logpath=%(logpath)s, chain="%(chain)s"]
action_xarf = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
             xarf-login-attack[service=%(__name__)s, sender="%(sender)s", logpath=%(logpath)s, port="%(port)s"]
action_cf_mwl = cloudflare[cfuser="%(cfemail)s", cftoken="%(cfapikey)s"]
                %(mta)s-whois-lines[name=%(__name__)s, dest="%(destemail)s", logpath=%(logpath)s, chain="%(chain)s"]
action_blocklist_de  = blocklist_de[email="%(sender)s", service=%(filter)s, apikey="%(blocklist_de_apikey)s"]
action_badips = badips.py[category="%(name)s", banaction="%(banaction)s"]
action = %(action_mwl)s
``
How do I change fail2ban to check the log file directly without using systemd-journal?
I changed the backend and did not change anything...

I do not know what I have to do!

There are thousands of blocked ips (8k only today) in fail2ban.log and the recidive rule is not working.

**Comment by sebres** [comment]
You seems to have a **default** backend = auto. This says nothing about the jails, e. g. in `recidive` it could be configured by maintainer-includes per default), so to be sure you can add it in your `[recidive]` section:
```ini
[DEFAULT]
backend = auto
....
[recidive]
backend = auto
```
Anyway to check the current backend value set in config, you could try:
```bash
fail2ban-client -d | grep "add', 'recidive"
```
you will see either (what could be wrong, because as I said - fail2ban logs into log-file):
```
['add', 'recidive', 'systemd']
```
or (probably correct):
```
['add', 'recidive', 'auto']
```
Also note that after config-change you need to restart fail2ban or reload configuration (I don't know reload was possible in 0.9.7).

> There are thousands of blocked ips (8k only today) in fail2ban.log and the recidive rule is not working.

Again, it is crucial how many entries do you have for single IP (so it does not ban, if you have 8k different IPs there).

**Comment by spawnzao** [comment]
After I added backend in jail recidive it worked...
Thank you!
