### ISSUE TITLE
SSH with Pubkey only, all valid attempts being blocked

### ISSUE THREAD

**Issue by acs-ferreira** [fail2ban/fail2ban#2288]
My `jail.local` is quite simple:

```
[DEFAULT]
ignoreip = 127.0.0.1/8
           111.111.111.111
findtime = 600
action = %(action_)s

[sshd]
enabled = true
logpath = %(sshd_log)s
port = 22
banaction = iptables
bantime = 2592000
maxretry = 1
```

Each valid connection attempt is blocked. Password auth is disabled, only Pubkey is accepted.
If i connect with a valid User + Pubkey, i'm blocked.

**auth.log**

`Nov 28 00:19:07 srv-p sshd[13070]: Accepted publickey for user from 1.2.3.4 port 56411 ssh2: ED25519 SHA256:vkdmN39xxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

**fail2ban.log**

```
2018-11-28 00:19:07,415 fail2ban.filter [22932]: INFO [sshd] Found 1.2.3.4 - 2018-11-28 00:19:07
2018-11-28 00:19:07,772 fail2ban.actions [22932]: NOTICE [sshd] Ban 1.2.3.4
```

**Fail2Ban v0.10.2**

**Comment by sebres** [comment]
Hmm... Cannot check right what is wrong there with 0.10.2, but it is not reproducible with latest 0.10 (>= 0.10.4).
Please try to update your sshd-filter from [0.10.4](https://raw.githubusercontent.com/fail2ban/fail2ban/0.10.4/config/filter.d/sshd.conf). Don't use newest sshd-filter because it could be incompatible to your fail2ban version.
Additionally note, that sshd is a multi-line filter, so fail2ban analyzes several lines of the connect, thus please provide all lines from log-file by `| grep 'sshd\[13070\]'`...
