### ISSUE TITLE
permanent banning and duplicate bans for same IP

### ISSUE THREAD

**Issue by hajes** [fail2ban/fail2ban#2325]
I've recently created file server and I wonder about fail2ban functionality.

**How does exactly fail2ban works because there is no detailed description** other than "fail2ban checks for several auth attempts in auth.log"

Since, I am only one user on my server - everything/everyone else is intruder. I have set permanent banning with "bantime=-1". I have set external file where all banned IPs are stored in case of server reboot.

So far I understand following functionality:

f2b watches auth.log
f2b bans IP

I noticed that f2b doesn't check what is already in iptables and simply adds IP again and again. I'm not sure how is it even possible with already active iptables rule to block this IP...f2b checking again same IP and blocks it

Is it bug or am I missing something - any suggestions, please?

### Environment:

Debian VPS + latest stable fail2ban

**Comment by sebres** [comment]
People, we have made our issue template not for nothing! 
Which version of fail2ban & OS is there? Do some customization's are made? Which ban-action is used (specified in jail.local for this jail or default)? Etc?

How fail2ban exactly works as well as many other details, you can find in our [wiki](https://github.com/fail2ban/fail2ban/wiki/).

Although it looks like a bug (or rather as misconfiguration) to me, I'll close this unless more info will provided.

**Comment by hajes** [comment]
I apologise my bad - Debian VPS, kernel 2.6.32, failban v0.9.6

config default except permanent ban setup and logging into external file

before I added rule to check for already existing IPs in block list...fail2ban kept adding same/duplicate IPs. It suppose to be impossible because it should be already blocked by iptables.

I have tried latest development version and it started to block me for no reason after just few days of running without any auth failures.

Of course it is OpenVZ VPS container with shared host HW so there may be underlying issues on ISP side.

I wondered about "actioncheck" in action.d/iptables-multiport.conf

**Comment by sebres** [comment]
Well, fail2ban 0.9.6 supports database (if not disabled in fail2ban.local), so stores this way the last log-positions as well as the already banned IPs.
Which will be restored (all still active going banned) if fail2ban started (and it unbans all IPs if goes stopped). And persistent tickets are always active (until not manually removed with `fail2ban-client ... unban`).

Normally fail2ban assumes the chains of fail2ban-actions (called `f2b-<name>`) are its own chains and nothing (excepting fail2ban self) should do something with this chains.

I don't know what do you have configured as "config default", but it looks me like something wrong in your configs or you still simply create the IPs of fail2ban with some external tools (like `iptables-restore`). If so, you should remove the entries of fail2ban (all chains and rules starting with `f2b-`) from stream/file  stored with `iptables-save`.

Parameter `actioncheck` is intended only to check the action is maintainable at all (e. g. for iptables simply checks the chain exists), so it could signal sane restoration of the chains should start, if it is missing for some reasons (e. g. iptables flush was caused from some external tool/service in-between).

This does not control the IP is already present or not in f2b-chain (still remember, this is fail2ban's own chain), however if this is wanted, it could be simply made in `actionban`/`actionunban`, for example in respective `iptables-*.local` (e.g. in iptables-multiport.local for [iptables-multiport.conf](https://github.com/fail2ban/fail2ban/blob/0.9/config/action.d/iptables-multiport.conf)) something like this:
```ini
[Definition]
actionban   = <iptables> -C f2b-<name> 1 -s <ip> -j <blocktype> 2>/dev/null && (echo "already" && exit 0)
              %(known/actionban)s
actionunban = <iptables> -C f2b-<name> 1 -s <ip> -j <blocktype> 2>/dev/null || (echo "not found" && exit 0)
              %(known/actionunban)s
```

Anyway, I leave this closed (to avoid duplicates), because we have already several "issues" like this, and there is also one cumulative todo-issue of me (#980) to prevent situations like this in the future versions.

**Comment by hajes** [comment]
if I understand correctly - it doesn't matter what is in iptables because fail2ban checks its database?

So if you reboot server, database will be empty and all starts all over again?

I wanted persistent ban so I added into `actionban` echo $IP >> ip.blocklist

in `actionstart` I added read lines from ip.block list and insert into iptables.

It may be cause why there is duplicate IPs blocked because database is empty after reboot but iptables contain all previously blocked IPs.

**Comment by hajes** [comment]
`dbpurgeage = 0` has same effect for persistent bans as tinkering with some external filöes right?

**Comment by sebres** [comment]
> if I understand correctly - it doesn't matter what is in iptables because fail2ban checks its database?

Yes, unless you extend the action (as described above) to check IP-rules.

> So if you reboot server, database will be empty and all starts all over again?

No, database is not empty after reboot (it is persistent database). Vice versa - therefore fail2ban begins to ban all IPs found as active after start.
And it simply does not expect at the moment, that something has manipulated the own chains of fail2ban.

> I wanted persistent ban so I added into actionban echo $IP >> ip.blocklist

You said fail2ban the IP is persistent (`bantime=-1`), so fail2ban takes the job to hold it persistently banned.
If something else excepting fail2ban manipulates fail2ban chains, it is not an issue of fail2ban.

The duplicates after reboot occurs because even something else "resores" the IPs before fail2ban starts.
Possibly why your ip.blocklist will be restored after restart (and hereafter fail2ban does it also).

Parameter `dbpurgeage` would not help here, because the time of purge is rather undefined, could be happen after restore active tickets (let alone there was a bug in v.0.9 as regards purge #1267, so purge process is simply never started at all).

Anyway I described above comprehensive enough why it happens as well the possible ways to resolve it.
External manipulating of IPs in rules, which are under fail2ban control, would avoid that in your case.

Disabling of fail2ban database may do that too, just it is not good idea at all (because the positions of log-files are then unknown after start, so fail2ban will process log-files again, if they are not rotated).

**Comment by hajes** [comment]
thanks for explanation, it is clear now why there is duplicates.

fail2ban loads own database
then loads again same IPs stored in external file.
