### ISSUE TITLE
Nextcloud Regexp problems

### ISSUE THREAD

**Issue by bonanza123** [fail2ban/fail2ban#2330]
I am having troubles to get my regexp working.
I have run the regexp tester with `-D` option, and it lists for example the line below under "missed"

```

{"reqId":"T1TlpiPe5MAUZDGQ8qKF","level":2,"time":"January 26, 2019 20:24:05","remoteAddr":"203.81.71.7","user":"Alfred.Dz","app":"core","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Login failed: 'alfred.dz@gmail.com' (Remote IP: '203.81.71.7')","userAgent":"Mozilla\/5.0 (Macintosh) mirall\/2.3.3 (build 84) (Nextcloud)","version":"15.0.2.0"} | ^{.*\"Login failed: '.*' \(Remote IP: '<HOST>'\)\".*}$ |  https://www.debuggex.com/?re=%5E%7B.%2A%5C%22Login+failed%3A+%27.%2A%27+%5C%28Remote+IP%3A+%27%28%3F%26.ipv4%29%27%5C%29%5C%22.%2A%7D%24&str=%7B%22reqId%22%3A%22T1TlpiPe5MAUZDGQ8qKF%22%2C%22level%22%3A2%2C%22time%22%3A%22January+26%2C+2019+20%3A24%3A05%22%2C%22remoteAddr%22%3A%22203.81.71.7%22%2C%22user%22%3A%22Alfred.Dz%22%2C%22app%22%3A%22core%22%2C%22method%22%3A%22GET%22%2C%22url%22%3A%22%5C%2Focs%5C%2Fv2.php%5C%2Fapps%5C%2Fnotifications%5C%2Fapi%5C%2Fv1%5C%2Fnotifications%3Fformat%3Djson%22%2C%22message%22%3A%22Login+failed%3A+%27alfred.dz%40gmail.com%27+%28Remote+IP%3A+%27203.81.71.7%27%29%22%2C%22userAgent%22%3A%22Mozilla%5C%2F5.0+%28Macintosh%29+mirall%5C%2F2.3.3+%28build+84%29+%28Nextcloud%29%22%2C%22version%22%3A%2215.0.2.0%22%7D&flavor=python
```

(For privacy reasons, I have searched&replaced the users name and mail addresses)

When opening the link to debuggerX, it mentions a full match. What is wrong there?

I am running Fail2Ban v0.9.6 on debian stretch.

**Comment by sebres** [comment]
The reason here is not the failregex (even if you'd use short `IP:\s+'<HOST>'`), but **unrecognized date-time pattern**. Shortly, fail2ban does not find any time there.
If you had used it in fail2ban or started fail2ban-regex with debug log-level, you'd see a long warning:
```
WARNING: Found a match for u'...' but no valid date/time found for u'...'. Please try setting a custom date pattern (see man page jail.conf(5)). ...
```
You can specify your own date-pattern via `datepattern = ,?\s*"time":"%%B %%d, %%Y %%H:%%M:%%S"` that will cover this log entry. 
*(Not if you'll test it as parameter for fail2ban-regex command line, you should use single `%`, dual `%%` used only in python-config files. Also note that fail2ban will cut the pattern from log-message out before apply failregex, so you should not match it there)*

BTW. Your regex is extremely vulnerable, because it is not anchored from both sides (`^{.*` is not an anchor) as well as with interim greedy catch-all (`.*`) in-between. Still worse you would catch an address from message that are placed after some foreign data (like URI), thus it is extremely inject-fragile.
Despite there is another entry `remoteAddr` (with the same IP-address) much closer (and before any foreign data).

This is many times safer regex just as possible example:
```ini
[Definition]

_groupsre = (?:(?:,?\s*"\w+":(?:"[^"]+"|\w+))*)
failregex = ^\{%(_groupsre)s,?\s*"remoteAddr":"<HOST>"%(_groupsre)s,?\s*"message":"Login failed:
\s*"message":"Login failed:

datepattern = ,?\s*"time":"%%B %%d, %%Y %%H:%%M:%%S"
```

**Comment by bonanza123** [comment]
@sebres thanks so much for your detailed reply and the example.

I took the liberty and copy/pasted it over to my machine and then ran the regexp tester which gives me: https://gist.github.com/bonanza123/689a7b9e093c0ce22f014f0a115e508b

(I just copied the first line of the missed ones)

It still seems to be missed and I can not find the reason. Are there any additional switches besides those I already have to see the reason of failure?

where `/etc/fail2ban/filter.d/nextcloud2.conf` contains your code from above.

**Comment by sebres** [comment]
Your gist shows definitely that the datepattern is ignored (it uses default date-templates).
[This](https://gist.github.com/bonanza123/689a7b9e093c0ce22f014f0a115e508b#file-fail2ban-L21-L37) should contain only one custom pattern (which should have hits, so not `[0]`).

No idea why it is exactly in your case (0.9 is toooo old). I tested it with 0.10 and it works there properly.
Either fail2ban-regex does not consider datepattern from filter-file (expects it in command line only, then it could work in fail2ban self) or even something else, like...

Maybe for 0.9 the `datepattern` should be added in section `[Init]` (below of `[Definition]`), anyway it was so in older commits, see for example:
https://github.com/fail2ban/fail2ban/blob/f2e55e8499744e6b1f9196d2033e25c53c23c61d/config/filter.d/squirrelmail.conf#L7-L9
For 0.10 it does no matter (the init-section is obsolete). In 0.10 you could even supply it directly in jail too.

**Comment by bonanza123** [comment]
That did it! Thanks!

Are there any plans for make your filter rule official by merging it into the repo?
