### ISSUE TITLE
fail2ban having trouble with date time format of unifi controller's server.log

### ISSUE THREAD

**Issue by startover909** [fail2ban/fail2ban#2343]
My fail2ban version is 0.9.6-2 on Debian 9 Stretch.

I'm trying to use fail2ban to protect the web GUI of unifi controller. The regex match works, but fail2ban.log complains:

WARNING Found a match for '[02:08:25,829] <webapi-7> INFO  api    - [api] Failed admin login for xxx from xx.xx.xx.xx' but no valid date/time found for '[02:08:25,829] 

So it has trouble understanding 02:08:25,829

Is there anyway to resolve this?

**Comment by sebres** [comment]
Yes... dude, there are so many docu/wiki/etc with examples....
Shortly:
```ini
datepattern = ^\[%%H:%%M:%%S(?:,%%f)?\]\s*
```
Note, the fail2ban cuts a match of date pattern out from failure message before it begins applying of `failregex`.
So in this case it should start with `^INFO ...`.

**Comment by sebres** [comment]
> I just have a quick question: with such `02:08:25,829` format that contains only time but no dates, can Fail2Ban still reliably work? I mean as the days go by and log fills up, I can imagine there will be duplicate time periods right? Does Fail2Ban maintain its internal datetime stamp, so it can tell that a logged line at 2:00am and another line at 2:01am a thousand lines below occurred on different days?

Basically - yes. Fail2ban would always assume current date (so today), if the time zone is correct and retrieved time `HH:MM:SS <= now` (otherwise it assumes yesterday and will ignore such entries if `findtime <= 86400` or `1d`).
So be sure the time in log is logged using the same time zone fail2ban work (normally it is the system timezone).

To avoid some time-related issues (e. g. ban some older attempts), you should possibly force log-rotation before restarts fail2ban.
Or simply use `tail` option for this jail (this would stop fail2ban scanning old log-files at start):
```ini
logpath = /path/to/log tail
```
See manpage <a href="https://manpages.debian.org/testing/fail2ban/jail.conf.5.en.html#JAIL_CONFIGURATION_FILE(S)_(_jail.conf)">jail.conf.5 - JAIL CONFIGURATION FILE(S) (jail.conf)</a> for details.

**Comment by Ethanol6** [comment]
I'm having issues with this as well.
`fail2ban-client version 0.11.2`
`Unifi Network Application version 7.1.65`

Log entries look like this:
>[2022-05-18T16:06:58,138] <webapi-160> WARN  api    - failed to authenticate to SSO: Cloud operation failed! RC=403, error: {"detail":"Invalid credential"}

`fail2ban-regex` without defining any `datepattern` in the filter file returns this:

```
Running tests
=============

Use   failregex filter file : unifi, basedir: /etc/fail2ban
Use      datepattern : {^LN-BEG} : Default Detectors
Use         log file : /var/log/unifi/server.log
Use         encoding : UTF-8


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [75780] {^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
`-

Lines: 75943 lines, 0 ignored, 0 matched, 75943 missed
[processed in 14.36 sec]
```
I've tried setting a `datepattern` like `\[%%Y-%%m-%%dT%%H:%%M:%%S,%%f\]` but haven't been able to catch any log lines with it.

**Comment by Ethanol6** [comment]
> What exactly do you want to catch here? The log line from your example doesn't contain any IP.

Huh, I hadn't even noticed since I was trying to get something to work at all. Now that I look at it, there are no log lines with any IP information. On top of that after cycling the logs the Unifi controller has stopped logging anything at all. So... chalk this up to Unifi being broken I guess.
