### ISSUE TITLE
how to use addfailregex

### ISSUE THREAD

**Issue by lrosenman** [fail2ban/fail2ban#2374]
I've just installed fail2ban 0.10.4, on FreeBSD 12, using python37.

I've tried a number of uses for addfailregex in both filter.d/exim.local, and jail.d/exim-pf.

What's the appropriate way to add a regex without having to copy the entire list.

Thanks!

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.10.4
- OS, including release name/version: FreeBSD thebighonker.lerctr.org 12.0-STABLE FreeBSD 12.0-STABLE r344973 LER-MINIMAL  amd64
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ x] You have not applied any additional foreign patches to the codebase
- [ x] Some customizations were done to the configuration (provide details below is so)

### The issue:

I've got it working, but am trying to figure out how to add a regexp to a filter without having to copy
the failregex.

I'm using the stock filter.d/exim.conf, and want to add:
^%(pid)s %(host_info)srejected EHLO or HELO ylmf-pc: CHECK_HELO: ylmf-pc$

**Comment by sebres** [comment]
> What's the appropriate way to add a regex without having to copy the entire list.

```ini
failregex = %(known/failregex)s
            ^my own regex 1 recognizes failure from <ADDR>
            ...
            ^my own regex N recognizes failure from <ADDR>
```
Normally (as long as you don't need some internal/predefined interpolations of filter), you'd be able to do that in `jail.local` too (otherwise use `filter.d/filter.local`).

This articles could be also interesting for you:
- [manpages :: JAIL.CONF(5) | Fail2Ban Configuration | CONFIGURATION FILES FORMAT](https://manpages.debian.org/unstable/fail2ban/jail.conf.5.en.html#CONFIGURATION_FILES_FORMAT)
- [wiki :: How fail2ban substitution resp. runtime interpolation works](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-substitution-resp.-runtime-interpolation-works)
