### ISSUE TITLE
How can I get the time of banned ip ?

### ISSUE THREAD

**Issue by ssli08** [fail2ban/fail2ban#2382]
As I mentioned in the title, I want to get the unix time for banned ip. 
How can I implement this?

Thanks for any help!

**Comment by sebres** [comment]
Where exactly?

If you mean you need it in action:
- since some version (I guess 0.9) you can simply use tag `<time>` in actionban
```ini
actionban = printf "time of ban: <time>"; ...
```
- for the case you have an older version, `$(date +%s)` would return current time (posix seconds);

If database is enabled (default for >= v.0.9), you can obtain it from there too:
```bash
# get last time of all tickets grouped by jail:
?sudo? sqlite3 'file:/var/lib/fail2ban/fail2ban.sqlite3?mode=ro' "select jail, max(timeofban) from bans where ip = '192.0.2.1' group by jail"
# get time of last ticket in jail sshd:
?sudo? sqlite3 'file:/var/lib/fail2ban/fail2ban.sqlite3?mode=ro' "select max(timeofban) from bans where ip = '192.0.2.1' and jail = 'sshd'"
```

Otherwise fail2ban.log (or journal of fail2ban.service) is your friend. For example:
```bash
?sudo? grep -F 'Ban 192.0.2.1' /var/log/fail2ban.log
```
Then you can convert it to unix time.

**Comment by ssli08** [comment]
Is there some fail2ban python libs (functions?) that i could use in my python script directly?

**Comment by sebres** [comment]
Shortly - yes, there are several python modules installed.

Which python script do you mean? Is it a pythonic action (with other words are you within a python-action during ban process)? Then you'd use something like this:
```python
class MyAction(ActionBase):
  ...
  def ban(self, aInfo):
    time = aInfo.get('time')
```
Otherwise see fail2ban.server.ticket, fail2ban.server.database etc (I don't know what do you exactly need). But note, this are modules belong to the server API, so may be not always possible to use outside of the fail2ban server.

**Comment by ssli08** [comment]
> Shortly - yes, there are several python modules installed.
> 
> Which python script do you mean? Is it a pythonic action (with other words are you within a python-action during ban process)? Then you'd use something like this:
> 
> ```python
> class MyAction(ActionBase):
>   ...
>   def ban(self, aInfo):
>     time = aInfo.get('time')
> ```
> 
> Otherwise see fail2ban.server.ticket, fail2ban.server.database etc (I don't know what do you exactly need). But note, this are modules belong to the server API, so may be not always possible to use outside of the fail2ban server.

Thank you. the script I meant was written in python myself. I just wanted to integrate fail2ban to my private servers that provided some real time video&audio business. So I'd like to call some outside modules of fail2ban.
