### ISSUE TITLE
Read gzip log files?

### ISSUE THREAD

**Issue by utags** [fail2ban/fail2ban#2391]
Hi all,

I have Fail2ban v0.10.2 running Ubuntu 18.04. I use logrotate.

My VPS old log files (_more than 2 day old_) use gzip compression and uses ".gz" file extension (like _.log.2.gz_). Apart from that, if logs older than 1 day it uses "_.log.1_" file extision. I want to know that, if I use **findtime** for **7 days** (seconds 604800), fail2ban can read my compressed log files like this?

**Comment by sebres** [comment]
>  fail2ban can read my compressed log files like this?

No, fail2ban has no backend at the moment to read compressed files.

Normally one doesn't need it, because the `findtime` is valid for all failures already read from file (also if they will be rotated later). 
Only a restart of fail2ban would cause ignoring older entries (in rotated files), but I don't think it is really interesting (either the IP would makes new attempts or it is anyway forgotten later).

This was already several times discussed and current conclusion is - don't really need it.
What does not say, if someone would provide a PR with such backend, it'd be not accepted.

BTW, I would anyway recommend to use `logpath ... tail` for longer `findtime` to avoid too long initial scan during the start of fail2ban.
