### ISSUE TITLE
recursion check should be case sensitive

### ISSUE THREAD

**Issue by KimBrodowski** [fail2ban/fail2ban#2399]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.2-2.1
- OS, including release name/version: Debian Buster (10)
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

I've migrated a server from Stretch to Buster. After that our fail2ban configuration no longer works:

~~~
Failed during configuration: properties contain self referencing definitions and cannot be resolved, fail tag: failregex, found: HOST in {'HOST': 11}, value: 
^(?:\s*\S+ cyrus/\w+\[\d+\]:) badlogin: (\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[<HOST>\]\]\]\]\]\]\]\]\]\]\]\] .*$
^(?:\s*\S+ cyrus/\w+\[\d+\]:) imaps TLS negotiation failed: (\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[<HOST>\]\]\]\]\]\]\]\]\]\]\]\]$
^(?:\s*\S+ cyrus/\w+\[\d+\]:) pop3s failed: (\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[(\S+ )?\[<HOST>\]\]\]\]\]\]\]\]\]\]\]\]$
~~~

This issue appears to be a rather simple case of two regexes using the same name, but with different casing applied. Of course this is somewhat bad practice, but since the filter did work on Stretch I'd expect it to work on Buster as well.

#### Steps to reproduce

1 Add the following filter to your fail2ban filter.d directory:

~~~
[DEFAULT]
prefix = (?:\s*\S+ cyrus/\w+\[\d+\]:)
host = (\S+ )?\[<HOST>\]

[Definition]
ignoreregex = 
failregex =
  ^%(prefix)s badlogin: %(host)s .*$
  ^%(prefix)s imaps TLS negotiation failed: %(host)s$
  ^%(prefix)s pop3s failed: %(host)s$
~~~

2. Add the filter to some jail.

#### Workaround

Rename the regex.

**Comment by sebres** [comment]
As already said, since 0.10 this incompatibility indirectly goes to on demand (recursive) interpolation of run-time parameters `<PRM>` (if they are static, so resolvable on client side) together with internal python substitution `%(prm)s` inside the config files. 
But directly this is caused by internal substitution inside of the python config reader, which is basically case insensitive per default.
Enabling of the case sensitivity in the config parsers could totally break the backwards compatibility.

Another way would be to ignore some run-time tags in filter config reader (like `<HOST>`, `<ADDR>`, etc). But until today it was also always possible to overwrite all this tags with some own regex-parts, so such change may introduce a large regression too.

Unfortunately this means that it is almost impossible to fix the issue without introducing heavy after effects, even up to total backwards incompatibility.

As an option I could implement some parameter which would enable the case sensitivity for the config files in fail2ban.
