### ISSUE TITLE
Proposed sendmail-auth rule

### ISSUE THREAD

**Issue by K2IE** [fail2ban/fail2ban#2407]
Repeated failed authentication attempts vs. sendmail, usually on port 465, are a serious problem.  Complicating matters is a long standing deficiency in remote host address logging in saslauthd, first raised in 2011 (see https://github.com/cyrusimap/cyrus-sasl/issues/346).  When the authentication attempt hits sendmail, it passes it off to saslauthd, which presents the following response on a failure:

`Apr 26 09:24:10 myhost.com saslauthd[1119]: pam_unix(smtp:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=`

There will also be more detail such as:

`Apr 26 09:24:11 myhost.com saslauthd[1119]:                 : auth failure: [user=josephmalone] [service=smtp] [realm=] [mech=pam] [reason=PAM auth error]`

Sendmail will then fail the attempt as follows:

`Apr 26 09:24:12 myhost.com sendmail[8911]: x3QDO5TG008911: [141.98.80.33] did not issue MAIL/EXPN/VRFY/ETRN during connection to TLSMTA-v6`

Since there is currently no directly way to pull the remote IP from the sasld failure, my remedy for repeated sendmail authentication failures is to match the above log line.

`^%(__prefix_line)s\w{14}: (\S+ )?\[(?:IPv6:<IP6>|<IP4>)\](?: \(may be forged\))? did not issue MAIL\/EXPN\/VRFY\/ETRN during connection to (TLS)?MTA-v[4,6]`

While the presented sendmail connection message is not in and of itself an authentication failure, taken in context it is an actionable artifact of an unwanted intrusion.  Please consider either adding this or suggesting improvements.  It has proved to be effective and non-disruptive at my site.

**Comment by sebres** [comment]
> Since there is currently no directly way to pull the remote IP from the sasld failure...

No idea it would help here, just some thoughts...

Fail2ban can serve multiple lines with same common ID, where one said a failure is occurred (but no IP is there) and another line can provide an IP information.
In 0.9.x it is a bit complex, slow and ugly (take a look at `maxlines = N` if you nevertheless want to implement that).
Since 0.10 we have special tags here:
- `<F-MLFID>...\S+...</F-MLFID>` - multi-line failure ID/token (should match a common ID like 1119 in your case)...
- `<F-NOFAIL>...</F-NOFAIL>` - signals the line is not a failure (e. g. used to obtain an IP).
- etc.

> Sendmail will then fail the attempt as follows...

The question is - does this occur by failures only (or it could happen also in other cases, like sasld-service is unavailable/busy or similar)?...
Otherwise possibly a sendmail or sasl-binding should get/provide an IP/authentication failed message in log to distinguish the auth-errors clearly.

**Comment by K2DLS** [comment]
Unfortunately, there is no direct correlation such as a common ID.  The examples provided are from a single incident.  Here is a complete stream in sequence:

```
Apr 26 12:41:32 myhost.com sendmail[18090]: STARTTLS=server, relay=[46.232.112.22], version=TLSv1.2, verify=NO, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256/256
Apr 26 12:41:34 myhost.com saslauthd[1118]: pam_unix(smtp:auth): check pass; user unknown
Apr 26 12:41:34 myhost.com saslauthd[1118]: pam_unix(smtp:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=
Apr 26 12:41:34 myhost.com audit[1118]: USER_AUTH pid=1118 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:saslauthd_t:s0 msg='op=PAM:authentication grantors=? acct="?" exe="/usr/sbin/saslauthd" hostname=? addr=? terminal=? res=failed'
Apr 26 12:41:36 myhost.com saslauthd[1118]: DEBUG: auth_pam: pam_authenticate failed: User not known to the underlying authentication module
Apr 26 12:41:36 myhost.com saslauthd[1118]:                 : auth failure: [user=bikedd] [service=smtp] [realm=] [mech=pam] [reason=PAM auth error]
Apr 26 12:41:37 myhost.com sendmail[18090]: x3QGfWAm018090: [46.232.112.22] did not issue MAIL/EXPN/VRFY/ETRN during connection to TLSMTA-v6
```
So the only option that I see at this time is to either tolerate repeated attempts to brute force SMTP authentication or to block based upon my initial suggestion.  I think it reasonable that we can expect repeated connections from the same IP that do not try to pass mail by use of a MAIL/EXPN/VRFY/ETRN command have no business repeatedly connecting to an SMTP port and have a malicious intent.

**Comment by asy972** [comment]
Update Sendmail to 8.16.1 and https://github.com/fail2ban/fail2ban/issues/2757 will help you.

**Comment by K2IE** [comment]
Since changed to postfix on the host in question, but thank you.

**Comment by sebres** [comment]
> `Apr 26 12:41:37 myhost.com sendmail[18090]: x3QGfWAm018090: [46.232.112.22] did not issue MAIL/EXPN/VRFY/ETRN during connection to TLSMTA-v6`

Although this failure can be matched by `sendmail-reject` filter with mode `extra` (see #2388 and #2787), but... 
I'd also suggest to update to newer sendmail version.

Since I don't known how we can help here otherwise (excepting to write very complex filter involved different syslog facility types), I'll close it now.
