### ISSUE TITLE
RFE: Define an action to write into database file.

### ISSUE THREAD

**Issue by trongnghia203** [fail2ban/fail2ban#2412]
Dear all,

I have installed Fail2ban successfully on our Mail-server, it work pretty well to block the IP Client try to send lots of mass spam email by detecting their failed attempt RCPT. See my attached image.
![image](https://user-images.githubusercontent.com/17697663/57071018-5632a580-6d03-11e9-975a-d47217c54d0c.png)

I would like to ask whether it's possible to write the detected email (linh13@mydomain.net) user to a database file.. eg: /etc/postfix/sender_checks

```
linh13@mydomain.net     REJECT  Your account is spammer
```

My postfix configuration will block these users listed in /etc/postfix/sender_checks

I am looking forward to a solution. Thank you so much for your time.
Nghia Le

**Comment by sebres** [comment]
> it's possible to write the detected email user to a database file.. eg: /etc/postfix/sender_checks

What you've called "database file" looks like a simple text-file.
So beside of the ban-action  you need still one (at least with `actionban`/`actionunban`) which would write expected string to this file in `actionban` and remove this line in `actionunban`, and possibly somehow notify postfix e. g. reload configuration (if expected).

Take a look at [action.d/nginx-block-map.conf](https://github.com/fail2ban/fail2ban/blob/76f28658835aac152d4f850a7f43930b871e3b4c/config/action.d/nginx-block-map.conf#L106-L108) for example of action like this.

Unfortunately your failure-ID (in the related filter) is probably an IP, but your action (for postfix blacklisting) would expect an email as identifier.

So firstly (in order to catch the email) you should either extend the filter too, so for example:
```diff
-prefregex = ^%(__prefix_line)s<mdpr-<mode>> <F-CONTENT>.+</F-CONTENT>$
+prefregex = ^%(__prefix_line)s<mdpr-<mode>> <F-CONTENT>.+?from=(?:<<F-EMAIL>[^@>]+@[^>]+</F-EMAIL>>)?.+</F-CONTENT>$
```
Or may be some grep over the tag `<matches>` (which contains last failure messages) in your blacklisting action-file.

Your second problem would be the "counter" by email (for example two IPs could use the same e-mail, so if the first IP going unbanned, the line with an e-mail will be removed from your black-list (despite the second IP is still banned).

Your action `action.d/postfix-black-list.conf` may look like:
```ini
[Definition]
blck_lst_msg = <sp> REJECT  Your account is spammer
blck_lst_file = /etc/postfix/sender_checks
blck_lst_reload = ...postfix... -some-option-to-reload-blacklist

actionban = echo "<F-EMAIL> %(blck_lst_msg)s" >> '%(blck_lst_file)s'; %(blck_lst_reload)s

actionunban = id=$(echo "<F-EMAIL>" | sed -e 's/\W/\\&/g'); sed -i "/$id %(blck_lst_msg)s/d" %(blck_lst_file)s; %(blck_lst_reload)s
```
And in your jail.local you have to extend an action with an additional new action you did write:
```ini
[postfix]
...
action = %(action_)s
         postfix-black-list
```

Due to the problem with counter, maybe a complete new jail with another filter (based on rules with email as failure-ID) and a ban-action using blacklisting by email would be better in your case.
Exactly the same way it was doing in above mentioned `nginx-block-map.conf`.

So then your action `action.d/postfix-black-list.conf` may look like above, just replace `<F-EMAIL>` with `<fid>` (it is failure id now).
And your jail would be:
```ini
[postfix]
...

[postfix-black-list]
filter = postfix-black-list
action = postfix-black-list
enabled = true
```

I hope it provides enough food for thought...
*Neither I've a postfix to try or test something like this, nor I've time to implement that.*

**Comment by trongnghia203** [comment]
Hi @sebres , thank you very very much for your instruction.., I got the idea now. Let me try to make that test and update you the result... Many thanks!!!
