### ISSUE TITLE
Installing fail2ban 0.11 on FreeBSD with setup.py

### ISSUE THREAD

**Issue by quicktrick** [fail2ban/fail2ban#2415]
Hello!  I'm able to install `fail2ban 0.11` on FreeBSD with `setup.py` and get it working using the default Linux scheme of directories. Is it possible to do the same using FreeBSD scheme of directories?

I can see the installation options executing
```
python setup.py --help install
```
I tried to set some of those options but I did not get the desired result, because I did not understand their exact meaning.

Could anybody give me any examples of using those installation options?

Here is the FreeBSD fail2ban 0.10.4 package (repacked to zip) as an example of the directories scheme: [py36-fail2ban-0.10.4-e73d7f799e.zip](https://github.com/fail2ban/fail2ban/files/3145232/py36-fail2ban-0.10.4-e73d7f799e.zip)

**Comment by chtheis** [comment]
Am 05.05.2019 um 09:22 schrieb quicktrick:
> Hello! I'm able to install |fail2ban 0.11| on FreeBSD with |setup.py|
> and get it working using the default Linux scheme of directories. Is it
> possible to do the same using FreeBSD scheme of directories?

The FreeBSD port patches some of the install paths, so the answer is yes
and no :)

Current release of fail2ban is 0.10.4. 0.11 will come once this version
is officially released. If you want to try out before you can modify the
Makefile in security/py-fail2ban to use 0.11 instead. Some more tweaking
of the patches may be necessary.


Christoph Theis

**Comment by sebres** [comment]
Additionally there is basically no large difference between both versions as regards the setup procedure and configuration files, so one should be able pretty simple merge that.

Normally you can use setup option `--prefix=/usr/local`, but it may not affect configuration (/etc/fail2ban) and other paths.
Please see [Installing Python Modules / Custom Installation - Python documentation](https://docs.python.org/2/install/#inst-custom-install) for the other options.

If you are better familiar with makefile-builds, you could try to patch [Makefile](https://github.com/freebsd/freebsd-ports/blob/master/security/py-fail2ban/Makefile) for 0.11 usage.

Further in #2106 (in order to avoid the duplicates).

**Comment by quicktrick** [comment]
@chtheis , thanks for you answer.  As I mentioned in my first post, I'm able to install and to get working the version 0.11 on FreeBSD.  In fact, I have a working installation of v. 0.11 on one of my FreeBSD production servers.  Besides, I have been using v. 0.11 for quite a long time on a few dozens of Linux servers (with my own custom jails too). So I'm familiar with fail2ban.

@sebres 
Сергей, здравствуйте!  Мы с вами знакомы по переписке по поводу вашей давней статьи на Хабре.    Спасибо за ответ, я, видимо, так или иначе сделаю свой порт v. 0.11 для FreeBSD, у меня уже несколько серверов на ней, просто руки пока не дошли.  За ссылку спасибо!
