### ISSUE TITLE
Regex throws assertionError

### ISSUE THREAD

**Issue by billynoah** [fail2ban/fail2ban#2425]
Fail2Ban v0.10.4
Ubuntu 16.04.6 LTS

I added the following to the `cmdfailre` section of sshd.conf to ban clients attempting to connect without public ssh key:

`^Connection closed by <HOST> port \d+ \[preauth\]$`

Then testing as follows:

`fail2ban-regex /var/log/auth.log /etc/fail2ban/filter.d/sshd.conf`

Throws an error:

```
Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use         maxlines : 1
Use      datepattern : Default Detectors
Use         log file : /var/log/auth.log
Use         encoding : UTF-8

Traceback (most recent call last):
  File "/usr/local/bin/fail2ban-regex", line 34, in <module>
    exec_command_line()
  File "/usr/local/lib/python2.7/dist-packages/fail2ban/client/fail2banregex.py", line 698, in exec_command_line
    if not fail2banRegex.start(args):
  File "/usr/local/lib/python2.7/dist-packages/fail2ban/client/fail2banregex.py", line 648, in start
    self.process(test_lines)
  File "/usr/local/lib/python2.7/dist-packages/fail2ban/client/fail2banregex.py", line 482, in process
    assert(not is_ignored)
AssertionError
```

Oddly, everything works fine if I insert it just a few lines up just before this line

`^<F-NOFAIL>Connection <F-MLFFORGET>closed</F-MLFFORGET></F-NOFAIL> by%(__authng_user)s <HOST><mdrp-<mode>-suff-onclosed>`

**Comment by sebres** [comment]
This assert means that this line would be ignored by another regex in `failregex` via tag `<F-NOFAIL>` (means this is not a failure) or `ignoreregex`, and then it is unexpected if matched again via other regex.

As you can see this regex is already there, just it has 2 meanings:
- in `normal` mode it is as ignored (just as multi-line helper for other failures without IP in line, for the same multi-line ID)
- in `aggressive` or `ddos` mode it would match as failure.

Because it is not directly an authentication issue, It was "fixed" in 22d37cdce21a7200b82c432348ff725dabd5c28b for both modes `aggressive` or `ddos`, (see also #2185).

PoC:
```diff
  msg='1557836450 srv sshd[12538]: Connection closed by 192.0.1.2 [preauth]'
- fail2ban-regex "$msg" sshd
+ fail2ban-regex "$msg" sshd[mode=ddos]
...
- Lines: 1 lines, 1 ignored, 0 matched, 0 missed
+ Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```

Thus closed:
- either you would choose another mode in your jail.local (set it to `aggressive` or `ddos`).
```ini
[sshd]
mode = aggressive
```
- or if you want add only this line (remain `normal` regex's), rather insert it before or you have to remove the same line with `<F-NOFAIL>` tag additionally (but note this line would be also used as a helper for another failures without IP and it covering also states like connection closed but without `[preauth]`, this way fail2ban will find the IP for failures of the same session which does not contain IP within).
