### ISSUE TITLE
how to use IP as the string word by iptables？

### ISSUE THREAD

**Issue by loveyang2012** [fail2ban/fail2ban#2434]
Through SDN or Array devices, the real IP is in x_forward_for. Although the real IP is added to the firewall, it does not work. So I want to use the way that using firewall to ban the string, and  real IP as a string word. How to write this action?
I want to math like this：
iptables -I INPUT 1  -m string --string "117.29.46.95" --algo bm -j DROP
the “117.29.46.95” is the real IP.

**Comment by sebres** [comment]
And? Why this should be a fail2ban's issue? Looks to me as pretty 3rd party issue.

You can configure fail2ban to do everything you want (even to ban by user name or e-mail, see for example [wiki :: How to ban something other as host (IP-address), like user or mail, etc.](https://github.com/fail2ban/fail2ban/wiki/How-to-ban-something-other-as-host-(IP-address),-like-user-or-mail,-etc.). 
There are also already several actions like [nginx-block-map](https://github.com/fail2ban/fail2ban/blob/0.10/config/action.d/nginx-block-map.conf) which would allow you to ban it directly in the web-server.

[Here](https://stackoverflow.com/questions/825481/iptable-rule-to-drop-packet-with-a-specific-substring-in-payload) you can find the answer to your direct question.
So you'd be able to create your action similar iptables-multiport.
Just I don't think it is good idea at all, because it could be vulnerable (everyone can simulate proxy and so is able to inject on the forwarded IP) as well as the communication via HTTPS / HTTPv2.0 is encrypted, so for iptables it is like a binary and string match would simply not work.
