### ISSUE TITLE
apache [error]  script How to join iptables

### ISSUE THREAD

**Issue by tyit** [fail2ban/fail2ban#2435]
![image](https://user-images.githubusercontent.com/31933126/58549974-54df9480-823f-11e9-95f4-0505f25d4b97.png)

![image](https://user-images.githubusercontent.com/31933126/58550138-b56ed180-823f-11e9-90aa-84da501887d1.png)

![image](https://user-images.githubusercontent.com/31933126/58550204-d6cfbd80-823f-11e9-9485-fd5492c71ccb.png)

![image](https://user-images.githubusercontent.com/31933126/58550587-a2a8cc80-8240-11e9-934d-abb1a9285b7c.png)

Hi
```
[Wed May 29 16:05:51 2019] [error] [client 45.40.241.96] script '/xxx/xxx' not found or unable to stat
[Wed May 29 16:05:53 2019] [error] [client 45.40.241.96] File does not exist: /xxx/xxx/
```
How to join iptables ?

**Comment by sebres** [comment]
> How to join iptables ?

This has nothing with iptables... All the filter you seem to use expecting certain constellation.
For example `apache-noscript` expects certain pattern with file extensions like .asp or .exe etc.
And `apache-badbots` expects some known identifier (e.g. user agent).

Neither one not another filter match your example messages.
You can also use `fail2ban-regex` to test the filter (or failregex) would find failures in line or log-file (or journal).

I don't know which fail2ban version are you using (you has completely ignored our issue template).
For newest fail2ban-version (since 0.10) you can overwrite the parameter `script` like here:
```ini
[jail]
filter = apache-noscript[script="/\S+"]
```
<details>
<summary>Example of fail2ban-regex testing that ...</summary>

```
$ fail2ban-regex /tmp/file-with-test-messages 'apache-noscript[script="/\S+"]'

Running tests
=============

Use   failregex filter file : apache-noscript, basedir: .../fail2ban/config/
Use   filter options : {'script': '/\\S+'}
...

Lines: 2 lines, 0 ignored, 2 matched, 0 missed
```
</details>

Or you can try to write your own `apache-noscript.local` filter on basis of `apache-noscript.conf` with overwritten `script` parameter.

Or you can simply write your failregex for a jail...
Here is a jail which could work for you:
```ini
[my-jail]
filter =
__script = /\S+
failregex = ^\[\] \[error\] \[client <HOST>\] script '%(__script)s' not found or unable to stat
            ^\[\] \[error\] \[client <HOST>\] [Ff]ile (?:does not exist|not found or unable to stat): %(__script)s
...
enabled = true
```

Please note it would ban ALL missing or invalid request URLs, and it could be dangerous to do that: so better make the `script` pattern more precise and possibly increase `maxretry`. Otherwise be sure your web-site does not have some "broken" or missing references produced on the regular basis (you won't ban legitimate users). And additionally note there are another situations possible, for example like described in  https://github.com/fail2ban/fail2ban/pull/1070#issuecomment-113232258
