### ISSUE TITLE
Jail order in firewall

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#2454]
I use a custom chain for Fail2ban chains in iptables.
How can I put `recidive` before custom jails?

```
Chain fail2ban (1 references)
 pkts bytes target     prot opt in     out     source               destination
 1307 77155 f2b-apache-instant  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 80,443
 1307 77155 f2b-apache-combined  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 80,443
 122K   31M f2b-apache-default  all  --  *      *       0.0.0.0/0            0.0.0.0/0
 122K   31M f2b-recidive  all  --  *      *       0.0.0.0/0            0.0.0.0/0
 2229  116K f2b-courier-auth  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 25,465,587,143,993,110,995
 2110  110K f2b-courier-smtp  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 25,465,587
 1307 77155 f2b-horde  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 80,443
   38  1844 f2b-sshd-ddos  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 3033
   38  1844 f2b-sshd   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 3033
 121K   31M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```

**Comment by sebres** [comment]
Firstly, jail `recidive` is an atavism (parse a log fail2ban written by itself is a nonsense). Better use `bantime.increment` of 0.11.

But, back to the issue:
Of course you can rewrite your iptables-action (parameter `actionstart`) to grab some number of some chain (let say into var `i`) and then add it to the insert command as rulenum parameter:
```diff
+i=$(<iptables> -L <chain> --line-numbers -n | grep -Po '^\d+(?=\s+f2b-custom)')
-<iptables> -I <chain>...
+<iptables> -I <chain> $i ...
```
Just note since fail2ban 0.10 `actionstart` may be called on demand, so the sequence how your jails are started (and IPs get banned) and which chains initially available is undefined.
See #1742 for more info (either you have to set `actionstart_on_demand = false`, or use some "persistent" chain/rule number for better anchoring).

But all your jail's rules seem to be placed in `fail2ban` chain, which, I guess, is referenced in the `INPUT` chain.
This means you could put it to `INPUT` before your fail2ban chain, like:
```ini
[DEFAULT]
chain = fail2ban
...
[recidive]
chain = INPUT
rulenum = 1
# rulenum = `<iptables> -L <chain> --line-numbers -n | grep -Po '^\d+(?=\s+fail2ban)'`
action = %(known/action)[rulenum="%(rulenum)s"]
```
And amend `<rulenum>` after `-I <chain>` in `actionstart` of your action (default `iptables-allports`), e. g. overwrite it in `iptables-allports.local`.
This way fail2ban will insert recidive rule into INPUT chain at the head of the chain (as commented variant) or even at dynamic position of fail2ban chain (in commented variant) .

**Comment by szepeviktor** [comment]
Thank you. I consider `rulenum`

**Comment by sebres** [comment]
Waiting for a PR extending some basic actions with a `<rulenum>`. :)
