### ISSUE TITLE
High CPU Usage 

### ISSUE THREAD

**Issue by EnSeal** [fail2ban/fail2ban#2460]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.9.3
- OS, including release name/version: Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-1087-aws x86_64)
- [ ] Fail2Ban installed via OS/distribution mechanisms: Yes 
- [ ] You have not applied any additional foreign patches to the codebase : No 
- [ ] Some customizations were done to the configuration (provide details below is so): only added IPs to ignore

### The issue:
I noticed my CPU usage always run at 100%, when i checked my logs i noticed fail2ban sits at the top of my list  as seen in screenshot below 

![image](https://user-images.githubusercontent.com/18033246/53329070-a64c5080-38eb-11e9-91e0-49a58c528451.png)

![image](https://user-images.githubusercontent.com/18033246/53329133-cb40c380-38eb-11e9-99bc-a7832232e34a.png)

Please will appreciate any tips 
#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
I see already #2359 which was closed due to missing info.

Thus again:
- which jails are enabled? which log-files are affected/monitored?
- is jail `recidive` enabled? and which log-level is set by fail2ban?
- do you have some custom jails (or filters)? if so try to disable them one by one in order to find a culprit (e. g. use `fail2ban-client set <jailname> enabled false` to do it without restart);
- do you have some service (monitored by fail2ban) which logging persistently? and please provide how fast (e. g. how many log-lines per second);

Please note:
- similar issues like #2327 or https://github.com/fail2ban/fail2ban/issues/1843#issuecomment-321478474,etc (just [search by word "CPU"](https://github.com/fail2ban/fail2ban/issues?q=is%3Aissue+cpu) in issue list).
- our wiki, e. g. [Best practice](https://github.com/fail2ban/fail2ban/wiki/Best-practice) article;
- version 0.9 is old, better upgrade it to 0.10 or higher;

**Comment by sebres** [comment]
I'll close it now... Please provide more info to process the issue (we could then reopen it).
