### ISSUE TITLE
Enable IPv6

### ISSUE THREAD

**Issue by basti12203** [fail2ban/fail2ban#2475]
Hello,
I use fail2ban 0.10.2 on debian and have a local.conf in /etc/init.d/jail.d so far so good.
When i set banaction = iptables-ipset-proto4 in DEFAULT section only ipv4 is enabled. 
When i set banaction = iptables-ipset-proto6 only IPv6 is enabled.
I have try banaction6 but this does not work.
How can I set both on same time?

Thanks for any help.
Best Regards

**Comment by sebres** [comment]
> have a local.conf in /etc/init.d/jail.d so far so good.

Not really, because `/etc/init.d/jail.d` is unknown to me, and if you mean `/etc/fail2ban/jail.d` - it is a directory for single jails only.
You need to create a file `/etc/fail2ban/jail.local` to overwrite defaults (this is normally a replacement for `jail.conf` for all branches you need).

> When i set banaction = iptables-ipset-proto4 in DEFAULT section only ipv4 is enabled.

Right, there is no IPv6-support by this action.

> When i set banaction = iptables-ipset-proto6 only IPv6 is enabled.

Hmm... how you see that?

Normally `iptables-ipset-proto6` is an action banning both families of IPs.
If I test the action, I see:
```
# ban IPv4:
ipset create f2b-j-w-iptables-ipset hash:ip timeout 0
iptables -w -I INPUT -p tcp -m multiport --dports http -m set --match-set f2b-j-w-iptables-ipset src -j REJECT --reject-with icmp-port-unreachable
ipset add f2b-j-w-iptables-ipset 192.0.2.1 timeout 600 -exist
# ban IPv6:
ipset create f2b-j-w-iptables-ipset6 hash:ip timeout 0 family inet6
ip6tables -w -I INPUT -p tcp -m multiport --dports http -m set --match-set f2b-j-w-iptables-ipset6 src -j REJECT --reject-with icmp6-port-unreachable
ipset add f2b-j-w-iptables-ipset6 2001:db8:: timeout 600 -exist
```
And this is well correct in my opinion.

Also note since v.0.10, the `actionstart` is executed on demand, so the chain and ipset will be created by first ban per family (#1742).

Thus normally if you want to use iptables with ipset actions, it is enough to add in `/etc/fail2ban/jail.local`:
```ini
[DEFAULT]
banaction = iptables-ipset-proto6
banaction_allports = iptables-ipset-proto6-allports
```

So I'll close it as invalid unless more info provided.
If you get an error, please provide that.

**Comment by basti12203** [comment]
Ok sorry the wrong path is my mistake.

`/etc/init.d/fail2ban restart
[ ok ] Restarting fail2ban (via systemctl): fail2ban.service.
/etc/fail2ban# iptables -nvL
Chain INPUT (policy ACCEPT 11286 packets, 3322K bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REJECT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 0:65535 match-set f2b-recidive src reject-with icmp-port-unreachable
   24  1384 REJECT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 25,465,587 match-set f2b-exim src reject-with icmp-port-unreachable
   11   660 REJECT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 22 match-set f2b-sshd src reject-with icmp-port-unreachable

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 12605 packets, 4452K bytes)
 pkts bytes target     prot opt in     out     source               destination         

/etc/fail2ban# ip6tables -nvL
Chain INPUT (policy ACCEPT 105M packets, 108G bytes)
 pkts bytes target     prot opt in     out     source               destination         
  10M 5910M f2b-sshd   tcp      *      *       ::/0                 ::/0                 multiport dports 22

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 105M packets, 50G bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain f2b-sshd (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  10M 5910M RETURN     all      *      *       ::/0                 ::/0                

/etc/fail2ban# cat /etc/fail2ban/jail.local
[DEFAULT]
banaction = iptables-ipset-proto6
banaction_allports = iptables-ipset-proto6
`
As you can see iptables use ipset while ipv6tables use "normal" ip6tables chain.

**Comment by basti12203** [comment]
OK, it seems that there is something wrong with that Installation. I try to reinstall.

**Comment by sebres** [comment]
> As you can see iptables use ipset while ipv6tables use "normal" ip6tables chain.

Do you mean this one?
```
10M 5910M f2b-sshd tcp * * ::/0 ::/0 multiport dports 22
```

Either it is not yet really created (as I wrote above it is creating on demand) and what do you see here is a leak from previous (erroneous) run of fail2ban.
Or you simply use some another (or customized) action.

It looks like case 1 to me (some old leak), because as already said fail2ban's ban actions of 0.10 execute `actionstart` on demand, what mean the chain `f2b-sshd` should be never empty (still know, by first ban) - and corresponding your excerpt it is empty.

So stop fail2ban and manually remove all iptables and ip6tables entries starting with `f2b-*`.
The start it and manually try to ban some test IPv6 address:
```
fail2ban-client set sshd banip 2001:db8::1
```
And then take a look in your ip6tables...

Otherwise, provide result of parameters dump `fail2ban-client -d | grep sshd`.
