### ISSUE TITLE
	Jump to chain f2b-iptable-drop	remove protocol type

### ISSUE THREAD

**Issue by arnold-b** [fail2ban/fail2ban#2484]
Hello, 

how to call chain on any protocol. Not only on TCP.

i tried 
protocol = all in jail.local

it don´t have any function

But i have to submit that i don´t understand jail.local

why is there a entry 
[sshd]
protocol = all
enabled = true
action = iptables-allports[]
maxretry = 3

the definition for ssh i stored also in jaild

thanks arnold

**Comment by sebres** [comment]
> it don´t have any function

What does it mean? Does fail2ban.log contain some errors if banning?

Which fail2ban version?

Note also in 0.10 the iptables chains will be created on demand (by first ban only).

> action = iptables-allports

This is wrong: either you should set `banaction` instead of `action`, or you should specify all expected parameters an action required, see for example https://github.com/fail2ban/fail2ban/blob/5045c4bb00c522c3691e7e47a706c24d8950f58e/config/jail.conf#L212
