### ISSUE TITLE
Filter rule failing with monit 5.20.0

### ISSUE THREAD

**Issue by pierre-alain-b** [fail2ban/fail2ban#2494]
Hi there,

It seems that the filter for Monit does not work with Monit version 5.20.0. I think the regexp here is not good:
https://github.com/fail2ban/fail2ban/blob/15734a923b226cac53e9a9fd606efa58a7be009c/config/filter.d/monit.conf#L17

Here is the line I see in my /var/log/monit.log :
```
[CEST Aug  6 10:14:51] error    : HttpRequest: access denied -- client [192.168.1.85]: unknown user 'test'
[CEST Aug  6 10:14:52] error    : HttpRequest: access denied -- client [192.168.1.85]: wrong password for user 'root'
```

I have the feeling that the brackets are causing the issue, is this possible?
I fixed it for now by adding a new (simple and not perfect) regexp:
`access denied -- client \[<HOST>\]:`

**Comment by pierre-alain-b** [comment]
Seems to be again a change in Monit as in #1355

**Comment by sebres** [comment]
Since #2560 rewrites several replacement tags anyway, they are extended now there:
* grouped tags (`<ADDR>`, `<HOST>`, `<SUBNET>`) recognize enclosed in square brackets IP addresses of both families (so all filters would accept square brackets around IPv4 addresses also).

Unless it gets merged/released, one could use own replacement directly in jail:
```ini
[monit]
filter = %(known/filter)s[HOST="\[?<ADDR>\]?"]
```
