### ISSUE TITLE
Documentation newer than 0.8 available?

### ISSUE THREAD

**Issue by hoergen** [fail2ban/fail2ban#2507]
Sorry to open an issue here, but I'm searching now quite a while (days) to find a newer documentation than version 0.8.

Is there any resource that hosts a documentation 0.9x or newer? I couldn't find any.

**Comment by sebres** [comment]
Which kind of documentation exactly do you need?

Here is a short list (could help):
- [README - Installation](https://github.com/fail2ban/fail2ban#installation)
- [Wiki](https://github.com/fail2ban/fail2ban/wiki)
- Man-pages e. g. [online, jail.conf.5](https://manpages.debian.org/unstable/fail2ban/jail.conf.5.en.html)
- [Issues labeled as documentation](https://github.com/fail2ban/fail2ban/issues?utf8=%E2%9C%93&q=label%3Adocumentation)
- [Issues labeled as how-to](https://github.com/fail2ban/fail2ban/issues?utf8=%E2%9C%93&q=label%3Ahow-to)

And last but not least, google, [DGG](https://duckduckgo.com/?q=fail2ban+how+to&t=h_&ia=web), [SE, SO, SF](https://stackexchange.com/search?q=fail2ban), etc would surely help you too to clear every question you have about fail2ban :).

**Comment by hoergen** [comment]
Thanks, Ok  the only good documentations seems to be those rare 0.9x and higher howtos found with search engines. ;)

**Comment by sebres** [comment]
> and higher howtos found with search engines

Hmm... still again, which docu exactly do you need?
Or rather why our wiki/man-page is not enough for your purposes? Both are actual as regards the newest versions.

**Comment by hoergen** [comment]
There were some big changes from version 0.8 to version 0.9 . I noticed that after my last big debian server update and I was wondering, why there is no dedicated 0.9 documentation on the project website or on git. On the website there is still just the 0.8 official documentation that you can't really use, when you are installing the latest fail2ban documentation that is delivered with the major Linux distributions.

Personally I struggle at the moment with the apache-badbots configuration. I can't figure it out what I'm doing wrong so that bots like e.g. Semrush|AhrefsBot|MJ12bot|DotBot aren't blocked when they appear in the logs. Most of the other configuration is working with some tutorial search ;)  At the moment it's more like a trial&error session, than knowing what I have to do ;)

**Comment by sebres** [comment]
Well, if you are at level of "some filter does not work to me", I'm pretty sure no one documentation would help you here... excepting the common knowledge how fail2ban work, which you could find in our wiki (see link above) and/or [RE's are basically working](https://docs.python.org/3/library/re.html#regular-expression-syntax)...
Or even possibly the hints and inline docu if it is provided by developer in the filter-config itself.

I don't think the differences between 0.8 and 0.9 playing any role by such things. 
As well as whether some concrete "documentation" could be ever helpful at all in this case.
Rather a couple of many things, starting from description of the service you're trying to monitor and its log-format or the structure and ending with understanding of regex.

So to write own filter (or rewrite existing one), you need few things:
- certain knowledge how fail2ban-configs (especially filters) are build and how substitution works - wiki or man, e. g. [jail.conf.5](https://manpages.debian.org/unstable/fail2ban/jail.conf.5.en.html);
- minimal knowledge how regex's ([PCRE](https://docs.python.org/3/library/re.html#regular-expression-syntax)) are working and how failregex deviates from pure python regex/PCRE, which is also well described in [jail.conf.5](https://manpages.debian.org/unstable/fail2ban/jail.conf.5.en.html);
- rough handling with [fail2ban-regex](https://manpages.debian.org/unstable/fail2ban/fail2ban-regex.1.en.html) to test the regex or the filter.

But better you're really understand what you are doing. just... For example the subject regex-engine (so PCRE as it is, unrelated to fail2ban) is too complex to be possible to provide you some 1 page documentation describing that all (what some people learning decades).
I know many people using RE's in the wild several years... and doing it still wrongly (e. g. "vulnerable", doubtful or ambiguous, etc pp).

> At the moment it's more like a trial&error session, than knowing what I have to do ;)

Well, I assume, nobody would be able to help you, if you cannot formulate what you are actually trying to find, fix or extend.

**Comment by sebres** [comment]
And in answer to your unspoken question...
To extend apache-badbots to recognize `Semrush|AhrefsBot|MJ12bot|DotBot`...

1. In 0.9 it is enough to extend filter via `filter.d/apache-badbots.local`, e. g. something like this:
```ini
[Definition]
badbots = %(known/badbots)s|Semrush|AhrefsBot|MJ12bot|DotBot
```
2. Since 0.10 would be also enough to provide it even directly in your `jail.local`:
```ini
[apache-badbots]
filter = apache-badbots[badbots="<known/badbots>|Semrush|AhrefsBot|MJ12bot|DotBot"]
```
You can even test it directly with fail2ban-regex without filter modifications:
```
fail2ban-regex /path/to/your/apache-log 'apache-badbots[badbots="<known/badbots>|Semrush|AhrefsBot|MJ12bot|DotBot"]'
```

P.S. I don't like filters like this at all for many reasons, but if one really need it...

Also note #2378 (and also related issue #1950).

**Comment by hoergen** [comment]
Thanks a lot for your help and your infos 🚀🌻

I found out that the failregex in apache-badbots is wrong

It should be` failregex = ^<HOST> -.*compatible;.*(?:%(badbots)s|%(badbotscustom)s)`

Source: https://gauss-development.com/fail2ban/

**Comment by sebres** [comment]
> I found out that the failregex in apache-badbots is wrong
> It should be ...

Don't know what exactly should not match using original filter regex (don't have logs to check it).
But as already said, I don't like it... despite neither original, nor this regex are good in my opinion, because few precise and have to many catch-all's (what could cause too slow handling, especially by too large parasite log "traffic").

I don't use apache, but for example how I would do that if I had it - https://github.com/fail2ban/fail2ban/issues/2378#issuecomment-476140401.
So separate log conditionally (to split it out from parasite trafic / logged requests of legitimate users), simplify logging format, like addr and info expected for parse only, or at least place it at begin of message to avoid traverse over (possibly large) foreign input, optimized shorter regex with fewer branches etc pp.
And why at all do the checking for the bot-name (like a black-list), if it would be good enough to ban someone doing too many 301..404 requests (possibly with a white-list for some known agents or work cases)?
