### ISSUE TITLE
[Feature request] Add Monitorix support for the built-in HTTP server auth

### ISSUE THREAD

**Issue by borzaka** [fail2ban/fail2ban#2514]
# About Monitorix
[Monitorix](https://www.monitorix.org/) is a free, open source, lightweight system monitoring tool designed to monitor as many services and system resources as possible.

## Details
Since 3.0 version Monitorix includes its own HTTP server built in.
You can enable an authentication mechanism to control access to pages and other resources. The only allowed mechanism is Basic and uses the 401 status code and the WWW-Authenticate response header.

### Processes
```
root      13837  0.1  0.1  99836 40864 ?        Ss   12:18   0:02 /usr/bin/monitorix -c /etc/monitorix/monitorix.conf -p /run/monitorix.pid
monitorix 13867  0.0  0.1  98008 33400 ?        Ss   12:18   0:00 monitorix-httpd listening on 8080
```

### Port
8080

### Logfile
`/var/log/monitorix-httpd`

### Logfile with auth error examples:
```
Tue Aug 27 11:14:58 2019 - AUTHERR - [112.126.99.90] Authentication error: /TP/public/index.php
Tue Aug 27 11:14:59 2019 - AUTHERR - [112.126.99.90] Authentication error: /TP/index.php
Tue Aug 27 11:14:59 2019 - AUTHERR - [112.126.99.90] Authentication error: /thinkphp/html/public/index.php
Tue Aug 27 11:15:00 2019 - AUTHERR - [112.126.99.90] Authentication error: /html/public/index.php
Tue Aug 27 11:15:01 2019 - AUTHERR - [112.126.99.90] Authentication error: /public/index.php
Tue Aug 27 11:15:02 2019 - AUTHERR - [112.126.99.90] Authentication error: /TP/html/public/index.php
Tue Aug 27 11:15:03 2019 - AUTHERR - [112.126.99.90] Authentication error: /elrekt.php
Tue Aug 27 11:15:03 2019 - AUTHERR - [112.126.99.90] Authentication error: /index.php
Tue Aug 27 11:15:04 2019 - AUTHERR - [112.126.99.90] Authentication error: /users
Tue Aug 27 11:15:04 2019 - AUTHERR - [112.126.99.90] Authentication error: /
Tue Aug 27 11:15:39 2019 - AUTHERR - [184.105.247.196] Authentication error: /
Tue Aug 27 12:18:40 2019 - AUTHERR - [62.77.233.66] Authentication error: /monitorix
```

#### Exceptions:
There is a built in responsiveness checker, which checks that the server is still up, if it's not, it restarts. But it's not working fine with auth enabled, so it generates this errors:
```
Tue Aug 27 13:30:01 2019 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Tue Aug 27 13:31:00 2019 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Tue Aug 27 13:32:00 2019 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Tue Aug 27 13:33:01 2019 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
```
So maybe `127.0.0.1` should be white-listed.

### System I'am using:
Debian 10 "buster"

### Current fail2ban version:
`Fail2Ban v0.10.2`

I would be very happy, if someone could make me a filter in advance with the correct regex and other settings to make this work. Thanks.

**Comment by sebres** [comment]
You don't need a filter for that (if only simple regex is expected).

Here is an example for a jail:
```ini
[monitorix]
filter = 
failregex = ^\s* \S+ AUTHERR \S+ \[<ADDR>\] Authentication error
logpath = /var/log/monitorix-httpd
port = 8080
enabled = true
```
<details>
<summary>PoC</summary>

```
$ msg='Tue Aug 27 11:14:58 2019 - AUTHERR - [112.126.99.90] Authentication error: /TP/public/index.php'
$ fail2ban-regex "$msg" '^\s* \S+ AUTHERR \S+ \[<ADDR>\] Authentication error'

Running tests
=============

Use   failregex line : ^\s* \S+ AUTHERR \S+ \[<ADDR>\] Authentication error
Use      single line : Tue Aug 27 11:14:58 2019 - AUTHERR - [112.126.99.9...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^\s* \S+ AUTHERR \S+ \[<ADDR>\] Authentication error
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```
</details>

Just as some other http-servers, it can also write an Authentication error in first request (in case the user is still not yet authorized).
So to avoid a mistakenly detection of legitimate authentication attempt I would check how the negotiation process (handshake) is looking here, resp. how the first request deviates from following (e. g. username is logged there).
Otherwise you'd increase `maxretry` to avoid ban of legitimate users.

**Comment by sebres** [comment]
> So maybe 127.0.0.1 should be white-listed.

Localhost (as well as its remote addresses) is ignored by `ignoreself` (true per default).
If you want to ignore another IPs, you can use `ignoreip = <ip1> <ip2> ... <ipN>`

**Comment by borzaka** [comment]
Thank you very much! It's working.

A rescan of the entire log file for this new jail would be nice. I followed your instructions in the #1682 issue, but with no luck;
1. I stopped fail2ban, deleted database (`/var/lib/fail2ban/fail2ban.sqlite3`), started fail2ban.
Positions of the logs were resetted to 0, but no bans were added after this, only new founds can be seen in the log.
`Added logfile: '/var/log/monitorix-httpd' (pos = 0, hash = ed38e974a023aaef5e104f87ffa8b4406c1c60b7)`
I had already many `sshd` jail bans, which are missing now. And no `monitorix` jail bans from the past.
So no re-parsing happened in this case.
2. Deleted logpath for `monitorix` and readded. Restarted server.
`$ fail2ban-client set monitorix dellogpath /var/log/monitorix-httpd`
`$ fail2ban-client set monitorix addlogpath /var/log/monitorix-httpd`
But the pos is not 0 in this case:
`Added logfile: '/var/log/monitorix-httpd' (pos = 3300417, hash = ed38e974a023aaef5e104f87ffa8b4406c1c60b7)
`
I have tried with `head` option, but it's the same, even if it's the default value in `addlogpath`.
No re-parsing happened in this case either.

Is there a new way or rescanning logs from the beginning for a specific jail?

**Comment by sebres** [comment]
Fail2ban will scan only `now - findtime` interval (in order to find `maxretry` attempts per IP) and ban only tickets which are not older as `endofban = timeOfLastAttempt + bantime`.

So you can do that (of course together with reset of position or `head`) if your `findtime` and `bantime` are long enough.

> A rescan of the entire log file for this new jail would be nice.

Why?! 
If the intruders are still active they will be banned after new `maxretry` attempts.
Otherwise they are anyway not interesting anymore.

**Comment by borzaka** [comment]
I understand your point of view. I just don't wanted to give them another chance to try on other services/methods.

Thank you so much again for your help!

**Comment by nchebotarev** [comment]
hello guys i am seeing a very similar issue in my log `/var/log/monitorix-httpd` 

```
Mon Mar  7 10:26:01 2022 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Mon Mar  7 10:27:01 2022 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Mon Mar  7 10:28:00 2022 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Mon Mar  7 10:29:01 2022 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Mon Mar  7 10:30:01 2022 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Mon Mar  7 10:31:00 2022 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Mon Mar  7 10:32:00 2022 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Mon Mar  7 10:33:01 2022 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
Mon Mar  7 10:34:01 2022 - AUTHERR - [127.0.0.1] Authentication error: /monitorix
```

I use Monitorix version 3.14.0 on ubuntu 20.04 and I have authorization enabled in monitorix. Could you help me to solve this problem?

**Comment by slrslr** [comment]
I suspect that if Monitorix is accessed via:
http://hostname:8080/monitorix-cgi/monitorix.cgi?mode=localhost&graph=all&when=1day&color=black
for some reason it loads tens of various page elements:
```
/var/log/monitorix-httpd:Fri May 19 11:00:10 2023 - AUTHERR - [yourIP] Authentication error: /monitorix/imgs/user3.1day.png
/var/log/monitorix-httpd:Fri May 19 11:00:10 2023 - AUTHERR - [yourIP] Authentication error: /monitorix/imgs/int2.1day.png
/var/log/monitorix-httpd:Fri May 19 11:00:10 2023 - AUTHERR - [yourIP] Authentication error: /monitorix/imgs/user1.1day.png
```
and maybe @sebres mentioned jail thinks that there is so many failure attempts and ban valid user - i do not know, but it blocked my IP as a result:
```
2023-05-19 10:57:00,655 fail2ban.filter         [1285]: INFO    [monitorix] Ignore 127.0.0.1 by ignoreself rule
2023-05-19 10:58:02,233 fail2ban.filter         [1285]: INFO    [monitorix] Ignore 127.0.0.1 by ignoreself rule
2023-05-19 10:58:03,084 fail2ban.filter         [1285]: INFO    [monitorix] Found yourIP - 2023-05-19 10:58:03
2023-05-19 10:58:09,355 fail2ban.filter         [1285]: INFO    [monitorix] Found yourIP - 2023-05-19 10:58:09
2023-05-19 10:58:09,367 fail2ban.filter         [1285]: INFO    [monitorix] Found yourIP - 2023-05-19 10:58:09
2023-05-19 10:58:09,385 fail2ban.filter         [1285]: INFO    [monitorix] Found yourIP - 2023-05-19 10:58:09
2023-05-19 10:58:09,413 fail2ban.filter         [1285]: INFO    [monitorix] Found yourIP - 2023-05-19 10:58:09
2023-05-19 10:58:09,433 fail2ban.filter         [1285]: INFO    [monitorix] Found yourIP - 2023-05-19 10:58:09
2023-05-19 10:58:09,446 fail2ban.actions        [1285]: NOTICE  [monitorix] Ban yourIP
```

my jail.conf
```
bantime  = 10m
findtime  = 10m
maxretry = 5
maxmatches = %(maxretry)s
...
[monitorix]
# is banned valid visit
filter =
failregex = ^\s* \S+ AUTHERR \S+ \[<ADDR>\] Authentication error
logpath = /var/log/monitorix-httpd
port = 8080
enabled = failse
```

# apt info monitorix
Package: monitorix
Version: 3.12.0-2 (3.15 seems to be the latest: https://www.monitorix.org/downloads.html )

**Comment by sebres** [comment]
> and maybe @sebres mentioned jail thinks that there is so many failure attempts and ban valid user - i do not know

No. I meant a bit different issue (which can be true here if monitorix logs every 401th attempt, also initial "handshakes" access without a user name).

But yes, jail sees `maxretry` failures from IP during the `findtime`, so it'd ban the IP.

> but it blocked my IP as a result

Well, it looks like monitorix generates an authentication issues by static files (like images in `/monitorix/imgs/*`), what is very strange... 
This is a ugly situation, because one can't really increase a `maxretry` in hope to circumvent mistaken failure counting, since an evildoer does the bruteforce mostly from automated scripts or bots, which allow to target only main url to authenticate, so legitimate users would generate 5 failures by single authentication attempt, whereas the bot is able to generate 1 failure for every attempt.
Filtering of URL is also bad idea (for example with negative lookahead `Authentication error: /monitorix(?!/imgs/)`) because probably the evildoer will be able to use any URL to affect HTTP authentication, also those images, so if they will be filtered out - he'd continue the attack invisibly.
I don't know how one can solve the issue without to change authentication mechanism or the logging behavior by auth-failures on monitorix side.
If you use some proxying server (like nginx), then you could monitor its log instead of monitorix (as well as disable logging for static files).
