### ISSUE TITLE
Adding ban jail /filter name to Cloudflare note?

### ISSUE THREAD

**Issue by utags** [fail2ban/fail2ban#2518]
Hi all,

Is it possible to add each banned IP address triggered relevant filter name/jail name to cloudflare IP Access Rules notes? At this moment it only shows "Fail2ban". 

```
actionban = curl -s -X POST "https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules" \
            -H "X-Auth-Email: <cfuser>" \
            -H "X-Auth-Key: <cftoken>" \
            -H "Content-Type: application/json" \
            --data '{"mode":"block","configuration":{"target":"ip","value":"<ip>"},"notes":"**Fail2ban**"}'
```

**Comment by sebres** [comment]
> At this moment it only shows "Fail2ban".

I don't know where your cloudflare action actually coming from. 
Because current stock action doesn't provide it at all:
https://github.com/fail2ban/fail2ban/blob/d01fe9d22a717a0122143cde41ce5c18a1790f6e/config/action.d/cloudflare.conf#L46-L48

But as I can see PR #2140 implement exactly what you propose here.
Thus I'll close it to avoid duplicates.

But of course you can extend your (custom) action like here:
```diff
- ... ,"notes":"**Fail2ban**"
+ ... ,"notes":"**Fail2ban** <name>"
```
