### ISSUE TITLE
explanation of log levels

### ISSUE THREAD

**Issue by pieter-groeneweg** [fail2ban/fail2ban#2547]
Good morning,

I have been searching for half a day now but cannot seem to find the explanation of all "LOG LEVELS". I may have overlooked or misphrased my search in Google. I am looking for explanation of the log levels by fail2ban.

Of course I am not to troubled about INFO and NOTICE levels, but going up from WARNING starts to trigger me to action...

In my logs I can find lines like:
```
WARNING Determined IP using DNS Lookup: static-xxx-xxx-xxx-xxx.subsub.sub.domain.com = ['xxx.xxx.xxx.xxx']
```
No ERRNO -x
```
WARNING Unable to find a corresponding IP address for iptables-allports[]: [Errno -5] No address associated with hostname
WARNING Unable to find a corresponding IP address for iptables-allports[]: [Errno -2] Name or service not known
```
With ERRNO -x

Is there a list explaining all error level messages? If not, what do the above mean? I assume the last two warnings are almost similar but still....

Using webmin/virtualmin with fail2ban 0.9.6 on CentOS 6

Thank you,

**Comment by sebres** [comment]
> WARNING Determined IP using DNS Lookup: 

This warning is caused by `usedns = warn` (default) and tell you the hostname (and not an IP) was found by `<HOST>` matching message, and a reverse lookup was used there. 
If you don't want to see this warning, specify `usedns = yes` for jails or default.

> No ERRNO -x
> With ERRNO -x

No idea what do you mean with ERRNO, but...

> Unable to find a corresponding IP address for iptables-allports

can mean that something is wrong with your configuration, for example you'll see this message if `ignoreip` would contain `iptables-allports`, what is worse, because it should be white-space separated list of IPs or hostnames (in newer versions comma supported), and I guess `iptables-allports` is not valid value. :)

**Comment by pieter-groeneweg** [comment]
ERRNO -x appears to be a series 1 to ?  of possible Errors in fail2ban.. 

And thanks for the direction to ignoreip... the .local had a typo causing this.. fixed that! Tx
