### ISSUE TITLE
Errno -2: WARNING Unable to find a corresponding IP address for... before properly banning IP

### ISSUE THREAD

**Issue by Montclair** [fail2ban/fail2ban#2549]
### Environment:
- Fail2Ban version (including any possible distribution suffixes):
Fail2ban v0.8.11

- OS, including release name/version:
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

Fail2Ban is issuing "WARNING Unable to find a corresponding IP address for BAN: [Errno -2] Name or service not known" before properly banning the IP.  Specifically, we're getting the following in our log files:
```
2019-10-20 15:54:03,593 fail2ban.filter : WARNING Unable to find a corresponding IP address for BAN: [Errno -2] Name or service not known
2019-10-20 15:54:04,063 fail2ban.actions: WARNING [blt-instablock] Ban 27.202.61.210
```
This was all working fine, and we made no changes to any configurations. We did have to restart the fail2ban service when it unexpectedly quit a few weeks ago, but that's about it. We didn't specifically notice these messages before that, but they may have been there.

Here's the filter for this:
```[Definition]
failregex = .*\[<HOST>\] \[BAN\]
ignoreregex = 
```
#### Expected behavior
No error message.

#### Any customizations done to /etc/fail2ban/ configuration
```
[blt-block-dos]
enabled  = true
filter   = blt-block-dos
port     = http,https
logpath  = /var/log/apache2/f2bmonitor.log
maxretry = 50
findtime = 5
bantime  = 604800  ; 1 week
# action   = iptables[name=HTTP, port=http, protocol=tcp]
# use default banning action specified above instead

[blt-instablock]
enabled  = true
filter   = blt-instablock
port     = http,https
logpath  = /var/log/apache2/f2bmonitor.log
# if any hack attempt from noted in f2bmonitor.log as [IP] [BAN]
# then ban them for a month
maxretry = 1 ; if any hit
findtime = 86400 ; in 1 day
bantime  = 2678400 ; ban for a month
# action   = iptables[name=HTTP, port=http, protocol=tcp]
# use default banning action specified above instead

[blt-ban-403]
enabled  = true
filter   = blt-ban-403
port     = http,https
logpath  = /var/log/apache2/error_log
# if 15 403's given in one day
maxretry = 15 ; if fifteen 403's
findtime = 86400 ; in 1 day
bantime  = 2678400 ; ban for a month
# action   = iptables[name=HTTP, port=http, protocol=tcp]
# use default banning action specified above instead
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_
```
2019-10-20 15:51:05,745 fail2ban.actions: WARNING [blt-instablock] Unban 94.23.208.174
2019-10-20 15:54:03,593 fail2ban.filter : WARNING Unable to find a corresponding IP address for BAN: [Errno -2] Name or service not known
2019-10-20 15:54:04,063 fail2ban.actions: WARNING [blt-instablock] Ban 27.202.61.210
2019-10-20 16:09:15,268 fail2ban.actions: WARNING [blt-ban-403] Ban 54.88.117.2
```

#### Relevant lines from monitored log files in question:
```
[2019-10-20 15:53:24] [196.19.205.119]
[2019-10-20 15:54:03] [27.202.61.210] [BAN]
[2019-10-20 15:55:08] [38.132.194.61]
```

fail2ban-client -d | grep 'blt-instablock' returns this
```
['add', 'blt-instablock', 'auto']
['set', 'blt-instablock', 'usedns', 'warn']
['set', 'blt-instablock', 'addlogpath', '/var/log/apache2/f2bmonitor.log']
['set', 'blt-instablock', 'maxretry', 1]
['set', 'blt-instablock', 'addignoreip', '127.0.0.1/8']
['set', 'blt-instablock', 'addignoreip', 'IP removed for privacy']
['set', 'blt-instablock', 'addignoreip', 'IP removed for privacy']
['set', 'blt-instablock', 'addignoreip', 'IP removed for privacy']
['set', 'blt-instablock', 'addignoreip', 'domain removed for privacy']
['set', 'blt-instablock', 'findtime', 86400]
['set', 'blt-instablock', 'bantime', 604800]
['set', 'blt-instablock', 'addfailregex', '.*\\[<HOST>\\] \\[BAN\\]']
['set', 'blt-instablock', 'addaction', 'iptables-allports']
['set', 'blt-instablock', 'actionban', 'iptables-allports', 'iptables -I fail2ban-<name> 1 -s <ip> -j <blocktype>']
['set', 'blt-instablock', 'actionstop', 'iptables-allports', 'iptables -D <chain> -p <protocol> -j fail2ban-<name>\niptables -F fail2ban-<name>\niptables -X fail2ban-<name>']
['set', 'blt-instablock', 'actionstart', 'iptables-allports', 'iptables -N fail2ban-<name>\niptables -A fail2ban-<name> -j RETURN\niptables -I <chain> -p <protocol> -j fail2ban-<name>']
['set', 'blt-instablock', 'actionunban', 'iptables-allports', 'iptables -D fail2ban-<name> -s <ip> -j <blocktype>']
['set', 'blt-instablock', 'actioncheck', 'iptables-allports', "iptables -n -L <chain> | grep -q 'fail2ban-<name>[ \\t]'"]
['set', 'blt-instablock', 'setcinfo', 'iptables-allports', 'blocktype', 'REJECT --reject-with icmp-port-unreachable']
['set', 'blt-instablock', 'setcinfo', 'iptables-allports', 'protocol', 'tcp']
['set', 'blt-instablock', 'setcinfo', 'iptables-allports', 'name', 'blt-instablock']
['set', 'blt-instablock', 'setcinfo', 'iptables-allports', 'chain', 'INPUT']
['set', 'blt-instablock', 'setcinfo', 'iptables-allports', 'port', 'http,https']
['start', 'blt-instablock']
```

**Comment by sebres** [comment]
Firstly fail2ban v.0.8 is outdated already several years.

> `Unable to find a corresponding IP address for BAN`

Fail2ban can ban host by the hostname (`<HOST>` matches IPs and hostnames)... 
This message means that your regex seems to have found a match for `BAN`.
Either you should disable `usedns` (no idea it is possible and will work with 0.8), or you have to write more precise regex - for example `\[<HOST>\] \[BAN\]` is too vulnerable.

And better upgrade your fail2ban to supported version.

**Comment by Montclair** [comment]
This is the only version supposedly officially supported by the OS distribution. I see no upgrades available for this listed from the trusty repositories. I hate linux so I'm probably doing something wrong there.

Regardless, this doesn't  address why this regex worked just fine and now is generating error messages. I don't recall ever seeing this before in the logs, and would have noticed after the extensive testing that it went through.

I just don't know if it cropped up before the service restart, or after.

**Comment by sebres** [comment]
Still again, v.0.8 is tooooo old, so neither I know what exactly can be wrong there, nor I've time for experiments with this old version.
But I cannot remember such bugs even with this old version, so I'm pretty sure you've in your log something like:
```
... [BAN] [BAN] ...
```
otherwise the regexp (you provided) would simply not match.

This can mistakenly happen if the logger of your program has a bug, so for example it writes into the log-file without lock/flush (if line buffered) multi-threaded (e. g. two threads/process would write ` [BAN]` simultaneously) and then produce something like:
```diff
-[2019-10-20 15:54:03] [192.0.2.1] [BAN]
-[2019-10-20 15:54:03] [192.0.2.2] [BAN]
+[2019-10-20 15:54:03] [192.0.2.1] 
+[2019-10-20 15:54:03] [192.0.2.2] [BAN] [BAN]
```
And your RE with greedy catch-all `.*` find match for `... [BAN] [BAN]`, 
where:
- `...` matched by `.*`
- first `[BAN]` - `\[<HOST>\]` 
- and second `[BAN]` - `\[BAN\]`.

> can you provide me with one that matches the simple log file?

Although if I were you, firstly I'd try to fix the bug on the logger side, but...
According your log excerpt, more precise regex (anchored and no catch-all) would be:
`^\[\]\s+\[<HOST>\]\s+\[BAN\]`
(Note fail2ban cut timestamp out before it searches for failregex.)

PoC:
```
fail2ban-regex -v '[2019-10-20 15:54:03] [192.0.2.1] [BAN]' '^\[\]\s+\[<HOST>\]\s+\[BAN\]'
...
Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^\[\]\s+\[<HOST>\]\s+\[BAN\]
|      192.0.2.1  Sun Oct 20 15:54:03 2019
`-
...
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```

And since v.0.10 you could use `<ADDR>` (or `usedns = no` in jail and `<HOST>` in regex) to match IP address only.

**Comment by Montclair** [comment]
There's no ...[BAN] [BAN]... in the log file anywhere, so I don't know what to tell you there.

However, I'll try your regex's and report back soon. Thank you for the help.

**Comment by sebres** [comment]
> There's no ...[BAN] [BAN]... in the log file anywhere, so I don't know what to tell you there.

Well, normally `[BAN] [BAN]` is only one thing in log, that could explain a match for `.*\[<HOST>\] \[BAN\]` at all, which could then lead to `Unable to find a corresponding IP address for BAN`.

Anything else would make no sense... Of course 0.8 is too old and I can not put my hand into fire that there is no bug causing that (just it'd be unknown to me), but also 0.8.11 seems to have "safe" RE for `<HOST>`, see 
https://github.com/fail2ban/fail2ban/blob/0a02cfe9e8e65e68ec438bcd1c10fb7493f3e842/server/failregex.py#L44

Still one were wrong `ignoreip` (e. g. if you had `BAN` specified there. but your excerpt of dump for the jail does not show me that, unless you've not this in some other jail or removed/replaced it with `IP removed for privacy`, see dump in your issue), so better double check it within dump of
`fail2ban-client -d | grep 'ignoreip.*BAN'`

**Comment by Montclair** [comment]
`fail2ban-client -d | grep 'ignoreip.*BAN'` results in nothing. 

I'll try your regexes and report back when I have a chance. Thank you!

**Comment by Montclair** [comment]
It's been almost a year, but I am back to report that `^\[\]\s+\[<HOST>\]\s+\[BAN\]` made no difference. I still get the error.

Can you advise how to upgrade the product when there are no updates listed in the trusty repositories for Ubuntu 14?

**Comment by sebres** [comment]
> I still get the error.

Did you really expect that some package would be upgraded for distribution that was released 2014?
Let alone 14.04 LTS reaches end of life on April 30, 2019. Just after next version released, it received security patches and critical fixes only.

> Can you advise how to upgrade the product

Well, you have few options:
1. either upgrade your obsolete distribution (this is actually the proper way);
2. or install it from some distribution having new version of that, for example from [neurodebian](http://neuro.debian.net/install_pkg.html?p=fail2ban).
But I guess you have to use some newest distribution as 14.04 for that (and set pinning priority lower than your default repositories), see the [versions for package fail2ban on neurodebian](https://neuro.debian.net/pkgs/fail2ban.html)
So possibly firstly read [How can I run Debian stable but install some packages from testing? - Server Fault](https://serverfault.com/questions/22414/how-can-i-run-debian-stable-but-install-some-packages-from-testing)
3. or download some newest deb-package for debian/ubuntu and install it using `sudo dpkg -i fail2ban.deb` (after you uninstalled your original version).
4. or install it from source (see README file how to do that) using current stable branches or releases from github (also firstly uninstall your old version).

But I would not recommend variants 2. to 4. if you're not familiar with linux environment (cannot revert your changes).

Anyway, also if it gets installed successfully, you have to control all default settings like `logpath`, `backend`, `banaction` or `port` for all active (enabled) jails (and overwrite it in jail.local), because they may differ in newest distributions.

**Comment by Montclair** [comment]
> Did you really expect that some package would be upgraded for distribution that was released 2014?
> Let alone 14.04 LTS reaches end of life on April 30, 2019. Just after next version released, it received security patches and critical fixes only.

Not sure if you've ever run a live, active, e-commerce server or not, but if it's doing what it's supposed to do, you don't go upgrading the OS.  Once you have a server stable, and working properly, in my 40 years of experience, it's best to not go upgrading the OS just because a few applications don't support it.  It's actually rather comical that you don't support a 6 year old OS.  XP was supported in one form or another for almost 20 years by Microsoft, and most of the software was as well for about 15 years.

In practice, when a significant number of updates aren't available, we'll migrate the site to another server, upgrade that offline, and go from there.

Regarding the bug in your program, the error message itself appears to be the bug as the IP is still banned -- so it's doing what it's supposed to do, but reporting an error that doesn't really exist.  Thanks for the replies, though. I appreciate them.

**Comment by sebres** [comment]
> a live, active, e-commerce server ... you don't go upgrading the OS.

How so, if support for this OS is expired?

> It's actually rather comical that you don't support a 6 year old OS.

We don't "support" something at all.

Firstly, core fail2ban has only dependencies to few OS things (mostly modular) and only few prerequirements like python 2.6 (right now) for the latest fail2ban version. But for example if you'd consider #2690 and others, you'd notice that some people want completely reject 2.x python support (and also possibly that I'm still against such measures right now for several reasons).

Secondly, this is solely the matter of @fail2ban/maintainers of specific distribution, which also have to follow certain rules that are valid there for upgrade of software or by release of some version.

Thirdly, you can use newest fail2ban versions on 20 year old OS (if the requirements are fulfilled), but the preconfigured settings that have been made by maintainers for you (in distribution package) are either not available in stock version, or (if coming for new distribution) may be not valid for your distro.

And last but not least, this is open source, so does not necessarily imply warranty at all. As well as (you'd surely understand that) we doing this on the side, off the job, so in a finite time that we can invest in the project development, it'll be doomed to fail if we'll fix every bug in every old version.

**Comment by sebres** [comment]
Back to your issue (regardless the old version, which working details or particularities may be unknown to me)...

1. I already told you, that the warning `Unable to find a corresponding IP address for BAN ...` can only happen if token `<HOST>` matching word `BAN` instead of IP address.
2. this is possible only:
  a) either if your regex is not precise enough (because `<HOST>` can match host name also) and `usedns` is on (no idea whether 0.8 has this option at all to disable it);
  b) or word `BAN` is really found in log at the place, where you'd normally expect the IP address (with other words, RE allows that). For example take a look for similar issue #2766. In this case you should notice something like that:
```
# normal logging scenario (lines logged buffered/atomically):
2020-02-09 18:00:01 BAN 192.0.2.1
2020-02-09 18:00:01 BAN 192.0.2.2

# invalid logging scenario (content of lines "mixing" in between):
2020-02-09 18:00:02
2020-02-09 18:00:02 BAN BAN
192.0.2.1
192.0.2.2
```
Such logging is really worse practice and possible solution for that is described in https://github.com/fail2ban/fail2ban/issues/2766#issuecomment-650199529.
