### ISSUE TITLE
how to make a filter ?

### ISSUE THREAD

**Issue by bigalownz** [fail2ban/fail2ban#2564]
Im trying to make a filter that will block HTTP/1.0 request

I have tried this
```ini
[Definition]

failregex = ^< HOST > - - \[[^]]+\] "GET / HTTP/1.0"

ignoreregex =
```
but that does not work any ideas ?
thanks

**Comment by sebres** [comment]
<sub>Why some people thinking their time were more expensive as our...</sub>

Firstly you've completely disregarded our issue template.
At least a log-line example would be helpful.

Secondly, there is no "does not work" in IT world - you could provide more precise error message or explain what happens at the moment.

I assume you should write `<HOST>` and not `< HOST >`, but it is too obvious somehow.

Thus closed unless more info provided.

**Comment by bigalownz** [comment]
sorry I'll re edit my question

OS used ubuntu 18.04
fail2ban 0.10.4 (installed from github)

this is not a issue but a how to question

In my server logs I am getting request using http/1.0 all of the request are from bad bots
eg: 
x.x.x.x - - [08/Nov/2019:12:00:00 +1200] "GET / HTTP/1.0" 301 618 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)"

I want to block these request

I have made a filter called bots.conf with the following


```
[Definition]

failregex = ^<HOST> - - \[[^]]+\] "GET / HTTP/1.0"

ignoreregex =

```

in jail.conf i have added the following 

```
[bots]
enabled   = true
port      = http,https
filter    = bots
logpath  = %(apache_access_log)s
maxretry = 1
```
and restarted fail2ban

but the filter is not banning the HTTP/1.0 requests

Can some one help me out
thanks

**Comment by sebres** [comment]
This is pretty simple - part `\[[^]]+\]` expects at least one char inside the brackets, but fail2ban cut part matching `datepattern` out from message before applying of the failregex search. 
So change it to `\[[^]]*\]` or even just `\[\]` and it'll work.

Just think about the "intruder" can use other methods as GET (POST, PUT, HEAD or even OPTIONS), other HTTP proto's as well as some login-name (also if no password required and it's allowed by web-server), so something like this were better and enough:
```ini
# set `url = \S+` to allow capturing all requests:
url = /
code = (?!20)\d+
# failregex = ^<HOST> \S+ \S+ \[\] "[A-Z]+ / [^"]*" (?!20)\d+
failregex = ^<HOST> \S+ \S+ \[\] "[A-Z]+ %(url)s [^"]*" %(code)s
```
Also note `(?!20)\d+` at end of RE - it'd ignore all requests responded with codes 20x (e.g. 200 - OK).

**Comment by bigalownz** [comment]
thanks for your help

for some reason that did not bock the http/1.0 request

i also tried a few things like

```
[Definition]

failregex = ^<HOST> - - .* "(GET|POST) .* HTTP/1.0"

ignoreregex =

```

```
[Definition]

failregex  = ^<HOST> - - (?:\[[^]]*\] )+\"(GET|POST) / HTTP/1.0"

ignoreregex =
```
but these did not block http/1.0 request

**Comment by sebres** [comment]
What exactly does mean "did not block"?

- do you see `[bots] Found 192.0.2.1` or `[bots] Ban 192.0.2.1` in the log for some IP?
- do you see any error in log?
- check your banaction and corresponding firewall (net-filter) are working.

Also check the FAQ in our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works).

**Comment by bigalownz** [comment]
it does block but only blocks normal request

eg:

`x.x.x.x.x - - [10/Nov/2019:22:47:06 +1000] "GET / HTTP/1.1" 200 20099 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36"`



`x.x.x.x.x - - [06/Nov/2019:08:11:31 +1100] "GET /tag/charlotte-angel/ HTTP/1.1" 200 14635 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
`

it is blocking HTTP/1.1 request
I only want HTTP/1.0 blocked

**Comment by sebres** [comment]
**Still again: what do you see exactly?**
And I mean - in fail2ban logs, in firewall (related to your banaction), in net-filter rules (iptables) etc pp. And not - "it does not block", this is not helpful at all.
Because you disclosed nothing till now, I should guess what happens on your side...

So again: for example you see http1.0 request from 192.0.2.1 in your web-server log.
If you see `[bots] Found 192.0.2.1` in fail2ban.log your filter (failregex) works properly.
Do you see `[bots] Ban 192.0.2.1` in fail2ban.log for those (HTTP 1.0) IPs too?
Because RE looks good, I assume yes, but somehow banaction seems not to work for those. And you see also `already banned` if they repeat requests?..
If so it could be some white-listing rules in firewall (before fail2ban's rules) for already established connections (see https://github.com/fail2ban/fail2ban/issues/2545#issuecomment-543087971 and below) and due to keep-alive they can repeat their requests unless disconnected from server.

If don't, see again in FAQ of our wiki (see link above) from scratch, whether you can find some reason affected you.
We are not shamane and don't understand what this or that star constellation means.

**Comment by bigalownz** [comment]
OS used ubuntu 18.04
fail2ban 0.10.4 (installed from github)
apache2 (2.4.29-1ubuntu4.11
iptables (1.6.1-2ubuntu2)

i did a fresh install of fail2ban 0.10.4
jail.conf is default
added new filter called ban.conf
added following to ban.conf

```
[Definition]
# set `url = \S+` to allow capturing all requests:
url = /
code = (?!20)\d+
# failregex = ^<ADDR> \S+ \S+ \[\] "[A-Z]+ / [^"]*" (?!20)\d+
failregex = ^<ADDR> \S+ \S+ \[\] "[A-Z]+ %(url)s [^"]*" %(code)s

ignoreregex =
```

in jail.conf i have added the following

```
[bots]
enabled   = true
port      = http,https
filter    = bots
logpath  = %(apache_access_log)s
maxretry = 1
```

disabled all filters except bot.conf

reboot server

waited for a few hours

in fail2ban log it says (real IP addresses removed)
```
2019-11-11 22:22:29,751 fail2ban.server         [1093]: INFO    --------------------------------------------------
2019-11-11 22:22:29,753 fail2ban.server         [1093]: INFO    Starting Fail2ban v0.10.4
2019-11-11 22:22:29,753 fail2ban.server         [1093]: INFO    Daemon started
2019-11-11 22:22:29,754 fail2ban.observer       [1093]: INFO    Observer start...
2019-11-11 22:22:29,865 fail2ban.database       [1093]: INFO    Connected to fail2ban persistent database '/var/lib/fail2ban/fail2ban.sqlite3'
2019-11-11 22:22:29,868 fail2ban.database       [1093]: WARNING New database created. Version '2'
2019-11-11 22:22:29,868 fail2ban.jail           [1093]: INFO    Creating new jail 'http'
2019-11-11 22:22:29,924 fail2ban.jail           [1093]: INFO    Jail 'http' uses pyinotify {}
2019-11-11 22:22:29,946 fail2ban.jail           [1093]: INFO    Initiated 'pyinotify' backend
2019-11-11 22:22:29,949 fail2ban.filter         [1093]: INFO      maxRetry: 1
2019-11-11 22:22:29,950 fail2ban.filter         [1093]: INFO      encoding: UTF-8
2019-11-11 22:22:29,950 fail2ban.filter         [1093]: INFO      findtime: 1296000
2019-11-11 22:22:29,950 fail2ban.actions        [1093]: INFO      banTime: 2592000
2019-11-11 22:22:29,950 fail2ban.filter         [1093]: INFO    Added logfile: '/var/log/apache2/access.log' (pos = 0, hash = d41d8cd98f75b204e9800998ecf8427z)
2019-11-11 22:22:30,088 fail2ban.jail           [1093]: INFO    Jail 'http' started
2019-11-11 22:22:52,057 fail2ban.filter         [1093]: INFO    [http] Found 192.168.1 - 2019-11-11 10:33:35
2019-11-11 22:22:52,302 fail2ban.filter         [1093]: INFO    [http] Found 192.168.2 - 2019-11-11 07:53:19
2019-11-11 22:22:52,304 fail2ban.filter         [1093]: INFO    [http] Found 192.168.1.3 - 2019-11-12 08:24:10
2019-11-11 22:22:52,304 fail2ban.filter         [1093]: INFO    [http] Found 192.168.1.4 - 2019-11-11 08:24:10
2019-11-11 22:22:52,304 fail2ban.filter         [1093]: INFO    [http] Found 192.168.1.5 - 2019-11-11 08:24:10
2019-11-11 22:22:52,304 fail2ban.filter         [1093]: INFO    [http] Found 192.168.1.6 - 2019-11-11 08:24:10
2019-11-11 22:22:52,666 fail2ban.filter         [1093]: INFO    [http] Ignore 192.168.2.1 by ip
2019-11-11 22:22:54,254 fail2ban.actions        [1093]: NOTICE  [http] Ban 192.168.1.1
2019-11-11 22:22:55,191 fail2ban.actions        [1093]: NOTICE  [http] Ban 192.168.1.2
2019-11-11 22:22:56,195 fail2ban.actions        [1093]: NOTICE  [http] Ban 192.168.1.3
2019-11-11 22:22:57,093 fail2ban.actions        [1093]: NOTICE  [http] Ban 192.168.1.4
2019-11-11 22:22:57,093 fail2ban.actions        [1093]: NOTICE  [http] Ban 192.168.1.5
2019-11-11 22:22:57,093 fail2ban.actions        [1093]: NOTICE  [http] Ban 192.168.1.6
```
server log of those banned from above

```
192.168.1.1 - - [11/Nov/2019:06:56:38 +1100] "GET / HTTP/1.1" 200 15716 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
192.168.1.2 - - [11/Nov/2019:08:24:10 +1100] "GET / HTTP/1.1" 200 699 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 Google Favicon"
192.168.1.3 - - [11/Nov/2019:22:50:50 +1100] "GET / HTTP/1.0" 403 7444 "_" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.4882.400 QQBrowser/9.7.13076.400"
192.168.1.4 - - [11/Nov/2019:23:41:27 +1100] "GET / HTTP/1.1" 403 8001 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 Google Favicon"
192.168.1.5 - - [03/Nov/2019:06:33:45 +1100] "GET / HTTP/1.1" 301 699 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 Google Favicon"
192.168.2.1 - - [03/Nov/2019:08:08:09 +1100] "GET / HTTP/1.1" 301 699 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 Google Favicon"
192.168.1.6 - - [04/Nov/2019:04:04:19 +1100] "GET / HTTP/1.1" 200 17453 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
192.168.2.23 - - [11/Nov/2019:22:46:45 +1100] "GET / HTTP/1.0" 301 618 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)"

```
in iptables  saved (edited for public posting)

```
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [13704:21152992]
:f2b-http - [0:0]
-A f2b-http -s 96.127.169.2/32 -j REJECT --reject-with icmp-port-unreachable
-A f2b-http -s 192.168.1.1/32 -j REJECT --reject-with icmp-port-unreachable
-A f2b-http -s 192.168.1.2/32 -j REJECT --reject-with icmp-port-unreachable
-A f2b-http -s 192.168.1.3/32 -j REJECT --reject-with icmp-port-unreachable
-A f2b-http -s 192.168.1.4/32 -j REJECT --reject-with icmp-port-unreachable
-A f2b-http -s 192.168.1.5/32 -j REJECT --reject-with icmp-port-unreachable
-A f2b-http -s 192.168.1.6/32 -j REJECT --reject-with icmp-port-unreachable
-A f2b-http -j RETURN
COMMIT
# Completed on Mon Nov 11 00:00:00 2019
```




as above you can see it is blocking some ips that are using HTTP/1.0 but not all
but also blocking some HTTP/1.1 request
there are 1000 of ips that are wrongly block or not blocked  but i just posted a sniped of them

**Comment by sebres** [comment]
> as above you can see it is blocking some ips that are using HTTP/1.0 but not all

Sure, you use my suggested RE and as I said it wouldn't block 20x requests at all (e. g. 30x/40x only).

> but also blocking some HTTP/1.1 request

Clear it does! Did you read what I was writing by description to this regex (in https://github.com/fail2ban/fail2ban/issues/2564#issuecomment-552109792)?

_Just think about the "intruder" can use other methods..., **other HTTP proto's**..._

So this regex is intentionally constructed to ban all protocols (inclusive HTTP/1.1), but only http codes that are not 20x.
This was an example only, because you did not provide your intention (or else because I don't know why 20x-responses of HTTP/1.0 should be banned, I provided a regex that make sense in my opinion). But of course you can use your own (initial) regex as I wrote you above what was your error:

_So change `\[[^]]+\]` to `\[[^]]*\]` or even just `\[\]` and it'll work._

> there are 1000 of ips that are wrongly block or not blocked but i just posted a sniped of them

The definition of **wrong** is your own definition only, that I can't follow as long as you don't provide what exactly you want.

If you want to ban **HTTP 1.0** only **regardless the response code** (also 20x responded requests inclusive) use this:
```ini
failregex = ^<ADDR> \S+ \S+ \[\] "[A-Z]+ / HTTP/1.0"
```
If something else, you must provide the example log-message (that should be banned or vice versa - that should not be banned).

But 1000 times better would be to reject unexpected requests in the web-server (e. g. with some code like `403` (Forbidden)), so you can use the failregex you already used (my suggested regex) and just set the `filter = bots[code=403]` in jail to ban ALL requests responded with 403 only.
That would be more plausible as your current intention.

**Comment by bigalownz** [comment]
sorry for not explaining  my problem better

but 

`failregex = ^<ADDR> \S+ \S+ \[\] "[A-Z]+ / HTTP/1.0"`

is just what i wanted and it works just as i wanted it to be

thanks for your help
