### ISSUE TITLE
OwnCLoud 10.3 filter

### ISSUE THREAD

**Issue by Kenshironanto** [fail2ban/fail2ban#2568]
### Environment:

- Fail2Ban version : 0.10.2
- OS : Debian 4.19.67-2+deb10u1 (2019-09-20)
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration : Usual conf param (destmail, ignoreip =(local ip/fqdn) debug level....

### The issue:

- Jail Owncloud created with his own filter
- Regex """seems correct""" -> "matches when test log"
- Try to brute-force Authentification on site 
- fail2ban doesn't detect anything

#### Steps to reproduce

**Here's the owncloud log**

```
{"reqId":"Z72K3dksA0M2wQLpSAhc","level":2,"time":"2019-11-29T06:01:54+00:00","remoteAddr":"192.42.116.23","user":"--","app":"core","method":"POST","url":"\/index.php\/login?user=sdf","message":"Login failed: 'sdf' (Remote IP: '192.42.116.23')"}
```

**Here's the regex**

```ini
[Definition]
_groupsre = (?:(?:,?\s*"\w+":(?:"[^"]+"|\w+))*)
failregex = ^\{%(_groupsre)s,?\s*"remoteAddr":"<HOST>"%(_groupsre)s,?\s*"message":"Login failed:

datepattern = %%Y-%%m-%%dT%%H:%%M:%%S
```

#### Expected behavior

- after 10 try, ban, here's config

```ini
[cloudurav]
enabled = true
port = http,https
filter = cloudurav
logpath = /path/to_log/owncloud.log
maxretry = 10
bantime = 2592000
action = iptables-multiport`
```
#### Observed behavior

- Result of regex test : 

```
root@cloud:~# fail2ban-regex  /path/to_log/owncloud.log /etc/fail2ban/filter.d/cloudurav.conf

Running tests
=============

Use   failregex filter file : cloudurav, basedir: /etc/fail2ban
Use      datepattern : Year-Month-DayT24hour:Minute:Second
Use         log file : /path/to_log/owncloud.log
Use         encoding : UTF-8


Results
=======

Failregex: 70 total
|-  #) [# of hits] regular expression
|   1) [70] ^\{(?:(?:,?\s*"\w+":(?:"[^"]+"|\w+))*),?\s*"remoteAddr":"<HOST>"(?:(?:,?\s*"\w+":(?:"[^"]+"|\w+))*),?\s*"message":"Login failed:
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [73] Year-Month-DayT24hour:Minute:Second
`-

Lines: 73 lines, 0 ignored, 70 matched, 3 missed
[processed in 0.00 sec]
```

- But fail2ban log even in DEBUG, stay silent- 

#### Any additional information

- The regex comes from here
- I use TOR to "Brute force " (just ramdom username/pass - enter- pass - enter- pass - enter.....etc....)

### Configuration, dump and another helpful excerpts

- After a restart : 
```
fail2ban.jail           [25110]: INFO    Jail 'cloudurav' started
```
..... and that all

Help! :'( i'm quite tired, just want to sleep well - 

Best regards

Ken

**Comment by sebres** [comment]
> The regex comes from here

You mean https://github.com/fail2ban/fail2ban/issues/2485#issuecomment-516400982 and some another issues for  other \*could?

Well perhaps they are a bit "different" log-formats or have some other deviations.

1. Firstly your failregex seems to work, but it seems to ignore the failure (finding) if it running in fail2ban, which can have several roots...
2. Check our [wiki for some possible reasons](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works)... 
  - either it recognizes wrong time , so invalid time zone (see in the wiki how check);
  - or jail/default have wrong backend;
  - or wrong log-path;
  - or there are really no failures generated after start of f2b.

As for the TZ, for example I see `2019-11-29T06:01:54+00:00`, so it looks like UTC/GMT and if your actual time zone is not GMT, fail2ban can ignore all the failures (due to exceeding of `findtime` for that).
For example in above mentioned comment it looks so:
```ini
datepattern = ,?\s*"time"\s*:\s*"%%Y-%%m-%%d[T ]%%H:%%M:%%S(%%z)?"
```
that will correct recognize the zone.

Just check all that described in the wiki step by step. We cannot do it for you from here. :)

> But fail2ban log even in DEBUG, stay silent

Hmm... this is hardly possible, but you can try HEAVYDEBUG (but it will produce a lot of messages).

**Comment by Kenshironanto** [comment]
@sebres  : Thanks a lot for your fast reply 

I w'll check that tomorrow - and come back here to feeback, 

Sincerely 

Kenshiro

**Comment by Kenshironanto** [comment]
Back after a goodnight.


I made somes mistakes when i create the issue. 
 

> But fail2ban log even in DEBUG, stay silent

How the hell someone can wrote that..... oh wait!.... my post..... shhaaaame ! 


So let's explore this : 

> either it recognizes wrong time , so invalid time zone (see in the wiki how check);

In 1st instance, fail2ban was able to detect my own regex rule (the one i create before exploring docs/google/.... and finaly came here asking help) - But as the datepattern wasn't in my regex, i got the message about the datepattern, for that i create my own datepattern : 

`"time":"2019-11-29T06:01:54+00:00"`

`datepattern = %%Y-%%m-%%dT%%H:%%M:%%S`


After my date pattern, fail2ban's logs wasn't able to detect anything. Otherwise, i was perfectly sure my datepattern was the one : 

`Date template hits:`
`|- [# of hits] date format`
`|  [73] Year-Month-DayT24hour:Minute:Second`


It was to able to detect the timestamp - i was pretty confidente about my datepattern....


But right after creating this issue, i comment the datepattern in my filter - I don't know why i did it - like the last cerebral breath, or God'sHand who say "Did This My Son" - I restart a very last time fail2ban and i test it and : 


`2019-11-29 23:49:02,474 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:49:02`
`2019-11-29 23:49:12,482 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:49:12`
`2019-11-29 23:49:16,796 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:49:16`
`2019-11-29 23:49:19,751 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:49:19`
`2019-11-29 23:49:22,455 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:49:22`
`2019-11-29 23:49:22,874 fail2ban.actions        [25839]: NOTICE  [cloudurav] Ban 35.0.127.52`
`2019-11-29 23:49:41,885 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:49:41`
`2019-11-29 23:49:46,691 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:49:46`
`2019-11-29 23:49:48,604 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:49:48`
`2019-11-29 23:49:57,716 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:49:57`
`2019-11-29 23:54:49,724 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:54:49`
`2019-11-29 23:54:49,959 fail2ban.actions        [25839]: WARNING [cloudurav] 35.0.127.52 already banned
`


_You can imagine how i was (let's make a precision, i wasn't able to mentally suuport the DEBUG mode, too much info, too much terminals windows opened, too much windows opened everywhere)_


Now detection seems working, but as you can see in the last log : 

`2019-11-29 23:49:22,874 fail2ban.actions        [25839]: NOTICE  [cloudurav] Ban 35.0.127.52`
`2019-11-29 23:49:41,885 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:49:41`
`2019-11-29 23:49:46,691 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:49:46`
`2019-11-29 23:49:48,604 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:49:48`
`2019-11-29 23:49:57,716 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:49:57`
`2019-11-29 23:54:49,724 fail2ban.filter         [25839]: INFO    [cloudurav] Found 35.0.127.52 - 2019-11-29 23:54:49`
`2019-11-29 23:54:49,959 fail2ban.actions        [25839]: WARNING [cloudurav] 35.0.127.52 already banned`


**I assume something wrong with iptable ban**


Anyway, you gave me somes precious infos, iven't made any correction till now on my code  - I wanted to give a feedback about it before.


I bet this last problem will not resist any longer - I wll be back here when everything will work like charms and share with everyone who need it.


Thanks for you time!

**Comment by sebres** [comment]
> I assume something wrong with iptable ban

Basically I wanted write:

I don't think so (at least if it doesn't occur in current time of running operation and no errors in log after banning action executed)... Perhaps that were the messages already produced by the intruder before you started f2b.
So just take a look how it looks with fresh failures. You can also see `already banned` due to certain latency between recognition and ban (but it should be minimal, so under few seconds).

But then I saw the time stamps in your log excerpt:
```
2019-11-29 23:49:22,455 ... Found 35.0.127.52 - 2019-11-29 23:49:22
```
The second time (after "Found") should be the real time of failure from log (not the time of detection). But it show no deviation to the current moment fail2ban logged that (so it looks like a real time).

Then it is possible only if your banning action (iptables-mutiport) does not work properly:
- either listener of your service has still some other ports as http,https;
- or your firewall has some white-listing rules (e. g. already established connections explicitly allowed), see https://github.com/fail2ban/fail2ban/issues/2545#issuecomment-543347684 or similar issues.
- or something in your net sub-system is configured "wrong" (in sense of f2b/firewall, because avoiding usage of them).

Anyway it is rather not a fail2ban issue (you'd not be able to do that with your net-filter too).
