### ISSUE TITLE
support elasticsearch as log source

### ISSUE THREAD

**Issue by jmcclelland** [fail2ban/fail2ban#2593]
I am interested in adding elasticsearch as a log source.

The use case is: we have several client-facing email servers, all accepting IMAP/POP logins and then proxying to the appropriate backend IMAP/POP server.

We can run fail2ban on each of these servers and ban IPs that reach the appropriate threshhold of failed login attempts, but since there are multiple front ends, an attacker can simply cycle through all of them.

Since we are aggreggating all the logs in real time to an elastic search server, it would be useful if each fail2ban instance could query the central elastic search server and benefit from a combined log.

If there are other ways to achieve this goal I woud be very interested to hear them (a central way to distribute IPs to ban??). Or if there are any fundamental or structural reasons why this is a bad idea   please let me know.

Thanks for the excellent software.

**Comment by sebres** [comment]
Either dup of #881 (or similar idea #239).

Anyway if your distributed log is neither a log-file nor a systemd journal (what I suppose), one would need a new `backend` for elastic.
There are no fundamental or structural reasons against that.

**Comment by opoplawski** [comment]
One possibly structural concern is that this would likely have to a polling process and I'm not sure how efficient it is to maintain a 'cursor' like item with elacticsearch and continually collect only new log items.

FWIW - I generally handle this situation by having the fail2ban action insert rules into our internet facing firewalls rather than just the local machine's, thus protecting all machines behind that firewall.

**Comment by jmcclelland** [comment]
Thanks for the feedback. Let's consider this a dupe of #881. I don't think i will purse an elastic backend given the alternatives discussed in #881.

**Comment by Matt-Yorkley** [comment]
@jmcclelland wouldn't it make sense to do it the other way around, e.g: develop Beats/Kibana modules for fail2ban?
