### ISSUE TITLE
Running external scripts based on internal conditions

### ISSUE THREAD

**Issue by EnKrypt** [fail2ban/fail2ban#2609]
In my example, I want to run a script when the 'currently banned' number in a jail exceeds a variable.

Is there an internal mechanism to handle that? (I couldn't find anything in the docs)
And if not, what is the sentiment towards implementing such a feature? (I will help contribute of course)

I understand that this can be achieved with a cron job that scans the logs or cli output at an interval, but I'd ideally like to avoid an inefficient solution as such.

**Comment by EnKrypt** [comment]
Couldn't assign labels to this issue. I would've added the 'question' label for clarity.

**Comment by sebres** [comment]
> Is there an internal mechanism to handle that? (I couldn't find anything in the docs)

Well, it is not quite clear what "currently banned" should mean:

1. if you mean the ban count of some sole IP if it gets banned, then yes, it is possible since 0.11 version, just use something like that in action:
```ini
actionban = if [ <bancount> -gt 10 ]; then
              echo "<ip> got banned <bancount> times"
            fi
```
2. if you mean a "statistic" number like in output of jail status, then it is also possibly but conditionally:
- one can extend actions module to provide such count, but...
it is not clear for which purposes such value can be interesting, because "currently banned" means a count of tickets banned at this time point, so it can grows by next bans but also can shrink by next unbans. The question is what should happens it got once reached, but if you've no unbans occurred it'll be reached again and again by every next ban in this jail.
- one can obtain it from fail2ban-client on ban in some new action, but the question remains - for which purposes such a counter (that hold only count valid for this moment) may be needed. Maybe rather you want `Total banned` modulo N (so triggering a command every N bans)...
Anyway - here you go:
```ini
actionban = cnt=$(fail2ban-client status "<name>" | grep -oP 'Currently banned:\s+\K\d+')
            if [ "$cnt" -gt 10 ]; then
              echo "<ip> got banned <bancount> times"
            fi
```
- or one can write own pythonic action and increment some count (as member of action object) on every ban (and possibly decrement on unban):
```py
# /etc/fail2ban/action.d/on-banned.py:
from fail2ban.server.actions import ActionBase
from fail2ban.server.utils import Utils

class Action(ActionBase):
  def __init__(self, jail, name, targetcount=10, command=""):
    super(Action, self).__init__(jail, name)
    self.bannedCount = 0
    self.targetCount = int(targetcount)
    self.command = command

  def ban(self, aInfo):
    self.bannedCount += 1
    # if target count reached:
    if self.bannedCount >= self.targetCount:
       # execute command:
       Utils.executeCmd(self.command, varsDict={'name':self._name, 'bannedCount':self.bannedCount})
       # reset count (next cycle counting up to targetCount bans):
       self.bannedCount = 0

# # no decrement atm, counting bans only ...
#  def unban(self, aInfo):
#    self.bannedCount -= 1
```
and you have to configure it in `jail.local` (here 2 actions, one banning and other executes the command if reached:
```ini
[my-jail]
action = %(known/action)s
         on-banned.py[targetcount=10, command='echo "jail $name reached $bannedCount banned tickets"']
```
which would do an echo every 10th ban:
```
jail my-jail reached 10 banned tickets
jail my-jail reached 20 banned tickets
jail my-jail reached 30 banned tickets
...
```
Not tested, but it should be working scenario.

Newest version of fail2ban (v.1.0) gets a new feature which could save some data in the command action and hold it persistently (or for some time) cached per jail or global for all jails/actions.
As well as new event mechanism (which can be possibly used for such purposes).
I'll provide some examples once it gets merged.
