### ISSUE TITLE
Gitlab sshd Docker - Found a match for... but no valid date/time found

### ISSUE THREAD

**Issue by jdsmall25** [fail2ban/fail2ban#2618]
### Environment:

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

I'm running fail2ban on my docker host and I'm trying to monitor my Gitlab container's sshd logs that I've mounted in an accessible volume.  I'm using the stock sshd.filter with a simple jail config. However it doesn't like how Gitlab is formatting the timestamp because it keeps warning that it found matches for the message but not the date/time.  Therefore nothing is getting blocked.  

#### Steps to reproduce
1. Install fail2ban on docker host
2. Setup gitlab container
3. Export gitlab container logs
4. Enable sshd jail with default filter, pointing at gitlab logs.

#### Expected behavior
I'd expect this to work out of the box without further configuration of the filters.  Seems like it should be a standard instance of sshd.

#### Observed behavior
No IP bans due to timestamp issue.

#### Any customizations done to /etc/fail2ban/ configuration
My jail config is as follows:
```
[sshd-aggressive]
enabled         = true
port            = ssh
filter          = sshd[mode=aggressive]
logpath         = /gitlab/logs/sshd/current
maxretry        = 2
banaction       = iptables-multiport
findtime        = 6m
bantime         = 180d
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

`2020-01-27 23:30:52,721 fail2ban.filter         [21760]: WARNING Found a match for '2020-01-28_04:30:52.72035 User root from 59.120.244.230 not allowed because not listed in AllowUsers' but no valid date/time found for '2020-01-28_04:30:52.72035 User root from 59.120.244.230 not allowed because not listed in AllowUsers'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.`
                                                                                                                                 

#### Relevant lines from monitored log files in question:

```
2020-01-27_16:21:07.50766 Disconnected from 69.158.207.141 port 34852 [preauth]
2020-01-27_16:21:58.08277 User root from 69.158.207.141 not allowed because not listed in AllowUsers
2020-01-27_16:21:58.08299 input_userauth_request: invalid user root [preauth]
2020-01-27_16:21:58.12387 Received disconnect from 69.158.207.141 port 52155:11: Normal Shutdown, Thank you for playing [preauth]
```

**Comment by sebres** [comment]
> I'd expect this to work out of the box without further configuration of the filters. 

And I would expect that every package/service of every distribution has the same date format.

> Seems like it should be a standard instance of sshd.

I don't think so - never saw this format (with underscore) neither by auth.log (sshd) nor by some other syslog's. 
Not to mention this messages are not conform to default common include, do not contain a minimal common prefix `sshd[...]`, and this is also an issue, because sshd is a multi-line filter and `[...]` identifies an intruder session (used as multi-line ID `<F-MLFID/>`) to assign failure-messages without IP to correct ticket.
And normally our default sshd-filter would not match that (and if it is matching it seems to be changed by you or the maintainers).
But if you mean this is a standard date format, you could contact the maintainers of fail2ban packet for your distribution (BTW, you did not provide what is it, see `OS, including release name/version` above).

Anyway I don't think it should be added to the default date patterns of fail2ban.
Let alone it is always better to specify that as precise a possible (see our [wiki :: best practice](https://github.com/fail2ban/fail2ban/wiki/Best-practice) for more info).
This is pretty simple:
```ini
[sshd]
datepattern = ^%%Y-%%m-%%d_%%H:%%M:%%S(?:\.%%f)?
```

**Comment by bionade24** [comment]
@jdsmall25 Did this pattern work for you?  I tried, even to modify them, but nothing ever worked. Only if I don't have loginfo in the same string, it worked.
```
>>> time.strptime("2020-02-22_18:58:37.73594", "%Y-%m-%d_%H:%M:%S.%f")
time.struct_time(tm_year=2020, tm_mon=2, tm_mday=22, tm_hour=18, tm_min=58, tm_sec=37, tm_wday=5, tm_yday=53, tm_isdst=-1)
```

**Comment by sebres** [comment]
> but nothing ever worked.

There is no such "error" in IT world. Please be a bit more precise (provide detailed info).

> Only if I don't have loginfo in the same string, it worked.

I don't follow what you mean with loginfo (what you don't have where? in which string?)...

Only one reason where `datepattern` would not work if it is specified directly in jail - if you have fail2ban version <= 0.9.x. Before v.0.10 it could be set in the `[Init]` section of the filter only.

**Comment by bionade24** [comment]
Okay, thanks. Yes, I'm on 0.9.6, so I'll take your advice and reconfigured it thanks. But somehow the manpage wasn't obviously guiding  me to set it there.
