### ISSUE TITLE
influxdb regex

### ISSUE THREAD

**Issue by davide-rhw** [fail2ban/fail2ban#2622]
i try to crete regex for influxdb access unoautorized but not work:

The error 401 in syslog :
```
"POST /query?q=+SELECT+*+FROM+%22input_boolean.sensore_bagno%22&db=hadb1 HTTP/1.1" 401 27 "-" "axios/0.19.2" 07a642e8-46a5-11ea-8001-080027642be1 94631
```
the regex in jail.d file:
```ini
[Definition]
failregex = ^<HOST> -.* HTTP/[0-9].[0-9]" 401
```
the jail in jail.conf:
```ini
[influxdb]
enabled = true
filter = influxdb
logpath = /var/log/syslog
banTime = 3600
findTime = 600
maxretry = 5
```
Thanks in advance

**Comment by sebres** [comment]
> i try to crete regex for influxdb access unoautorized but not work:

Error "not work" does not exist in IT world. Please describe exactly what it means (error, `fail2ban-regex` output, etc).
See also our [wiki](https://github.com/fail2ban/fail2ban/wiki) for possible reasons why it could fail or may not work.

> The error 401 in syslog :
> `"POST /query?q=+SELECT+*+FROM+%22input_boolean.sensore_bagno%22&db=hadb1 HTTP/1.1" 401 27 "-" "axios/0.19.2" 07a642e8-46a5-11ea-8001-080027642be1 94631`

You have provided an error without an IP in message:
- what do you want to ban? (if it should be some IP, it is impossible with this single line; if something else - then you should tell us what it is).
- if the line has an IP (you cut it out), please provide whole line (you can replace the IP with `192.0.2.1` if you want to blacken it).

> the regex in jail.d file:

This looks like a filter file, either use `/etc/fail2ban/filter.d/influxdb.conf` instead of "jail.d file" or specify `failregex` directly in jail.local (and set `filter =`).
