### ISSUE TITLE
pgrep fail2ban

### ISSUE THREAD

**Issue by ghnp5** [fail2ban/fail2ban#2623]
Hello,

My server just upgraded from 0.10.4 to 0.10.5, and then I started getting several alerts about fail2ban not running.
I checked, and in fact, fail2ban seems to be running, but I still went ahead and restarted it. However, the alerts continue.

This is because the cron runs:
`pgrep fail2ban`
which returns nothing, since the upgrade.

But if I run:
`ps aux | grep fail2ban`
It can indeed find the process:

> /usr/bin/python -s /usr/bin/fail2ban-server -xf start

On my other server, which hasn't upgraded yet, running 0.10.4, `pgrep fail2ban` continues to find the process.
The process is as:

`/usr/bin/python /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid -x --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto`

On the server which upgraded, fail2ban seems to be working fine, banning IPs as it finds them, etc...

However, I can't understand why "pgrep" isn't finding the process.
Do you have any idea why?

I'm just afraid that something changed significantly, and that I may need to make some config changes to ensure everything is working as before.

In addition -- are there any breaking changes on the upgrade from 0.10.5 to 0.11.1 that I should be aware of?
The change log looks massive since the last version, so I'm afraid that I might have missed something that requires an action by me!

Thank you very much.

### Environment:

- Fail2Ban version: 0.10.5
- OS: CentOS 7
- Fail2Ban installed via yum
- No patches - original
- Configuration via jail.local, just to enable some lookups

**Comment by sebres** [comment]
> This is because the cron runs:
`pgrep fail2ban`
which returns nothing, since the upgrade.

Why it should be so complex? Normally init- or systemd-units check it by themselves and it is enough in common case. What are the purposes of `pgrep fail2ban`?

> However, I can't understand why "pgrep" isn't finding the process. Do you have any idea why?

Well, I cannot explain it, but may be f3dbc9dda10e52610e3de26f538b5581fd905505 is responsible for that - all fail2ban threads are named now and main (server) thread is called `f2b/server` (where it had no name previously).
But I don't know pgrep consider that (prefer thread name to process name / command line).
Another reason may be that systemd-unit (fail2ban.service) gets many modifications (e. g. switched from forking via fail2ban-client to direct usage of fail2ban-server).
But such units are matter of packet maintainers (we don't have install process for that in our setup script).

Anyway it is too vague to do checks like `pgrep fail2ban` (just imagine you would find )...
Normally fail2ban writes a pid file into `?/var?/run/fail2ban/fail2ban.pid`. Better use that pid and check whether the process with pid exists.
```
pid=$(cat /run/fail2ban/fail2ban.pid)
if [ "$pid" != "" ] && ps -p "$pid" > /dev/null; then
echo 'exists'
fi
```

> In addition -- are there any breaking changes on the upgrade from 0.10.5 to 0.11.1 that I should be aware of?

Well, every substantial change is mentioned in ChangeLog but major compat-things can be found in [Compatibility section](https://github.com/fail2ban/fail2ban/blob/0.11.1/ChangeLog#L12).

There are no hard and fast rules about how much it could affect potentially every system/distribution as well as every use case (as you can see we were not aware about `pgrep` thing).

If you upgrade to 0.11.1 most important feature would be ban-time increment (#1460), you have at least to [enable](https://github.com/fail2ban/fail2ban/blob/0.11.1/config/jail.conf#L47-L81) that per jail or in default section:
```ini
[DEFAULT]
bantime.increment = true
bantime.maxtime = 3w
```

**Comment by cherdt** [comment]
This is causing problems for me as well. My Nagios check_procs plugin was configured to check for "fail2ban-server". Now it needs to check for "f2b/server" but check_procs interprets the "/" as part of a path.

The man page for `proc` doesn't prohibit any characters, but since `comm` should represent the "command name associated with the process" including a "/" seems unexpected.

**Comment by ghnp5** [comment]
@sebres Thank you very much for your response, which was extremely useful.
I'm sure there are better ways of doing what I'm doing, but I used "pgrep" simply because it seemed to be doing the job for all the processes I wanted to make sure are running.

I confirm that doing "pgrep f2b" finds the right process. I had no idea that what "pgrep" sees would be different than what "ps aux" sees.

I appreciate very much everything you said in your response, which I'm going to take advantage of (the incremental feature, etc...).

Myself, I'm ok to accommodate my process to check the right process name.
However, as @cherdt mentioned, this change might be affecting others as well.

Very kind regards.

**Comment by sebres** [comment]
Well, f3dbc9dda10e52610e3de26f538b5581fd905505 implements a nice feature allowing to recognize a bothering thread in case of some issue (e. g. high CPU load etc), so we will definitely retain this (for child threads).
But I tend to revert the change of thread name for the **main thread (server)**, since this change affects the process name too (so it confuses `pgrep` et al).

The reason for usage of short prefix (`f2b/`) is simple - thread name can be maximal 15 chars long, so it makes possible to see as many as possible characters from jail name (and filter/action) in order to distinguish all them.

As long as it is not yet fixed, one could change the related line:
https://github.com/fail2ban/fail2ban/blob/f3dbc9dda10e52610e3de26f538b5581fd905505/fail2ban/server/server.py#L84
to this one:
```diff
-		prctl_set_th_name('f2b/server')
+		prctl_set_th_name('fail2ban-server')
```

BTW, `pgrep` can consider command line instead of process (well, thread) name, so this should work:
`pgrep --full fail2ban-server`
Also `pgrep` had a possibility to get process by pid-file -  `pgrep --pidfile /run/fail2ban/fail2ban.pid`.

**Comment by ghnp5** [comment]
@sebres You are being very helpful. Thank you very much for all your help here. I'll add " --full" to my cron. Very kind regards!

**Comment by sebres** [comment]
Fixed.
Additionally it introduces new command-line option `--pname <NAME>` (default `fail2ban-server`), which can be supplied to change main thread (process) name (could be used to identify several instances of server if needed).
