### ISSUE TITLE
Add documentation for logencoding

### ISSUE THREAD

**Issue by ygoe** [fail2ban/fail2ban#2625]
I see a ton of messages like these in my /var/log/fail2ban.log file:

> WARNING Error decoding line from '/var/log/mail.log' with 'UTF-8'. Consider setting logencoding=utf-8 (or another appropriate encoding) for this jail.

This is understandable given what Exim writes into this file. But I cannot resolve the warning because I can't find a working encoding to set in my config. There is no documentation about the possible values so I had to crawl the web for any clues. I found the values "auto" (which isn't really auto but platform-default, in my case UTF-8), "utf-8" and "ascii". None of these work. I'd like to set something like ISO-8859-1 which at least cannot produce decoding errors. Actually I don't care that much about the codepoints 0x80 through 0xff because no filters should exist for such characters anyway. I just don't want my logs to be flooded with this useless warning.

What should I write into my config file? Please explain.

BTW, isn't it pointless to recommend explicitly setting an encoding that just failed to work?

My version is 0.9.3 on Ubuntu 16.04. The documentation issue applies to all versions.

**Comment by sebres** [comment]
> But I cannot resolve the warning because I can't find a working encoding to set in my config.

This would be probably impossible, because exim writes some binary data (port scanners, intrusions attempts or similar) and it would not match any "proper" encoding you would try to use.
Simply because it is invalid.

Because the warning is really annoying, this was "fixed" in #1542, and namely:
- [ENH] prevents permanent annoying logging of "Error decoding line from ... process line ignoring invalid characters" - now does it once per day and log-file

... already 4 years ago - your version is simply too old (I guess it was firstly released with >= 0.9.6).
