### ISSUE TITLE
Number of retries disregarded or faulty?

### ISSUE THREAD

**Issue by wehkah** [fail2ban/fail2ban#2641]
Hello,

I'm using "Fail2Ban v0.10.2" on Debian Buster and I'm having a slight problem of understanding: 

In jail.local there's this entry

```
[sshd]
enabled = true
port    = ssh
filter  = sshd
logpath = /var/log/auth.log
maxretry = 2
bantime = -1 
```

Yet, I get an e-mail saying:

> The IP 172.86.125.166 has just been banned by Fail2Ban after 10 attempts against sshd.

The e-mail also contains lots of lines like this:

```
Feb 23 05:39:57 linux.localnet sshd[30624]: Connection closed by 172.86.125.166 port 39756 [preauth]
Feb 23 05:40:15 linux.localnet sshd[30626]: Received disconnect from 172.86.125.166 port 43010:11: Normal Shutdown, Thank you for playing [preauth]
Feb 23 05:40:15 linux.localnet sshd[30626]: Disconnected from authenticating user root 172.86.125.166 port 43010 [preauth]
Feb 23 05:40:15 linux.localnet sshd[30628]: Received disconnect from 172.86.125.166 port 43034:11: Normal Shutdown, Thank you for playing [preauth]
Feb 23 05:40:15 linux.localnet sshd[30628]: Disconnected from authenticating user root 172.86.125.166 port 43034 [preauth]
Feb 23 05:40:15 linux.localnet sshd[30646]: Received disconnect from 172.86.125.166 port 43272:11: Normal Shutdown, Thank you for playing [preauth]
Feb 23 05:40:15 linux.localnet sshd[30646]: Disconnected from authenticating user root 172.86.125.166 port 43272 [preauth]
Feb 23 05:40:15 linux.localnet sshd[30654]: Received disconnect from 172.86.125.166 port 43448:11: Normal Shutdown, Thank you for playing [preauth]
Feb 23 05:40:15 linux.localnet sshd[30654]: Disconnected from authenticating user root 172.86.125.166 port 43448 [preauth]
Feb 23 05:40:15 linux.localnet sshd[30657]: Received disconnect from 172.86.125.166 port 43490:11: Normal Shutdown, Thank you for playing [preauth]
```

I can not find any configuration file that allows 10 retries. I thought that the entry in jail.local would limit the number to just 2. Where do I need to look to change the 10 possible retries?

**Comment by sebres** [comment]
People!
You are asking about some mail action, but don't provide which mail action it is...

1. `maxretry = 2` says that fail2ban will ban this IP after 2 attempts within a `findtime`.
    Neither it says that following attempts will be not noticed in matches for IP unless it got banned, nor it says about how some mail actions cumulate the failures in order to to send a report.

2. If it is some mail-action that use tag `<matches>`:
    - normally the max value of tag `<matches>` can be restricted also using `maxmatches`, see #2402; 
    just it is not available for your version (firstly released with v.0.10.5).
    - you can rewrite your mail action to restrict count of lines of tag `<matches>`;

3. If it is some mail-action that use `grep`:
    - some of mail actions have an option to restrict the messages from IP:
 https://github.com/fail2ban/fail2ban/blob/d01fe9d22a717a0122143cde41ce5c18a1790f6e/config/action.d/mail-whois-lines.conf#L89-L92
    - if you use some of that, you can extend your `action` specification with `grepmax` parameter, like `mail-whois-lines[grepmax=2]`.

**Comment by wehkah** [comment]
I don't see why you are so rude. I asked a question about something I do not understand. I don't know why you are talking about the mail action, which information about it you need, and I don't know what a mail action has to do with the 8 retries that are too many according to the setting.

As you can see, all attempts took place within half a minute. There is no time to cool down time for the trigger between those attempts. So according to the setting, as I understand it, this IP should have been blocked right after the second attempt, fail2ban should not have waited for 10 attempts to happen.

I don't see what the difference between 2 attempts allowed and 10 attempts happening has to do with a mail action.

**Comment by sebres** [comment]
> I don't see why you are so rude. 

What exactly was rude in my answer?

> I asked a question about something I do not understand.

Well, basically this place is a developer repository and not serverfault, stackoverflow or similar forums for questions.

> I don't know why you are talking about the mail action, which information about it you need, and I don't know what a mail action has to do with the 8 retries that are too many according to the setting.

To get a mail from fail2ban you have to configure any mail-action.
So there are 3 possibilities how you configured action without to know what it is:
1. you followed some article from internet "how to setup fail2ban" without to understand it.
2. you taken over a support for the host fail2ban was installed by someone else.
3. you experimented with your config without to read documentation man's.

I don't believe that maintainers of your fail2ban distribution were choosing some default mail-action for you, so there are only this 3 way in my opinion.
Then the question is either why you asking here and not there or rather why don't read manual.
We have also several [wiki articles](https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration) about.

Anyway, the action is specified somewhere in your config, you can find it with:
```
fail2ban-client -d | grep 'sshd.*action'
# all options of sshd jail:
fail2ban-client -d | grep 'sshd'
```

> The e-mail also contains lots of lines like this ...

> I don't see what the difference between 2 attempts allowed and 10 attempts happening has to do with a mail action.

Well basically according your example configuration no one of the messages from your excerpt should be matched at all, so I think your mail-action makes just grep via IP address (point number 3 of my comment above).

The provided messages (`Connection closed ... [preauth]` and `Disconnected ... [preauth]`) are matched only in mode `aggressive` which is not specified corresponding jail configuration you've provided.
So fail2ban probably found 2 another messages matched in mode `normal`.

> So according to the setting, as I understand it, this IP should have been blocked right after the second attempt, fail2ban should not have waited for 10 attempts to happen.

Well, backend (filter) and actions working totally asynchronously, so if some attempts are found during the banning process takes place (completed), all the matches get still noticed by fail2ban.
Also note that python is not really multithreaded (due to GIL), so some processes are not running in parallel but sequentially rather.
Therefore fail2ban don't really wait, but there is every chance that a ban gets certain latency after last expected attempt is found.

**Comment by wehkah** [comment]
The complete reason for my question is this:

There are two physical identical server machines, running the same OS version and the same fail2ban configuration. The other day I was sitting at my working machine and tried to ssh into one of these machines. Well... at least I **thought** I was sitting at my **usual** working machine, where the ssh keys and the ssh-config file with the necessary credentials are located. But instead, I was using a temporal working place. Therefore, the two unsuccessful tries gave me two errors, because this temporal working station had no ssh key for the target and no ssh-configuration. 

And the two unsuccessful tries also resulted in a ban of my temporal working machine.

Great news, every one! All is great, fail2ban works as expected! :)

Then, a few days later, I got this e-mail, saying that it took 10 tries to make fail2ban react, although it was expected to react after the second unsuccessful attempt. And that is the thing I don't understand: my forgetfulness made fail2ban react instantly, while someone else could fire 10 times without consequences. 

Maybe know you understand why I am worried about the fail2ban set up and its accuracy.
