### ISSUE TITLE
Fail2ban as non-root

### ISSUE THREAD

**Issue by dunderrrrrr** [fail2ban/fail2ban#2649]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): **Fail2Ban v0.10.2**
- OS, including release name/version: **Ubuntu 18.04.4 LTS bionic**
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Be able to run `fail2ban-client status`, and `fail2ban-client status <jail>` without being root.  

There is some documentation in [run-rootless.txt](https://github.com/fail2ban/fail2ban/blob/master/doc/run-rootless.txt) but it's not very detailed.  
Is there a step-by-step guide somewhere? 

#### Steps to reproduce
```bash
$ fail2ban-client status
 Permission denied to socket: /var/run/fail2ban/fail2ban.sock, (you must be root)
```

#### Expected behavior
```bash
$ fail2ban-client status
Status
|- Number of jail:	2
`- Jail list:    jail01, jail02
```

**Comment by sebres** [comment]
> There is some documentation in run-rootless.txt but it's not very detailed.

It describes a bit different intention (either how to run fail2ban without root).
You want rather to communicate with fail2ban-server by user without root.

> Be able to run `fail2ban-client status`, and `fail2ban-client status <jail>` without being root.  

Well it is possible, but unfortunately not for `status`  solely. 
Because fail2ban server/client don't have individual permission or user privileges models, if you would allow the server access from `fail2ban-client` for some user/group you could do everything (inclusive stop of server, change runtime config, ban, unban, etc pp).

The communication takes place via unix-socket `?/var?/run/fail2ban/fail2ban.sock` which has following permissions per default:
```
$ sudo ls -la /var/run/fail2ban/fail2ban.sock
srwx------ 1 root root ... /var/run/fail2ban/fail2ban.sock
```
So change the group or user and allow read/write rights for this, and you'll be able to use `fail2ban-client` to communicate with fail2ban server.
And don't forget to update or extend your init-script or journal unit to make this changes persistently.

**Comment by dunderrrrrr** [comment]
Ohh, perfect. 
Thanks! :smile:
