### ISSUE TITLE
Looking for howto on prolonged bantime from 0.11

### ISSUE THREAD

**Issue by joe-average-user** [fail2ban/fail2ban#2654]
Since this is more or less a question of usage and not really a bug report please be gentle when answering :-)
I am using fail2ban to ban IPs in this manner:
first appearance ip gets banned for 7200 secs
second appearance ip gets banned for 86400 secs
third appearance ip gets banned for 7776000 secs
Currently this is implemented with 3 jails, where the last follow the log output of the first.
The first follows a simple linux kernel log file and takes SRC=\<HOST\>
The problem with this is that it is slow. I had to drop the database function completely because otherwise the db gets huge and is useless in such a setup anyway.
My question is: is there an easier way to achive the same bans without having to follow two logfiles? I think the 0.11 feature of prolonging bantime should somehow manage this, but how?

Thanks for any hints.

**Comment by sebres** [comment]
> I think the 0.11 feature of prolonging bantime should somehow manage this, but how?

Some questions were already answered in similar "issue" #2652.
Shortly you have to enable it via `bantime.increment = true` per jail or default.
The factor between 2h (7200) and 1d (86400) were 12, so if you really need such large increase already after first known ban (why?), just set `bantime.factor = 12` or you have to use your custom multipliers instead of default exponential formula.

> I had to drop the database function completely because otherwise the db gets huge and is useless in such a setup anyway.

The bantime increment feature would only work if a database is enabled, but there is some options now that can help to hold it a bit slimmer, see #2402 .
