### ISSUE TITLE
Command ['status', 'sshd-ddos'] has failed. Received UnknownJailException('sshd-ddos')

### ISSUE THREAD

**Issue by frollic** [fail2ban/fail2ban#2657]
### Environment:

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

After recent upgrade log fills with 

fail2ban.transmitter    [9532]: WARNING Command ['status', 'sshd-ddos'] has failed. Received UnknownJailException('sshd-ddos')

fail2ban-firewalld-0.10.5-2.fc30.noarch
fail2ban-shorewall-0.10.5-2.fc30.noarch
fail2ban-server-0.10.5-2.fc30.noarch
fail2ban-0.10.5-2.fc30.noarch
fail2ban-sendmail-0.10.5-2.fc30.noarch

#### Steps to reproduce

unsure, 
sshd-ddos entries in the ban DB, after sshd-ddos filter was removed in the upgrade ? 

#### Expected behavior

no error entries

#### Any additional information

Tried dropping the sshd-ddos entries in the DB, but it didn't help.
also deleted the sshd-ddos entries in jails and logs.

### Configuration, dump and another helpful excerpts

there are no sshd-ddos entries in the configs.

#### Any customizations done to /etc/fail2ban/ configuration

sshd is set to agrassive, could this be the culprit, since ddos is part of agressive ?

#### Relevant parts of /var/log/fail2ban.log file:

fail2ban.conf loglevel = DEBUG

2020-03-12 11:01:02,663 fail2ban.transmitter    [9532]: WARNING Command ['status', 'sshd-ddos'] has failed. Received UnknownJailException('sshd-ddos')
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fail2ban/server/jails.py", line 78, in __getitem__
    return self._jails[name]
KeyError: 'sshd-ddos'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fail2ban/server/transmitter.py", line 58, in proceed
    ret = self.__commandHandler(command)
  File "/usr/lib/python3.7/site-packages/fail2ban/server/transmitter.py", line 143, in __commandHandler
    return self.status(command[1:])
  File "/usr/lib/python3.7/site-packages/fail2ban/server/transmitter.py", line 492, in status
    return self.__server.statusJail(name)
  File "/usr/lib/python3.7/site-packages/fail2ban/server/server.py", line 532, in statusJail
    return self.__jails[name].status(flavor=flavor)
  File "/usr/lib/python3.7/site-packages/fail2ban/server/jails.py", line 80, in __getitem__
    raise UnknownJailException(name)
fail2ban.exceptions.UnknownJailException: 'sshd-ddos'

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
Jail `sshd-ddos` is removed in stock fail2ban since #1710 (already 3 years ago) in version >= 0.10 due to better handling with single jail `sshd` and parameter `mode` (saves the system load).

But this is not directly an error of fail2ban (sever) - if shortly, the message `Command ['status', 'sshd-ddos'] has failed.` is occurring if something (service, cron etc) trying to execute
`fail2ban-client status sshd-ddos` 
and it fails now (because no such jail anymore).
Still again - something other but not fail2ban by itself.

So either you have to remove this cron, service entry, whatever or to restore this jail back (as your local jail).

To use the single jail (together with ddos), just set mode of `sshd` to `ddos` (or even `aggressive`) in your `jail.local`.
```ini
[sshd]
mode = ddos
enabled = true
```
or create your own jail `sshd-ddos` also in your `jail.local` as something like this:
```ini
[sshd-ddos]
filter  = sshd[mode=ddos]
port    = ssh
logpath = %(sshd_log)s
backend = %(sshd_backend)s
enabled = true
```
and your other parameter that were already defined locally for this jail(s).

Just note that in case with `sshd-ddos` you would also ban the failures of normal mode too (same as `sshd` with mode `normal`) because all modes of the filter also including mode `normal` (so it may be "dual" unnecessary banning if both jails are active and `maxretry` and `findtime` are the same).
If you don't want it, you should use other filter so either restore the filter of previous version or rewrite newest filter to don't include the failregex's of normal mode in ddos (e. g. reset internals like `cmnfailre` to empty value or ddos-related stuff only).

**Comment by frollic** [comment]
Thank you,

that was acutally the hint I needed to point me in the correct direction.

I have monitorix set up to create fail2ban graphs, and obviously ssd-ddos was one of the
graphs beeing generated.
