### ISSUE TITLE
Can i use a common ipset in different prisons? and also to use ipset without iptables?

### ISSUE THREAD

**Issue by lokha** [fail2ban/fail2ban#2665]
1. Can i use a common ipset in different jails? Will this work correctly?
2. Is it possible to make action just put ip in ipset without creating an iptables rule?

The thing is, I don't want fail2ban to dynamically create iptables rules. This makes it difficult to use iptables-restore and iptables-save.

I would like to create a general rule on my own where I would forbid ipset "badip":  
`iptables -I INPUT -m set --match-set badip src -j DROP`

And fail2ban would just add ip to the badip list for all jails.

How to do as I want?

**Comment by sebres** [comment]
Sure it is possible. You have to write your own action that simply does not call iptables.

Get the action [/etc/fail2ban/action.d/iptables-ipset-proto6.conf](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/iptables-ipset-proto6.conf) as an example - as you can see here some commands already don't have iptables in:
https://github.com/fail2ban/fail2ban/blob/8a0c06ba9ea3baad77cf84d2e8d4a055ea95b782/config/action.d/iptables-ipset-proto6.conf#L52
and 
https://github.com/fail2ban/fail2ban/blob/8a0c06ba9ea3baad77cf84d2e8d4a055ea95b782/config/action.d/iptables-ipset-proto6.conf#L62

So remove the lines that invoke iptables stuff (see actionstart, actionstop) and you has an action that is working with ipset only.

Then set it as banaction in your jail or default in your `jail.local`:
```ini
[DEFAULT]
banaction = my-ipset-action
```
That's it.

You can also check whether iptables calls are still available in main `action*` commands using dump:
```
fail2ban-client --dp; # --dump-pretty
```
Another variant is to overwrite call of iptables in action.
The fail2ban versions greater than 0.10 already use a tag `<iptables>` (that is dynamical due to IPv6 support), so you could try to overwrite it in depending action (own action which includes some default action). 
Or directly in `jail.local`:
```ini
# empty iptables function allows to avoid execution of iptables inside action:
banaction = iptables-ipset-proto6[iptables="iptables(){ :; }; iptables"]
```
But this has only one advantage - it would become updated together with new versions of fail2ban, but it is also a bit ugly (you have to check there are no some dependencies in future version of action that you possibly have to overwrite too), so I'd perhaps write own action instead.
