### ISSUE TITLE
Filter for Lighttpd

### ISSUE THREAD

**Issue by dcaccount** [fail2ban/fail2ban#2675]
Hello,

I am using Lighttpd as https web server. Unfortunately the standard jail.conf file does not include any filter for Lighttpd web server.

Can you please help and advise a Fail2Ban filter for Lighttpd as https web server?

Thanks,
Dan

**Comment by sebres** [comment]
Hmm... What do you mean exactly?
[filter.d/lighttpd-auth.conf](https://github.com/fail2ban/fail2ban/blob/0.9/config/filter.d/lighttpd-auth.conf) is included since 8 years (initially in b6d9f795dca4783c84cf57a9e56c551e4fa09905) at least for auth-concerns.
If you need more or something other:
1. please follow our issue template
2. provide an example (log- or journal-excerpt containing failure messages, log name, etc. pp)

Closed unless more info provided.
