### ISSUE TITLE
Migrate to python3

### ISSUE THREAD

**Issue by soltysek** [fail2ban/fail2ban#2690]
As python2 is no longer supported maybe it's time to migrate code base to python3? As far as I can see changes made by 2to3 tool are in many cases backward compatible. To have support for python2 or import from "future" / using six / simple if..else hack can be used. 
IMHO having support for both version is better than to remember to use some 2to3 script before installing. I can of course make PR with needed changes after this issue is 'blesses' by maintainers ;)

**Comment by sebres** [comment]
> To have support for python2 or import from "future" / using six / simple if..else hack can be used.

- as for six, I don't think that introducing still one layer (to solve compatibility issues) is a good idea at all.
- as for if..else hack, unfortunately it is hardly possible due to invalid syntax at a compile time point (not at run-time)... For example you'd not be able to compile with python2 a file containing constructs like this (due to SyntaxError during compilation process):
```python
if sys.version_info >= (3,):
  {n:v for n,v in {'a':1, 'b':2, 'c':3}.items()}
```
> IMHO having support for both version is better than to remember to use some 2to3 script before installing. 

But as one can see for above-mentioned reason you're quasi suggesting now vice versa handling (e. g. 3to2) "before installing".

Sure sometimes it will be time to switch to 3.x, but I'm still not sure it is now.

**Comment by soltysek** [comment]
Sure it was only my suggestion. You'll do what is the best for project.

**Comment by dwfreed** [comment]
All distros that still have python2 are working on removing it.  Python2 went EOL at the start of 2020.  The time to convert to python3 was before python2 went EOL, so you're long overdue.  Finalize the conversion and remove the 2to3 usage in setup.py.

**Comment by sebres** [comment]
And now think about some hardware boxes like routers, etc as well as some IoT-capable hardware.
Many of them will never get an upgrade to new distribution. Not to mention the certain performance "degradation" and resources declines if switching to 3.x on a not so powerful hardware.
Official support for Python 2.6 has ended 2013, but I'm still seeing people using it in some old boxes.

Unless I'll see important reasons to switch to 3.x solely, we will retain 2.x support, at least for python 2.7.
Let alone there are many other tasks with much higher precedence.
