### ISSUE TITLE
why does the datetime format not support?

### ISSUE THREAD

**Issue by daxue2017** [fail2ban/fail2ban#2692]
in the log file fail2ban.log,   it show  the date time format "20200414072453.886092" is not valid. 
the date time format is  "yyyymmddHHMMSS.microsecond"。
why does the datetime format not support? 
how can i modify the code to support this date time format?

**Comment by sebres** [comment]
People, I'll simply close the issues that does not follow our issue template.
You did not provide fail2ban version, how and where exactly you specify the custom `datepattern`, etc pp.

Shortly, for "how to set a datepattern" take a look in the documentation or at similar issues like #2193 or #2637, etc.

Your datepattern would be something like `%Y%m%d%H%M%S\.%f` (note you have to use `%%` instead of `%` in config files). Here is the test using fail2ban-regex:
```
$ fail2ban-regex -v -d '%Y%m%d%H%M%S\.%f' '20200414072453.886092 test 192.0.2.1' '^ test <HOST>'

Running tests
=============

Use      datepattern : YearMonthDay24hourMinuteSecond\.Microseconds
Use   failregex line : ^ test <HOST>
Use      single line : 20200414072453.886092 test 192.0.2.1


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^ test <HOST>
|      192.0.2.1  Tue Apr 14 07:24:53 2020
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] YearMonthDay24hourMinuteSecond\.Microseconds
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```
