### ISSUE TITLE
<bantime> breaks for actionstart/actionend since 0.11

### ISSUE THREAD

**Issue by AndCycle** [fail2ban/fail2ban#2710]
### Environment:
Gentoo
net-analyzer/fail2ban-0.11.1-r2

### The issue:
as Gentoo linux recently make 0.11.1 version stable I just upgrade the package,
there are behavior change in 0.11 around action parsing
here is a snippet I do for a custom action
which involve `xt_recent` that require setup match time
```
actionstart = if [ `id -u` -eq 0 ]; then \
                modprobe xt_recent; \
                modprobe xt_TARPIT; \
                iptables -t raw -C PREROUTING -p tcp -j f2b-recent-notrack || (iptables -t raw -N f2b-recent-notrack && iptables -t raw -I PREROUTING -p tcp -j f2b-recent-notrack); \
                iptables -t raw -A f2b-recent-notrack -p tcp -m recent --update --seconds <bantime> --name f2b-<name> -j NOTRACK; \
                iptables -C INPUT -j f2b-recent-blackhole || (iptables -N f2b-recent-blackhole && iptables -I f2b-recent-blackhole -j REJECT); \
                iptables -C INPUT -j f2b-recent-check || (iptables -N f2b-recent-check && iptables -I INPUT -j f2b-recent-check); \
                iptables -A f2b-recent-check -m recent --update --seconds <bantime> --name f2b-<name> -j f2b-recent-blackhole; \
              fi
```
which works perfectly fine in 0.10.4 but breaks in 0.11.1

fail2ban.log
```
2020-05-04 18:58:31,352 fail2ban.utils          [28242]: ERROR   7f8e88001df0 -- exec: if [ `id -u` -eq 0 ]; then \
modprobe xt_recent; \
modprobe xt_TARPIT; \
iptables -t raw -C PREROUTING -p tcp -j f2b-recent-notrack || (iptables -t raw -N f2b-recent-notrack && iptables -t raw -I PREROUTING -p tcp -j f2b-recent-notrack); \
iptables -t raw -A f2b-recent-notrack -p tcp -m recent --update --seconds <bantime> --name f2b-courier-500 -j NOTRACK; \
iptables -C INPUT -j f2b-recent-blackhole || (iptables -N f2b-recent-blackhole && iptables -I f2b-recent-blackhole -j REJECT); \
iptables -C INPUT -j f2b-recent-check || (iptables -N f2b-recent-check && iptables -I INPUT -j f2b-recent-check); \
iptables -A f2b-recent-check -m recent --update --seconds <bantime> --name f2b-courier-500 -j f2b-recent-blackhole; \
fi
```

**Comment by sebres** [comment]
> there are behavior change in 0.11 around action parsing

No... unfortunately this has nothing with action parsing.
Since 0.11 `<bantime>` is a **dynamic value** (see #1416) that is depending on the ticket (IP address), which is not available in `actionstart` or `actionstop`. 
Previously it was fixed value of a jail, which was (undocumented) directly supplied to the actions.

Possibly we could check whether it would be possible to restore previous behavior if `bantime.increment` is not enabled.

> which involve xt_recent that require setup match time

Such timeouts that are not controlled by fail2ban may be worse and cause too many issues.
I'd recommend to use some persistent handling in xt_recent and leave the ticket expiration to the fail2ban (e. g. remove it via `echo -<ip> >/proc/net/xt_recent/...` in actionunban).
Also note that if `bantime.increment` is enabled, it can also be necessary to extend the action with `actionprolong` parameter (because prolongation takes place asynchronously and `bantime` can be not yet calculated if `actionban` executed).

**Comment by AndCycle** [comment]
thanks for the detail around the implementation and advise, 
it's clear how I should change my usage around xt_recent.
