### ISSUE TITLE
iptables ban rule in different chain/table

### ISSUE THREAD

**Issue by cc2** [fail2ban/fail2ban#2735]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"

### The issue:
I want to change the default behavior for sshd ban and instead of using iptables rules use ipset. It works pretty well except I don't want the rule to be added in INPUT, I want it in RAW/PREROUTING.
So I copied iptables-ipset-proto4.conf to a new file and then modified the action start command from:

<iptables> -I INPUT

to 

 <iptables> -t raw -I PREROUTING

it seems that it doesn't add the iptables rule there. I tested it few times without luck.

#### Steps to reproduce
make a copy of this file: iptables-ipset-proto4.conf
i used iptables-ipset-proto4-customized.conf

change the default action in your jail file

change the line that start with <iptables> -I <chain> in actionstart to <iptables> -t raw -I PREROUTING

#### Expected behavior
to add the rule to raw/prerouting instead of input

#### Observed behavior

doesn't add it

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
> it seems that it doesn't add the iptables rule there. I tested it few times without luck.
> Observed behavior: doesn't add it

What exactly do you mean?

1. The reason why fail2ban may not add this can be simply - still no ban in related jails.
Due to IPv6 functionality support, many actions (inclusive iptables) are rewritten so the `actionstart` is executed on demand by the first start.
If you need that this going executed immediately by start of jail, you have to specify `actionstart_on_demand=false`, see #1742.
In this case it has nothing to do with your customization - it is normal fail2ban behavior since 0.10.

2. If it failed (you have some error in fail2ban.log) by execution of actionstart, please provide the excerpt here.

To check which values (resulting commands) you will get after your customizations you can use dump:
```
fail2ban-client -d | grep "$somejail"
```
Please provide this output if you have further questions.

Normally all iptables action have a common include [iptables-common.conf](https://github.com/fail2ban/fail2ban/blob/0.10/config/action.d/iptables-common.conf), so normally it'd be enough to specify parameters declared there.

For example either directly in jail:
```ini
banaction = iptables-ipset-proto4[lockingopt="-w -t raw", chain="PREROUTING"]
```
or in related custom action of you:
```ini
[INCLUDES]
before = iptables-ipset-proto4.conf
[Init]
lockingopt = %(known/lockingopt)s -t raw
chain = INPUT
```

You can also create a completely new action fully implementing your needs without any includes of us.

**Comment by sebres** [comment]
Also note that you have to **restart** jail/fail2ban by action modifications, because a **reload** wouldn't affect already executed commands (started actions of started jails and already banned tickets).
