### ISSUE TITLE
what is the difference between "filter" and "failregex" in custom jail configuration?

### ISSUE THREAD

**Issue by lokha** [fail2ban/fail2ban#2747]
I configure jail in /etc/fail2ban/jail.d

I used to always use filter and had to create files in /etc/fail2ban/filter.d

But today I read in this documentation https://manpages.debian.org/testing/fail2ban/jail.conf.5.en.html
you can specify failregex directly in the prison file in /etc/fail2ban/jail.d

What is the difference? Which is better to use?

**Comment by sebres** [comment]
Before v.0.10 many parameters of filter (like `datepattern`) ware possible only in the filter.
Since v.0.10 all such parameters (provided from filter) can be set in jail directly.
Thus filter is optional now (you have then to set it to empty value, like `filter =`) and `failregex`, `datepattern`, etc can be simply specified in some of your jails.
Filter has only few advantages at the moment:
- this is the way how standard jails are provided with distribution (and can be replaced from maintainer);
- filter can have some options (and some internal substitution would not bother some jail parameters (e.g. so can avoid potential name conflicts);
- filter (with its whole definition and local mods) is usable as parameter for `fail2ban-regex`, jail is not (at least at the moment, see https://github.com/fail2ban/fail2ban/issues/2655#issuecomment-597523960).
For example, this means a filter not jail:
```bash
fail2ban-regex systemd-journal 'sshd[mode=aggressive]'
```
- same filter can be used by several jails (e.g. with different parameters), for instance:
```ini
[jail1]
filter = some-filter[mode=aggressive, service=pam]
[jail2]
maxretry = 20
filter = some-filter[mode=ddos, service="\S+"]
```

**Comment by lokha** [comment]
Thanks for the answer, someday I will create my version of the fail2ban documentation where I will describe all the details :)

An empty value "filter =" is required to set? Is this to override the default value?
