### ISSUE TITLE
fail2ban regex flags

### ISSUE THREAD

**Issue by woodholly** [fail2ban/fail2ban#2762]
How to change failregex/ignoreregex regex flags ?
fail2ban uses python regex's, I want to use re.X (re.VERBOSE) flag to make filters more readable.
How can I do that ?

**Comment by sebres** [comment]
> How to change failregex/ignoreregex regex flags ?
>  I want to use re.X (re.VERBOSE) flag to make filters more readable. How can I do that ?

One can supply flags using `(?...)` prefix, so you could specify prefix `(?x)` in regex for verbose flag, see https://docs.python.org/2.7/library/re.html#regular-expression-syntax

But you would not be able to supply multiline regex, because fail2ban would assume multiple regex's in this case (every line represents single re). So it is simply impossible to supply such commented RE to fail2ban via filter- or jail-config:
```regex
(?x)^\s+<ADDR>    # the address of evildoer
\s+ERROR          # level
\s+auth\s+failure # message
```

So although there is a possibility to use that with `fail2ban-regex` (supply it as an argument).
```bash
fail2ban-regex '2020-06-22T13:00:00 192.0.2.1 ERROR auth failure' '(?x)
^\s+<ADDR>        # the address of evildoer
\s+ERROR          # level
\s+auth\s+failure # message'
```
But there is no such possibility for the usage in server (as part of filter-file).

**Comment by woodholly** [comment]
@sebres I hope this can be fixed or added as a new feature.

**Why?**
Let's take as an example this filter: https://github.com/mitchellkrogza/Fail2Ban.WebExploits/blob/master/webexploits.conf:
```python
failregex = ^<HOST> -.*(GET|POST|HEAD).*(/\.git/config)
            ^<HOST> -.*(GET|POST).*/administrator/index\.php.*500
            ^<HOST> -.*(GET|POST|HEAD).*(/:8880/)
            ^<HOST> -.*(GET|POST|HEAD).*(/addons/theme/stv1/_static/image/favicon\.ico)
            .... and 180 more similar regexes
```

It has many very similar regexes and works as intended but is very very slow (1 CPU core processes 200 log lines per second). It is so slow that attacker can use it to DDOS website using it :-)
This slowness happens because regexes are processed one by one.
It is possible to increase speed of processing by replacing many regexes with one large regex:

```python
failregex = ^<HOST> -.*(GET|POST|HEAD).*(/\.git/config|/administrator/index\.php.*500|/:8880/|/addons/theme/stv1/_static/image/favicon\.ico|...)
```
This simple method makes processing 12 times faster.

So. Now you can see why I want verbose flag. This single-line large regex is unreadable and unmaintainable. If only verbose flag was available, I would use this instead:
```python
failregex_flags = wx
failregex = ^<HOST> -.*(GET|POST|HEAD).*(
            /\.git/config
            | /administrator/index\.php.*500
            # some comment
            | /:8880/
            | /addons/theme/stv1/_static/image/favicon\.ico # more comments
            | ....)
```

As you can see, single regex flag makes huge changes and increases readability without sacrificing speed.

**Comment by sebres** [comment]
>  I hope this can be fixed or added as a new feature.

This is simply impossible as long as NL-char remains as separator for multiple regex's in our ini-file.
Sure, one could implement some parameter like `singleregex = 1` to signal single regex, but why? (see below).

> This slowness happens because regexes are processed one by one.

Sure, but it is not only reason, because...

> `^<HOST> -.*(GET|POST|HEAD).*( ...`

... I see two catch-all's here, so it is not vulnerable only, but also extremely slow.
Better is it to rewrite the regex as more precise without catch-alls as well as with some prefregex, for example:
```diff
-failregex = ^<HOST> -.*(GET|POST|HEAD).*( ...
-            ^<HOST> -.*(GET|POST|HEAD).*( ...
-            ^<HOST> -.*(GET|POST|HEAD).*( ...
+prefregex = ^<HOST> -[^"]*\"(?:GET|POST|HEAD)\s+<F-CONTENT>\S+</F-CONTENT> HTTP/[^"]+" 40\d\s\d+
+failregex = ^...
+            ^...
+            ^...
```

> This single-line large regex is unreadable and unmaintainable. 

You can do it more readable using some substitutes (`<prm>` or `%(prm)s`):
```ini
# _req_method = (?:GET|POST|HEAD|...)
_req_method = [A-Z]{3,}
# _req_code = (?:404|...)
_req_code = (?!401)[345]0\d\s
prefregex = ^<HOST> -[^"]*\"%(_req_method)s\s+/<F-CONTENT>\S+</F-CONTENT> HTTP/[^"]+" (?:%(_req_code)s)\s
_bad1 = \.git/config|/administrator/index\.php.*500|:8880/|addons/theme/stv1/_static/image/favicon\.ico
_bad2 = ...
# failregex = <HOST> -[^"]*\"%(_req_method)s\s+/(?:<_bad1>|<_bad2>|...)
failregex = (?:<_bad1>|<_bad2>|...)
```
But, basically I don't see the necessity for such filters at all, so instead of provide many blacklisted URI's, since one knows which application or URI-prefixes are valid, better would be to provide single location logging all "invalid" URI's in separate log-file to let fail2ban consider all them as failures, see https://github.com/fail2ban/fail2ban/issues/2583#issuecomment-569664487 and bellow.

**Comment by sebres** [comment]
Oh... I think I found also a workaround for your "new feature"...
Since `prefregex` (implemented in fail2ban >= 0.10) is a single line regex, it is indeed possible, so you could place your verbose regex inside that with some artificial empty `failregex` (that always matches):
```ini
prefregex = (?x)^<HOST> ...
            first line # some first line
            second line # some second line
            ...
failregex = 
```

**Comment by woodholly** [comment]
Thanks, I know about .*, and nginx location -> log -> fail2ban will be much faster. Substitutes also do the job, but make spaghetti from config :-)
**prefregex solves the problem, very good!**

**Comment by woodholly** [comment]
Small fix - failregex requires something to match, so it should be:
```python
prefregex = (?x)^<HOST>\s-...
            first line # some first line
            second line # some second line
            ...
failregex = .

```

**Comment by sebres** [comment]
OK, an empty regex matches always, but an empty failregex would cause empty list of regex, so doesn't enter matching cycle, I guess.
Maybe `failregex = ^` could be better in this case.

**Comment by lars44** [comment]
Is there a recent version of  webexploits.conf ?
