### ISSUE TITLE
Fail2ban works only for log entries with atomic writes.

### ISSUE THREAD

**Issue by dElogics** [fail2ban/fail2ban#2766]
It seems, when the logs are written 'slowly', fail2ban misses the logs. A test case is as such -- 

echo -n '1.1.1.1 a succes' >> logfile
--------wait for a few seconds----------
echo 'sful ban pattern' >> logfile

Even if the pattern is '<host> a successful ban pattern' fail2ban will not register this as a match, but this -- 

echo -n '1.1.1.1 a successful ban pattern' >> logfile

Will result in a successful ban.

This type of scenario arises when logs are written in a common log server and the writes are in 'blocks' (assumed as as binary data) instead of lines; this is the case here.

Expected behavior is for fail2ban to wait for a newline before processing it; before that it may keep it internally in it's buffers.

**Comment by sebres** [comment]
> It seems, when the logs are written 'slowly', fail2ban misses the logs. 

Nope, rather it is a invalid logging that causing that.
Logging which is organized with flush after each partial output is "broken" per design and doomed to fail, beginning with (inter)locking and ending with mixed content in the log.

For example think about multi-processing (multi-threading) or other asynchronous issues you may get in such a logs:
- 1st processing noticed success, so wrote `192.0.2.111 ` and `OK pattern` few seconds later.
- 2nd processing noticed failure, so wrote `192.0.2.222 ` and `Fail pattern` few seconds later.
Now what you'll see in log is not determinated, because it depends on how long is this "few" (time in between) and in worse case you'd even get `192.0.2.111 Fail pattern`, what is totally wrong (because this IP did not generated a failure).

> Expected behavior is for fail2ban to wait for a newline before processing it; before that it may keep it internally in it's buffers.

No. The program logging that, must either implement the logging process using line-buffering mode, so flush the buffers by new-line only ("keep it internally in its buffers").
Or (not a good practice, but possible) it could generate 2 lines (with some common unique identifier), for example like sshd doing that:
```
Apr 27 13:02:01 host sshd[29116]: Connection from 192.0.2.4 port 55555
Apr 27 13:02:02 host sshd[29116]: User root not allowed because account is locked
```
and fail2ban is able to process that using multi-line handling in filter:
```
fail2ban-regex -o row /tmp/log-excerpt sshd
['192.0.2.4',   1587985322.0,   {'ip4': '192.0.2.4', 'ip6': None, 'user': 'root', 'dns': None, 'users': set(['root']), 'mlfid': ' host sshd[29116]: '}],
```
But as already said better would be to write it as single-line with IP in every line.

**Comment by sebres** [comment]
There is a workaround you could use for that - use `maxlines = 2` for this jail (or filter) to define the size of buffer window as 2 lines.
Just it is a bit slower as a single line processing as well as you may notice some messages a bit later due to internal handling for such processing.

**Comment by dElogics** [comment]
The logging in on NFS, maybe that's why it's giving so much problems. This's a cluster actually with 100s of applications running.

Regardless, I made a script which makes the writes atomic.

Thanks for the clarification.
