### ISSUE TITLE
new standard jail recidive-subnet 

### ISSUE THREAD

**Issue by ruppel** [fail2ban/fail2ban#2775]
disclaimer:
I am only a user of fail2ban and happy that i managed to install it on my server on got it running...
So, i'm not the one to start deep technical discussions :-)

What I can see in the mails from fail2ban, that I ban a lot of ip's from the same subnet (currently 46.38.150.0/24).
I know, somehow it is possible to ban a subnet, but it seems all to complicated for me.
And perhaps there are (magical) ways to let fail2ban detect those subnets, but they are much more complicated to me...

I would like to suggest a standard jail called recidive-subnet.
Like the recidive jail, it could scan the fail2ban log.
Additional parameter could be:
maxips = the number of bans on different ips of the same subnet before the subnet get banned

How about?

**Comment by sebres** [comment]
We have already several issues about this with good stuff in discussions inside (e. g. #927).
Please let us continue there. Thus closed in order to avoid duplicates..

As for recidive-subnet jail - the idea is possibly not so bad (as an interim solution), just at the moment fail2ban can't match subnet of address prefixes (e. g. scanning of fail2ban log to consider repeated IP prefixes is impossible), because `192.0.2` would be invalid address, only `<ADDR>` (`192.0.2.1`), `<ADDR>/<CIDR>` or `<SUBNET>` (`192.0.2.0/24`) are supported at the moment in regex.
Also note that to implement #927, fail2ban misses currently only the logic to detect a subnet from a couple of banned IP addresses (either expand them to a subnet or cumulate and calculate attempt count of whole subnet directly by failure arriving).
Approximately almost the same logic (at RE-level) your recidive jail would need to work, but once it gets implemented such recidive jail will be not needed.

What one perhaps could do, were to scan fail2ban's sqlite-database for a subnet (e. g. in actionban), something like 
`select count(ip) from bans where ip like '`192.0.2.%' and ip != '192.0.2.1'` 
and ban a whole subnet by finding with count over some threshold.

Anyway since I don't like workarounds, I'll prefer some regular and well thought out solution instead.
