### ISSUE TITLE
fail2ban-client get banip --with-time fails for jails with infinite ban times

### ISSUE THREAD

**Issue by mgrant0** [fail2ban/fail2ban#2817]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.11.1-2
- OS, including release name/version: Debian bullseye/sid
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

fail2ban-client get banip --with-time fails for jails with infinite ban times

#### Steps to reproduce

Set this in a jail, for example, in recedive:

[recedive]
bantime  = -1

then (with at least one entry in this jail):

% fail2ban-client get recidive banip --with-time 
2020-08-26 07:15:49,999 fail2ban                [16303]: ERROR   NOK: ('year 4461763 is out of range',)
year 4461763 is out of range

#### Expected behavior

Here are some possible suggestions:

192.168.1.2  2020-08-26 07:08:59 + INFINITY = FOREVER

192.168.1.2  2020-08-26 07:08:59 + Infinity = 9999-12-31 23:59:59

192.168.1.2  2020-08-26 07:08:59 + ∞ = 9999-12-31 23:59:59

Clearly 'INFINITY' and 'FOREVER' are English terms, should they be localizable?  I have seen 'Infinity' used in JavaScript and SQL and some other languages.  The ∞ character is a multi-byte unicode character, may not be the best choice here but it looks nice!

The second version above (192.168.1.2  2020-08-26 07:08:59 + Infinity = 9999-12-31 23:59:59) is my favorite.

#### Observed behavior

2020-08-26 07:15:49,999 fail2ban                [16303]: ERROR   NOK: ('year 4461763 is out of range',)
year 4461763 is out of range

#### Any customizations done to /etc/fail2ban/ configuration
```
[recidive]
enabled = true
bantime  = -1
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
Fixed in be3115cda0c5ab7def871256995974880221683d.

BTW, neither usage of recidive jail, nor persistent ban is advisable at all, especially in 0.11th branch (with `bantime.increment` feature) - it would just unneeded eat system resources (as well as with time will make network sub-system slower), not to mention an overreaction for possible false positive on some constellation.
Normally even with incremental banning something like `bantime.maxtime = 5w` is really enough - almost all evildoers disappear if get banned several times for 5 weeks (and if don't - 5w is a extremely large bantime to succeed a bruteforce).
