### ISSUE TITLE
"prefregex" is critical and used everywhere, but undocumented

### ISSUE THREAD

**Issue by jcea** [fail2ban/fail2ban#2820]
After wasting an afternoon trying to understand why my REGEX was fine in "fail2ban-regex" but failed to match anything in production, I studied the source-code and I discovered "prefregex".

I was stunned that such an important issue is completely undocumented and not even accessible via "fail2ban-client" HELP info, although "fail2ban-client get JAIL prefregex" works (not documented anywhere).

Also, "fail2ban-regex" worse than useless if the jail uses "prefregex" (important if you are just doing tiny changes via ".local" files).

Thanks for your time and effort.

**Comment by sebres** [comment]
> my REGEX was fine in "fail2ban-regex" but failed to match anything in production

How so? fail2ban-regex with failregex directly would not consider filter parameters (so not a prefregex only, but ALL parameters).
If you was working on the filter you'd see the prefregex immediately above of failregex.
If you was on the failregex to provide it directly in jail, you don't need the filter at all (so no prefregex will be set for that jail). 

> After wasting an afternoon ...
>  I studied the source-code and I discovered "prefregex".

So it's not a wasting - you've learned something new now :)

> Also, "fail2ban-regex" worse than useless if the jail uses "prefregex" (important if you are just doing tiny changes via ".local" files).

Well yes, at the moment fail2ban-regex does not consider the jail parameters at all (see #2565) 
But no, you can test your local changes of filter with `fail2ban-regex "$msg_or_journal" "$filter_name"`, for example make your tiny changes in filter.d/sshd.local and test it using this:
```
fail2ban-regex systemd-journal sshd
```
And you can test your failregex (as well as some other parameters of filter) together with `prefregex` specified in filter, for example:
```bash
$ msg='2020-08-24T15:43:03 srv sshd[12345] Broken publickey for test from 192.0.2.1 port 55555 ssh2'
$ fail2ban-regex -o row "$msg" sshd[failregex='^Broken publickey for <F-USER>\S+</F-USER> from <ADDR>']
['192.0.2.1',   1598276583.0,   {'user': 'test', 'ip6': None, 'users': set(['test']), 'ip4': '192.0.2.1', 'mlfid': ' srv sshd[12345] '}],
```

> "prefregex" is critical and used everywhere, but undocumented

Indeed (and we definitely need to close this lack).

*By the way, I am nevertheless confident that at some point, I'll hopefully see someone that instead of complaining about missing documentation would provide a pull request with such documentation enhancements.
The great thing about open source is that everyone can contribute to the projects (inclusive or even especially to its documentation or wiki).*

**Comment by sebres** [comment]
FWIW some small description in #2837.

**Comment by egberts** [comment]
> FWIW some small description in #2837.

OK.  I've updated the "HOWTO" document  in [wiki/Developing-Regex-in-Fail2ban](https://github.com/fail2ban/fail2ban/wiki/Developing-Regex-in-Fail2ban)

**Comment by sebres** [comment]
documentation is extended in 5d0e74d2ab8980356b6a6cb2760b43945e4e34b3
