### ISSUE TITLE
Feature Request: Enhance fail2ban-client to modify ignoreip across all jails

### ISSUE THREAD

**Issue by iCounsellorUK** [fail2ban/fail2ban#2825]
In the [DEFAULT] section of both _jail.conf_ and _jail.local_ there is the entry: _**ignoreip**_

```
# "ignoreip" can be an IP address, a CIDR mask or a DNS host
ignoreip = 127.0.0.1 109.123.86.227 109.123.86.0/24
```
Unlike individual jails, though, where the jail's list of IP addresses to be ignored can be modified with fail2ban-client (aka: set -JAIL- addignoreip -IP-), the default _ignoreip_ cannot be modified via fail2ban-client.

My broadband connection occasionally changes my home/office IP address (even though the change may not occur for a couple of weeks), and there are times when I need fail2ban to ignore my home/office IP address throughout all jails.

Currently, the only way to update _ignoreip_ is to modify jail.local and restart the fail2ban server.
 
Currently using fail2ban version 0.11.1

**Comment by sebres** [comment]
There are several option you can use for that already now:

1. You can modify default of jail.local or even some include-file, that you would include in jail.local, and then use `fail2ban-client reload` to supply it to fail2ban (without restart and interim unban/ban), but it'd do nothing else as supply this for every jail with `addignoreip` (besides all other parameters).
2. You could specify some dynamic DNS instead of IP for `ignoreip`, if you have that (so it'll be refreshed if DNS entry gets updated with new IP).
3. You can use common `ignorecommand` (together with `ignorecache` to speedup the lookup. see #2176), so you don't need to update it in fail2ban at all.
4. You can write a script using scenario like that:
```bash
for each jail do
  fail2ban-client set "$jail" delignoreip "$oldip"
  fail2ban-client set "$jail" addignoreip "$newip"
end
```

From other point of view, we can extend fail2ban-client with new logic doing that, for instance as something like:
`fail2ban-client set --all addignoreip $ip`
but it would not really correspond the handling updating default section with final reload - it'd rather mean set some parameter across all jails.
I don't think that a special set/update handling for default section parameters is possible at all to be implemented properly, at least for the reason that many parameters are used even as default only, parts of other parameters or includes, etc.
For all this cases `fail2ban-client reload` has been implemented.

**Comment by iCounsellorUK** [comment]
_fail2ban-client reload_

Doh! I did scan fail2ban-client's options but my brain didn't catch on that reload bypassed the interim unban/ban process whilst applying the new configuration.

That's the solution for me for now.

Solution #4 looks interesting (I've written a 3rd-party script that calls fail2ban-client to dynamically & temporarily modify jail settings when server hits/attacks/DOS get a little crazy - I'll document that elsewhere, rather than here).


Thank you 👍🏻
