### ISSUE TITLE
bans.bantime may not be NULL

### ISSUE THREAD

**Issue by Copyrght** [fail2ban/fail2ban#2828]
Hi. After reinstalling fail2ban i cant manually ban an ip. I got error - bans.bantime may not be NULL after command - fail2ban-client set JAIL banip xx.xx.xx.xx. There is my jail:

[sasl]

enabled = true
filter = postfix-sasl
action = iptables-allports[name=SASL]
         sendmail-whois[name=SASL, sender="xx@xx.xx", dest="xx@xx.xx"]
logpath = /var/log/zimbra.log
bantime = -1
maxretry = 5

Fail2ban version 0.9.6

**Comment by sebres** [comment]
> After reinstalling fail2ban ... I got error - bans.bantime may not be NULL

Well, I guess you have previously installed fail2ban 0.11 (which did upgrade a sqlite-database of fail2ban), and then switched back to 0.10.
There is no downgrade of database to be 0.10 compliant available, so you have to delete `/var/lib/fail2ban/fail2ban.sqlite3` or whatever is set in `/etc/fail2ban/fail2ban.conf` or .local
https://github.com/fail2ban/fail2ban/blob/08dbe4abd593c09be8be9101964c2ee1915374f5/config/fail2ban.conf#L64
the database will be automatically created by start again...
```
fail2ban-client stop
rm /var/lib/fail2ban/fail2ban.sqlite3
fail2ban-client start
```
Just note that after this restart fail2ban will scan all your log-files for all enabled jails from scratch (because it does not known the last position previously stored in database too), so if they are large it could take some time, so it is advisable to force a log-rotate for large logs before a restart.

If you're familiar, for manually backup/restore of positions for logs (tables `jails` and `logs`) you can use following scripts (stop fail2ban before doing that):
<details>

```bash
dbpath='/var/lib/fail2ban/fail2ban.sqlite3'

# backup:
sudo sqlite3 "$dbpath" .dump | grep -E '^INSERT INTO .(logs|jails).' > /tmp/f2b-tab.bckp

# delete database:
sudo rm "$dbpath"
# (re)create db:
sudo fail2ban-python -c "dbpath='$dbpath'; import sys, logging; logging.basicConfig(stream=sys.stdout, level=logging.DEBUG); from fail2ban.server.database import Fail2BanDb; db = Fail2BanDb(dbpath); print('ready');"

# restore:
sudo sqlite3 "$dbpath" < /tmp/f2b-tab.bckp
```
</details>
