### ISSUE TITLE
(Shaun's) helper PHP script

### ISSUE THREAD

**Issue by digidax** [fail2ban/fail2ban#2829]
Using action.d/abuseipdb.conf for reporting, but there are in comment too many details like host or IP adresses of my system
The link in abuseipdb.conf : [https://wiki.shaunc.com/wikka.php?wakka=ReportingToAbuseIPDBWithFail2Ban](https://wiki.shaunc.com/wikka.php?wakka=ReportingToAbuseIPDBWithFail2Ban) isn't working. 

How can I control the data wich are sent in the comment part?

**Comment by sebres** [comment]
> The link in abuseipdb.conf ... isn't working.

This link is initially there (so old and can be indeed broken in the mean time). I'll remove it later.
But it has basically nothing with your issue - "there are in comment too many details" (I guess the comment was added later to action abuseipdb).

> How can I control the data wich are sent in the comment part?

The data sent in comment (in current version shorten to 1000 chars) coming from `<matches>` tag, see:
https://github.com/fail2ban/fail2ban/blob/3d4044084af143c0ec04f707ecb20315a7eb5a64/config/action.d/abuseipdb.conf#L89

The solution would be to replace tag `<matches>` (failure lines from log or journal stored in banned ticket):
 - in newer versions of fail2ban you can just set it as action parameter (so it would overwrite the ticket value during execution), for example:
```ini
[jail]
action = %(action_)s
         abuseipdb[matches="from fail2ban", abuseipdb_apikey="my-key"]
```
- otherwise (older fail2ban version can completely ignore init parameter `matches`), you have to rewrite `actionban` in `action.d/abuseipdb.local` to remove the tag `<matches>` or to filter info in tag `<matches>` with some expression.

**Comment by GwynethLlewelyn** [comment]
For those having the same question in the future, even though this issue has been closed: Shaun Cummiskey aka @parseword, the author of this AbuseIPDB action, has indeed taken his Wiki down, but the Wayback Machine still finds a copy of it from 2019: https://web.archive.org/web/20190123052042/https://wiki.shaunc.com/wikka.php?wakka=ReportingToAbuseIPDBWithFail2Ban

That page includes the mentioned PHP script.

**_Note:_** In the (unlikely) case _that_ link goes down, I've attached [a print of that page](https://github.com/fail2ban/fail2ban/files/7738170/Reporting.to.AbuseIPDB.com.with.Fail2ban_Shaun.s.Brain.Backup.pdf), saved as PDF, for future reference. It's not clear to me if Shaun intended that page to be included on the Wayback Machine or not; he explicitly blocked `ia_archiver` from crawling his old Wiki. However, for many years at least, _both_ the Internet Archive and the [Alexa site indexer](https://alexa.com/) used that same user-agent — because allegedly the same person ran both and thus shared the same crawler — so it's not clear what Shaun's intended purpose was: to block Alexa or block the Internet Archive. If the latter is the case, I'll remove the enclosed PDF; the original page doesn't say under which license it has been made available, so one must assume that it _might_ be protected under full copyright laws, although some parts of it — namely, the action script itself — have been distributed under the same license as fail2ban itself (e.g. the [GNU General Public License v2.0](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html)).

In any case, Amazon announced that [they will soon discontinue the Alexa service](https://support.alexa.com/hc/en-us/articles/4410503838999) anyway...

**Comment by lyh16** [comment]
Just following up on this issue to report that I've been able to contact Shaun(@parseword) concerning @GwynethLlewelyn 's point, who confirmed that it was his intention for the code provided in his original wiki to be open source. He has also been kind enough to upload an enhanced version of this PHP script to [Github](https://github.com/parseword/fail2ban-abuseipdb) under a GPLv2 license, which matches that of fail2ban.
