### ISSUE TITLE
554 5.7.1 Client host rejected: cannot find your hostname not matching

### ISSUE THREAD

**Issue by digidax** [fail2ban/fail2ban#2832]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): 
- OS, including release name/version:  CentOS 7.8, fail2ban: 0.11.1-10.el7
- [ X] Fail2Ban installed via OS/distribution mechanisms by yum
- [ X] You have not applied any additional foreign patches to the codebase

### The issue:
Postfix 2:2.10.1-9.el7 log: /var/log/maillog line:
`Sep 23 06:31:40 farm11 postfix/smtpd[27085]: NOQUEUE: reject: RCPT from unknown[186.86.32.126]: 554 5.7.1 Client host rejected: cannot find your hostname, [186.86.32.126]; from=<akzumeca@gmailsdfd.net> to=<foo@domain.com> proto=ESMTP helo=<dynamic-ip-1868632126.cable.net.co>`

Used filter: /etc/fail2ban/filter.d/postfix.conf
mdre-normal:

`^RCPT from [^[]*\[<HOST>\]%(_port)s: 45[04] 4\.7\.\d+ (?:Service unavailable\b|Client host rejected: cannot find your (reverse )?hostname\b)`

#### Steps to reproduce
`# fail2ban-regex 'Sep 23 06:31:40 farm11 postfix/smtpd[27085]: NOQUEUE: reject: RCPT from unknown[186.86.32.126]: 554 5.7.1 Client host rejected: cannot find your hostname, [186.86.32.126]; from=<akzumeca@gmailsdfd.net> to=<foo@domain.com> proto=ESMTP helo=<dynamic-ip-1868632126.cable.net.co>' '^RCPT from [^[]*\[<HOST>\]%(_port)s: 45[04] 4\.7\.\d+ (?:Service unavailable\b|Client host rejected: cannot find your (reverse )?hostname\b)'`

Running tests
=============

Use   failregex line : ^RCPT from [^[]*\[<HOST>\]%(_port)s: 45[04] 4\.7\....
Use      single line : Sep 23 06:31:40 farm11 postfix/smtpd[27085]: NOQUE...

Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
`-

Lines: 1 lines, 0 ignored, 0 matched, 1 missed
[processed in 0.01 sec]

|- Missed line(s):
|  Sep 23 06:31:40 farm11 postfix/smtpd[27085]: NOQUEUE: reject: RCPT from unknown[186.86.32.126]: 554 5.7.1 Client host rejected: cannot find your hostname, [186.86.32.126]; from=<akzumeca@gmailsdfd.net> to=<foo@domain.com> proto=ESMTP helo=<dynamic-ip-1868632126.cable.net.co>
`
=> Filter not matching to Postfix log. Postfix uses status 554, filter is looking for 450 or 454

**Comment by sebres** [comment]
> Filter not matching to Postfix log. Postfix uses status 554, filter is looking for 450 or 454

As for 2nd regex - yes, you are right, but your message will match the first regex (any `554 5.7.1` message)
https://github.com/fail2ban/fail2ban/blob/3b2f75414cb207aacb9e88409339dcbdfabc16ad/config/filter.d/postfix.conf#L19

And this is long time there so should be already released with 0.11.1. Doesn't it really work for you?

Anyway, testing it with current version (or with the stock 0.11.1 release as well) shows the match to me:
<details>

```bash
$ fail2ban-regex "$msg" postfix
Running tests
=============

Use   failregex filter file : postfix, basedir: /etc/fail2ban/
Use      datepattern : {^LN-BEG} : Default Detectors
Use      single line : Sep 23 06:31:40 farm11 postfix/smtpd[27085]: NOQUE...


Results
=======

Prefregex: 1 total
|  ^(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel:\s?\[ *\d+\.\d+\]:?\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?postfix(-\w+)?/\w+(?:/smtp[ds])?(?:\(\S+\))?[\]\)]?:?|[\[\(]?postfix(-\w+)?/\w+(?:/smtp[ds])?(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?(?:\w+: reject:|(?:improper command pipelining|too many errors) after \S+) (?P<content>.+)$
`-

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^RCPT from [^[]*\[<HOST>\](?::\d+)?: 55[04] 5\.7\.1\s
`-
...
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```
</details>

> `fail2ban-regex "$msg" '^RCPT from ...'`

Exactly this attempt would not work, because you've used part of `failregex` based on `prefregex` (applicable on part of message cut after prefregex gets applied).
To test single RE of such filters, you could: 
- either modify filter (e. g. in local inheritance filter.d/postfix.local) and use `fail2ban-regex "$msg" postfix`
- or supply failregex as filter parameter `fail2ban-regex "$msg" 'postfix[failregex="^RCPT from ..."]'`
- or supply larger variant of failregex (together with prefregex)
