### ISSUE TITLE
Regex assistance with Nginx logs

### ISSUE THREAD

**Issue by modem7** [fail2ban/fail2ban#2833]
## Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: Docker, crazymax
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Hey guys, 

Looking to try to create a fail2ban filter so block bots trying to crawl the site. Tried the official one for Nginx, but it seems that's not quite right - I'm an absolute noob at regexes. 

```
# Fail2Ban filter to match web requests for selected URLs that don't exist
#

[INCLUDES]

# Load regexes for filtering
before = botsearch-common.conf

[Definition]

failregex = ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) \/<block> \S+\" 404 .+$
            ^ \[error\] \d+#\d+: \*\d+ (\S+ )?\"\S+\" (failed|is not found) \(2\: No such file or directory\), client\: <HOST>\, server\: \S*\, request: \"(GET|POST|HEAD) \/<block> \S+\"\, .*?$

ignoreregex =

datepattern = {^LN-BEG}%%ExY(?P<_sep>[-/.])%%m(?P=_sep)%%d[T ]%%H:%%M:%%S(?:[.,]%%f)?(?:\s*%%z)?
              ^[^\[]*\[({DATE})
              {^LN-BEG}

# DEV Notes:
# Based on apache-botsearch filter
#

```

But unfortunately this is not picking up the logs from the Nginx error or access logs. 

#### Steps to reproduce
Attempted above regex on https://pastebin.com/rckDfKbf (error log) and https://pastebin.com/TxSnyA8d (access log)

#### Expected behavior
For the IP addresses to be banned. 

#### Observed behavior
Did not ban. Probably a misconfiguration on the regex. 
#### Any customizations done to /etc/fail2ban/ configuration
```
Using this container: https://github.com/guillaumebriday/traefik-custom-error-pages
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
https://pastebin.com/aUyZrXQS
```

**Comment by sebres** [comment]
1. pastebin is not usual resource to provide log-excerpt for issues - github has own (drag&drop, select or paste them to comment or issue description) or include between 
\`\`\`
\`\`\`
2. this is developer repository and not a place for how-to's, better seek help by SO or similar forums.
3. it is not clear what you would describe as failures here, normally you've to provide an example with a row you want capture.
Whole log-analysis is a bit much more work as just "regex assistance".

As for your log excerpts, it looks like a proxying requests to me (always the same local address 172.22.0.114 as client), so you have to add remote address to some custom log format (better to some special error location). 
Also note [wiki :: Best practice -> Reduce parasitic log traffic](https://github.com/fail2ban/fail2ban/wiki/Best-practice#reduce-parasitic-log-traffic).

As for regex:
- the first one capturing any message from error-log:
```ini
[jail]
filter =
_url_pattern = [^"]*
failregex = ^\s*\[error\] (?:28|30)#\d+: \*\d+ (?:open\(\) |directory index of )?"%(_url_pattern)s" (?:(?:failed|is not found) \(2: No such file or directory\)|is forbidden), client: <ADDR>
logpath = /path/to/error.log
enabled = true
```
- the access-log is normally not really suitable directly for parsing (see the link on wiki above), because it can be too heavy (to many parasitic messages would cause high load), so you can write it in some special location or conditional; 
also it looks, like you have already some location for 404 response, so you can (and must either) write into different log-file there.
Since you can rewrite the log-format in this special nginx location, you can also use another (shorter) RE with host and some short reason (code).

**Comment by sebres** [comment]
Example of log-format for 3 types of messages matched by regex provided above:
```
2020/09/24 15:43:52 [error] 30#30: *81 directory index of "/var/www/public/" is forbidden, client: 192.0.2.1, server: , request: "GET / HTTP/1.1", host: "www.example.com"
2020/09/24 18:02:51 [error] 28#28: *84 "/var/www/public/webfig/index.php" is not found (2: No such file or directory), client: 192.0.2.1, server: , request: "GET /webfig/ HTTP/1.1", host: "192.0.2.200"
2020/09/24 18:02:52 [error] 28#28: *84 open() "/var/www/public/webfig/404.html" failed (2: No such file or directory), client: 192.0.2.1, server: , request: "GET /webfig/404.html HTTP/1.1", host: "80.4.200.39", referrer: "https://192.0.2.200/webfig/"
```
As you can see in 3rd message, your configuration has also some errors, so for instance an internal redirect to error page 404.html (with relative path?) also missing the file, so therefore a single attempt will be mistakenly counted twice here.
