### ISSUE TITLE
Executable daemon file placement

### ISSUE THREAD

**Issue by egberts** [fail2ban/fail2ban#2838]
### Environment:

- Fail2Ban version latest master
- OS: Linux 5.11
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Executable files that are root-only should be placed under  `/usr/sbin`, and not in  `/usr/bin`.

### Citation

According to (File System Standard 3.0](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html), the daemon executable file goes into system binary directory (`/usr/sbin`.)

3.16. /sbin : System binaries

3.16.1. Purpose
...  Programs executed after `/usr` is known to be mounted (when there are no problems) are generally placed into `/usr/sbin`. ...

#### Any additional information
Armor, GR-SEC, and SELinux are doubling down on root-only being in the ordinary /usr/bin directory.  (I find this out using Fedora 33 which disabled `kernel selinux=off` option  became no longer available).

Furthermore, most ordinary users would not have `/usr/sbin` in their `$PATH`.

==== Effort Required
Most package manager will  remove the old `fail2ban-server` from `/usr/bin` while updated package will start using `/usr/sbin` automatically (almost).

Note: One other file spotted  (`fail2ban/debian/backports/nopycentral.patch`) makes mention of this server executable file.

**Comment by sebres** [comment]
Well, this is rather a matter of @fail2ban/maintainers (because it is distribution related thing)...

Fail2bans setup.py using standard python's setuptools or distutils installer, which can pre-select directory depending on version, distro and build or install parameters (see `python setup.py --help` or `python setup.py install --help`).

But you're able to specify own path or even prefix for every installed directory.

For example, you can also try a dry run to check how the option affecting that:
```
$ python setup.py --dry-run install --install-scripts /usr/sbin | grep bin

copying and adjusting bin/fail2ban-client -> build/scripts-2.7
copying and adjusting bin/fail2ban-server -> build/scripts-2.7
copying and adjusting bin/fail2ban-regex -> build/scripts-2.7
copying and adjusting bin/fail2ban-testcases -> build/scripts-2.7

Creating build/fail2ban.service (from fail2ban.service.in): @BINDIR@ -> /usr/sbin
 | ExecStartPre=/bin/mkdir -p /run/fail2ban
 | ExecStart=/usr/sbin/fail2ban-server -xf start
 | # ExecStart=/usr/sbin/fail2ban-server -xf --logtarget=sysout start
 | ExecStop=/usr/sbin/fail2ban-client stop
 | ExecReload=/usr/sbin/fail2ban-client reload
creating fail2ban-python binding -> build/scripts-2.7 (dry-run, real path can be different)
Copying content of build/scripts-2.7 to /usr/sbin
```
The core distribution from this repository provides rather a basic installation, but real distribution related stuff is provided by maintainers (some of them have even different setup scripts).

Maybe we should add the info about this (and other) options to README or our wiki.

I'll close it here as unrelated,
but @fail2ban/maintainers et al, don't hesitate to ping me, whether we need other default paths or prefixes (I'll reopen the issue).

**Comment by sebres** [comment]
> Executable files **that are root-only** should be placed under /usr/sbin, and not in /usr/bin

As regards root-only - this is not quite correct, because:
- fail2ban can theoretically work without root;
- `fail2ban-regex` does not necessarily need root permissions;
- `fail2ban-client` can be used without root too, if unix socket file of fail2ban gets another permissions (e. g. you can allow some group to notify fail2ban server using `fail2ban-client` about failures, manual bans or unbans etc);

**Comment by egberts** [comment]
Theoretically? As in all scripts, that are called by fail2ban action setting, having appropriate SUID/GUID?

**Comment by egberts** [comment]
Also, how do I post issues related to maintainer? Is there like a separate issue DB named “fail2ban/maintainer”, like in “fail2ban/wiki”?

**Comment by sebres** [comment]
@yarikoptic, @fail2ban/maintainers what do you think about the idea of new repository fail2ban/distributions (or whatever) for you all? At least for an issue tracker or possibly some other distro related stuff.

**Comment by sebres** [comment]
As for no-root, you can also see #2649

**Comment by yarikoptic** [comment]
> @yarikoptic, @fail2ban/maintainers what do you think about the idea of new repository fail2ban/distributions (or whatever) for you all? At least for an issue tracker or possibly some other distro related stuff.

In general debian folks prefer to maintain packages in VCS on debian infrastructure since not all maintainers/contributors are upstream developers, and upstream hosting can move etc.  Since I was busy/lazy, @sylvestre kindly took over maintainership and for the reasons aforementioned, git repository for debian packaging is now at https://salsa.debian.org/python-team/packages/fail2ban (from what I see -- based on the previous repo, so this one).  So most likely here in `debian` branch and/or `fail2ban/distributions` should just have all files removed and README.md posted that packaging for debian has moved to that repository.  I would not remove `debian` branch here completely since previous versions of fail2ban packages still have vcs fields pointing to it and some people might look for release tags etc.
