### ISSUE TITLE
Having difficulty with multiline regex / ssh-ddos

### ISSUE THREAD

**Issue by lcurtis-datto** [fail2ban/fail2ban#2850]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.11.1-1
- OS, including release name/version: Ubuntu 20.04
- [ x] Fail2Ban installed via OS/distribution mechanisms
- [ x] You have not applied any additional foreign patches to the codebase
- [x ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Unable to block IP using multiple line regex match for ssh-ddos filter
#### Steps to reproduce
Due to upstream openssh issues, the existing failregex of '^%(__prefix_line)sDid not receive identification string from <HOST>( port [0-9]+)?$' no longer works in Ubuntu 20.04

However, by setting ssh logging to VERBOSE, it is possible to obtain the ip address of a possible ssh ddos attack across multiple lines. Trying to figure out how to combine multiple lines to block corresponding IP.

Example:

```
2020-10-06T12:51:15.725629+00:00 auth.info <hostname> sshd[111499]: Connection from <src ip address> port 58614 on <listening ip> port 22 rdomain ""
2020-10-06T12:51:15.725945+00:00 auth.err <hostname> sshd[111499]: error: kex_exchange_identification: Connection closed by remote host
```
#### Expected behavior
ip is blocked
#### Observed behavior

I am able to get a match on a few failregex lines using:
```
fail2ban-regex /var/log/auth.log ./sshd-ddos.local -v
```

but unable to block ip by combining the multiple failregex lines. I have looked at various examples, and feel that it is probably something missing in my prefregex or __prefix_line directives, but not able to figure it out. Perhaps someone could point me in the right direction? I am trying to use the NOFAIL directive to match IP and then the subsequent error line to match the IP. Any advice greatly appreciated.

### Configuration, dump and another helpful excerpts

Here are the relevant lines in /etc/fail2ban/filter.d/sshd-ddos.local:
```
__pref = (?:(?:error|fatal): (?:PAM: )?)?
prefregex = ^<F-MLFID>%(__prefix_line)s</F-MLFID>%(__pref)s<F-CONTENT>.+</F-CONTENT>$

failregex = ^%(__prefix_line)sDid not receive identification string from <HOST>( port [0-9]+)?$
            ^<F-NOFAIL>%(__prefix_line)sConnection from <HOST></F-NOFAIL>
            ^%(__prefix_line)serror: kex_exchange_identification: Connection closed by remote host
```

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
2020-10-06T12:51:15.725629+00:00 auth.info <hostname> sshd[111499]: Connection from <src ip address> port 58614 on <listening ip> port 22 rdomain ""
2020-10-06T12:51:15.725945+00:00 auth.err <hostname> sshd[111499]: error: kex_exchange_identification: Connection closed by remote host
```

**Comment by sebres** [comment]
I knew this day would come...
Although sshd (openssh) people have already changed the format previously in several versions, but after the prefix only.
Now the change seems to affect the part retrieved in filter as multi-line failure ID (`<F-MLFID>`).

Without to take a closer look in your whole description, I guess your MLFIDs for both lines would be something like that:
```
auth.info hostname sshd[111499]
auth.err hostname sshd[111499]
```
which as you can see deviate by info vs. err (you could also see that if you would run `fail2ban-regex -l 5 ...`, with heavy debug log level).

Thus any attempt to rewrite `__prefix_line` only is simply doomed to fail
(due to inclusion of whole prefix between `<F-MLFID>...</F-MLFID>` in the `prefregex`).

Because now one has to exclude `auth.*` from `<F-MLFID>...</F-MLFID>` to consider both failures coming from same session (so fail2ban would be able to find both line are related - the dependency between host IP from first line and a failure of second line by its common ID).

Here is a working attempt which rewrites `prefregex` of sshd filter (and add RE for ddos mode) for this format:
```
$ flt='sshd[mode=ddos, logtype=short, prefregex="^\s*auth\.\w+ \S+ <_daemon>\[<F-MLFID>\d+</F-MLFID>\]: <__pref><F-CONTENT>.+</F-CONTENT>$", mdre-ddos="<known/mdre-ddos>
kex_exchange_identification: Connection closed by remote host"]'

$ fail2ban-regex --out row /tmp/gh-2850.txt "$flt"

['192.0.2.1',   1601988675,     {'dns': None, 'ip6': None, 'mlfid': u'111499', 'ip4': u'192.0.2.1'}],
```

<details> <summary><code>$ fail2ban-regex --print-all-matched /tmp/gh-2850.txt "$flt"</code></summary>

```
Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use   filter options : {'logtype': 'short', 'mode': 'ddos', 'mdre-ddos': '<known/mdre-ddos>\nkex_exchange_identification: Connection closed by remote host', 'prefregex': '^\\s*auth\\.\\w+ \\S+ <_daemon>\\[<F-MLFID>\\d+</F-MLFID>\\]: <__pref><F-CONTENT>.+</F-CONTENT>$'}
Use         maxlines : 1
Use      datepattern : {^LN-BEG} : Default Detectors
Use         log file : /tmp/gh-2850.txt
Use         encoding : UTF-8


Results
=======

Prefregex: 2 total
|  ^\s*auth\.\w+ \S+ sshd\[(?P<mlfid>\d+)\]: (?:(?:error|fatal): (?:PAM: )?)?(?P<content>.+)$
`-

Failregex: 2 total
|-  #) [# of hits] regular expression
|  27) [1] kex_exchange_identification: Connection closed by remote host
|  28) [1] ^<F-NOFAIL>Connection from</F-NOFAIL> <HOST>
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [2] {^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
`-

Lines: 2 lines, 1 ignored, 1 matched, 0 missed
[processed in 0.00 sec]

|- Matched line(s):
|  2020-10-06T12:51:15.725945+00:00 auth.err hostname sshd[111499]: error: kex_exchange_identification: Connection closed by remote host
`-
|- Ignored line(s):
|  2020-10-06T12:51:15.725629+00:00 auth.info hostname sshd[111499]: Connection from 192.0.2.1 port 58614 on 0.0.0.0 port 22 rdomain ""
`-
```
</details>

So the `prefregex` for this format could be this:
```ini
prefregex=^\s*auth\.\w+ \S+ <_daemon>\[<F-MLFID>\d+</F-MLFID>\]: <__pref><F-CONTENT>.+</F-CONTENT>$
```
or even this:
```ini
prefregex=^\s*auth\.\w+ <F-MLFID>\S+ <_daemon>\[\d+\]</F-MLFID>: <__pref><F-CONTENT>.+</F-CONTENT>$
```
----
Probably also good workaround would be to include it to the `datepattern` instead of completely rewrite `prefregex`:
```
$ fail2ban-regex -d '{DATE} auth\.\w+' /tmp/gh-2850.txt 'sshd[mode=ddos,logtype=short]'
```
so you can use:
```ini
datepattern = {DATE} auth\.\w+
```
or even more precise with exact, single pattern:
```ini
datepattern = ^%%Y-%%m-%%dT%%H:%%M:%%S(?:[.,]%%f)?(?:\s*%%z)? auth\.\w+
```

But it is impossible to handle that by rewrite of __prefix_line only (since type of event seems to be included in prefix now).

**Comment by lcurtis-datto** [comment]
@sebres - THANK YOU!

It was my hope that by posting the question, others who are trying to master fail2ban and its powers might benefit, as well. I sincerely appreciate your taking the time to answer so thoughtfully and thoroughly. Your answer has enlightened me on other possibilities.

My new failregex looks like:

```
failregex = ^%(__prefix_line)sDid not receive identification string from <HOST>( port [0-9]+)?$
            <F-NOFAIL>Connection from <HOST></F-NOFAIL>
            kex_exchange_identification: Connection closed by remote host
```
The above appears to work well. Thanks so much for all of your efforts on this project. You and Fail2ban are amazing.

**Comment by lcurtis-datto** [comment]
I must thank you again. For some reason I did not get RE match when first using ``^ `` , but working now. Ace!

Here are relevant lines in /etc/fail2ban/filter.d/sshd-ddos.local:

```
# optional prefix (logged from several ssh versions) like "error: ", "error: PAM: " or "fatal: "
__pref = (?:(?:error|fatal): (?:PAM: )?)?
#prefregex = ^<F-MLFID>%(__prefix_line)s</F-MLFID>%(__pref)s<F-CONTENT>.+</F-CONTENT>$
prefregex=^\s*auth\.\w+ \S+ <_daemon>\[<F-MLFID>\d+</F-MLFID>\]: <__pref><F-CONTENT>.+</F-CONTENT>$

# Ubuntu 16.04 doesn't contain the trailing 'port X' part of the line, but 18.04 does,
#  it has been made optional below
failregex = ^%(__prefix_line)sDid not receive identification string from <HOST>( port [0-9]+)?$
            ^<F-NOFAIL>Connection from <HOST></F-NOFAIL>
            ^kex_exchange_identification: Connection closed by remote host
```

**Comment by sebres** [comment]
[02525d7b6f96c2841c24c4dbfcfe14e4a3d1ef63] is in upstream now:
mode `ddos` (and `aggressive`) extended with new rule closing flood attack vector, matching:
`error: kex_exchange_identification: Connection closed by remote host`

[4b8b0085e34b6b672e9314f46581c77d23e7c456] is committed in branch [gh-2850](https://github.com/fail2ban/fail2ban/compare/0.10...sebres:gh-2850) (just to hold it for the case this new logging (syslog?) format with `facility.priority` becomes standard per default so would need some standard parameter or new common logtype substitution in fail2ban).

**Comment by lcurtis-datto** [comment]
Hello @sebres . I wanted to let you know that I tried out your changes in https://github.com/fail2ban/fail2ban/commit/4b8b0085e34b6b672e9314f46581c77d23e7c456 and ran into an issue similar to https://github.com/fail2ban/fail2ban/issues/1727 .

When running with sshd.conf as configured in your change:
```
_facility = auth
_priority = \w+
_eventtype = (?: %(_facility)s\.%(_priority)s)?
...
prefregex = ^%(_eventtype)s<F-MLFID>%(__prefix_line)s</F-MLFID>%(__pref)s<F-CONTENT>.+</F-CONTENT>$
```
regular closed connections are getting banned after several connection attempts even though fail2ban-regex shows 0 hits.

**Comment by sebres** [comment]
> regular closed connections are getting banned after several connection attempts even though fail2ban-regex shows 0 hits.

Hmm... with which mode? (normal or ddos/aggressive)?
the only one difference `fail2ban-regex` has (at the moment), it doesn't consider settings of jail.local at all (second argument of `fail2ban-regex` is regex or filter, not a jail name.
So you have to supply all the parameters like here:
```
fail2ban-regex -o row "$log_or_journal" 'sshd[mode=ddos]'
```
If you are unable to find it, please provide your setting (and possibly some excerpt of legitimate attempts of such "regular closed connections")

**Comment by lcurtis-datto** [comment]
It fails using ddos mode (also to note - ddos mode only seems to work if I set ``mode = ddos`` in sshd.local and not in jail.local).

Using the the settings noted previously:
```
_facility = auth
_priority = \w+
_eventtype = (?: %(_facility)s\.%(_priority)s)?
...
prefregex = ^%(_eventtype)s<F-MLFID>%(__prefix_line)s</F-MLFID>%(__pref)s<F-CONTENT>.+</F-CONTENT>$
```

and the relevant line in log:

``2020-10-12T20:28:05.553077+00:00 auth.info <hostname> sshd[2364039]: Connection from <src ip> port 49598 on <listening ip> port 22 rdomain ""
``
It is banned after a few aborted ssh attempts as a test per the maxretry setting in jail.local

**Comment by sebres** [comment]
> It fails using ddos mode
> It is banned after a few aborted ssh attempts as a test per the maxretry setting in jail.local

Hmm... what do you think, mode `ddos` should avoid?
But normally this recognizes not properly established connections, that intruders open to generate high load (or doing flood, port scan, etc).

> also to note - ddos mode only seems to work if I set mode = ddos in sshd.local and not in jail.local

If you meant `fail2ban-regex`, then I already wrote above, that fail2ban-regex does not consider jail setting at all (it reads only filter file). See also related RFE #2655.

If you mean processing in fail2ban server, then something is wrong with your configuration, because as you can see here, the default interpolation of filter look like:
https://github.com/fail2ban/fail2ban/blob/4d2734dd86421d3d529bcb5cf71fadbe57c84649/config/jail.conf#L167

Probably you overwrite the default filter in jail sshd, then you have to supply mode as parameter of filter like above.

> and the relevant line in log:
`... sshd[2364039]: Connection from ...`

Well as I asked for an excerpt, I mean **ALL** messages generated by sshd for some single session (in this case all messages with `sshd[2364039]`.
Without additional messages, the message you're mentioned above does not cause any failure at all. The regex matching that is simply a helper used to remember IP address for failures (from the same session) without an IP in the line.

This is also covered in our test-suite and as you can see https://github.com/fail2ban/fail2ban/blob/4b8b0085e34b6b672e9314f46581c77d23e7c456/fail2ban/tests/files/logs/sshd#L331-L334
the first message does not produce a match (it is false), only IP address is noticed and the second message produces a failure for the IP.
With other words messages matching regex with non-empty `<F-NOFAIL>` group are ignored (the same you'd see using `fail2ban-regex`).

So if I generate a lot of messages with `Connection from 192.0.2.1` I don't see something producing ban, but some other messages with same ID, matching regex without `<F-NOFAIL>` (and without `Accepted` message in-between) would generate a failure (and finally a ban if reached maxretry).

Still again, please provide whole excerpt producing a failures. The "relevant" line, that you meant above, alone would not do that.

**Comment by sebres** [comment]
As PoC you can do following by yourself:
1. in new extra console start monitoring of auth.log and fail2ban.log:
```
sudo tail -n 0 -f /var/log/auth.log /var/log/fail2ban.log 
```
2. then generate 3 messages like in your example above:
```
logger -t 'sshd' --id=12345 -p auth.info 'Connection from 192.0.2.1 port 58614 on 127.0.0.1 port 22 rdomain ""'
logger -t 'sshd' --id=12345 -p auth.info 'Connection from 192.0.2.1 port 58614 on 127.0.0.1 port 22 rdomain ""'
logger -t 'sshd' --id=12345 -p auth.info 'Connection from 192.0.2.1 port 58614 on 127.0.0.1 port 22 rdomain ""'
```
  as you can see nothing happens in fail2ban.log, just 3 messages in auth.log as expected.
```
==> /var/log/auth.log <==
Oct 13 11:49:26 host sshd[12345]: Connection from 192.0.2.1 port 58614 on 127.0.0.1 port 22 rdomain ""
Oct 13 11:49:28 host sshd[12345]: Connection from 192.0.2.1 port 58614 on 127.0.0.1 port 22 rdomain ""
Oct 13 11:49:30 host sshd[12345]: Connection from 192.0.2.1 port 58614 on 127.0.0.1 port 22 rdomain ""
```

3. then generate 2 real failures (in my case maxretry was set to 2) in sense of ddos mode:
```
logger -t 'sshd' --id=12345 -p auth.err 'error: kex_exchange_identification: client sent invalid protocol identifier ""'
logger -t 'sshd' --id=12345 -p auth.err 'error: kex_exchange_identification: Connection closed by remote host'
```

Now you can observe that fail2ban finds 2 failures and finally bans this IP:
```
==> /var/log/auth.log <==
Oct 13 11:50:07 host sshd[12345]: error: kex_exchange_identification: client sent invalid protocol identifier ""
==> /var/log/fail2ban.log <==
2020-10-13 11:50:07,476 fail2ban.filter         [12457]: INFO    [sshd] Found 192.0.2.1 - 2020-10-13 11:50:07

==> /var/log/auth.log <==
Oct 13 11:50:07 host sshd[12345]: error: kex_exchange_identification: Connection closed by remote host
==> /var/log/fail2ban.log <==
2020-10-13 11:50:07,545 fail2ban.filter         [12457]: INFO    [sshd] Found 192.0.2.1 - 2020-10-13 11:50:07
2020-10-13 11:50:08,214 fail2ban.actions        [12457]: NOTICE  [sshd] Ban 192.0.2.1
```

**Comment by lcurtis-datto** [comment]
@sebres - Issue was exactly as you describe and due to missing ``filter = %(__name__)s[mode=%(mode)s] `` 

Everything working as expected! Thanks again and best wishes.
