### ISSUE TITLE
fail2ban-regex not matching for subnet

### ISSUE THREAD

**Issue by ValeryKV** [fail2ban/fail2ban#2866]
I have log entry that contains subnet:

`Nov 04 07:01:38 INFO     whois 141.98.10.183 cidr=(141.98.10.0/24) any text`

I want to block "141.98.10.0/24" but the following regexs returns 0 matches:

```
fail2ban-regex "Nov 04 07:01:38 INFO     whois 141.98.10.183 cidr=(141.98.10.0/24) any text" "whois.*cidr=\(<HOST>\).*any"
fail2ban-regex "Nov 04 07:01:38 INFO     whois 141.98.10.183 cidr=(141.98.10.0/24) any text" "whois\s+<HOST> cidr=\(<ip>.*</ip>\).*any"
```

I can block "141.98.10.183" with the following regex:

`fail2ban-regex "Nov 04 07:01:38 INFO     whois 141.98.10.183 cidr=(141.98.10.0/24) any text" "whois\s+<HOST> cidr=\(.*\).*any"`

And I can block "141.98.10.0" with the regex:

`fail2ban-regex "Nov 04 07:01:38 INFO     whois 141.98.10.183 cidr=(141.98.10.0/24) any text" "whois.*cidr=\(<HOST>/24\).*any"`

But I need to block "141.98.10.0/24". I do not know I have to use `<HOST>` or `<ip></ip>`.

**Comment by sebres** [comment]
#2560 implementing subnet tags to parse a subnet instead of IP (released with 0.10.5 and 0.11.1).
Just note that then your banning action should be able to ban a subnet (otherwise you have to customize that).

Another variant (as long as not yet upgraded for you) would be to provide custom pattern for that using `<F-ID>` tag, e. g. 
`<F-ID>[^\)]+</F-ID>`, so something like `^\s*INFO whois \S+ cidr=\(<F-ID>[^\)]+</F-ID>\) any`
see https://github.com/fail2ban/fail2ban/issues/2559#issuecomment-548745220 for details.
For instance try:
`fail2ban-regex -o row "Nov 04 07:01:38 INFO whois 192.0.2.183 cidr=(192.0.2.0/24) any text" "cidr=\(<F-ID>[^\)]+</F-ID>\)"`
If no host or IP found in message, fail2ban would use value of ID to substitute `<ip>` tag in the action.
