### ISSUE TITLE
nginx not working after installation on centOS8

### ISSUE THREAD

**Issue by tomizius** [fail2ban/fail2ban#2872]
I just had some problems to get fail2ban running on my centOS8 server. 

### Environment:
- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.11.1
- OS, including release name/version: CentOS Linux release 8.2.2004 (Core) 
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

To be sure it is not my problem I just rent a completely new blank server and just run following commands:
`[root@centos ~]# history`
   `1  dnf update`
    `2  dnf install nginx`
    `3  systemctl start nginx`
    `4  dnf install epel-release`
    `5  dnf install fail2ban`
    `6  systemctl start fail2ban`
    `7  systemctl enable nginx`
    `8  systemctl enable fail2ban`
    `9  reboot now`

After command 3 I got a curl response from my server, the default nginx page.
After command 9 it is not possible to connect to the server anymore:
`curl http://95.X.X.X`
`curl: (7) Failed to connect to 95.X.X.X port 80: Keine Route zum Zielrechner`

#### Steps to reproduce
Run my commands above and try to connect to the default nginx page.
#### Expected behavior
Everything running fine, connecting to nginx is possible.
#### Observed behavior
No connection to any service.

#### Any customizations done to /etc/fail2ban/ configuration
nope, it's just the default configuration from the installation

#### Relevant parts of /var/log/fail2ban.log file:
Not relevant but here we go:
```
2020-11-17 11:22:05,066 fail2ban.server         [3611]: INFO    --------------------------------------------------
2020-11-17 11:22:05,066 fail2ban.server         [3611]: INFO    Starting Fail2ban v0.11.1
2020-11-17 11:22:05,067 fail2ban.observer       [3611]: INFO    Observer start...
2020-11-17 11:22:05,071 fail2ban.database       [3611]: INFO    Connected to fail2ban persistent database '/var/lib/fail2ban/fail2ban.sqlite3'
2020-11-17 11:22:05,074 fail2ban.database       [3611]: WARNING New database created. Version '4'
2020-11-17 11:22:25,741 fail2ban.server         [3611]: INFO    Shutdown in progress...
2020-11-17 11:22:25,741 fail2ban.observer       [3611]: INFO    Observer stop ... try to end queue 5 seconds
2020-11-17 11:22:25,762 fail2ban.observer       [3611]: INFO    Observer stopped, 0 events remaining.
2020-11-17 11:22:25,803 fail2ban.server         [3611]: INFO    Stopping all jails
2020-11-17 11:22:25,804 fail2ban.database       [3611]: INFO    Connection to database closed.
2020-11-17 11:22:25,805 fail2ban.server         [3611]: INFO    Exiting Fail2ban
2020-11-17 11:22:45,247 fail2ban.server         [870]: INFO    --------------------------------------------------
2020-11-17 11:22:45,250 fail2ban.server         [870]: INFO    Starting Fail2ban v0.11.1
2020-11-17 11:22:45,254 fail2ban.observer       [870]: INFO    Observer start...
2020-11-17 11:22:45,264 fail2ban.database       [870]: INFO    Connected to fail2ban persistent database '/var/lib/fail2ban/fail2ban.sqlite3'
```

**Comment by sebres** [comment]
> any customizations done to /etc/fail2ban/ configuration
> nope, it's just the default configuration from the installation

So you have no jails enabled in fail2ban (as you can see in log-file no one jail is started, let alone absolutely no bans occurred at all)... 
In this case fail2ban after install and start wouldn't configure anything with your net-filter or network subsystem (iptables or something else), so it cannot and would not bother your nginx connections. 
Therefore the issue is somewhere else.
You can try to enable debugging on nginx side (or even in your net-filter) to find what is happening here.

**Comment by tomizius** [comment]
Dear sebres,

I know this is the reason why I open this issue because nothing should be changes at the net-filter.
But you can just test it by yourself, that when you just run the simple 8 commands and reboot your server nginx won't work anymore. If you just uninstall fail2ban again it works like magic.
So I think the issue comes with the fail2ban package!

**Comment by sebres** [comment]
> when you just run the simple 8 commands and reboot your server nginx won't work anymore.

Neither I have any combination of any OS/distribution (e.g. CentOS), nor I have any intention to check that by myself. Just because I know how fail2ban is working (and normally an issue submitter has a duty to provide proof or evidence).
If you mean the fail2ban package should be responsible for that, you may open an issue by maintainer of your CentOS distribution, you have obtained fail2ban from. Stock version of fail2ban would not do any change that can affect nginx connectivity unless you configure some jail and banning action for that.

@fail2ban/maintainers Any idea what can happen here?

> So I think the issue comes with the fail2ban package!

Still again it cannot basically. Because fail2ban is working jail based and you did not configure any jail it is strictly impossible.
If you can point me to anything causing that (banning action or nftables/iptables/firewald entry, dependencies e. g. start of fail2ban avoids start of nginx service, etc) we can reopen this.
As long as more info is provided, we'll consider this as incorrect issue.

**Comment by tomizius** [comment]
>Neither I have any combination of any OS/distribution (e.g. CentOS)

I will just quote my first post: `OS, including release name/version: CentOS Linux release 8.2.2004 (Core)`

>Stock version of fail2ban would not do any change that can affect nginx connectivity unless you configure some jail and banning action for that.

right but it does, which is a bug in my opinion and this is the reason why I opened this issue.

>As long as more info is provided, we'll consider this as incorrect issue.

What more information do you need? I think the problem is clear as I describe it, even if you don't believe it. But it has been tested several times by me and as soon as fail2ban is installed, nginx no longer works and that without any configuration for both packages.

**Comment by hobbes1069** [comment]
Unfortunately there's not enough information to even hazard a guess. I just tried to reproduce the problem and I could not on my CentOS 8 Stream box. I could browse to the nginx test page before and after starting fail2ban.

**Comment by tomizius** [comment]
>I could browse to the nginx test page before and after starting fail2ban.

Have you restarted your server after the installation of the both packages?
Because as described just after the installation it works. After a reboot not.

**Comment by hobbes1069** [comment]
Rebooting had no effect, I still get the default nginx page in Chrome.

**Comment by sebres** [comment]
Thx Richard!
As assumed, it looks like a 3rd party issue to me (and I can even not imagine what exactly must be misconfigured to cause that).
Since "No route to host" may refer to a common network problem (no reply from host), and it is not a "Connection refused", so mostly it is no listener on port 80 (443) for the given IP/adapter or your firewall blocking this port for incoming connections with DROP or REJECT without some icmp informing packet.
Anyway if I were you, I would forget fail2ban and start with check of firewall (e. g. https://superuser.com/a/720860/1131979) and nginx - whether service is started, port is open and listening by nginx (`sudo netstat -lnp | grep 80`), hostname in request matches some host or default configured in nginx, etc, up to debugging that deeply).

The only one thing where fail2ban can be involved here - if it has some dependency in your distribution, e. g. installing some firewall/net-filter which either was already configured on this host with some strict rules, for instance per default drop/reject any incoming connection to any port, which is not explicitly allowed, or has such strict default configuration (what I doubt because not confirmed by @hobbes1069).
But also in this case you haven't to blame fail2ban here.
