### ISSUE TITLE
How to block an ip IF it hits a certain url more than N times?

### ISSUE THREAD

**Issue by starchild** [fail2ban/fail2ban#2890]
Sorry for posting here but I'm struggling to work this out.  I'm hoping some freindly member will be able to point us in te right direction.

We have the problem of hackers trying to submit forged payment requests. They return the url /shop?fail=1 when their attempts fails.

How can we block their ip IF they visit that url more than 3 times in 1 min?

Thank you.

**Comment by sebres** [comment]
There are several ways to do that, depending on the software you use. But the scenario is like this:

1. you have to create a jail with `failregex` (or filter) matching the log-entry, or you could use fail2ban internal protocol to notify each single attempt or use `fail2ban-client set "$jail" attempt $ip` (see https://github.com/fail2ban/fail2ban/issues/2559#issuecomment-548851675 for more details).
2. for the first variant (with `failregex`) you must log every single attempt in file or journal (and set logpath to this log or select systemd backend for journal), and then specify `maxretry = 3` and `findtime = 1m` in order to ban after 3 failures in 1 minute,
3. you have to set banning action banning the IP (IP-based action using net-filter subsystem) or session id or whatever else identifying the intruder (ID-based action, e. g. like [nginx-block-map.conf](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/nginx-block-map.conf)).

Also consider the article [wiki/Best-practice](https://github.com/fail2ban/fail2ban/wiki/Best-practice).
