### ISSUE TITLE
Server starts up with 2.4GB memory?

### ISSUE THREAD

**Issue by alexhass** [fail2ban/fail2ban#2900]
I'm running Fail2Ban v0.9.6 (Debian 9) for a long time and today I found it is eating 2,4GB of memory what sound really extreme to me.

I checked fail2ban.sqlite3 and it was nearly 400MB. As a try I stopped the service and remove the file. After starting up the service the db was recreated and is now small and slowlyy growing... I will keep an eye on it.

However the fail2ban server still runs with 2.4GB. Is this normal? How can I reduce the memory usage?

**Comment by sebres** [comment]
> I found it is eating 2,4GB of memory what sound really extreme to me.
> However the fail2ban server still runs with 2.4GB. Is this normal? How can I reduce the memory usage?

If you mean virtual memory, see https://github.com/fail2ban/fail2ban/issues/2045#issuecomment-364880345 answering similar question.
If you mean physical memory, it is indeed extreme and is definitely not normal.
I guess you have some jail(s) which observing too many failures (without to result to a ban, due to large values of `maxretry` and `findtime`) or even have a large ban list. 
Anyway see similar issues, like https://github.com/fail2ban/fail2ban/issues/2843#issuecomment-708310517 (or #2118).

Shortly, if you have fail2ban version >= 0.10.5 (or >= 0.11.1) you can set `maxmatches` as described in #2402.
For older versions, you have only the possibility to decrease `maxretry` and `findtime`.

> I checked fail2ban.sqlite3 and it was nearly 400MB.

There is also an option to hold it slimmer (`dbmaxmatches`, see #2402), but it also relative new (introduced in 0.10.5/0.11.1).
Also note that before 0.11, the purge (auto-cleanup) was never called, so you can be affected by the issue #1267.
The "fix" for that would be either to switch to 0.11 or periodically purge it manually (in cron or timer).
