### ISSUE TITLE
Many tests are failing

### ISSUE THREAD

**Issue by mfilser** [fail2ban/fail2ban#2915]
Hello,
first, thank you a lot for this projects, i like it very much and helps a lot :)

I want to have some look at the rules and tests, and before i am doing changes, i want to run the tests, but they are failing at my system.
I thought it's maybe of some configuration problems, so i decided to run it in an docker container, but also the same tests fail there.
This is the command i am running in the fail2ban git repository on my machine:
```bash
$ docker run --rm -it -v $PWD:/data -w /data python:2 bin/fail2ban-testcases
```

**Comment by sebres** [comment]
I guess you tried some last released version? If so see https://github.com/fail2ban/fail2ban/issues/2904#issuecomment-754042663, this was a "mistake" of me - some tests containing timestamp from 201x, but fail2ban could handle only years 200x as alternate date (it artificially running in 2005) and current decade 202x (from current and previous year), so every date from 201x is not recognized with precise datepatterns, therefore all the errors for instance for year 2013 etc.

If it is not the same, one needs to know which version you tested and which tests exactly fail.

**Comment by mfilser** [comment]
@sebres 
Thank you a lot for the fast answer.
I tried at this commit: 2c60d08b284f3068682942de1769e9a8e4e53418

At the latest commit 2781e7b9d1111005e2bc97c96ddb53f0fbf47f99 most tests are ok.
Now, a few tests still are failing, but it's different if running in docker or not.

Here are a 2 attachement's:
[fail_docker.txt](https://github.com/fail2ban/fail2ban/files/5848881/fail_docker.txt)
[fail_no_docker.txt](https://github.com/fail2ban/fail2ban/files/5848882/fail_no_docker.txt)

**Comment by sebres** [comment]
As for docker, dunno... 
first (testTextToIp) looks like a network stuff (DNS or so): it found an IP for either `doh1.2.3.4.buga.xxxxx.yyy.invalid` or `1.2.3.4.buga.xxxxx.yyy.invalid` hosts, which should normally result to nothing, 
in your case it resolves to an IP `185.*.*.*` (see your excerpt) for some reasons.

but second testDirectRE_1 found more than expected for some reason (3 lines contain invalid timestamp), so here is expected vs. reported diff:
```diff
- Lines: 19 lines, 0 ignored, 16 matched, 3 missed
+ Lines: 19 lines, 0 ignored, 19 matched, 0 missed
```
I'll check what it can be.

As for physical host, there is some strange "kill" behavior (seems to be disallowed or so), because both tests using that, one covering terminating child after timeout, another testing a proper teardown on kill signal.
Never saw this before... Probably you could try with another user (or even root/sudo)...

Anyway if you take a look at 2781e7b9d1111005e2bc97c96ddb53f0fbf47f99, you'll see it is green (check flag left from), so all [tests](https://github.com/fail2ban/fail2ban/actions/runs/474028361) pass with all python versions.

**Comment by mfilser** [comment]
Thank you a lot for the answer.
Just for clarify, i think i posted it a bit unclear.
The file ```fail_no_docker.txt``` was the physical host, and ```fail_docker.txt``` was the one which was run into docker.

I will have a look at it too. I think you can close this issue if you like.
Thank you a lot for your help,

Best regards

**Comment by sebres** [comment]
OK, thus closed (we can reopen it by some findings).
