### ISSUE TITLE
sshd jail is full of banned ip's yet none of them are found in auth.log

### ISSUE THREAD

**Issue by sephethus** [fail2ban/fail2ban#2925]
### Environment:

Ubuntu 18.04
Fail2ban version 0.10.2

- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

Not seeing any of the IPs found in the `fail2ban-client status sshd` list of banned IPs within the /var/log/auth.log file. How is this possible? This is concerning the sshd jail only. Where is it getting this huge list of IPs to ban constantly if they aren't in the auth.log?

Conversely, 3 attempts from the same IP aren't getting banned:
```
Feb  1 19:47:25 sftp-service sshd[21318]: Invalid user admin from 192.144.254.35 port 57866
Feb  1 19:47:25 sftp-service sshd[21318]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.144.254.35
Feb  1 19:47:27 sftp-service sshd[21318]: Failed password for invalid user admin from 192.144.254.35 port 57866 ssh2
Feb  1 19:47:27 sftp-service sshd[21318]: Received disconnect from 192.144.254.35 port 57866:11: Bye Bye [preauth]
Feb  1 19:47:27 sftp-service sshd[21318]: Disconnected from invalid user admin 192.144.254.35 port 57866 [preauth]
Feb  1 19:53:30 sftp-service sshd[4873]: Invalid user dovenull from 192.144.254.35 port 53740
Feb  1 19:53:30 sftp-service sshd[4873]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.144.254.35
Feb  1 19:53:32 sftp-service sshd[4873]: Failed password for invalid user dovenull from 192.144.254.35 port 53740 ssh2
Feb  1 19:53:32 sftp-service sshd[4873]: Received disconnect from 192.144.254.35 port 53740:11: Bye Bye [preauth]
Feb  1 19:53:32 sftp-service sshd[4873]: Disconnected from invalid user dovenull 192.144.254.35 port 53740 [preauth]

```
```
fail2ban-client get sshd maxretry
3
```
_Summary here_

#### Steps to reproduce

Find IP in banned list, grep for it in /var/log/auth.log

#### Expected behavior

Find the IP banned in the sshd jail (tons of IPs found in there)

```
fail2ban-client status sshd
```

#### Observed behavior

No IPs in the banned list show up in auth.log

#### Any customizations done to /etc/fail2ban/ configuration

PLEASE NOTE THAT THIS ISSUE OCCURRED WITH OR WITHOUT THESE CUSTOMIZATIONS

From iptables-multiport.conf
```
actionstart = <iptables> -N f2b-<name>
              <iptables> -A f2b-<name> -j <returntype>
              <iptables> -I <chain> -p <protocol> -m multiport --dports <port> -j f2b-<name>
          cat /etc/fail2ban/persistent.bans | awk '/^fail2ban-<name>/ {print $2}' \
          | while read IP; do <iptables> -I f2b-<name> 1 -s $IP -j <blocktype>; done
```
and
```
actionban = <iptables> -I f2b-<name> 1 -s <ip> -j <blocktype>
        if ! grep -Fq "fail2ban-<name> <ip>" /etc/fail2ban/persistent.bans; then echo "fail2ban-<name> <ip>" >> /etc/fail2ban/persistent.bans; fi
```
From jail.conf:

```
[sshd]

# To use more aggressive sshd modes set filter parameter "mode" in jail.local:
# normal (default), ddos, extra or aggressive (combines all).
# See "tests/files/logs/sshd" or "filter.d/sshd.conf" for usage example and details.
#mode   = normal
#logpath = %(sshd_log)s
logpath = /var/log/auth.log
maxretry = 3
backend = %(sshd_backend)s
enabled  = true
port     = ssh
filter   = sshd
bantime = -1
banaction = iptables-multiport
            slack-notify

```

From slack-notify.conf
```
actionban = cat /var/log/auth.log | grep <ip> | while read line; do if [[ $line != *"nvalid user"* ]] && [[ $line == *"Failed password"* ]]; then curl -X POST --data-urlencode "payload={\"text\": \"[$(hostname -f)]: Fail2Ban: $line\", \"channel\": \"#<slack_channel>\" }" '<slack_webhook_url>'; fi; done
```

**Comment by sebres** [comment]
> jail is full of banned ip's yet none of them are found in auth.log

Setting `bantime = -1` means persistent bans, due to this persistency such bans will never expire. Since fail2ban stores the bans to database and all active bans get restored after restart, even after restart all of those persistent tickets will be considered as still active and restored.
The only possibility to remove such bans is to remove them manually one by one or all in jail `fail2ban-client restart --unban sshd` or even all tickets `fail2ban-client unban --all`, or even with removal of database.

Note: the usage of persistent banning is not recommended (unneeded extra load of fail2ban and net-filter subsystem), specifying of `30d` is totally enough to prevent rude evildoers to repeat his attempts at some point.
You can also switch to v.0.11 which has a new feature (incremental banning), which can also be helpful against recidive intruders.
But even in this version it is advisable to restrict max banning time (to specify `bantime.maxtime`) to avoid endless growing of time, see https://github.com/fail2ban/fail2ban/issues/2652#issuecomment-596107934 for details.

> Conversely, 3 attempts from the same IP aren't getting banned:

Note that sshd is the most changing filter, so 0.10.2 is probably too old version here (either update your sshd-filter or fail2ban version).
Here is a result for your excerpt with current version (0.10.6):
```
fail2ban-regex -v /tmp/log 'sshd'
...
Lines: 10 lines, 6 ignored, 4 matched, 0 missed

fail2ban-regex -v /tmp/log 'sshd[mode=aggressive]'
...
Lines: 10 lines, 4 ignored, 6 matched, 0 missed
```

**Comment by sebres** [comment]
Since you use a debian (Ubuntu 18.04), you could try our newer [0.10.6~upstream version](https://github.com/fail2ban/fail2ban/releases/tag/0.10.6) (or even newest [0.11.2~upstream version](https://github.com/fail2ban/fail2ban/releases/tag/0.11.2)), since both can be compatible (and containing a deb-package built for debians).
