### ISSUE TITLE
postfix.conf: should filter also by BDAT and DATA (not only RCPT)

### ISSUE THREAD

**Issue by maxbritov** [fail2ban/fail2ban#2927]
smtpd_data_restrictions in postfix config will generate logs like:

```
postfix/smtpd[9034]: 8892C160605: reject: DATA from
postfix/smtpd[9034]: 8892C160605: reject: BDAT from
```

filter.d/postfix.conf only filter by RCPT:

```
mdre-normal=^RCPT from [^[]*\[<HOST>\]%(_port)s: 55[04] 5\.7\.1\s
....
```

"(BDAT|DATA|RCPT)" works for me with smtpd_data_restrictions

**Comment by sebres** [comment]
Fixed in c5f1598a215b337ce5a93243fe17896edff780e6.
Although the filter is extended to match reject message on `DATA` and `BDAT` (et al.), the regex was rewritten previously (in ae3e9b9149c36e3334447e869667bcf171ff0a3a) as more precise single regex, so I'm unsure it would cover every case and completely match any smtpd_data_restrictions message.
Thus closed. Please provide an excerpt with exact message if it does not work in some case.
