### ISSUE TITLE
Very long error messages in fail2ban.log

### ISSUE THREAD

**Issue by tkalfaoglu** [fail2ban/fail2ban#2928]
I am seeing very long lines in the fail2ban log whenever there is an error banning/unbanning some IP.
For example:
```
2021-02-03 08:31:14,420 fail2ban.filter [9599]: INFO [fail2ban-repeats] Found 87.246.7.226 - 2021-02-03 08:31:14
2021-02-03 08:31:14,834 fail2ban.actions [9599]: NOTICE [fail2ban-repeats] Ban 87.246.7.226
2021-02-03 08:31:14,846 fail2ban.actions [9599]: ERROR Failed to execute ban jail 'fail2ban-repeats' action 'route' info 'ActionInfo({'
ipfailures': 4036, 'ip-rev': '226.7.246.87.', 'family': 'inet4', 'ipmatches': "2021-02-02 05:53:39,410 fail2ban.actions [16221]: NOTICE
[sasl] Unban 87.246.7.226\n2021-02-02 05:53:39,539 fail2ban.actions [16221]: NOTICE [plesk-postfix] Unban 87.246.7.226\n2021-02-02 05:54
:58,787 fail2ban.actions [16221]: NOTICE [plesk-postfix] Unban 87.246.7.226\n2021-02-02 05:54:58,966 fail2ban.actions [16221]: NO
TICE [sasl] Unban 87.246.7.226\n2021-02-02 06:28:26,460 fail2ban.actions [9599]: NOTICE [sasl] Unban 87.246.7.226\n2021-02-02 06:28:26,
632 fail2ban.actions [9599]: NOTICE [plesk-postfix] Unban 87.246.7.226\n2021-02-02 06:59:03,366 fail2ban.actions [9599]: NOTICE
[plesk-postfix] Unban 87.246.7.226\n2021-02-02 06:59:03,645 fail2ban.actions [9599]: NOTICE [sasl] Unban 87.246.7.226\n2021-02-02 07:29:
32,665 fail2ban.actions [9599]: NOTICE [plesk-postfix] Unban 87.246.7.226\n2021-02-02 07:29:32,968 fail2ban.actions [9599]: NOTIC
E [sasl] Unban 87.246.7.226\nFeb 3 07:29:36 jedi postfix/smtpd[46947]: warning: unknown[87.246.7.226]: SASL LOGIN authentication failed: authe
ntication failure\nFeb 3 07:29:39 jedi postfix/smtpd[59565]: warning: unknown[87.246.7.226]: SASL LOGIN authentication failed: authentication f
(etc this goes on for pages)
```
I am using fail2ban-0.10.3.1-2.centos.7+p18.0.33.0+t210122.1058.noarch

**Comment by sebres** [comment]
As for "too long", it is already noticed and was fixed in 79350e916e79ec2d91d3430e6796f26da386ecf0 (released in version >= 0.10.4), so the action info is not interpolate every dynamic value anymore in the log (only values needed in action)...

As for your issue `Failed to execute ban jail 'fail2ban-repeats' action 'route'`, unfortunately you did not provide the actual error message (at end of this line and probably in next one), so it is not clear what exactly happen here.
But because it looks like some recidive jail (`fail2ban-repeats`), please consider this additionally:
- due to double ban (1 time in originated jail and 1 time in `fail2ban-repeats`), I guess it could be similar to this issue https://github.com/fail2ban/fail2ban/issues/2373#issuecomment-473714585 (simply said, banning action `route` is not suitable right now to ban same IP address in several jails).
- if you can switch to v.0.11, you would not need such repeatable handling with recidive jails like 'fail2ban-repeats' anymore, just use `bantime.increment = true` (incremental banning) instead.
