### ISSUE TITLE
fail2ban filter pass variable to action

### ISSUE THREAD

**Issue by maykel535** [fail2ban/fail2ban#2941]
Hi, I've configured fail2ban with action, filter for my php application.

My app output log like this:

unknown user foo (192.x.x.x)

My jail conf:
```ini
[php-app-login]
enabled = true
port = 80
protocol = tcp
filter = php-app-login
logpath = /var/www/php-app-login/var/logs/dev.log
findtime = 3600
bantime = 86400
maxretry = 3
ignoreip  = 127.0.0.1/8
```
My filter definition:
```ini
[Definition]

failregex = unknown user .* \(<HOST>\)
ignoreregex =
```
It works well, but I like fail2ban add comment in iptables rule when add ban IP.

For example:
```
iptables -A INPUT -p tcp --dport 80 -m comment --comment "Ban foo" -j DROP

iptables -L -n -v

Chain INPUT (policy ACCEPT 94 packets, 23457 bytes)
 pkts bytes target     prot opt in     out     source
destination
    0     0 DROP       tcp  --  *      *       0.0.0.0/0
0.0.0.0/0            tcp dpt:80 /* Ban foo */
```
I've googled and I think something needs to be changed in action but I
can't find how to pass the user variable to that action.

**Comment by sebres** [comment]
If you have at least fail2ban v.0.10 (it is also possible with >= 0.9.5 or 0.9.6, but it has some restrictions)...

Filter:
```diff
- failregex = unknown user .* \(<HOST>\)
+ failregex = unknown user <F-USER>\S+</F-USER> \(<ADDR>\)
```
By the way, your regex is vulnerable (rewrite it more precise with anchoring and without catch-alls).

Action (no idea which action do you use, here is a simple diff for [iptables-multiport](https://github.com/fail2ban/fail2ban/blob/0.10.6/config/action.d/iptables-multiport.conf#L41)):
```diff
- actionban = <iptables> -I f2b-<name> 1 -s <ip> -j <blocktype>
+ actionban = <iptables> -I f2b-<name> 1 -s <ip> -j <blocktype> -m comment --comment "Ban user <F-USER>"
- actionunban = <iptables> -D f2b-<name> -s <ip> -j <blocktype>
+ actionunban = <iptables> -D f2b-<name> -s <ip> -j <blocktype> -m comment --comment "Ban user <F-USER>"
```

One could overwrite it in `action.d/some-action.local` (then simply overwrite setting you need) or even directly from jail.local by supplying of such parameter, like here (for aforementioned change):
```ini
[iptables-multiport]
banaction = iptables-multiport[blocktype='<known/blocktype> -m comment --comment "Ban user <F-USER>"']
```

Just note, in your example it looks like you want to change `actionstart` which would be not correct - `actionstart` is executed once per jail (and IP family) but not per ban, `actionban` is executed per ticket if it gets banned (so your comment belongs rather to another rule and chain as in your example).
One can write another iptables action (write everything is in INPUT chain), but this is not the proper way (moreover better is to use iptables+ipset actions).

Also note that in my example above it would ban an IP and just add a comment to the banning rule.
If your intention is either to ban user instead of IP, this is completely different approach (see action [nginx-block-map](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/nginx-block-map.conf) for example).
