### ISSUE TITLE
Using nginx-block-map.conf causes error in nginx log file on reboot

### ISSUE THREAD

**Issue by bitcity** [fail2ban/fail2ban#2949]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.11.2
- OS, including release name/version: Ubuntu 16.04
- [x] Fail2Ban installed from source
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:
I'm following the advice here https://github.com/fail2ban/fail2ban/issues/2258 for using fail2ban with a load balancer. It works as expected i.e. nginx is reloaded and we can ban the IPs identified by fail2ban via nginx. 

The problem happens with the server reboots, there's an error generated in the nginx log file at the moment fail2ban shuts down. The error message is `[error] 1891#1891: invalid PID number "" in "/var/run/nginx.pid"`

#### Steps to reproduce
- Using action : config/action.d/nginx-block-map.conf
- Reboot the machine after fail2ban is configured

#### Expected behavior
There shouldn't be an error in the nginx log file

#### Observed behavior
The error message in nginx log file is : 

`/var/log/nginx/error.log`
> 2021/02/24 13:41:05 [notice] 1891#1891: signal process started
> 2021/02/24 13:41:05 [error] 1891#1891: invalid PID number "" in "/var/run/nginx.pid"

This happens at the same time when fail2ban is shutting down.

#### Any customizations done to /etc/fail2ban/ configuration
> [nginx-limit-req]
> enabled = true
> filter = nginx-limit-req
> action = nginx-block-map[Name=TestNginx]
> logpath = /var/log/nginx/error.log

#### Relevant parts of /var/log/fail2ban.log file:

`/var/log/fail2ban.log`
> 2021-02-24 13:41:05,245 fail2ban.server         [1742]: INFO    Shutdown in progress...
> 2021-02-24 13:41:05,246 fail2ban.observer       [1742]: INFO    Observer stop ... try to end queue 5 seconds
> 2021-02-24 13:41:05,266 fail2ban.observer       [1742]: INFO    Observer stopped, 0 events remaining.
> 2021-02-24 13:41:05,307 fail2ban.server         [1742]: INFO    Stopping all jails
> 2021-02-24 13:41:05,307 fail2ban.filter         [1742]: INFO    Removed logfile: '/var/log/nginx/error.log'
> 2021-02-24 13:41:05,449 fail2ban.actions        [1742]: NOTICE  [nginx-limit-req] Flush ticket(s) with nginx-block-map
> 2021-02-24 13:41:05,485 fail2ban.jail           [1742]: INFO    Jail 'nginx-limit-req' stopped
> 2021-02-24 13:41:05,486 fail2ban.database       [1742]: INFO    Connection to database closed.
> 2021-02-24 13:41:05,486 fail2ban.server         [1742]: INFO    Exiting Fail2ban

**Comment by bitcity** [comment]
I can reproduce the problem by shutting down nginx first and then shutting down fail2ban. Probably the systemd config is incorrect. I'm using the fail2ban.service script from the repo (just added `After=nginx.service`), hoping that this would start fail2ban after nginx and shutdown in reverse order.

    [Unit]
    Description=Fail2Ban Service
    Documentation=man:fail2ban(1)
    After=nginx.service network.target iptables.service firewalld.service ip6tables.service ipset.service nftables.service
    PartOf=iptables.service firewalld.service ip6tables.service ipset.service nftables.service

    [Service]
    Type=simple
    Environment="PYTHONNOUSERSITE=1"
    ExecStartPre=/bin/mkdir -p /run/fail2ban
    ExecStart=/var/virtualenv/test/bin/fail2ban-server -xf start
    # if should be logged in systemd journal, use following line or set logtarget to sysout in fail2ban.local
    # ExecStart=/var/virtualenv/test/bin/fail2ban-server -xf --logtarget=sysout start
    ExecStop=/var/virtualenv/test/bin/fail2ban-client stop
    ExecReload=/var/virtualenv/test/bin/fail2ban-client reload
    PIDFile=/run/fail2ban/fail2ban.pid
    Restart=on-failure
    RestartPreventExitStatus=0 255

    [Install]
    WantedBy=multi-user.target

**Comment by bitcity** [comment]
Sorry, it was a misconfiguration issue with the systemd service. Closing the issue.

**Comment by sebres** [comment]
No problem.

It can be indeed solved by adding of such a dependency, but if someone does not want this for several reasons?..
For instance any kind of protection organized by fail2ban is retarded (the host is unprotected unless nginx starts) etc. 

For example I'd prefer such "error" in log (which doesn't bother me at all).

Although this action is rather a "template", so is pretty extendable and customizable (multiple nginx instances, different handling, etc).
But we can indeed extend the action to check the existence of pid-file by default.
```diff
- blck_lst_reload = %(srv_cmd)s -qt; if [ $? -eq 0 ]; then
+ blck_lst_reload = test -f /run/nginx.pid && %(srv_cmd)s -qt; if [ $? -eq 0 ]; then
```

**Comment by bitcity** [comment]
Thanks, that's good to know. Also appreciate adding [nginx-block-map.conf](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/nginx-block-map.conf). It's a helpful template as an alternative to iptables.

**Comment by sebres** [comment]
You are welcome.
Myself uses custom nginx module that gets the map from a database (redis, memcached, faster, whatever else), so it is not necessary to reload nginx at all.

Back to the issue... must be fixed now in 63acc862b139bb1d8b45edb0b3716044b36c7113
Although I guess nginx could simply output this error message in stderr only instead of putting the message in its error.log.

**Comment by bitcity** [comment]
> Myself uses custom nginx module that gets the map from a database (redis, memcached, faster, whatever else), so it is not necessary to reload nginx at all.

Sounds cool. Is this from a public repo ?

**Comment by sebres** [comment]
No, I still not published it because it is based on my own nginx with tcl version which is different, must still rebase it to common nginx (not so simple, no time, etc). If I would get some time to fulfill that I will notify here (and in fail2ban release).

But you can do that using lua, perl or whatever is available on your system - e. g. using modules like https://github.com/openresty/lua-resty-redis, or still simpler using [auth_request](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html) to some internal or named location accessing your database inside (per script, fastcgi or whatever else), and with enabled cache for this location you would get hardly noticeable overhead for that (which is almost comparable to seeking over map), at least this was my initial variant for that and it working well some years.
There are also other [modules](https://www.nginx.com/resources/wiki/modules/redis/) that may help you to implement such thing.

And the counterpart fail2ban action to write to database is really simple, either a command action (using command line of database client) or something pythonic:
```python
from fail2ban.server.actions import Actions, ActionBase, BanTicket

class StoreDBAction(ActionBase):

  def start(self):
    pass

  def stop(self):
    pass

  def ban(self, aInfo):
    fid = str(aInfo['fid'])
    _set_in_db(fid)

  def unban(self, aInfo):
    fid = str(aInfo['fid'])
    _unset_in_db(fid)

  def flush(self):
    _flush_in_db()

Action = StoreDBAction
```
