### ISSUE TITLE
[BR]: non-root cannot create log file and database 

### ISSUE THREAD

**Issue by bitcity** [fail2ban/fail2ban#2958]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.11.2
- OS, including release name/version: Ubuntu 16.04
- [x] Fail2Ban installed from source
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The Issue
fail2ban as a non-root user throws error. It cannot create `/var/log/fail2ban.log` and cannot write to sqlite database.

#### Steps to reproduce
Install fail2ban as non-root user [following the advice here](https://github.com/fail2ban/fail2ban/blob/master/doc/run-rootless.txt)

#### Customizations
```
fail2ban.service

[Service]
User=fail2ban
Group=adm
RuntimeDirectory=fail2ban
```
#### Expected behavior
fail2ban should start without any error

#### Observed behavior

  > sudo service fail2ban status

    ● fail2ban.service - Fail2Ban Service
       Loaded: loaded (/etc/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
       Active: active (running) since Fri 2021-03-05 06:11:58 UTC; 11min ago
         Docs: man:fail2ban(1)
      Process: 905 ExecStartPre=/bin/mkdir -p /run/fail2ban (code=exited, status=0/SUCCESS)
     Main PID: 906 (fail2ban-server)
        Tasks: 3 (limit: 2306)
       CGroup: /system.slice/fail2ban.service
               └─906 /var/virtualenv/test/bin/python /var/virtualenv/test/bin/fail2ban-server -xf start

    Mar 05 fail2ban-server[906]: 2021-03-05 06:11:58,883 fail2ban.server         [906]: ERROR   Unable to log to '/var/log/fail2ban.log'
    Mar 05 fail2ban-server[906]: 2021-03-05 06:11:58,885 fail2ban.server         [906]: INFO    Logging to previous target None
    Mar 05 fail2ban-server[906]: 2021-03-05 06:11:58,885 fail2ban.server         [906]: INFO    --------------------------------------------------
    Mar 05 fail2ban-server[906]: 2021-03-05 06:11:58,885 fail2ban.server         [906]: INFO    Starting Fail2ban v0.11.2
    Mar 05 fail2ban-server[906]: 2021-03-05 06:11:58,888 fail2ban.observer       [906]: INFO    Observer start...
    Mar 05 fail2ban-server[906]: 2021-03-05 06:11:58,909 fail2ban.server         [906]: ERROR   Unable to log to '/var/log/fail2ban.log'
    Mar 05 fail2ban-server[906]: 2021-03-05 06:11:58,909 fail2ban.server         [906]: INFO    Logging to previous target None
    Mar 05 fail2ban-server[906]: 2021-03-05 06:11:58,909 fail2ban.transmitter    [906]: WARNING Command ['server-stream', [['set', 'syslogsocket', 'auto'], ['set', 'loglevel', 'INFO'], ['set
    Mar 05 fail2ban-server[906]: 2021-03-05 06:11:58,909 fail2ban                [906]: ERROR   NOK: ('Failed to change log target',)
    Mar 05 fail2ban-server[906]: Server ready

  > groups fail2ban
  fail2ban : fail2ban adm

  > ps fail2ban
  906 fail2ban adm      /var/virtualenv/test/bin/python /var/virtualenv/test/bin/fail2ban-server -xf start

**Comment by sebres** [comment]
Hmm... have you check which permissions the user, under which fail2ban is running, does have on /var/log?

There are several possibilities to handle this:
- either you allow this user to write in /var/log (e. g. add it to group that can write there) 
- or create this file and give the needed permissions or change owner (`chown root:fail2ban /var/log/fail2ban.log; chmod g+w /var/log/fail2ban.log`), also don't forget to check logrotation script to do the same there (e. g. `create 664 root fail2ban`).
- or switch `logtarget` to something better suitable, e. g. to other location (/var/log/fail2ban/fail2ban.log) with different permissions, to SYSLOG to write using system logging, or to SYSOUT to write to systemd journal (since it seems to run as systemd unit)

The same is valid for database, pid-file and unix-socket or either for whole run-time directory where fail2ban writes database and other stuff (default `?/var/?/run/fail2ban/`):
- either change permissions in this directory (allow everything for fail2ban user), this would be better option
- or switch the paths to different location where this user have whole permissions

Several configuration (paths) can be made in `/etc/fail2ban/fail2ban.local` (see `/etc/fail2ban/fail2ban.conf` for possible options) or changing start parameters in your (local) unit file (see `fail2ban-server --help` for options).
https://github.com/fail2ban/fail2ban/blob/08393f9d82d4929ce3ee09bd9f3c685d38b2428d/files/fail2ban.service.in#L10-L11

No matter whether this being a part of `run-rootless.txt` or not, this is basics in unix and linux world (also not much different in windows) - ability to write to some path expects certain permissions, so quasi a matter of course.
