### ISSUE TITLE
[BR]: No file(s) found for glob /var/log/audit/audit.log

### ISSUE THREAD

**Issue by arnold-b** [fail2ban/fail2ban#2960]
there is nowhere configured this path.

 No file(s) found for glob /var/log/audit/audit.log
 Failed during configuration: Have not found any log file for selinux-ssh jail

**Comment by sebres** [comment]
> there is nowhere configured this path.

No, there is...

https://github.com/fail2ban/fail2ban/blob/960e30cfcdae7e2c81f74046efdbff1606f9774e/config/paths-common.conf#L44

And default configuration for selinux-ssh looks like:

https://github.com/fail2ban/fail2ban/blob/27a10e0e646fb1eb088f3c7183715b57bcd08316/config/jail.conf#L283-L286

which will substitute to `/var/log/audit/audit.log`.

Either specify another `logpath` for something matching your distribution (or change backend to systemd if it is systemd journal) in your `jail.local`, or simply don't enable this jail.

**Comment by arnold-b** [comment]
its useless to have this in  jail.d/ssh.conf 
[sshd]
enabled = true
bantime  = 36000
# Override the default value - overwrites, does not merge
ignoreip = 127.0.0.1/8
logpath  = /var/log/auth.log
[ssh]
enabled  = true
port     = 9999
# Use a pre-configured filter
filter   = sshd
bantime  = 36000
logpath  = /var/log/auth.log

In fail2ban/config/paths-common.conf

Line 44 in 960e30c

 auditd_log = /var/log/audit/audit.log 

i changed the path to /var/log/audit.log 

and i still get the error: 
No file(s) found for glob /var/log/audit.log
 Failed during configuration: Have not found any log file for selinux-ssh jail

**Comment by sebres** [comment]
> its useless to have this in jail.d/ssh.conf

This is useless because `jail.d/ssh.conf` is for jail `ssh` (not `sshd`), but section where you write the config is called `sshd` (not `ssh`). This is single section file, where name of the file must be the same as the section name and the jail name.
Moreover the error is affecting jail `selinux-ssh` (so it seems to be enabled somewhere). 
Please read the error message carefully.

You can also configure everything in single file `/etc/fail2ban/jail.local` (multi-section file where every entry in some section overwrites the values of `/etc/fail2ban/jail.conf` and includes).

> i changed the path to /var/log/audit.log 
> No file(s) found for glob /var/log/audit.log

So there is simply no such file (or user runs fail2ban cannot read). Find correct path for you distribution or fix its permissions.

Also note, that you shouldn't change default configuration (which can be overwritten next time fail2ban gets upgraded).
It is enough to write everything in `/etc/fail2ban/jail.local` (or even other local files), see https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration
