### ISSUE TITLE
[FR]: Owncloud timestamp pattern mismatch "but no valid date/time found for"

### ISSUE THREAD

**Issue by atcapollo** [fail2ban/fail2ban#2969]
Owncloud filter fails seem to be an issue with time stamp format. 

### Environment:

- Fail2Ban version:
fail2ban:
  Installed: 0.11.1-1
  Candidate: 0.11.1-1
  Version table:
 *** 0.11.1-1 500
        500 http://gb.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        500 http://gb.archive.ubuntu.com/ubuntu focal/universe i386 Packages

- OS, including release name/version : 
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : n/a
- Service, project or product name, including release name/version : OwnCloud 10.5.0
- Repository or URL (if known) : 
- Service type : systemd
- Ports and protocols the service is listening : tcp / https 443

#### Log or journal information

- Log file name(s) : 
/var/www/owncloud/data/owncloud.log

- Journal identifier or unit name : 

Unit: jail.local
```ini
[owncloud]
enabled = true
port = 80,443
protocol = tcp
filter = owncloud
maxretry = 3
bantime = 10800
logpath = /var/www/owncloud/data/owncloud.log
```
Filter: owncloud.conf
```ini
[Definition]
failregex={.*Login failed: \'.*\' \(Remote IP: \'<HOST>\'\)"}

ignoreregex =
```

#### Owncloud.log seems to be an issue with the time stamp

```
{"reqId":"nTx5SmVOyY2UAmpqTFmC","level":2,"time":"2021-03-12T02:15:06+00:00","remoteAddr":"192.168.1.100","user":"--","app":"core","method":"POST","url":"\/owncloud\/index.php\/login","message":"Login failed: 'test' (Remote IP: '192.168.1.100')"}
```

#### Fail2Ban error
```
WARNING Found a match for '{"reqId":"XVq8jGDSncMmFDjAfWYI","level":2,"time":"2019-08-25T15:53:47+00:00","remoteAddr":"192.168.1.1","user":"--","app":"core","method":"PROPFIND","url":"\\/owncloud\\/remote.php\\/webdav\\/","message":"Login failed: \'username\' (Remote IP: \'192.168.1.1\')"}' but no valid date/time found for '{"reqId":"XVq8jGDSncMmFDjAfWYI","level":2,"time":"2019-08-25T15:53:47+00:00","remoteAddr":"192.168.1.1","user":"--","app":"core","method":"PROPFIND","url":"\\/owncloud\\/remote.php\\/webdav\\/","message":"Login failed: \'username\' (Remote IP: \'192.168.1.1\')"}'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.
```

**Comment by sebres** [comment]
> `{.*Login failed: \'.*\' \(Remote IP: \'<HOST>\'\)"}`

This RE looks a bit vulnerable (no anchors, several catch-all's, etc), please consider https://github.com/fail2ban/fail2ban/issues/2485#issuecomment-516400982 for similar log-format (same filter?)

**Comment by atcapollo** [comment]
Thanks for quoting 2485, this all seems to have worked.

``
[Definition]
_groupsre = (?:(?:,?\s*"\w+":(?:"[^"]+"|\w+))*)
failregex = ^\{%(_groupsre)s,?\s*"remoteAddr":"<HOST>"%(_groupsre)s,?\s*"message":"Login failed:

datepattern = ,?\s*"time"\s*:\s*"%%Y-%%m-%%d[T ]%%H:%%M:%%S(%%z)?"
``
What does _groupsre do? Sorry I'm not familiar with RE.

Having looked through some related issues quoted in 2485, it seems this comes up quite a lot. It would be great if there was a standard built in filter for Own / Next cloud. I took my filter from an Owncloud guide which clearly is out of date / wrong.

**Comment by sebres** [comment]
The regex stored in `_groupsre` provides a bypass for simplest json-similar `tag:value` pairs grouped by comma, where tag is a name in format of alnum within quotes (`"\w+"`), and value can be either something quoted without a quote inside (`"[^"]+"`) or a simple alnum word `\w+` without quotes. And this matches as many such pairs as possible (`"a":"b & c", "d":e, ..., "y":"z"`). Usage of such filling REs makes possible to provide more safer RE (faster and fewer vulnerable against injections on foreign input), so anchor whole expression at start (`^`) as well as avoid usage of catch-alls.
The regex is holding as a parameter `_groupsre` for clarity as well as because it is needed twice, before `remoteAddr` name:value pair and before actually the failure marker `"message":"Login failed:`

**Comment by atcapollo** [comment]
Thanks for taking the time to explain. I clearly need to learn a lot more about regexp use.

Is there a 'simple' way to test a defined regexp filter from the CLI to see how it parses a log? in order to improve the RE.

I looked at the fail2ban documentation but I suspect I need to do this outside of fail2ban.

**Comment by sebres** [comment]
> Is there a 'simple' way to test a defined regexp filter from the CLI to see how it parses a log?

Hmm... what do you mean as simple?
The REs as well as the filter can be tested with `fail2ban-regex`. See `fail2ban-regex --help` for details.

As for "to see how it parses a log" it is really simple:
```
fail2ban-regex -l 5 $Line_OR_Log $Regex_OR_Filter
```
It will output debug info (due to `-l 5`, 5 for heavydebug) how fail2ban parses the lines in log.

As for regex, well there are surely some online regex services in internet that can help to understand how the REs working or to visualize every part matched by regex. Note that it must understand pythons regex (PCRE) and you have to replace special tags of fail2ban (e. g. `<HOST>` or `<ADDR>` etc) with something else (like `(?P<ip>\S+)` so this parser/visualizer can understand that.
```
fail2ban-regex -vv $Line_OR_Log $Regex_OR_Filter
```
will provide you (due to `-vv`) the real regex fail2ban would generate after special tags replacement.

There is also ` -D` option which would provide you a debuggex URL for regex (no idea it is still working, I did not tested it several years).
