### ISSUE TITLE
[FR]: IPSEC / Charon filter request

### ISSUE THREAD

**Issue by atcapollo** [fail2ban/fail2ban#2971]
Seeking to write a filter for IPSEC (OpenSwan) which uses Charon to handle authentication of VPN sessions.

The issue is that the authentication success / failure log line item, is on a separate line item from the host IP. How do I write a regexp that can connect the two line items together - see bolded in log.

### Environment:

Fail2Ban version:
fail2ban:
Installed: 0.11.1-1
Candidate: 0.11.1-1
Version table:
*** 0.11.1-1 500
500 http://gb.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
500 http://gb.archive.ubuntu.com/ubuntu focal/universe i386 Packages

OS, including release name/version :
LSB Version: core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description: Ubuntu 20.04.1 LTS
Release: 20.04
Codename: focal

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : new .... ipsec-charon.conf
- Service, project or product name, including release name/version : ipsec (OpenSwan)
- Repository or URL (if known) : 
- Service type :  /etc/init.d/ipsec
- Ports and protocols the service is listening :  51/UDP, 500/UDP, 4500/UDP

#### Log or journal information

- Log file name(s) : 

- Journal identifier or unit name : 

#### failures in sense of fail2ban filter (fail2ban must match):

/var/log/syslog
```
Mar 13 00:37:41 SERVER ipsec[2990]: 15[CFG] selected peer config "tunnel"
Mar 13 00:37:41 SERVER charon: 15[ENC] generating ID_PROT response 0 [ ID HASH ]
Mar 13 00:37:41 SERVER ipsec[2990]: 15[ENC] generating ID_PROT response 0 [ ID HASH ]
Mar 13 00:37:41 SERVER ipsec[2990]: 15[NET] sending packet: from 192.168.1.100[4500] to 214.205.192.3[64916] (76 bytes)
Mar 13 00:37:41 SERVER charon: 15[NET] sending packet: from 192.168.1.100[4500] to 214.205.192.3[64916] (76 bytes)
Mar 13 00:37:41 SERVER charon: 15[ENC] generating TRANSACTION request 2750310981 [ HASH CPRQ(X_USER X_PWD) ]
Mar 13 00:37:41 SERVER charon: 15[NET] sending packet: from 192.168.1.100[4500] to 214.205.192.3[64916] (76 bytes)
Mar 13 00:37:41 SERVER charon: 01[NET] received packet: from 214.205.192.3[64916] to 192.168.1.100[4500] (108 bytes)
Mar 13 00:37:41 SERVER charon: 01[ENC] parsed INFORMATIONAL_V1 request 2865392490 [ HASH N(INITIAL_CONTACT) ]
**Mar 13 00:37:41 SERVER charon: 08[NET] received packet: from 214.205.192.3[64916] to 192.168.1.100[4500] (108 bytes)**
Mar 13 00:37:41 SERVER charon: 08[ENC] parsed TRANSACTION response 2750310981 [ HASH CPRP(X_USER X_PWD) ]
Mar 13 00:37:41 SERVER charon: 08[IKE] none of 1 found XAuth secrets for '192.168.1.100' - 'username' matched
**Mar 13 00:37:41 SERVER charon: 08[IKE] XAuth authentication of 'username' failed**
```

#### legitimate messages (fail2ban should not consider as failures):

```
Mar 13 00:33:36 SERVER charon: 14[CFG] selected peer config "tunnel"
Mar 13 00:33:36 SERVER charon: 14[ENC] generating ID_PROT response 0 [ ID HASH ]
Mar 13 00:33:36 SERVER charon: 14[NET] sending packet: from 192.168.1.100[4500] to 214.205.192.3[64916] (76 bytes)
Mar 13 00:33:36 SERVER charon: 14[ENC] generating TRANSACTION request 276352866 [ HASH CPRQ(X_USER X_PWD) ]
Mar 13 00:33:36 SERVER charon: 14[NET] sending packet: from 192.168.1.100[4500] to 214.205.192.3[64916] (76 bytes)
Mar 13 00:33:36 SERVER charon: 07[NET] received packet: from 214.205.192.3[64916] to 192.168.1.100[4500] (108 bytes)
Mar 13 00:33:36 SERVER charon: 07[ENC] parsed INFORMATIONAL_V1 request 3342732587 [ HASH N(INITIAL_CONTACT) ]
Mar 13 00:33:36 SERVER charon: 09[NET] received packet: from 214.205.192.3[64916] to 192.168.1.100[4500] (108 bytes)
Mar 13 00:33:36 SERVER charon: 09[ENC] parsed TRANSACTION response 276352866 [ HASH CPRP(X_USER X_PWD) ]
Mar 13 00:33:36 SERVER charon: 09[IKE] XAuth authentication of 'username' successful
```

**Comment by sebres** [comment]
It is possible with a condition that `08` (in `08[NET]` and `08[IKE]`) is something like session-ID, at least unique for the period between connect received (first message in log) and authentication successful or failed.

Fail2ban has so called multi-line parsing modes: new variant (>= v.0.10) using `<F-MLFID>` tag to match such session-ID and old obsolete parsing (<= v.0.9) across several lines with `maxlines` defined buffer window skipping some in-between using `<SKIPLINES>` tag).

Using first variant the filter will look like:
```ini
[Definition]

prefregex = ^\s*\S+ charon: <F-MLFID>\d+</F-MLFID><F-CONTENT>.+</F-CONTENT>$

failregex = ^\[NET\] <F-NOFAIL>received</F-NOFAIL> packet: from <ADDR>\[\d+\]
            ^\[IKE\] XAuth authentication of '<F-USER>[^']+</F-USER>' failed\b
            ^\[IKE\] XAuth authentication of '<F-USER>[^']+</F-USER>' <F-MLFFORGET><F-MLFGAINED>successful</F-MLFGAINED></F-MLFFORGET>\b
```
where `<F-NOFAIL>` signals a helper (not a failure) to store the IP for ID (08 or 09), `<F-MLFGAINED>` signals a successful connect and let forget all previous failures (and stored mapping session-ID to IP) if user name is not changed (previous failures were from same user, to protect against bruteforce from some existing account).

To test it simply place the content to `/etc/fail2ban/filter.d/charon.conf` and use:
```bash
# verbose output:
fail2ban-regex -v /var/log/syslog charon
# output matched failures (newer f2b versions only, >= 0.11.2 / 0.10.6)
fail2ban-regex -o row /var/log/syslog charon
```

Since the second variant (with `<SKIPLINES>` tag) is obsolete (and not good for several reasons) I'll not provide it here, for the example see [fail2ban/tests/config/filter.d/zzz-sshd-obsolete-multiline.conf](https://github.com/fail2ban/fail2ban/blob/0.10/fail2ban/tests/config/filter.d/zzz-sshd-obsolete-multiline.conf).

**Comment by atcapollo** [comment]
Thanks trying to wrap my head around the parsing of the prefregex:
`
^\s*\S+ charon: <F-MLFID>\d+</F-MLFID><F-CONTENT>.+</F-CONTENT>$
`

Would I be right to understand that it parses each log line as follows:

Mar 13 00:33:36 SERVER charon: 09[NET] received packet: from 214.205.192.3[64916] to 192.168.1.100[4500] (108 bytes)
<F-MLFID> = 09
<F-CONTENT> = [NET] received packet: from 214.205.192.3[64916] to 192.168.1.100[4500] (108 bytes)

Mar 13 00:33:36 SERVER charon: 09[ENC] parsed TRANSACTION response 276352866 [ HASH CPRP(X_USER X_PWD) ]
<F-MLFID> = 09
<F-CONTENT> = [ENC] parsed TRANSACTION response 276352866 [ HASH CPRP(X_USER X_PWD) ]

Mar 13 00:33:36 SERVER charon: 09[IKE] XAuth authentication of 'username' successful
<F-MLFID> = 09
<F-CONTENT> = [IKE] XAuth authentication of 'username' successful

If I have understood correct its interesting that you don't have to tell it to delimit with a [ for it to know where the condition 08 / 09 etc. ends

Then I interpret that the F-CONENT 'string' is then parsed through the failregex RE?

**Comment by atcapollo** [comment]
Filter is working it logs failed attempts.
It is silent on successful attemps.

Thanks for your help.

**Comment by sebres** [comment]
>  you don't have to tell it to delimit with a [ for it to know where the condition 08 / 09 etc. ends

You don't need to do this, because `\d+` matches only integer, and `[` is obviously not such thing.
Because this log seems to be very wordy e. g. has many not-interesting (parasitic) messages, to be more precise in `prefregex` or rather to ignore other messages (so a bit faster at end) you could indeed extend it a bit:
```diff
- ^\s*\S+ charon: <F-MLFID>\d+</F-MLFID><F-CONTENT>.+</F-CONTENT>$
+ ^\s*\S+ charon: <F-MLFID>\d+</F-MLFID><F-CONTENT>(?:\[NET\] received|\[IKE\] XAuth).+</F-CONTENT>$
```

so resulting filter would look like this:
```ini
[Definition]

prefregex = ^\s*\S+ charon: <F-MLFID>\d+</F-MLFID><F-CONTENT>(?:\[NET\] received|\[IKE\] XAuth).+</F-CONTENT>$

failregex = ^\[NET\] <F-NOFAIL>received</F-NOFAIL> packet: from <ADDR>\[\d+\]
            ^\[IKE\] XAuth authentication of '<F-USER>[^']+</F-USER>' failed\b
            ^\[IKE\] XAuth authentication of '<F-USER>[^']+</F-USER>' <F-MLFFORGET><F-MLFGAINED>successful</F-MLFGAINED></F-MLFFORGET>\b
```

But it is not recommended to use such verbose logs (if you have better options, like separate log with failures only - single line for every failed attempt containing IP directly), see https://github.com/fail2ban/fail2ban/wiki/Best-practice for details.

**Comment by atcapollo** [comment]
thanks will test the updated regexp.

My other box is unfortunately stuck with fail2ban 0.9.3 on Ubuntu 16.04 - for that box I assume I need to try the equivalent with the obsolete maxlines approach?

**Comment by sebres** [comment]
Yes, as written above the new handling works only with version >= 0.10
Or you can try to upgrade fail2ban (our [releases](https://github.com/fail2ban/fail2ban/releases) have also a debian packages now or you can install it from source, see https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually).

**Comment by atcapollo** [comment]
Worked like a dream - beer money on its way.
