### ISSUE TITLE
[FR]: bind9 / named-refused does not match `query (cache) denied`

### ISSUE THREAD

**Issue by Happyfeet01** [fail2ban/fail2ban#2979]
Hello,

I use bind9 on my server and I got many requests from other servers. 

The fail2ban Filter: named-refused don't work. 

This is the logentry:

```
19-Mar-2021 18:22:28.260 client @0x7fd2dc209db0 81.105.67.254#80 (sl): query (cache) 'sl/ANY/IN' denied
19-Mar-2021 18:22:28.287 client @0x7fd2dc209db0 104.26.5.3#443 (sl): query (cache) 'sl/ANY/IN' denied
19-Mar-2021 18:22:28.295 client @0x7fd2dc209db0 104.26.5.3#443 (sl): query (cache) 'sl/ANY/IN' denied
19-Mar-2021 18:22:28.305 client @0x7fd2dc209db0 104.26.5.3#443 (sl): query (cache) 'sl/ANY/IN' denied
19-Mar-2021 18:22:28.337 client @0x7fd2dc209db0 86.57.243.197#2456 (sl): query (cache) 'sl/ANY/IN' denied
```

I added an acl rule so that only the slave zone DNS server have access to my dns. But the questions are not going away.

Thanks.

**Comment by sebres** [comment]
> The fail2ban Filter: named-refused don't work.

No, current filter `named-refused` definitely does work (matches all 5 messages from your excerpt):

```bash
$ fail2ban-regex /tmp/log named-refused

Running tests
=============

Use   failregex filter file : named-refused
Use         log file : /tmp/log
Use         encoding : UTF-8


Results
=======

Prefregex: 5 total
|  ^(?:\s*\S+ (?:(?:\[\d+\])?:\s+\(?named(?:\(\S+\))?\)?:?|\(?named(?:\(\S+\))?\)?:?(?:\[\d+\])?:)\s+)?(?: error:)?\s*client(?: @\S*)? (?:\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\d{1,3}\.){3}\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\]?|(?P<dns>[\w\-.^_]*\w))#\S+(?: \([\S.]+\))?: (?P<content>.+)\s(?:denied|\(NOTAUTH\))\s*$
`-

Failregex: 5 total
|-  #) [# of hits] regular expression
|   1) [5] ^(?:view (?:internal|external): )?query(?: \(cache\))?
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [5] {^LN-BEG}Day(?P<_sep>[-/])MON(?P=_sep)ExYear[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
`-

Lines: 5 lines, 0 ignored, 5 matched, 0 missed
[processed in 0.01 sec]
```

You did not provide fail2ban version, so may be it is simply outdated, then try to compare and update the filter in `/etc/fail2ban/filter.d` from [named-refused](https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/named-refused.conf).
Otherwise follow [wiki : How fail2ban works](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works), e. g. check whether the bans occurs at all, but probably requests going via UDP protocol (and you banning TCP only)...
Also note the warning in jail.conf - https://github.com/fail2ban/fail2ban/blob/a45b1c974c969e9486326872447c33feca9ce0b2/config/jail.conf#L667-L677

**Comment by Happyfeet01** [comment]
Yes, it was outdated. Now it works.

Date template hits:
|- [# of hits] date format
|  [137133] {^LN-BEG}Day(?P<_sep>[-/])MON(?P=_sep)ExYear[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
`-

Lines: 137133 lines, 0 ignored, 137133 matched, 0 missed
[processed in 8.06 sec]
