### ISSUE TITLE
prefix_line matches journalctl output but not what fail2ban reads from systemd journal

### ISSUE THREAD

**Issue by twheel** [fail2ban/fail2ban#2999]
The timestamp is different, which causes __prefix_line to fail.

`journalctl '_SYSTEMD_UNIT=php-fpm7.service' --no-pager > /tmp/journalctl.txt`
`tail -n3 /tmp/journalctl.txt`
> Apr 11 08:03:04 server.example.com wordpress(www.virtualhost1.com)[1648817]: Authentication attempt for unknown user test from 185.189.48.246
> Apr 11 08:03:47 server.example.com wordpress(www.virtualhost2.com)[1316061]: Authentication attempt for unknown user admin from 103.47.60.44
> Apr 11 08:05:25 server.example.com wordpress(www.virtualhost3.com)[1649006]: Authentication failure for molly from 93.114.86.226

`fail2ban-regex -l heavydebug "systemd-journal[journalflags=1]" wordpress-soft | grep "Read systemd journal entry:" | tail -n3`
> 2021-04-11 08:21:03,153 fail2ban.filtersystemd  [1650328]: HEAVY  H: [~jailless~] Read systemd journal entry: 2021-04-11T08:18:25.158890 server.example.com wordpress(www.virtualhost1.com)[1316075]: Authentication attempt for unknown user admin from 5.11.134.152
2021-04-11 08:21:03,154 fail2ban.filtersystemd  [1650328]: HEAVY  H: [~jailless~] Read systemd journal entry: 2021-04-11T08:19:52.864976 server.example.com wordpress(www.virtualhost1.com)[1316072]: Authentication attempt for unknown user admin from 189.114.140.70
2021-04-11 08:21:03,154 fail2ban.filtersystemd  [1650328]: HEAVY  H: [~jailless~] Read systemd journal entry: 2021-04-11T08:20:19.072972 server.example.com wordpress(www.virtualhost1.com)[1316061]: Authentication attempt for unknown user admin from 190.249.147.162

`fail2ban-regex 'systemd-journal[journalflags=1]' /tmp/wordpress-soft.conf`
> Running tests
> 
> Use   failregex file : /tmp/wordpress-soft.conf
> Use      datepattern : {^LN-BEG} : Default Detectors
> Use         systemd journal
> Use         encoding : UTF-8
> Use    journal match : _SYSTEMD_UNIT=php-fpm7.service
> 
> 
> Results
> 
> Failregex: 0 total
> 
> Ignoreregex: 0 total
> 
> Date template hits:
> 
> Lines: 77605 lines, 0 ignored, 0 matched, 77605 missed
> [processed in 9.29 sec]
> 
> Missed line(s): too many to print.  Use --print-all-missed to print all 77605 lines

` fail2ban-regex /tmp/journalctl.txt /tmp/wordpress-soft.conf`

> Running tests
> 
> Use   failregex file : /tmp/wordpress-soft.conf
> Use      datepattern : {^LN-BEG} : Default Detectors
> Use         log file : /tmp/unit.txt
> Use         encoding : UTF-8
> 
> 
> Results
> 
> Failregex: 47364 total
> |-  #) [# of hits] regular expression
> |   1) [2369] ^(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel:\s?\[ *\d+\.\d+\]:?\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?(?:wordpress|wp)(?:\(\S+\))?[\]\)]?:?|[\[\(]?(?:wordpress|wp)(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?Empty username from <HOST>$
> |   2) [18154] ^(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel:\s?\[ *\d+\.\d+\]:?\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?(?:wordpress|wp)(?:\(\S+\))?[\]\)]?:?|[\[\(]?(?:wordpress|wp)(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?Authentication failure for .* from <HOST>$
> |   4) [26841] ^(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel:\s?\[ *\d+\.\d+\]:?\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?(?:wordpress|wp)(?:\(\S+\))?[\]\)]?:?|[\[\(]?(?:wordpress|wp)(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?XML-RPC authentication failure for .* from <HOST>$
> `-
> 
> Ignoreregex: 0 total
> 
> Date template hits:
> |- [# of hits] date format
> |  [77579] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
> `-
> 
> Lines: 77580 lines, 0 ignored, 47364 matched, 30216 missed
> [processed in 4.95 sec]
> 
> Missed line(s): too many to print.  Use --print-all-missed to print all 30216 lines

[wordpress-soft.conf](https://github.com/fail2ban/fail2ban/files/6291748/wordpress-soft.conf.txt)
[common.conf](https://github.com/fail2ban/fail2ban/files/6291733/common.conf.txt)

**Comment by sebres** [comment]
This is not a bug, but a feature... :smile: (see #2387)... 
No, basically it is some incorrect parameter (for include `common.conf`) specified in filter, I suspect.

You did provide the filter example, but I guess it were something like [this](https://docs.wp-fail2ban.com/en/3.6/filters.html).

The basic reason of the issue is the value of `_daemon` - this is defined as ` (?:wordpress|wp)`, which is not the case in the log (e. g. where it is `wordpress(www.virtualhost1.com)`) and matching if parsing the file, because due to option `logtype` some part of very expensive default form of `__prefix_line` accidentally find something matching part `(...)` from there.

Whereas `logtype` by parsing systemd journal is set to `journal` (same as `short`) and generates much short (and efficient) `__prefix_line` matching exactly `wordpress` only without part enclosed in parenthesis.

So if you would try `fail2ban-regex` with `logtype=short` on your text file with journal excerpt, like here:
```bash
fail2ban-regex /tmp/journalctl.txt 'wordpress-soft[logtype=short]'
```
it would also not find any line, exactly the same way as by parsing of systemd journal directly.

Correct expression for `_daemon` for this log-format would be something like that:
```ini
_daemon = (?:wordpress|wp)(?:\([^\)]*\))?
```
where `(?:\([^\)]*\))?` optionally matching part `(...)` after word wordpress.

You can also test it directly by overwriting of the parameter `_daemon` via command line:
```bash
fail2ban-regex 'systemd-journal[journalflags=1]' 'wordpress-soft[logtype=short][_daemon="(?:wordpress|wp)(?:\([^\)]*\))?"]'
```
