### ISSUE TITLE
SSH IP failed to detect and ban

### ISSUE THREAD

**Issue by zhanwen-cheng** [fail2ban/fail2ban#3000]
Dear sebres, thanks for your contribution into this useful software. Recently I was using fail2ban version ```0.10.2``` on my ``` Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-128-generic x86_64)``` server. Here is how I install fail2ban on my computer.
```sudo apt-get install fail2ban```
```sudo cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local```
```sudo cp /etc/fail2ban/fail2ban.conf /etc/fail2ban/fail2ban.local```
```sudo cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local```
And the attachment is my editted ```jail.local``` file.
[jail.local.txt](https://github.com/fail2ban/fail2ban/files/6292080/jail.local.txt)

I start the fail2bam with ```sudo systemctl start fail2ban``` and ```sudo systemctl enable fail2ban```, and check the fail2bam service with ```sudo systemctl status fail2ban.service```, it shows 
```
● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2021-04-11 21:47:51 CST; 1h 18min ago
     Docs: man:fail2ban(1)
 Main PID: 40587 (fail2ban-server)
    Tasks: 3 (limit: 6143)
   CGroup: /system.slice/fail2ban.service
           └─40587 /usr/bin/python3 /usr/bin/fail2ban-server -xf start

Apr 11 21:47:51 profxia-SUSTC-309 systemd[1]: Starting Fail2Ban Service...
Apr 11 21:47:51 profxia-SUSTC-309 systemd[1]: Started Fail2Ban Service.
Apr 11 21:47:51 profxia-SUSTC-309 fail2ban-server[40587]: Server ready
```

However, when I mimic the the server was attacked with a non-existed user(test) in ssh,
```
login as: test
test@10.16.15.53's password:
Access denied
test@10.16.15.53's password:
Access denied
test@10.16.15.53's password:
Access denied
test@10.16.15.53's password:
Access denied
test@10.16.15.53's password:
Access denied
test@10.16.15.53's password:

Server sent disconnect message
type 2 (protocol error):
Too many authentication failures for test
```
Those message could be recorded with ```lastb -i ```
```
test     ssh:notty    10.17.121.161    Sun Apr 11 23:10 - 23:10  (00:00)
test     ssh:notty    10.17.121.161    Sun Apr 11 23:10 - 23:10  (00:00)
test     ssh:notty    10.17.121.161    Sun Apr 11 23:10 - 23:10  (00:00)
test     ssh:notty    10.17.121.161    Sun Apr 11 23:10 - 23:10  (00:00)
test     ssh:notty    10.17.121.161    Sun Apr 11 23:10 - 23:10  (00:00)
test     ssh:notty    10.17.121.161    Sun Apr 11 23:10 - 23:10  (00:00)
test     ssh:notty    10.17.121.161    Sun Apr 11 23:10 - 23:10  (00:00)
```
However, in my ```/var/log/fail2ban.log``` file，nothing was recored even waiting for a long time.
```
2021-04-11 21:47:51,733 fail2ban.server         [40587]: INFO    ---------------------------------------------
2021-04-11 21:47:51,733 fail2ban.server         [40587]: INFO    Starting Fail2ban v0.10.2
2021-04-11 21:47:51,739 fail2ban.database       [40587]: INFO    Connected to fail2ban persistent database '/v
2021-04-11 21:47:51,741 fail2ban.database       [40587]: WARNING New database created. Version '2'
2021-04-11 21:47:51,742 fail2ban.jail           [40587]: INFO    Creating new jail 'sshd'
2021-04-11 21:47:51,765 fail2ban.jail           [40587]: INFO    Jail 'sshd' uses pyinotify {}
2021-04-11 21:47:51,771 fail2ban.jail           [40587]: INFO    Initiated 'pyinotify' backend
2021-04-11 21:47:51,772 fail2ban.filter         [40587]: INFO      maxLines: 1
2021-04-11 21:47:51,795 fail2ban.server         [40587]: INFO    Jail sshd is not a JournalFilter instance
2021-04-11 21:47:51,795 fail2ban.filter         [40587]: INFO    Added logfile: '/var/log/auth.log' (pos = 0,
2021-04-11 21:47:51,796 fail2ban.filter         [40587]: INFO      encoding: UTF-8
2021-04-11 21:47:51,796 fail2ban.filter         [40587]: INFO      maxRetry: 5
2021-04-11 21:47:51,796 fail2ban.filter         [40587]: INFO      findtime: 600
2021-04-11 21:47:51,797 fail2ban.actions        [40587]: INFO      banTime: 600
2021-04-11 21:47:51,798 fail2ban.jail           [40587]: INFO    Jail 'sshd' started
```
Also, the ```fail2ban-client status sshd``` records no attacking
```
Status for the jail: sshd
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- File list:        /var/log/auth.log
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:
```
Does this means my ```jail.local``` file's setting was wrong? Could you help me with that?
Thanks!

**Comment by sebres** [comment]
> Those message could be recorded with lastb -i

Since your jail sshd monitoring log-file `/var/log/auth.log`, you have to provide a log excerpt from `/var/log/auth.log`.

> Does this means my jail.local file's setting was wrong?

One thing I can tell you about your `jail.local` right now - Don't copy it from `jail.conf`! Never! Your `jail.local` must contain **solely** the custom options of your (not every setting of `jail.conf` which can be changed by upgrade of fail2ban).
Read [wiki](https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration) for more info.

> Could you help me with that?

No, unless you provide corresponding log-data.

**Comment by zhanwen-cheng** [comment]
Hi sebres, I check my ```/var/log/auth.log``` file,it is empty.  So where could I add an additional log file(my ```/var/log/btmp``` seems to record the failed log attempts) to fail2ban to monitor? 
BTW, to solve the problem, which corresponding log-data you want?

**Comment by sebres** [comment]
> So where could I add an additional log file(my /var/log/btmp seems to record the failed log attempts) to fail2ban to monitor?

Well, our [wiki](https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration) (the link I provided in comment above) answer this question.

But you have to set `logpath = /var/log/btmp` in jail sshd in jail.local... To add it additionally to default logpath you have to specify something like this:
```ini
[sshd]
logpath = %(known/logpath)s
          /var/log/btmp
enabled = true
```

And reload fail2ban or restart this jail.

> to solve the problem, which corresponding log-data you want?

The issue template tells it exactly: "Relevant parts of /var/log/fail2ban.log file" and "Relevant lines from monitored log files"
So if your log is /var/log/btmp, provide an excerpt from this log (any messages around the time of failures attempts).

Since it is incorrect settings at the moment, I'll close it here (can be reopened later if still "failed to detect and ban", once you provide more data). 
Also take a look at [How fail2ban works](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) for possible reasons for the issue.
