### ISSUE TITLE
[FR]: dovecot missing some attacks

### ISSUE THREAD

**Issue by RobbieTheK** [fail2ban/fail2ban#3003]
Here are some logs that the dovecot filter is missing, running fail2ban-0.11.2-1.fc33.noarch and I've confirmed we're using [the latest version](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/dovecot.conf).

```
Apr 13 07:23:44 imap-login: Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small: user=<>, rip=111.7.96.180, lip=x.x.x.x,, session=<PPr03Ni/UmBvB2C0>

Apr 13 14:14:44 pop3-login: Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small: user=<>, rip=64.39.99.71, lip=x.x.x.x, session=<gvjOmt6/lMpAJ2NH>

pop3-login: Info: Aborted login (auth failed, 1 attempts in 0 secs): user=<admin>, rip=31.210.20.134, lip=x.x.x.x,, session=<5PaPC+a/w8Ef0hSG>
```

**Comment by baluballa** [comment]
Think this log lines is due to misconfiguration of your server. Make you key longer:

> SSL_CTX_use_certificate:ee key too small

**Comment by RobbieTheK** [comment]
> Think this log lines is due to misconfiguration of your server. Make you key longer:
> 
> > SSL_CTX_use_certificate:ee key too small

Thanks already did that a while ago, I think this is a new attack.

**Comment by baluballa** [comment]
I have a log line from a misconfigurated dovecot server:
`Apr 21 11:53:17 mx dovecot: imap-login: Error: Failed to initialize SSL server context: Can't load DH parameters: error:1408518A:SSL routines:ssl3_ctx_ctrl:dh key too small: user=<>, rip=x.x.x.x, lip=y.y.y.y, session=<1KwwiHjAN+NPocp4>
`
_(rip=x.x.x.x and lip=y.y.y.y is instead of real ip's)_
Its very similar to yours loglines, also here the `user=<>` also is empty. How can we distinguish by regex?

**Comment by sebres** [comment]
I also don't think it is a new vector (despite an attempt from outside caused this). Just your DH keys are probably too small (or missing), so it is probably not possible to establish a secure connection at all...
See https://askubuntu.com/questions/1263950/imap-login-error-failed-to-initialize-ssl-server-context-cant-load-ssl-certi

**Comment by RobbieTheK** [comment]
Here's why I think it's a true positive. When I log in with a known user here are the logs:

```
Apr 22 09:39:35 imap-login: Info: Login: user=<myuser>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=1471888, secured, session=<17dWz4/A6oV/AAAB>
Apr 22 09:39:35 imap(myuser)<1471888><17dWz4/A6oV/AAAB>: Info: Logged out in=262 out=957 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Apr 22 09:39:35 imap-login: Info: Login: user=<myuser2>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=1471897, secured, session=<Lwdcz4/A7IV/AAAB>
Apr 22 09:39:35 imap(myuser2)<1471897><Lwdcz4/A7IV/AAAB>: Info: Logged out in=227 out=1075 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Apr 22 09:39:35 imap-login: Info: Login: user=<myuser2>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=1471903, secured, session=<cg9lz4/A8oV/AAAB>
Apr 22 09:39:36 imap(myuser2)<1471903><cg9lz4/A8oV/AAAB>: Info: Logged out in=444 out=2150 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Apr 22 09:39:36 imap-login: Info: Login: user=<myuser2>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=1471908, secured, session=<HIlpz4/A9IV/AAAB>
Apr 22 09:39:36 imap(myuser2)<1471908><HIlpz4/A9IV/AAAB>: Info: Logged out in=477 out=2246 deleted=0 expunged=0 trashed=0 hdr_count=1 hdr_bytes=255 body_count=0 body_bytes=0
```

Back on Apr 4 I ran:
`14/04/21 11:29:53 openssl dhparam -out /etc/dovecot/dh.pem 4096`

In `10-ssl,conf`

```
ssl_cipher_list = HIGH:!DH:!aNULL
ssl_dh=</etc/dovecot/dh.pem
```

Restarted dovecot and it actually upgraded last night to `dovecot-2.3.14-1.fc33`.

Also we don't allow pop3 and overnight these logs appeared:


```
Apr 22 02:27:10 pop3-login: Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): erro
r:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small: user=<>, rip=74.120.14.39, lip=xx.xx.xx.xx, session=<sUTwxInAtNBKeA4n>
Apr 22 02:27:10 pop3-login: Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): erro
r:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small: user=<>, rip=74.120.14.39, lip=xx.xx.xx.xx, session=<9/nwxInA6NZKeA4n>
Apr 22 02:27:10 pop3-login: Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): erro
r:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small: user=<>, rip=74.120.14.39, lip=xx.xx.xx.xx, session=<m7HxxInAktlKeA4n>
Apr 22 02:27:10 pop3-login: Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): erro
r:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small: user=<>, rip=74.120.14.39, lip=xx.xx.xx.xx, session=<qWjyxInAIt5KeA4n>
Apr 22 02:27:10 pop3-login: Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): erro
r:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small: user=<>, rip=74.120.14.39, lip=xx.xx.xx.xx, session=<kCfzxInALuJKeA4n>
Apr 22 03:43:53 imap-login: Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): erro
r:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small: user=<>, rip=71.6.199.23, lip=xx.xx.xx.xx, session=<SNVH14rAYutHBscX>
Apr 22 03:43:53 imap-login: Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): erro
r:140AB18F:SSL
```


And one might ask where is [this IP from](https://www.abuseipdb.com/whois/66.240.205.34)?:

```
ISP	CARInet Inc.
Usage Type	Data Center/Web Hosting/Transit
Hostname	malware-hunter.census.shodan.io
```

Shodan! Clearly some snooping.

**Comment by sebres** [comment]
There are several methods which can be used to establish secure layer connection (SSL/TLS, StartTLS etc).
I assume your client just uses a method which does not cause "ee key too small" error. If you'd switch it in client, your dovecot would generate the same error. I think something is still not correct in the config, because the log says about "ssl_cert setting".

> Clearly some snooping.

I don't doubt it, rather I think you are trying to use wrong "method" to detect it.
Anyway, if you really need such regex, just add it to your jail:
```ini
[dovecot]
failregex = %(known/failregex)s
            ^Error: Failed to initialize SSL server context: Can't load SSL certificate \([^\)]*\): [^,]*, rip=<ADDR>
```
But I really recommend to check your configuration (e. g. using [doveconf](https://linux.die.net/man/1/doveconf)) instead, possibly some include will show still obsolete settings by some circumstances.

**Comment by baluballa** [comment]
> There are several methods which can be used to establish secure layer connection (SSL/TLS, StartTLS etc).

Indeed, also if you look at mine log line it starts with:  `Apr 21 11:53:17 mx dovecot: imap-login:`. @RobbieTheK maybe its not Dovecot at all "puking" this to log? Also this **could** be a log-line from misconfigurated server, and you/we don't want to block your/our users due to that?

Also if your server not supports pop3, why do it respond to the port? _Just close port in firewall_.

However I can see in AbuseIPDB that also `74.120.14.39` is listed quite heavily as abuser, so I assume the intention to the attempted logins is not friendly.

**Comment by RobbieTheK** [comment]
> maybe its not Dovecot at all "puking" this to log? Also this **could** be a log-line from misconfigurated server, and you/we don't want to block your/our users due to that?

Good hypothesis but nothing that I can think of is configured to write to our` /var/log/dovecot.log` file. I ran a `strace `against the logs and the only time I saw output was when I checked email via Squirrelmail in a browser.


> Also if your server not supports pop3, why do it respond to the port? _Just close port in firewall_.

Good call, just did that and made sure to disable it from the `dovecot.conf file`.

> But I really recommend to check your configuration (e. g. using [doveconf](https://linux.die.net/man/1/doveconf)) instead, possibly some include will show still obsolete settings by some circumstances.

I didn't see any errors but I did see the `10-ssl.conf` file was set to the default settings for `ssl_cert `and `ssl_key`, so I changed them to the LetsEncrypt version that the web server is using for web pages. Perhaps I'd have to ask the Dovecot mailing list more about this error/warning and how the connection is made with the `ssl_dh `option.

**Comment by panachoi** [comment]
I'm adding this because the subject matches what I want to report, but has nothing to do with SSL issues, its really that the dovecot filter does not handle all authentication failures properly.

fail2ban version: 0.10.2-2.1
Distribution: Debian Buster (but probably applies to all)

When acting as a director/proxy, entries for login failure with a wrong password appear thusly in the log:

```
dovecot: imap-login: proxy($USER,$DSTIP:143): Login failed: [AUTHENTICATIONFAILED] Authentication failed.: user=<$USER>, method=PLAIN, rip=A.B.C.D, lip=W.X.Y.Z, TLS, session=<LACCmwS2kKOyxrG2>
```

There is no coverage for this in filter.d/dovecot.conf; I've just checked latest code and its not there either.
