### ISSUE TITLE
[BR]: ban.Time vs bantime

### ISSUE THREAD

**Issue by tc60045** [fail2ban/fail2ban#3004]
lines 65 and 68 of jail.conf reference ban.Time, which is not previously declared in jail.conf

on line 101 there is a reference to bantime, but it isn't clear whether bantime = ban.Time...

also unclear after *casual* look at jail in code here how ban.Time is discovered, but it is referenced only as ban.Time

Suggest:  
- declare the variable prior to formulas, in preferred form, or indicate that both forms are interchangeable
- mention that the default value follows at around line 100 and is used in formulas like so
- mention for noobs that it can be declared at jail level

Just a suggestion.  Your pizza store, your rules.

**Comment by sebres** [comment]
The mentioned `ban.Time` (as well as `ban.Count` etc) in the formula belonging to `ban` member in expression on python side, which represent dynamic data of current ticket used by calculation of a new banning time in `bantime.increment` process.
https://github.com/fail2ban/fail2ban/blob/6893d5a8b78fbdf263df8a233b3b9ac343c7a02c/config/jail.conf#L63-L68

As it is released I will not change it to `bantime` (at least due to compatibility reasons). 
Although I would not recommend to rewrite this formula (e. g. it were better to use `bantime.factor` instead), but one could do that, so such change would be not backwards compatible anymore.

As for relation to a configuration option `bantime` - although in my opinion it is obvious, but there is indeed nothing to argue against adding this to the related comment.

**Comment by tc60045** [comment]
Very easy for anyone to complain with a red pen; here is my attempt to use the "black pen" to write what I think you say in a way that may avoid future questions.  I expose myself to your red pen, and as with my earlier note, I respect fully the legacy of this project.  Best, TC

`# bantime -- history and new features
# bantime has been a critical variable for fail2ban and it will remain a key configuration variable
# It represents the number of seconds that a host will be banned, and it can be defined per jail or 
# here in the default section (default, if left commented out, is 600 seconds)
# 
# In version 0.11, bantime has become a python class in our code, enabling more user flexibility and fine-tuning.
# We illustrate two different and popular conventions below, each of which can be uncommented and used.
# Furthermore, we have enabled custom-specified expressions using the elements of ban (ban.Time, 
ban.Factor, ban.Count, ban.multipliers), specified with bantime.formula = ...
# 
# For new users, we recommend highly that you test the supplied conventions fully before attempting your own custom formula.  "Exponential" ban times are easily achieved using the first such example by just uncommenting the line.  
#
# Future compatibility of formulas is more likely for formulas that utilize the ban.element construction, as with bantime.formula = ....  
# Any use of bantime.element in a formula is mapped to ban.element directly, for compatibility
# 
`

**Comment by sebres** [comment]
OK, thanks for the suggestions.
But now I guess your assumptions were a bit false probably - so I try to explain what exactly can be incorrect:

> In version 0.11, bantime has become a python class in our code

No or rather not really. Only the formula is such a thing solely, that is available in configuration as pythonic expression.
But this option is optional and already set correctly by default (just not enabled unless `bantime.increment = true` is not set). Moreover as I already wrote above "I would not recommend to rewrite this formula (e. g. it were better to use `bantime.factor` instead)". Nobody likes "undocumented" features, therefore it is available in jail.conf as a short comment, just I am also not really in the mode to provide a description resembling "dissertation" by its size (at least not as comment).

> "Exponential" ban times are easily achieved using the first such example by just uncommenting the line.

This (as many other commented parameters in config) is default value - you don't need to uncomment something excepting `bantime.increment = true` to let the bantime grow for recidive intruders.

Furthermore, normally nothing must be uncommented in jail.conf directly (because it can get conflicts resp. will be overwritten by upgrade).  Please read [wiki :: Proper fail2ban configuration](https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration).

So to allow this feature you basically need to specify only this in `jail.local` in default or jail section:
```ini
bantime.increment = true
```
That's it.
But it is also recommended to set `bantime.maxtime` (to restrict unneeded endless growth).
Few details to this matter can be found in https://github.com/fail2ban/fail2ban/issues/2652#issuecomment-596107934

As for black or red pen, if you really have an interest to participate in exciting process of the documentation writing, welcome with PR - [edit man/jail.conf.5](https://github.com/fail2ban/fail2ban/edit/0.11/man/jail.conf.5) - the theme incremental banning (and its parameter description) seems to be completely lacking yet.
But please try to remain as laconic as possible. For a bit larger treatises you are also welcome to our wiki where you could also write [new](https://github.com/fail2ban/fail2ban/wiki/_new) or extend some existing article. 
Also our [discussions](https://github.com/fail2ban/fail2ban/discussions) are open for everyone to ask something or leave some comment.
