### ISSUE TITLE
[BR]: Verify existence and executability of ignorecommands

### ISSUE THREAD

**Issue by ohreally** [fail2ban/fail2ban#3006]
I discovered #3005 because the fail2ban logs were full of false positives for Googlebot. The reason for this is probably that the existence of the script is not verified before executing it, and the `No such file or directory` exit code from the OS is interpreted by fail2ban as the `Block this IP address` exit code from the script.
Which means that FreeBSD systems using the _apache-fakegooglebot_ filter have probably not had their websites indexed by Google for a while.

So, before executing a script from this directory, it's existence and executability should be verified. Or the exit code logic should be turned around, so that a non-existing script would cause an IP address to be permitted.

**Comment by sebres** [comment]
> So, before executing a script from this directory, it's existence and executability should be verified.

I don't think so. Sure one can do it (and write an error message), but since it is ignore command what the filter should then do? Ignore or not ignore? The answer is obvious in my opinion.

> Or the exit code logic should be turned around, so that a non-existing script would cause an IP address to be permitted.

Definitely no. Since the message was found by `failregex` (fail2ban filter wanted to generate a ban) it is quasi legitimate to say if ignorecommand is not found simply don't ignore anything (as it were not specified). Also note that in common case - having a false positives is many time better than completely overlooking the attack vector (ignoring everything).

Note that fail2ban is just a tool and as any other tool must be properly used (also if it is preconfigured by maintainers for your "distro" a bit incompletely).
