### ISSUE TITLE
How to not unban everyone when the service stops

### ISSUE THREAD

**Issue by Foxite** [fail2ban/fail2ban#3008]
Currently, when I stop fail2ban, it removes all bans from the firewall, and reinstates them when the service is started again.

Given the amount of bans I have on my server (as all IPs are permanently banned after a single failure, because I'm the only user and I have no chill), it takes about a minute to restart the service. Additionally, I'm concerned that the speed at which it sends notifications for every reinstated ban (which is done via Discord) might get me in trouble for violating the rate limit.

Is there any way to avoid this behaviour? And what is the reason for it?

**Comment by sebres** [comment]
> Is there any way to avoid this behaviour? 

As for unban by stop - no, there is no such possibility (excepting the command `actionflush`, which doing a "bulk" unban if defined in action). If you don't need an unban on stop for some of your custom actions, just define `actionflush = true` in such an action and fail2ban will stop execution of `actionunban` for this action.
As for (re)ban by start - at the moment there is no bulk ban (I have only experimental branch inmplemented such thing for several banning actions, work still in progress). Another possibility basically introduced for non-banning actions (like mailing actions) is `norestored` option, which can avoid repeated notification by restart (see #1669).

Anyway the functionality for reban of active tickets by restart is intended and cannot be avoided at the moment.
But if you need to reload configuration (new or modifying regex, new jail etc pp), you can use `fail2ban-client reload` instead.

> And what is the reason for it?

Well, fail2ban has every ban under its own control and there is no direct back relation between actions and banned tickets, so if it gets stopped it must unban every ticket, to be able to ban it hereafter properly (without possible conflicts in some chains of action) as well as to leave safe state (everything made from fail2ban is reversed after stop).

Also note that fail2ban cannot predict the reason of the stop:
- user want to reban everything (e. g. iptables gets flushed by some other service, for instance `iptables-restore` or is in an unusable state due to some error of fail2ban, net-filter subsystem or some program manipulating on same subsystem chains);
- user want to reban everything using another banning action (switch from iptables to ipset or nftables, etc);
- user made some another fundamental changes in configuration, so after restart the bans are not the same (e. g. defined different target chain etc);
- user don't want to use fail2ban anymore;

Theoretically we can provide some option for stop signaling an intention to leave the bans by stop, but to make a proper (re)start hereafter fail2ban need some feedback functionality from banning action (e. g. list of currently banned tokens) or a silent ignore for restore tickets, so the banning action can be reimplemented properly to consider such a restart.

But I would prefer to fulfill the bulk ban solution instead.
