### ISSUE TITLE
[BR]: fail2ban regex match but not work @ Ubuntu 20.04

### ISSUE THREAD

**Issue by MicroDuke** [fail2ban/fail2ban#3041]
```
root@lts:/var/log# fail2ban-regex auth.log sshd.conf

Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use         maxlines : 1
Use      datepattern : Default Detectors
Use         log file : auth.log
Use         encoding : UTF-8


Results
=======

Failregex: **3008** total
|-  #) [# of hits] regular expression
|   6) [1] ^[iI](?:llegal|nvalid) user <F-USER>.*?</F-USER> from <HOST>(?: (?:port \d+|on \S+|\[preauth\])){0,3}\s*$
|  19) [3] ^<F-NOFAIL>Received <F-MLFFORGET>disconnect</F-MLFFORGET></F-NOFAIL> from <HOST>(?: (?:port \d+|on \S+)){0,2}:\s*11:
|  21) [6] ^<F-MLFFORGET><F-MLFGAINED>Accepted \w+</F-MLFGAINED></F-MLFFORGET> for <F-USER>\S+</F-USER> from <HOST>(?:\s|$)
|  **24) [2998**] ^Unable to negotiate with <HOST>(?: (?:port \d+|on \S+)){0,2}: no matching (?:(?:\w+ (?!found\b)){0,2}\w+) found.
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [3163] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
`-

Lines: 3163 lines, 9 ignored, 2999 matched, 155 missed
[processed in 1.00 sec]

|- Ignored line(s):
....................
`-
Missed line(s): too many to print.  Use --print-all-missed to print all 155 lines
```

```
root@lts:/var/log# fail2ban-client status sshd
Status for the jail: sshd
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     1
|  `- File list:        /var/log/auth.log
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:
```

**Comment by sebres** [comment]
Well this shows only that fail2ban-regex find a lot of failures (but fail2ban does not), but it is not obvious:
- whether this failures are actual (e. g. how old there are, e.g. no log rotation);
- whether fail2ban (jail sshd) is running with same filter you did test by fail2ban-regex (no restart/reload after update?);
- which parameters have been setting for the jail (`maxretry`, `findtime` and `bantime`)
- **which fail2ban version is it**

See https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works for more info.

If you freshly started fail2ban (I guess so), note that fail2ban would only consider failures occurring `findtime` seconds ago up to now, so a lot of those 2999 findings may be not interesting (anymore).

Moreover normally `Unable to negotiate with ...` (which is the most fail in your case) is only matched in mode `extra` (or `aggressive`), in your test with `fail2ban-regex` I doesn't see this was set at all, so it is a mystery to me how it can show this result.
https://github.com/fail2ban/fail2ban/blob/579c6a94aff0bb680090b3be1aef91491cf0a061/config/filter.d/sshd.conf#L81-L82
Do you have some customizations in your sshd-filter?
Because it should find that with `fail2ban-regex auth.log sshd[mode=aggressive]` for instance, but not how you tested this. 
In this case you have also to set `mode = aggressive` in sshd jail (in jail.local) to do the same in fail2ban (but fail2ban-regex does not consider parameters specified in jails, they must be supplied directly in command line).

**Comment by MicroDuke** [comment]
> Well this shows only that fail2ban-regex find a lot of failures (but fail2ban does not), but it is not obvious:
> 
> * whether this failures are actual (e. g. how old there are, e.g. no log rotation);

> * whether fail2ban (jail sshd) is running with same filter you did test by fail2ban-regex (no restart/reload after update?);
> * which parameters have been setting for the jail (`maxretry`, `findtime` and `bantime`)
> * **which fail2ban version is it**
> 
> See https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works for more info.
> 
> If you freshly started fail2ban (I guess so), note that fail2ban would only consider failures occurring `findtime` seconds ago up to now, so a lot of those 2999 findings may be not interesting (anymore).
> 
> Moreover normally `Unable to negotiate with ...` (which is the most fail in your case) is only matched in mode `extra` (or `aggressive`), in your test with `fail2ban-regex` I doesn't see this was set at all, so it is a mystery to me how it can show this result.
> https://github.com/fail2ban/fail2ban/blob/579c6a94aff0bb680090b3be1aef91491cf0a061/config/filter.d/sshd.conf#L81-L82
> 
> 
> Do you have some customizations in your sshd-filter?
> Because it should find that with `fail2ban-regex auth.log sshd[mode=aggressive]` for instance, but not how you tested this.
> In this case you have also to set `mode = aggressive` in sshd jail (in jail.local) to do the same in fail2ban (but fail2ban-regex does not consider parameters specified in jails, they must be supplied directly in command line).

Thanks
I do follow step 
1、modify /etc/fail2ban/filter.d/sshd.conf as below:
mode = extra
filter = sshd[mode=aggressive]
2、add 3 line in  /etc/ssh/sshd_config file as below:
Port = **portno1**
Port = **portno2**
Port = **portno3**
3、modify /etc/fail2ban/jail.conf file
#diff jail.conf jail.conf.org
101c101
< bantime  = 1d
---
> bantime  = 10m
285,286c285
< enabled = true
< port    = **ssh,**portno1,portno2,portno3**
---
> port    = ssh
4、flush log file & restart ssh & restart fail2ban
#cat  /dev/null > /var/log/auth.log
#rm /var/log/fail2ban.log
#/etc/init.d/ssh restart
#/etc/init.d/fail2ban restart
5、Others Information
![image](https://user-images.githubusercontent.com/24806479/121781553-eb3d4380-cbd7-11eb-88af-197c603afda7.png)

(The two  BAN IPs in the picture are manually added by me）

My  server has been under attack all the time, please help me to check where fail2ban is configured incorrectly, thank you.

**Comment by sebres** [comment]
1. The setting `mode = extra` **in filter** does nothing because it will be overwritten from jail:
https://github.com/fail2ban/fail2ban/blob/92f90038fa67d719c55c75f5eff8059e849fe747/config/jail.conf#L123-L129

Also the setting `filter = sshd[mode=aggressive]` has nothing to do in the filter too. This must be done in jail.local (but it is normally enough to set `mode = aggressive` in the jail.

2. ...

3. Don't modify `jail.conf` file (this can be overwritten or becomes conflicting by upgrade). Any custom setting must be done in new file `jail.local` instead. Better would be to restore `jail.conf` from original if you can.

> My server has been under attack all the time ...

Well it is not directly an attack, just a botnet is unable to use new methods to exchange session keys (so basically nothing happens further). But you could indeed ban them using aggressive mode...

Just create `/etc/fail2ban/jail.local` file and set everything (and `mode`) there:
```ini
[DEFAULT]
# default settings going here ...

[sshd]
mode = aggressive
port = ssh,portno1,portno2,portno3
bantime  = 1d
enabled = true
```
That's it.

**Comment by MicroDuke** [comment]
> 1. The setting `mode = extra` **in filter** does nothing because it will be overwritten from jail:
>    https://github.com/fail2ban/fail2ban/blob/92f90038fa67d719c55c75f5eff8059e849fe747/config/jail.conf#L123-L129
> 
> Also the setting `filter = sshd[mode=aggressive]` has nothing to do in the filter too. This must be done in jail.local (but it is normally enough to set `mode = aggressive` in the jail.
> 
> 1. ...
> 2. Don't modify `jail.conf` file (this can be overwritten or becomes conflicting by upgrade). Any custom setting must be done in new file `jail.local` instead. Better would be to restore `jail.conf` from original if you can.
> 
> > My server has been under attack all the time ...
> 
> Well it is not directly an attack, just a botnet is unable to use new methods to exchange session keys (so basically nothing happens further). But you could indeed ban them using aggressive mode...
> 
> Just create `/etc/fail2ban/jail.local` file and set everything (and `mode`) there:
> 
> ```ini
> [DEFAULT]
> # default settings going here ...
> 
> [sshd]
> mode = aggressive
> port = ssh,portno1,portno2,portno3
> bantime  = 1d
> enabled = true
> ```
> 
> Then reload fail2ban... That's it.
Thanks a lot.
I will try it .
