### ISSUE TITLE
[RFE]: fail2ban_block_IPS_script 

### ISSUE THREAD

**Issue by zer0nem0** [fail2ban/fail2ban#3042]
Hi

Its possible add to jail.local ban ips list?

example:

ignoreip = 10.0.0.0/16

banip = 192.168.0.0/16 187.100.0.0/16

This method i cant add more IPs, IPranges etc. just one IP every add banip..

fail2ban-client set sshd banip WW.XX.YY.ZZ 

Someone had some script add IP blacklist from TXT?

**Comment by sebres** [comment]
Well, sure it would be possible, just it is questionable whether fail2ban may need such functionality, e. g. why you would like to do this using fail2ban? I mean not via iptables (nftables, whatever firewall or net-filter sub-system you currently use)?

Anyway, if the banning action can basically do this for the subnets (e. g. iptables actions), you can surely do it after start of fail2ban using:
```ini
fail2ban-client set sshd banip 192.168.0.0/16
```
Just fail2ban will unban it after `bantime` specified for the jail.
Thus better you'd create some other jail (monitoring some empty log) with persistent ban, and ban it there. And you would need to ban them only once, because persistent bans will be also restored after restart of fail2ban:
```ini
[permanent]
logfile = /etc/fail2ban/empty.log
bantime = -1
filter =
failregex = ^<ADDR>$
banaction = iptables-allports
```
and calling `fail2ban-client set permanent banip 192.168.0.0/16` once will block this subnet infinitely (unless you don't invoke unban manually).

If you use banning action which is unable to ban subnets, either you'd switch to another action or even rewrite the action to make it possible. This is anyway a prerequisite for that (regardless fail2ban would get such a functionality for initial bans).

Also note that fail2ban v.0.11 has incremental banning feature, which can help to ban intruders faster and for longer time, so may be if you would use that it were better option (only IPs really made a failures going banned and they have fewer attempts, that makes a bruteforce quasi senseless).

FWIW, as for subnet banning, there is another FR #927

**Comment by zer0nem0** [comment]
Hi Sebres

Thanks!
" I mean not via iptables " etc. 
I cant add it fastly whole IP (+ranges) Geo example "china" because its slow and process it.

Over host.deny doesnt work because its a "large file"

I need this way because someone try to login all the times with huge different geo IPs.
I think some noob want to make my fail2ban sqlite to huge "large" file for stopping the fail2ban service.

Thanks!

KR:

**Comment by zer0nem0** [comment]
> Well, sure it would be possible, just it is questionable whether fail2ban may need such functionality, e. g. why you would like to do this using fail2ban? I mean not via iptables (nftables, whatever firewall or net-filter sub-system you currently use)?
> 
> Anyway, if the banning action can basically do this for the subnets (e. g. iptables actions), you can surely do it after start of fail2ban using:
> 
> ```ini
> fail2ban-client set sshd banip 192.168.0.0/16
> ```
> 
> Just fail2ban will unban it after `bantime` specified for the jail.
> Thus better you'd create some other jail (monitoring some empty log) with persistent ban, and ban it there. And you would need to ban them only once, because persistent bans will be also restored after restart of fail2ban:
> 
> ```ini
> [permanent]
> logfile = /etc/fail2ban/empty.log
> bantime = -1
> filter =
> failregex = ^<ADDR>$
> banaction = iptables-allports
> ```
> 
> and calling `fail2ban-client set permanent banip 192.168.0.0/16` once will block this subnet infinitely (unless you don't invoke unban manually).
> 
> If you use banning action which is unable to ban subnets, either you'd switch to another action or even rewrite the action to make it possible. This is anyway a prerequisite for that (regardless fail2ban would get such a functionality for initial bans).
> 
> Also note that fail2ban v.0.11 has incremental banning feature, which can help to ban intruders faster and for longer time, so may be if you would use that it were better option (only IPs really made a failures going banned and they have fewer attempts, that makes a bruteforce quasi senseless).
> 
> FWIW, as for subnet banning, there is another RFE #927

Hi Sebres

I have a little bit problem.

Your fail2ban regex doesnt work for me.

I added many IP, IP ranges for empty.log but still doesnt work. (debian 10)

I tried to add it /home/banned.log + changed logfile to logpath + add enabled = true still doesnt work..
Should i add it some pemanent.conf to conf.d ?

[permanent]
enabled = true
logpath = /home/banned.log
bantime = -1
filter =
failregex = ^<ADDR>$
banaction = iptables-allports

my banned.log looks like so:

27.116.56.0/22
43.230.209.0/24
43.249.40.0/22
43.250.136.0/22
45.65.58.0/23
45.116.128.0/23
45.125.224.0/22
45.126.253.0/24
57.92.0.0/20
58.147.128.0/19
59.153.124.0/22
61.5.192.0/20
62.4.115.0/24
63.76.180.160/29
63.99.56.40/29
64.86.63.64/27

i added my orig IP adress and orig IP adress range but still doesnt work..

Pls send me some solutions :)

Thanks! Yur da best :)

**Comment by sebres** [comment]
No, I didn't tell you that new jail should monitor some log (moreover I told you it must be an empty log).
Instead you had to use `fail2ban-client set permanent banip ...` to ban the intruder manually (one time, hereafter they are in database of fail2ban and will be always banned by restart).
And failregex was a simplest RE which would work (fail2ban does not allow a jail without failregex at the moment).

Your current approach is not so simple at the moment, because to do such kind of monitoring (of `banned.log` with a subnets), you must have newest version supporting `<SUBNET>` or `<ADDR>/<CIDR>` tags (which must be used instead `<ADDR>`), which was part of #2560  and you have to provide a `datepattern` and write a timestamp to the log, because fail2ban before 0.10.6 or 0.11.2 was unable to process log-message without date/time.

Thus don't do this, just create empty.log and add your permanently banned subnets using `fail2ban-client`.

**Comment by zer0nem0** [comment]
Yeah but its a same manualy steps like this one:

sudo fail2ban-client set sshd banip WW.XX.YY.ZZ

So im not smarter now :)

Its manualy and slow.. 

this iptables mod is work but still slow .. 

xargs -I {} iptables -A INPUT -s {} -j DROP < ipaddresses.txt

thanks anyway.. i will try some other method.

**Comment by sebres** [comment]
> Yeah but its a same manualy steps like this one

No, it is not.<br/>
`fail2ban-client set sshd banip WW.XX.YY.ZZ` would ban **single address** and unban it after `bantime` (forget the ban).
`fail2ban-client set permanent banip WW.XX.YY.ZZ/CIDR` would ban a **subnet** and never unban it (due to persistent `bantime` specified by the jail), and because unban is never occur you don't need to repeat it.

**Comment by zer0nem0** [comment]
LOL..

Yes its same method.. Of course i can add IP with client example

fail2ban-client set sshd banip WW.XX.YY.ZZ/CIDR

its work for me like a hell long time ago.... (bantime = -1, banaction = multiport)

now i try to add ips (with range) like so:

fail2ban-client set sshd banip ip1/CIDR ip2/CIDR ip3/CIDR..............................

**Comment by zer0nem0** [comment]
> `fail2ban-client set sshd banip WW.XX.YY.ZZ` would ban **single address** and unban it after `bantime` (forget the ban).
> `fail2ban-client set permanent banip WW.XX.YY.ZZ/CIDR` would ban a **subnet** and never unban it (due to persistent `bantime` specified by the jail), and because unban is never occur you don't need to repeat it.

Hier ist my solutions

for IP in $(cat banned_ip_list); do fail2ban-client set permanent banip $IP; done

verbose:

for IP in $(cat banned_ip_list); do echo "Banning $IP"; fail2ban-client set permanent banip $IP; done

**Comment by sebres** [comment]
> its work for me like a hell long time ago

what do you mean? if it works, why do you try to ban a subnet in the cycle expanded with single IPs?
