### ISSUE TITLE
[RFE]: Syslog socket as backend

### ISSUE THREAD

**Issue by booshlinux** [fail2ban/fail2ban#3043]
#### Feature request type
New backend idea

#### Description
When sourcing logs for `fail2ban` to process, it would be nice to have the ability to have a open socket (either TCP or UDP) that accepts valid `syslog` formatted messages, to which then fail2ban processes. If this was possible, multiple hosts could send `syslog` data to one `fail2ban` host, instead of having multiple `fail2ban` instances installed and running between many hosts.

Consider the following:
Server A: Host with `fail2ban` running on it
Server B - *: Hosts that are sending logs to Server A via the `syslog` protocol. 

Server A has the hypothetical socket listening that is provided by `fail2ban` on port 5514 UDP.
Server B sends a valid syslog message to Server A over port 5514
Server A parses the data, and extracts the message
Server A continues with normal `fail2ban` processing of the matched line

#### Considered alternatives
There are workarounds to this, but it involves other packages. For example, `syslog-ng` can be configured to accept `syslog` messages on the `fail2ban` server, as well as write that data to a local file under `/var/log`. Hosts that need to send messages to the `fail2ban` server send their data to `syslog-ng`. The logs effectively are collected and parsed with `fail2ban`. The only problem is disk usage and log rotation. Seems like an over abundant use of tools/applications. 

#### Any additional information
Facility and priority of the `syslog` message could be parsed to provide `journalmatch` style filtering when many messages are received.

**Comment by sebres** [comment]
> multiple hosts could send syslog data to one fail2ban host, instead of having multiple fail2ban instances installed and running between many hosts.

So the intention is to mirror syslog/journal messages across the servers? Then why the new backend must directly monitor the messages on some port? With other words which pros exactly would this provide compared to the systemd backend monitoring journals?
Following terms from your scenario: fail2ban on server A uses systemd backend to monitor journal, server B mirrors the messages to server A, systemd backend would find the messages from server B in journal of A...
Is this not what you approximately need?

If we are rather speaking about something like fail2ban network, I doubt what you're suggesting would be better strategy than a RFE #881.
Just to compare: in case of implemented network support, fail2ban would supply the attempt (after read, parse, search of match in the log/journal) and put it to other fail2ban instances in cluster as ready attempt (without parsing and match search) etc.
Also the work may be distributed in this way across the servers (one server takes the search on, another the banning).

**Comment by booshlinux** [comment]
> fail2ban on server A uses systemd backend to monitor journal
> So the intention is to mirror syslog/journal messages across the servers?

Not exactly. Server A has the hypothetical "backend" in question, lets call it the `syslog` backend for sake of example. The backend provides a listening port (5514 UDP for example), that accepts `syslog` messages. Once data is received on that port, it continues parsing it as normal. Example:
Server B sends log line to Server A over port 5514 with the following content:
```
Dec 31 2020 dovecot[12345]: Failed login from 192.168.1.200
```
Server A parses this log line as normal, extracting `192.168.1.200`, and continuing normal `fail2ban` operations.

`syslog` messages are not mirrored across servers, but instead accepted on the `fail2ban` server.

**Comment by sebres** [comment]
How it is deviating from:
- server B, C, ..., Z mirroring the logs to A;
- server A (with fail2ban) listening journal (instead of the port);
- fail2ban on server A finding failures and banning them

I still does not see the pros for the UDP/port-listener stuff in fail2ban (as backend or whatever). Or rather why it must be part of fail2ban, if it is already now possible using systemd backend (for the mirrored logs)...
If you don't want mix mirrored messages with messages of server A, just configure different target path for receiving journal (can be set on fail2ban side using `backend = systemd[journalpath=...]` or use filter (so restrict the `journalmatch` by servername or some option signaling "remote" message).

So just would like to hear the arguments why this new socket-listener (and syslog-parser) must be necessarily a part of fail2ban.

> The end goal of this addition would be the ability to monitor multiple hosts at the same time from one fail2ban host, while sending blocks to an external firewall, rather than one running on the host getting attacked.

I understood this, and my second part of previous comment (about fail2ban network) was just an additional suggestion (e. g. an attempt to show the pros of distributed handling).

> Assume there are 20 servers behind one firewall. It makes more sense to send logs from those 20 servers to one fail2ban server to parse, and in the event of blocking an IP address, that one fail2ban server sends a request to the (external) firewall to block the IP

No, it does not make more sense.
You want send the whole log traffic of 20 servers (probably multiple services of them) to single fail2ban instance, what can cause a large latencies (between occurrence of failure and resulting ban) due to huge amount of data to transfer and parse, up to overloading of this fail2ban instance completely.
Moreover it is very probably that only 1/20 (of whole log traffic) is relevant for every single instance, and no one of them is interesting from the point of view for the remaining 19 servers, but the log-traffic from this 19 servers would burden this common fail2ban instance and therefore every single server in this net. 
Note that the latencies could grow exponentially, because it is like a snowball - so every additional second (by delayed ban) allows the intruder continue the attack, so generate more failures, more log-traffic and in result increase the latency for new other bans. And all that would be twentyfold (because 20 servers doing this).
It depends on many factors, like how many jails there are, how much parasitic (in sense of fail2ban) log-traffic is to expect, how large is `maxretry` (and `findtime`), etc, but in simplest case on well visited hosts such snowball can completely paralyze the work of fail2ban, and as result either "open" the servers for an attack (all the servers), or even overload this servers too, because those load would also grow.

Although I understand the intention or necessity to use a common firewall (as a central place behind the whole net used for blocking), but I don't follow the needs to relocate fail2ban to exactly one server. It is at least doubtful strategy in my opinion, therefore I meant the fail2ban network before.

**Comment by booshlinux** [comment]
> How it is deviating from:
> server B, C, ..., Z mirroring the logs to A;
> server A (with fail2ban) listening journal (instead of the port);
> fail2ban on server A finding failures and banning them

Elaborate on "mirroring". How does the data get to Server A from Server B? I think this is where the confusion is happening. I don't refer to anything "mirroring", but `sending` to Server A from Server B, through the `syslog` protocol. 

> ... if it is already now possible using systemd backend (for the mirrored logs)...
> ... So just would like to hear the arguments why this new socket-listener (and syslog-parser) must be necessarily a part of fail2ban.

Your only thinking of grabbing logs from `systemd`, a log file, etc. The logs would be sourced **from the socket itself**, *not* any file on the filesystem.

>No, it does not make more sense.
You want send the whole log traffic of 20 servers (probably multiple services of them) to single fail2ban instance, what can cause a large latencies (between occurrence of failure and resulting ban) due to huge amount of data to transfer and parse, up to overloading of this fail2ban instance completely.

Are you saying that when `failban` matches a line and executes `actionban`, it's a blocking process which will halt all other operations until completed?

>Moreover it is very probably that only 1/20 (of whole log traffic) is relevant for every single instance, and no one of them is interesting from the point of view for the remaining 19 servers, but the log-traffic from this 19 servers would burden this common fail2ban instance and therefore every single server in this net.

Yes you are correct, that's why you don't send every log that gets generated over syslog, that's the point of filtering. I understand where your coming from in regards to this request, and after hearing your opinions, I no longer think this would be a good idea.

Thanks.

**Comment by sebres** [comment]
>  I don't refer to anything "mirroring", but sending to Server A from Server B, through the syslog protocol.

Yes and it is the same thing.

> Your only thinking of grabbing logs from systemd, a log file, etc. The logs would be sourced from the socket itself, not any file on the filesystem.

But systemd module would use data it already has in cache, so it does not necessarily expect a read from file here.

> Are you saying that when failban matches a line and executes actionban, it's a blocking process which will halt all other operations until completed?

Not directly. There are several workers, so for instance firstly 1 worker parses the log (or journal, or whatever the backend is) to find a failures, if it found `maxretry` attempts during `findtime`, it cause a ban, which is executed in different worker.
The whole thing is multi-threaded, sure... But python is not really multi-threaded (due to GIL one could even say it behaves often like single-threaded process). Anyway you have to consider the time to transfer etc. It is complex, but one could try and measure the overhead.

> that's why you don't send every log that gets generated over syslog, that's the point of filtering.

Sure, just one can not estimate how this filtering is better than a filtering in fail2ban. In any case, you'd probably send much more messages than fail2ban would recognize as a failure, so the ratio between parasitic log-traffic and fail-traffic will grow, and this would cause the mentioned snowball issue and not on fail2ban side only, because you must still consider the time for the transfer over the network (all the messages) and its extra load (cpu's and bandwidth are not endless), etc.

But would not the same filtering (type or facility I guess) work if one would send it to the instance with systemd journal (the mirror I suggested above, but I really don't know whether syslog-ng supporting systemd-journal source driver and all that works).
