### ISSUE TITLE
[BR]: firewallcmd-ipset.conf multiport invalid port/service `1-65535' specified

### ISSUE THREAD

**Issue by kowach** [fail2ban/fail2ban#3047]
fail2ban v0.11.2
firewalld v0.8.2
CentOS 8.3.2011

Here is the error log:

      exec: ipset create f2b-dovecot hash:ip timeout 0
      firewall-cmd --direct --add-rule ipv4 filter INPUT_direct 0 -p tcp -m multiport --dports "$(echo '1:65535' | sed s/:/-/g)" -m set --match-set f2b-dovecot src -j REJECT --reject-with icmp-port-unreachable
      ipset v7.1: Set cannot be created: set with the same name already exists
      Error: COMMAND_FAILED: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore v1.8.4 (nf_tables): invalid port/service `1-65535' specified
      Error occurred at line: 2
      Try `iptables-restore -h' or 'iptables-restore --help' for more information.

Looks like this version of firewall-cmd does accepts dports delimiter "-" in "1-65535" and it should be left "1:65535".

Solution is to replace multiport in firewallcmd-ipset.conf:
`multiport = -p <protocol> -m multiport --dports "$(echo '<port>' | sed s/:/-/g)"`
to
`multiport = -p <protocol> -m multiport --dports "<port>"`

**Comment by sebres** [comment]
Hmm... 
and how one would handle this now?!

#2821 reported about vice versa situation (and therefore it was fixed in a038fd5dfe8cb0714472833604735b83462a217d), but not even a year later it must be reverted...

Still worse if this depends now on firewalld backend (e. g. `-` vs. `:` related to `iptables` vs. `nftables`).

But how fail2ban action must distinguish what exactly is expected (to be backwards and "forwards" compatible)?

*I'm slowly tired to ask - why one uses this weird wrapper "firewalls" instead of native net-filters like iptables/ipset or nftables?*

**Comment by kowach** [comment]
Oh, that is very messy situation.
Now I know why my iptables are empty, because nftables replaced it :smile:

**Comment by kovacs-andras** [comment]
> Oh, that is very messy situation. Now I know why my iptables are empty, because nftables replaced it smile

No, it isn't. You should check `iptables-nft` https://www.redhat.com/en/blog/using-iptables-nft-hybrid-linux-firewall

**Comment by kovacs-andras** [comment]
Imho it's a matter of taste how people like to interact with their firewalls. It's probably harder to break but easier to read this way.

There is a clear statement in man firewall-cmd:
_Warning: Direct rules behavior is different depending on the value of FirewallBackend. See CAVEATS in firewalld.direct(5)._

So it requires a simple check like:
`grep -q '^FirewallBackend=nftabless' /etc/firewalld/firewalld.conf`
If it returns true, we should use `-` as an interval separator instead of `:`
Basically... that's it.

**Comment by kovacs-andras** [comment]
@sebres do the sed commands are necessary?
I think tt would be faster with a different binary, shell substitution, etc. or do this char replacement only once.
Or do you prefer sed because it's easier to read?

**Comment by sebres** [comment]
> So it seems like the best would be just revert to `:` from `-`

Agree. 
I'll revert a038fd5dfe8cb0714472833604735b83462a217d because if someone need it with `-` (for nft and other backends), it is simply possible by specifying own port range. Vice versa it would be impossible (since it gets wrapped in action).
Thus the conclusion is very simple.

And I'll repeat my statement: 
*Why one uses this weird wrapper "firewalls" in fail2ban instead of native net-filters like iptables/ipset or nftables?*
*Why?!*

**Comment by kovacs-andras** [comment]
Many thanks!
It felt disrespectful to make a PR with this revert in it but please, let me know if I can further help!

**Comment by sebres** [comment]
Just for the record:
a038fd5dfe8cb0714472833604735b83462a217d was reverted in 4b54a07d71a6ce1c85a3eae92bace6c0dadcdcfb (no replacement of range separator takes place in the firewalld actions anymore).
Released in v.1.0.x.
