### ISSUE TITLE
[FR]:  over lap of rules in apache-noscript.conf and apache-overflows.conf

### ISSUE THREAD

**Issue by RobbieTheK** [fail2ban/fail2ban#3049]
Fail2ban 0.11.2-1 on Fedora, from `/etc/fail2ban/filter.d/apache-nohome.conf`

```
# Fail2Ban filter to web requests for home directories on Apache servers
# Regex to match failures to find a home directory on a server, which
# became popular last days. Most often attacker just uses IP instead of
# domain name -- so expect to see them in generic error.log if you have
# per-domain log files.
```

Is this description still accurate? Also, poor English in "became popular last days".

Isn't this regex overlapping in `apache-noscript.conf`

`failregex = ^%(_apache_error_client)s (AH00128: )?File does not exist: .*/~.*`

From `/etc/fail2ban/filter.d/apache-noscript.conf`

`# Fail2Ban filter to block web requests for scripts (on non scripted websites)`

What are "`non scripted websites`"?

So is the following regex an overlap from `apache-noscript.conf`
```
script = /\S*(?:php(?:[45]|[.-]cgi)?|\.asp|\.exe|\.pl|\bcgi-bin/)
prefregex = ^%(_apache_error_client)s (?:AH0(?:01(?:28|30)|1(?:264|071)|2811): )?(?:(?:[Ff]ile|script|[Gg]ot) )<F-CONTENT>.+</F-CONTENT>$
failregex = ^(?:does not exist|not found or unable to stat): <script>\b
            ^'<script>\S*' not found or unable to stat
            ^error '[Pp]rimary script unknown(?:\\n)?'
```

Both jails are being triggered from logs like the following as students are testing web pages and scripts. This gets annoying as then the `recidive` jail kicks in if this happens multiple times in a day. But I suppose the comments from the script do mention that false positives are possible. 
```
# This matches many types of scripts that don't exist. This could generate a
# lot of false positive matches in cases like wikis and forums where users
# no affiliated with the website can insert links to missing files/scripts into
# pages and cause non-malicious browsers of the site to trigger against this
# filter.
```

```
[Sun Jun 27 16:58:32.343853 2021] [core:info] [pid 848366:tid 848413] [client xx.xx.xx.xx:55135] AH00130: File does not exist: /home/ourusers/user1/public_html/cgi-bin/html.txt/symbols1207036.txt, referer: https://ourdomain.edu/~user1/index.htmlLAB6

/var/log/httpd/error_log-20210627:[Fri Jun 25 20:53:54.993410 2021] [core:info] [pid 1323104:tid 1323286] [client xx.xx.xx.xx:59706] AH00128: File does not exist: /home/ourusers/user2/public_html/cgi-bin/exchanges214609.txt, referer: https://oudomain.edu/~user2/index.htmlLAB6

/var/log/httpd/error_log-20210627:[Thu Jun 24 21:56:37.719781 2021] [core:info] [pid 1323103:tid 1323303] [client xx.xx.xx.xx:50676] AH00128: File does not exist: /home/ourusers/user3/public_html/cgi-bin/exchanges3875252.txt, referer: https://ourdomain.edu/~user3/index.htmlLAB06
```

Are these jails meant to be kept separate? Is there a way to work around the FPs?

**Comment by sebres** [comment]
> Is this description still accurate? 

Huh? what exactly is not "accurate" here?

> Isn't this regex overlapping in apache-noscript.conf

No. Do you see `/~` in `.*/~.*` ?

> What are "non scripted websites"?

Obviously they are sites without scripts (e. g. serving pure static pages for example). One can also supply custom parameter `script` to the filter in order to restrict extension or paths of some scripts unused for this site.

> This gets annoying as then the recidive jail kicks in if this happens multiple times in a day. But I suppose the comments from the script do mention that false positives are possible.

Isn't it really apparent?

> Are these jails meant to be kept separate? 

All these apache jails (and filters) are kept for backwards compatibility (so consider this more as an illustration)... 
Neither I like this filters, nor I find that this is a good way (by default) to protect the website against script kiddies or scanner bots.
For instance using nginx one is able to push unexpected traffic (no matter which kind of) to some special location to log in separate file, in order to reduce parasite traffic (in sense of fail2ban), as well as to minimize amount of false positives (at least one can be more precise by site configuration).
See [wiki/Best-practice#reduce-parasitic-log-traffic](https://github.com/fail2ban/fail2ban/wiki/Best-practice#reduce-parasitic-log-traffic).

> Is there a way to work around the FPs?

Conditionally. Try to rewrite parameter `script` (or even the whole `prefregex`) as precise as possible. E. g. whitelist the directories or suffixes (enhancements) you don't want to ban... 
Or/and increase `maxretry` (or/and decrease `findtime`)...

Fix your pages (see the referrer URLs) which referencing this non-existing URLs, so avoid matching the filter.
