### ISSUE TITLE
[BR]: Potential command injection in fail2ban engine

### ISSUE THREAD

**Issue by sei-vsarvepalli** [fail2ban/fail2ban#3051]
This is mostly to address @kevinbackhouse blog on potential command injection that was published recently by Github Security Lab https://securitylab.github.com/research/Fail2exploit/ 

### Environment:

- Fail2Ban version  : Current master branch https://github.com/fail2ban/fail2ban/tree/master 
- OS, including release name/version : Ubuntu 20.04.2 LTS
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

The raw mode of IPAddr class does not normalize IP address sufficiently to avoid potential command injection
https://github.com/fail2ban/fail2ban/blob/eea1881b734b73599a21df2bfbe58b11f78d0a46/fail2ban/server/filter.py#L929-L937 
#### Steps to reproduce
`
from fail2ban.server import ipdns
ipdns.IPAddr('`/bin/cat/etc/passwd`',ipdns.IPAddr.CIDR_RAW)
`
Provides a potential way to inject commands into fail2ban Filter.performBan routine https://github.com/fail2ban/fail2ban/blob/eea1881b734b73599a21df2bfbe58b11f78d0a46/fail2ban/server/filter.py#L443 

#### Expected behavior
Throw ValueError: Invalid IP address and CIDR raw value seen

#### Observed behavior
Returns `/bin/cat/etc/passwd` as the string value of IPAddr class

#### Any additional information
Potential simple fix can be to add validation for either hostname or IP CIDR that 
https://github.com/fail2ban/fail2ban/blob/master/fail2ban/server/ipdns.py#L354-L355 
```
			if re.search('[^a-zA-Z0-9\-\:\.\/]',ipstr):
				raise ValueError("Invalid IP raw CIDR value seen")
```

**Comment by sebres** [comment]
Shortly: neither this is a "potential way to inject", nor this can provide any vulnerability or attack vector, moreover this is an intention (so to speak a feature).

TLDR, between a foreign user input and the IPAddr object (not to mention the resulting action invocation) is a very long long way which is full of many barriers, starting with failregex and ending with proper escape by substitution of the resulting action command.

1. fail2ban can ban not the IPs only, but any kind of identifier of the potential intruder in sense of IDS/IPS (user name, session-ID, e-mail, whatever else), see RFE #1459

2. the object (IPAddr) is used as an identifier and if it is intended to capture `/bin/cat /etc/passw` or any other "raw" string as an ID, it is absolutely correct this way. But to do this, it is necessary to use either special tags in `failregex` of the filter like `<F-ID>\S+ \S+</F-ID>` or set `usedns` to `raw`, because normally fail2ban would recognize the hosts, e. g. hostnames (if `usedns` is `true` or `warn`) or the IP addresses only.

3. although the raw string would be stored then in the ID member of the ticket, its usage in the command action is safe, because the foreign input will be escaped by the resulting interpolated commands, moreover it will be provided as an variable in the substituted command. So for instance the usage of following command action is pretty correct:
&nbsp;   `actionban = some-ban-engine --session-id "<f-id>"`
because it would then evaluate something like this:
&nbsp;   `f2bV_id=$0 ...; some-ban-engine --session-id "$f2bV_id"`
so even if value of `<f-id>` becomes something like `$(cat /etc/passw)` or any other injection attempt, for the action it is just a value of the variable, so to speak a string supplied as an argument to the shell script, nothing more.

4. there must be several other key prerequisites present to allow the "injection", but the conditions above are already enough.

5. and any direct invocations of fail2ban-API (like in your example `ipdns.IPAddr('/bin/cat /etc/passwd', ipdns.IPAddr.CIDR_RAW)`) do not and can not show any even potential vulnerability, because it makes simply no sense apart from the context, without the background or its usage details.
It's like to supply string `'/bin/cat /etc/passwd'` to some member or variable, which is never used in vulnerable context, e. g. just used as an identifier (for example used as text in some file solely).

With other words, you must make a real effort to introduce such a "potential way to inject" - from constructing of own regex with a tag or part that matching IDs like that inclusive whole regex that would be able to match whole line, up to direct evaluation of properly escaped variable (e. g. to force shell to interpolate the variable value as a conmmand), because usually it is not "executable" at all.

Therefore it is quasi absolute legitimate to use IPAddr (it could be even simple string object with the same conclusion) without any validation like in your suggestion.
Missing validation somewhere does not immediately mean it is vulnerable, sometimes it simply means it is not required at all (at least preventive).

And last but not least, if you're sure to have found a vulnerability or other security relevant bug, it would be much more correct to report it to the project members (for instance to fail2ban-vulnerabilities@lists.sourceforge.net), before you'd publicly disclose it, e. g. to let the hackers as few chances as possible to misuse it (because the knowledge of the vulnerability before it gets fixed can increase the risk of possible exploit). That means in order to perform so called coordinated disclosure process (CVD) please contact the members firstly in a non-public way.

**Comment by sebres** [comment]
As for @kevinbackhouse analyse regarding this inject, his assumption is not quite correct (or probably you did not understand it correctly).

But this looks a bit confusing to me:

> Whoa! My command injection attempt (`touch /etc/kevwozere`) has made it all the way to a call to subprocess.Popen.

Because this one:

> 
```
2021-06-16 12:41:49,473 fail2ban.utils          [193923]: ERROR   7f002fc09880 -- exec: ['f2bV_ip=$0 \niptables -w -I f2b-sshd 1 -s $f2bV_ip -j REJECT --reject-with icmp-port-unreachable', '`touch /etc/kevwozere`']
2021-06-16 12:41:49,474 fail2ban.utils          [193923]: ERROR   7f002fc09880 -- stderr: "Bad argument `/etc/kevwozere`'"
```
does not show that touch was executed. This error means that iptables action (which is basically an action for IPs only, but anyway) was called a command iptables with 1 extra (unexpected) argument - 2 arguments instead of 1 argument (because of missing quotes).
Here as diff to illustrate what is happened by interpolation of variable in the shell:
```diff
- f2bV_ip='`touch /etc/kevwozere`'
- iptables -w -I f2b-sshd 1 -s $f2bV_ip -j REJECT --reject-with icmp-port-unreachable
+ iptables -w -I f2b-sshd 1 -s '`touch' '/etc/kevwozere`' -j REJECT --reject-with icmp-port-unreachable
```
so that `iptables` obviously throws "Bad argument" error.

Sure one could add to `<ip>` the quotes:
```diff
- iptables ... -s <ip> ...
+ iptables ... -s "<ip>" ...
```
Just:
- the action like iptables are basically used for IPs only, which are as is generally known one word and don't need to be quoted;
- if someone would use custom regex to capture free formed IDs (e.g. with space in it), one would surely use (e. g. configure) other banning action as iptables and co;
- such a change would be not backwards compatible (e. g. for some reason, some iptables-action must intentionally gets the arguments from the log together with IPs), so I'd try to retain it as is, unless really needed (and I don't see it as a vulnerable at the moment).

And he also write below:

> The injection enables me to add arbitrary extra command line arguments to iptables

Although he was using tags `<F-ID>` instead of `<ADDR>` or `<HOST>` and supply the matched result to IP-based banning action, was already an issue. 
Not to mention, that helper tags `<F-IP4>` or `<F-IP6>` are never supposed to be used like this. If the regex expect some special handling to capture IP-group (and you are unable to describe the IP within correct regex), then use `<F-IP4/>` (or `<F-IP6/>`) tag, which would match only IPv4 (or IPv6) in its correct form.
The major issue is - the `failregex` is vulnerable:
- don't allow to capture any stuff you supply to the action (especially if it is not escape/quote it, e. g. expecting IPs);
- don't use catch-all's like `.*` and `.*?` and not anchored regex (what could match everything);
- if you use `<F-ID>...something...that...can...contain...spaces</F-ID>`, quote it (use `"<id>"`) in the action, if you need single argument.

**Comment by sei-vsarvepalli** [comment]
Hello @sebres 

Thank you for your time and detailed + clear explanation.  As the blog was already public I decided to create an open issue.  I am all about CVD, I just didn't want the blog to be sitting there without any real validation or input from the developers or owners of the repo. Just bring some transparent way to address what is raised as a concern but may never be seen as an "issue" in your Git repository and therefore never validated or addressed. 

BTW, Are you aware of security.md and GHSA ways to handle CVD.  We are curious to see if projects can benefit from such a coordinated disclosure using GitHub's platform.

https://docs.github.com/en/code-security/security-advisories/about-github-security-advisories 

Any input is appreciated.
Thanks!
Vijay
