### ISSUE TITLE
mysql-auth failregex missing common log (see #2611) 

### ISSUE THREAD

**Issue by AWSBarker** [fail2ban/fail2ban#3061]
I've been struggling to ban some persistent hits to my mariadb server. Similar to #2611 the issue seems to be a date or space in the log format that my regex skills cannot debug.

I actually have fail2ban version 0.9.6 running and didn't want a upgrade yet, so I tried editing mysql-auth.conf based on #2611 by a clean install on an Uubuntu 20.04 giving fail2ban version 0.11.1 but the enabled mysql-auth still doesn't capture the format below:-

```
$ fail2ban-regex "2021-07-18  0:48:22 1777148736 [Warning] Access denied for user" /etc/fail2ban/filter.d/mysqld-auth.conf 

Running tests
=============
Use   failregex filter file : mysqld-auth, basedir: /etc/fail2ban
Use      datepattern : Default Detectors
Use      single line : 2021-07-18  0:48:22 1777148736 [Warning] Access de...

Results
=======
Failregex: 0 total
Ignoreregex: 0 total
Date template hits:
|- [# of hits] date format
|  [1] {^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
`-
Lines: 1 lines, 0 ignored, 0 matched, 1 missed
[processed in 0.00 sec]
|- Missed line(s):
|  2021-07-18  0:48:22 1777148736 [Warning] Access denied for user
` 
```
When I look into the mysql-auth.conf I see the developers seem to use a different format: 

```
# DEV Notes:
#
# Technically __prefix_line can equate to an empty string hence it can support
# syslog and non-syslog at once.
# Example:
# 130322 11:26:54 [Warning] Access denied for user 'root'@'127.0.0.1' (using password:
```

My regex understand isn't good enough to debug any further so could somebody guide me on a possible solution? 

It seems even if I upgrade to V0.11.1 I will still face the same issue.

**Comment by AWSBarker** [comment]
well no feedback after a couple of weeks, any suggestions at all?

**Comment by sebres** [comment]
Your sample message does not contain the HOST/IP (is it truncated?):
> 2021-07-18  0:48:22 1777148736 [Warning] Access denied for user

So what exactly is the message you need to match with the filter?

> It seems even if I upgrade to V0.11.1 I will still face the same issue.

If you take a look at the test cases:

https://github.com/fail2ban/fail2ban/blob/10cd81552538fa950cefc32787b9f82b5ee1b998/fail2ban/tests/files/logs/mysqld-auth#L20-L21

it shows that similar to your log-format message is matched with current filter.

**Comment by AWSBarker** [comment]
> Your sample message does not contain the HOST/IP (is it truncated?):

Yes I did truncate the message since I thought the issue was with the prefix of date/timestamp. The format should be like this:-

"2021-07-17 23:06:12 1776943936 [Warning] Access denied for user 'root'@'34.79.107.251' (using password: NO)"

But I have to use this custom regex to get it to detect this

`failregex = ^%(__prefix_line)s(?:(?:\d{6}|\d{4}-\d{2}-\d{2})\s?\d{1,2}:\d{2}:\d{2} )?(?:\d+ )?\[\w+\] (?:\[[^\]]+\] )*Access denied for user '[^']+'@'<HOST>' (to database '[^']*'|\(using password: (YES|NO)\))*\s*$
`
This seems to work now so I guess we can close this.
Many thanks
Andrew

**Comment by sebres** [comment]
This message is already matching by current filter, indeed. Thus close it for now.

**Comment by Perritu** [comment]
Just to clear this issue I had today.
MariaDB differs a little bit, so the standard regex didn't work for me.

The raw log line is
```
2021-11-27  2:44:06 [not-a-user] @  [10.10.200.95] ERROR 1045: Access denied for user 'not-a-user'@'10.10.200.95' (using password: YES) : (null)
```
My "custom" filter is this
```conf# Fail2Ban filter for unsuccesful MariaDB authentication attempts
#
# To log wrong access attempts create the file in /etc/mysql/mariadb.conf.d/50-errors.cnf and put
# this, then restart mariadb daemon.
# [mariadb]
# #plugin_load_add = sql_errlog
# sql_error_log_filename=/var/log/mysql/Mariadb.err
# sql_error_log_rotate=1
#
# This assumes you are using the default production environment.

[INCLUDES]

# Read common prefixes. If any customizations available -- read them from
# common.local
before = common.conf

[Definition]

_daemon = mysqld

failregex = ^%(__prefix_line)s(.)*Access denied for user '<F-USER>[^']+</F-USER>'@'<HOST>' (to database '[^']*'|\(using password: (YES|NO)\))*.*$

ignoreregex =

# DEV Notes:
#
# Basically, this qualifies as a "fork" from mysqld.conf file, but it's supposed to be destroyed
# once this patch is propertly integrated, so are not a true "fork".
#
# Authors: Artur Penttinen
#          Yaroslav O. Halchenko
#          Angel Garcia
```

Also, i put this in `/etc/fail2ban/jail.d/mariadb.conf`
```conf
[mariadb-auth]
enabled = true
port     = 3306
logpath  = /var/log/mysql/Mariadb.err
backend  = %(mysql_backend)s
```

All of this is to integrate F2B in my own environment, but it can be easy integrated with other environments, I suppose.

**Comment by sebres** [comment]
> `failregex = ^%(__prefix_line)s(.)*Access denied ...`

Don't do that... RE `(.)*` is a catch-all and therefore the whole expression is quasi unanchored, especially with `.*$` at end (so vulnerable and can be very slow).

More precise exact matching RE for your log-format can look like this:
```ini
failregex = ^\s*\[[^\]]+\]\s+@\s+\[<ADDR>\] ERROR \d+: Access denied for user '<F-USER>[^']+</F-USER>'
```
Or much shorter (if I correct understand that the user name is enclosed in first brackets):
```ini
failregex = ^\s*\[<F-USER>[^\]]+</F-USER>\]\s+@\s+\[<ADDR>\] ERROR \d+: Access denied
```

MariaDB (15.1-15.3) on few Debian boxes of me seems to log it to the systemd journal in original format (with `[Warning]` etc) without any special configuration in `mariadb.conf.d` and the stock [fail2ban filter](https://github.com/fail2ban/fail2ban/blob/a57643404c98fee74398cb175e7de1d3883a6f99/config/filter.d/mysqld-auth.conf#L20) is able to match it using:
```ini
[mariadb]
filter = mysqld-auth[_daemon=mariadbd, journalmatch='_SYSTEMD_UNIT=mariadb.service']
enabled = true
```

**Comment by Perritu** [comment]
I'm using `(.)*` 'cause i don't know the intentions of `%(__prefix_line)s`,  so I'm not removing it, thus my patch is not a 'best-practice', its only a patch so I can get f2b working in my specific environment. 

`.*$` is because **I think** it is necessary finishing with the line ending RE flag `$`.

Anyways, what Im doing is looking for the string `Access denied for user `, anything else are not relevant to me.

Finally, I go with
```conf
failregex = Access denied for user '<F-USER>[^']+</F-USER>'@'<ADDR>'
```
The reason is, even if the user and host is at the beginning, the spaces around the `@` mess things with regex-es.

Also, thanks for the tip about getting the logs from systemd journal ;)

**Comment by sebres** [comment]
> i don't know the intentions of `%(__prefix_line)s`

It depends on `common.conf` or its overrides provided for your distribution and on `logtype` parameters, etc.
The value how it gets interpolated can be found in verbose output, e. g. using `fail2ban-regex -v ...`.
Typically it'd match something like `hostname mariadbd[12345]: ` (or even nothing if it absents, because it is mostly optional).
And of course you could overwrite (or even remove) it, because it wouldn't match anything at your message format anyway. 
Let alone I don't think it advisable to use some "unknown" value, especially if you create a new filter.

> I'm not removing it, thus my patch is not a 'best-practice', its only a patch so I can get f2b working in my specific environment.

Unless someone else would consider your comment as a kind of how-to... Therefore I believe it is important to emphasize that **one should better don't use that**.

> Finally, I go with

As already said, it is vulnerable as well as can be very slow, especially if the log is wordy... Think what would happen if a lot of large messages arriving in same log or journal, where no match were there, so it'd need to scroll the whole line in hope to find `Access denied for user ...`, and that line by line.
Still worse it is has even not anchored prefix anymore, so the expression is completely unanchored now.
Not to mention if this log could get some messages with foreign user input (like statements or parts of them), so someone would be able to ban everyone just by generating of certain statement with data, matching by your "bad" RE.

**Comment by Perritu** [comment]
Then (just a question)... How about this one?
```
^\d{4}(\-\d\d?){2}\s+\d+(:\d+){2}\s+([^:]+): Access denied for user '<F-USER>[^']+</F-USER>'@'<ADDR>'( ?(\([^\)]+\)|:))*$
```

**Comment by sebres** [comment]
This wouldn't work, because fail2ban cuts the part with timestamp (matching datepattern) out before it starts to apply failregex (so you need `\d{4}(\-\d\d?){2}\s+\d+(:\d+){2}` only if timestamp logged twice, e. g. by syslog/journal and mariadb-logger).
Also `([^:]+)` may be a bit ambiguous, because it would not match if colon `:` can be found somewhere in prefix, probably not really in username, but it can be surely a part of IPv6 (in second brackets).
The end anchoring RE `( ?(\([^\)]+\)|:))*$` is also unneeded here, if you don't need something from there, the whole expression remains anchored at begin and you don't have catch-all similar handling within.

I already provided two variants working for your log-format... But if you need the address after the second `@` only (why?), you can rewrite it like here:
```ini
failregex = ^\s*\[[^\]]+\]\s*@\s*\S+ ERROR \d+: Access denied for user '<F-USER>[^']+</F-USER>'@'<ADDR>'
# or:
failregex = ^\s*(?:(?:\[[^\]]+\]|@)\s*){1,3}ERROR \d+: Access denied for user '<F-USER>[^']+</F-USER>'@'<ADDR>'
```
But really why, if they are obviously duplicates, just at first place they are logged directly (part of the log-format), but later they are just a part of the error message (so could change if message format gets changed later too).

Basically it is probably enough to have something like that (matching error-codes, without to consider error message at all):
```ini
failregex = ^\s*\[<F-USER>[^\]]+</F-USER>\]\s+@\s+\[<ADDR>\] ERROR (?:1045|1698)
```
