### ISSUE TITLE
[BR]: Changing logtarget in jail.local seems to have no effect

### ISSUE THREAD

**Issue by caponecicero** [fail2ban/fail2ban#3083]
### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

OS is FreeBSD 13.0.  Python is 3.8.11.  Fail2ban is  v0.11.2 

### The issue:

fail2ban.conf contains many warnings to not modify it.  However, fail2ban.conf is the only place that modifying 'logtarget' seems to have any effect.  Changing 'logtarget' in jail.local seems to have no effect.

v0.11.2 is the latest version from the FreeBSD ports collection.

**Comment by sebres** [comment]
*Seriously?! So the man-pages, documentation and wiki are not for you? Let's open an issue straight away*

> fail2ban.conf contains many warnings to not modify it. 

The same is valid for `jail.conf`... Therefore there are local-files (`fail2ban.local` and `jail.local`) for that reasons.

> However, fail2ban.conf is the only place that modifying 'logtarget' seems to have any effect.

Yes, because `jail.local` is for jail definitions.
Please set it in `fail2ban.local`, for example:
```ini
[Definition]
logtarget = SYSLOG
```
