### ISSUE TITLE
Question | Unban after restart

### ISSUE THREAD

**Issue by Keller18306** [fail2ban/fail2ban#3084]
Why is the list of bans cleared when restarting and reloading in fail2ban-client? How can I disable this?

**Comment by sebres** [comment]
> Why is the list of bans cleared when restarting and reloading in fail2ban-client?

A restart is like a stop + start, when fail2ban stops it resets everything to leave behind a clean and tidy state (as would be that fail2ban has been not started).
Especially it is important If during restart something action-related is changed (like ports, protocols, or even whole action), so fail2ban will flush (unban) old state and reban with new state (e. g. using other banning actions/parameters).
Also there can be some time between stop and restart, so some banned tickets may be outdated (and will not be banned).

For other needs there is `?sudo? fail2ban-client reload` one can use instead of restart - `reload` does not restart fail2ban process so doesn't unban active tickets, just updates current configuration (e. g. `failregex` etc).

> How can I disable this?

One cannot disable this. 
There are several possibilities to workaround this, e. g. one could either write custom action or supply `actionflush` and `norestored` to the action, where `actionflush` does nothing and due to `norestored=1`, `actionban` would ignore restored tickets by start, see #3038 for example, so something like this:
```
banaction = %(known/banaction)s[norestored=1, actionflush=true]
```
Just note that the banned entries in chains would be no more under control of fail2ban after restart, so they will never be unbanned anymore (so one would need to unban them manually using `iptables`, `ipset`, `nft` whatever.
Although one could write complex actions ignoring duplicates (for IPs left behind by previous fail2ban process), so without `norestored` and with some extra check, ignoring IPs already available in chains by reban, but...

But I don't understand why it is necessary at all or else by which scenarios it is expected?
