### ISSUE TITLE
[BR]: comment error

### ISSUE THREAD

**Issue by skyer9** [fail2ban/fail2ban#3090]
### Environment:

```bash
sudo fail2ban-client -V
0.11.1

uname -a
Linux notebook 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### The issue:

add comment to end of line.

```bash
cat /etc/fail2ban/jail.local
[DEFAULT]
bantime = 1h
bantime.increment = true      # test
```

configuration is ignored.

```bash
sudo fail2ban-client -d
2021-08-23 22:06:30,354 fail2ban.configreader   [146863]: WARNING Wrong value for 'bantime.increment' in 'sshd'. Using default one: 'None'
......
```

**Comment by sebres** [comment]
> add comment to end of line.

Who said it is or must be possible?! Fail2ban uses python's ini-config files, see https://docs.python.org/2.7/library/configparser.html :

*Configuration files may include comments, prefixed by specific characters (`#` and `;`). Comments may appear on their own in an otherwise empty line, or may be entered in lines holding values or section names. In the latter case, they need to be preceded by a whitespace character to be recognized as a comment. (For backwards compatibility, only `;` starts an inline comment, while `#` does not.)*

Also note #226
