### ISSUE TITLE
How can I get a refund from Fail2Ban

### ISSUE THREAD

**Issue by paularenson** [fail2ban/fail2ban#3102]
I tried the free forum.  I tried to write to Freebies?  I tried three or 4 ways. I bought the bronze plan because I found that there was no way to install scripts and I was given the understanding that if I installed the bronze plan plug it would work out of the box.  No instructions.  This is clearly only for coders.  I deed the plugin but am I out the one year subscription????  I left comments on the free bulletin board but nothing at all.   Very disappointed.  Thanks

**Comment by istiak101** [comment]
And from where did you buy this said "1 Year Bronze Fail2ban subscription"? @paularenson

**Comment by sebres** [comment]
I don't really understand your query.
Fail2ban is an open source software, moreover it is a free software. We don't sell anything, neither the "product", nor the support, simply nothing.
Basically if you purchased something somewhere, you must request for a refund there where you did it. But surely do not from fail2ban members or open source community!

Also note our disclaimer in the [readme](https://github.com/fail2ban/fail2ban#license) and the license:
*Fail2Ban is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.*

Since this is the developer repository, I'll close it as unrelated.
Don't hesitate to ask us if you have some technical issues.

**Comment by paularenson** [comment]
Thank you. I bought it from Fremius I think after being directed there from one if those fail2ban pages (all black background). Hard to read. I sent email to every fail2ban address i could find and their help forum and fremius. A link from fail2ban said this is the best place to get help. I understand freemius is selling on behalf of whoever made the plugin so they are getting my bronze fee. I wrote to freemius about how to get yhe documentation on what to set and how. No response. About 3 weeks. Obviously I am not getting through to whoever I should be. Thanks.

Ps. Someone said they are closing the thread. I hope it goes through. Thanks.

**Comment by paularenson** [comment]
Ok i found it. Fail2ban wordpress plugin. This is not you?

https://wp-fail2ban.com/features/

**Comment by sebres** [comment]
Well, I don't know who they are and what they or their plugin doing, sorry.

You could ask your lawyer which legal steps can be taken to obtain the expected bought service from them (or to cancel the subscription and return the fee). Here is wrong place for that.

Regarding the technical concerns, you could surely try to ask for help here (e. g. open a discussion), and you'd even obtain it for free. :) Just nobody here would be probably able to answer the questions about some foreign plugins.
Also note that fail2ban is something for sysadmins (near to what you described as "coders"), so don't expect you'd become an instruction like "click with mouse on that menu item", rather it would be command line stuff and configuration in form of ini-files.

For a start you could take a look in our [wiki](https://github.com/fail2ban/fail2ban/wiki).

**Comment by sebres** [comment]
As for the plugin (really no idea what it does, but to speak in general about plugins ...), you must understand certain prerequirements to be able use many of them:
1. very often a plugin is just some binding to fail2ban software (which should be available on the host or on some network access point), so...
2. you use a hosting where you can install or use fail2ban, or you have own server where you're able to install fail2ban
(mostly it'd expect root access to the server or some automation of hosting provider made for you in order to install and configure fail2ban).
If it is a simple web-hosting it would be probably impossible.
3. plugins must be compatible to your software, host configuration, fail2ban version etc pp
4. some additional steps (like jail configuration) may be needed after you install some of "plugins" (if it does only logging in certain format and doesn't create and configure a jail in fail2ban directly).

**Comment by paularenson** [comment]
Thanks for all your help.  And your offers to help/suggestions.  
First, as a non techie it took a while to figure out that others can use the name fail2ban and it is not limited to the original developers. Aplogies for bugging you guys.

So I retraced my steps.  Finally found some possible help.  To summarize:

1) This was the route I took to this plugin, mistakenly assuming it was the same human beings who created fail2ban.
https://wordpress.org/plugins/wp-fail2ban/ <https://wordpress.org/plugins/wp-fail2ban/>

With a link to invisnet <https://profiles.wordpress.org/invisnet/> / aka charles.lecklider.org <http://charles.lecklider.org/>

3) Support had moved from here
https://wordpress.org/support/plugin/wp-fail2ban/ <https://wordpress.org/support/plugin/wp-fail2ban/>
to here
 https://forums.invis.net/c/wp-fail2ban/ <https://forums.invis.net/c/wp-fail2ban/>

(I was put off by the back background but managed to leave a few unanswered messages. At age 669 it is hard to get used to things like black backgrounds.)

4) Somehow, I found the premium versions but can’t find them now. However, I just located my download page at Freemius.com <http://freemius.com/> and managed to get in a request for support. Finally they answered. Probably will ask for my money back as there is no documentation.

(Again, thanks for your offers of sharing knowledge, but because of problems with several conflicting security programs, I have moved from shared hosting to a vps managed by a friend with tight security at the pre Wordpress level he says.

By the way, I originally found a good review for them on Kinsta so wrote to them mentioning what I have said here.

Again, thanks again. Appreciate all your responses. 

paul






> On Sep 16, 2021, at 21:51, Sergey G. Brester ***@***.***> wrote:
> 
> 
> As for the plugin (really no idea what it does, but to speak in general about plugins ...), you must understand certain prerequirements to be able use many of them:
> 
> very often a plugin is just some binding to fail2ban software (which should be available on the host or on some network access point), so...
> you use a hosting where you can install or use fail2ban, or you have own server where you're able to install fail2ban
> (mostly it'd expect root access to the server or some automation of hosting provider made for you in order to install and configure fail2ban).
> If it is a simple web-hosting it would be probably impossible.
> plugins must be compatible to your software, host configuration, fail2ban version etc pp
> some additional steps (like jail configuration) may be needed after you install some of "plugins" (if it does only logging in certain format and doesn't create and configure a jail in fail2ban directly).

AND
