### ISSUE TITLE
[RFE]: systemd-journald way to limit journal size... custom filter matrix-synapse is slow

### ISSUE THREAD

**Issue by benneti** [fail2ban/fail2ban#3131]
#### Feature request type
Some journalctl entries might get very long, leading to increased cpu usage from fail2ban.
It would be convenient to have a way to tell systemd to only use X last lines or "--since=5h" or similar to not get problems in fail2ban.

#### Description
A particular case for me is synapse (matrix server) where I use the filter 
```
      [Init]
      maxlines = 5
      [INCLUDES]
      before = common.conf
      [Definition]
      _daemon = synapse
      # Part of regex definition (just used to make more easy to make the global regex)
      __synapse_start_line = %(__prefix_line)ssynapse\..+
      failregex = ^%(__synapse_start_line)s.*[POST\-(\d+)].*(Attempted to login as @.+:.+ but they do not exist|Failed password login for user @.+:.+).*<SKIPLINES>%(__synapse_start_line)s.*[post\-\1].*<HOST>.*$
      ignoreregex =
```
and 
```
        [matrix-synapse]
        enabled   = true
        filter   = matrix-synapse
        action   = iptables-multiport[name=HTTP, port="http,https"]
        journalmatch = _SYSTEMD_UNIT=matrix-synapse.service
```
the log has 315616 (`journalctl _SYSTEMD_UNIT=matrix-synapse.service | wc -l`) lines right now and grows very fast.
Without this jail fail2ban-server is at about 0.5%CPU in htop and with it at 25% (full thread of the CPU).

#### Considered alternatives
I am open to suggestions but I don't now. I thought about decreasing the global journal size but this seems like a bad solutions in case I want to have a peek at old logs...

**Comment by sebres** [comment]
> Some journalctl entries might get very long, leading to increased cpu usage from fail2ban.

How so?
1. Fail2ban by initial start of jail (first time ever) would scroll to `now - findtime` (default 10 minutes, what corresponds to `--since=10m`). In case of second start (e. g. after restart) it will scroll back to minimum between `findtime` and time of last log fail2ban previously processed (so if it was restarted 1 minute ago, it would start the scan process from 1 minute back).
2. It is recommended to set `journalmatch` in the filter or jail so the monitored journal entries would be additionally pre-filtered for the related service/unit/executable/command and it would drastically reduce the count of messages to process. For example: 
https://github.com/fail2ban/fail2ban/blob/1e8ce20b325e1a60c92025e0512fe0a547552293/config/filter.d/sshd.conf#L126

Note to us: see similar RFE #2529 (for `fail2ban-regex`).
