### ISSUE TITLE
[BR]: Hello, I seem to be able to detect failures but not actually block:/etc/fail2ban# fail2ban-client status sshd Status for the jail: sshd |- Filter |  |- Currently failed:	0 |  |- Total failed:	20 |  `- File list:	/var/log/auth.log `- Actions    |- Currently banned:	0    |- Total banned:	0    `- Banned IP list:	

### ISSUE THREAD

**Issue by gspeier** [fail2ban/fail2ban#3158]
### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment]
1. All reasons why it may happen are described in [the FAQ of our wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works). I guess in your case the `maxretry` or `findtime` are too large (or there are few failures as expected), or not all failures you want to detect can be found due to the settings of sshd or sshd jail (e. g. `mode = aggressive`).
2. The issue template is there not for nothing - you need to fill it as precise as possible (and don't write everything in a title line).
One can also change it later - click on `[...]` by first comment and then on `[Edit]`.
