### ISSUE TITLE
Possible to have a 403 error if nothing is on jail?

### ISSUE THREAD

**Issue by Barabba11** [fail2ban/fail2ban#3168]
I'm trying to figure out what is wrong here, I have a 403 on nginx, I would exclude I've set wrongly fail2ban, is it possible it locks access if in jail there is nothing?
There is any way to suspend for a while fail2ban? For example sudo systemctl restart fail2ban, if yes I've already tried it without results. Where can I have the problem?
Thanks for help

**Comment by sebres** [comment]
> is it possible it locks access if in jail there is nothing?

Normally it is not possible... But it may depend on the actions involved or the parameter one used in configuration.

But I don't think it is fail2ban. because 403 is basically a code nginx would generate in common case of prohibition, that takes place either in the nginx itself (e.g. `deny` or `return 403` directives), or behind the gateway (e.g. supplied from upstream). If nginx cannot connect to upstream you would rather get some 50x error.

> any way to suspend for a while fail2ban? For example sudo systemctl restart fail2ban.

Do you mean stop probably? Yes you can stop fail2ban or the single jail. See `fail2ban-client --help` for details.

This closed as incorrect and 3rd party issue.
If you mean fail2ban may be responsible for that, please provide the log except and the dump of net-filter listing (chains and rules) affecting the gateway ports.
