### ISSUE TITLE
Change permission fail2ban.sock

### ISSUE THREAD

**Issue by micheldutra** [fail2ban/fail2ban#3171]
Hello guys,

How can I change the permission to 777 of the fail2ban.sock file? It automatically generates after starting / restarting the fail2ban service.

I need to do a ban and unban control over the web interface for a client.
Server is running Centos 7.

Thank you all.

**Comment by sebres** [comment]
I would not do that (I mean `chmod 777`) - better would be to add the user of a web-service that must connect to fail2ban to some group and change owner group for the directory with fail2ban.sock.

Anyway you could:
1. change it after fail2ban started, in `ExecStartPost` (of systemd unit) or in init-script starting fail2ban.
2. or extend default permissions with `setfacl` for the directory (persistently or in `ExecStartPre`), 
3. or reconfigure fail2ban (parameter `-s` or `--socket` of starting command in unit/script or `socket` setting in `[Definition]` section of  `/etc/fail2ban/fail2ban.local` - for instance set another path to fail2ban socket to some persistent directory (e. g. `/opt/fail2ban` instead of `/run/fail2ban`) with appropriate permissions.

See also https://serverfault.com/a/1078787/488604 for similar Q.

**Comment by TLATER** [comment]
Could fail2ban not delete an existing socket so that we can configure this with systemd's socket creation support instead? Maybe bailing or recreating it only if it's set to `o+rwx` to work around misunderstandings of socket permissions?

Then any monitoring services that are also configured with systemd can be configured to correctly start *after* fail2ban's socket exists, as-is with `ExecStartPost` hacks there's a race condition.
