### ISSUE TITLE
botsearch filter ignoring commas

### ISSUE THREAD

**Issue by iosonogio** [fail2ban/fail2ban#3179]
The filter for apache botsearch ([botsearch-common.conf](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/botsearch-common.conf)) does have the following block expression.

```
[Init]
# Block is the actual non-found directories to block
block = \/?(<webmail>|<phpmyadmin>|<wordpress>|cgi-bin|mysqladmin)[^,]*
```
Disregarding the details of each `<...>` section, why are you ignoring lines containing a comma after those sections?
Example:

`https://example.com/cgi-bin/foo`  
versus
`https://example.com/cgi-bin/foo,bar`

Why not just using this regex instead?

```
block = \/?(<webmail>|<phpmyadmin>|<wordpress>|cgi-bin|mysqladmin).*
```

**Comment by sebres** [comment]
I have no idea why, but it got introduced this way at begin (18778d91749e7d9d6396706291f90a62b1f66c9f), just from scratch it was not there (7c09a61ca5efccacf1e505ef5297b87468950468).
I assume `[^,]*` is intended to stop by comma at the referrer (so at `, referrer: ...uri...`), so quasi supposed to "protect" against mixing with part of referrer URI.

In this case it may be enough to use word-boundary, so something like `\S*\b` instead of `[^,]*`, but it depends (e. g. whether the spaces logged unescaped) and thus may be a bit incompatible.

> Why not just using this regex instead?

Because `.*` is a catch-all, we're not allowing to use such constructs in our filters anymore (at least if it's not justified, and it isn't here).
Sure `[^,]*` is almost a catch-all too (excepting comma), but it was introduced 7 years ago, so it is retained now for backwards compatibility only.
My personal view - instead of "repair" the filter somehow, it would be better to remove them and create a how-to in the wiki instead.

And last but not least, I would not recommend at all to use such filters as is (too unprecise, too vulnerable against false positives, etc).

**Comment by iosonogio** [comment]
Hi thank you for your feedback, indeed I was (am) somewhat confused about how fail2ban interprets regexes.

Let me give some feedback here myself about using the catch-all. Based on further testing I've been doing this is how it seems to work:

```
[Definition]

failregex = (?i)^<HOST> .* "(HEAD|GET|POST) <block> HTTP/[012.]+" (404) .*$

ignoreregex =

[Init]

# CASE 1
# URI begins with one or more / (DO NOT write the ^ at the beginning of the regex)
# block = /+(<wip>).*

# CASE 2
# URI does not contain any further character than <wip> (DO NOT write the $ at the end of the regex) 
# block = /+(<wip>)

# CASE 3
# URI may contain <wip> anywhere
block = /+.*(<wip>).*

wip = api
```

On the basis of the above, I assume that using the catch-all `.*` is actually **needed** in CASES 1 and 3. And it may even be necessary at the beginning of the pattern when you want to match your pattern anywhere in the URI - CASE 3.

Anyway, I support your recommendation to get inspired but pre-built filters but build your own.

**Comment by sebres** [comment]
String `api` does not exists in URL without some context, so one mostly always knows how it appears in URI, so instead of a catch-all, no matter left and right, one can use correct more precise RE.
For instance the catch-all's in RE `/+.*(?:api).* ` could be replaced with `(?:[^/]+/)*` on the left and with `\b\S*` on the right.
```diff
- /+.*(?:api).*
+ /+(?:[^/]+/)*(?:api)\b\S*
```
As a result it would not match `/capitan` or even `/mapi` and `/apical` so would have fewer false positives from one side, but can still match `/xyz/api/test` or `/foo/api,bar` from other side (if it is expected at all). As well as it would not find string `api` somewhere in the injecting referrer, especially if it is created artificially by some URLs redirecting from. Moreover it would not even start such a unprecise search if can already stop by lot of legitimate messages (that is the main reason why expressions containing catch-alls are mostly very slow).
Anyway it is many times faster, much safer, more precise and fewer vulnerable expression.

A catch-alls or such similar expressions are only legitimate if no other possibilities are there at all. And I don't see it is really necessary here or could be somehow justified.

**Comment by iosonogio** [comment]
Hi Sergey, ok you definitively owned me :) Thank you much for pointing me to the right direction, I've been gaining a much better understanding, but still a lot to be improved on my side. 

This discussion now makes my original point superseeded.

I hopefully have improved my filters on your advices, but maybe I will follow up with a question on stackoverflow for further advice, not being a developing issue anymore.
 
Many thanks again.

**Comment by iosonogio** [comment]
Unless anyone is of different advice, personally I would consider this closed.
