### ISSUE TITLE
ssh aggressive-without-normal jail?

### ISSUE THREAD

**Issue by positron96** [fail2ban/fail2ban#3180]
Hi and thank you for awesome software!

I have a `normal` ssh jail to block ordinary "fast" login attempts, with maxretry=5, findtime=default, bantime=10min. However, there are bots that take 5 min delay between attempts (I assume they are only harmful when in swarms), their logs are caught by `ddos` regex, so I also enabled sshd[mode=aggressive] jail with maxretry=6, findtime=45min, bantime=1h to catch these attempts. This works fine; however, since this jail also has normal regexes, it also blocks normal attempts for 1h (as I understand it, after 5 attempts `sshd` jail blocks these attempts for 10 min, and after they get unbanned, on next attempt `sshd-aggressive` bans it for 1h), a behavior I'd like to avoid. 

Is it possible to restrict aggressive jail only to slow attempts? I'd think that I need some aggressive-without-normal filter, is this the correct way to go? Can it be done without creating a custom new filter file, by reusing `sshd.conf`?

I have fail2ban 0.11.2 from github releases deb, and debian-10-ish OS on raspberry pi.

**Comment by positron96** [comment]
I somehow attached a `bug` label and cannot remove it. This is not a bug.

**Comment by sebres** [comment]
> Can it be done without creating a custom new filter file, by reusing sshd.conf?

Well, conditionally it can...

You'd would supply `cmnfailre=""` parameter to the filter, you could suppress all the "normal", so it'd use only aggressive (ddos, extra etc) rules. 
```
[my-sshd]
filter = sshd[mode=aggressive, cmnfailre=""]
```

Just there are some helpers regexs that are used to recognize the IP of some session which would get removed too. For instance:
https://github.com/fail2ban/fail2ban/blob/095aeda8407b433098df35424cde2764a09566a6/fail2ban/tests/files/logs/sshd#L311-L316

will be recognized yet, because `Connection from` matching RE is provided in different block (`cfooterre`), so the IP address can be retrieved for this session and following failures are triggered with an IP.

But it can be another constellation where some `<F-NOFAIL>` helpers from `cmnfailre` block expecting, so after all it'd not match.

You can test it like `fail2ban-regex ... 'sshd[mode=aggressive, cmnfailre=""]'` to find out whether it would be good enough for your needs.

Also consider a new option `bantime.increment = true` (in version >= 0.11), which could probably help from other direction - you could set larger values `maxretry` and `findtime` and smaller initial `bantime` and if `bantime.increment` enabled for some jail or by default, it would ban faster (reducing maximal attempts count) and longer (increasing ban time) for recidive (known as "bad") offenders.
So you could probably simplify your configuration to few jails (or use default aggressive mode without accidental false positives).

**Comment by positron96** [comment]
These are great advices, and bantime increment seems like a great feature. I'll check this as soon as I can (I was stupid enough to  get locked out of my rpi which is located elsewhere). 
Anyway, I believe one of these advices will help me, so I'm closing this as resolved for now.
