### ISSUE TITLE
[BR]: fail2ban gone missing after reboot 

### ISSUE THREAD

**Issue by ReddotCleaner** [fail2ban/fail2ban#3181]
### Environment:

- Fail2Ban version 0.11.2 : 
- OS, unraid 6.9.2 : 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Like i said in the title, i install fail2ban(0.11.2) from source on unraid(6.9.2), it works well after i install it. It will ban ips that trying to hack my  server. BUT ervery time I reboot my server, fail2ban just went gone missing like i nerver installed it before.

#### Steps to reproduce
1.Install from source
2.reboot unraid 

#### Expected behavior
fail2ban gone missing

#### Observed behavior
fail2ban gone missing after reboot

#### Any additional information
Sadly I cant provide any log files since it just gone with wind without any trace. And I have no clue why this happen. Any help?

**Comment by sebres** [comment]
> fail2ban gone missing after reboot

What do you mean exactly?

Fail2ban installed from source just creates fail2ban modules in python, as well as few binaries (starter scripts) which simply calling python with corresponding fail2ban module.
What `setup.py` would not do - it doesn't install systemd unit or init script, so you have to create and setup them manually.

Please clarify what "missing" mean. 

1. there are no starter scripts `fail2ban-client` and `fail2ban-python`:
```
$ ?sudo? whereis fail2ban-client
fail2ban-client: /usr/local/bin/fail2ban-client
$ ?sudo? whereis fail2ban-python
fail2ban-python: /usr/local/bin/fail2ban-python
```
2. there are no fail2ban-modules:
```
$ ?sudo? fail2ban-python -c 'from fail2ban.version import version; print(version)'
0.11
$ python?3? -c 'from fail2ban.version import version; print(version)'
0.11
```
3. did you use any virtual env if you install fail2ban?

Closed for now, since it is almost impossible to predict what is "wrong" with your system without more data (and because it's basically 3rd party issue).

**Comment by ReddotCleaner** [comment]
Before reboot everything works fine. See below.
![微信图片_20211218095320](https://user-images.githubusercontent.com/34325738/146625220-7bc6dcb0-2f7b-44a0-8fad-b2b360114516.jpg)
and I did not using any vitual env. I diretly install it on my server.
And this is after reboot. Everything is gone.
![微信图片_20211218095328](https://user-images.githubusercontent.com/34325738/146625232-f630da76-ceb7-47e9-bd45-a82dfb0f23c6.jpg)
![微信图片_20211218095335](https://user-images.githubusercontent.com/34325738/146625233-4f47a774-067b-42d3-8b75-552a870ee103.png)
Since it was a 3rd party issue. i will try to figure it out. if something comes up, i will post here.

**Comment by sebres** [comment]
> and I did not using any vitual env

But is there something other (like containerization e. g. docker and co)...

Anyway since your `/usr/bin` is affected too, I can only imagine a non-persistent storage (e. g. /usr/ or parts of it mounted to some drive, expecting synchronization hereafter) or some kind of issues with the HDD/SSD.

Also see similar "unraid" related issues:
1. https://www.reddit.com/r/unRAID/comments/ahqo65/my_settings_reset_for_applications_after_reboot/
2. https://forums.unraid.net/topic/99464-settings-lost-after-reboot/
3. https://forums.unraid.net/topic/39193-restarted-unraid-and-lost-configuration/

You could also try to install fail2ban to other prefix than `/usr`, e. g. using `--prefix=` parameter.
