### ISSUE TITLE
[BR]: fail2ban sometimes doesn't work

### ISSUE THREAD

**Issue by BeardAndAxe** [fail2ban/fail2ban#3182]
### Environment:

- Fail2Ban version  : v0.10.2
- OS, including release name/version :  Ubuntu 18.04
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

fail2ban sometimes doesn't work. Almost every day it does not work at different times, sometimes it writes to the log and everything is ok, but then it stops working without any error messages. The process itself exists, but it does not write anything to the log. After some time (for example, 8 hours), he starts to write to the log again. 

#### Any additional information

Reads access log nginx. There are a lot of logs.
I used jail nginx-dos.

### Configuration, dump and another helpful excerpts

[nginx-dos]
enabled = true
port = http,https
filter  = nginx-dos
logpath = /var/log/nginx/access.log
maxretry = 80
findtime = 60
bantime  = 1
banaction = dummy
ignoreip = {{ fail2ban_ignoreips }}

**Comment by sebres** [comment]
Your values of `maxretry` and `findtime` mean that a ban occur by 80 attempts with 1 minute, which is a lot, so may be it is just no such failures anymore (e. g. 79 found messages in a minute wouldn't cause a ban).
Another possible reason that you have simply too many messages within your access.log so that possibly not well or optimal regexs are unable to find the offenders fast enough (to capture 80 in 1 minute from every IP).

Furthermore your `bantime` is 1 second (so it unbans almost immediately) what together with the action `dummy` also wouldn't help to stop the flood.

Additionally if you use nginx, why as a DoS prevention you try to monitor access-log directly instead of using something like a combination `ngx_http_limit_req_module` + filter [nginx-limit-req](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/nginx-limit-req.conf)?

Anyway, it is hardly possible to help you without to know all the details (you did provide almost nothing), but there are many issues targeting similar circumstances, for instance #2911 or any referenced within #2402.

Also your fail2ban version (0.10.2) could be affected by #2660 (ultimately fixed with b43dc147b5177019a1dcb51de9833139e904cc21, released with 0.10.6 / 0.11.2).

And last but not least, please read [wiki :: Best practice](https://github.com/fail2ban/fail2ban/wiki/Best-practice), especially the part "Reduce parasitic log-traffic".

**Comment by BeardAndAxe** [comment]
This time is set on purpose, this is a test mode, just check it in monitoring for now.

As for ngx_http_limit_req_module, I just needed a solution without add-ons for nginx. I have my own filter configured that processes our specific log format. Worked correctly, but can't handle larger logs.

It looks like these links have a solution to my problem, I'll try the new version and let you know if it helped. Thanks!

**Comment by sebres** [comment]
> As for ngx_http_limit_req_module, I just needed a solution without add-ons for nginx. 

Isn't this module included by default in nginx packages by Ubuntu? (In Debian it is included within [nginx-full](https://packages.debian.org/buster/nginx-full) or [nginx-extras](https://packages.debian.org/buster/nginx-extras)).
Anyway `?sudo? nginx -V 2>&1 | tr ' ' '\n' | grep limit` can show whether it was included by the build so you can use it out-of-the-box. Otherwise 

> I have my own filter configured that processes our specific log format. Worked correctly, but can't handle larger logs.

One can surely optimize the log-format and `datepattern`, `failregex` (and/or `prefregex`), but even then it'll be many times slower than already "pre-filtered" output of limit_req. As for own log format, you can do the same from a location handling 503 response code (generated by limit-req), e. g. in `@limit503` by `error_page 503 @limit503` or by conditional logging (as illustrated in first example [here](https://github.com/fail2ban/fail2ban/wiki/Best-practice#reduce-parasitic-log-traffic))...

At least it is highly advisable to separate access-log's (e. g. legitimate and suspicious traffic into different files) as well as to reduce the amount of messages with any suitable method if it's somehow possible.

> It looks like these links have a solution to my problem

Do you mean #2660 (flood with `Found` but no `Ban`)? Then indeed newer versions shall help here. You could also try the 0.10.6 or 0.11.2 deb-packets from https://github.com/fail2ban/fail2ban/releases, they must be technically compatible to Ubuntu 18.04.

Just if I have to repel a dos-attack, I would anyway switch to limit-req processing and co. 
Lastly one has to reduce a system load by all available means, and your approach, on the contrary, may boost it.
