### ISSUE TITLE
Jail sshd is not a JournalFilter instance

### ISSUE THREAD

**Issue by V0RTX** [fail2ban/fail2ban#3186]
This is occuring in log file for some jails including recidive.
Done some searching, but can't find much about it.

**My question is**: _Is it a config issue?_  If so how do I fix it?

TIA

**Comment by sebres** [comment]
> Is it a config issue? 

No. It is just a notice (neither an error nor a warning)... it happens if `jornalmatch` provided by filter or jail, but the jail is monitoring log-files (not journal), so a backend is something other as `systemd`. And `jornalmatch` is basically set by many jails (must be actually set for every jail), just it is "active" only by `systemd` backend (if jail start to monitor journal).

> If so how do I fix it?

You can't "fix" it. 
But because I also don't think this info is really helpful, I'll remove it in further versions.
