### ISSUE TITLE
[BR]: Error starting action Jail('sshd')/iptables-multiport: 'Script error'

### ISSUE THREAD

**Issue by pobv** [fail2ban/fail2ban#3192]
### Environment:
debian 11, lxc-container

- Fail2Ban version 

```fail2ban-client  --version
Fail2Ban v0.11.2
```

- OS, including release name/version : 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

sshd ips are detected, but ips are not banned with the following in fail2ban.log. Same config works on bare metal and kvm.

#### Steps to reproduce
just install and start in an lxc container.

#### Expected behavior
it should ban

#### Observed behavior
it does not ban with a Script error

#### Any additional information
when trying to manually execute iptables with the command I think it uses, I get
```
iptables -w -I INPUT -p tcp -m multiport --dports ssh -j f2b-sshd
iptables v1.8.7 (nf_tables): Couldn't load match `multiport':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
```
but iptables was fully installed and a similar configuration works fine on a kvm machine
(and I cannot use kvm on that machine)

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
iptables -w -A f2b-sshd -j RETURN
iptables -w -I INPUT -p tcp -m multiport --dports ssh -j f2b-sshd
2021-12-25 16:36:18,924 fail2ban.utils          [673]: ERROR   7f0288033ea0 -- stderr: 'iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument'
2021-12-25 16:36:18,924 fail2ban.utils          [673]: ERROR   7f0288033ea0 -- stderr: ''
2021-12-25 16:36:18,924 fail2ban.utils          [673]: ERROR   7f0288033ea0 -- stderr: 'iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument'
2021-12-25 16:36:18,924 fail2ban.utils          [673]: ERROR   7f0288033ea0 -- stderr: ''
2021-12-25 16:36:18,924 fail2ban.utils          [673]: ERROR   7f0288033ea0 -- stderr: "iptables v1.8.7 (nf_tables): Couldn't load match `multiport':No such file or directory"
2021-12-25 16:36:18,924 fail2ban.utils          [673]: ERROR   7f0288033ea0 -- stderr: ''
2021-12-25 16:36:18,924 fail2ban.utils          [673]: ERROR   7f0288033ea0 -- stderr: "Try `iptables -h' or 'iptables --help' for more information."
2021-12-25 16:36:18,924 fail2ban.utils          [673]: ERROR   7f0288033ea0 -- returned 2
2021-12-25 16:36:18,925 fail2ban.actions        [673]: ERROR   Failed to execute ban jail 'sshd' action 'iptables-multiport' info 'ActionInfo({'ip': '221.131.165.56', 'family': 'inet4', 'fid': <function Actions.ActionInfo.<lambda> at 0x7f028954dc10>, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7f028954e310>})': Error starting action Jail('sshd')/iptables-multiport: 'Script error'
```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment]
> when trying to manually execute iptables with the command I think it uses, I get `Couldn't load match `multiport':No such file or directory`

So why you did open an issue in fail2ban, if it is obviously an issue of your machine (containerization)?
I guess lxc host simply not allow your container to load multiport kernel module.
1. either fix it on host side (if you can, allow to use multiport in hosts kernel).
2. or switch to iptables-action, like `iptables-allports`, so in default section of your jail.local:
```ini
[DEFAULT]
banaction = iptables-allports
banaction_allports = iptables-allports
```
3. or since it looks like net filtering is served by nf_tables, you can try action `nftables[type=multiport]` (or `nftables-multiport`).

> but iptables was fully installed and a similar configuration works fine on a kvm machine

LXC are the lightweight and portable OS based virtualization units which share the base operating system's kernel. 
KVM, on the other hand, is a full virtualization (so KVMs machines have its own kernel). This means that with KVM, they really have full access to all hardware-related functions.

**Comment by sebres** [comment]
Short explanation for the people landing here with the same error:

`iptables v1.8.7 (nf_tables)` means that native net-filter on this system is actually nftables, and iptables is just a proxying mockup, so to say a passthrough to an emulator that tries to represent the nftables rules in iptables manner, what may work but seems to have several bugs occasionally (and exactly this one in v1.8.7 too).
There is no way to get it working excepting to wait for the fix... or to switch to native `nftables` action instead of `iptables-*` actions. Or as described above to switch to allports type of action, etc...

Adding this to `jail.local` will switch to native nftables action and should fix most of the issues of emulating iptables:
```ini
[DEFAULT]
banaction = nftables[type=multiport]
banaction_allports = nftables[type=allports]
```
or for old fail2ban versions (below v. 0.10.2-2):
```ini
[DEFAULT]
banaction = nftables-multiport
banaction_allports = nftables-allports
```
Newest debians will already use this action by default, see d0d07285234871bad3dc0c359d0ec03365b6dddc.

Additionally it is many times faster than iptables-based actions (without ipset), see performance comparison below (ipt vs. nftset).
One can also replace iptables-ipset based actions, since nftables action uses own nft-sets to hold the list of IPs, which has almost the same performance than iptables-ipset and it is also linear (`O(n)` on throughput vs. set-size).

Performance analyze (click to original article):
<a href="https://developers.redhat.com/blog/2017/04/11/benchmarking-nftables#copy-code-10"><img src="https://developers.redhat.com/blog/wp-content/uploads/2017/04/addr_and_port.png"/>
