### ISSUE TITLE
[BR]: After MariaDB and python3 update fail2ban fails

### ISSUE THREAD

**Issue by seimei** [fail2ban/fail2ban#3193]
### Environment:

- Fail2Ban version  : 0.9.6-2
- OS, including release name/version : Debian 9.13 stretch
- [x ] Fail2Ban installed via OS/distribution mechanisms
- [x ] You have not applied any additional foreign patches to the codebase

### The issue:
After the MariaDB update from 10.3 to 10.6 and python3.5 to python3.9 I can't start the fail2ban service anymore. I get always the same error again. I tried a ton and nothing helped so far. I tried to purge all settings, install again over repo, install manually from git and nothing helped. Tried with never fail2ban version too. ISPConfig is running on the VM and worked fine since the installation.

#### MariaDB issue?
If I try to stop or start the service I get this error:
```
Failed to get properties: Unit name mariadb-extra@.socket is missing the instance name.
Failed to get properties: Unit name mariadb@.socket is missing the instance name.
```
I found just this [Jira](https://jira.mariadb.org/browse/MDEV-26461) ticket with the same issue but no solution.

#### Python3 issue?
If I try any fail2ban command like fail2ban-client I get this error:
```
Traceback (most recent call last):
  File "/usr/bin/fail2ban-client", line 37, in <module>
    from fail2ban.version import version
ModuleNotFoundError: No module named 'fail2ban'
```
The fail2ban log is empty. I would like to solve the issue and get the service to run asap. In worst case I will make a backup and install a fresh Debian 11. TIA

**Comment by sebres** [comment]
> ModuleNotFoundError: No module named 'fail2ban'

You have to reinstall fail2ban using python 3.9 (pythons 3.5 and 3.9 don't share the same modules, so there simply no fail2ban modules for 3.9 now).
For manual installation (in order you would be unable to do that using default packages from Debian), see [wiki :: How to install or upgrade fail2ban manually](https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually).
Anyway if the installation is completed, following must return successfully (with version you installing):
```
$ python3.9 -c 'from fail2ban.version import version; print(version)'
0.11
$ fail2ban-python -c 'from fail2ban.version import version; print(version)'
0.11
```

> Fail2Ban version : 0.9.6-2

This version is too old, but if I take a look at the [package](https://packages.debian.org/stretch/fail2ban), it shows python (and not python3) as required, so normally fail2ban 0.9 for Debian stretch is installing for python2 (2.7).
You seems to have some other installations (manually or some other repo's) which overwritten your default starter scripts (or having path conflicts - e. g. `/usr/bin` vs. `/bin` etc).
Check where `fail2ban-*` scripts are installed to (e. g. `whereis fail2ban-client`) and remove "duplicates" which referencing incorrect installed version. 
Also I guess `/usr/bin/fail2ban-client` targets wrong python version, see `cat /usr/bin/fail2ban-client | head -n 1`.
If the shebang is `#!/usr/bin/env python` or `#!/usr/bin/python` (and your `python --version` shows 3.x), try to change the shebang to `python2`, otherwise try to resolve conflicting bin-paths.

> Debian 9.13 stretch
>  In worst case I will make a backup and install a fresh Debian 11

Did you try to upgrade from stretch to bullseye?

**Comment by billouetaudrey** [comment]
root@raspberrypi:~# whereis fail2ban-client
fail2ban-client: /usr/bin/fail2ban-client /usr/share/man/man1/fail2ban-client.1.gz

root@raspberrypi:~# python3.9 -c 'from fail2ban.version import version; print(version)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'fail2ban'

root@raspberrypi:~# fail2ban-python -c 'from fail2ban.version import version; print(version)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'fail2ban'

root@raspberrypi:~# whereis fail2ban-client
fail2ban-client: /usr/bin/fail2ban-client /usr/share/man/man1/fail2ban-client.1.gz

root@raspberrypi:~# python3 -c 'from fail2ban.version import version; print(version)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'fail2ban'

root@raspberrypi:~# python2 -c 'from fail2ban.version import version; print(version)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named fail2ban.version

root@raspberrypi:~# python -c 'from fail2ban.version import version; print(version)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'fail2ban'

root@raspberrypi:~# whereis fail2ban
fail2ban: /etc/fail2ban /usr/share/man/man1/fail2ban.1.gz

root@raspberrypi:~# whereis fail2ban-client
fail2ban-client: /usr/bin/fail2ban-client /usr/share/man/man1/fail2ban-client.1.gz

root@raspberrypi:~# whereis fail2ban-server
fail2ban-server: /usr/bin/fail2ban-server /usr/share/man/man1/fail2ban-server.1.gz
