### ISSUE TITLE
[FR]: action fails to ban with HAProxy on a different machine

### ISSUE THREAD

**Issue by schklom** [fail2ban/fail2ban#3200]
### Environment:

- Fail2Ban version  : 0.11.2
- OS, including release name/version : Debian Bullseye

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : 
- Service, project or product name, including release name/version : Nextcloud stable
- Repository or URL (if known) : https://github.com/nextcloud/server
- Service type : File storage and sync
- Ports and protocols the service is listening : Port 80 in the dockerized Nextcloud and port 5080 on the machine, TCP

#### Log or journal information
Offending IP is correctly detected, the official [filter](https://docs.nextcloud.com/server/stable/admin_manual/installation/harden_server.html#setup-a-filter-and-a-jail-for-nextcloud) works well.

#### Any additional information
Action `iptables-allport` doesn't properly ban the IP. Ideally, `iptables-multiport` can be used instead, but neither work right now. Also ideally, this can be achieved on `crazymax/fail2ban`'s Docker image via the `DOCKER-USER` chain.

The problem is (I believe) that connections are thought of (by the `iptables` system?) as coming from HAProxy on my home router.

I don't really know how to use `iptables`, so I'm not sure how to fix this.

**Comment by sebres** [comment]
> Action iptables-allport doesn't properly ban the IP.  Ideally, iptables-multiport can be used instead, but neither work right now.

"doesn't properly ban" could mean everything starting from "nothing happens" up to "error in fail2ban.log by the ban".
What do you mean exactly?

> Also ideally, this can be achieved on crazymax/fail2ban's Docker image via the DOCKER-USER chain.

So why you open the issue here if it is docker related stuff?

> I don't really know how to use iptables, so I'm not sure how to fix this.

Then it may be the time to learn how to use it, or even to search in internet for some questions or to ask on [Server Fault](https://serverfault.com/) or other [SE site](https://stackexchange.com/sites#).

There are many actions which can be used instead of `iptables` (e. g. `nftables` etc), but only you know which is suitable for your needs or how the net-filter being organized on your system.

Because I see the HAProxy, I could guess that you may try to "wrong" IP address (e. g. IP of proxying machine instead of real IP of the intruder).
Because I see the docker, I could assume that your system may have some inappropriate rules executing in pre-filter **before fail2ban chains**, so either whitelisting it completely (like allow already established connections) or pushing them to docker container, etc.

Also note [FAQ in our wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) for other possible reasons.

**Comment by schklom** [comment]
Thanks for the very fast reply :)

> "doesn't properly ban" could mean everything starting from "nothing happens" up to "error in fail2ban.log by the ban".
What do you mean exactly?

My bad, I mean that the IP can still access the service despite the `iptables` rule.

> So why you open the issue here if it is docker related stuff?

Because I think it is the same problem. I mainly use f2b on Docker, but debugging feels easier on the bare machine.

> Then it may be the time to learn how to use it, or even to search in internet for some questions or to ask on Server Fault or other SE site.

Sure, I can try that.

> Fail2ban has many actions which can be used instead of iptables (e. g. nftables etc)

`nftables-allports` doesn't have any effect either, despite the f2b logs showing a ban.

> how the net-filter being organized on your system.

I haven't touched network related stuff on the machine since I reinstalled Debian, except disabling ipv6. Flushing rules doesn't help either (see below).

> Because I see the HAProxy, I could guess that you may try to "wrong" IP address

The IP is correctly detected, and banned, but the device can still access the server.

Following your advice, I have looked a little bit into how chains work, and figured out that the chain `f2b-nextcloud` registers and allows the connection. The number of packets logged in the `RETURN` rule of that chain increases correctly.

```diff
$ iptables -F

$ fail2ban-client set nextcloud banip <correct-IP>
1

// Before and after connection to Nextcloud from my phone for the first time
$ iptables -L -v
-Chain INPUT (policy ACCEPT 130 packets, 20234 bytes)
+Chain INPUT (policy ACCEPT 5259 packets, 3244K bytes)
 pkts bytes target     prot opt in     out     source               destination
-   41 10294 f2b-nextcloud  tcp  --  any    any     anywhere             anywhere
+ 1623 2825K f2b-nextcloud  tcp  --  any    any     anywhere             anywhere

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

-Chain OUTPUT (policy ACCEPT 145 packets, 142K bytes)
+Chain OUTPUT (policy ACCEPT 5463 packets, 6121K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain f2b-nextcloud (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 REJECT     all  --  any    any     <correct-IP>       anywhere             reject-with icmp-port-unreachable
-   41 10294 RETURN     all  --  any    any     anywhere             anywhere
+ 1623 2825K RETURN     all  --  any    any     anywhere             anywhere

... other empty chains
```

I still believe the system only registers the IP of the router instead of the real one. Any idea, or should I go ask on a specialized forum? \^\^

**Comment by sebres** [comment]
> I still believe the system only registers the IP of the router instead of the real one. 

This is my assumption too, therefore I wrote about "wrong IP" above.
The question is which IP is really used by incoming packets e.g. would you see in `netstat`?

Let me explain with this example: your test intruder device has IP 192.0.2.5, this is connected to the endpoint, let say 192.168.178.9 (which is logging 192.0.2.5 and causing ban in F2B also for 192.0.2.5) via router wit IP 192.168.178.1. In this case banning 192.0.2.5 via net-filter subsystem is useless, because the connection you really see on the host with fail2ban coming from 192.168.178.1 (and real connect behind the router/NAT is invisible here).

In this case to log IP after NAT (192.168.178.1 not 192.0.2.5) and ban it with netfilter-based action is bad idea, because being pretty senseless in case of router, in the end you would ban everything then.

So you have basically 2 possibilities only:
- either to write some action which could ban IP 192.0.2.5 on router side, so before it'd sends packets to the 192.168.178.9 (if your router supporting such functionality)
- or to ban 192.0.2.5 with other non net-filter based action, for example in HAProxy direct.
I don't know whether HAProxy has such functionality, but nginx has it, the proper action would be for example [nginx-block-map](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/nginx-block-map.conf).

Few other attempts to ban IP behind NAT, e.g. like [content based filter in iptables](https://stackoverflow.com/questions/67134322/how-can-we-block-x-fordward-for-header-ip-https-request-with-iptables) would assuredly fail too for many reasons, for example because it'd be too unprecise, error-prone or even completely impossible due to encryption (https).

So better don't even try it using net-filter behind the NAT, write an action rejecting them directly in proxy or on router side (before NAT).

**Comment by schklom** [comment]
Too bad, `netstat -atn` (I didn't know about this tool, thanks for the tip :) ) shows that the server receives packets from the router, and sends them to the device.

> So better don't even try it using net-filter behind the NAT, write an action rejecting them directly in proxy or on router side (before NAT).

I will do that on the PFSense router hosting HAProxy then, I don't want to have to run and learn nginx \^\^

My last question is the following, then I stop bothering you :P
The following bash script properly bans an IP on PFSense, but requires logging in SSH first, using a passphrase protected private key file. I found a way to specify the passphrase in a shell script directly, without leaving a trace.
```sh
cat > ./echo_passphrase << EOL
      echo my_passphrase
      EOL
      chmod 700 echo_passphrase
      export SSH_ASKPASS_REQUIRE="force"
      export SSH_ASKPASS="./echo_passphrase"
      ssh -i /root/pfsense root@pfsense.home easyrule block wan 1.2.3.4
      rm echo_passphrase
```

My attempt at an actionban (not succeeding though) is
```python
actionban = cat > ./echo_passphrase << EOL
            echo my_passphrase
            EOL
            chmod 700 echo_passphrase
            export SSH_ASKPASS_REQUIRE="force"
            export SSH_ASKPASS="./echo_passphrase"
            ssh -i /root/pfsense root@pfsense.home easyrule block wan <ip>
            rm echo_passphrase
```

Is this not the way to write a bash script in python?

**Comment by sebres** [comment]
> My attempt at an actionban (not succeeding though)

Again... what exactly "not succeeding" means? Error? Unable to connect via ssh? Whatever it is let the interlocutor (without the mindreading ability) know that, so one doesn't need to guess it.

> Is this not the way to write a bash script in python?

This is not directly python, rather it is pythons config + fail2bans own implementation of exec.
But it is normally the way. So I don't follow quite why it would not work in action if it works in the shell, excepting something going wrong in that case due to tty, different users or environment (note fail2ban is running as service).
Let alone I don't understand how it can work in shell/terminal, because if ssh is running from a terminal, SSH_ASKPASS is normally ignored.

Anyway you could try to use `ssh-agent` or `sshpass` instead...
So try something like this one (I don't known pfsense, so used [pf](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/pf.conf)-action as base here):
```ini
[INCLUDES]
before = pf.conf

[Definition]
## pfctl = pfctl -a f2b/<name>
## key without password:
#pfctl = ssh -i /path/to/key root@pfsense.home <known/pfctl>
## key with password:
pfctl = sshpass -p  my_passphrase ssh -i /root/pfsense root@pfsense.home <known/pfctl>
```

But instead of storing password in plain text in action or wherever, better and simpler would be to use passwordless private key (I guess you can extend routers `.ssh/.authorized_keys` with still one public key, see for example this [forum](https://forum.netgate.com/topic/25091/how-to-configure-ssh-authorized-key)).

**Comment by schklom** [comment]
> Let alone I don't understand how it can work in shell/terminal, because if ssh is running from a terminal, SSH_ASKPASS is normally ignored.

FYI, `SSH_ASKPASS_REQUIRE="force"` prevents it from being ignored.

It turns out I had copied a wrong version of the script, and the ssh key file name was slightly wrong.

Thank you so much for all the advice, it has been very helpful! Your project is awesome :)
