### ISSUE TITLE
Last banned IP?

### ISSUE THREAD

**Issue by kalleboy** [fail2ban/fail2ban#3201]
Is there any way to get the last banned IP address in a jail with a command like fail2ban-client? 

"fail2ban-client banned" returns all the banned IPs, however I'm look for the latest banned one. (For further process, analysis and hardware firewall needs)

Best.

**Comment by sebres** [comment]
No, there is no such command directly, despite it is not quite possible to get the last one (without to store it somewhere), because the list of banned tickets is not ordered dict (so it is mixing by hash buckets):
https://github.com/fail2ban/fail2ban/blob/095aeda8407b433098df35424cde2764a09566a6/fail2ban/server/banmanager.py#L54

One method right now would be to store the last one in some action, another - to parse it from fail2ban.log.
But since it is asynchronous, how you'd be sure that it is the last and not the next one?
Every jail can have more than 1 action, so proper way would be to execute some second action additionally to ban action with `<ip>`, which is the current address (so obviously deterministic the last IP in every call of action).
