### ISSUE TITLE
[BR]: AttributeError: 'SMTPAction' object has no attribute 'consistencyCheck' in smtp.py

### ISSUE THREAD

**Issue by cottonthread** [fail2ban/fail2ban#3214]
### Environment:
- Fail2Ban version 0.11.1 with UFW v0.36
- OS, including release name/version :` Ubuntu 20.04 LTS 5.11.0-1029-gcp #33~20.04.3-Ubuntu SMP Tue Jan 18 12:03:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- [x ] Fail2Ban installed via OS/distribution mechanisms
- [x ] You have not applied any additional foreign patches to the codebase

### The issue:

Since I have a docker container using port 25, I had to enable smtp.py to try to send the new bans. When this error occurs, the blocking process cannot be completed. Then you cannot pass banaction correctly to ufw. That's why in ufw you don't see any blocked IP, although in fail2ban-client status jail you do.

**Apparently the actions.py is not able to find the consistencyCheck attribute.**
Has anyone encountered this type of error? What should I do to fix it in this case?

#### Steps to reproduce
Wait for an ban with  jail.local >` action = smtp.py[host="remotehost:25", user="remoteuser", password="remotepasswd", sender="root@localhost", dest="someone@remotehost", matches="ipmatches"]`

#### Expected behavior
Communicate the ban via `action `and perform the `banaction`.

#### Observed behavior
Do not report the ban via `action` and do not perform `banaction`

### Configuration, dump and another helpful excerpts
jail.local >` action = smtp.py[host="remotehost:25", user="remoteuser", password="remotepasswd", sender="root@localhost", dest="someone@remotehost", matches="ipmatches"]`

#### Relevant parts of /var/log/fail2ban.log file:
```
CRITICAL Unhandled exception in Fail2Ban:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fail2ban/server/jailthread.py", line 69, in run_with_except_hook.
    run(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/fail2ban/server/actions.py", line 332, in run
    bancnt = Utils.wait_for(lambda: not self.active or self.__checkBan(), self.sleeptime)
  File "/usr/lib/python3/dist-packages/fail2ban/server/utils.py", line 320, in wait_for
    ret = cond()
  File "/usr/lib/python3/dist-packages/fail2ban/server/actions.py", line 332, in <lambda>
    bancnt = Utils.wait_for(lambda: not self.active or self.__checkBan(), self.sleeptime)
  File "/usr/lib/python3/dist-packages/fail2ban/server/actions.py", line 515, in __checkBan
    action.consistencyCheck()
AttributeError: 'SMTPAction' object has no attribute 'consistencyCheck'.
```

**Comment by sebres** [comment]
It is indeed a bug:
https://github.com/fail2ban/fail2ban/blob/35d73d975856d6a17534db68f4bffbb7d3c7c3a9/fail2ban/server/actions.py#L546
missing a validation `if hasattr(action, 'consistencyCheck'):` like here:
https://github.com/fail2ban/fail2ban/blob/35d73d975856d6a17534db68f4bffbb7d3c7c3a9/fail2ban/server/actions.py#L663

So you could fix it either with this:
```diff
							for action in self._actions.itervalues():
-								action.consistencyCheck()
+								if hasattr(action, 'consistencyCheck'):
+									action.consistencyCheck()
```
Or much simpler by adding empty method `consistencyCheck` to the pythonic action `SMTPAction`:
```diff
class SMTPAction(ActionBase):
...
+	def consistencyCheck(self, **kwargs):
+		return True
```

Bad news is - it can be an after effect, because the former occurs only if the IP is still able to connect after ban (and then there are many `already banned` in fail2ban.log), so something may be not quite correct with your banning action.

**Comment by cottonthread** [comment]
> It is indeed a bug:
> 
> https://github.com/fail2ban/fail2ban/blob/35d73d975856d6a17534db68f4bffbb7d3c7c3a9/fail2ban/server/actions.py#L546
> 
> 
> missing a validation `if hasattr(action, 'consistencyCheck'):` like here:
> https://github.com/fail2ban/fail2ban/blob/35d73d975856d6a17534db68f4bffbb7d3c7c3a9/fail2ban/server/actions.py#L663
> 
> So you could fix it either with this:
> 
> ```diff
> 							for action in self._actions.itervalues():
> -								action.consistencyCheck()
> +								if hasattr(action, 'consistencyCheck'):
> +									action.consistencyCheck()
> ```
> 
> Or much simpler by adding empty method `consistencyCheck` to the pythonic action `SMTPAction`:
> 
> ```diff
> class SMTPAction(ActionBase):
> ...
> +	def consistencyCheck(self, **kwargs):
> +		return True
> ```
> 
> Bad news is - it can be an after effect, because the former occurs only if the IP is still able to connect after ban (and then there are many `already banned` in fail2ban.log), so something may be not quite correct with your banning action.

Thank you very much for the quick response and the immediate solution. Sorry for my lack of knowledge about the inner workings of the program, but I imagine that the most appropriate would be as you say, to do a programming in the smtp.py file on consistencyCheck, right? In this case, could you please tell me where is the related code in case of NOT using smtp.py? I mean, like sendmail or mailx, I want that so I can try to help you to complete what smtp.py really lacks.

**Comment by sebres** [comment]
You're welcome.

> I imagine that the most appropriate would be as you say, to do a programming in the smtp.py file on consistencyCheck, right?

Well, not really, because there is almost nothing to check in this action. Consistency or invariant check (as well as restore of sane environment) may be needed in banning actions, for instance if something are flushed the chains/rules of iptables, such mechanism could restore the chains of fail2ban back. But this is a mail action, so it simply send the status like banned/unbanned, not to mention I don't really understand the necessity to do that per ticket (who may really need 1000 mails per jail everyday?)...

With other works smtp.py doesn't really lack something in this direction (consistency check). 
Either it lacks something like cumulative handling of tickets (e. g. sending some summary only once a day or some configurable period), although it may be better implemented directly on fail2ban side without an action at all.

Thus I'll close it as fixed now.
