### ISSUE TITLE
ip address issue

### ISSUE THREAD

**Issue by homelistt** [fail2ban/fail2ban#3219]
Hi i want to ask two questions: 
1- i am using fail2ban for my vps hosting in linode. And i am trying to do configurations. As far as i understand, With this command "ignoreip = 127.0.0.1/8 123.45.67.89 ", we can exclude some IPs from fail2ban rules. And guide is saying that "By default, this command does not ban the localhost." And i think it means our device that we log in to linode automatically excluded from fail2ban rules. So what is the point of adding IPs to this command then?
2-the ip address that i save in jail.local (in ignoreip of fail2ban) is different from the ip i am using now. Normally fail2ban is supposed to ban me but i can still connect my linode with ssh. So  it means fail2ban is not working? (i didnt finish all confugirations in this guide https://www.linode.com/docs/guides/using-fail2ban-to-secure-your-server-a-tutorial/ )

Thank you.

**Comment by sebres** [comment]
> So what is the point of adding IPs to this command then?

Matter of documentation I guess (like an example how one can add a subnet as well as more than 1 IP).
Anyway it is correct that since fail2ban 0.10 own addresses are excluded by `ignoreself` option which is on by default (but `ignoreself` means at the moment IPs which resolving hostname/localhost only).

> Normally fail2ban is supposed to ban me but i can still connect my linode with ssh.

Here is a lot of reasons why it may be - https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works
So you have to check:
- either "Fail2ban does not detect some authentication failures or ban doesn't occur" if you don't see `[sshd] Found ...` and `[sshd] Ban ...` in fail2ban.log.
- or "Ban takes place but does not work, the intruder is still able to connect and continues an attack" if `[sshd] Ban ...` is there for the IP you used for test, but IP still able to connect.

Often it is the issue of net-filter misconfiguration, e. g. some rules "conflicting" with fail2ban tables or chains, see https://github.com/fail2ban/fail2ban/issues/2545#issuecomment-543087971 and below for an example why it happens.
