### ISSUE TITLE
sshd filters/modes broken

### ISSUE THREAD

**Issue by grzegorz-janoszka** [fail2ban/fail2ban#3222]
When I set in jail.local in [ssh] section: mode = extra (or aggressive) then fail2ban still ignores the following lines in authlog:
```
sshd[458759]: Unable to negotiate with 165.232.112.163 port 47994: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 [preauth]
```
The command fail2ban-regex /var/log/auth.log /etc/fail2ban/filter.d/sshd.conf --print-all-missed confirms that such lines are missed.

There is a regexp to much similar logs in the default sshd filter, but obviously it is broken.

**Comment by sebres** [comment]
> When I set in jail.local in [ssh] section: mode = extra

Do you probably mean `sshd` section? There is no `ssh` section in stock jail-conf.

Current sshd-filter matching this without any issue in aggressive (or extra) mode.
```bash
$ msg='Feb 17 12:40:18 sshd[458759]: Unable to negotiate with 192.0.2.1 port 47994: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 [preauth]'
$ fail2ban-regex "$msg" 'sshd[mode=aggressive]'

Running tests
=============

Use   failregex filter file : sshd, basedir: /home/bcadmin/Projects/fail2ban.master/config/
Use   filter options : {'mode': 'aggressive'}
Use         maxlines : 1
Use      datepattern : {^LN-BEG} : Default Detectors
Use      single line :  Feb 17 12:40:18 sshd[458759]: Unable to negotiate ...
...
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```
I guess your log has a timestamp too like `Feb 17 12:40:18` I used above (or it reads from systemd journal), because only newest versions can handle messages without a timestamp.

Anyway last fix in this direction was - 159957ab883efc151a2dddf53197153ba41576c2 (released in 0.10.2 and 0.11.1) and this filter matches it without any issues also.

If your fail2ban version is older you can update the filter from [here](https://github.com/fail2ban/fail2ban/blob/0.11/config/filter.d/sshd.conf) for example, just ensure to replace `F-MLFGAINED` with `F-NOFAIL` if your version is older than 0.10.5 (introduced in 1c1d2cc435d6e8f1eb4a1b60c935a1385a82e295), otherwise it'd become incompatible.
For old v.0.9 you'd need to update the filter from [fail2ban/tests/config/filter.d/zzz-sshd-obsolete-multiline.conf](https://github.com/fail2ban/fail2ban/blob/8ac49b58582cfe82626307b5a8b0574a63499d95/fail2ban/tests/config/filter.d/zzz-sshd-obsolete-multiline.conf#L64), but better would be upgrade the fail2ban version.
