### ISSUE TITLE
[FR]: Univention Console Login - filter (<HOST>) issue with IP being in round brackets?

### ISSUE THREAD

**Issue by rholighaus** [fail2ban/fail2ban#3247]
### Environment:  

- Fail2Ban version  : 010.2
- OS, including release name/version : Debian 10 (buster)

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : 
- Service, project or product name, including release name/version : Univention Corporate Server
- Repository or URL (if known) : 
- Service type : 
- Ports and protocols the service is listening : 80,443

#### Log or journal information

- Log file name(s) : /var/log/univention/management-console-web-server.log

- Journal identifier or unit name : 

#### Any additional information

I have written a regex but there seems to be a problem with evaluation the <HOST> statement.

This is the line of the logfile I would like to match / detect:

`24.03.22 14:11:08.351  MAIN        ( PROCESS ) : CPAuth (192.168.1.10:44560) response message: The authentication has failed, please login again.`

When applying this regex in regex101.com, it matches:

` : CPAuth \(.*:\d+\) response message: The authentication has failed, please login again.$`

Now trying to add `<HOST>` and run it through fail2ban-regex:

`# fail2ban-regex '24.03.22 14:11:08.351  MAIN        ( PROCESS ) : CPAuth (192.168.1.10:44560) response message: The authentication has failed, please login again.' ' : CPAuth \(<HOST>:\d+\) response message: The authentication has failed, please login again.$'`

Result:

```
Running tests
=============

Use   failregex line :  : CPAuth \(<HOST>:\d+\) response message: The aut...
Use      single line : 24.03.22 14:11:08.351  MAIN        ( PROCESS ) : C...


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:

Lines: 1 lines, 0 ignored, 0 matched, 1 missed
[processed in 0.02 sec]

|- Missed line(s):
|  24.03.22 14:11:08.351  MAIN        ( PROCESS ) : CPAuth (192.168.1.10:44560) response message: The authentication has failed, please login again.
`-

```

Any idea of how the _failregex_ has to be constructed to catch the line and allow blocking of the corresponding IP?

#### failures in sense of fail2ban filter (fail2ban must match):

```
24.03.22 14:11:08.351  MAIN        ( PROCESS ) : CPAuth (192.168.1.10:44560) response message: The authentication has failed, please login again.
```

#### legitimate messages (fail2ban should not consider as failures):

```
```

**Comment by sebres** [comment]
It is not the regex which makes it impossible, but the missing `datepattern` that can match your timestamp format either (note no entries by `Date template hits`) - and fail2ban 0.10.2 did not allow matches without timestamps. 
Adding `-vv` parameters would show all default datepatterns fail2ban support (by all similar timestamps it expects four-digit year, and by two-digit years the format is a bit different too).

You have to specify an own `datepattern`, in case of `fail2ban-regex` with regex using `-d '^%d\.%m\.%y %H:%M:%S(?:\.%f)'` or in the filter (or jail) using:
```ini
datepattern = ^%%d\.%%m\.%%y %%H:%%M:%%S(?:\.%%f)
```
(note the dual `%%` here because fail2ban or rather python config-files expect that %-char will be escaped in this way)

BTW, also you could anchor the regex to begin of message (note the timestamp matching datepattern is cut from message out), what is a bit better here, as well as specify `<ADDR>` instead of `<HOST>` (if you don't expect hostnames here but only IP addresses):
```ini
failregex = ^\s*MAIN [^:]*: CPAuth \(<ADDR>:\d+\) response message: The authentication has failed
```

**Comment by rholighaus** [comment]
Thank you very much. Adding the datepattern was the trick!
