### ISSUE TITLE
[BR]: mumble-server/murmur: Simulate NOW in operation since found time has too large deviation

### ISSUE THREAD

**Issue by antonv6** [fail2ban/fail2ban#3248]
### Environment:

- Fail2Ban version  : 0.11.2-2
- OS, including release name/version : debian bullseye
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

After restarting mumble-server (aka murmurd) fail2ban complains that the deviation is too large (see log excerpt below).

#### Steps to reproduce

Install fail2ban and mumble-server, enable `murmur` jail, restart fail2ban, restart mumble-server.

#### Expected behavior

No warnings in fail2ban.log.

#### Observed behavior

fail2ban complains, probably because it can't find the timestamp in the log line.

#### Any additional information

I have a suspicion that it's a simple pattern matching issue: /etc/fail2ban/filter.d/murmur.conf has `__prefix_journal = (?:\S+\s+%(_daemon)s\[\d+\]:(?:\s+\<W\>[\d\-]+ [\d:]+.\d+)?)` and `datepattern = ^<W>{DATE}`, which means any other mumble-server log level (e.g. C or X, not W) won't match the fail2ban's line/timestamp expectations.

#### Relevant parts of /var/log/fail2ban.log file:

```
2022-03-27 10:16:30,993 fail2ban.filter         [22254]: WARNING [murmur] Simulate NOW in operation since found time has too large deviation None ~ 1648376190.9936266 +/- 60
2022-03-27 10:16:30,994 fail2ban.filter         [22254]: WARNING [murmur] Please check jail has possibly a timezone issue. Line with odd timestamp: <C>2022-03-27 10:16:30.964 Caught SIGTERM, exiting
```

#### Relevant lines from monitored log files:

```
<C>2022-03-27 10:16:30.964 Caught SIGTERM, exiting
<W>2022-03-27 10:16:30.964 Killing running servers
<W>2022-03-27 10:16:30.971 1 => Stopped
<W>2022-03-27 10:16:30.972 Shutting down
<X>2022-03-27 10:16:31.022 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2022-03-27 10:16:31.022 Initializing settings from /etc/mumble-server.ini (basepath /etc)
<W>2022-03-27 10:16:31.706 ServerDB: Opened SQLite database /var/lib/mumble-server/mumble-server.sqlite
<W>2022-03-27 10:16:31.709 ServerDB: Using SQLite's default rollback journal.
<W>2022-03-27 10:16:31.780 Murmur 1.3.4 (1.3.4-1) running on X11: Debian GNU/Linux 11 (bullseye): Booting servers
<W>2022-03-27 10:16:31.787 1 => Server listening on 0.0.0.0:64738
<W>2022-03-27 10:16:32.422 1 => Not registering server as public
```

**Comment by sebres** [comment]
> fail2ban complains, probably because it can't find the timestamp in the log line.

datepattern is only relevant for file-related backend, and is totally not interesting for systemd backend monitoring journal. And since you mentioned journal and `__prefix_journal` containing the part matching timestamp (fail2ban cuts it out if `datepattern` got applied), I assume it is systemd backend, isn't it?

If it is not the case, you can specify another datepattern matching timestamp of any line - `datepattern = ^<[A-Z]>{DATE}`.
However this is just a warning (once a day) and can be safely ignored if the timezone issue can be generally excluded.

Also note #2882 (and a "fix" for that - ebf5784b8cd4b7c52d0f328b780833b8594f5567).

**Comment by antonv6** [comment]
(I've tried email, but my response didn't make it here. Just saying, if at some point it will.)

> datepattern is only relevant for file-related backend, and is totally not interesting for systemd backend monitoring journal. And since you mentioned journal and __prefix_journal containing the part matching timestamp (fail2ban cuts it out if datepattern got applied), I assume it is systemd backend, isn't it?

No, /var/log/mumble-server/mumble-server.log is a plain text file. I only mentioned __prefix_journal because it has the same issue as datepattern, i.e. it only looks at messages with `W` mark.

> If it is not the case, you can specify another datepattern matching timestamp of any line - datepattern = ^<[A-Z]>{DATE}.
 
That's what I'm thinking as well. But I the pattern should be fixed for everyone, not just for me.

> However this is just a warning (once a day) and can be safely ignored if the timezone issue can be generally excluded.
 
Here's the funny part. I have `monit` set up to monitor various services on a server, and one of the blocks is
```
check file fail2ban_log with path /var/log/fail2ban.log
    if match "ERROR|WARNING" then alert
```
It's actually the default behavior, because this block is present in /etc/monit/monitrc.d/fail2ban that comes from fail2ban package in debian (that's right, it's distro-shipped). So when monit sends an alert, it's not easy to ignore it.

**Comment by sebres** [comment]
> ... __prefix_journal because it has the same issue as datepattern

No, it does not. Although it uses the same expression (because it may log additional timestamp like mentioned in https://github.com/fail2ban/fail2ban/issues/2043#issuecomment-364199123), but it'd be not affected by the issue (would simply not match anything excepting `<W>` if timestamp is logged at all).

> the pattern should be fixed for everyone, not just for me.

Well, it should not really - newer version of fail2ban doesn't warn and safely ignoring lines with different timestamp.
Anyway I don't see the warning neither with file- nor with journal-related backend.

**Comment by antonv6** [comment]
> newer version of fail2ban doesn't warn and safely ignoring lines with different timestamp
Good to hear. I hope this newer version gets released soon.

**Comment by dnlldl** [comment]
I'm having the same issue and don't understand what "implemented in newer version" means in this case since I'm already running the latest version which was released in 2020. Am I missing something? How do I run the newer version?

**Comment by dnlldl** [comment]
I'm having the same issue and don't understand what "implemented in newer version" means in this case since I'm already running the latest version which was released in 2020. Am I missing something? How do I run the newer version?

**Comment by sebres** [comment]
> How do I run the newer version?

https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually

"implemented in newer version" means that current version in our repo (no matter released or not yet) already have the fix or else the issue is not reproducible there.
I'm not responsible for maintenance of distribution and since this is developer repository, the issue is closed here.

**Comment by dnlldl** [comment]
Makes sense, I have the official package from OpenSUSE, I'll see if I can update manually from git without breaking anything, thank you!
