### ISSUE TITLE
[BR]: Bitwarden with Fail2ban not blocking IPs

### ISSUE THREAD

**Issue by jad-01** [fail2ban/fail2ban#3256]
I'm new to fail2ban and I'm currently trying to integrate with a self hosted version of bitwarden. Both instances are synced in terms of date and time as I read that is a possible issue. I've pointed the logpath to the access.log file for bitwarden with the filter to match it. However, the banning doesn't occur. I'm open to alternative solutions if this approach isn't feasible. I did try with the identity log as well but had no luck either.

-- jail.local 
```ini
[bitwarden]
enabled = true
filter = bitwarden
logpath = /opt/bitwarden/bwdata/logs/identity/nginx/access.log
maxretry = 2
bantime = 300
port = 80,443
```
-- /filter.d/bitwarden.conf
```ini
[Definition]
failregex = ^.*"(GET|POST).*identity/connect/token.*HTTP.*"<HOST>"$
ignoreregex =
```
-- /bwdata/logs/nginx/access.log
```
x.x.x.x - - [12/Apr/2022:11:56:45 +0000] "POST /identity/connect/token HTTP/2.0" 400 166 "https://x.x.x.x/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55" "-"
```
-- output for: fail2ban-client bitwarden
```
[root@localhost fail2ban]# fail2ban-client status bitwarden
Status for the jail: bitwarden
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- Journal matches:
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:
```

**Comment by sebres** [comment]
https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works

*the proper parameter `backend` (for example `auto` for log files or `systemd` for journal), proper path to the log files (parameter `logpath`) or proper journal control parameter `journalmatch` should be set for this jail.*

Shortly: you seem to have incorrect backend for that jail (e. g. your default backend is systemd due to status output `Journal matches`, so it monitoring journal).
Add this to the jail to monitor `logpath` instead:
```ini
[bitwarden]
backend = auto
```

Furthermore I don't think your regex is good (has many catch-all's and doesn't really anchored) and that it would match at all.
You can use something like this instead (but I don't know the corner case what exactly you'd need to match):
```
failregex = ^<ADDR>[^"]+"[A-Z]+\s+/identity/connect/token [^"]*" 400\b
```
Not to mention the common issue with access-log - see https://github.com/fail2ban/fail2ban/wiki/Best-practice#reduce-parasitic-log-traffic

**Comment by jad-01** [comment]
> 
Hey,
I applied your suggestion 'backend = auto' however upon restarting fail2ban I get the following shown below. As for the regex expression because of the nature of Bitwarden the Identity logs don't show me the actual addresses but in the nginx logs (access.log) it shows in the 'x.x.x.x' expression mentioned above. The idea was to catch the date, POST, 400 error for bad request and the address.

Apr 13 07:37:40 localhost.localdomain systemd[1]: Starting Fail2Ban Service...
Apr 13 07:37:40 localhost.localdomain systemd[1]: Started Fail2Ban Service.
Apr 13 07:37:40 localhost.localdomain fail2ban-server[4986]: 2022-04-13 07:37:40,934 fail2ban                [4986]: ERROR   Failed during configuration: Have not found any log file for bitwarden jail
Apr 13 07:37:40 localhost.localdomain fail2ban-server[4986]: 2022-04-13 07:37:40,937 fail2ban                [4986]: ERROR   Async configuration of server failed
Apr 13 07:37:40 localhost.localdomain systemd[1]: fail2ban.service: main process exited, code=exited, status=255/n/a
Apr 13 07:37:40 localhost.localdomain systemd[1]: Unit fail2ban.service entered failed state.
Apr 13 07:37:40 localhost.localdomain systemd[1]: fail2ban.service failed.

**Comment by sebres** [comment]
> Have not found any log file for bitwarden jail

The error is exactly as it says - there are no log files for specified `logpath` pattern found. Check for possible typos (permissions etc) and fix `logpath` and it would work.

> but in the nginx logs (access.log) it shows in the 'x.x.x.x' expression mentioned above.

Well, since it is nginx, you could create special location (serving 400 or whatever) logging failures into different log-file, so all the access-log entries would not cause extra traffic on fail2ban side. This is the suggestion in the "Best practice" link I provided above.

**Comment by jad-01** [comment]
> The error is exactly as it says - there are no log files for specified `logpath` pattern found. Check for possible typos (permissions etc) and fix `logpath` and it would work.
> I ensured that the log path is correct with all the right permissions, so i'm not sure what it could possibly be to be honest
> Well, since it is nginx, you could create special location (serving 400 or whatever) logging failures into different log-file, so all the access-log entries would not cause extra traffic on fail2ban side. This is the suggestion in the "Best practice" link I provided above.
> Yep, I'm still looking into this to see what the best approach would be. Unfortunately, there's little help online to integrate fail2ban  with Bitwarden and if there is, it's outdated.

**Comment by sebres** [comment]
> I ensured that the log path is correct with all the right permissions ...

SELinux? If so take a look at `/var/log/audit/audit.log` or in journal.
Probably you need to provide policies to read the logfile from fail2ban service (add it to related SELinux module or use something like audit2allow to update policy from log/journal).
There may be also `fail2ban_selinux` package on your system or take a look at https://serverfault.com/a/1036140/488604 for other variants.

If it is not, everything must work if your fail2ban is not in some container (docker/etc) and the path is correct (normally fail2ban service runs as root).

**Comment by jad-01** [comment]
> 
So disabled SELinux to see if that was the issue but still getting the same error and for fail2ban itself, it's not in a container and currently running as root.

Sorry to be pain but I'm really not sure what the issue could possibly be

**Comment by sebres** [comment]
> So disabled SELinux ...

rebooted or just `setenforce 0`? I'm unsure it'd work for services without reboot or some extra ping-pong.

> in terms of the jail.local and logpath it all seems to be correct at first glance.

```
?sudo? fail2ban-client -d | grep 'logpath'
```
would show you the logpaths in config-stream supplied to the server during (re)start or reload.
If it is correct path and such log exists (and accessible for user fail2ban is running), I'm at my wit's end, sorry.

**Comment by jad-01** [comment]
> > So disabled SELinux ...
> 
> rebooted or just `setenforce 0`? I'm unsure it'd work for services without reboot or some extra ping-pong.
I tried both but no luck unfortunately. 
> > in terms of the jail.local and logpath it all seems to be correct at first glance.
> 
> ```
> ?sudo? fail2ban-client -d | grep 'logpath'
> ```
> 
> would show you the logpaths in config-stream supplied to the server during (re)start or reload. If it is correct path and such log exists (and accessible for user fail2ban is running), I'm at my wit's end, sorry.

No worries, thank you for helping out the best you could. I'll close it for now and reopen if I find a fix.

**Comment by sebres** [comment]
> Just one more tweak if I could ask for your help in. Just needs some tweaking with the regex so that it does what I want it do. 

Does my above suggested regex not work as expected?
```bash
# test RE:
fail2ban-regex /correct/path/to/access.log '^<ADDR>[^"]+"[A-Z]+\s+/identity/connect/token [^"]*" 400\b'
# show tickets fail2ban would match:
fail2ban-regex -o row /correct/path/to/access.log '^<ADDR>[^"]+"[A-Z]+\s+/identity/connect/token [^"]*" 400\b'
```
To match every kind of "bad" request (regardless the URL) you could also try:
```ini
# match every error (excepting 401 for authentication, which needs to be processed separately, 
# to consider "handshakes" initiation, e. g. ignore empty user name):
failregex = ^<ADDR>[^"]+"[^"]*" (?!401)[45]\d\d\b
```

**Comment by jad-01** [comment]
It does work but bitwardens Nginx container doesn't return the clients true IP address. Which makes it hard for fail2ban to apply banning. So I'm just trying to find a way around that at the moment.
These are the commands I found but it's just implementing them now that is the issue. 

```proxy_set_header X-Forwarded-For $remote_addr
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;```

**Comment by sebres** [comment]
There are several ways to do that, for instance you can use [real IP module](https://serverfault.com/a/896163/488604), so the client's actual IP address will be considered the remote IP address, rather than your load balancer's IP address. Or you could just log `X-Forwarded-For` header instead of client's IP, e. g. you can configure your own log format (preferred to use in locations you need it only) or even replace main log-format:
```diff
- log_format main '$remote_addr - $remote_user ...
+ log_format main '$http_x_forwarded_for - $remote_user ...
```
So the fail2ban would find failures from "correct" IP, but...
The issue hereafter will be probably [the impossibility to ban it using default IP-based banactions](https://stackoverflow.com/a/67182014/7161854), because the request is basically arriving from another IP than you'll see and log (and then would ban).
The solution would be to use another custom action supplying the ban to the host side where the real IP gets proxying (and so connected), if it is basically under your control, or to use some special action like [nginx-block-map](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/nginx-block-map.conf) banning directly inside nginx by `X-Forwarded-For` header.

**Comment by jad-01** [comment]
Hi, sorry for the late reply I was away.

The Bitwarden container is a bit fiddley just because the majority of the configs get overwritten when updated. However, I'll do some further digging and see where I can apply the changes with your suggestion.
