### ISSUE TITLE
[BR]: mode=aggressive/ddos with ssh jail bans usage of ssh-keyscan

### ISSUE THREAD

**Issue by EugenMayer** [fail2ban/fail2ban#3259]
### Environment:

ubuntu 20.04

- Fail2Ban version  :  0.11.1-1
- OS, including release name/version : 
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

When using fail2ban for ssh, with `mode=aggressive` to block out authentication attempts with public keys, it is found that using
`ssh-keyscan -H <ssh-host>` already leads to a ban since this log is added

```
Apr 17 09:28:13 <redacted-hostname> sshd[8429]: Connection closed by <redacted-ip> port 38866 [preauth]
```

#### Steps to reproduce

Add this configuration for a ssh jail

```
[sshd]
enabled = true
port=22
maxretry = 3
findtime = 43200
bantime = 3600
# ddos leads to the same issue, normal/extra works but does not ban authentiction attempts with wrong ssh key
mode= aggressive
publickey= any
```

#### Expected behavior

One should not get banned for using `ssh-keyscan -H <ssh-host>`

#### Observed behavior

using `ssh-keyscan` 3 times leads to a ban

### Configuration, dump and another helpful excerpts

It's a complete stock fail2ban configuration with the above rule, nothing else.

**Comment by sebres** [comment]
> When using fail2ban for ssh, with `mode = aggressive` to block out authentication attempts with public keys ...

Mode `ddos` (and `aggressive` which includes `ddos`) is intended to recognize many kinds of "failures" inclusive port-scan etc - e. g. multiple attempts to connect without authentication will be considered as failure and after `maxretry` attempts it going banned.

It is not necessarelly intended to "block out authentication attempts with public keys".
For this purposes you need use newest filter with parameter `publickey`, https://github.com/fail2ban/fail2ban/blob/f81f85569d88da74d76f286b431dc54d0ae00748/config/filter.d/sshd.conf#L95-L104
which is `nofail` by default to avoid ban for users using multiple keys.
See my answer https://github.com/fail2ban/fail2ban/issues/2765#issuecomment-650058745 to similar question for details.

Although it is surely possible too with the modes `ddos` or `aggressive` to ban `Failed publickey`, but you could catch some false positives on certain circumstances (like in your case), so to avoid that you may need to increase `maxretry` (and/or decrease `findtime`).

> [sshd]
> `publickey= any`

You cannot specify filter parameter `publickey` in jail this way - it'll be not supplied to the filter at the moment (only `mode` gets supplied).
You need to write it as a filter parameter, e. g. in `jail.local`:
```ini
[sshd]
filter = %(known/filter)s[publickey=any]
```
or (fewer preferable) in `filter.d/sshd.local`:
```ini
[Definition]
publickey = any
```
Anyway you would not need `mode = aggressive` for `publickey = any`, because if correctly supplied to the filter it'll find any `Failed publickey` with `normal` mode too.

**Comment by EugenMayer** [comment]
Thank you @sebres for caring a lot about this issue, seems like similar come up quiet a lot, at least i'am not the only dummy.

Thank you for the hint with the publickey option - AFAIR as i understood this is yet no available in my version 0.11.1-1 - right?

Or does the variant `filter = %(known/filter)s[publickey=any]` work in 0.11.1 too? Thank you a lot for the very detailed answer

**Comment by EugenMayer** [comment]
i tried upgrading to https://github.com/fail2ban/fail2ban/releases/tag/0.11.2 with

I used 

```
[sshd]
enabled = true
port=22
maxretry = 3
findtime = 1200
bantime = 3600
mode = normal
filter = %(known/filter)s[publickey=any]
```

I suppose that was you were reffering.

Using that, `ssh-keyscan` is no longer banned, but neither are any failed `ssh server -i key` login attemps. `/var/log/auth.log` logs

```
Apr 24 07:26:54 <redacted-server-hostname> sshd[1253121]: Connection closed by authenticating user ubuntu <redacted-ip> port 46180 [preauth]
```

Is there something i miss?

**Comment by sebres** [comment]
> auth.log logs `... Connection closed by authenticating user ...`

Parameter `publickey=any` allows to find messages like `Failed publickey for ?invalid? user`.
If you don't have it in your log, no one setting can help you to find them :) excepting aggressive mode (which searching for different messages).

Probably the log-level of sshd is simply too low, see https://serverfault.com/a/477424/488604 for details:

Change the setting for `LogLevel` in `/etc/ssh/sshd_config` as:
```
LogLevel VERBOSE
```

If you still get troubles or there are some other messages only, please provide the excerpt **of whole session** (included all messages) for both commands, that should work and should be banned.

**Comment by EugenMayer** [comment]
@sebres using VERBOSE works, but i guess this is even more surprising to setup and will lead to more questions down the road.

Nevertheless, that works for me and you helped me a lot, thank you!

**Comment by sebres** [comment]
You are welcome.

> using VERBOSE works, but i guess this is even more surprising to setup and will lead to more questions down the road

Well, neither I have an idea why openssh' people don't log public key failed attempts by default (I guess probably because they consider key-auth procedure as "safe enough"), nor we have any voice or exert any influence on their decision-making. Moreover I could say that openssh is the project with probably the most-frequent changing logging format and behavior, at least this shows the history of sshd-filter and our issue tracker.

Anyway unless sshd would not be able to notify fail2ban about the failed attempts directly (fail2ban protocol has such a feature) or would not allow to do that via some configurable command (e. g. to set it up to `fail2ban-client set sshd attempt "$IP" "$message"`), the single possibility to consider a failure is and remains the monitoring of a log-file or journal, but we have a chance to find the failures only if they get logged at all.

**Comment by EugenMayer** [comment]
I get your POV entirely. IMHO i think the default "normal" which fail2ban includes is probably rather suprising to more then just me. 

I understand that brute-forceing a ssh-key is rather very hard and thus considered to be non practical to do at all - in the contrary passwords would be. 

But honestly, if that would eb the point, i would not need fail2ban for ssh - there is no password auth for sshd on any of my servers and this will not change. Still i would assume banning people which try to get their way into the servers makes sense to me. So i would have expected public-keys to be included by default, or at least with "extended".

But on the other side, i understand that you are out of options here - you can either parse logs or you get notified. And since for now the latter is not to be expected, the former heavily relies on the actual loggin format. I really ask myself if PAM could be used as a proxy here.

Anyway, i understand that this situation is stuck. Thank you for all your time elaborating and explaining the issue!

**Comment by sebres** [comment]
> if PAM could be used as a proxy here

Just by the way, PAM failures can be found with `pam-generic` filter too.
Although, I don't think ssh public key authentication is implemented via PAM actually and does not simply bypass the PAM auth-stack completely. But you could try `AuthorizedKeysCommand` or something similar to use PAM with key-auth.
