### ISSUE TITLE
[RFE]: port knock to get sending public ip unblocked?

### ISSUE THREAD

**Issue by mxmilkiib** [fail2ban/fail2ban#3278]
#### Feature request type
i keep getting locked out, sometimes have a dynamic ip, and a port knock method to unblock oneself would be handy 

#### Description
some interaction with knockd, or similar

or documentation for setting up such a situation

**Comment by sebres** [comment]
For `knockd` (or other kind of knocking e. g. over http), it is enough to specify `command` like (if I remember correctly it replaces `%IP%` with knocking IP):
```
fail2ban-client unban %IP%
```
or to unban for single jail only (sshd for example):
```
fail2ban-client set sshd unbanip %IP%
```
Also you can place special whitelisting rule of `knockd` before default fail2ban chain (`INPUT`) or configure fail2ban to put its rules to the fail2ban chain below the `INPUT` chain in order to bypass whitelisted by `knockd` IPs.

Alternatively one can use some special jail (with filter like #1112) which could unban the IP with special action invoking aforementioned commands or add some whitelisting rules to net-filter).

If someone would wish to provide the documentation, welcome to our [wiki](https://github.com/fail2ban/fail2ban/wiki).

> sometimes have a dynamic ip

Just by the way, if one have a dyndns it is possible to add the hostname to `ignoreip` in form of FQDN, so the IP will be ignored (note that certain latency by DNS and internal fail2ban caches may sometimes retard the assessment about IP switch for several minutes on fail2ban side).
