### ISSUE TITLE
[BR]: fail2ban-client status <jal> does not list all banned hosts

### ISSUE THREAD

**Issue by dbuteyn** [fail2ban/fail2ban#3300]
### Environment:

- Fail2Ban version: 0.11.1-10.el7
- OS, including release name/version : CentOS 7
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase

### The issue:

fail2ban-client status <jail> does not list all banned hosts when executed right after restarting fail2ban.

#### Steps to reproduce

1. Manually ban a few hosts.
2. systemctl restart fail2ban && while ! fail2ban-client status [jail]; do false; done

#### Expected behavior

Once fail2ban-client is able to connect, I would expect to see all banned hosts for the specified jail.

#### Observed behavior

fail2ban-client status <jail> shows zero or just one banned host.

**Comment by sebres** [comment]
Fail2ban restores banned tickets after restart asynchronously. This means that the active banned IPs will becomes banned bit by bit.
This behavior will probably change once bulk ban facility (e. g. #3088) gets implemented.

**Comment by sebres** [comment]
> restarting fail2ban results in the system being temporarily unprotected?

What does "unprotected" mean? Fail2ban's jail are immediately active and during the restore process they should ban new attempts as they arrive. The restore of previously banned IPs takes place as soon as possible, but I don't see why one must consider such "old" intruders as much worse as the currently attacking intruders. Vice versa I assume that the previously banned intruders don't start the attempts immediately on unban (the certain latency until they would notice the ability to connect again is surely more than expected and mostly the regular case).

And as already said, later if bulk banning gets implemented it'd be much faster.

Besides, how often you'd restart fail2ban (or the host)? Not to mention that there is also `reload` facility that can be used instead of `restart`, so it'd update a runtime configuration (excepting banning action related stuff) without temporary unbanning/rebanning the tickets. So if you need update filter/regex or enable new jail etc, just use `fail2ban-client reload` instead of `restart`.

**Comment by dbuteyn** [comment]
Well, depends on your definition of "old". In the case of #3088, there was a four hour window of opportunity. While my case is not that extreme, I suspect bans are probably not restored LIFO (newest first) but random or by IP. Suppose for whatever reason someone restarts fail2ban during some attack they're not aware of (a sin, I know), freshly banned hosts will (temporarily) have access once more.

You are right, performing a reload is probably the more efficient way to do things. Until #3088 lands however, I think is reasonable for fail2ban-client status <jail> to block until restore of the requested jail has completed. Or alternatively have some indication that the list of banned hosts is incomplete so that the caller knows to try again later. As it stands, the status command is providing false information which our end-users rightfully complain about and is the reason why I created this issue.
