### ISSUE TITLE
[RFE]: Disable start/stop mails

### ISSUE THREAD

**Issue by kroese** [fail2ban/fail2ban#3302]
#### **Feature request type**

When a jail is started/stopped it sends an mail, there should be a simple flag to disable this.

#### **Description**

As is clear from this topic ( https://serverfault.com/questions/257439/stop-fail2ban-stop-start-notifications ) it is extremely complicated to disable these notifications. It completely depends on your configuration what files you need to edit.

#### **Considered alternatives**

There is no alternative except for the steps in the topic above.

#### **Any additional information**

It would be so much easier to just have a simple flag for this.

**Comment by sebres** [comment]
> There is no alternative except for the steps in the topic above.

I don't think so. It is enough to reset `actionstart` and `actionstop`. And one could do that directly in jail.local for `[DEFAULT]` section (all jails):
```ini
[DEFAULT]
action_mw = %(known/action_mw)s[actionstart="", actionstop=""]
```
Or even for single jail where you'd set the action:
```diff
[jail]
- action = %(action_mw)s
+ action = %(action_mw)s[actionstart="", actionstop=""]
```
I'm not a friend of such actions at all (never understand the necessity to send mails after each ban), moreover I don't think that 2 additional messages by (start/stop) would change something in relation to hundreds or thousands bun/unban messages.

I think fail2ban should rather get another common mailing facility, sending a summary report once a day/hour/whatever.

**Comment by sebres** [comment]
> So normally they never get any mail, but as soon as their other protections fail, they want to be notified.

Thousands mails (by thousands banned tickets)?

> only the START mails seem disabled? Is there a logical explanation for that?

No... And it should not mail something by STOP too. 

Which STOP mail do you mean? Or rather the time point of it?
If it was at the restart time point, then sure it would still send one, because at that time the old configuration was valid yet (and actionstop was still set for that actions). The action runtime parameters with new configuration are valid only after restart, thus it should not send the STOP mail anymore (e. g. next time you'd stop fail2ban or the jail).

If it is still wrong, please provide an excerpt for some jail with actions related stuff from dump `fail2ban-client -d | grep "$jail"`
