### ISSUE TITLE
Need help with fail2ban regex for broken headers in nginx:

### ISSUE THREAD

**Issue by Helios-23** [fail2ban/fail2ban#3303]
ive been trying to make a f2b regex that matches broken header: errors in nginx but when i do i get stuck

the format of the messages is like so:
```
2022/06/07 11:02:13 [error] 21128#21128: *1220853 broken header: "??ꀗ?D?^?/
ܷ?(??2,?ʞ???2?8fE lbf??????p<O?N??㱿?t?{3??!?	??
?/5?
-" while reading PROXY protocol, client: 54.226.160.170, server: 0.0.0.0:443
2022/06/07 11:02:13 [error] 21131#21131: *1220857 broken header: "MIYB%?@?????R?G?F?X?Ԑ?>?R"98??32??ED5?/?A?" while reading PROXY protocol, client: 54.226.160.170, server: 0.0.0.0:443
2022/06/07 11:02:13 [error] 21128#21128: *1220854 broken header: "???
(???<R?????j??F??6???C???T????X???P???=?-\???I??I???/?0????/5K" while reading PROXY protocol, client: 54.226.160.170, server: 0.0.0.0:443
2022/06/07 11:02:13 [error] 21128#21128: *1220855 broken header: "??	?@O[ul??}?Z,?䈸??????l?v? ၛ???k???0T??(?bu???$ݘ??+?,?	?
K

" while reading PROXY protocol, client: 54.226.160.170, server: 0.0.0.0:443
```
my regex should be:
```
\[error\] .* broken header: "(garbage to match)"  while reading PROXY protocol, client: <HOST>
```
but i am unsure how to catch everything inside (garbage to match).

the binary data is sometimes a few characters, sometimes contains multiple lines with carriage returns, etc. the data itself is unimportant and the message always follows the format of the regex.

i Dont think theres a bug in fail2ban i just have absolutely no idea what to place between the " " that will catch or ignore whatever there so the regex can match the rest of the important bits.

Any help would be appreciated

**Comment by sebres** [comment]
> the binary data is sometimes a few characters, sometimes contains multiple lines with carriage returns, etc. 

Oops.
If it is really so (the data is written really unescaped to the log, it may be a bug, because can provide certain "vulnerability" in case of log analysis or error-log monitoring (since an artificially constructed foreign input may cause some mistaken action like a ban for legitimate IP/sessions etc) and must be surely fixed on nginx side (e. g. by escaping of NL-char with `\n` or using URL-encoding).

As for the possible filter, a multiline matching can be activated using `maxlines` > 1 and `(?ms)` inline flags in RE (MULTILINE + DOTALL), so it may look like that:
```ini
maxlines = 5
failregex = (?ms)^\s*\[error\] \d+#\d+: \*\d+ broken header: ".*?" while reading PROXY protocol, client: <ADDR>
```
But it is ugly - slow, unprecise, not to mention the abovementioned "vulni".

**Comment by sebres** [comment]
BTW... it looks indeed like it will be written unescaped at the moment:
https://github.com/sebres/nginx/blob/1b6e3dcf16afc941c6d82c941d965760779605b3/src/core/ngx_proxy_protocol.c#L142-L143

**Comment by sebres** [comment]
Just for the record - https://mailman.nginx.org/archives/list/nginx-devel@nginx.org/thread/66JDESDGT26N6HVCILNDBPFFKO4R2SZD/

**Comment by sebres** [comment]
Unfortunately my path or rather fix suggestion (with proper "escape") was not fully accepted, see https://mailman.nginx.org/pipermail/nginx-devel/2022-September/UMIHHT5S7HWKFBXIIHFCJZKNGBHZ63JZ.html
It was fixed in nginx in this way - https://github.com/nginx/nginx/commit/68119b43620c4da4ce0269a2f860a3df7c4dc0b5
Release for nginx versions >= 1.23.2
So there will be no NL/CR chars anymore in the output (so it cannot break the log layout, the message remains as single line), but the quote-char ist still allowed.

Thus the `maxlines` is not necessary now (it'd always remain single line), just the end anchor becomes important, and RE may look like:
```ini
failregex = ^\s*\[error\] \d+#\d+: \*\d+ broken header: "(?:[^"]*|.*?)" while reading PROXY protocol, client: <ADDR>, server: \S+\s*$
```
Note that both anchors (`^` and `$`) are required to avoid possible injection on foreign input by a match with non-greedy catch-all `.*?`.
