### ISSUE TITLE
[FR]: support BIND named log categories

### ISSUE THREAD

**Issue by miken32** [fail2ban/fail2ban#3388]
### Environment:

- Fail2Ban version  : 1.0.1-1.el9
- OS, including release name/version : AlmaLinux release 9.0

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : named-refused
- Service, project or product name, including release name/version : BIND
- Service type : DNS

#### Any additional information
BIND has the option to include a log message category with entries. If this feature is enabled, Fail2ban doesn't catch the lines. In the examples below, the category is `security`. AFAIK all matching lines should be covered by adding  `(?:(?:update-)?security:)?` to the existing regex, or simply `(?:[\w-]+:)?` to catch all possible categories.

#### failures in sense of fail2ban filter (fail2ban must match):

```
23-Oct-2022 02:06:39.201 security: info: client @0x7f4e446fd6e8 104.248.51.8#53 (cyberresilience.io): query (cache) 'cyberresilience.io/A/IN' denied
23-Oct-2022 03:35:40.882 security: error: client @0x7f4e45c07a48 164.92.66.237#55956 (radiusone.ca): zone transfer 'radiusone.ca/AXFR/IN' denied
```

Happy to submit a pull request if it will be helpful.

**Comment by sebres** [comment]
I'm fundamentally a friend of precise as possible expressions, so if I would be someone who enables categories, I'd extend the prefix to mandatory categories I want to match. Something like that in jail:
```ini
[named-refused]
filter = %(known/filter)s[__line_prefix=<known/__line_prefix>(?:update-)?security:\s+]
```
or even because the message seems not to have prefix at all (excepting the category now):
```ini
[named-refused]
filter = %(known/filter)s[__line_prefix=\s*(?:update-)?security:\s+]
```
This would make the search more precise and faster.

But I'll extend the filter as suggested optional for any possible word as category (and provide the RE parameters with `_category` and `_category_re` which can be set more precise).

Thx for your contribution.
