### ISSUE TITLE
[RFE]: Need help for defining action

### ISSUE THREAD

**Issue by ne20002** [fail2ban/fail2ban#3403]
I try to write an action that calls Crowdsec local API for banning an ip. I got it partially working but need help with adding some more info into the json for the call.
This is what I have so far:
```
# Crowdsec configuration file
#
# Action to report IP address to Crowdsec local API
#
# NOTE: These reports may include sensitive Info.
#
# IMPORTANT: This action relies on a credentials being added to the above action conf,
# and the appropriate categories set.
#
# Example, for ssh bruteforce (in section [sshd] of `jail.local`):
#   action = %(known/action)s
#            crowdsec[lapi_url="http://local-api:8080", machine_id="ReverseProxy", password="******"]
#

[Definition]
 
# bypass action for restored tickets
norestored = 1
 
# Option:  actionstart
# Notes.:  command executed on demand at the first ban (or at the start of Fail2Ban if actionstart_on_demand is set to false).
# Values:  CMD
#
actionstart =
 
# Option:  actionstop
# Notes.:  command executed at the stop of jail (or at the end of Fail2Ban)
# Values:  CMD
#
actionstop =
 
# Option:  actioncheck
# Notes.:  command executed once before each actionban command
# Values:  CMD
#
actioncheck =
 
# Option:  actionban
# Notes.:  command executed when banning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
#
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionban = WHOIS_RESPONSE=`whois <ip>`
            WHOIS_ASN=``
            WHOIS_ASNAME=``
            WHOIS_COUNTRY=`$WHOIS_RESPONSE =~ /^Country:\s*(.*)/m;`
            TIME=`date +"%%Y-%%m-%%d, %%H:%%M:%%S"`
            curl -H "Authorization: Bearer $(curl -s -X POST -H 'Content-Type: application/json' -d '{"machine_id": "ReverseProxy","password": "***********"}' http://cs-lapi:8014/v1/watchers/login | jq -r ".token")" -X POST http://cs-lapi:8014/v1/alerts -H 'Content-Type: application/json' -d '[
  {
    "scenario": "fail2ban/<name>",
    "scenario_hash": "",
    "scenario_version": "0.1",
    "message": "Ip <ip> performed illegal connection attempt at $TIME ",
    "events_count": 1,
    "start_at": "$TIME",
    "stop_at": "$TIME",
    "capacity": 0,
    "leakspeed": "0s",
    "simulated": true,
    "events": [
      {
        "timestamp": "$TIME",
        "meta": [
          {
            "key": "source_ip",
            "value": "<ip>"
          },
          {
            "key": "user-agent",
            "value": "<agent>"
          }
        ]
     }
    ],
    "remediation": true,
    "decisions": [
      {
        "origin": "fail2ban",
        "type": "ban",
        "scope": "Ip",
        "value": "<ip>",
        "duration": "<bantime>s",
        "scenario": "fail2ban/<name>"
      }
    ],
      "source": {
        "scope": "Ip",
        "value": "<ip>",
        "ip": "<ip>",
        "range": "",
        "as_number": "$WHOIS_ASN",
        "as_name": "$WHOIS_ASNAME",
        "cn": "$WHOIS_COUNTRY"
      }
    }
  ]'

 
# Option:  actionunban
# Notes.:  command executed when unbanning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionunban =
 
[Init]

```
This is working with adding ip, bantime and name into the JSON. But I can't get the additional info about ASN and country to be inserted correctly.

Any help welcome.

**Comment by sebres** [comment]
Fail2ban doesn't have the info at the moment, neither the ASN lookup, nor some kind of geo-info detection can take place in action.
Although there is a `cymru` flavor one can use it in `fail2ban-client status` to see the ASN or country, but no such tags for the action at the moment.
<details><summary>Here is everything what we support right now ...</summary>

https://github.com/fail2ban/fail2ban/blob/e1d3006b0330e9777705a7baafe3989d442ed120/fail2ban/server/actions.py#L374-L401
</details>

Either you would need to do it in the action by yourself, or it'd be some enhancement of fail2ban later.
For instance an RFE #1854, I plan to back-port some of my branches with IP-based Geolocation (and subnet) database support and an update possibility via callback (unfortunately persistently no time to fulfill it).

**Comment by ne20002** [comment]
> 
Hi
Sorry. I know. That's why I tried to retrieve the info within the action. But I can't get the scripting to correctly work with the replacing of the values.

**Comment by sebres** [comment]
Sure... 
The reason for that is - the interpolation of variables within single quoted string in shell simply wouldn't work...
The interpolation for fail2ban tags like `<ip>` works in single quoted string only because it is plane word without special chars (otherwise you'd see a variable name there).

Use double quoted string instead, just compare it in shell:
```bash
$ A=aaa B=bbb 
$ echo ' {"a": "$A", "b":"B"} '
 {"a": "$A", "b":"B"}
$ echo " {\"a\": \"$A\", \"b\":\"B\"} "
 {"a": "aaa", "b":"B"}
```
Or something like `printf`:
```bash
$ echo $(printf ' {"a": "%s", "b":"%s"} ' "$A" "$B")
{"a": "aaa", "b":"bbb"}
```
(note that `%` char needs to be escaped in config files as `%%`)

Another variant would be to construct JSON with some tool, something like `jq`, see for example https://stackoverflow.com/a/48470227.

**Comment by ne20002** [comment]
> Sure... The reason for that is - the interpolation of variables within single quoted string in shell simply wouldn't work... The interpolation for fail2ban tags like `<ip>` works in single quoted string only because it is plane word without special chars (otherwise you'd see a variable name there).
> 
> Use double quoted string instead, just compare it in shell:
> 
> ```shell
> $ A=aaa B=bbb 
> $ echo ' {"a": "$A", "b":"$B"} '
>  {"a": "$A", "b":"$B"}
> $ echo " {\"a\": \"$A\", \"b\":\"$B\"} "
>  {"a": "aaa", "b":"bbb"}
> ```
> 
> Or something like `printf`:
> 
> ```shell
> $ echo $(printf ' {"a": "%s", "b":"%s"} ' "$A" "$B")
> {"a": "aaa", "b":"bbb"}
> ```
> 
> (note that `%` char needs to be escaped in config files as `%%`)
 :)
Thank you. Give a try tomorrow.

**Comment by ne20002** [comment]
Hi @sebres 
I still have problems putting the info into the json. It works in a bash script, but not when used in fail2ban action.
Any idea?

```
actionban = WHOIS_RESULT=$(whois $1)
            WHOIS_COUNTRY=$(echo "$WHOIS_RESULT" | grep -a -i Country | tail -1 | sed -n -e 's/^.*[Cc]ountry:\s*//p')
            WHOIS_ASN=$(echo "$WHOIS_RESULT" | grep -a -i Origin | tail -1 | sed -n -e 's/^.*[Oo]rigin.*:\s*//p')
            WHOIS_ASNAME=$(echo "$WHOIS_RESULT" | grep -a OrgName | tail -1 | sed -n -e 's/^.*OrgName:\s*//p')
            TIME=$(date +"%%Y-%%m-%%d, %%H:%%M:%%S")
            JSON_STRING=$( jq -n --arg cn "$WHOIS_COUNTRY" --arg an "$WHOIS_ASN" --arg nm "$WHOIS_ASNAME" --arg ti "$TIME" '[{ "scenario": "fail2ban/<name>", "scenario_hash": "", "scenario_version": "0.1", "message": "Ip <ip> performed illegal connection attempt.", "events_count": 1, "start_at": $ti, "stop_at": $ti, "capacity": 0, "leakspeed": "0s", "simulated": true, "events": [ { "timestamp": $ti, "meta": [ { "key": "source_ip", "value": "<ip>" }, { "key": "user-agent", "value": "<agent>" } ] } ], "remediation": true, "decisions": [ { "origin": "fail2ban", "type": "ban", "scope": "Ip", "value": "<ip>", "duration": "<bantime>s", "scenario": "fail2ban/<name>" } ], "source": { "scope": "Ip", "value": "<ip>", "ip": "<ip>", "range": "", "as_number": $an, "as_name": $nm, "cn": $cn }}]')
            curl -H "Authorization: Bearer $(curl -s -X POST -H 'Content-Type: application/json' -d '{"machine_id": "ReverseProxy","password": "********"}' http://cs-lapi:8014/v1/watchers/login | jq -r ".token")" -X POST http://cs-lapi:8014/v1/alerts -H 'Content-Type: application/json' -d "$JSON_STRING"

```

**Comment by sebres** [comment]
> It works in a bash script, but not when used in fail2ban action.

"Doesn't work" can be everything... What exactly happens?
What I can can recognise at first glance is `$1` (you need surely replace it with `<ip>`):
```diff
- WHOIS_RESULT=$(whois $1)
+ WHOIS_RESULT=$(whois "<ip>")
```
Also you could use `<time>` instead of now (to get real time of ban), something like this:
```diff
- TIME=$(date +"%%Y-%%m-%%d, %%H:%%M:%%S")
+ TIME=$(LC_ALL=C date -d "@<time>" +"%%Y-%%m-%%d, %%H:%%M:%%S")
```
(`LC_ALL=C` is only for the case that locale vars are not set in env if it running as service)

Additionally note that `PATH` can also deviate from your shell (it depends on system and configuration), so `jq` need to be used fully-qualified (with its path).

And I would specify IP as variable too (e. g. supplied as `--arg ip "<ip>"` to jq), for example:
```diff
- JSON_STRING=$( jq -n --arg cn "$WHOIS_COUNTRY" --arg an "$WHOIS_ASN" --arg nm "$WHOIS_ASNAME" --arg ti "$TIME" '[{ "scenario": "fail2ban/<name>", "scenario_hash": "", "scenario_version": "0.1", "message": "Ip <ip> performed illegal connection attempt.", "events_count": 1, "start_at": $ti, "stop_at": $ti, "capacity": 0, "leakspeed": "0s", "simulated": true, "events": [ { "timestamp": $ti, "meta": [ { "key": "source_ip", "value": "<ip>" }, { "key": "user-agent", "value": "<agent>" } ] } ], "remediation": true, "decisions": [ { "origin": "fail2ban", "type": "ban", "scope": "Ip", "value": "<ip>", "duration": "<bantime>s", "scenario": "fail2ban/<name>" } ], "source": { "scope": "Ip", "value": "<ip>", "ip": "<ip>", "range": "", "as_number": $an, "as_name": $nm, "cn": $cn }}]')
+ JSON_STRING=$( jq -n --arg ip "<ip>" --arg cn "$WHOIS_COUNTRY" --arg an "$WHOIS_ASN" --arg nm "$WHOIS_ASNAME" --arg ti "$TIME" '[{ "scenario": "fail2ban/<name>", "scenario_hash": "", "scenario_version": "0.1", "message": "Ip $ip performed illegal connection attempt.", "events_count": 1, "start_at": $ti, "stop_at": $ti, "capacity": 0, "leakspeed": "0s", "simulated": true, "events": [ { "timestamp": $ti, "meta": [ { "key": "source_ip", "value": "$ip" }, { "key": "user-agent", "value": "<agent>" } ] } ], "remediation": true, "decisions": [ { "origin": "fail2ban", "type": "ban", "scope": "Ip", "value": "$ip", "duration": "<bantime>s", "scenario": "fail2ban/<name>" } ], "source": { "scope": "Ip", "value": "$ip", "ip": "$ip", "range": "", "as_number": $an, "as_name": $nm, "cn": $cn }}]')
```
As already said `<ip>` will be interpolated in single quoted string at the moment, but normally for consistency reasons all variable fail2ban tags must be better enclosed in double quotes (or without quotes if single word-token expected, for the case we'll change that logic with direct interpolation later.

> Is there a way to do debug output when performing the action?

In case of error you'd normally see the output in fail2ban.log, even with loglevel INFO (default).
So simplest way is to add some `echo`'s where you need it and `exit 1` at end of command (to generate an error if curl doesn't produce it).

But yes, there is also regular way - `fail2ban-client set loglevel DEBUG` or `fail2ban-client set loglevel HEAVYDEBUG` and then ban something manually (e. g. some IP from test-net like `192.0.2.111`).
You can also start fail2ban in foreground like `?sudo? fail2ban-server --logtarget=STDOUT --loglevel=HEAVYDEBUG -f` to see the output directly in shell's console (but again note that some env-vars may deviate if started as service).

**Comment by ne20002** [comment]
Hi @sebres 
Thank you. I'll do as suggested with the changes.

For the JSON template: is it best practice to put each step in a single line or is it possible to use multiple lines for the template (I believe it would be easier readable.

**Comment by sebres** [comment]
> is it best practice to put each step in a single line ...

It is not necessarily the best practice issue - rather something of personnel preferences.
Readability is surely great thing, but since JSON can be pretty simple re-formatted using some automatic tools it is not the main point.
However I'd prefer multiline template for the purpose of readability and better transparency and traceability of source code, especially versioned in SCM (the changes are better pursuable in diff, it'd have fewer conflicts in case of 3 way merge, etc).

> is it possible to use multiple lines for the template

Sure it is possible - strings are multiline in posix shell:
```bash
$ echo '1st
> 2nd
> 3rd'
1st
2nd
3rd
```

If you need minimalist result, you can also have multiline string that results in a single line JSON, just use [heredoc](https://en.wikipedia.org/wiki/Here_document) with backslash before every new-line for that (single-quoted strings don't interpolate backslash escape sequences).
