### ISSUE TITLE
[FR]: mosquitto mqtt broker

### ISSUE THREAD

**Issue by kri164** [fail2ban/fail2ban#3427]
Hello,

tryed to cook myself as below, but it is not working. So asking for help. Thanks

```
[Init]
maxlines = 2
[Definition]
failregex = .+ New connection from <HOST>:\d+ on port \d+.\n+ Client <unknown> disconnected, not authorised.
```

### Environment:

- Fail2Ban version : fail2ban-0.11.2-150400.2.4.noarch
- OS, including release name/version : linux openSUSE 15.4

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : 
- Service, project or product name, including release name/version : Eclipse Mosquitto, mosquitto-2.0.10
- Repository or URL (if known) : https://mosquitto.org/
- Service type : MQTT broker
- Ports and protocols the service is listening : 1883, 8883, 9001, 9883

#### Log or journal information

- Log file name(s) : 
/var/log/mosquitto/mosquitto.log

#### failures in sense of fail2ban filter (fail2ban must match):
```
Dec 06 13:23:49: New connection from 192.168.0.100:48732 on port 8883.
Dec 06 13:23:49: Client <unknown> disconnected, not authorised.
```

#### legitimate messages (fail2ban should not consider as failures):
```
Dec 06 13:33:50: New client connected from 192.168.0.111:45853 as Johnny (p2, c0, k900, u'johnny').
Dec 06 13:43:50: Client Johnny has exceeded timeout, disconnecting.
Dec 06 13:50:01: Client Rosamunde disconnected: Protocol error.
```

**Comment by sebres** [comment]
Well there is no unique ID (like connect-ID, session- or PID/TID) in the log lines which will unambiguous identify the connect / disconnect messages belonging to the same connection.
Just imagine the messages crossing like here:
```
00:00:00: New connection from 192.0.2.100:12345 on port 8883.
00:00:01: New connection from 192.0.2.200:23456 on port 8883.
00:00:02: Client ... disconnected, not authorised.
00:00:03: Client ... has exceeded timeout, disconnecting.
```
How do you want to know which connection is evil here (`192.0.2.100` is legitimate and `192.0.2.200` is unauthorized or vice versa)?
Additionally `maxlines = 2` can be too small, because if an evildoer will achieve somehow to retard the disconnect message (e. g. by later authentication or with some flood using more than 1 connection), you'd not be able to detect that at all.
But make it larger would simply enlarge the probability of false positive.

Unfortunately, in my opinion, it is not really possible to create proper filter for this kind of logging.
The logging format is simply poor for analysis.

FWIW, here is an example for multi-line log parsing using `maxlines` buffering that could work (but as already said **I would not use it**):
```ini
maxlines = 10
failregex = ^\s*: New connection from <ADDR>:\d+ [^\n]*<SKIPLINES>^\s*: Client \S+ disconnected, not authorised\.
```

Another (basically better but also unsuitable) variant would be newer multi-line parsing without lines buffering, but it would imply a usage of `<F-MLFID>` and so needs an unique ID. For more info and an example of such filter see https://github.com/fail2ban/fail2ban/issues/3419#issuecomment-1327375907. Just in is still less good approach for you, since your log example doesn't have such an ID at all and therefore has aforementioned issue with a confusion of legitimate and evil messages.

**Comment by kri164** [comment]
Thank you very much for explain. I will contact mosquitto developers with RFE.
