### ISSUE TITLE
run action with every matched log entry

### ISSUE THREAD

**Issue by xolom** [fail2ban/fail2ban#3437]
This is no actual issue or request, it's a question if something like that can be realized with fail2ban.

There is a ssh honeypot running on my server which logs every login attempt to a log file.
I use fail2ban to scan the log file and run custom actions on it to execute python scripts which inserts the login attempts to a database.

The jail looks like this
```INI
[ssh-honeypot]
enabled   = true
chain     = INPUT
logpath   = /remotelogs/ssh-honeypot.log
findtime  = 5
bantime   = 5
banaction =
maxretry  = 1
action    = ip2mysql[script="/shared/ip2mysql/ip2mysql.py", name=%(__name__)s]
            pw2mysql[script="/shared/pw2mysql/pw2mysql.py"]
```

For completeness here is the filter
```INI
[Definition]
failregex = ^\[.*\]\s<HOST>\s<F-USER>[^\s]+</F-USER>\s<F-PASSWORD>.*</F-PASSWORD>
ignoreregex = ^\[.*\] ssh-honeypot
```
and action
```INI
# pw2mysql.conf
[Definition]
actionban = python3 "<script>" "<ip>" "<F-USER>" "<F-PASSWORD>"
actionunban =

[Init]

```

```INI
# ip2mysql.conf
[Definition]
actionban = python3 "<script>" "<ip>" "<name>"
actionunban =

[Init]
```

What I now would like to achieve is to execute the `action` for every found log entry independent of `bantime`, which is not a usual use-case for fail2ban, but it would be a very neat functionality. Otherwise I need to implement a log observing script similar to what fail2ban already does.

**Comment by sebres** [comment]
Dup of #2304.

> I use fail2ban to scan the log file ...

FWIF, fail2ban can be also notified directly (syntax: `fail2ban-client set <jail> attempt <ip> [<failure-message1> ... <failure-messageN>]`)

> What I now would like to achieve is to execute the action for every found log entry independent of bantime ...

At the moment it is not really possible independently of bantime. See https://github.com/fail2ban/fail2ban/issues/2304#issuecomment-590276134 for possible workaround using `ignorecommand`
(you may also need to set `maxretry` as high as possible, so the ban would not take place, since you'd use `ignorecommand` instead of banning action).

Following configuration may be used as another workaround:
```ini
maxretry  = 1
bantime   = 1
```
This will execute ban action on every failure, BUT no more often than one time per second (because next near attempts get ignored, due to bantime).
