### ISSUE TITLE
[BR]: Error iptables restore when restart F2B

### ISSUE THREAD

**Issue by Jason-Linux** [fail2ban/fail2ban#3439]
Hi actually i have problem with fail2ban when i restart it.

I used Fail2ban Crowdsec and firewalld on RockyLinux 8.4

I have standalone configuration

#### Relevant parts of /var/log/fail2ban.log file:
```
firewalld[1345925]: ERROR: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore v1.8.4 (nf_tables): invalid port/service `1-65535' specified#012Error occurred at line: 2#012Try `iptables-restore -h' or 'iptables-restore --help' for more information.
firewalld[1345925]: ERROR: COMMAND_FAILED: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore v1.8.4 (nf_tables): invalid port/service `1-65535' specified#012Error occurred at line: 2#012Try `iptables-restore -h' or 'iptables-restore --help' for more information.
```

**Comment by sebres** [comment]
You seem to have some jail that uses multiport firewalld action without ports specified (by default range is `1-65535`.
Either you'd need to change the banning action to some allports action, for instance:
```ini
[some_jail]
...
banaction = firewallcmd-allports
# or another action:
# banaction = firewallcmd-ipset[actiontype=<allports>]
```
Or you'd need to specify port(s):
```ini
[some_jail]
...
port = 80,443
```
Since firewalld is just an interface around native net-filter, it depends on the backend (it uses on your system, e. g. iptables and nftables may have different format) which range syntax for port is allowed.
You could also try to set default for proper value (but it depends on which fail2ban version is used, see below):
```ini
[DEFAULT]
port = 0:65535
```
Also see #3047 and #2821. Conclusion is https://github.com/fail2ban/fail2ban/issues/3047#issuecomment-956125985
