### ISSUE TITLE
[BR]: Fail2Ban filter for apache bots regex bug

### ISSUE THREAD

**Issue by iulianwebdev** [fail2ban/fail2ban#3445]
There seems to be an issue with the regex on the bad-bots config for apache

This line right here

```failregex = ^<HOST> -.*"(GET|POST|HEAD).*HTTP.*"(?:%(badbots)s|%(badbotscustom)s)"$```
I made it work with the following addition, but not sure it is not too inclusive

```failregex = ^<HOST> -.*"(GET|POST|HEAD).*HTTP.*".*(?:%(badbots)s|%(badbotscustom)s)"$```

This is due to how the log formats vary in different apache2 versions by default. Mine has status code and some other stuff like bytes after the ```HTTP.*"``` part.

Hope this is clear enough.

### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment]
> not sure it is not too inclusive

Probably, it is. Let alone also original regex is not good for my taste (several catch-alls, etc).
By and large, it is too error prone.

> Hope this is clear enough.

No it is not. You did not provide an excerpt from log with messages that must be matched, however our issue template says that it is mandatory (basically one'd use filter request instead of bug report).
Thus closed unless more info provided.

**Comment by iulianwebdev** [comment]
Sorry for late reply

Apache default Logs will contain some other data like bytes and status code after this bit
```^<HOST> -.*"(GET|POST|HEAD).*HTTP.*"```
and before ```(?:%(badbots)s|%(badbotscustom)s)"$```
So the regex will never match anything as long there are extra characters in between.

For example this line won't be ever caught:
```192.1.1.11 - - [17/Jan/2023:06:25:32 +0000] "GET /some/url/index.php HTTP/1.1" 200 249854 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.268"```

because according to the regex after this bit ```HTTP.*"``` it expects the non-capturing match ```(?:%(badbots)s|%(badbotscustom)s)"$``` straight away.

Not sure my solution is good, but it works on my setup.

**Comment by sebres** [comment]
> Apache default Logs will contain some other data like bytes and status code after this bit

This is not a problem here, because at the moment the regex has a catch-all to bypass that:
```ini
failregex = ^<HOST> -.*"(GET|POST|HEAD).*HTTP.*"(?:%(badbots)s|%(badbotscustom)s)"$
#                                            ^
```
at the moment it matches the part after HTTP up to next quote before Bad-Agent (`/1.1" 200 249854 "-" "` in your example).

Also line from your example would not be matched (no matter how weak one would rewrite the RE, because YandexBot is simply not included in badbots or badbotscustom list, and I don't think why it should).
PoC:
```bash
msg='192.1.1.11 - - [17/Jan/2023:06:25:32 +0000] "GET /some/url/index.php HTTP/1.1" 200 249854 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.268"'

$ fail2ban-regex "$msg" 'apache-badbots[badbotscustom='"'"'[^"]*\bYandexBot\b[^"]*'"'"']'
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
# but:
$ fail2ban-regex "$msg" 'apache-badbots[failregex='"'"'^<HOST> -.*"(GET|POST|HEAD).*HTTP.*".*(?:<badbots>|<badbotscustom>)"$'"'"']'
Lines: 1 lines, 0 ignored, 0 matched, 1 missed
```

Just neither I like (and recommend to use) the existing filter (due to its weaknesses), nor I think making it more weak would be somehow justified, let alone the outdated list (and necessity to update it periodically) as well as the possible false positives etc.
Not to mention the possibility for bots to switch the agent (disguise itself using common browser agent).

Better option could be good concepted robots.txt and a rate-limiting for bots and/or filters like `nginx-limit-req` to ban too aggressive bots by exceeding limits (or generating a lot of traffic on unexpected locations).

Additionally it is questionable to monitor access-log at all, see https://github.com/fail2ban/fail2ban/wiki/Best-practice#reduce-parasitic-log-traffic

Anyway, If someone really need apache-badbots similar filters, one'd use something like this:
```ini
failregex = ^<ADDR> [^"]*"[^"]+" \d+ \d+ "[^"]*" "[^"]*\b(?:<badbots>|<badbotscustom>)\b[^"]*"
```
Note that the regex is more strict and faster, not confuses other parts like referrer with agent, etc.
Also note the construct `"[^"]*\b ... \b[^"]*"` around the bot-name, which in opposite to catch-all's `.* ... .*` doesn't jump from the quotes (thus also many times faster) and uses a word-boundary (`\b`), so would have fewer false positives after all.
Although I don't think such "wildcard" at left&right is good idea by default, rather one'd do that for certain bots only.

**Comment by iulianwebdev** [comment]
The Yandex bot was just as an example.
I still fail to see why it wasn't working for me... But that is my problem
Thank you for the detailed explanation. Much obliged
