### ISSUE TITLE
[BR]: apache-auto and .htaccess Require ip possible FP

### ISSUE THREAD

**Issue by Deepcuts** [fail2ban/fail2ban#3483]
### Environment:

- Fail2Ban version : v0.11.2
- OS, including release name/version : Debian 5.10.162-1
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

apache-auth triggered by .htaccess Require ip

#### Steps to reproduce
Website under development and allowing access only from certain IPs, with the use of .htaccess
```
ErrorDocument 403 /index.maintenance.html
<RequireAll>
    Require ip 1.2.3.4 1.2.3.5
</RequireAll>
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]r
```

fail2ban-regex
```
fail2ban-regex --print-all-matched --print-no-missed /var/log/virtualmin/domain_error_log apache-auth | grep 5.6.7.8
|  [Sat Mar 25 03:58:48.888172 2023] [authz_core:error] [pid 126996:tid 140153666381568] [client 5.6.7.8:35394] AH01630: client denied by server configuration: /home/domain/public_html/favicon.ico
|  [Sat Mar 25 03:59:50.005302 2023] [authz_core:error] [pid 126996:tid 140153934817024] [client 5.6.7.8:35414] AH01630: client denied by server configuration: /home/domain/public_html/test
```

#### Observed behavior
fail2ban detects an invalid auth attempt and logs the action

#### Any customizations done to /etc/fail2ban/ configuration

```
[apache-auth]
enabled = true
filter = apache-auth
logpath = %(apache_error_log)s
              /var/log/virtualmin/*_error_log
port = 80,443
findtime = 12h
maxretry = 3
bantime = 30d
```

#### Relevant parts of /var/log/fail2ban.log file:

```
2023-03-25 03:58:49,427 fail2ban.filter         [659]: INFO    [apache-auth] Found 5.6.7.8 - 2023-03-25 03:58:48
```

#### Relevant lines from monitored log files:

```
[Sat Mar 25 03:58:48.888172 2023] [authz_core:error] [pid 126996:tid 140153666381568] [client 5.6.6.8:35394] AH01630: client denied by server configuration: /home/domain/public_html/favicon.ico
[Sat Mar 25 03:58:49.088421 2023] [authz_core:error] [pid 126996:tid 140154173957888] [remote 5.6.7.8:55328] AH01630: client denied by server configuration: /home/domain/public_html/index.maintenance.html
```

**Comment by sebres** [comment]
> Website under development and allowing access only from certain IPs, with the use of .htaccess

The problem is: the site produces a denied access error, which is intentionally captured as a failure finding by fail2ban.
Obviously we observe a conflict of interest here (many of users would still want consider such attempts as a failures in sense of fail2ban further).
However your approach is a bit strange - normally nobody developing directly on production server.

Anyway, you have several ways to solve that:
- either temporarily put this jail down as long as it's under development (e. g. `fail2ban-client stop apache-auth` and if you get ready `fail2ban-client reload`);
- or use your own filter (rewrite original filter without a `failregex` that causes a finding for that), e. g. remove this RE from `failregex`: https://github.com/fail2ban/fail2ban/blob/a9b30eb86ea4367e7464c90f517b1e1da9c88020/config/filter.d/apache-auth.conf#L27
- or better add own `ignoreregex` to the jail (even possible with some URL-prefix):
```ini
[apache-auth]
enabled = true
ignoreregex = ^client denied by server configuration: /home/domain/public_html/
```
