### ISSUE TITLE
modsecurity confusion with fail2ban log 

### ISSUE THREAD

**Issue by mtissington** [fail2ban/fail2ban#3488]
I have setup modsec according to [https://www.fail2ban.org/wiki/index.php/HOWTO_fail2ban_with_ModSecurity2.5](url)

I am confused about the following entries in fail2ban log, specifically the following line
```
2023-04-03 02:09:13,767 fail2ban.filter         [9723]: WARNING [modsec] Found a match but no valid date/time found for '03/Apr/2023:02:09:13 +0800'.
2023-04-03 02:09:13,767 fail2ban.filter         [9723]: WARNING [modsec] Match without a timestamp: 03/Apr/2023:02:09:13 +0800Message: Rule 7f2d83742c58 [id "-"][file "/etc/apache2/modsecurity-crs/coreruleset-3.3.0/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"][line "345"] - Execution error - PCRE limits exceeded (-8): (null).
2023-04-03 02:09:13,767 fail2ban.filter         [9723]: WARNING [modsec] Please try setting a custom date pattern (see man page jail.conf(5)).
2023-04-03 02:09:13,768 fail2ban.ipdns          [9723]: WARNING Unable to find a corresponding IP address for Execution: [Errno -2] Name or service not known
```

and also
```
2023-04-03 02:09:31,505 fail2ban.ipdns          [9723]: WARNING Unable to find a corresponding IP address for library: [Errno -2] Name or service not known
2023-04-03 02:09:31,509 fail2ban.ipdns          [9723]: WARNING Unable to find a corresponding IP address for libraries: [Errno -2] Name or service not known
```
Can I fix these warnings and if so how?

**Comment by nillebor** [comment]
Hello Sebres
I have the same problem and have tested all settings and configs for several hours. I've read all the pages and comments that Google spits out, especially from sebres and crazy max.

I installed fail2ban on a Synology Diskstation in Docker. This also works without problems, only the error message always comes. What is this good for? In my tests, I found out that the message comes every 5 minutes, unless a new entry takes place in time. As long as a new connection takes place in the 5 minutes, everything is ok, even over a longer period of time.

I tested this with Opengist (Docker) internally with IP and FQDN (own DNS server) and externally with IP and FQDN. Internal and external is the same result. But I wanted to rule out a possible mistake.

My Jail, Log Opengist and fail2ban are here:

[opengist.log](https://github.com/fail2ban/fail2ban/files/11707753/opengist.log)
[fail2ban.log](https://github.com/fail2ban/fail2ban/files/11707754/fail2ban.log)
[jail.txt](https://github.com/fail2ban/fail2ban/files/11707798/jail.txt)
[filter.txt](https://github.com/fail2ban/fail2ban/files/11707799/filter.txt)

The ban and fail2ban works without problems. It's just a beauty problem for me. I would like to stop this and learn more about the ipdns. Do you have some more info for me? Why is the setting not taken into Docker? Do you see another mistake with me?

Thanks

**Comment by mtissington** [comment]
I found the name of the jail was the problem - or rather the length - I think it is limited to 8 characters.

**Comment by nillebor** [comment]
Are you sure about that? Just be vaultwarden-admin there are a lot more letters.
Which error message does your statement apply to?

**Comment by mtissington** [comment]
Am I sure? - well I had the issue about IP address, and when I shortened the name of the jail it resolved the issue.

**Comment by nillebor** [comment]
I have now renamed the jail and filter. Of course, with `dnsuse = no`. - with the same result:

![grafik](https://github.com/fail2ban/fail2ban/assets/59985723/9c59dba9-b216-491b-a482-a5d7db4394a7)

**Comment by mtissington** [comment]
What is in your jail.local?

In my case I had `[wordpress]` and when I changed it to `[wp]`

I just revisited my jail.local and noted a comment to myself that section names are limited to 7 characters.

**Comment by nillebor** [comment]
Sorry, I don't have jail.local. I have a jail.conf for jail.d and filter.d. So far, the instructions have not mentioned a jail.local. Does this always have to be created? Is there a reason why the setting of `usedns = no` is not taken into account in the jail.conf? 

I tried it with a gist.conf (jail & filter) and the gist.local, therefore all 3 files together! The warning message still comes up. The option `usedns = no` is **ignored** and is also **not included** in the start log.

Do you also use docker and the image of crazy-max? Maybe @sebres can say something else about what it could be.

**Comment by sebres** [comment]
> It's just a beauty problem for me. I would like to stop this and learn more about the ipdns. Do you have some more info for me?

The warning `Unable to find a corresponding IP address for fail2ban` shows a impossibility to resolve IP for host `fail2ban`. 
It has possibly nothing to do with `usedns`, but probably with `ignoreip` (where is a host name fail2ban in the list).
Try to find it in your configs (e. g. also in `[Default]` section). And/or inspect the dump of fail2ban start stream, e. g. `fail2ban-client -vv --dp` or `fail2ban-client -d | grep ignoreip`.

> The option usedns = no is ignored and is also not included in the start log.

It is not ignored. This option disabled only handling around `<HOST>` tag, with value `no`:
- it would stop DNS resolving on the phase of failure search if hostname is found instead of IP.
- but also it would quasi change the `<HOST>` to `<ADDR>` (so hostnames are not matched anymore).

**Comment by sebres** [comment]
> I found the name of the jail was the problem - or rather the length - I think it is limited to 8 characters.

You're wrong, @mtissington.
Neither this has something with that warning, nor such length limitation is somehow known.
Basically the length of jail name can be an issue in some action, because it is supplied to action and interpolated there as a name of chain.
In case of iptables action, the resulting name of chain becomes `f2b-name_of_jail`, so for some old netfilter/distros (with XT_FUNCTION_MAXNAMELEN defined as 30), it means the length of jail name can be 26.
Also it is possible to rewrite the chain name, e. g.:
```ini
[...some-very-long-jail-name...]
chain = some-short-unique-name
```
However as already said, it is 26 (and not 8) characters, and this warning is completely different thing.
Other actions (or some distros) may surely have different limitations, but 8 (+4 for `f2b-` prefix) would be anyway too short for my taste.
