### ISSUE TITLE
Multiple SASL Login Attempts adds IP Address to be Ignored

### ISSUE THREAD

**Issue by tanderson213** [fail2ban/fail2ban#3495]
Fail2Ban works.

We wanted to know how the bad actors are able to add IP Address to be ignored by F2B

![image](https://user-images.githubusercontent.com/130790495/232128035-1da471ce-f062-4db4-a3d7-102acd676edf.png)

Thanks for your help

**Comment by sebres** [comment]
> how the bad actors are able to add IP Address to be ignored by F2B

They are not.
The log message `Ignore ... by ip` occurs because of [ignoreip](https://manpages.debian.org/unstable/fail2ban/jail.conf.5.en.html#ignoreip) option, that someone (you?) configured for the jail or in default section of jail.local.
Maybe it is wrong CIDR mask (like /1 or even /0) used for some IP there.

**Comment by tanderson213** [comment]
Thanks Sebres, We will check the Fail2Ban dump
