### ISSUE TITLE
How to automatically set you WAN IP as ignored in jail.local

### ISSUE THREAD

**Issue by AndrzejL-eu** [fail2ban/fail2ban#3504]
Hello,

I was wondering if there was a way for a fail2ban to automagically detect my external (WAN) IP and add it to the jail.local file as ignored?

Kindest regards.

Andrzej

**Comment by sebres** [comment]
I guess you speak about a server running behind the NAT (or the router) where fail2ban is running. 
In that case it is hardly possible on side of that server, because only the router really know your external IP.
Just it is questionable why fail2ban would really need to know it... your intranet servers must then establish some outgoing connections and they must be external (why? if normally it'd always prefer internal routing), otherwise something from other side would do that, but doesn't provide a proxying original IP (and may do an attack and then ignored by fail2ban). Either way I don't see why it'd be an advantage for you.

However it is surely possible:
- either by specifying of dns resolving your external IP address in `ignoreip` (likely preferred variant);
- or by specifying of a callback in the router refreshing fail2ban configuration after update of dynamic IP (many routers provide such a possibility), for instance by writing it into fail2ban's config and doing `fail2ban-client reload` hereafter;
- or, if you know some command to obtain an IP from router, using `ignorecommand` (and/or `ignorecache`), for instance:
```ini
ignorecache = key="<ip>", max-count=100, max-time=5m
ignorecommand = if [ "<ip>" = "$(curl -s4 ifconfig.co/)" ] || [ "<ip>" = "$(curl -s6 ifconfig.co/)" ]; then exit 0; fi; exit 1
```
  the last one is the worst case because to check every IP it'd need to establish external connection (here to ifconfig.co), let alone possible connectivity issues along with possible service quota.
