### ISSUE TITLE
<matches> only contains 1st line after update to v0.11.2

### ISSUE THREAD

**Issue by defkev** [fail2ban/fail2ban#3510]
I use `<matches>` in a custom action like so:

```
banaction = alert=$(echo "<matches>" | python -c "import sys; parseMatchesFrom.sys.stdin.read()"); curl --data "alert=$alert" http://my.super.fancy/api/v2
```

to postprocess matches and dump them on an internal API endpoint.

This used to, and still does, work pretty well except since updating to v0.11.2 (from 0.9?) `<matches>` only contains the 1st log line matching the filter instead of all lines.

I can even reproduce this by replacing banaction with just `echo "<matches>"` and running fail2ban-server with --loglevel DEBUG watching stdout

Oddly enough if i use %(action_mwl)s (sendmail-whois-matches.conf) the mail still contains all matching log lines.

What gives?

**Comment by defkev** [comment]
Okay this really seems to be related to

> 0.11 is significantly faster than 0.9

causing `maxretry` to (now) work as intended :grin: 

The jail in question (honeypot) is using `maxretry = 0` if i increase this to the default of 5 i get 5 hits in `<matches>` instead of just 1 whereas in 0.9 i would get all, or i assume at the very least most `<matches>` regardless.

Is there any way to "delay" an action until `<matches>` is fully populated considering the failmanager/addFailure thread sees all hits (6 in total all within <1 second) before the observer/banFound triggers util/executeCmd to mimic the 0.9 behavior?

The action in this particular case (aggregation) is not time critical i would even be willing to wait 30 seconds as long as i get all `<matches>`

**Comment by sebres** [comment]
> Is there any way to "delay" an action until `<matches>`

Direct? Unfortunately no, not really... At least without to patch something in the source code.
(However I must admit such a delay may be nice feature).

Since the ban takes place as fast as possible, matches get rare more lines as expected for ban.
The only way how one could do that by oneself would be a grep in log-files inside the action.
Similar to `*-lines` actions, with `%(_grep_logs)s`:
https://github.com/fail2ban/fail2ban/blob/5d9603c104fd50c6320d69dec394a28a452606f5/config/action.d/helpers-common.conf#L7
Just if the ban happens too fast, one would need additionally to slowdown the action a bit with a `sleep` and co. What can cause that a real banning (if action also contains a banaction) would be delayed also, what may be not so good.
So some asynchronous call doing grep and expected job after small delay may be the solution here:
```
( sleep 1s ; do-something "%(_grep_logs)s" ) &
```

**Comment by defkev** [comment]
Using `%(_grep_logs)s` in my `banaction` (like `sendmail-whois-lines.conf`, dunno why i assumed this used `<matches>`) with a custom `_grep_logs_args` works as intended to restore the "old" behavior:

```
_grep_logs_args = -wE `foo <ip> bar"
banaction = alert=$(%(_grep_logs)s | python -c "import sys; parseMatchesFrom.sys.stdin.read()"); curl --data "alert=$alert" http://my.super.fancy/api/v2
```

Tho i can see this become a problem if logrotate is longer than `bantime` (which is about equal in my case) causing `_grep_logs` to pick up old lines on consecutive bans so a configurable `action` delay like e.g.

```
action = my-super-duper-action[delay=30] # Delay my-super-duper-action for 30 seconds
```

would still be nice-to-have.
