### ISSUE TITLE
nginx-4xx regex filter problem

### ISSUE THREAD

**Issue by ezubnt** [fail2ban/fail2ban#3518]
Hi fail2ban team

Im trying to resolve an issue with fail2ban where a nginx-4xx which reads all 4xx error codes and bans the IP's receives the following error and causes issues with the startup of fail2ban.
 
jail.local/conf:

[nginx-4xx] 
enabled = true 
port    = http,https 
filter  = nginx-4xx 
logpath = /config/log/nginx/access.log 
action = iptables-allports

filter.d:

[Definition] 
failregex = ^<HOST>.*"(GET|POST).*" (404|444|403|400) .*$
ignoreregex = 

fail2ban.log shows the error below reffering to a regex which isnt part of my config, so im not sure where to start looking or make a change:

['start', 'nginx-http-auth'], ['start', 'nginx-botsearch'], ['start', 'nginx-badbots'], ['start', 'nginx-deny'], ['start', 'nginx-unauthorized'], ['start', 'nginx-4xx']]] has failed. Received RegexException("Unable to compile regular expression '.*(?i)plex.*':\nglobal flags not at the start of the expression at position 2")

any help will be appreciated
Thanks in advance

**Comment by ezubnt** [comment]
OK this was resolved with a linuxserver.io update to the SWAG container

**Comment by sebres** [comment]
_As a retrospect, for the people coming here with similar "error"..._

1. Latest RE-engine of newest python versions [doesn't allow](https://bugs.python.org/issue22493) to supply global flags like `(?i)` in the middle of RE, so it must be rewritten either with move of global flags to the start of RE or usage of local flags like `(?i: ... )`. Basically (since #3267) fail2ban is able to map global flags to local flags, but only if it can recognize that.
2. Provided configuration seems not to contain errored RE `.*(?i)plex.*` at all.
So it may be somewhere else (grep `/etc/fail2ban` for that).
Also dump of start stream may help to find the issue - `fail2ban-client -vv --dp`.
3. Provided RE is vulnerable, contains catch-alls and unanchored. Use something like that:
```diff
- failregex = ^<HOST>.*"(GET|POST).*" (404|444|403|400) .*$
+ failregex = ^<ADDR> [^"]*"[A-Z]{3,} [^"]+" 4(?:0[034]|44)
```
or something a bit more descriptive and configurable:
```ini
_req_method = [A-Z]{3,}
# _req_code = 4(?:0[034]|44)
_req_code = (?!401)[345]0\d
_req_uri = \S+
failregex = ^<HOST> -[^"]*\"%(_req_method)s\s+/(?:%(_req_uri)s) HTTP/[^"]+" (?:%(_req_code)s)\s
```
4. Also direct monitoring of access-log is not recommended (due to possible large parasite log-traffic), see [wiki :: Best practice](https://github.com/fail2ban/fail2ban/wiki/Best-practice) for details.

**Comment by ezubnt** [comment]
Thanks @sebres for the improved regex examples , usage suggestions and wiki references - much appreciated ...
