### ISSUE TITLE
[BR]: Keep getting "Unable to negotiate with x port y: no matching key exchange method found" despite setting mode to aggressive

### ISSUE THREAD

**Issue by Phouter0499** [fail2ban/fail2ban#3538]
### Environment:

I am using the latest version of fail2ban for ubuntu server 22.04.02

### The issue:

I keep getting error message of this form:
```
Unable to negotiate with 185.225.74.53 port 36962: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 [preauth]
```
I highly suspect I am getting probed left and right. I already have 34 ips banned.

#### Expected behavior

I was expecting fail2ban to stop ban any ips failing to negotiate as well. I have had this expectation because after doing some google search, someone else had a similar issue and many answered that one just had to set mode to aggressive. I also searched here as well but I can't find any answers relevant to me. I am a newbie and I am not exactly sure what to do from here on out.

#### Any additional information

Here is my jail.local file:
```
[sshd]
mode = aggressive
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 2
findtime = 300
bantime = 86400
bantime.increment = true
bantime.maxtime = 5w
ignoreip = 127.0.0.1
```

**Comment by sebres** [comment]
> many answered that one just had to set mode to aggressive.

Yes it is, if one exactly follows the configuration manuals e. g. from [wiki :: Proper fail2ban configuration](https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration)...
Basically 2 points are interesting related to that issue:
- **don't** copy jail.conf to jail.local
- configure only settings you really need to overwrite.

In you case it is surely `filter = sshd` which overwrites default https://github.com/fail2ban/fail2ban/blob/48c91dfb6bd8478968c226d0c6ca965bdce2768d/config/jail.conf#L167
(so `mode` configured in jail is not supplied to the filter at all and it works in `mode = normal`)

Simply remote it:
```diff
- filter = sshd
```
or if you overwrite this, do it correctly:
```diff
- mode = aggressive
- filter = sshd
+ filter = sshd[mode=aggressive]
```
Although the last is not recommended, because it can miss some parameters later that become specified by default in future fail2ban versions by upgrade. So use it only if you want use another filter or specify more parameters.

That all as regards the latest versions of fail2ban. So the provided line will match by current filter.
You can check it by yourselves using
`fail2ban-regex "$msg_or_log_name_or_journal" 'sshd[mode=aggressive]'`...

I have no idea which fail2ban version exactly Ubuntu 22.04 install, so if it is older than some fix matching that (basically too old), you can try to add this to `[sshd]` section in your `jail.local`:
```ini
failregex = %(known/failregex)s
            ^Unable to negotiate with <HOST>(?: (?:port \d+|on \S+)){0,2}: no matching (?:(?:\w+ (?!found\b)){0,2}\w+) found.
```
(note the spaces are mandatory).

Alternatively one can try to upgrade config file from [filter.d/sshd.conf#L84](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/sshd.conf#L84)

If it doesn't work for you, please provide more info, for instance:
```
fail2ban-regex --version
msg='... full line with Unable to negotiate from your log or journal ...'
fail2ban-regex -vv "$msg" 'sshd[mode=aggressive]'
```

**Comment by Phouter0499** [comment]
doesn't work.
using fail2ban-regex 0.11.2
msg='Unable to negotiate with 185.225.74.53 port 36962: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 [preauth]'

|- Missed line(s):
|  Unable to negotiate with 185.225.74.53 port 36962: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 [preauth]

**Comment by sebres** [comment]
"Doesn't work" doesn't exist...

1. As for fail2ban-regex: you need to use the **whole** message in command line for fail2ban-regex (with timestamp, host, pid and all the prefixes before `Unable ...`).
Or test it against log file or journal (or it's excerpt).
BTW, also always provide the complete output (so one'd be able to find the reason, if it'd really miss the match).
2. If it doesn't match in fail2ban server (after removal of `filter` from the jail section), the reason may be - you simply forgot to reload the configuration:
```
?sudo? fail2ban-client reload
```
3. and last but not least - it must work with v.0.11.2, at least it does that with the stock filter.
