### ISSUE TITLE
[BR]: Confilict with docker in CentOS8

### ISSUE THREAD

**Issue by huangjinshe** [fail2ban/fail2ban#3547]
Unable to install, always show:

```
[root@MyServer ~]# yum install fail2ban
Last metadata expiration check: 0:37:29 ago on Sat 05 Aug 2023 02:51:58 AM CST.
Error:
 Problem: problem with installed package selinux-policy-targeted-3.14.3-80.el8_5.2.noarch
  - package fail2ban-server-1.0.2-3.el8.noarch requires (fail2ban-selinux if selinux-policy-targeted), but none of the providers can be installed
  - package fail2ban-1.0.2-3.el8.noarch requires fail2ban-server = 1.0.2-3.el8, but none of the providers can be installed
  - conflicting requests
  - nothing provides selinux-policy >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
  - nothing provides selinux-policy-base >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[root@MyServer ~]#
```
But if we uninstall docker with it dependency, then it could install.

Disable selinux, use `--skip-broken`, or `--nobest`  all not working....

**Comment by sebres** [comment]
This is wrong place for that issue - this is upstream development repository and has nothing with packages of any distribution (excepting probably upstream package for debians released here).
The issue is surely a matter of fail2ban (or docker) maintainers for CentOS.
@fail2ban/maintainers, @crazy-max any idea what could cause that?

**Comment by crazy-max** [comment]
The only "requires" I see in our packaging is https://github.com/docker/docker-ce-packaging/blob/6d29a612078e1bef63cb042e22a29ac3eacdba6d/rpm/SPECS/docker-ce.spec#L18 and not sure how it could conflict :thinking: Rings a bell @thaJeztah?

**Comment by thaJeztah** [comment]
Yeah, no idea how that would conflict. Do you have docker packages from download.docker.com installed, or are those packages provided by your distro? What version of docker do you have installed?

**Comment by huangjinshe** [comment]
I'm using the newest version of docker, I can't fix it , docker need some version of selinux, but looks like when I install ban2fail it'll need different version of selinux....  the OS is CentOS8.  so at the end I installed the lowest version of fail2ban one by one manually few days ago, like fail2ban-client,  fail2ban-server, ...etc.  I don't remember the version, maybe like 0.9.8 around.   but today I checked and it showed version is : Fail2Ban v0.11.2,  I don't remember when it upgraded.....


Here is some info:

>  Version:           24.0.5
>  API version:       1.43
>  Go version:        go1.20.6
>  Git commit:        ced0996
>  Built:             Fri Jul 21 20:36:32 2023
>  OS/Arch:           linux/amd64
>  Context:           default
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          24.0.5
>   API version:      1.43 (minimum version 1.12)
>   Go version:       go1.20.6
>   Git commit:       a61e2b4
>   Built:            Fri Jul 21 20:35:32 2023
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.6.22
>   GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
>  runc:
>   Version:          1.1.8
>   GitCommit:        v1.1.8-0-g82f18fe
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0

> CentOS Linux release 8.5.2111


The funny things is another OS use CentOS 7.9, all fine.

**Comment by sixpackets** [comment]
same issue. 

Seems due to packaged version. 

" selinux-policy-3.14.3-80.el8_5.2.noarch " is what's there, while package "fail2ban-server-1.0.2-3.el8.noarch" is saying:
  - nothing provides selinux-policy >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
  - nothing provides selinux-policy-base >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch

so i guess we wait til selinux-policy-{>\=}3.14.3-108.el8_7.1 is packaged and available, and simultaneously hope and pray that no new release of "fail2ban-server" is released that requires a newly unavailable packetd selinux-policy version.

**Comment by jynine** [comment]
![image](https://github.com/fail2ban/fail2ban/assets/6419646/24da9937-6095-4d84-b308-18da3b905c62)
出现相同的问题
