### ISSUE TITLE
Openvz7 kernel 3.10 Ubuntu 22.04 behavior of fail2ban

### ISSUE THREAD

**Issue by changemenemo** [fail2ban/fail2ban#3556]
Hi,
I'm sorry for the lack of template but I'm not really comfortable to classify what follows as a bug, a feature request or just a question.

I know that openvz has been let go over time but a lot of providers are still using it. My end goal was to use docker and fail2ban inside openvz but being blocked (mostly by docker) I have encountered also a few bugs or bad implementation of iptables(nftables)´s usage by fail2ban.

As far as I can see it is reproductible on every openvz7 with same distribution. Fail2ban is duplicating rules inside INPUT but also f2b-sshd. Which leads to also a RETURN rule (which should only be in f2b-* chain) .

Can we do something about it ?
Thanks in advance for any answers provided

**Comment by sebres** [comment]
> Fail2ban is duplicating rules inside INPUT but also f2b-sshd. 

Normally fail2ban would never do that. Where I could imagine the double entries in iptables would be a restart of fail2ban after some failed start (e. g. due to incorrect configuration by start of action, so a stop of action doesn't clean all the entries).
So it can be:
1. either not a fail2ban issue (e. g. some bug by mockup iptables-nftables).
2. or some incorrect fail2ban configuration (causing errors by start/first ban, see fail2ban.log for details).

> Can we do something about it ?

In former case - maybe switch to [ntfables](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/nftables.conf) action:
```ini
[DEFAULT]
banaction = nftables[type=multiport]
banaction_allports = nftables[type=allports]
```

In second case we need more info: errors in fail2ban.log, excerpt of config or its dump `fail2ban-client -d`.
