### ISSUE TITLE
[FR]: Jail for Docker logs, filter 40x cods for app in container. Error date pattern. 

### ISSUE THREAD

**Issue by Bellikaa** [fail2ban/fail2ban#3601]
### Environment:

- Fail2Ban version  :  Fail2Ban v0.11.1
- OS, including release name/version : Ubuntu 20.04

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : created a new filter and jail
- Service, project or product name, including release name/version : log by my app in docker container 

#### Log or journal information

- Log file name(s) :  *container-id*-json.log 

#### Any additional information

I made a regular expression that matches the logs with the required parameters, attempts are selected in the fail2ban logs, but there is a message about the wrong time and attempts are not banned

#### failures in sense of fail2ban filter (fail2ban must match):

```
{"log":"INFO:     213.87.134.38:53735 - \"GET /wer HTTP/1.1\" 404 Not Found\n","stream":"stdout","time":"2023-10-10T14:47:35.467434244Z"}
```

#### legitimate messages (fail2ban should not consider as failures):

```
{"log":"INFO:     167.94.138.126:39894 - \"GET / HTTP/1.1\" 200 OK\n","stream":"stdout","time":"2023-10-11T06:12:12.958941353Z"}

```

#### My filter:
```
[INCLUDES]
before = common.conf

[Definition]
failregex = ^.*<HOST>\:.*\"(GET|POST).*\" (405|404|444|403|400) .*$
ignoreregex = /apple-touch-icon.*
              /favicon\.ico

````
#### My jail:
```
[ban400]
enabled = true
backend = pyinotify
filter = ban400
port = http,https
logpath = /var/lib/docker/containers/*/*-json.log
bantime = 86400
findtime = 600
maxretry = 4

```
If I add Includes to the jail file, then I have no matches. But at the same time, information about attempts is received in the ban file logs.
![изображение](https://github.com/fail2ban/fail2ban/assets/37300371/ac84a237-2da4-4b6e-97f4-15a59336b38d)

But if you comment Includes, there are matches. (Add scrin)
![изображение](https://github.com/fail2ban/fail2ban/assets/37300371/f69d32bb-9045-4bb0-b0cd-49b66c09febf)

Please tell me how I can correct the filter and jail so that it works correctly?

**Comment by sebres** [comment]
> But if you comment Includes, there are matches.

Because by default common include specifies datepatterns anchored at begin of message:
https://github.com/fail2ban/fail2ban/blob/8eac5f597aaf0c993f4ba006beeeafa28b18bafe/config/filter.d/common.conf#L73

Since you don't use anything from common include, you don't need it at all.

You can also specify anchored datepattern (what'd make the search more faster and precise):
```ini
# datepattern = (?:,\s*)?"time":"{DATE}"(?=\}$)
datepattern = (?:,\s*)?"time":"%%Y-%%m-%%dT%%H:%%M:%%S\.%%f\d*%%z"(?=\}$)
```

By the way, your RE is extremely vulnerable, slow and ugly due to several catch-alls and its unanchored nature (`^.*` and `.*$` are not anchors at all), so tag `<HOST>` may match something in the middle of the string (even a word, which will be mistakenly resolved as FQDN) or 404 at different place (e. g. in part of the URI), so may match a lot of false positives or open an injection vector to generate improper block for legitimate addresses.

Until fail2ban doesn't have real json preprocessing (there is an RFE about that), better would be to use something like that:
```ini
failregex = ^\{"log"\s*:\s*"INFO:\s+<ADDR>:\d+ \S+ \\"[A-Z]+ [^"]*\\" 4(?:0[0345]|44)
```

Additionally take a look at [wiki :: Best practice](https://github.com/fail2ban/fail2ban/wiki/Best-practice).

**Comment by Bellikaa** [comment]
Thanks for the answer. Your solution works correctly.
