### ISSUE TITLE
fail2ban.configreader   [224376]: ERROR   No section: 'Definition'

### ISSUE THREAD

**Issue by fw114** [fail2ban/fail2ban#3643]
Hi,
i got a similar issue like in this old thread : https://github.com/fail2ban/fail2ban/issues/2849
i dont use nginx

but can't find the solution so i hope u can help me out here.

so...
if i start fail2ban i got the error message that:

fail2ban-client -v -v -v start

 99 7EFF48C43040 fail2ban.configreader     DEBUG Reading configs for filter.d/botsearch-common under /etc/fail2ban 
 +   99 7EFF48C43040 fail2ban.configreader     DEBUG Reading config files: /etc/fail2ban/filter.d/botsearch-common.conf
 +   99 7EFF48C43040 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/filter.d/botsearch-common.conf']
 +   99 7EFF48C43040 fail2ban.configparserinc  TRACE     Shared file: /etc/fail2ban/filter.d/botsearch-common.conf
 +  100 7EFF48C43040 fail2ban.configreader     ERROR No section: 'Definition'
 +  100 7EFF48C43040 fail2ban.configreader     ERROR No section: 'Definition'
 +  100 7EFF48C43040 fail2ban.configreader     ERROR No section: 'Definition'
 +  100 7EFF48C43040 fail2ban.configreader     ERROR No section: 'Definition'
 +  100 7EFF48C43040 fail2ban.configreader     ERROR No section: 'Definition'
 +  100 7EFF48C43040 fail2ban.configreader     ERROR No section: 'Definition'
 +  100 7EFF48C43040 fail2ban.configreader     ERROR No section: 'Definition'
 +  101 7EFF48C43040 fail2ban.configreader     ERROR No section: 'Definition'
 +  101 7EFF48C43040 fail2ban.configreader     ERROR No section: 'Definition'
 +  101 7EFF48C43040 fail2ban.configreader     ERROR No section: 'Definition'
 +  101 7EFF48C43040 fail2ban.configreader     ERROR No section: 'Definition'
 +  101 7EFF48C43040 fail2ban.configreader     ERROR No section: 'Definition'
 +  101 7EFF48C43040 fail2ban.configreader     ERROR No section: 'Definition'
 +  114 7EFF48C43040 fail2ban                  DEBUG   async starting of server in 225416, fork: True - 225417
 +  115 7EFF48C43040 fail2ban                  DEBUG   async starting of server in 225417, fork: True - 0
 +  115 7EFF48C43040 fail2ban                  DEBUG Starting '/usr/bin/fail2ban-server' with args ['fail2ban-server', '--async', '-b', '-s', '/var/run/fail2ban/fail2ban.sock', '-p', '/var/run/fail2ban/fail2ban.pid', '-vvv', '--loglevel', 'INFO', '--logtarget', '/var/log/fail2ban.log', '--syslogsocket', 'auto']
 +  115 7EFF48C43040 fail2ban                  HEAVY __waitOnServer: (True, 30)
 +  116 7EFF48C43040 fail2ban                  HEAVY   wait-time: 0.0010335445404052734
 +  129 7EFF48C43040 fail2ban                  HEAVY   wait-time: 0.01399683952331543
 +  154 7EFF48C43040 fail2ban                  HEAVY   wait-time: 0.039267778396606445
 +   25 7FE32DD30040 fail2ban                  INFO  Using socket file /var/run/fail2ban/fail2ban.sock
 +   25 7FE32DD30040 fail2ban                  INFO  Using pid file /var/run/fail2ban/fail2ban.pid, [INFO] logging to /var/log/fail2ban.log
 +   25 7FE32DD30040 fail2ban                  DEBUG   direct starting of server in 225417, deamon: True
 +   52 7FE32DD30040 fail2ban.server           INFO  Starting in daemon mode
 +   54 7FE32DD30040 fail2ban                  DEBUG Exit with code 0
 +  204 7EFF48C43040 fail2ban                  HEAVY   wait-time: 0.08960843086242676
 +  305 7EFF48C43040 fail2ban                  HEAVY CMD: ['ping', 0.1]
 +  305 7EFF48C43040 fail2ban                  HEAVY OK : 'pong'

in botsearch-common.conf is no definition OK. so the error has to be in another file
but i am not able to find out in which one .
can u guide me here ? Thank you

**Comment by sebres** [comment]
[botsearch-common](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/botsearch-common.conf) seems indeed not to have `Definition` section (one can create it, just as empty section `[Definition]` before `[Init]`), but it is just an include (normally it is included in other filters, like [nginx-botsearch.conf](https://github.com/fail2ban/fail2ban/blob/44fa2959e7c8ee010138250b3dafcfebc57dbce8/config/filter.d/nginx-botsearch.conf#L7) or [apache-botsearch.conf](https://github.com/fail2ban/fail2ban/blob/44fa2959e7c8ee010138250b3dafcfebc57dbce8/config/filter.d/apache-botsearch.conf#L22), which do have this section), so it overwrites init section only in both mentioned filters.

Did you create a `botsearch-common` jail or use `filter = botsearch-common` somewhere (in `jail.local` or `jail.d/*.conf`)? 
If so this is the error, because you must use one of both mentioned filters instead.

**Comment by fw114** [comment]
Hi, thanks for your answer. 
i have no clue what changes i've done. so here comes the dump (Note : IpV6 is disabled on this system!)

[fail.txt](https://github.com/fail2ban/fail2ban/files/13624284/fail.txt)

**Comment by sebres** [comment]
Well, I see jail `botsearch-common` in your config dump, so I guess it also uses `botsearch-common` filter (by default the jail uses a filter with the same name).
Please read carefully my `https://github.com/fail2ban/fail2ban/issues/3643#issuecomment-1841288398` - you should not have  `botsearch-common` jail and not use `botsearch-common` (since it is an include)... 
Instead, for nginx use `nginx-botsearch` or for apache use `apache-botsearch`.
Stock fail2ban doesn't have jail `botsearch-common` at all (see https://github.com/search?q=repo%3Afail2ban%2Ffail2ban%20botsearch-common&type=code)
So remove that jail from your jail.local, or create your own filter (with definition section) and use it inside.
