### ISSUE TITLE
Error when trying to ban? 

### ISSUE THREAD

**Issue by mjessa12** [fail2ban/fail2ban#3663]
![image](https://github.com/fail2ban/fail2ban/assets/72001246/3ea666fd-e47f-4d72-a02d-7e44782f851d)

anyone know how to fix this issue? f2b running in docker reading NPM logs

**Comment by sebres** [comment]
1. Why do you completely ignored the issue template, which is extremely important, and yes, maybe costs a bit of your time, but spares a lot of our time? This is also often considered rude, since indicate that your time should be thousand times more treasured than ours (and others people filling the issue templates completely).
2. Posting a screenshot to the log excerpt, instead of (blackened) log excerpt itself is really bad manners, you know?
3. The error looks like an after effect, so the log contains probably more errors previously... 

Anyway it is hard to say without all info.
But my assumption - the jail name is too long for `iptables` related action: IIRC, the max length of `iptables` chain name is 30, and since fail2ban uses `f2b-` prefix for chains, the max length of jail name shall be 26 then.
