### ISSUE TITLE
[RFE]: Mix `<fid>` and `<ip>` in a ban action

### ISSUE THREAD

**Issue by wixaw** [fail2ban/fail2ban#3712]
Hello, 
Would it be possible to mix `<fid>` and `<ip>` in a ban action?

Filter : 
```
[DEFAULT]
_daemon = jupyterhub

[Definition]
ignoreregex =
journalmatch= _SYSTEMD_UNIT=jupyterhub.service + _COMM=jupyterhub
mode = normal
maxlines = 1
failregex = ^.*PAM Authentication failed \(<F-ID>[^@]*</F-ID>@<ADDR>\): .*$

```
Action :
```
[Definition]
actionstart =
actionstop =
actioncheck =
actionban = /bin/ssh remotefw save.sh -s srv -i "<ip>" -t loginFailed -c user:<fid>
actionunban =
```

Log: 
```
2024-03-29 10:29:28,425 fail2ban.utils          [23645]: ERROR   7f3735288f30 -- exec: /bin/ssh remotefw save.sh -s srv -i "xxx.xxx.xxx.xxx" -t loginFailed -c user:xxx.xxx.xxx.xxx
2024-03-29 10:29:28,425 fail2ban.utils          [23645]: ERROR   7f3735288f30 -- stderr: '/bin/sh: line 1: /bin/ssh: Permission denied'
2024-03-29 10:29:28,425 fail2ban.utils          [23645]: ERROR   7f3735288f30 -- returned 126
2024-03-29 10:29:28,431 fail2ban.utils          [23645]: ERROR   7f3735288f30 -- exec: /bin/ssh remotefw save.sh -s srv -i "xxx.xxx.xxx.xxx" -t loginFailed -c user:xxx.xxx.xxx.xxx
2024-03-29 10:29:28,431 fail2ban.utils          [23645]: ERROR   7f3735288f30 -- stderr: '/bin/sh: line 1: /bin/ssh: Permission denied'
2024-03-29 10:29:28,431 fail2ban.utils          [23645]: ERROR   7f3735288f30 -- returned 126
2024-03-29 10:29:28,431 fail2ban.actions        [23645]: ERROR   Failed to execute ban jail 'occidata-jupyter' action 'sendproxy' info 'ActionInfo({'ip': '141.115.3.28', 'family': 'inet4', 'fid': 'xxx.xxx.xxx.xxx', 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7f373650de50>})': Error banning xxx.xxx.xxx.xxx
```

Expected result: 
`/bin/ssh remotefw save.sh -s srv -i "xxx.xxx.xxx.xxx" -t loginFailed -c user:myusername`

Actual result:
`/bin/ssh remotefw save.sh -s srv -i "xxx.xxx.xxx.xxx" -t loginFailed -c user:xxx.xxx.xxx.xxx`

Version Fail2Ban : fail2ban-1.0.2-12.el9.noarch

I also have a problem with the execution of the ssh command, maybe you have an idea?
Edit : Fix, it's SELINUX 

Thanks 
William

**Comment by sebres** [comment]
Yes, they can be combined, but only if your banning action intended to ban by `<fid>` too (meant the intruders with the same `<fid>` will be blocked, so it is not allowed to do further attempts for them, regardless from which IP it arrived). Otherwise (you'll still ban by IP in action), fail2ban would internally think the  `<fid>` is banned, and so doesn't execute the action, even if new failure has different`<ip>`. Tag `<fid>` is unique identifier for the ban.
If it must be banned by a combination, either `<F-ID>` must include both data (the IP is also part of it), for instance `<F-ID>[^@]*@<ADDR></F-ID>` instead of `<F-ID>[^@]*</F-ID>@<ADDR>`.
Or you have to use tuples as ID (see https://github.com/fail2ban/fail2ban/issues/2755#issuecomment-643426471 fo details).

If the IP belong to the ban (and another tags are just informative, use `<ADDR>` for IP and instead of `<F-ID>` something other `<F-*>` (but no ID), for instance  `<F-USER>` for user name (and you can use it as `<F-USER>` in acton too). So in this case the identifier of ban remains the IP (and it is also banned by IP regardless the user name).

As for your actual result, it is unexpected... I don't know why it uses IP as fid... Which fail2ban version is it? Did you restart the jail after changes in the config?

**Comment by wixaw** [comment]
Thank you so much for the great explanations! 

I tried what you suggested and it worked. Out of curiosity, I tried my old code again and it worked too! So it might have been the fact that I fixed my SELinux issue that resolved the problem. 

Here's the policy I added, in case it might be useful to the community:

```bash
module sh_policy 1.0;

require {
        type kmod_exec_t;
        type ssh_exec_t;
        type rpcd_t;
        type autofs_t;
        type ssh_home_t;
        type ssh_port_t;
        type fail2ban_t;
        type default_t;
        type krb5_keytab_t;
        class dir search;
        class file { execute execute_no_trans getattr map open read };
        class tcp_socket name_connect;
}

#============= fail2ban_t ==============
allow fail2ban_t autofs_t:dir search;
allow fail2ban_t default_t:file { execute getattr };
allow fail2ban_t krb5_keytab_t:dir search;
allow fail2ban_t ssh_exec_t:file { execute execute_no_trans getattr open read };

#!!!! This avc can be allowed using the boolean 'domain_can_mmap_files'
allow fail2ban_t ssh_exec_t:file map;
allow fail2ban_t ssh_home_t:dir search;
allow fail2ban_t ssh_home_t:file { getattr open read };

#!!!! This avc can be allowed using the boolean 'nis_enabled'
allow fail2ban_t ssh_port_t:tcp_socket name_connect;

#============= rpcd_t ==============
allow rpcd_t kmod_exec_t:file getattr;
```
Sorry for the inconvenience
