### ISSUE TITLE
[BR]: dpkg: warning: unable to delete old directory '/usr/lib/systemd/system': Directory not empty

### ISSUE THREAD

**Issue by blade1989** [fail2ban/fail2ban#3715]
### Environment:

- Fail2Ban version  : 
- OS, including release name/version : all
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

When deleting fail2ban via ubuntu repo or deb file downloaded from github, I get the following message:

```bash
dpkg: warning: unable to delete old directory '/usr/lib/systemd/system': Directory not empty
```

I don't know much about the creation of .deb files, but I would rather have this just delete the `/usr/lib/systemd/system/fail2ban.service` file, instead of my entire `/usr/lib/systemd/system` directory.

#### Steps to reproduce

On my Ubuntu (22.04) I delete my fail2ban like so:

```
apt remove fail2ban
```
Then you get shown the scary message.

#### Expected behavior

To just remove `/usr/lib/systemd/system/fail2ban.service`, and not display I scary message like `unable to delete old directory '/usr/lib/systemd/system'...`.

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment]
> Then you get shown the scary message.

It is not "scary" at all, many packages do similar attempts (as a consequence of "pre-creation" rules), but would do that only if the directory contains only from package installed files (removed previously), so basically only empty directory.

Anyway:
1. The released here deb-file (and probably Ubuntu package) are built with branches from [salsa.debian.org/.../fail2ban repo](https://salsa.debian.org/python-team/packages/fail2ban) and must be basically discussed there.
2. I don't see a direct attempt to remove (or post-remove) of `/usr/lib/systemd/system`, but can imagine it'd done from deb itself because of [this rule](https://salsa.debian.org/python-team/packages/fail2ban/-/blob/master/debian/rules?ref_type=heads#L48) or here (a bit different) in debian-branch:
https://github.com/fail2ban/fail2ban/blob/07adcc1cc967d47e5feab36c50613693e47273fa/debian/rules#L46

@sylvestre can you follow that? Is it safe to delete this rule (e. g. considering different `$(DESTDIR)` the directory can be missed)?
