### ISSUE TITLE
Help Needed: Creating Fail2ban Filter for Exchange Autodiscover Failed Login Attempts

### ISSUE THREAD

**Issue by jericho234** [fail2ban/fail2ban#3751]
Hi. i have a problem with fail2jail filter for blocking failed login attempts in to exchange autodiscover/autodiscover.xml.

I'm seeking assistance with configuring a fail2ban filter to effectively block failed login attempts targeting the autodiscover/autodiscover.xml endpoint on our Exchange server. Despite mounting IIS log files and ensuring proper setup, I encountered an issue where fail2ban blocked the Exchange server's IP itself instead of the IP attempting the unauthorized access.

To enhance our fail2ban filter's efficacy, I aim to craft a syntax that accurately identifies and blocks IP addresses associated with failed login attempts.

example of my iis logs:
```
2024-05-25 07:19:47 (server ip) GET /autodiscover/autodiscover.xml &CorrelationID=<empty>;&cafeReqId=90e5v93h-5e82-4u64-f8o1-054349555759; 443 - (ip of fail logins attempt) Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/125.0.0.0+Safari/537.36+Edg/125.0.0.0 - 401 0 0 61 -
```
Would anyone kindly share insights or suggestions on refining the fail2ban filter configuration to achieve this? Your expertise and guidance would be immensely appreciated.

Thank you in advance for your assistance.

**Comment by sebres** [comment]
Since it seems only a first authentication 401th response (handshake?), please provide few messages from this IP.
Also if possible a successful attempt (I guess first invoke without a user name and password would always cause 401), so one need to bypass them.

Also please don't blacken the IPs and other data like `(server ip)`, the structure of message must be retained.
Just use test-subnet for IPs, e. g. `192.0.2.1` - for server, `192.0.2.100` - for client, `example.com` for domains, etc.
