### ISSUE TITLE
[RFE]: Extend ignoreip to cater for dynamic IP scenarios by resolving FDNs assigned

### ISSUE THREAD

**Issue by by** [fail2ban/fail2ban#3762]
#### Feature request type
Currently `ignoreip` only searches for its very entries in the logs/sources, so if a fully qualified domain name is used, it will look for it coming up during its operations; with many users running on dynamic IPs these days, it would be great to have a way to resolve (their) FDNs in `ignoreip` every time and use the respective IPv4 and(!) IPv6 values instead solely looking for the FDN itself. 

#### Description
As described above; while the dynamically assigned IP might change over time, I feel it would be sufficient to resolve and compare at ban-time, and not release old bans of it once the assigned IP changes.

#### Considered alternatives
There are solutions available that are incorporated into individual filters (and jails), but I feel that this is a generic problem and should be solved case-independent; this would also make the usage of `ignoreip` more consistent.

#### Any additional information
<none>

**Comment by sebres** [comment]
As [man jail.conf.5#ignoreip](https://manpages.debian.org/bookworm/fail2ban/jail.conf.5.en.html#ignoreip) says, `ignoreip` supports FQDN and this already long time (since v.0.9 IIRC).

As for dynamic IP, it would surely works too, just one needs to consider that due to performance purposes resolving of DNS will be mostly always cached by DNS servers (for unknown time), local network or host DNS resolver cache (for some short time).
Also fail2ban caches them internally for the same purposes, for maximal 5 minutes (since last resolve), and at the moment it is not yet configurable but fest coded...
https://github.com/fail2ban/fail2ban/blob/304c3cd56693c9ba90ace8b11c656ac2912648ca/fail2ban/server/ipdns.py#L80
So if the dynamic IP gets changed, it may have a certain latency before fail2ban gets new IP address for the DNS.
So it may be considered as a solution for sporadic failures from such DNS, but not really suitable by persistent error source (continuous failures from that hosts, happening often than at least every 5 minutes).
