### ISSUE TITLE
[FR]: SNMPv3 filters for Unknown User, Bad AUTH password and PRIV password, multiline, mutiple filters

### ISSUE THREAD

**Issue by prankurgit** [fail2ban/fail2ban#3767]
### Environment:

- Fail2Ban version  : v0.11.2
- OS, including release name/version : Debian 11

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : 
- Service, project or product name, including release name/version : snmpd (NET-SNMP version 5.9)
- Repository or URL (if known) : https://github.com/net-snmp/net-snmp
- Service type : systemd
- Ports and protocols the service is listening : 161, udp

#### Log or journal information

- Log file name(s) : journalctl -u snmpd

- Journal identifier or unit name : snmpd

#### Any additional information
* already try and implemented AUTH failure case from #3419 
* fail2ban-client status and fail2ban-regex matches but no effect observed,\
malicious user still gets immediate access even after being banned.
* to work with fail2ban also modified /etc/snmp/snmpd.conf i.e. extend a fail2ban perl script
* `echo 'extend fail2ban /etc/snmp/fail2ban' >> /etc/snmp/snmpd.conf`
* [Contents of /etc/snmp/fail2ban perl script](https://github.com/librenms/librenms-agent/raw/master/snmp/fail2ban)
* Question: how to add two more filters (as mentioned in the cases below) also how to modify the existing filter to match more than 2 lines ?

* Current snmpd filter /etc/fail2ban/filter.d/snmpd.conf 
```
[INCLUDES]

# Read common prefixes. If any customizations available -- read them from
# common.local
before = common.conf

[DEFAULT]

_daemon = snmpd

[Definition]
prefregex = ^\s*\S+ snmpd\[<F-MLFID>\d+</F-MLFID>\]: <F-CONTENT>.+</F-CONTENT>$
failregex = ^<F-NOFAIL>Connection</F-NOFAIL> from \w+: <ADDR>:\d+
            ^Authentication failed for <F-USER>\S+</F-USER>
ignoreregex =
journalmatch = _SYSTEMD_UNIT=snmpd.service + _COMM=snmpd
```

* Current jail /etc/fail2ban/jail.d/snmpd.conf
```
[snmpd]
enabled = true
port = 161
protocol = udp
filter = snmpd
findtime = 600
bantime = 600
maxretry = 5
backend = systemd
```

```
# fail2ban-client status snmpd -v
Status for the jail: snmpd
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     5
|  `- Journal matches:  _SYSTEMD_UNIT=snmpd.service + _COMM=snmpd
`- Actions
   |- Currently banned: 1
   |- Total banned:     1
   `- Banned IP list:   192.168.50.123
```

```
# fail2ban-regex systemd-journal snmpd

Running tests
=============

Use   failregex filter file : snmpd, basedir: /etc/fail2ban
Use      datepattern : {^LN-BEG} : Default Detectors
Use         systemd journal
Use         encoding : UTF-8
Use    journal match : _SYSTEMD_UNIT=snmpd.service + _COMM=snmpd

Results
=======

Prefregex: 2292 total
|  ^\s*\S+ snmpd\[(?P<mlfid>\d+)\]: (?P<content>.+)$
`-

Failregex: 569 total
|-  #) [# of hits] regular expression
|   1) [531] ^<F-NOFAIL>Connection</F-NOFAIL> from \w+: <ADDR>:\d+
|   2) [38] ^Authentication failed for <F-USER>\S+</F-USER>
`-

Ignoreregex: 0 total

Date template hits:

Lines: 2292 lines, 531 ignored, 38 matched, 1723 missed
[processed in 0.25 sec]
```

#### failures in sense of fail2ban filter (fail2ban must match):

* Case 1 : Unknown User
```
Jun 13 14:55:46 DUT-23 snmpd[757701]: Connection from UDP: [192.168.50.123]:49201->[192.168.30.23]:161
Jun 13 14:55:46 DUT-23 snmpd[757701]: usm: USM processing begun...
Jun 13 14:55:46 DUT-23 snmpd[757701]: usm: Unknown User(test)
```
* Case 2 : Bad AUTH password
```
Jun 13 13:03:29 DUT-23 snmpd[757701]: Connection from UDP: [192.168.50.123]:49201->[192.168.30.23]:161
Jun 13 13:03:29 DUT-23 snmpd[757701]: usm: USM processing begun...
Jun 13 13:03:29 DUT-23 snmpd[757701]: usm: match on user pca
Jun 13 13:03:29 DUT-23 snmpd[757701]: usm: Verification failed.
Jun 13 13:03:29 DUT-23 snmpd[757701]: Authentication failed for pca
```
* Case 3 : Bad PRIV password
```
Jun 13 13:03:44 DUT-23 snmpd[757701]: Connection from UDP: [192.168.50.123]:49201->[192.168.30.23]:161
Jun 13 13:03:44 DUT-23 snmpd[757701]: usm: USM processing begun...
Jun 13 13:03:44 DUT-23 snmpd[757701]: usm: match on user pca
Jun 13 13:03:44 DUT-23 snmpd[757701]: usm: Verification succeeded.
Jun 13 13:03:44 DUT-23 snmpd[757701]: usm: USM processing completed.
Jun 13 13:03:44 DUT-23 snmpd[757701]: security service 3 error parsing ScopedPDU
```

#### legitimate messages (fail2ban should not consider as failures):

* Case OK (correct User, AUTH and PRIV password)
```
Jun 14 09:01:49 DUT-23 snmpd[1401950]: Connection from UDP: [192.168.50.123]:49201->[192.168.30.23]:161
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: USM processing begun...
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: match on user pca
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: Verification succeeded.
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: boot_uint 0 myBoots 300 time_diff 372 => not in time window
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: USM processing has begun (offset 54)
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: getting user pca
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: match on user pca
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: USM processing completed.
Jun 14 09:01:49 DUT-23 snmpd[1401950]: Connection from UDP: [192.168.50.123]:49201->[192.168.30.23]:161
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: USM processing begun...
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: match on user pca
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: Verification succeeded.
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: USM processing completed.
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: USM processing has begun (offset 139)
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: Encryption successful.
Jun 14 09:01:49 DUT-23 snmpd[1401950]: usm: USM processing completed.
```

**Comment by sebres** [comment]
> fail2ban-regex matches but no effect observed

Regarding "Unknown User" and "Bad PRIV" messages, it does not really. It'd only match `Connection from` messages as no failure (and ignore them after all later) and single message `Authentication failed` (and ban only this one after `maxretry` failures occur during `findtime` interval).

For other cases why "no effect observed" try to find out in this [FAQ in wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) (answers to 1st or 2nd Q). I guess no UDP protocol specified for banning action or something similar.

As for another messages, here is your requested filter (it must match both additional failures with 2 new REs in failregex at end):
```ini
[Definition]
prefregex = ^\s*\S+ snmpd\[<F-MLFID>\d+</F-MLFID>\]: <F-CONTENT>.+</F-CONTENT>$
failregex = ^<F-NOFAIL>Connection</F-NOFAIL> from \w+: <ADDR>:\d+
            ^Authentication failed for <F-USER>\S+</F-USER>
            ^usm: Unknown User\(<F-USER>[^\)]*</F-USER>\)
            ^security service \d+ error parsing

ignoreregex =
journalmatch = _SYSTEMD_UNIT=snmpd.service + _COMM=snmpd
```

By the way you don't need `[INCLUDES]` with `[DEFAULT]` sections here, because no common substitutions used in the filter (in definition section) at all... so your whole filter may basically look like I provided here above.

**Comment by prankurgit** [comment]
Dear @sebres ,

Thanks for your fast and detailed response. I am really grateful.
I will check out the FAQs and try to understand why does the ban not work.
Is there some documentation that I can read for fail2ban-regex regarding multiple lines ?
So that in future I do not bother you guys and write it on my own.

Cheers
Prankur

**Comment by sebres** [comment]
[man jail.conf.5](https://manpages.debian.org/bookworm/fail2ban/jail.conf.5.en.html#FILTER_FILES_(filter.d/*.conf)) may help here.
But I'd also see several filters and examples here and in www (search phrase would be something like `"F-MLFID" multi-line filter`).

Best and simplest example excepting the issue #3419 (you already mentioned) could be probably #1966...

And the logic is very simple:
- having some common identifier (like session-id or pid/tid of process serving request), one could "group" several messages by this ID (with `<F-MLFID>`), in order to match a message with IP (that is not a failure) and message(s) without IP (but what is a failure basically).
- the helper message with IP (if it is not a failure), should get a RE-mark `<F-NOFAIL>...</F-NOFAIL>` capturing non empty string, so fail2ban will only store the combination ID with IP and knows which IP belongs to further failure messages (that don't have them).
- all other messages matching another REs with captured same `<F-MLFID>` get the same IP as that helper RE.
- the order of messages in log is irrelevant (the message with IP can be also after the failure), crucially is only the common ID the messages have.

That's it.

**Comment by prankurgit** [comment]
[SOLVED]
* for the last part of the puzzle were the iptables, after checking the /var/log/fail2ban.log file I understood that iptables was not installed on my machine.
* apt install iptables and then restarting the fail2ban make the ban successfull
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
f2b-snmpd  udp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 161

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain f2b-snmpd (1 references)
target     prot opt source               destination         
REJECT     all  --  MALCIOUS_IP       0.0.0.0/0            reject-with icmp-port-unreachable
RETURN     all  --  0.0.0.0/0            0.0.0.0/0 
```
