### ISSUE TITLE
How to protect Nginx container by Fail2Ban?

### ISSUE THREAD

**Issue by hack3rcon** [fail2ban/fail2ban#3770]
Hi,
I have an Nginx container. Do I need to install Fail2Ban on the container to protect it?

Thank you.

**Comment by sebres** [comment]
> Do I need to install Fail2Ban on the container to protect it?

If the emphasis of question is "install **on the container**" then the answer is one can do it on both sides:
- if installed in container, the filter and banning actions could work out of the box (however the Q is whether the IP you'd try to ban is from outside and it is possible to ban them behind the bridged network inside container)
- if installed on host, besides the question of IP, you've to configure the jail (and container) to access nginx logs or journal from fail2ban (so filter will work), as well as the banning action should get proper input chain configured (mostly `DOCKER-USER`), but it depends. See [wiki :: Fail2Ban and Docker](https://github.com/fail2ban/fail2ban/wiki/Fail2Ban-and-Docker) or details.

If the emphasis is like "Do I need to install Fail2Ban to protect nginx", it depends.
Fail2ban has stock filters (or actions) to protect against different attack vectors: 
- [nginx-http-auth](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/nginx-http-auth.conf) against authentications bruteforce attacks, that can be used out of the box by nginx auth module failures
- [nginx-limit-req](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/nginx-limit-req.conf) used to ban hosts, that were failed through nginx by limit request processing rate (or after #3674 by limit the number of connections), that will expect configuration on nginx side (`limit_req` and/or `limit_conn` and zones).
- [nginx-forbidden.conf](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/nginx-forbidden.conf) used to ban hosts generating forbidden errors
- other filters (e. g. against bots etc), although since they monitoring access-logs, it is questionable approach, see [wiki :: Best practice / Reduce parasitic log-traffic](https://github.com/fail2ban/fail2ban/wiki/Best-practice#reduce-parasitic-log-traffic) for details and better approach.

Often people use own jails/filters/failregex to protect own applications, however it depends on application, logging approach or the kind of use.

The question is too general, therefore firstly you've to choice or to determine which protection you may need and which attack vectors are important for you and need to be monitored and prevented.
There is no simple answer like yes or no, and simply by installing of fail2ban (and enabling of few jails) it is probably not solved.
Also if one has additionally to handle containerization questions (the chains, the IP proxying issues, etc). 
But even without containers there are many questions which are too specific and depends on many factors.
