### ISSUE TITLE
Unable to Configure Custom Log Parsing in fail2ban for Calibre-Web

### ISSUE THREAD

**Issue by jayabs2020** [fail2ban/fail2ban#3774]
I am writing to seek assistance with configuring fail2ban to properly parse logs from Calibre-Web. Despite numerous attempts and adjustments, I have been unable to get fail2ban to recognize and act on the relevant log entries.

Here’s a summary of the issue:
I am attempting to set up fail2ban to monitor logs generated by Calibre-Web, a web application for managing e-book libraries. The goal is to ban IP addresses that exhibit suspicious behavior indicated by specific log entries. Both calibre-web and fail2ban are running as docker containers. 

example log entry: 
```
[2024-06-24 22:35:41,543]  WARN {cps.web:1409} Login failed for user "test" IP-address: ::ffff:11.11.11.11
```
Fail2ban filter for Calibre-Web login failures
```
[Definition]
failregex = ^\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}\]  WARN \{cps\.web:\d+\} Login failed for user .* IP-address: ::ffff:<HOST>$
ignoreregex =
```
The contents of jail.d/calibre-web.conf is as follows, 
```
[calibre-web]
enabled = true
chain = FORWARD
filter = calibre-web
port = 8083
logpath = /calibre-web.log
maxretry = 3
findtime = 600
bantime = 3600
```
Thank you in advance for your help. I look forward to your response.

**Comment by sebres** [comment]
Here is your failregex:
```ini
failregex = ^(?:\[\])?\s*WARN \{[^\}]*\} Login failed for user "<F-USER>[^"]*</F-USER>" IP-address: <ADDR>
```

I did not inspect your RE, but main issue may be that you tried to match the part with a timestamp (it is not correct, because fail2ban cuts it out from message line before it start to process with failregex). 
See [man jail.conf.5](https://manpages.debian.org/stable/fail2ban/jail.conf.5.en.html#failregex~2):
<i>
**NOTE**: the `failregex` will be applied to the remaining part of message after `prefregex` processing (if specified), which in turn takes place after `datepattern` processing (whereby the string of timestamp matching the best pattern, cut out from the message).
</i>

**Comment by jayabs2020** [comment]
Thanks for the pointer, it works now 👍
