### ISSUE TITLE
[FR]: CVE-2024-6387 aka RegreSSHion filter?

### ISSUE THREAD

**Issue by ccheath** [fail2ban/fail2ban#3784]
### Environment:

- Fail2Ban version  v0.11.2
- OS, including release name/version : Ubuntu 22.04..4

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : sshd

#### failures in sense of fail2ban filter (fail2ban must match):
```
Jun 30 08:39:10 server sshd[287207]: fatal: Timeout before authentication for 120.52.152.112 port 34410
Jun 30 08:42:28 server sshd[287348]: fatal: Timeout before authentication for 116.147.40.93 port 50630
Jun 30 08:43:42 server sshd[287387]: fatal: Timeout before authentication for 116.147.40.93 port 32882
Jun 30 08:44:56 server sshd[287449]: fatal: Timeout before authentication for 116.147.40.93 port 43360
Jun 30 08:46:10 server sshd[287468]: fatal: Timeout before authentication for 116.147.40.93 port 53840
Jun 30 08:47:24 server sshd[287491]: fatal: Timeout before authentication for 116.147.40.93 port 36094
Jun 30 08:48:29 server sshd[287523]: fatal: Timeout before authentication for 154.83.15.94 port 58142
Jun 30 08:48:37 server sshd[287544]: fatal: Timeout before authentication for 116.147.40.93 port 46582
Jun 30 08:49:40 server sshd[287557]: fatal: Timeout before authentication for 154.83.15.94 port 41224
Jun 30 08:54:29 server sshd[287679]: fatal: Timeout before authentication for 154.83.15.94 port 41334
Jun 30 08:58:33 server sshd[287727]: fatal: Timeout before authentication for 154.83.15.94 port 58428
Jun 30 09:09:43 server sshd[290071]: fatal: Timeout before authentication for 154.83.15.94 port 41918
Jun 30 09:10:57 server sshd[290076]: fatal: Timeout before authentication for 154.83.15.94 port 53260
Jun 30 09:11:20 server sshd[290139]: fatal: Timeout before authentication for 222.186.10.55 port 55022
Jun 30 10:37:29 server sshd[293731]: fatal: Timeout before authentication for 123.139.158.75 port 2142
Jun 30 10:39:14 server sshd[293772]: fatal: Timeout before authentication for 123.139.158.75 port 2143
Jun 30 10:40:58 server sshd[293800]: fatal: Timeout before authentication for 123.139.158.75 port 2144
Jun 30 10:42:42 server sshd[293885]: fatal: Timeout before authentication for 123.139.158.75 port 2145
Jun 30 10:44:26 server sshd[293950]: fatal: Timeout before authentication for 123.139.158.75 port 2146
Jun 30 10:46:10 server sshd[293987]: fatal: Timeout before authentication for 123.139.158.75 port 2147
Jun 30 10:53:15 server sshd[294179]: fatal: Timeout before authentication for 123.139.158.75 port 2154
Jun 30 10:54:53 server sshd[294209]: fatal: Timeout before authentication for 123.139.158.75 port 2155
Jun 30 10:56:30 server sshd[294231]: fatal: Timeout before authentication for 123.139.158.75 port 2156
Jun 30 10:58:07 server sshd[294264]: fatal: Timeout before authentication for 123.139.158.75 port 2157
Jun 30 10:59:46 server sshd[294297]: fatal: Timeout before authentication for 123.139.158.75 port 2158
Jun 30 11:01:27 server sshd[294359]: fatal: Timeout before authentication for 123.139.158.75 port 2159
Jun 30 11:03:09 server sshd[296506]: fatal: Timeout before authentication for 123.139.158.75 port 2160
Jun 30 11:04:51 server sshd[296514]: fatal: Timeout before authentication for 123.139.158.75 port 2161
Jun 30 11:10:14 server sshd[296577]: fatal: Timeout before authentication for 123.139.158.75 port 2165
Jun 30 11:14:54 server sshd[296651]: fatal: Timeout before authentication for 123.139.158.75 port 2169
Jun 30 11:16:34 server sshd[296697]: fatal: Timeout before authentication for 123.139.158.75 port 2170
Jun 30 12:16:05 server sshd[299377]: fatal: Timeout before authentication for 106.13.208.11 port 52326
Jun 30 21:36:05 server sshd[325681]: fatal: Timeout before authentication for 116.198.216.58 port 58518
Jun 30 23:35:58 server sshd[332489]: fatal: Timeout before authentication for 119.5.157.124 port 37232
Jun 30 23:55:53 server sshd[333339]: fatal: Timeout before authentication for 124.47.36.58 port 45425
Jun 30 23:55:57 server sshd[333343]: fatal: Timeout before authentication for 117.34.71.28 port 56862
Jun 30 23:56:50 server sshd[333448]: fatal: Timeout before authentication for 101.36.111.53 port 33830
Jun 30 23:57:01 server sshd[333452]: fatal: Timeout before authentication for 124.47.36.58 port 49968
Jun 30 23:57:54 server sshd[333512]: fatal: Timeout before authentication for 117.34.71.28 port 44306
Jun 30 23:58:05 server sshd[333525]: fatal: Timeout before authentication for 124.47.36.58 port 54514
Jun 30 23:59:11 server sshd[333573]: fatal: Timeout before authentication for 124.47.36.58 port 59049
Jun 30 23:59:50 server sshd[333611]: fatal: Timeout before authentication for 117.34.71.28 port 59986
Jul  1 00:00:14 server sshd[333627]: fatal: Timeout before authentication for 124.47.36.58 port 35361
Jul  1 00:01:49 server sshd[333717]: fatal: Timeout before authentication for 117.34.71.28 port 47470
Jul  1 00:05:16 server sshd[336096]: fatal: Timeout before authentication for 124.47.36.58 port 58065
Jul  1 00:05:35 server sshd[336109]: fatal: Timeout before authentication for 117.34.71.28 port 50588
Jul  1 00:06:22 server sshd[336130]: fatal: Timeout before authentication for 124.47.36.58 port 34372
Jul  1 00:07:25 server sshd[336164]: fatal: Timeout before authentication for 124.47.36.58 port 38919
Jul  1 00:07:36 server sshd[336178]: fatal: Timeout before authentication for 117.34.71.28 port 38042
Jul  1 00:08:29 server sshd[336200]: fatal: Timeout before authentication for 124.47.36.58 port 43463
Jul  1 00:08:39 server sshd[336209]: fatal: Timeout before authentication for 117.34.71.28 port 45882
Jul  1 00:09:35 server sshd[336227]: fatal: Timeout before authentication for 124.47.36.58 port 48000
Jul  1 00:09:39 server sshd[336231]: fatal: Timeout before authentication for 117.34.71.28 port 53722
Jul  1 00:10:38 server sshd[336257]: fatal: Timeout before authentication for 124.47.36.58 port 52538
Jul  1 00:11:28 server sshd[336330]: fatal: Timeout before authentication for 117.34.71.28 port 41164
Jul  1 00:11:44 server sshd[336334]: fatal: Timeout before authentication for 124.47.36.58 port 57080
Jul  1 00:12:48 server sshd[336398]: fatal: Timeout before authentication for 124.47.36.58 port 33387
Jul  1 00:13:50 server sshd[336418]: fatal: Timeout before authentication for 124.47.36.58 port 37930
Jul  1 00:14:18 server sshd[336430]: fatal: Timeout before authentication for 117.34.71.28 port 36440
Jul  1 00:14:52 server sshd[336436]: fatal: Timeout before authentication for 124.47.36.58 port 42467
Jul  1 00:15:14 server sshd[336442]: fatal: Timeout before authentication for 117.34.71.28 port 44276
Jul  1 00:16:02 server sshd[336448]: fatal: Timeout before authentication for 124.47.36.58 port 47006
Jul  1 00:16:08 server sshd[336450]: fatal: Timeout before authentication for 117.34.71.28 port 52114
Jul  1 00:17:08 server sshd[336463]: fatal: Timeout before authentication for 124.47.36.58 port 51545
Jul  1 00:18:58 server sshd[336486]: fatal: Timeout before authentication for 117.34.71.28 port 47392
Jul  1 00:19:54 server sshd[336500]: fatal: Timeout before authentication for 117.34.71.28 port 55232
Jul  1 00:20:20 server sshd[336549]: fatal: Timeout before authentication for 124.47.36.58 port 36934
Jul  1 00:20:50 server sshd[336558]: fatal: Timeout before authentication for 117.34.71.28 port 34838
Jul  1 00:21:47 server sshd[336566]: fatal: Timeout before authentication for 117.34.71.28 port 42674
Jul  1 00:23:12 server sshd[336579]: fatal: Timeout before authentication for 124.47.36.58 port 50566
Jul  1 00:24:15 server sshd[336584]: fatal: Timeout before authentication for 124.47.36.58 port 55107
Jul  1 01:21:09 server sshd[339204]: fatal: Timeout before authentication for 36.137.249.148 port 60560
Jul  1 02:08:19 server sshd[341689]: fatal: Timeout before authentication for 121.196.208.112 port 36004
Jul  1 04:18:34 server sshd[348053]: fatal: Timeout before authentication for 106.12.111.140 port 54046
Jul  1 04:18:56 server sshd[348079]: fatal: Timeout before authentication for 106.12.111.140 port 56870
Jul  1 04:19:22 server sshd[348086]: fatal: Timeout before authentication for 106.12.111.140 port 59236
Jul  1 04:19:41 server sshd[348094]: fatal: Timeout before authentication for 106.12.111.140 port 33698
Jul  1 04:20:03 server sshd[348143]: fatal: Timeout before authentication for 106.12.111.140 port 36352
Jul  1 04:20:26 server sshd[348154]: fatal: Timeout before authentication for 106.12.111.140 port 38820
Jul  1 04:20:48 server sshd[348186]: fatal: Timeout before authentication for 106.12.111.140 port 41358
Jul  1 04:21:58 server sshd[348209]: fatal: Timeout before authentication for 106.12.111.140 port 49296
Jul  1 04:22:20 server sshd[348220]: fatal: Timeout before authentication for 106.12.111.140 port 52122
Jul  1 04:23:02 server sshd[348234]: fatal: Timeout before authentication for 106.12.111.140 port 57128
Jul  1 04:23:21 server sshd[348243]: fatal: Timeout before authentication for 106.12.111.140 port 59734
Jul  1 04:23:41 server sshd[348250]: fatal: Timeout before authentication for 106.12.111.140 port 34114
Jul  1 04:24:03 server sshd[348254]: fatal: Timeout before authentication for 106.12.111.140 port 36728
Jul  1 04:24:26 server sshd[348261]: fatal: Timeout before authentication for 106.12.111.140 port 39310
Jul  1 04:25:06 server sshd[348271]: fatal: Timeout before authentication for 106.12.111.140 port 44550
Jul  1 04:25:28 server sshd[348279]: fatal: Timeout before authentication for 106.12.111.140 port 47130
Jul  1 04:25:48 server sshd[348282]: fatal: Timeout before authentication for 106.12.111.140 port 49706
Jul  1 04:26:27 server sshd[348300]: fatal: Timeout before authentication for 106.12.111.140 port 55168
Jul  1 04:26:47 server sshd[348304]: fatal: Timeout before authentication for 106.12.111.140 port 57160
Jul  1 04:27:08 server sshd[348324]: fatal: Timeout before authentication for 106.12.111.140 port 60198
Jul  1 04:27:28 server sshd[348328]: fatal: Timeout before authentication for 106.12.111.140 port 34382
Jul  1 04:27:51 server sshd[348334]: fatal: Timeout before authentication for 106.12.111.140 port 37282
Jul  1 04:28:11 server sshd[348383]: fatal: Timeout before authentication for 106.12.111.140 port 39798
Jul  1 04:28:35 server sshd[348387]: fatal: Timeout before authentication for 106.12.111.140 port 41940
Jul  1 04:57:55 server sshd[348765]: fatal: Timeout before authentication for 101.126.69.23 port 36132
Jul  1 04:58:59 server sshd[348776]: fatal: Timeout before authentication for 103.44.237.68 port 37718
Jul  1 04:59:59 server sshd[348815]: fatal: Timeout before authentication for 103.44.237.68 port 46236
Jul  1 05:01:59 server sshd[348920]: fatal: Timeout before authentication for 103.44.237.68 port 35030
Jul  1 05:04:01 server sshd[351081]: fatal: Timeout before authentication for 103.44.237.68 port 52062
Jul  1 05:04:59 server sshd[351115]: fatal: Timeout before authentication for 103.44.237.68 port 60570
Jul  1 05:10:58 server sshd[351297]: fatal: Timeout before authentication for 101.126.69.23 port 42236
Jul  1 05:12:17 server sshd[351374]: fatal: Timeout before authentication for 103.44.237.68 port 55260
Jul  1 05:13:19 server sshd[351396]: fatal: Timeout before authentication for 103.44.237.68 port 35550
Jul  1 05:14:16 server sshd[351411]: fatal: Timeout before authentication for 103.44.237.68 port 44076
Jul  1 05:16:06 server sshd[351488]: fatal: Timeout before authentication for 103.44.237.68 port 32868
Jul  1 05:17:15 server sshd[351509]: fatal: Timeout before authentication for 103.44.237.68 port 41394
Jul  1 05:21:05 server sshd[351573]: fatal: Timeout before authentication for 103.44.237.68 port 47224
Jul  1 05:22:00 server sshd[351588]: fatal: Timeout before authentication for 103.44.237.68 port 55734
Jul  1 05:23:04 server sshd[351606]: fatal: Timeout before authentication for 103.44.237.68 port 36018
Jul  1 05:24:00 server sshd[351637]: fatal: Timeout before authentication for 103.44.237.68 port 44530
Jul  1 05:24:57 server sshd[351687]: fatal: Timeout before authentication for 103.44.237.68 port 53040
Jul  1 05:25:46 server sshd[351692]: fatal: Timeout before authentication for 101.126.69.23 port 46630
Jul  1 05:25:53 server sshd[351696]: fatal: Timeout before authentication for 103.44.237.68 port 33326
Jul  1 05:26:50 server sshd[351702]: fatal: Timeout before authentication for 103.44.237.68 port 41836
Jul  1 11:18:55 server sshd[369682]: fatal: Timeout before authentication for 183.36.126.68 port 41754
Jul  1 11:20:30 server sshd[369706]: fatal: Timeout before authentication for 182.61.18.107 port 40106
Jul  1 11:20:58 server sshd[369713]: fatal: Timeout before authentication for 171.104.141.57 port 37840
Jul  1 11:24:42 server sshd[369939]: fatal: Timeout before authentication for 139.227.46.101 port 38930
Jul  1 11:25:40 server sshd[369959]: fatal: Timeout before authentication for 139.227.46.101 port 45224
Jul  1 11:28:34 server sshd[370043]: fatal: Timeout before authentication for 139.227.46.101 port 37262
Jul  1 11:29:04 server sshd[370051]: fatal: Timeout before authentication for 139.227.46.101 port 40094
Jul  1 11:29:33 server sshd[370069]: fatal: Timeout before authentication for 139.227.46.101 port 43482
Jul  1 11:31:22 server sshd[370151]: fatal: Timeout before authentication for 139.227.46.101 port 56554
Jul  1 11:32:33 server sshd[370223]: fatal: Timeout before authentication for 139.227.46.101 port 34874
Jul  1 11:35:29 server sshd[370318]: fatal: Timeout before authentication for 139.227.46.101 port 54448
Jul  1 11:36:29 server sshd[370346]: fatal: Timeout before authentication for 139.227.46.101 port 32938
Jul  1 11:37:57 server sshd[370382]: fatal: Timeout before authentication for 139.227.46.101 port 42884
Jul  1 16:59:26 server sshd[385439]: fatal: Timeout before authentication for 14.103.19.145 port 46310

```

#### legitimate messages (fail2ban should not consider as failures):

```
n/a ?
```

**Comment by ccheath** [comment]
was going to try to make my own filter, but figured this was something that someone might have already done or asked for and couldn't find it so I figured that I would submit this issue...

if the filter isn't something that is going to get added instructions to create my own would be nice to (or a link to somewhere that explains how to make your own)

thanks

**Comment by fdellwing** [comment]
> fatal: Timeout before authentication for 14.103.19.145 port 46310

This is not a new log message with OpenSSH 9.8.

**Comment by ccheath** [comment]
correct, it is not a new log message, but it should be taken as an indication of attempt to breach and logged as bannable offense, right?

**Comment by ox42** [comment]
> CVE?! Seriously?

@sebres I think the spirit of the question is to ask if the default configuration of fail2ban prevents this vulnerability https://blog.qualys.com/vulnerabilities-threat-research/2024/07/01/regresshion-remote-unauthenticated-code-execution-vulnerability-in-openssh-server ?

As one of the solutions is to have proper Intrusion Detection, i think it's a fair question to know if most setups of fail2ban prevent this bug or not.

**Comment by sebres** [comment]
Regarding CVE-2024-6387 (aka RegreSSHion) or a regression for fixed CVE-2006-5051 of OpenSSH...

I don't think it has here even a bit to do with that CVE or somehow concerning this matter, just because mentioned CVEs imply remote race condition (but you see a timeout here)... I hope it is clear for everyone what race condition basically means (emphasis on word "race").

Let alone to use it with some chance of success there are many factors:
- x86 architecture (no known x64 exploits, I guess because of ASLR, what is on by default for x64 and IIRC for ARM or ARM64cannot be disabled at all);
- GSSAPI (or other PAM similar) authentications must be enabled (and long dancing with a tambourine around SIGALRM handlers & co are expected)
- unpatched SSHD version 8.5p1 ... 9.7p1 (a lot of distros provided an update for them already)
- mentioned race condition (without to get banned by IDS)
- a lot of luck, etc

**Comment by sebres** [comment]
> a fair question to know if most setups of fail2ban prevent this bug or not.

Unfortunately, it is hard to answer (even more difficult to predict)...
Because to know whether one is not affected by this "bug", he'd need to consider all theoretical variants of exploits (what is hardly possible)... Especially because the evildoers are creative and what is imaginable today as an exploit scenario may be completely different tomorrow or even misuse totally different vector.

I can only say that `mode = aggressive` would have surely more chances for prevention than default `mode = normal`, although one has to accept certain probability for false positives, even because the filter is more aggressive, and could theoretically ban legitimate users by certain circumstances (for instance by unstable connections).
As many other things it is to check individually.

**Comment by ccheath** [comment]
using aggressive mode did not catch these attempts (i tried that before posting this issue)
I ended up adding ```^Timeout before authentication for <HOST>``` to ```cmnfailre``` in ```filters.d/sshd.conf``` and that seems to have caught these

as for being implemented in a new version... that doesn't help those who use a distribution that hasn't updated the package in their repo

thanks

**Comment by sebres** [comment]
> using aggressive mode did not catch these attempts

And I guess that you found out why...

> i tried that before posting this issue

What you did not tried before posting is to search (google, GH, etc) whether it is already implemented.

> that doesn't help those who use a distribution that hasn't updated the package in their repo

Although this is known problem, but as already said, it is not critical vector, so I understand the maintainers (that may be busy with other stuff or spend their time on other tasks with higher priorities).
4f679a56e0d564bafa7781938f8d28bb69fd96af is released in [1.1.0](https://github.com/fail2ban/fail2ban/releases/tag/1.1.0), what is relative fresh yet. I think our deb-package (released here) is installable on 22.04, however I cannot guarantee 100% compatibility (regarding default filters and backends), so one'd probably need some manual configuration changes.

Anyway it is a bit strange to complain open source community (no matter us or the distro maintainers) for something like that.

**Comment by ccheath** [comment]
I did search first to find out if it was implemented but couldn't find the answer so I came here
_(this page is now the third google result for 'fail2ban regreSSHion' after reddit and splunk, so hopefully others who search can get their answer now)_
I then searched this repo and couldn't find the answer, hence this issue
sure there's going to be some over-hype, but with all of the big news about this CVE saying it's not critical seems a bit complacent
I'm not complaining, just trying to maintain security of my server

**Comment by sebres** [comment]
> I did search first to find out if it was implemented but couldn't find the answer so I came here

What exactly? 
- the timeout RE? - it is pretty obvious and a simple search (also on [GH](https://github.com/search?q=repo%3Afail2ban%2Ffail2ban%20sshd%20%22Timeout%20before%20authentication%22)) would immediately show an answer here.
- the special protection against regresshion on side of f2b? - I explained [above](https://github.com/fail2ban/fail2ban/issues/3784#issuecomment-2207038195) why it is hardly possible without to know  specific details.

> sure there's going to be some over-hype, but with all of the big news about this CVE saying it's not critical seems a bit complacent

Who said that mentioned CVE were not critical? Moreover nobody would call a vulni with potential for RCE with root privileges as uncritical.
I just [said](https://github.com/fail2ban/fail2ban/issues/3784#issuecomment-2207016971) what I said: I'm really unsure the timeouts messages you see are really a result of the exploit attempt... moreover I doubt it is, because:
- timeout is surely reverse condition to the race (especially considering that more than 10K attempts would be needed)
- the timeouts could also be caused by bans of fail2ban itself (in this case you'll see a lot `already bannded` in fail2ban.log after you appended the RE).

As well as I have provided my current state of knowledge about CVE itself (what at the same time is just my opinion and nobody can tell you with 100% probability whether and how it being used by the offenders)... 
Although I'm sure details of CVE got published firstly after lot of distros updated openssh-server or provided the patch.
In your particular case it is [1:8.9p1-3ubuntu0.10](https://launchpad.net/ubuntu/+source/openssh/1:8.9p1-3ubuntu0.10) (published on 2024-07-01), see https://ubuntu.com/security/notices/USN-6859-1 .

The mentioned race condition with the large count of attempts, very precise timing to hit the race condition window (very crucial but complex on busy hosts or machines with few cores, especially virtual) result to effectively challenging complexity for some possible exploit, what'd mean that the vulnerability is hardly usable for successful attacks, let alone it'd require a high level of skill, perseverance and a lot of luck above.
If one'd consider architectures like x64 or ARM only, it'd additionally become still more challenging due to stronger ASLR of that platforms.

Additionally, I can tell you that friends of me, having a honeypot behind of vulnerable ssh-server, standing under persistent attacks, didn't notice any unauthorized access and the logs of the ssh-server don't show something especially conspicuous, what could be explained by this particular attack-vector only, however only from the perspective of current state of knowledge we have about theoretical exploit for that (signal handler race condition, etc). But... as already said, the evildoers are creative and what they could really invent... who knows.

**Comment by ccheath** [comment]
got it, thanks for the further explanation
