### ISSUE TITLE
[FR]: endlessh

### ISSUE THREAD

**Issue by stellarpower** [fail2ban/fail2ban#3789]
[Endlessh]( https://github.com/skeeto/endlessh ) is a standalone SSH tarpit. After moving the SSH server to a non-standard port, it would generally be stood up on 22 and exploits the fact that the client will wait as long as it takes to receive the server's banner without hanging up automatically. endlessh thus sends random lines very very slowly in order to annoy malicious users and slow down the efficacy of botscripts by leaving them hanging (possibly infinitely) with this dummy server. 

I think combining this with fail2ban is ideal. Assuming all admin users know not to connect to 22 on a machine where a tarpit is installed, then basically any IP attempting connection can be assumed malicious - or at best, unauthorised - and therefore it would warrant closing off all ports to those IPs for a reasonable amount of time. I also think, many connections will just be from some script hosted in a datacentre, and the aim is to bog that bot down and make the attack less profitable. But, if someone were to try a targetted attack against a specific server, i.e. an interactive user, then the tarpit is designed to frustrate that person. They might now be more determined to win over and spend more time attacking our machine in other ways. I've seen reddit comments where people are worried about the possibility of a backfire compared to just closing off 22 and leaving it at that. I therefore think the ability to slot endlessh into fail2ban is quite important, as it allows us to take extra measures in case someone really gets annoyed. And as mentioned, I think the chances of a legitimate user connecting on a system where it's decided it's been worth installing the tarpit are low - so almost all, if not all, connection attempts we can consider malicious.

Note, there is already [a different project](https://github.com/itskenny0/fail2ban-endlessh) combining endlessh with fail2ban, but this instead forwards malicious users into the tarpit after they have already been banned from some other service. Conversely, I am suggesting adding a filter rule to detect connections to the tarpit itself and then block that IP from other services.

I've implemented a basic filter [in my fork](https://github.com/stellarpower/fail2ban/tree/stellarpower.AddFeature.EndlesshFilter) that detects connection opens/closes from endlessh. There's a bit of a tradeoff - on my setup, it seems that triggering the ban on a connection open doesn't interrupt that connection. Once a user falls into the tarpit, I close off all ports for an amount of time I deem reasonable given that the IP might recycle to a genuine visitor. But this may not be the case for other OSs or other ban methods, I leave it to someone more learned to comment on if there's a risk the initiating connection might be cut off, which is not what we want with a tarpit - as long as a malicious script is stuck, we waste its time and stop it targetting other systems, protecting other users worldwide in the process.

This is really a starting point - it currently works for me, so I'm providing it as-is in case someone else who knows fail2ban much better and has the time to contribute is happy to finish it off and polish it sufficiently for inclusion.

### Environment:

- Fail2Ban version:  1.0.2-1 from the main Lunar repository.
- OS, including release name/version : Ubuntu 23.04

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : not already present
- Service, project or product name, including release name/version : TEsted on version 1.1-5
- Repository or URL (if known) : https://github.com/skeeto/endlessh
- Service type : Security
- Ports and protocols the service is listening : Generally 22 but this can be changed and obviously is not safe to have enabled by default after installing fail2ban. endlessh itself defaults to 2222, I think probably because it would be a bad idea to have it default to 22 when installing, and not because 2222 is the most sensible port to use.

#### Log or journal information

- Journal identifier or unit name : endlessh

#### Any additional information
The verbosity defaults to 0 (quiet), and this does not log IPs. 1 Has proven sufficient to log connections without a load of debug info. So users need to make sure endlessh is configured accordingly for the protection to work

#### failures in sense of fail2ban filter (fail2ban must match):

```
Jul 08 16:03:11 ns311210 endlessh[1689464]: 2024-07-08T16:03:11.408Z ACCEPT host=::ffff:1.2.3.4 port=62934 fd=7 n=4/4096
Jul 08 16:03:41 ns311210 endlessh[1689464]: 2024-07-08T16:03:41.409Z CLOSE host=::ffff:1.2.3.4 port=62934 fd=7 time=30.001 bytes=39
```
Please see comments in the conf file - endlessh can urn in v4, v6, or v4/v6 mode. It may be fail2ban can handle this automatically just extracting the host.

#### legitimate messages (fail2ban should not consider as failures):
None really; the rest is startup noise. Assuming that we want to ban anyone falling into the tarpit for some time, then I assume if we see an IP address, ban it.

**Comment by sebres** [comment]
Just for the record, to provide better RE (anchored and without catch-alls)...

```diff
- failregex = ACCEPT.*host=<HOST>[\s]+port
+ failregex = ^\s*\S+ endlessh\[\d+\]: (?:\d{4}\S* )?ACCEPT host=<ADDR>
```

If both messages must be counted as an attempt (don't know why, but you provided both as failures in excerpt):
```ini
failregex = ^\s*\S+ endlessh\[\d+\]: (?:\d{4}\S* )?(?:ACCEPT|CLOSE) host=<ADDR>
```

By the way, I don't follow the idea with a tarpit which clients shall become banned at the same time.
In this case one doesn't really need a tarpit (endlessh) at all - it'd be enough to consider connection attempts on closed port, like https://github.com/fail2ban/fail2ban/issues/1945#issuecomment-362247222 and then ban them hereafter.

Tarpits, honeypots and other similar things follow normally a bit different approach and serve the needs of deception or confusion, but also analysis or info accumulation. Or like in case of endlessh to keep the clients locked up by receiving a slow "banner"...
Neither it expecting an additional ban thereby (it is like a ban by itself, just instead of drop/reject, it is masquerading as very slow ssh-server), nor both together makes a sense for me. 
Let alone this approach wouldn't distinguish "legitimate" users (for instance just mixed-up the ports or IP) with real evildoers (bruteforcing passwords or exploiting another attack vectors).

**Comment by stellarpower** [comment]
Hi,

- I started with an anchored regex, but removed it later since I didn't see a need for it. The logs only cover one line, unless fail2ban is reading the whole file every time; I assumed line-based processing and the "host" keyword anchors it
- We don't need both messages, but the tarpit is operating effectively if the client never disconnects - so we don't get a connection closed log because they're still stuck. We want the client to fall in and never come out unless we reboot the server, as that wastes their time the most. However, I don't know if banning the IP will affect current connections. AFAIK it doesn't on Linux, but I don't know about other OSs that fail2ban supports, and some people might not be using the iptables/equivalent action. So ideally we want to ban any future access on connection but also never cut that first connection.
- the server I have tried this on is one that is effectively only administered by me. Only two others have keys on there and aren't that likely to log in anyway. I think this setup would apply to many users who self-host. They want to administer their machine remotely, but nobody else is going to log in. So we can assume that anyone arriving at port 22 who doesn't know that ssh isnt really on there is malicious. The rule I have set up is then to block everything for that IP for some time - web, mail, etc. After I implemented this, I discovered CrowdSec - so as you mention, accumulating data could be valuable, as we can donate info on these IPs to the community at large to help track malicious users and then other systems can block those IPs too. I know there's a 95+%  chance anyone getting stuck in the tarpit has malicious intentions.
- what you say on closed ports makes sense, I didn't know that was an option. Although also the tarpit helps protect other users who expose public services by drawing the scripts away from other systems that might not be protected. Same as scambaiters, by laying a honeypot we help protect others who might be more vulnerable by frustrating their efforts. I'm considering not just my machines but others in this too. If they can port-scan say 60 IPs an hour then if they get stuck in the pit overnight that's a lot of servers that might not have vulnerabilities exposed. By integrating with fail2ban I feel comfortable that whoever started that script isn't going to be able to retaliate by trying to attack my machines in detail when otherwise they'd just have moved on.

Hope that makes sense.

I guess also, I think I see it as user choice. If there's no harm by adding an additional filter, then might as well add it. Obviously time testing and maintaining it is part of that, but, if someone else out there wants to run the same setup, they have the choice. If they don't see the logic, they don't need to. I decided to, hence I've uploaded what I have, but I don't want to make an assumption that's false and open a PR that works on my machine but has problems in it. So up to the maintainers if they want to take it or not, the fork is there for anyone that does.

**Comment by sebres** [comment]
> I started with an anchored regex, but removed it later since I didn't see a need for it.

You may do what you want, but we would not accept such "vulnerable" filters in this repository and I wanted also emphasize it for others which could read it or warn them against copy&paste. There are many arguments why such REs are bad, but I'll not repeat that everything here, because I consider the whole approach for useless (or even disturbing).

> but the tarpit is operating effectively if the client never disconnects

Questionable (from point of view of the host resources, like free ports, see below)...
But then it is still more confusing and contradicting - why do you want to put fail2ban in this chain (to disconnect them)?

> the server I have tried this on is one that is effectively only administered by me...

Then I don't understand the needs of endlessh in your case completely. It'd simply generate unneeded load on the host or its net-subsystem and has no advantages against simple monitoring of closed port (no matter port scanners or ssh-brutforcer).

> Although also the tarpit helps protect other users who expose public services by drawing the scripts away from other systems that might not be protected. 

Conditionally, because the bots have mostly a timeout and it'll continue few minutes latter.
But more or less such "protection" happens on your costs - every connection to such tarpit will simply reserve a port on your host (and you've only max 65K free ports less few K reserved ports and few K ports serving TCP/IP stack needs, like hanging on half-open or half-closed connections and waiting for SYN or FIN packets).

Also it is somehow contradicting approach - from one side you'll make this "protection" for others with a tarpit, from other side you want to reject or drop the connections with fail2ban, what would neglect the former completely.

Anyway that is questionable argument, in my opinion.

> I guess also, I think I see it as user choice

Sure, just I'd not like to "advertise" it indirectly by providing a filter for this weird approach in stock fail2ban.
Sorry, but no, not here.

**Comment by stellarpower** [comment]
That's precisely what I am saying, if you read my comments - I do not want to drop the current connection but block any and all future connections from that IP (within a sensible time limit as IPs recycle). The current setup I have achieves this on my system. If the bots are well-written, they should timeout. But they aren't, and currently, the average time wasted is 15 minutes for what ought to be roughly a 30-second job, so that's 30 other systems they havent managed to scan in that time using a very small amount of resources on my machine. Anyway, fine if you don't want it, CrowdSec looks like it's just better so I'll be deploying that in future instead of fail2ban. Using that I can pre-emptively ban bad users without needing them to have even visited my system before, and equally I can share with them the IPs in the pit so that others can ban them as long as rogue behaviour is detected as well.

**Comment by sebres** [comment]
> I do not want to drop the current connection but block any and all future connections from that IP

This is completely depending on net-filter, network configuration and/or used banning action.
Some of them would drop the established connections too, another would reject all new packets from IP (in this case it'd also reject the established connections sooner or later, since keepalive packets would not arrive anymore (see how [TCP keepalive](https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html) works).
Your approach would basically work only with those who refuse new connections only and do not touch established connections at all.

> the average time wasted is 15 minutes for what ought to be roughly a 30-second job, so that's 30 other systems they havent managed to scan in that time using a very small amount of resources on my machine

This "very small amount of resources" is also valid for the other side.
Have you ever heard about multi-threading or multi-processing? The only restriction that they have is free number of ports, the hanging connections don't bother their systems at all.
But since such attacks are almost never happen from single machine (rather they are whole botnets), the approaches with a tarpits like that are predestined to fail, because a botnet with N machines have N times more free ports than yours.
Basically this means that an attack of a botnet with ca. 6K infected devices by default maxretry (5) could consume the half of free ports of your server. Because you have 2 listener (one in tarpit and another in real ssh-server), this amount would be even enough to reach full TCP/IP-port exhaustion.
A bit more clever attack (for example all machines simultaneously) would be able to create much more connections than maxretry allows, before the attempts get logged and the IPs become detected and banned (because this is not instant process), so a port exhaustion is possible with 1K botnet or even smaller.

> Using that I can pre-emptively ban bad users without needing them to have even visited my system before

The approach with preventive banning is even more worse than your approach with a tarpit for a number of obvious reasons.
Thus good luck with that.

**Comment by stellarpower** [comment]
> This is completely depending on net-filter, network configuration and/or used banning action.

Hence two regular expressions. Banning on connection is working for me, it may not on someone else's machine, which is why I added a comment.

If someone really wants to try and exhaust the number of possible ports on one of my machines then I expect they'll find a way to do that irrespective of any tarpit or SSH. Triggering fail2ban from some other application is never going to stop a massive targeted DDOS attempt. But most of the spam I see is some script just scanning everything on the public Internet looking for vulnerabilities. The aim is to slow down the amount of information they extract, not to try and exhaust their system. And with CrowdSec, who as it turns out already have a connection for endlessh, share that activity with others so they can ban them too.

I'm also not sure what these obvious reasons are. If someone else detects a bot from a data centre port mapping their server then there's almost no legitimate reason they'd be trying to access any of my servers. I want them shut out for as long as malicious activity is flagged on that IP, simple as. There's no advantage for me to have them connect to my machine and trigger something first. If you see someone across the street punching someone, don't let them into your bar in order to find out.

Anyway, I see no need to continue this discussion.

**Comment by sebres** [comment]
> Banning on connection is working for me, it may not on someone else's machine

I think you didn't understand my explanation what word "banning" could mean and what a consequences it has for this kind of tarpit.

> If someone really wants to try and exhaust the number of possible ports on one of my machines then I expect they'll find a way to do that irrespective of any tarpit or SSH

It is not about intentional DDoS, it is something about occasional port exhaustion, which may be caused by usage of such tarpits.

> I'm also not sure what these obvious reasons are.

Think about:
- how many IPv4 and especially how many IPv6 exist across the world
- pure dynamic IPs
- devices got vulnerable yesterday but fixed today or tomorrow
- possible extra load for a net-filter caused by preventive banning with IDS (by potentially million of addresses)
- etc

> If you see someone across the street punching someone, don't let them into your bar in order to find out.

Don't confuse real world with internet, e. g. someone across the ocean cannot enter your bar, there are simply too few candidates compared to count of potentially vulnerable devices. Regardless why you think the door of your bar is firewall or auth-service behind the listener.

> Anyway, I see no need to continue this discussion.

Indeed.
