### ISSUE TITLE
[FR]: Latest openssh changed how sshd deamon logs access failures - fail2ban stopped banning sshd logins

### ISSUE THREAD

**Issue by skibbipl** [fail2ban/fail2ban#3812]
### Environment:

- Fail2Ban version  : 1.1.0
- OS, including release name/version : debian unstable

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : sshd
- Service, project or product name, including release name/version : 
- Repository or URL (if known) : 
- Service type : 
- Ports and protocols the service is listening : 

#### Log or journal information
```
sie 02 17:38:19 xxxx sshd-session[1220961]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=189.195.123.54  user=root
sie 02 17:38:21 xxxx sshd-session[1220961]: Failed password for root from 189.195.123.54 port 37470 ssh2
sie 02 17:38:22 xxxx sshd-session[1220961]: Received disconnect from 189.195.123.54 port 37470:11: Bye Bye [preauth]
sie 02 17:38:22 xxxx sshd-session[1220961]: Disconnected from authenticating user root 189.195.123.54 port 37470 [preauth]
```

- Log file name(s) : systemd

- Journal identifier or unit name : ssh.service

#### Any additional information
Accoring to news:
```
sshd(8): several log messages have changed.  In particular, some log
messages will be tagged with as originating from a process named
"sshd-session" rather than "sshd".
```

**Comment by sebres** [comment]
See #3782 (already fixed and merged)

**Comment by vinc17fr** [comment]
> See #3782 (already fixed and merged)

This just changes `_daemon = sshd` to `_daemon = sshd(?:-session)?`, but this is not sufficient for Debian's fail2ban package. I've eventually found out that `journalmatch` was also incorrect: `_SYSTEMD_UNIT=sshd.service` needs to be changed to `_SYSTEMD_UNIT=ssh.service`. This was fixed in 6fce23e7baa484c7d1f9b0c9a11986f3916c41dd, but this is not in Debian yet. See the [Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1078208) I had reported (due to this other bug, it is possible that fail2ban got broken before OpenSSH 9.8 became available in Debian, but I noticed the issue only a few days ago, while I was looking at the journal for a bug with another software).

**Comment by sebres** [comment]
Yes, the issue with systemd-unit is well known... However since they seems to be called diffirently everywhere, there is no good solution for stock fail2ban here, excepting patch per distro by maintainers (or by user in local config), see https://github.com/fail2ban/fail2ban/issues/3747#issuecomment-2223483868

@sylvestre wanted to fix it for debian (https://github.com/fail2ban/fail2ban/issues/3747#issuecomment-2122411188), but it looks unchanged.

My plan was firstly to revert 6fce23e7baa484c7d1f9b0c9a11986f3916c41dd in master, but put it to debian branch here.

**Comment by sylvestre** [comment]
sorry, i dropped the ball on this. I will upload a new version with this change:
https://salsa.debian.org/python-team/packages/fail2ban/-/commit/f019de0bc2f633aedb7e2d995aeac43ff6195589
