### ISSUE TITLE
[BR]: Placeholder in action is filled incorrectly

### ISSUE THREAD

**Issue by ipod86** [fail2ban/fail2ban#3825]
I created the following action:

```
[Definition]

actionban =   printf %%b "Subject: [Fail2Ban] <name>: BANNED IP <ip>!
              Date: `LC_ALL=C date +"%%a, %%d %%h %%Y %%T %%z"`
              From: <sendername> <<sender>>
              To: <destination>\n
              Hi,\n
              The jail <name> has banned ip <ip> after <failures> attempts against <name> .\n
              Here is some info about the IP: https://db-ip.com/<ip> \n
              Regards,\n
              Fail2Ban" | <mailcmd> <destination>
```

I use the action to send an email. This works wonderfully. However, the second time <name> is repeated, the following is always inserted: The first 4 letters of the name, then an = and then a new line with the rest of the name. For example:

```
Hi,



The jail pingvin has banned ip 192.168.99.83 after 5 attempts against ping=

vin.
```

**Comment by sebres** [comment]
Hmm, weird... I guess it is not an issue of fail2ban... maybe something with your mail subsystem (e. g. hard wrapping)... 
Because `<name>` is not dynamic interpolation (since the constants would be replaced at the config read time)...
What do you see with:
```bash
fail2ban-client --dp | grep 'attempts against'
```
I guess the name is substituted directly inside the message: And you'd see something like `... attempts against pingvin`.
So the mail command would get it as pure plain/text.
