### ISSUE TITLE
[FR]: Nginx-apolapollo.conf log regular expression requirements

### ISSUE THREAD

**Issue by suixhxy** [fail2ban/fail2ban#3874]
Hello, big God

I have a need:

tail -f  /var/log/nginx/apollo.access.log

Monitor an nginx log in the following format:
```
{" http_host ":" apollo-portal.xxxxxxx.com ", "remote_addr" : "123.5.42.99", "remote_user" : ""," time_local ": "06/Nov/2024:17:18:47 +0800", "request": "GET /vendor/angular/ angular-resource-min.js.map HTTP/2.0", "status": 404, "body_bytes_sent": 147, "http_referer": "", "http_user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64;  x64;  rv:131.0) Gecko/20100101 Firefox/131.0", "http_x_forwarded_for": ""," request_time ":" 0.009 ", "request_body" : ""," upstream_response_time ":" 0.010 ", "star_jwt" : ""}
```
This log is the password input error generated, I want to achieve password 3 errors on the interception ip, this re should be written how?
My version of fail2ban is Fail2Ban v0.9.4
1、
```
vim  /etc/fail2ban/jail.conf
[nginx-apollo]
enabled = true
port = http,https
filter = nginx-apollo
logpath = /var/log/nginx/apollo.access.log
action = iptables-multiport[name=404,port="http,https",protocol=tcp]
# action = firewallcmd-ipset[name=404,port="http,https",protocol=tcp]
maxretry = 3
findtime = 300
bantime = 7200
```
2、
vim  /etc/fail2ban/filter.d/nginx-apollo.conf
```
[Definition]
failregex = ^<HOST>.*"(GET|POST).*" (404|444|403|400) .*$
ignoreregex =
```
This failregex is incorrect. How should the correct failregex be written?

Please help answer, thank you very much。

**Comment by sebres** [comment]
Similar issue - https://github.com/fail2ban/fail2ban/issues/3456#issuecomment-1427114645

Although there was a bit different format, so here you go:
```ini
[Definition]

datepattern = "time_local":\s*"%%d/%%b/%%Y:%%H:%%M:%%S(?: %%z)?",\s*

_groupre = (?:"(?!(?:remote_addr|request|status)\b)\w+"\s*:\s*(?:"[^"]*"|\w+)\s*[,\}]\s*)

_uri = [^"]+
_code = [45]0\d

failregex = ^\{%(_groupre)s*"remote_addr"\s*:\s*"<ADDR>",\s*%(_groupre)s*"request"\s*:\s*"%(_uri)s",\s*%(_groupre)s*"status"\s*:\s*"?%(_code)s"?
```
Assuming typos or manually redacting by spaces for single tag names, like `" time_local "` vs `"time_local"`.
If it is really with spaces in the log, you have to add `\s*` everywhere for parameter names, like:
```diff
- datepattern = "time_local":\s*"%%d/%%b/%%Y:%%H:%%M:%%S(?: %%z)?",\s*
+ datepattern = "\s*time_local\s*":\s*"%%d/%%b/%%Y:%%H:%%M:%%S(?: %%z)?",\s*
```
(or one could fix the log-format in the configuration of nginx or related service with names normalization)


Also you have to adjust the `_uri` and `_code` to URIs and response code you really need... And normally if the site support authentication, one would exclude 401 codes (which have to be handled separately, due to handshake procedure or initial requests responding with 401 in regular case), so for instance:
```diff
- _code = [45]0\d
+ _code = (?!401)[45]0\d
```
To check it'd match, you can use `fail2ban-regex`, e. g.:
```bash
fail2ban-regex -vv "$message_or_logname" nginx-apollo
```
