### ISSUE TITLE
Similar issue - https://github.com/fail2ban/fail2ban/issues/3456#issuecomment-1427114645

### ISSUE THREAD

**Issue by suixhxy** [fail2ban/fail2ban#3875]
Thank you for your answer, thank you very much!

But now the requirements change, I want to monitor the error log information,
The log format is as follows:
tail -f  /var/log/nginx/apollo.error.log
The following log content:
The log information is generated after the incorrect password is entered.
Now want to implement, enter the wrong password 3 times, automatically intercept. How to write regular expressions? Thank you for your help
vim /etc/fail2ban/filter.d/nginx-apollo.conf
```
[Definition]
failregex = client:.*?  . *? <HOST>.*?  "GET /signin HTTP/2.0".*.*? [error].*?
ignoreregex =
```
The error log contents are as follows:
```
2024/11/08 11:01:13 [error] 58907#58907: *675189321 js exception: TypeError: cannot get property "replace" of undefined
at headersAllowed (/etc/nginx/jwt.js:105)
while reading response header from upstream, client: 123.5.42.99, server: apollo-portal.xxxxxxx.com, request: "GET/signin HTTP / 2.0", upstream: "http://192.168.3.126:18071/signin", host: "apollo-portal.xxxxxxx.com"
2024/11/08 11:01:14 [error] 58907#58907: *675189321 js exception: TypeError: cannot get property "replace" of undefined
at headersAllowed (/etc/nginx/jwt.js:105)
while reading response header from upstream, client: 123.5.42.99, server: apollo-portal.xxxxxxx.com, request: "GET/HTTP / 2.0" prefix - path, upstream: "http://192.168.3.126:18071/prefix-path", host: "apollo-portal.xxxxxxx.com", referrer: "https://apollo-portal.xxxxxxx.com/signin
```

**Comment by sebres** [comment]
No idea, why do you need to match js exceptions (caused by an error in probably your own script)... 
Seems like an error happens for different URIs (e. g. the first is `/signin`, the second is `/`)...
Also I don't think it is good idea to much such generalized thing - better would be to fix the error (check for the property `replace` or for type of object `replace` is used for, and/or catch the error and generate single-line message instead).

But if you really want to match it, you need to take a look at parameter [maxlines](https://manpages.debian.org/experimental/fail2ban/jail.conf.5.en.html#maxlines) in man jail.conf.5, so if you'd set it to 3 and add `(?ms)` modifiers as prefix to regex (for multiline search), you'd be able to match 3 lines log messages with the RE.

I have at the moment no time to provide you the ready filter for this (but guess it is not really that what one needs, see above).

BTW, your failregex looks very vulnerable (no anchors, many catch-alls, especially those before significant data like IP etc).

> How to write regular expressions? 

Tried google? I'm pretty sure there are hundred how-tos and manuals to the subject "learn regex"

**Comment by suixhxy** [comment]
> No idea, why do you need to match js exceptions (caused by an error in probably your own script)... Seems like an error happens for different URIs (e. g. the first is `/signin`, the second is `/`)... Also I don't think it is good idea to match such generalized thing - better would be to fix the error (check for the property `replace` or for type of object `replace` is used for, and/or catch the error and generate single-line message instead).
> 
> But if you really want to match it, you need to take a look at parameter [maxlines](https://manpages.debian.org/experimental/fail2ban/jail.conf.5.en.html#maxlines) in man jail.conf.5, so if you'd set it to 3 and add `(?ms)` modifiers as prefix to regex (for multiline search), you'd be able to match 3 lines log messages with the RE.
> 
> I have at the moment no time to provide you the ready filter for this (but guess it is not really that what one needs, see above).
> 
> BTW, your failregex looks very vulnerable (no anchors, many catch-alls, especially those before significant data like IP etc).
> 
> > How to write regular expressions?
> 
> Tried google? I'm pretty sure there are hundred how-tos and manuals to the subject "learn regex"


I know what you mean. I think I know what to do. Thank you. Thank you very much
