### ISSUE TITLE
Fail2ban+iptables-multiport I don’t see any ports in the created rule

### ISSUE THREAD

**Issue by draconMo** [fail2ban/fail2ban#3882]
hello 
debian12+dovecot+postfix+fail2ban (I use the filter  dovecot.conf that comes with fail2ban )
mcedit /etc/fail2ban/jail.local 
[dovecot]
enabled = true
filter  = dovecot
port    = imap,imaps,pop3,pop3s
action  = iptables-multiport[name=dovecot, port="imap,imaps,pop3,pop3s", protocol=tcp]
bantime = 60m
maxretry = 3
findtime = 60m

restart fail2ban

I entered the wrong password 3 times

I see the blocking is triggered

024-11-13 11:25:49,381 fail2ban.jail           [1658152]: INFO    Jail 'modoboa' started
2024-11-13 11:25:49,383 fail2ban.filtersystemd  [1658152]: INFO    [modoboa] Jail is in operation now (process new journal entries)
2024-11-13 11:25:49,428 fail2ban.filter         [1658152]: INFO    [dovecot] Found 193.105.37.198 - 2024-11-13 11:08:39
2024-11-13 11:25:49,429 fail2ban.filter         [1658152]: INFO    [dovecot] Found 193.105.37.198 - 2024-11-13 11:22:05
2024-11-13 11:25:49,429 fail2ban.filtersystemd  [1658152]: INFO    [dovecot] Jail is in operation now (process new journal entries)
2024-11-13 11:25:49,751 fail2ban.actions        [1658152]: NOTICE  [dovecot] Restore Ban 193.105.37.198

I look at the created iptables rule. I see

Chain f2b-dovecot (1 references)
num  target     prot opt source               destination
1    REJECT     0    --  193.105.37.198       0.0.0.0/0            reject-with icmp-port-unreachable
2    RETURN     0    --  0.0.0.0/0            0.0.0.0/0

I see that there was a blocking without taking into account the port. This is how it should be (action = iptables-multiport[name=dovecot, port="imap,imaps,pop3,pop3s", protocol=tcp) ?

**Comment by sebres** [comment]
> how often does fil2ban look at the log?

It depends on `backend`:
- by backend `polling` (log-file) it is dynamic, but maximal up-to 1 second after last lookup.
- by backend `pyinotify` (log-file) or `systemd` (journal) - it is almost immediately after change of log-file or journal

(backend `auto` prefers `pyinotify` if all requirements are available, otherwise will fallback to `polling`)

> I noticed that the Found and Ban events appear in fial2ban.log with a delay (2-5 min)

It is definitely not normal or you're simply making some mistake somewhere...

"Found" must happen almost in the same second.
You'd also see the time of the failure in the message:
```
2024-11-13 11:37:54,820 fail2ban.filter         [980]: INFO    [jail] Found 192.0.2.123 - 2024-11-13 11:37:54
```
(left is time where fail2ban found the attempt, right is the time from log/journal)

"Ban" takes places after `maxretry` found attempts within `findtime` time window.
With other words, by `maxretry = 3`, the IP would need 3 failed attempts to get banned, and this can be surely several minutes (if 3rd attempt happens few minutes after the 1st), also the jail will forget the failures occurred `findtime` back, so by `findtime = 60m` it'd consider only failures within last hour.

**Comment by draconMo** [comment]
> Я заметил, что события «Найдено» и «Бан» появляются в fial2ban.log с задержкой (2–5 мин)

> Это определенно ненормально, или вы просто где-то допускаете ошибку...

> "Найдено"` должно произойти почти в ту же секунду.

Perhaps the delay is due to the fact that I do not use a separate file for dovecot logs (journalmatch = _SYSTEMD_UNIT=dovecot.service)

**Comment by sebres** [comment]
No, there is normally no latency in any case, no matter file- or journal-related backends used.
