### ISSUE TITLE
[RFE]: You want to add a CC protection rule by default

### ISSUE THREAD

**Issue by SONGjiemo** [fail2ban/fail2ban#3889]
Hopefully there can be CC fool-proof protection rules,
For example, a smoother setting would be:
1. A single IP can only be accessed by 15 times, and the blocking time is 30 minutes if the system request is checked every 20s.
2. The IP of the chief engineer can access 300 at the same time. If it is exceeded, it will not be opened automatically.
PS: You can also modify the configuration

**Comment by sebres** [comment]
> CC fool-proof protection rules

No idea what a common criteria exactly you meant... Please be more precise by the description what it shall be and/or which rules you mean exactly and for which purposes.

Shall it be some tool, automatically checking that the failures will be found and a ban happens?
If so then despite the certain complexity by coverage of all vectors, I don't think it must be the task of fail2ban, especially because such thing need to be constructed on the another side (behind the network adapter). One can surely write a simple cron or whatever service checking the ban on the side of fail2ban, but it'd be ugly and too artificial.

The complexity can be illustrated by following issues:
1. too many jails but also the attack vectors the filters finding (let alone things like the mode, e. g. `aggressive` or `ddos` covering different approaches, etc), so the checker needs to try several attempts in different ways;
2. to cover them properly, such checker needs fully simulate the bot and/or do it via corresponding service (port/protocol), like sshd, smtp- or web-server etc, because otherwise (e. g. simulating via log-message) it could theoretically miss the change of log-message in new version of corresponding service, so simulating it via journal/log-file would not find the deviation;
3. too many protocols that such a tool would need to support;
4. different settings and ways how the services may reject or refuse the bad connections (e. g. `MaxStartups` or `LoginGraceTime` of sshd-service) and/or how it'd affect the logging behavior;
5. too many settings on fail2ban side, that could hinder the check, e. g. incremental banning (`bantime.increment = true`) would cause that the "IP of the chief engineer" will be banned faster and for longer time each next attempt.

**Comment by SONGjiemo** [comment]
> > CC防呆保护规则
> 
> 不知道什么是一个共同的标准到底你的意思.请更精确地描述它应该是什么和/或您确切地指的是哪些规则以及用于哪些目的。
> 
> 它
> 应该是一些工具，自动检查故障将被发现和禁令发生？如果是这样的话，那么尽管覆盖所有向量的复杂性，我不认为这一定是fail 2ban的任务，特别是因为这样的事情需要在另一边（网络适配器后面）构建。当然可以编写一个简单的cron或任何服务来检查fail 2ban的禁令，但这会很难看，而且太人工了。
> 
> 复杂
> 性可以通过以下问题来说明：
> 
> 1. 太多的监狱，而且过滤器发现的攻击向量（更不用说像模式，e. G. `aggressive`或`ddos`覆盖不同的方法等），所以检查器需要以不同的方式尝试几次尝试;
> 2. 为了正确地覆盖它们，这样的检查器需要完全模拟机器人和/或通过相应的服务（端口/协议）来完成，如sshd，smtp或web服务器等，因为否则（e. G.通过日志消息模拟）理论上它可能错过相应服务的新版本中日志消息的变化，因此通过日志/日志文件模拟它将不会发现偏差;
> 3. 这种工具需要支持的协议太多;
> 4. 服务如何拒绝或拒绝坏连接的不同设置和方式（例如，G. `MaxStartups`或`LoginGraceTime`sshd-service）和/或它如何影响日志记录行为;
> 5. fail 2ban端的设置太多，可能会阻碍检查，e. G.增量禁止（`bantime.increment = true`）将导致“总工程师的IP”将被更快地禁止，并且每次下一次尝试的时间更长。


`[Definition]
failregex = ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+XDEBUG.+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+GponForm.+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+phpunit.+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+ajax-index\.php .+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+sellers\.json .+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+adminer\.php .+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+wp-configuration\.php.+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+ThinkPHP.+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+wp-config.+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+dede\/login\.php .+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+plus\/recommend\.php .+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+e\/install\/index.php .+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+m\/e\/install\/index\.php .+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+e_bak\/install\/index.php .+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+\.aspx .+$
            ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+\.act .+$
            ^<HOST>.*] "(GET|POST|HEAD) .*xmlrpc\.php.*
            ^<HOST> -.*"(GET|POST|HEAD).*HTTP\/1\.1.*"*.Mozilla/5\.0 \(Windows NT 6\.1\; rv\:60\.0\) Gecko\/20100101 Firefox\/60\.0.*"$
            ^<HOST> -.*"(GET|POST|HEAD).*HTTP\/1\.1.*"*.Photon.*"$
            ^<HOST> -.*"(GET|POST|HEAD).*HTTP\/1\.1.*"*.Mozilla\/5\.0 zgrab\/0\.x.*"$
            ^<HOST> -.*"(GET|POST|HEAD).*HTTP\/1\.1.*"*.XTC.*"$
            ^<HOST> -.*"(GET|POST|HEAD).*HTTP\/1\.1.*"*.python-requests.*"$
            ^<HOST> -.*"(GET|POST|HEAD).*HTTP\/1\.1.*"*.bidswitchbot.*"$
            ^<HOST> -.*"(GET|POST|HEAD).*HTTP\/1\.1.*"*.Google-adstxt.*"$
            ^<HOST> -.*"(GET|POST|HEAD).*HTTP\/1\.1.*"*.Apache-HttpClient.*"$
            ^<HOST>.*] "POST .*HTTP\/1\.1.*
            ^<HOST> -.*"(GET|POST|HEAD).*HTTP\/1\.1.*"*.Go-http-client\/1\.1.*"$
            ^<HOST> .* ".*\\x.*" .*$
            ^<HOST> -.*"(GET|POST|HEAD) .+wp-login\.php .*HTTP\/1\.1.*
            ^<HOST> -.*"(GET|POST|HEAD) .*wp-includes/wlwmanifest.xml .*HTTP\/1\.1.*
ignoreregex = ^<HOST>.*] "POST /xmlrpc\.php\?for=wpandroid*
              ^<HOST>.*] "POST /wp-cron\.php\?doing_wp_cron=.*
datepattern = {^LN-BEG}%%ExY(?P<_sep>[-/.])%%m(?P=_sep)%%d[T ]%%H:%%M:%%S(?:[.,]%%f)?(?:\s*%%z)?
              ^[^\[]*\[({DATE})
              {^LN-BEG}`

**Comment by sebres** [comment]
See [apache-badbots](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/apache-badbots.conf) and similar filter.
But...
It is hardly possible to create a good and well thought out filter with a pure blacklist for generic purposes.
Despite it'd be too unprecise, too slow and ugly, it'd have a lot of other issues - for instance see the discussion in https://github.com/fail2ban/fail2ban/issues/2583#issuecomment-569694859 and below.

More or less generic protection is pretty simple: a filter monitoring special log (not a common access-log), generated from common location/handler in the web-server, responsible for failures only, in sense of the application(s)...
Either 401 (authentication issues) or 40x/50x errors, excepting those from legitimate users, if some may occur by certain circumstances (e. g. 404 for broken links/images). But definitely not a URI-based black-list. If you'd read the reasons provided in #2583 attentively, you'd surely recognize that this were not a proper solution.
