### ISSUE TITLE
[BR]: fail2ban says IP is already banned so it doesn't call custom action

### ISSUE THREAD

**Issue by Filip52542** [fail2ban/fail2ban#3911]
### Environment:

- Fail2Ban version : 1.1.0 (`fail2ban-client version`)
- OS, including release name/version : `Linux <redacted> 6.11.11-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec  5 18:38:39 UTC 2024 x86_64 GNU/Linux` (`uname -a`) / Fedora 40
- [x] Fail2Ban installed via OS/distribution mechanisms (yes, `dnf`)
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

I've set up a jail to call a custom action. The action calls a custom script (written by me) which handles iptables rules. The script seems to have some issue where it doesn't ban an IP every time. Due to that, when an IP bothers me again, fail2ban thinks it is already banned and throws a warning and **doesn't** call my script.

Therefore, my question/problem is:
How to call an action even if fail2ban thinks the IP is already banned?

#### Steps to reproduce

Create a custom action which just logs every ban without actually banning the IP. You can see that the second time fail2ban tries to ban the same IP, the script isn't called.

#### Expected behavior

The script is called again.

#### Observed behavior

The script is never called a second time.

#### Any additional information

Am I missing a configuration option? I can't find any helpful info online.

#### Any customizations done to /etc/fail2ban/ configuration

/etc/fail2ban/action.d/custom_ban.conf
```
[Definition]
actionstart = <redacted>/custom_ban.sh start <port>
actioncheck =
actionban   = <redacted>/custom_ban.sh ban <ip> <port>
actionunban = <redacted>/custom_ban.sh unban <ip> <port>
actionstop  =
```

/etc/fail2ban/jail.local
```
action = custom_ban[port='%(port)s', actionflush=true]
```

#### Relevant parts of /var/log/fail2ban.log file:
```
2024-12-28 11:05:22,692 fail2ban.filter         [3873815]: DEBUG   Processing line with time:1735383922.692202 and ip:14.103.126.104
2024-12-28 11:05:22,693 fail2ban.filter         [3873815]: INFO    [sshd] Found 14.103.126.104 - 2024-12-28 11:05:22
2024-12-28 11:05:22,693 fail2ban.failmanager    [3873815]: DEBUG   Total # of detected failures: 579. Current failures from 1 IPs (IP:count): 14.103.126.104:1
2024-12-28 11:05:22,694 fail2ban.observer       [3873815]: DEBUG   [sshd] Observer: failure found 14.103.126.104
2024-12-28 11:05:23,007 fail2ban.actions        [3873815]: WARNING [sshd] 14.103.126.104 already banned
```

**Comment by sebres** [comment]
> How to call an action even if fail2ban thinks the IP is already banned?

It is not possible. Or rather it is not foreseen in fail2ban that its banning action doesn't work at all, so normally fail2ban simply logs "Already banned" and do nothing, because consider the situation as the events corresponding the messages caused future ban happened before the first ban took place. Moreover newer version of fail2ban will count such events and if the number becomes too large, it'd try to repair it, e.g. initiate a restore sane environment process (recreate the actions and reban everything).

With other words:
1. either your custom action doesn't work at all (in sense of banning)
2. or you miss real banning action (and your custom action must be the second action)
3. or it is not intended to be banning jail (like something for the logging, honeypot etc), then to call the action again, the ticket must be "unbanned" immediately, e. g. set `bantime = 1` (or to few seconds).

> Create a custom action which just logs every ban without actually banning the IP.

OK, it looks indeed like variant 3, thus simply set `bantime` to the time you want to see the log the next time. Ensure it is larger than 1 (1 second), to prevent missing "bans" by some delays by detection etc (interval between recognized time of failure and time of banning), because otherwise the ban can be considered as obsolete and it would not invoke the ban command at all.

Also note https://github.com/fail2ban/fail2ban/issues/2304#issuecomment-590276134.
