### ISSUE TITLE
better error message than "Unable to contact server. Is it running?"

### ISSUE THREAD

**Issue by grooverdan** [fail2ban/fail2ban#595]
from https://bugs.launchpad.net/ubuntu/+source/fail2ban/+bug/903647

**Comment by leeclemens** [comment]
Although it violates [EAFP] (https://docs.python.org/2/glossary.html#term-eafp), I added more error checking with #1088 (in order to provide more specific error messages). Otherwise simply adding "You must be root" to the existing message should satisfy this issue and related bugs.

Since three people touched this, I assumed it was worth fixing.

**Comment by sebres** [comment]
fixed in #1088
