### ISSUE TITLE
Patch for Joyent SmartOS(Solaris based)

### ISSUE THREAD

**Issue by sawanoboly** [fail2ban/fail2ban#607]
Hi,

I have created a patch for Joyent SmartOS(Solaris based).

https://gist.github.com/sawanoboly/8838359

This patch was created from 0.8.12.

Problems of `setup.py` and some files with the SmartOS are as follows:

- `/usr/lib` and `/usr/share` are Read only.
- Should use `/usr/local/share`.

Could you include this patch to code repository?

**Comment by leeclemens** [comment]
I don't think this patch will work, since the paths (destination) are defined in setup.py. If you could provide a suitable solution to install and reference the new paths, that may be worth adding. Otherwise, I'm not sure what to do with this Issue. Closing unless new information/justification can be provided (very old).

**Comment by sawanoboly** [comment]
I I found that Joyent has been provided official package of fail2ban since 2015Q1.

http://pkgsrc.joyent.com/packages/SmartOS/2015Q1/x86_64/security/

Thanks.
