### ISSUE TITLE
Automated filter update service

### ISSUE THREAD

**Issue by kwirk** [fail2ban/fail2ban#617]
It would be great if there was a feature in Fail2Ban to automatically update filter configurations, independent of software updates. Similar way that _spamassassin_ has _sa-update_ to pull the latest spam rules.

This could be a _fail2ban-update_ or similar program which could be run on a cron job daily, pulling the latest filters. This means if a new attack method is being used, or there is an vulnerability for a filter, everyone can get the updates much quicker than software update. 

The program could be quite simple, just downloading the latest filters from _github_. Just need to keep sure there aren't any incompatibilities between filters (e.g. some of the _0.9_ filters wont function with current _0.8.x_).

Obviously, users still have _.local_ files to override these auto updates if they have their own custom filters.

**Comment by sebres** [comment]
I agree with @yarikoptic in all points. Additionally, I see real problem to implement it plausible for all possible distributions (and it's versions). Normally maintainers can (and must) add own distribution-related modifications (or includes), that may the have the conflicts with "newer" filter, automatically distributed per such update.
The same is valid for local customization (changes in ".local" files of the host self).

So I'm currently also with conclusion:
> better to stay with releases and just release more often

Still one point for another "service" for fail2ban, that we could introduce - something like "monitor" resp. "observer/checker", that will periodically execute smal scripts, that tries to "authenticate" each "service" (observed with fail2ban), in order to produce a failure (to cover all filters). If this will be not caught by fail2ban hereafter, it should raise the alarm (notify admin, etc). 
So he will be able to update the filters manually.
