### ISSUE TITLE
RF to allow arbitrary set of keys (not just HOST) to track the failures

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#67]
From the mailing list:
http://sourceforge.net/mailarchive/forum.php?thread_name=50143F62.6050904%40whyscream.net&forum_name=fail2ban-users

```
> On 28-07-12 16:18, Gerry Magill wrote:
> > VoIP has to go through a SIP aware firewall in My scenario to resolve
> > NAT-traversal issues with the SIP protocol. So my SIP Registrar sees all
> > connections as coming from my SBCs IP. Each new distinct user appears to
> > me as traffic from a new port. This port binding never changes until my
> > SBC is rebooted.

> > I can identify SIP SPIT and SPAM using snort but blocking the whole IP
> > would kill my SBC.

> > So I am looking to black list IP port bindings I identify as being
> > malicious and release them after 3 days in jail.
```

So this use case would require to track not only by IP but by (IP, port) pair.  We could implement this based on the named groups in the failregex (ATM only ```P<host>``` is utilized) and pass all those to the actions complementing the variables defined in Init and passed into the jail definition

**Comment by chetan-prime** [comment]
I have a particular requirement with my email server to detect compromised users regardless of IP. I have a regex ready to detect when a user is sending emails and a script ready to disable that user temporarily.
All I need is a way to run the user disable script with fail2ban passing the email address captured using the regex.
Ideally this requires changes to fail2ban to allow grouping matches by a regex variable,or to allow setting <HOST> to a named regex match, so fail2ban can detect if the same user is sending emails too fast (irrespective of IP)
#1110

**Comment by tguild** [comment]
Another person who needs more data from matched log line than just IPv4 address.  Hope this gets released soon and surprised this has been open for nearly 4 years.

**Comment by sebres** [comment]
@chetan-prime please test #1454

**Comment by sebres** [comment]
Issue can be reopened later:
- if someone needs multiple groups (the "host" as ban-identifier should be accumulated from multiple "tags")
- there is no unique ban identifier (user, pair ip:port, mac-address) available or there should not be unique: for example "banning" process does not really ban, but should just execute some action after X failures (for example just sends a mail to admin);

**Comment by chetan-prime** [comment]
Thank you @sebres , this looks exactly like what I wanted. I'm testing and will report back in case of issues

**Comment by sebres** [comment]
@chetan-prime, by merge in 0.10 I've currently realized, that I've forgotten to commit my last filter.py, that contains change, allows a new value 'raw' inside setUseDns.
Without this amend-fix `usedns` goes with fallback again to `no`, so the fail2ban will ignore such failures (because are not valid)

Please be sure by your tests, that you've actualized the master (and it contains b853474).

**Comment by jerrykan** [comment]
>     * if someone needs multiple groups (the "host" as ban-identifier should be accumulated from multiple "tags")

Sorry to comment in a closed issue, but was the ability to combine multiple groups/tags into a ban-identifier ever implemented? After searching everywhere this seems to be the only place that mentions it.

I have a use-case with the squid proxy where I want to match on the client IP and the requested domain. The log line looks something like:
```
1591753818.254      0 192.168.1.30 TCP_DENIED/407 3978 CONNECT www.example.com:443 - HIER_NONE/- text/html
```
Because of how squid authentication works it is expected that there will be a `TCP_DENIED/407` (failure) response followed by a `TCP_MISS/200` (success). However occasionally a client doesn't work well with the proxy and keeps making requests resulting in `TCP_DENIED/407`. I would like to match on both the client IP and the requested domain as a unique pair and ban the IP if there are persistent `TCP_DENIED/407` for the same domain. Without combining multiple tags this doesn't seem possible.

**Comment by jerrykan** [comment]
@sebres thanks for taking the time to respond to my query. I've created a new issue to continue the discussion so I'm not spamming a bunch of people subscribed to a closed issue.

see: https://github.com/fail2ban/fail2ban/issues/2755
