### ISSUE TITLE
Allow established traffic before fail2ban filters

### ISSUE THREAD

**Issue by oh3nwq** [fail2ban/fail2ban#732]
Could we have a configurable option of adding 
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
line in iptables before the fail2ban filters?
This would speed up the already allowed traffic.

**Comment by leeclemens** [comment]
I suggest this be closed

**Comment by nelenkov** [comment]
It seems latest `firewalld` already adds a `ctstate RELATED,ESTABLISHED` at the top which effectively breaks fail2ban. If you are scanning from the same host:port, packets will go through even after the IP is banned by fail2ban. Cf. INPUT chain from CentOS 7:

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
INPUT_direct  all  --  0.0.0.0/0            0.0.0.0/0
INPUT_ZONES_SOURCE  all  --  0.0.0.0/0            0.0.0.0/0
INPUT_ZONES  all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0
REJECT     all  --  0.0.0.0/0            0.0.0.0/0            reject-with icmp-host-prohibited
```

**Comment by yarikoptic** [comment]
With the given discussion I think I will indeed just close this issue.  Any necessary custom rules could either be added through fail2ban's mechanisms (.local etc) and/or within any given firewall to grant establish connections the green light early in the chain.
Cheers!

**Comment by nelenkov** [comment]
That's all well and good, but since the default behaviour has changed (at least when using firewalld), isn't that a bug in itself?

**Comment by leeclemens** [comment]
@nelenkov I haven't tested on CentOS 7, but can you provide the f2b chain (or really the entire config, since I don't see a fail2ban related chain)? (I don't see it in your provided listing).  Also, since sshd should terminate a connection after X attempts, the TCP sessions would no longer be related or established - allowing the fail2ban's chain to deny/reject the connect moving forward. That is application specific, but I wanted to mention it here.

**Comment by nelenkov** [comment]
Yes, it is application specific, I should've been more clear. TCP-based protocols like SSH should be OK, because connections are generally closed on auth failure. However, for UDP protocols like SIP, while there is no connection per se, packets from the same host:port to the server's UDP 5060 are treated as related, so you probing/bruteforcing works even after you ban the IP (as long as they are using the same source port). Not sure what is a good way to handle this? 

As for my chains, f2b chains are referenced from `INPUT_direct` which comes after `ACCEPT  ctstate RELATED,ESTABLISHED`. This is using `banaction = firewallcmd-new`, but same behaviour with `firewallcmd-ipset`. Something like this:

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
INPUT_direct  all  --  0.0.0.0/0            0.0.0.0/0
...
Chain INPUT_direct (1 references)
target     prot opt source               destination
f2b-asterisk-tcp  tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW multiport dports 5060,5061
f2b-asterisk-udp  udp  --  0.0.0.0/0            0.0.0.0/0            state NEW multiport dports 5060,5061
...
Chain f2b-asterisk-tcp (1 references)
target     prot opt source               destination
REJECT     all  --  1.2.3.4      0.0.0.0/0            reject-with icmp-port-unreachable
REJECT     all  --  1.2.3.5        0.0.0.0/0            reject-with icmp-port-unreachable
RETURN     all  --  0.0.0.0/0            0.0.0.0/0

Chain f2b-asterisk-udp (1 references)
target     prot opt source               destination
REJECT     all  --  1.2.3.4      0.0.0.0/0            reject-with icmp-port-unreachable
REJECT     all  --  1.2.3.5        0.0.0.0/0            reject-with icmp-port-unreachable
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
...
```

**Comment by nelenkov** [comment]
For the record, `iptables-multiport` inserts itself at the top of `INPUT` (before the `RELATED, ESTABLISHED` rule), so UDP bans work as expected.

**Comment by leeclemens** [comment]
@nelenkov iptables-multiport sure does, fail2ban's rules being processed before any other chain is critical to its effectiveness (baring a whitelist). Please checkout the very first post to this issue :) And feel free to create a new/separate Issue if you have different concerns.
