### ISSUE TITLE
Doesn't work on Fedora 20

### ISSUE THREAD

**Issue by maxhaase** [fail2ban/fail2ban#816]
Installed using yum:
********************************************************************************
Downloading packages:
fail2ban-0.9-2.fc20.noarch.rpm                                                                                                                                                              | 359 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction (shutdown inhibited)
  Installing : fail2ban-0.9-2.fc20.noarch                                                                                                                                                                      1/1 
  Verifying  : fail2ban-0.9-2.fc20.noarch                                                                                                                                                                      1/1 

Installed:
  fail2ban.noarch 0:0.9-2.fc20                                                                                                                                                                                     

Complete!
********************************************************************************
Then, try to use it:

[root@computer fail2ban]# service fail2ban-server start
Redirecting to /bin/systemctl start  fail2ban-server.service
Failed to issue method call: Unit fail2ban-server.service failed to load: No such file or directory.
[root@computer fail2ban]# 
[root@computer fail2ban]# service fail2ban-server status
Redirecting to /bin/systemctl status  fail2ban-server.service
fail2ban-server.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

**Comment by RamananSharma** [comment]
I had the issue with Fedora 23 and it was because sshd logs are stored in journal instead of the path /var/log/secure declared in paths-fedora.conf. Fixed it by overriding the value `backend = auto` to `backend = systemd` in jail.local

**Comment by georgedorn** [comment]
backend = systemd fixed a similar issue for me on xubuntu 16.04.  'service fail2ban restart' was failing with "fail2ban.service start request repeated too quickly, refusing to start" and changing the backend fixed this.

**Comment by AvielOssi** [comment]
Hi there,

For those of you installing fail2ban on Xenserver 7 after installation, who encountered problems with EPEL and dependencies that has to do deal with systemd-python / fail2ban-server-0.9.7-1.el7.noarch systemd-python. 
Please follow the following step to get this working, you don't want your hypervisor to be jacked by an automated botnet.

1. Download the latest stable fail2ban variant:
wget https://github.com/fail2ban/fail2ban/archive/0.8.14.tar.gz

2. Untar, install ./setup.py install

3. create the directory and file:
 - mkdir -p /var/run/fail2ban
 - /usr/lib/systemd/system/fail2ban.service

4. for our service /usr/lib/systemd/system/fail2ban.service add the following lines (thank you  mrc0mmand ):

[Unit]
Description=Fail2ban Service
After=syslog.target network.target firewalld.service

[Service]
Type=forking
ExecStart=/usr/bin/fail2ban-client -x start
ExecStop=/usr/bin/fail2ban-client stop
ExecReload=/usr/bin/fail2ban-client reload
PIDFile=/var/run/fail2ban/fail2ban.pid
Restart=always

[Install]
WantedBy=multi-user.target

5. Once this is done, we can configure jail.conf; be wary that the package from fail2ban comes with the ssh.log directory instead of the /var/log/secure directory in CentOS. You must change this.

Go to /etc/fail2ban/jail.conf and change the logvalue, and configure the jail to work as required. Be advised that the top values for timeout and bantime override the rest. One more point; To ban for infinate time, bantime value must be -1.

[ssh-iptables]
enabled  = true
filter   = sshd
action   = iptables[name=SSH, port=ssh, protocol=tcp]
           sendmail-whois[name=SSH, dest=x@x, sender=x@x, sendername="Fail2Ban"]
logpath  = /var/log/secure
maxretry = 3


[ssh-ddos]
enabled  = true
filter   = sshd-ddos
action   = iptables[name=SSHDDOS, port=ssh, protocol=tcp]
logpath  = /var/log/secure
maxretry = 2

6. Run fail2ban with service fail2ban start / systemctl start fail2ban.

6. service fail2ban status:

[root@ ~]# service fail2ban status
Redirecting to /bin/systemctl status  fail2ban.service
● fail2ban.service - Fail2ban Service
   Loaded: loaded (/usr/lib/systemd/system/fail2ban.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-10-13 12:48:05 CEST; 21min ago
  Process: 5490 ExecStart=/usr/bin/fail2ban-client -x start (code=exited, status=0/SUCCESS)
 Main PID: 5506 (fail2ban-server)
   CGroup: /system.slice/fail2ban.service
           └─5506 /usr/bin/python /usr/bin/fail2ban-server -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid -x

Hope this helps!

**Comment by sebres** [comment]
> Download the latest stable fail2ban variant ... fail2ban/archive/0.8.14.tar.gz

Hmm, the latest stable is v.0.10 (or if you want long approbated variant then v.0.9). 
v. 0.8 is at least 3 years old and already a long time is out of date (thus no support anymore)...

**Comment by AvielOssi** [comment]
Fail2ban propagates 0.8.14 as "very-stable" 
http://www.fail2ban.org/wiki/index.php/Downloads

It is a very old version, however - it does its job, right?

**Comment by sebres** [comment]
I would answer: why don't use XenServer 5.6?

**Comment by yarikoptic** [comment]
Fwiw, a very stable fail2ban would be appropriate (only) for very stable os releases ;-)
