### ISSUE TITLE
fail to parse line-trailing comments

### ISSUE THREAD

**Issue by drzraf** [fail2ban/fail2ban#821]
``` bash
[vsftpd]
filter = vsftpd
bantime = 18000
```

```
$ fail2ban-client -d|grep vsftpd.*bantime
['set', 'vsftpd', 'bantime', 18000]
```

ok

But now...

``` bash
[vsftpd]
filter = vsftpd
bantime = 18000 # 5h
```

```
$ fail2ban-client -d|grep vsftpd.*bantime
['set', 'vsftpd', 'bantime', 600]
```

is **not** ok, the bantime wasn't interpreted (because of the comment).
A default value was set which does not come come from `[DEFAULT]`
No notification is thrown that the configuration failed to be parsed correctly (at least trying to (int)cast such a string should trigger a warning).

I thought markdown would performs better, but as of writing it seems that the purple color for int seems to depend on the presence of the trailing comment ("18000" is only colored in the 2nd  code-block config' sample)

**Comment by sebres** [comment]
Possibly too late, but nevertheless...

see [13.2. ConfigParser — Configuration file parser — Python 2.7.13 documentation](https://docs.python.org/2/library/configparser.html?highlight=configparser#module-ConfigParser)...
> Lines beginning with '#' or ';' are ignored and may be used to provide comments.

We using default python configuration files syntax (with our own enhancements), but it would be too incompatible if we'll recognize `#` or `;` in the middle of the line as comment.
I'm definitely against. Just imagine it is part of regular expression (`failregex`) or something similar.

BTW `5h` can be used directly now instead of `18000` by all time-inputs in our newer version (0.10).
