### ISSUE TITLE
installed on fedora 20 - no banning is being performed (firewallD)

### ISSUE THREAD

**Issue by propertunist** [fail2ban/fail2ban#827]
i was able to successfully install and start fail2ban on fedora 20 (64bit) - yet there is no banning happening as far as i can see.
i used the guide here: http://apuntesderoot.wordpress.com/2014/02/27/configure-fail2ban-in-fedora-20-to-use-firewall-cmd-and-ipset/
though i wasn't 100% clear on where each of the new config files should be placed.

presently i have a 'jail.customisation' file in /etc/fail2ban/jail.d/
and a 'fail2ban.local' file in /etc/fail2ban/fail2ban.d/

jail.customisation contains:
```
[sshd]
enabled=true
action = firewallcmd-ipset
```
and 'fail2ban.local' contains:
```
[Definition]
loglevel = DEBUG
```

i can see from putty (when i use it to login via ssh) that there have been failed login attempts made by hackers, yet fail2ban is not detecting them or adding them to any block lists.

anyone know what i am missing here?

**Comment by TB1234** [comment]
Hi,
I have also big problems to run fail2ban in a OpenVZ VE. Maybe someone can help me.
The VE run with CentOS 7. fail2ban is 0.9.2. All possible IPTable modules are availibe in the VE. The banaction with ipset are not possible because of restrictions with the Kernel. So I tried the other methods you wrote here like firewallcmd-new.
In this case I got the message:
Kernel module xt_set is not loaded in.
Any ideas what I can do? I cannot load this module into the VE. On the Host it is available. Thanks and regards

**Comment by leeclemens** [comment]
@TB1234 can you provide you're configs? You are commenting on an issue almost a year old that you had not participated in.

What action are you using? What errors are in fail2ban's log? If your VE is restricting you from executing things, fail2ban isn't going to magically circumvent those restrictions. Fail2ban should be logging (set it to DEBUG as OP did) the commands it attempts to execute. This should help point to exactly what is failing for your specific environment - and possibly provide alternatives (iptables instead of firewalld). fail2ban-client -v -d could also prove useful.

**Comment by TB1234** [comment]
I fixed it five minutes ago. The problem was on my side. :-/ 
I copied the jail.conf to jail.local (I didn't this before) and switched to firewallcmd-new. Now it is working...
Thanks for your help :)

**Comment by leeclemens** [comment]
Glad to hear it! I strongly suggest only overriding things in jail.local (not copying the entire config)...since jail.conf can change in the future, but you'll permanently override those settings in your jail.local.

**Comment by shadowym** [comment]
Fyi for others who run into this on OpenVZ.  OpenVZ kernel does NOT support ipset inside a container.  That is why the firewallcmd-ipset banaction does not work.  Use firewallcmd-new or iptables instead.
