### ISSUE TITLE
Can't run multiple jails for same service

### ISSUE THREAD

**Issue by dr8** [fail2ban/fail2ban#931]
I am trying to run multiple jails for ssh. Each of them has different filters defined and different thresholds.

i.e.:
* attempts to log in as 'root'  has maxretry=0
* attempts to log in with bad credentials (i.e. standard ssh filter) has maxretry=5

Essentially, I never expect an attempt to log in as root, and want to ban instantly; but want to allow some grace for errors in log-ins by legitimate users.
All jails have same bantime, so there's no issue with the order of unbanning.

What actually happens:
Only one jail initialises (it appears to vary on start-up, but then doesn't change until the service stops), so the system will either:
* only ever ban those trying root logins and allow infinite attempts as non-root accounts or
* ban everyone equally and allow root logins multiple times

Each jail can be shown to work in isolation, so I'm happy that the filters are correct.

Ubuntu 14.04
fail2ban 0.8.11-1

**Comment by mrc0mmand** [comment]
Wouldn't be easier to just disable root login via ssh in `sshd_config` (`PermitRootLogin no`) and let fail2ban handle the rest? Or you have some specific reasons to leave ssh root login enabled?

**Comment by yarikoptic** [comment]
>    Ubuntu 14.04
>    fail2ban 0.8.11-1

outdated by any means now ... could you replicate with 0.8.13 or better
0.9.1 ?  backports for 0.8.13 available from neurodebian:
http://neuro.debian.net/pkgs/fail2ban.html?highlight=fail2ban

I believe that this issue was reported before but couldn't find it 
quickly and it might have been resolved and @mrc0mmand is completely right that it is better just to adjust your sshd_config , and may be if not "no" then ```PermitRootLogin without-password``` to still allow logins via ssh keys

**Comment by dr8** [comment]
I agree that this may be a nice to have - PermitRootlogin provides security, etc. This comes from trying to replicate some of the features of DenyHosts - which also includes a tighter threshold on bad usernames (on the grounds that you're more likely to mess up your password than get your username wrong, and brute force attempts are often guessing user names as much as passwords).

It doesn't seem unlikely that there are other use cases too though - like different classes of attack on apache, etc. where you might not want to treat all logged events as equivalent. It seems a bit of a limitation to only allow one filter/jail per service.

I'm happy to try later versions to see if I get different behaviour. I'll give that a go.
Ultimately, though, I wanted to know whether Fail2Ban *supported* looking for different classes of attack on the same service (and having separate thresholds) - or not.

**Comment by leeclemens** [comment]
PermitRootLogin doesn't have to do with fail2ban or DenyHosts - It simply won't allow it. It is best practice. In addition, using DenyHosts or fail2ban block any IP attempting such an invalid attempt is also beneficial.

You can use multiple jails (and subsequently filters) with the same log files. Obviously best practices, especially regarding SSH, should be followed before relying on any other software (like fail2ban).

If you can provide the two jails configurations, we might be able to help. Otherwise we' d just be guessing at how you have it setup. However, two jails with two filters both using the same log file (ssh) is possible.

**Comment by dr8** [comment]
Thanks - I thought it ought to be possible.
I've upgraded to 0.8.13, and run some tests; in which fail2ban appears to be demonstrating the expected behaviour of allowing multiple jails to be run for the same service, banning at different thresholds, etc.
Thanks for the link to the backport.
