### ISSUE TITLE
ignorecommand scripts directory

### ISSUE THREAD

**Issue by leeclemens** [fail2ban/fail2ban#937]
I wanted to solicit thoughts on where to put a 'stock' ignorecommand file. The jail expects a path/file to execute, rather than a command - and arguably writing one-liners for everything could become pretty messy.

Currently, the only ignorecommand executable file is in the unittests. So I wanted to get people's thoughts on where a regular executable should go - which would be part of a jail's default configuration.

It would also need to be referenced from the jail, and I think all of the distro-specific paths are for log files (not that one couldn't be added) - just food for thought.

@fail2ban/contributors

**Comment by leeclemens** [comment]
One thought:
ignorecommand_apache_fakegooglebot = /etc/fail2ban/scripts/apache-fakegooglebot.sh

**Comment by leeclemens** [comment]
Well, this seems to work:

ignorecommand_apache_fakegooglebot = ignore_apache-fakegooglebot.sh

2015-01-31 14:22:05,330 fail2ban.filter         [4650]: DEBUG   ignore command: ignore_apache-fakegooglebot.sh 66.249.66.1

python home/site-packages/fail2ban-0.9.1.dev0-py2.7.egg/EGG-INFO/scripts/ignore_apache-fakegooglebot.sh
python home/bin/ignore_apache-fakegooglebot.sh

**Comment by leeclemens** [comment]
Using ignorecommand_apache_fakegooglebot = /etc/fail2ban/ignorecommand/apache-fakegooglebot.sh

https://github.com/fail2ban/fail2ban/pull/938

**Comment by yarikoptic** [comment]
Well... I see three choices for placement of commands:

1.  install them all along side with fail2ban- scripts to system wide path.Just prefix them all with e.g. fail2ban-ignore-;  then we don't need to do anything additionally.  cons:  those are not really for a user to run  

2. keep them indeed under config/filters/ignorecommands  and execute from there.  cons: scripts among configuration files.  But otherwise probably the best location since goes along with where used -- in filters

3. keep/install somewhere under fail2ban/server/ignorecommands (and alongside with the module).  pros: no scripts in /etc  cons: separating away from configuration where they are intended to be used...

so I would vote for your 2 ;)

**Comment by leeclemens** [comment]
@yarikoptic Thanks for the response, I think I'll go with 2 as well, /etc/fail2ban/filter.d/ignorecommands/<>.sh

Perhaps offtopic, but it seems there are not tests that utilize ignorecommand in a jail/filter's configuration. One could argue ignorecommand belongs in the filter (with ignoreregex), but it is setup pretty much only as a jail configuration (which, iirc, would override the filter anyway).

While there is a simple test (manually coded) for ignorecommand, I believe this is the first that uses it - and it may not have been implemented at the time of its coding (hence no unittests).

**Comment by leeclemens** [comment]
I think this can be closed if PR https://github.com/fail2ban/fail2ban/pull/940 is merged - coverage seemed to have increased overall.

**Comment by yarikoptic** [comment]
Let's just close so we don't forget and #940 will get merged soon I bet ;)
