### ISSUE TITLE
Fai2ban zimbra / postfix

### ISSUE THREAD

**Issue by nikolas22t** [fail2ban/fail2ban#977]
Is there any way to ban a user if connect (sent) 10 emails in 1 minute for example parsing the log below:

 Feb 26 16:07:34 mail0 postfix/submission/smtpd[1513]: 382BD2616DC: client=unknown[1.1.1.1], sasl_method=PLAIN, sasl_username=username@domain.com

 Feb 26 16:07:37 mail0 postfix/submission/smtpd[1513]: 93B612616E2: client=unknown[1.1.1.1], sasl_method=PLAIN, sasl_username=username@domain.com

 Feb 26 16:07:47 mail0 postfix/submission/smtpd[2931]: B58412616E2: client=unknown[1.1.1.1], sasl_method=PLAIN, sasl_username=username@domain.com

**Comment by sebres** [comment]
I don't think, that is easy to build a tricky action to ban a user. Because regular fail2ban bans an IP-addresses only.

If you want this (really IP - also `1.1.1.1`, not a user), just create own regular expression to parse a given lines, like in example below (not tested):
```
# jail.local:
[postfix-ban-spammer]
filter   = postfix
port     = smtp,465,submission
logpath  = %(postfix_log)s
failregex = ^%(__prefix_line)s(?:\S+:+\s+)?client=\S+\[<HOST>\],\s+.+username=[^@\s]+@[^@\s]+$
maxretry = 10
findtime = 60
...
```

But, if you really want to disallow an users to send mails, you should create own action and define own ban/unban rules inside it (ex.: like shell commands).
Theoretically it is possible (but for this I know postfix not so good).

**Comment by nikolas22t** [comment]
That was mistype , i want to block an ip , if the user sends for example 10 emails in 60 seconds

**Comment by johnpatcher** [comment]
Why don't you use the policy interface of Postfix [1]? There are a couple of policy server [2], which would be helpful in your case.

[1]: http://www.postfix.org/SMTPD_POLICY_README.html

**Comment by nikolas22t** [comment]
to be honest i tried it but didn't like it

**Comment by johnpatcher** [comment]
What does "didn't like it" mean? It is probably the right (TM) solution, since banning on an IP level might also ban wrong users. Someone who knows what he is doing can probably also come up with a new IP to send out another 10 mails ;). When you're authenticating users, ban them on this ground, not on their IP address.

**Comment by nikolas22t** [comment]
I have like 10000 users and only the spammers do so many connections in that short time

**Comment by yarikoptic** [comment]
may be whenever someone addresses #67 smth like what you need @nikolas22t could be implemented, but unfortunately currently, as @sebres noted already, I also don't see a way.  Thus I just maked it as wontfix and will close it.  Feel free to continue the discussion, I just don't want lingering it around since we aren't much of help for you here

**Comment by mgrennan** [comment]
Follow these instructions - 
http://zach.seifts.us/posts/2013/07/14/how-make-fail2ban-bans-persistent
http://vavai.net/2011/10/tips-improving-zimbra-mail-server-security-with-fail2ban/

Then add this script to cron:

wget http://www.spamhaus.org/drop/drop.txt
cat drop.txt | awk '{print $1}' | grep -v ';' > /etc/fail2ban/ip.blacklist 
rm drop.txt
service fail2ban restart

And you will start with a list of know spammers then build a list as new IPs show up.

**Comment by donttrustem** [comment]
How would you add that script to cron?
something like wget http://www.spamhaus.org/drop/drop.txt & cat drop.txt | awk '{print $1}' | grep -v ';' > /etc/fail2ban/ip.blacklist & rm drop.txt & rm drop.txt
